### ISSUE TITLE
Install doesn't work

### ISSUE THREAD

**Issue by Betaman2k** [FezVrasta/ark-server-tools#10]
Heya

OS: Debian 64

I used ur script, i install and downloading the game ~17 GB
i wanna start the game server, but the game server wanna start the server,  no error logs nothing, no session is running.
I wanna stop the server 
arkmanager stop
No screen session found.

what is wrong ?
cya
betaman

**Comment by FezVrasta** [comment]
the start/stop functions are not yet tested, give us time

**Comment by rakeleer** [comment]
In arkmanager.cfg - akrserverapass should be arkserverapass, and /usr/bin/arkmanager doesn't like the entire path/binary/arguments in one string. I'm not familiar with github and contributing, unfortunately.

55
<     screen -dmS "$servicename" "$thejob"
---
>     screen -dmS "$servicename" "$arkserverroot/$arkserverexec" "$arkserveropts"

**Comment by Atriusftw** [comment]
The start command should be fixed as of 2ff1ac081a40dbb6e811c6bd93c0bb4f53280767

**Comment by FezVrasta** [comment]
fixed config typo, thanks rakeleer!
