### ISSUE TITLE
Ship 1.2 - create 1.3-dev with RCON support.

### ISSUE THREAD

**Issue by Atriusftw** [FezVrasta/ark-server-tools#100]
We should ship 1.2 asap, and make 1.3-dev branch with RCON support. Any thoughts?

Ping @FezVrasta, @Sispheor, @klightspeed

**Comment by Sispheor** [comment]
Yep, we have to discuss about new features.

- arkmanager save   --> RCON save world
- arkmanager broadcast   --> RCON broadcast
- arkmanager update  (update the code to use save function before stop)
- arkmanager status   --> update the code to get number of currently
connected players, list name and steam id with RCON


What do you think about that? Any other idea?



2015-07-08 16:28 GMT+02:00 Marius Linge <notifications@github.com>:

> We should ship 1.2 asap, and make 1.3-dev branch with RCON support. Any
> thoughts?
>
> Ping @FezVrasta <https://github.com/FezVrasta>, @Sispheor
> <https://github.com/Sispheor>, @klightspeed
> <https://github.com/klightspeed>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/100>.
>



-- 
*Nicolas MARCQ*

**Comment by Atriusftw** [comment]
Definitely. Lets use this thread for such.

My suggestions;

* Broadcasts before update (Maybe configurable to let the user decide the interval?)
* List players
* Kick/Ban players

**Comment by Sharkking** [comment]
if possible use a xml scheduler configuration (like discontinued BEC for Arma www.ibattle.org)
http://forums.bistudio.com/showthread.php?180125-B-E-C-quot-Battleye-Extended-Controls-quot-Admin-tool-for-dedicated-servers

**Comment by Atriusftw** [comment]
Regarding RCON:

As of right now, the server console isn't interactive.
Version 185.0 only adds the RCON Protocol, which means that you will have to use an external RCON client to access in-game commands.

**Comment by Sispheor** [comment]
There is a python lib from valve.
http://python-valve.readthedocs.org/en/latest/rcon.html

**Comment by Atriusftw** [comment]
@Sispheor That looks pretty sweet.

**Comment by klightspeed** [comment]
What are your thoughts on the RCON implementation in 1a57576, and the server query in 47b0792

**Comment by Atriusftw** [comment]
@klightspeed Looks absolutely brilliant to me!

**Comment by FezVrasta** [comment]
@klightspeed very nice, I'd prefer a perl implementation rather than python, but I think it will be good as well...

**Comment by FezVrasta** [comment]
created 1.3-dev branch and shipped 1.2

**Comment by Atriusftw** [comment]
:+1:
