### ISSUE TITLE
need help with ubuntu permission and winscp

### ISSUE THREAD

**Issue by badboysgaming** [FezVrasta/ark-server-tools#1013]
getting this when i try to edit any file 
`Permission denied.
Error code: 3
Error message from server: Permission denied`i have tried as default user and created user still can't edit files via winscp

**Comment by klightspeed** [comment]
Is the user you're logging into the server as the same user as that under which the game server is running?

**Comment by badboysgaming** [comment]
yes have tried multiple times haven't even got server installed yet because i'm unable to edit the main or arkmanager.cfg

**Comment by klightspeed** [comment]
Please check the owner and permissions on those files.  They should be owned by the user you specified when installing arkmanager.

**Comment by badboysgaming** [comment]
not sure how but i managed to get it working correctly haven't ran ark tools since 2016 little rusty at it lol
