### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by Keyn-Thror** [FezVrasta/ark-server-tools#1018]
After April 28 my arkmanager doesn't download mods and fails to update the server.

When I run ./arkmanager installmod <modid>, I get the error: 
Mod <modid> was not successfully downloaded

and it happens with all mods I'm trying to install or update

Today, May 3, I tried to run ./arkmanager update, and the update never finishes.
I just get the "Performing ARK update ..." that is running forever.

I'm using Arkmanager 1.6.46 version right now
Tried older version - same problem.

**Comment by klightspeed** [comment]
What is the output of `./arkmanager update --verbose`?

**Comment by Keyn-Thror** [comment]
> What is the output of `./arkmanager update --verbose`?

$ ./arkmanager update --verbose
Running command 'update' for instance 'main'
Checking for update; PID: 34577
The server is already stopped
Performing ARK updateExecuting /home/steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +force_install_dir /home/steam/ARK +app_update 376030 +quit
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Downloading update (0 of 49,677 KB)...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
"@NoPromptForPassword" = "1"

**Comment by klightspeed** [comment]
If that is all, then steamcmd is very broken.

**Comment by Keyn-Thror** [comment]
> If that is all, then steamcmd is very broken.

Yeah, I just tried to update steamcmd and got this:

$ ./steamcmd.sh

Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Failed to apply update, reverting...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.

**Comment by Keyn-Thror** [comment]
Got this error in one of update attempts:
Loading Steam API...applicationmanager.cpp (3335) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
applicationmanager.cpp (3335) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
applicationmanager.cpp (3498) : Assertion Failed: m_vecInstallBaseFolders.Count() > 0

**Comment by klightspeed** [comment]
How does it go if you try to re-install steamcmd (basically delete or move the old steamcmd directory, and re-extract steamcmd)?

**Comment by Keyn-Thror** [comment]
Wow... my Debian 8 doesn't find steamcmd in repositories at all...

$ sudo apt-get install -f steamcmd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package steamcmd

**Comment by klightspeed** [comment]
(basically delete or move the old steamcmd directory, and re-extract steamcmd)?

**Comment by Keyn-Thror** [comment]
Yeah, I managed to reinstall SteamCMD and the Arkmanager works fine now.
Thank you very much for help!
