### ISSUE TITLE
Backup command creates the backup directory but no backup

### ISSUE THREAD

**Issue by Rob-bb** [FezVrasta/ark-server-tools#1031]
issuing the 'arkmanager backup' command will go through the motions, it will create the backups directory specified in the config, compress the files and say it created a backup, but the backups directory is empty.  

Where is it creating the backup?

**Comment by sphbecker** [comment]
Check arkmanager.cfg for the location, here is the default...
arkbackupdir="/home/steam/ARK-Backups"

**Comment by Rob-bb** [comment]
As I mentioned in the original post, it will create the backup dir specified in the config if it does't exist but the back file is not placed in that directory.

**Comment by klightspeed** [comment]
It should store the backup `yyyy-mm-dd_hh.mm.ss.tar.bz2` in a `yyyy-mm-dd` directory in the backup directory.

Does it show `[   OK   ]` for each of the steps it does?

**Comment by Rob-bb** [comment]
Yes it does, ignore me I am being dumb.
