### ISSUE TITLE
arkCpuAffinity use taskset for the wrong process

### ISSUE THREAD

**Issue by LotekHeavy** [FezVrasta/ark-server-tools#1036]
I set arkCpuAffinity=8,9 (I have 14 cores) and only the arkmanager receives the cpu affinity and not the ShooterGameServ. Right?

Example:
ark@wintermute:~/etc$ cat arkmanager/instances/island.cfg

```
# config environment
arkserverroot="/home/ark/island"                                     # path of your ARK server files (default ~/ARK)
arkCpuAffinity=8,9

```
27777 ark       20   0 9090276 5,862g  64624 S  26,7  9,3   4:43.48 ShooterGameServ

```
ark@wintermute:~/etc$ taskset -pc 27777
aktuelle Bezugsliste für PID 27777: 0-13
```

27756 ark       20   0   19304   8488   2148 S   0,0  0,0   0:01.10 arkmanager

```
ark@wintermute:~/etc$ taskset -pc 27756
aktuelle Bezugsliste für PID 27756: 8,9
```

**Comment by klightspeed** [comment]
This sounds like either the game server is changing its own CPU affinity, or `kill -STOP $BASHPID` isn't working to suspend the process until the process priority or CPU affinity are set.

Does `taskset -c 8,9 arkmanager start @instance` carry the CPU affinity through to the server?

**Comment by klightspeed** [comment]
798e5de should fix this.
