### ISSUE TITLE
.ark-update.lock: No such file or directory

### ISSUE THREAD

**Issue by W4nn4be** [FezVrasta/ark-server-tools#1041]
Hi there,

i was running a cluster, which was set up with arkmanager. Haven´t touched that server for several months now. 2 days ago we decided to revive it, but i doesnt start or update at all.
Tried to fix it by myself, but i am pretty lost right now.

Right now, it is:
Version: 1.6
Channel: master
Release Tag: v1.6.42

As soon as i try to "arkmanager start" or "arkmanager update" console is spamming:
/usr/local/bin/arkmanager: line 1785: /home/ark/ARK/ShooterGame/Saved/.ark-update.lock: No such file or directory 

Additionaly getting some error report, when using some commands

[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
[  ERROR  ]     You have not rights to write in the log directory.

So i tried to set folder owner and read/write access for the user. Either it didnt work or didnt affect it at all.
Not sure what it caused to behave it like that, but last time the cluster was running everything was fine.
As mentioned above, haven't touched the arkmanager for a few months, i would appreciate every hint in order to solve this. 

TY

**Comment by W4nn4be** [comment]
NVM Whiped it. RIP breedings

**Comment by garzj** [comment]
This happened to me as well, when I rsync'd my data to a new server. I run arkmanager inside a docker container, so I don't have the `steam` user on the machine itself and rsync changed my files to another user id.

So for anyone having this issue, try running `chown -R steam:steam ark-server` on the folder (or use the user and group id inside the container, in my case 1000).

**Comment by klightspeed** [comment]
> This happened to me as well, when I rsync'd my data to a new server. I run arkmanager inside a docker container, so I don't have the `steam` user on the machine itself and rsync changed my files to another user id.

Since the `steam` user would not have existed on the destination machine, `rsync` would have copied the numeric user ids.

**Comment by garzj** [comment]
I think it's because on the old host machine, there was another user occupying id 1000. On the new machine there is a user with the same name but another user id.

**Comment by garzj** [comment]
Ok I tried it and you're right. I used the `-a` option.

Either way, it works now.
