### ISSUE TITLE
Update says it completes but no update was performed

### ISSUE THREAD

**Issue by cabyio** [FezVrasta/ark-server-tools#1043]
I am running two servers in a cluster on one machine.  When I am trying to update them it looks like it is successful but the version number doesn't change.

[root@arkserver ~]# arkmanager update @main
Running command 'update' for instance 'main'
Checking for update; PID: 6350
The server is already stopped
Performing ARK update ... Update to 4205769 complete

Afterwords I check the version and it is the old version 298.41.  I can run the command over and over and it keeps detecting an update and saying it completed it but nothing changes.

**Comment by klightspeed** [comment]
What does the following command give:

arkmanager --verbose update @main

**Comment by BigMikJ** [comment]
This has been happening on the last 3 updates I've received about ARK. Cannot auto update. Have to manually download to staging dir with "app_update 376030 validate" then apply to each instance.

[root@NUKEAPP02 Steam]# arkmanager --verbose update @aberration 
Running command 'update' for instance 'aberration'
Checking for update; PID: 26840
Downloading ARK updateExecuting /app_data/home/steam/Steam/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +force_install_dir /app_data/ark/staging +app_update 376030 +quit
Redirecting stderr to '/app_data/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
ERROR! Timed out waiting for AppInfo update.
Stopping server; reason: update
The server has been stopped

**Comment by klightspeed** [comment]
> ERROR! Timed out waiting for AppInfo update.

The suggestion from <https://www.reddit.com/r/playrust/comments/c3q3zh/error_timed_out_waiting_for_appinfo_update/> to delete the appinfo.vdf and packageinfo.vdf from `~/Steam/appcache`, it would appear you have `steamcmd_appinfocache` pointing at the wrong file.  In your case it looks like you should set:

```
steamcmd_appinfocache="/app_data/home/steam/Steam/appcache/appinfo.vdf"
```

**Comment by cabyio** [comment]
Okay, I ran the command and got this output:

`
[steam@arkserver ~]$ arkmanager --verbose update @main
Running command 'update' for instance 'main'
Checking for update; PID: 120595
The server is already stopped
Performing ARK updateExecuting /home/steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +force_install_dir /home/steam/ARK +app_update 376030 +quit
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
ERROR! Timed out waiting for AppInfo update.
Update to 4205769 complete
`

Tried to delete the vdf files and got the same result.

**Comment by cabyio** [comment]
Okay, I seem to have fixed it.  It seems that is was the steamcmd that was borked because I couldn't even get it to manually install other games.  Not sure what was borked but a yum update seems to have made it happy again.
