### ISSUE TITLE
arkwarnminutes vs msgWarnUpdateMinutes

### ISSUE THREAD

**Issue by theEvil007** [FezVrasta/ark-server-tools#1047]
Hi,

I've set arkwarnminutes to 30 minutes, but in discord messages it shows 60 minutes to restart.

Did I the mistake, or is it a bug?

**Comment by klightspeed** [comment]
If you run `arkmanager printconfig @instance`, check the file that it lists as having the `arkwarnminutes` setting.

**Comment by theEvil007** [comment]
Yeahh, have it.
My instance uses some settings out of .arkmanager.cfg in home-dir of the user and some other settings out of /etc/arkmanager/arkmanager.cfg

Can I fix it by myself or do I have to edit the cfg in home-dir manually?

**Comment by klightspeed** [comment]
The fact that you have configs in both places suggests you barged past the following warning when doing the user-install:

```
You have requested a user-install.  You probably don't want this.
A user-install will create ~/.config/arkmanager/instances/main.cfg
This config file will override /etc/arkmanager/instances/main.cfg
Add --perform-user-install if you really want this.
```

Just delete the `~/.config/arkmanager` directory if you don't want it.

**Comment by theEvil007** [comment]
Thanks for the advice. I had to read carefully. Now it works fine.
