### ISSUE TITLE
Instance names in discord messages

### ISSUE THREAD

**Issue by theEvil007** [FezVrasta/ark-server-tools#1048]
Hi,

I've removed the main.cfg complete, but when I use the param @all to restart or something else, always it shows that there is no relation to instance main.

It would be great to have the possibility to name the instances in config files. I don't want to have a config called main, only config files named to the map e.g.

**Comment by klightspeed** [comment]
What is the exact error message?

Note that instance names come from the following:

- `<instancename>.cfg` in `/etc/arkmanager/instances`
- `<instancename>.cfg` in `~/.config/arkmanager/instances`
- `configfile_<instancename>=<filename>` in `/etc/arkmanager/arkmanager.cfg` or `~/.arkmanager.cfg`

**Comment by theEvil007** [comment]
When I do a list-instances I got this: @main: Error: no config files for instance main

Maybe related to the fact that instance config files using settings from /etc/arkmanager/arkmanager.cfg AND ~/.arkmanager.cfg !?

**Comment by klightspeed** [comment]
Is `defaultinstance` set in either of those files?

**Comment by theEvil007** [comment]
Thank you very much. When using the correct cfg-file it will work fine
