### ISSUE TITLE
Inconsistent casing in map name - Ragnarok.ark does not exist, but  does

### ISSUE THREAD

**Issue by ventra007** [FezVrasta/ark-server-tools#1049]
Hello everyone,

I'm attempting to launch multiple maps in a cluster and i'm getting the above error when launching either Ragnarok, TheCentre or Aberration.

In each instance config I've added the map name as both Ragnarok and "_P" variants of all of them and each time I get the error above for both ie. Aberration and Aberration_P etc.

Is this something to be concerned about or am I doing something wrong?

Many thanks

**Comment by klightspeed** [comment]
Is the ark file in `ShooterGame\Saved\SavedArks` named `Ragnarok.ark` or `ragnarok.ark` or some other combination of case?

**Comment by ventra007** [comment]
Hi klightspeed,
Thank you for attending to this.

The file name in that directory is `ragnarok.ark`

**Comment by klightspeed** [comment]
Makes me wonder if Wildcard has changed the game saving to lower-case the map name when saving a new world map.

**Comment by ventra007** [comment]
My apologies, I meant to capitalize the letter. The filename is `Ragnarok.ark`
Sorry.

**Comment by klightspeed** [comment]
Linux is case-sensitive.

Please copy and paste the exact warning, the exact map name, and the exact filename from `ShooterGame\Saved\SavedArks`

**Comment by ventra007** [comment]
Ok. So it seems i'm not being entirely scientific tackling this issue.

While reporting this issue I launched the ShooterGameServer without arkmanager and used the Ragnarok?listen command line parameter which created the Ragnarok.ark file in the SavedArks directory, which now resolved this particular issue.

If I try a brand new instance for TheCentre, the .ark file isn't created or downloaded automatically.
Here is the error output:

root@ark-survival:/home/ark/server/ShooterGame/Saved/SavedArks# arkmanager start @the-centre
Running command 'start' for instance 'the-centre'
Checking for updates before starting
Checking for update; PID: 2009
The server is already stopped
\033[0;39m Saved arks directory is /home/ark/server/ShooterGame/Saved/SavedArks
 Copying ARK world file (TheCenter) cp: cannot stat '/home/ark/server/ShooterGame/Saved/SavedArks/TheCenter.ark': No such file or directory
cp: cannot stat '/home/ark/server/ShooterGame/Saved/SavedArks/TheCenter.ark': No such file or directory
cp: cannot stat '/home/ark/server/ShooterGame/Saved/SavedArks/TheCenter.tmp': No such file or directory
\033[0;39m\e[68G[ \033[1;31mFAILED\033[0;39m ]
Inconsistent casing in map name - TheCenter.ark does not exist, but  does
 Copying ARK profile files
   76561197988942275.arkprofile                                    [   OK   ]
   76561197989008588.arkprofile                                    [   OK   ]
 Copying ARK tribe files
 Copying ARK tribute tribe files
 Copying GameUserSettings.ini                                      [   OK   ]
 Copying Game.ini                                                  [   OK   ]
 Compressing Backup                                                [   OK   ]
 Created Backup:  the-centre.2019-11-28_08.45.01.tar.bz2
Updating mod 731604991
Copying files to /home/ark/ARK-Staging/Mods/731604991
cp: cannot create hard link '/home/ark/server/ShooterGame/Content/Mods/731604991/./__modversion__.info' to '/home/ark/ARK-Staging/Mods/731604991/./__modversion__.info': Permission denied
cp: cannot create hard link '/home/ark/server/ShooterGame/Content/Mods/731604991/./__arkmanager_modbranch__.info' to '/home/ark/ARK-Staging/Mods/731604991/./__arkmanager_modbranch__.info': Permission denied

Also been getting these permission issues, but doesn't seem to affect the server running.

Directory Listing:

root@ark-survival:/home/ark/server/ShooterGame/Saved/SavedArks# ll -h
total 1.2G
drwxr-xr-x 2 ark ark 4.0K Nov 28 08:44 ./
drwxr-xr-x 6 ark ark 4.0K Nov 28 08:46 ../
-rw------- 1 ark ark 3.5K Nov 27 13:35 76561197988942275.arkprofile
-rw------- 1 ark ark 3.5K Nov 27 13:33 76561197988942275.profilebak
-rw------- 1 ark ark  12K Nov 27 15:24 76561197989008588.arkprofile
-rw------- 1 ark ark 8.8K Nov 27 15:08 76561197989008588.profilebak
-rw------- 1 ark ark  50M Nov 28 08:44 Ragnarok_AntiCorruptionBackup.bak
-rw------- 1 ark ark  50M Nov 28 08:27 Ragnarok.ark
-rw------- 1 ark ark  35M Nov 26 17:23 TheIsland_26.11.2019_17.23.43.ark
-rw------- 1 ark ark  35M Nov 26 17:31 TheIsland_AntiCorruptionBackup.bak
-rw------- 1 ark ark  35M Nov 26 17:32 TheIsland.ark
-rw------- 1 ark ark  35M Nov 26 17:32 TheIsland_NewLaunchBackup.bak
-rw------- 1 ark ark  60M Nov 26 21:14 Valguero_P_26.11.2019_21.14.53.ark
-rw------- 1 ark ark  60M Nov 26 23:24 Valguero_P_26.11.2019_23.24.53.ark
-rw------- 1 ark ark  60M Nov 27 01:34 Valguero_P_27.11.2019_01.34.53.ark
-rw------- 1 ark ark  60M Nov 27 03:44 Valguero_P_27.11.2019_03.44.53.ark
-rw------- 1 ark ark  60M Nov 27 05:54 Valguero_P_27.11.2019_05.54.53.ark
-rw------- 1 ark ark  60M Nov 27 08:04 Valguero_P_27.11.2019_08.04.53.ark
-rw------- 1 ark ark  60M Nov 27 18:48 Valguero_P_27.11.2019_18.48.59.ark
-rw------- 1 ark ark  60M Nov 27 20:58 Valguero_P_27.11.2019_20.58.59.ark
-rw------- 1 ark ark  60M Nov 27 23:08 Valguero_P_27.11.2019_23.08.59.ark
-rw------- 1 ark ark  60M Nov 28 01:18 Valguero_P_28.11.2019_01.18.59.ark
-rw------- 1 ark ark  60M Nov 28 03:28 Valguero_P_28.11.2019_03.28.59.ark
-rw------- 1 ark ark  60M Nov 28 05:38 Valguero_P_28.11.2019_05.38.59.ark
-rw------- 1 ark ark  60M Nov 28 08:45 Valguero_P_AntiCorruptionBackup.bak
-rw------- 1 ark ark  60M Nov 28 06:41 Valguero_P.ark
-rw------- 1 ark ark  60M Nov 27 16:58 Valguero_P_NewLaunchBackup.bak

So from this I see that I have some sort of permission error, arkmanager application doesn't have write permission to the folder :(

**Comment by klightspeed** [comment]
You are running the command as root, so it is dropping privileges to the `steamcmd_user` specified in `/etc/arkmanager/arkmanager.cfg`

Does it work if you instead log in as the `ark` user and try running the commands?

**Comment by ventra007** [comment]
Get the same error:

ark@ark-survival:~$ arkmanager start @the-centre
Running command 'start' for instance 'the-centre'
Checking for updates before starting
Checking for update; PID: 29829
The server is already stopped
\033[0;39m Saved arks directory is /home/ark/server/ShooterGame/Saved/SavedArks
 Copying ARK world file (TheCenter) cp: cannot stat '/home/ark/server/ShooterGame/Saved/SavedArks/TheCenter.ark': No such file or directory
cp: cannot stat '/home/ark/server/ShooterGame/Saved/SavedArks/TheCenter.ark': No such file or directory
cp: cannot stat '/home/ark/server/ShooterGame/Saved/SavedArks/TheCenter.tmp': No such file or directory
\033[0;39m\e[68G[ \033[1;31mFAILED\033[0;39m ]
Inconsistent casing in map name - TheCenter.ark does not exist, but  does
 Copying ARK profile files
   76561197988942275.arkprofile                                    [   OK   ]
   76561197989008588.arkprofile                                    [   OK   ]
 Copying ARK tribe files
 Copying ARK tribute tribe files
 Copying GameUserSettings.ini                                      [   OK   ]
 Copying Game.ini                                                  [   OK   ]
 Compressing Backup                                                [   OK   ]
 Created Backup:  the-centre.2019-11-28_09.18.53.tar.bz2
Updating mod 731604991
Copying files to /home/ark/ARK-Staging/Mods/731604991
cp: cannot create hard link '/home/ark/server/ShooterGame/Content/Mods/731604991/./__modversion__.info' to '/home/ark/ARK-Staging/Mods/731604991/./__modversion__.info': Permission denied

would I need to add the ark user to the root group?

**Comment by klightspeed** [comment]
As root, try running the following command to fix up permissions, then try again:
```
chown -R ark:ark /home/ark/server
```

**Comment by klightspeed** [comment]
Also make sure that either each server runs in its own directory or that each server has a separate `AltSaveDirectoryName`

**Comment by ventra007** [comment]
OK great, so no more errors, and all saving in their own directories. Thank you.
