### ISSUE TITLE
Updating arkmanager?

### ISSUE THREAD

**Issue by StuartWhelan** [FezVrasta/ark-server-tools#105]
When the next release of arkmanager is available, do we just 'curl -sL http://git.io/vtf5N | sudo bash -s steam' again?

Can I suggest an updatescripts command to update arkmanger itself, like we can with the 7 days to die server manager?

**Comment by Q11x** [comment]
There have already been added a way to automatically upgrade arkmanager with a arkmanager command in the 1.2-dev branch. 
It will be added to master when they think the branch is ready.

**Comment by Atriusftw** [comment]
As @Q11x says - we already have that ready in 1-2-dev which is probably going to be merged into master sometime within this week.

Apart from this, our focus right now will be to implement RCON into arkmanager.
