### ISSUE TITLE
Mod Install problem

### ISSUE THREAD

**Issue by Badbob007** [FezVrasta/ark-server-tools#1053]
Hello and first thank you for helping. I am a new user to server infrastructure in Linux and I've followed some tutorials on setting up my own Ark dedicated server. Over the course of two weeks I've encountered numerous different suggestions on how to get mods to work and found my way here to use Ark Manager. Now I had some challenges to get Ark Manager configured for my Ark Server, but I've worked through them. I am still encountering challenges with the command arkmanager installmods. Here is the error I am receiving.

```
ark@robert-MS-7968:~$ arkmanager installmods
Running command 'installmods' for instance 'Boblandia'
Downloading mod 702828089 ... -/usr/lib/games/steam/steamcmd.sh: line 29: /usr/lib/games/steam/linux32/steamcmd: No such file or directory
Mod 702828089 download failed
Mod 702828089 was not successfully downloaded
Downloading mod 731604991 ... -/usr/lib/games/steam/steamcmd.sh: line 29: /usr/lib/games/steam/linux32/steamcmd: No such file or directory
Mod 731604991 download failed
Mod 731604991 was not successfully downloaded
Downloading mod 741203089 ... -/usr/lib/games/steam/steamcmd.sh: line 29: /usr/lib/games/steam/linux32/steamcmd: No such file or directory
Mod 741203089 download failed
Mod 741203089 was not successfully downloaded
Downloading mod 895711211 ... -/usr/lib/games/steam/steamcmd.sh: line 29: /usr/lib/games/steam/linux32/steamcmd: No such file or directory
Mod 895711211 download failed
Mod 895711211 was not successfully downloaded
ark@robert-MS-7968:~$
```

At first I assumed it was due to not having the lib32gcc1 installed, but when running sudo apt-get install lib32gcc1 it tells me it is already installed. Any suggestions? I've reviewed the config files and looked for line 29 or any reference to it pointing to the path /usr/lib/games/steam/linux32 and not finding anything except the command installmods referencing it when attempting the install.

Thanks for any help in advance!

**Comment by klightspeed** [comment]
> ```
> /usr/lib/games/steam/steamcmd.sh: line 29: /usr/lib/games/steam/linux32/steamcmd: No such file or directory
> ```
That is line 29 in `/usr/lib/games/steam/steamcmd.sh`

Does `/usr/lib/games/steam/linux32/steamcmd` exist?
Does `/lib/ld-linux.so.2` exist?

**Comment by Badbob007** [comment]
/usr/lib/games/steam/steacmd.sh does not exist
/lib/ld-linux.so.2 does exist

**Comment by klightspeed** [comment]
Is the `steamcmd` package installed?

**Comment by Badbob007** [comment]
Yes it is. I ran through the walkthrough off the official Steam site. I've also been running the server fine except for Mods. I decided to install mods which is how I've come to this arkmanager tool.

**Comment by klightspeed** [comment]
The `steamcmd` package that Ubuntu installs is out of date, and always tries to update itself.

Your best bet would be to either try the manual install, or:
* Create a `steamcmd` directory in your home directory
* Copy `/usr/lib/games/steam/steamcmd.sh` to that directory
* Create a `linux32` directory in that `steamcmd` directory
* Copy `/usr/lib/games/steam/steamcmd` to that directory
* Change `steamcmdroot` to that `steamcmd` directory in your arkmanager config.

**Comment by Badbob007** [comment]
That worked! Thanks for your help.
