### ISSUE TITLE
multiple instances in the same cluster - game crashs

### ISSUE THREAD

**Issue by christian1211** [FezVrasta/ark-server-tools#1054]
Hello all,

I just set up my ARK server a few days ago with ark-server-tools on my Debian 10 server. As long as I had only one instance, everything works fine. Since I added a second instance, a problem appears. Both instances seems starting without issues but when I try to join one of them (doesn't matter which one) with my client, the game crashes. When I start only one, join the server with the client and start the other one after, I can still play. But when I quit and want to join again, the error appears. When I start only one of the instances (doen't matter which one), everything works fine again. Same behavior on a second client. I guess it's my own fault but I can't find the mistake.

Some configs:

/etc/arkmanager/arkmanager.cfg: https://pastebin.com/aBmZzg8L
/etc/arkmanager/instances/TheIsland.cfg: https://pastebin.com/ZB0LsCuK
/etc/arkmanager/instances/ScorchedEarth.cfg: https://pastebin.com/BuWSy1F7

The error on client side when the game crashs: https://imgur.com/a/bRJljsZ

Would be great if someone has an idea...

Thank you.

**Comment by klightspeed** [comment]
It sounds like the mods from the two instances are incompatible.

Please try running the servers from separate directories (moving `arkserverroot` to the instance config), with `ark_ClusterDirOverride` set to the absolute path where the cluster shared files should reside.

`arkmanager` used to forbid instances from running from the same directory (and still does if `clusterid` is not set), but this prohibition was removed when cluster support was added to ARK and the developers recommended running cluster instances from the same directory.

Perhaps we should add a warning strongly discouraging running servers from the same directory.

**Comment by christian1211** [comment]
Both instances don't have any mods. I already tried it with two seperate game folders (with `arkserverroot` in instance config, like you said), same issue.

I read much stuff about this ark manager and it should be possible to use one game folder for more than one instance?

**Comment by klightspeed** [comment]
I wonder how many other people use the cluster name `MyARKCluster`?

Try setting `arkopt_clusterid` to a unique name (for example the output of `dd if=/dev/urandom bs=1 count=8 2>/dev/null | xxd -p`), and setting `arkopt_ClusterDirOverride` to an absolute path (e.g. `/home/steam/ARKCluster`)

> I read much stuff about this ark manager and it should be possible to use one game folder for more than one instance?

Running multiple instances from a single directory is possible, but has been known to cause issues.  It is recommended that you run each instance from its own directory.

From <https://github.com/FezVrasta/ark-server-tools/issues/989#issuecomment-448899384>:
> Using a single install directory was a hangover from between the introduction of clusters and the introduction of the ClusterDirOverride setting.
> 
> If the reason for the single install is due to disk space limitations, arkmanager can use a shared staging directory (on the same filesystem) and hardlinks to reduce the disk space taken.

**Comment by christian1211** [comment]
So, I changed back to single game folders, here my updated config:

/etc/arkmanager/arkmanager.cfg: https://pastebin.com/H9iZqiJL
/etc/arkmanager/instances/TheIsland.cfg: https://pastebin.com/5sQG1NT1
/etc/arkmanager/instances/ScorchedEarth.cfg: https://pastebin.com/ZVETw0e5

MyARKCluster was just an example, I had a more unique cluster name. Anyway now I changed it again.

```
steam@xxxxxxx:~/ARK$ ls -lah
insgesamt 24K
drwxrwx--- 6 root  steam   4,0K Jan 19 13:36 .
drwxrwx--- 6 root  system2 4,0K Jan 14 14:15 ..
drwxr-xr-x 7 steam steam   4,0K Jan 19 13:47 ScorchedEarth
drwxr-xr-x 2 steam steam   4,0K Jan 19 13:15 Shared
drwxr-xr-x 2 steam steam   4,0K Jan 19 13:36 Staging
drwxr-xr-x 7 steam steam   4,0K Jan 19 13:47 TheIsland
```

**Comment by klightspeed** [comment]
<https://steamcommunity.com/app/346110/discussions/0/1726450077665715386/>
First, what is your ping to the server?
Second, does reducing the maximum in-game browser ping help?

**Comment by christian1211** [comment]
Ping is around 15-20 usually (same internal network).
No, didn't help. I set it to 250 some days ago (I already found the post you posted) but still same behavior.

I have no possibility right now for checking it from outside my network but I guess the two servers are visible because all ports are opened.

**Comment by klightspeed** [comment]
So they're inside your network?  Are you trying to connect to them using the LAN server browser, or through the internet server browser?  Does the client still crash if you try to join using the Steam server browser or the join link outputted by `arkmanager status @instance`?

Do the servers have different passwords?

I'm not sure what else I can offer.

**Comment by christian1211** [comment]
Yes, inside my network.
I'm trying to connect in ARK server browser. I selected "LAN" and then the problem appears.
Sorry, what you mean by "Steam server browser"?
How can I use this link?
I didn't do much in Steam, sorry for this basic questions.

**Comment by christian1211** [comment]
Okay with the join link and in the ARK server browser (if I don't chose "LAN"!) it's working! **Thank you so much!** So seems the problem is that the server is in my internal network.

**Comment by klightspeed** [comment]
Very odd - when testing here with TheIsland and Ragnarok running with query ports 27016 and 27017, I could not reproduce the crash when using the LAN browser.

**Comment by christian1211** [comment]
I tried it with all of the maps. For me it was everytime the same. I also tried transferring a character from one server to the other and it's working without problems.
