### ISSUE TITLE
Empty "./Saved/SavedArks" folder created in arkserverroot

### ISSUE THREAD

**Issue by podostro** [FezVrasta/ark-server-tools#1057]
When I started the server with arkmanager start @all/@instance_name
it created an empty ./Saved/SavedArks directory on the arkserverroot path.

I figured the problem was around line 310, "# SavedArks directory"; when it checks if the directory is writeable; for some reason arkserverdir is probably unset.
ark_AltSaveDirectoryName seems to be unset too. 
Even though it's on my instance.cfg because I'm using a different one for each instance.
Maybe this code is being executed before reading the specific instance.cfg?

I added arkserverdir="ShooterGame" to my arkmanager.cfg file, and it creates the folder inside of ShooterGame (ShooterGame/Saved/SavedArks)

But still, it's an unused empty directory because my instances use each a different AltSaveDirectoryName

---
My server: Ubuntu 18.04 Server

I installed SteamCMD from apt package, and game from command line with force_install_dir "/home/steam/servers/ark"

arkmanager.cfg relevant contents
steamcmdroot="/home/steam"                                          # path of your steamcmd instance
steamcmdexec="steamcmd"                                             # name of steamcmd executable
steamcmd_user="steam"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/steam/.steam/appcache/appinfo.vdf"     # cache of the appinfo command
steamcmd_workshoplog="/home/steam/.steam/logs/workshop_log.txt"     # Steam workshop log

arkserverroot="/home/steam/servers/ark" 
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"

**Comment by klightspeed** [comment]
That suggests you have `arkserverroot` set in `arkmanager.cfg` rather than your instance config.

**Comment by podostro** [comment]
@klightspeed yes, as shown in the contents of my arkmanager.cfg

Since all my instances share the same binaries and .ini directories; the logical step is to set that var only once in the main .cfg instead of copying the same var with same value in each independent instance .cfg...
Only logical use for arkserverroot var in each of the instances' .cfg is to point each of them to different directories; in which case AltSaveDirectoryName is useless, since the root is already distinct, they may as well user their own default SavedArk directory

**Comment by klightspeed** [comment]
c116e12 should fix this.

**Comment by podostro** [comment]
awesome @klightspeed, just tried it on my server and it no longer creates the empty folder.
Odd how the script passes through there... Since I'm run "arkmanager start @instance_name", and not "arkmanager install" ... (in fact I haven't run it even once, since I had already installed the game server)

**Comment by klightspeed** [comment]
The directory check occurs if `install` is _not_ passed as the first argument to `checkConfig` and if `arkserverroot` is set.  The update adds the requirement that `instance` is set (i.e. the check is occurring while executing a command on an instance).

**Comment by podostro** [comment]
I fill dumb, didn't see the !=.
This is working nicely, I have updated server's script with this change and it's no longer creating the empty directory.
