### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by tenten36** [FezVrasta/ark-server-tools#106]
I just updated the arkmanager via curl -sL http://git.io/vtf5N | sudo bash -s steam and get 

steam@cloudsrv1:~$ arkmanager start
/usr/local/bin/arkmanager: Line 417: Syntaxfehler beim unerwarteten Wort »;«
/usr/local/bin/arkmanager: Line 417: `        else; then'

*sadface*

**Comment by FezVrasta** [comment]
please update arkmanager, there was a typo.
