### ISSUE TITLE
Displaying Port in webhook output like so.

### ISSUE THREAD

**Issue by Nytridr** [FezVrasta/ark-server-tools#1060]
notifyTemplate="Message from instance {instance} on server cosmicknights.com:{QueryPort} {msg}"
Right now this does not work.

What would I need to do to have it display the port also..

**Comment by klightspeed** [comment]
`${ark_QueryPort}` (making sure `notifyTemplate` is after where you define `ark_QueryPort`)

**Comment by Nytridr** [comment]
the notifytemplet is in arkmanager config but the ark_queryport is in the instances..  should I put the notify stuff in the instances and take it out of arkmanager.cfg?

**Comment by Nytridr** [comment]
I actually figured that out.  I was thinking of somehow importing but then I thought.. I already have it.  

The only thing that would ever change if you have DDNS or static IP would be the port.. 
notifyMsgServerUp="Server steam://connect/cosmicknights.com:${ark_QueryPort} is now up."
