### ISSUE TITLE
Questions: arkStagingDir for every instance or a single directory?

### ISSUE THREAD

**Issue by LotekHeavy** [FezVrasta/ark-server-tools#1062]
Can I run a central/same arkStagingDir for every instance OR do I need to have separate Staging Directories? 

I run 4 instances with the same mods only different maps and used in the past always a single / same directory for all my instances. But in the last few weeks a got a lot of "mod mismatch" error, where the mods on the server was not updated correctly. 

Thanks for help / clarification!

**Comment by klightspeed** [comment]
The staging directory should be able to be shared between instances.

Mods will also be extracted to the `Mods` directory in the staging directory, and copied or linked over to the instance's mods directory.  It's possible that the mods in the `Mods` directory in the staging directory were corrupt.  If those files were newer than the files downloaded by steamcmd, then they would not have been overwritten.

**Comment by LotekHeavy** [comment]
thx
