### ISSUE TITLE
arkGameUserSettingsIniFile / arkGameIniFile not working

### ISSUE THREAD

**Issue by garrowson** [FezVrasta/ark-server-tools#1065]
Just saw some amazing new config options.
Unfortunately I can't seem to get them to work.

I put arkGameUserSettingsIniFile and arkGameIniFile in each of my <myinstance>.config since I couldn't figure out where /path/to/instance was supposed to be.

But when I start my instances the config files are not being replaced at all.

arkmanager --version:
Version: 1.6
Channel: master
Commit: 36b8a3e
Release Tag: v1.6.49

**Comment by klightspeed** [comment]
The commit this was added in hasn't been put into a release yet.  It'll be in v1.6.50

**Comment by garrowson** [comment]
ok. thx!
