### ISSUE TITLE
Install error - Debian Buster

### ISSUE THREAD

**Issue by Azuna1** [FezVrasta/ark-server-tools#1066]
I'v a fresh install of debian Buster with a fresh steamcmd install following this https://developer.valvesoftware.com/wiki/SteamCMD#Linux

I'v installed all the mentioned Packages, most of them were already installed.
Issueing `curl -sL http://git.io/vtf5N | sudo bash -s steam`
Results in:

> Getting latest release...
> Latest release is v1.6.49
> Getting commit for latest release...
> Downloading installer
> Running install.sh
> Created symlink /etc/systemd/system/multi-user.target.wants/arkmanager.service → /etc/systemd/system/arkmanager.service.
> Ark server will now start on boot, if you want to remove this feature run the following line
> systemctl disable arkmanager.service
> **cp: cannot create regular file '/etc/bash_completion.d/arkmanager': No such file or directory**
> ARK Server Tools successfully installed
>

**Comment by klightspeed** [comment]
That error just means that /etc/bash_completion.d doesn't exist, and so the bash completion file wasn't installed.

I have fixed this in 94a8b96e74ddc8045cb6eee9355c7dd57df4d129

If you want bash completion:
```
mkdir -p /etc/bash_completion.d
wget "https://raw.githubusercontent.com/FezVrasta/ark-server-tools/master/tools/bash_completion/arkmanager" -O /etc/bash_completion.d/arkmanager
```
