### ISSUE TITLE
set settings that are suppose to be under a category from instance.cfg and/or arkmanager.cfg

### ISSUE THREAD

**Issue by Nytridr** [FezVrasta/ark-server-tools#1067]
How would we set something like this.

```
[StructuresPlus]
EnableQuickClimb=false
NoFoundationsRequired=false
AdditionalSupportDistanceInFoundations=5
```

Or does it even matter?

**Comment by klightspeed** [comment]
These are not settable on the command-line, so do not go into arkmanager's config files.  You will need to put them directly into GameUserSettings.ini
