### ISSUE TITLE
Feature request:  log file out put

### ISSUE THREAD

**Issue by Nytridr** [FezVrasta/ark-server-tools#1070]
logdir="/var/log/arktools"

be able to name the file.. something like

logfile="${serverMap}-${ark_QueryPort}.log"

have default the way you have it now, but in the instances allow renaming the log file to what you want.. 

Also I am not sure if there is a way to override the name of arks log files, but if there is you would be the one to ask, maybe..

**Comment by klightspeed** [comment]
You can override the log file name using `arkmanagerLog` or `arkserverLog` in the instance config - define those variables after defining the variables they reference.

e.g.
```
serverMap="Genesis"
ark_QueryPort="27016"
arkserverLog="${serverMap}-${ark_QueryPort}.log"
```

**Comment by Nytridr** [comment]
ty
