### ISSUE TITLE
issue with wait command 

### ISSUE THREAD

**Issue by tamasvincze** [FezVrasta/ark-server-tools#1071]
Hi there!

The itself is nice and sophisticated, tho i have a little issue.
I'd like to use the wait command (island is a working instance):
```
arkmanager wait --online @island
```
For this there's a little wait, then i get a message and the full help info for the tool:
> arkmanager v1.6: no command specified
> Usage: arkmanager [Commands]
> Commands can be followed by one or more @instance arguments
> The special '@all' instance selects all instances
> Commands may also be followed by zero or more --options
> <full list of commands>

Thanks,
Tamas

**Comment by klightspeed** [comment]
`wait` was expected to be used with another command.  ee7b81d11a90e472a186b223ac7ee54241f69a93 fixes this so it will exit without printing a help message if there are no other commands.

**Comment by tamasvincze** [comment]
Ah, i see.
Thank you for the fast reponse, i'm gonna close the ticket :)
