### ISSUE TITLE
/bin/bash: warning: shell level (1000) too high, resetting to 1

### ISSUE THREAD

**Issue by MarvinKlemp** [FezVrasta/ark-server-tools#1075]
On a fresh ubuntu 18.04 with the minimal setup:

```
apt-get update & apt-get upgrade
apt-get install perl-modules curl lsof libc6-i386 lib32gcc1 bzip2
apt-get install steamcmd

iptables -I INPUT -p udp --dport 27016 -j ACCEPT
iptables -I INPUT -p tcp --dport 27016 -j ACCEPT
iptables -I INPUT -p udp --dport 7778 -j ACCEPT
iptables -I INPUT -p tcp --dport 7778 -j ACCEPT
iptables -I INPUT -p tcp --dport 32330 -j ACCEPT

curl -sL http://git.io/vtf5N | sudo bash -s root

arkmanager --verbose install 
```

Just prints 
`/bin/bash: warning: shell level (1000) too high, resetting to 1`

**Comment by MarvinKlemp** [comment]
Closing this one. 

One of two possible fixes:
Adding a `steam` user instead of root

Exactly follow the installation manual of `steamcmd`

**Comment by klightspeed** [comment]
Probably should error out immediately if the `steamcmd_user=root`

* I'm running as root, let's try to drop privileges by re-executing as root
  * I'm running as root, let's try to drop privileges by re-executing as root
    * I'm running as root, let's try to drop privileges by re-executing as root
      * I'm running as root, let's try to drop privileges by re-executing as root
        * I'm running as root, let's try to drop privileges by re-executing as root
          - ... 993 steps later
            * I'm running as root, let's try to drop privileges by re-executing as root
              * I'm running as root, let's try to drop privileges by re-executing as root
                * Shell level >1000, giving up

**Comment by MarvinKlemp** [comment]
Yea that could be true.

Maybe we should add an error message. As nothing is displayed atm.
