### ISSUE TITLE
issuing commands to servers

### ISSUE THREAD

**Issue by Nytridr** [FezVrasta/ark-server-tools#1079]
is there any way to issue commands, like restart to all the servers with out having to wait for each server to go through the process?  trying to avoid having to open multiple putty sesstions to do all of them.   The @all is great but sometimes I just do not feel like waiting, if you know what I mean.

**Comment by klightspeed** [comment]
`arkmanager rconcmd @ALL saveworld rconcmd @ALL doexit` should save the world on all servers then restart (an exit that `arkmanager` did not directly initiate will be treated as an unexpected exit, and will cause the server to be restarted).  Note however that this will not take into account any changes to the config files.

**Comment by Nytridr** [comment]
neat, ty klightspeed
