### ISSUE TITLE
Looking for GameUserSettings.ini at wrong path and "ARK server exec not found"

### ISSUE THREAD

**Issue by mkelley88** [FezVrasta/ark-server-tools#1081]
I am trying to set up arkmanager in Ubuntu. I have my Ark server installed into the directory "/home/ark/server/" I edited the config file at `/etc/arkmanager/arkmanager.cfg` to reflect this. I set "arkserverroot" to "/home/ark/server". 

After saving the config, and running `arkmanager status` I get:

```
ark@arkserver:~$ arkmanager status
Running command 'status' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
 Server running:   No
/usr/local/bin/arkmanager: line 369: /home/ark/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini: No such file or directory
/usr/local/bin/arkmanager: line 369: /home/ark/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini: No such file or directory
 Server listening:   No
 Server build ID:
```
Unless I am misunderstanding something, it is looking for the ark server in "/home/ark/ARK" which is not what I set.

Here is my full config: [arkmanager.cfg.txt](https://github.com/FezVrasta/ark-server-tools/files/4380041/arkmanager.cfg.txt)

**Comment by klightspeed** [comment]
Did you do a user-install even though it warned you probably don't want it?  (unless of course you completely bypassed that by using `--perform-user-install`)
Do `~/.arkmanager.cfg` and `~/.config/arkmanager/instances/main.cfg` exist?  If so, then delete them.

**Comment by mkelley88** [comment]
I installed the Ark server and SteamCmd under the user "ark" on a fresh Ubuntu Server 18.04. 

I ran this command to install arkmanager:
`curl -sL http://git.io/vtf5N | sudo bash -s ark`

I wasn't asked to do a user install and no config files exist in those directories. I know it is reading from the config file at `/etc/arkmanager.cfg` because I made a change to correct the SteamCmd exec filename. I had to change "steamcmd.sh" to "steamcmd" and by doing so, it removed an error.

**Comment by klightspeed** [comment]
Please check `/etc/arkmanager/instances/main.cfg`

**Comment by mkelley88** [comment]
> Please check `/etc/arkmanager/instances/main.cfg`

Looks like this may have solved it. Thank you! I was not aware of this file and I don't understand how `/etc/arkmanager/instances/main.cfg` interacts with `/etc/arkmanager/arkmanager.cfg`. I see similar options in both files for "Ark server flags" and Ark server options". I would assume one of these files overrides the other? I am trying to use my existing game settings in `/home/ark/server/ShooterGame/Config/GameUserSettings.ini`.

**Comment by klightspeed** [comment]
Global settings go into `arkmanager.cfg`, while instance settings go into the instance config (e.g. `main.cfg` is for the `main` instance).
