### ISSUE TITLE
Upgrade command not functioning

### ISSUE THREAD

**Issue by TekThis** [FezVrasta/ark-server-tools#109]
steam@tekthis-alpha:~$ arkmanager upgrade
arkmanager v: Checking for updates...
/usr/local/bin/arkmanager: line 375: A new version was found! Do you want to upgrade ARK Server Tools to v${$arkstLatestVersion}?: bad substitution

**Comment by Atriusftw** [comment]
Did you update your config file aswell?

It looks like you're missing the version line in there.

**Comment by TekThis** [comment]
That's a big ten-four, it was the lack of version in the CFG.  Maybe a catch to clarify if it's not in the .cfg?

**Comment by Atriusftw** [comment]
We always encourage people to update their configuration when upgrading arkmanager, but we could add a function for that.
