### ISSUE TITLE
Server starting but Players 0 / 0

### ISSUE THREAD

**Issue by loulou1310** [FezVrasta/ark-server-tools#1095]
Hello,

I'm trying to setup an Ark Server (one instance) on a dedicated server running centos 7.
Everything seems fine until I run the status command :

> Running command 'status' for instance 'main'
 Server running:   Yes
 Server PID:   8995
 Server listening:   Yes
Server Name: MusketeersServer - (v310.68)
Players: 0 / 0
Active Players: 0
 Server online:   No
 Server build ID:   5036335

I've waited an hour and it doesn't change. When I go to my steam servers, it shows during around 1 second with the game name and 0/0 players then disappear. So I think it's not a firewall issue.
This is what i get for the used port :

> lsof -i -P -n
COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ShooterGa 8995 steam   10u  IPv4 392273      0t0  UDP *:27015
ShooterGa 8995 steam   16u  IPv4 394257      0t0  TCP *:32330 (LISTEN)
ShooterGa 8995 steam   18u  IPv4 391638      0t0  UDP *:7778

Can someone help me ?

**Comment by klightspeed** [comment]
`Server online: No` suggests that the server can't communicate with the Steam master server.
