### ISSUE TITLE
i screwed up my cluster and now its broken

### ISSUE THREAD

**Issue by warlordkn** [FezVrasta/ark-server-tools#1098]
2 problems.

1. i created a server cluster, went to an oblique and tried to do a transfer to another server.  the other server shows up and allowed me to switch. 
when the map loads in it forced me to make a new character.
Now if i try loading up the original map my character is gone. and that means all my structures, tames, and imprints are gone.

2. where could i have gone wrong that it allows me to see and join other servers but the characters are lost?

most importantly is there any way to recover my original character?

**Comment by warlordkn** [comment]
ok i fixed my character by forcing myself into the tribe, making myself the owner, and forcing the imprints onto me so im just gonna live with that.

however going back to the clusters.

here is my original configuration file

`# config environment
arkserverroot="/home/hostbox/ARK"                                     # path of your ARK server files (default ~/ARK)

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Ragnarok"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort="32330"                                                # RCON Port
ark_SessionName="***************"                                  # if your session name needs special characters please use the .ini instead
ark_Port="7778"                                                     # ARK server port (default 7778)
ark_QueryPort="27015"                                               # ARK query port (default 27015)
ark_ServerPassword="******"                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="*********"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="10"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true   
arkflag_NoBattleye=true                              # Uncomment to disable players from becoming spectators when they die

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
arkopt_ActiveEvent=Easter
arkflag_NoTransferFromFiltering=""
arkopt_clusterid=grease
#ark_PreventDownloadSurvivors=False
#ark_PreventDownloadItems=False
#ark_PreventDownloadDinos=False
#ark_PreventUploadSurvivors=False
#ark_PreventUploadItems=False
#ark_PreventUploadDinos=False
#ark_noTributeDownloads=false
arkopt_ClusterDirOverride=/home/ark/cluster

#arkPreStart="/etc/arkmanager/instances/instance.start"              # Set this to override the start script; defaults to config file name with .cfg replaced by .start`

**Comment by klightspeed** [comment]
Is the same cluster directory accessible by all of the instances in the cluster?  I think the cluster directory is used to transfer tributes (characters) and tames between instances.

**Comment by warlordkn** [comment]
im not sure exactly where the directory is.

i have arkopt_ClusterDirOverride=/home/ark/cluster

but when i goto that folder it remains empty even when i upload a survivor or a dino

**Comment by klightspeed** [comment]
Is `/home/ark/cluster` owned by the user under which the server is running?

`/home/hostbox/ARK` seems to suggest that you are running under docker - is `/home/ark/cluster` shared between the containers?

**Comment by warlordkn** [comment]
it is being run as the main user.  i diddnt create a special user to install this.

docker and containers are foreign concepts to me. so unless i have to explicitly set them up they shouldnt be there.

**Comment by warlordkn** [comment]
ok i looked both up.

i never installed docker so that shouldn't be a problem, and I've not explicitly set up any containers

**Comment by warlordkn** [comment]
ok i found the screw up (i think)

i forgot to put the username in the pathways for the cluster directory and the alt save directories.

i also decided to make separate installations for each map, to hopefully keep certain things cleaner. which may have been necessary anyway.
