### ISSUE TITLE
arkmanager start dont work

### ISSUE THREAD

**Issue by puseidr** [FezVrasta/ark-server-tools#11]
your script cant start the server

you are trying to start it with
`` "thejob="$arkserverroot/$arkserverexec $arkserveropts"``

but it should be like this: 
``thejob="$arkserverroot/ShooterGame/Binaries/Linux/$arkserverexec $arkserveropts"``

but anyway screen isn't starting with your script, don't know why..

**Comment by puseidr** [comment]
got it! 
you need to use the following command to start the game:
`` screen -dmS "$servicename" $thejob
``
instead of 
``screen -dmS "$servicename" "$thejob"
``

**Comment by FezVrasta** [comment]
ah thanks! good catch! fixed it

**Comment by puseidr** [comment]
but you need to fix this too:
``thejob="$arkserverroot/ShooterGame/Binaries/Linux/$arkserverexec $arkserveropts"``

**Comment by Atriusftw** [comment]
@puseidr That has been added in 2ff1ac081a40dbb6e811c6bd93c0bb4f53280767. Added it in the config to make the script look prettier.
