### ISSUE TITLE
Different Ark Server Root - You do not have rights to write in the defined ARK server root directory

### ISSUE THREAD

**Issue by StuartWhelan** [FezVrasta/ark-server-tools#110]
My arkserverroot is outside my steam dir.

My arkserverroot is /ssd/ark
My steamcmdroot is /home/steam

The /ssd folder is not owned by steam, but I do not think it should be.

The check on line 78 is checking the parent directory of the ark server root, not the ark server root itself.

**Comment by Atriusftw** [comment]
You can change your server root on [line 11] (https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager.cfg#L11) in the configuration file.

**Comment by StuartWhelan** [comment]
Sorry, I didn't make it clear.

Yes, server root is set to /ssd/ark.

[Here](https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L78) the script is checking permissions on the parent of the server root (in my case /ssd), not the server root itself (/ssd/ark)

**Comment by Atriusftw** [comment]
@StuartWhelan 

I don't have the opportunity to test now, but can you try editing [line 78](https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L78) in arkmanager to [this snippet](https://gist.github.com/Atriusftw/86510521d5bb174b54c3) and report back please?

**Comment by StuartWhelan** [comment]
Yes, that is the edit that I did to get it working, but I do not think it is a complete fix.

I am guessing that the check of the parent folder is done in order to check that an install will work.

I think the check before starting the install is valid. Something along the lines of:

If arkserverroot doesn't exist, then check if the parent is readable. 

If the parent is writable, create the arkserverroot.

If the parent is not readable, then exit with the error.

I will put up a pull request with those changes shortly.
