### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by lettucetrail** [FezVrasta/ark-server-tools#1102]
```
Running command 'run' for instance 'main'
start
Running /ark/server/ShooterGame/Binaries/Linux/ShooterGameServer Valguero_P\?MaxPlayers=70\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=password\?ServerPassword=password\?SessionName=world\?listen -log
/ark/server/ShooterGame/Binaries/Linux/ShooterGameServer: error while loading shared libraries: libEOSSDK-Linux-Shipping.so: cannot open shared object file: No such file or directory
Server PID: 3645
Bad PID ''; expected '3645'
exited with status 0
```

This was after an update for 311.78
Additionally before this i was unable to connect to the server and was timing out however now the server will not start

**Comment by CorsairF4U** [comment]
seems to have something to do with the ?bRawSockets being broken so disabling in the config?

**Comment by lettucetrail** [comment]
rawsockets isn't enabled in my config though?

`# --- USER CONFIG --- #
# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Valguero_P"                                          # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
ark_SessionName=${SESSIONNAME}                                  # if your session name needs special characters please use the .ini instead
ark_ServerPassword="password"                            # ARK server password, empty: no password required to login
ark_ServerAdminPassword=${ADMINPASSWORD}                        # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers=${NBPLAYERS}                                      # Number MAX of player
# ark_bRawSockets=""                                            # Uncomment if you want to use ark raw socket (instead of steam p2p) [Not recommended]
arkflag_log=""


# ----- Mods ----- #
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
# Mod OS Selection
mod_branch=Windows
# Add mod-specific OS selection below:
#mod_branch_496735411=Windows
# ----------------#

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
#arkflag_PreventSpawnAnimations=true
#arkflag_crossplay=false

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures
#arkopt_activeevent=easter

#ark_AltSaveDirectoryName="ValgueroSave"                                    # Uncomment to specify a different save directory name

# Update warning messages
# Modify as desired, putting the %d replacement operator where the number belongs
msgWarnUpdateMinutes="This ARK server will shutdown for an update in %d minutes"
msgWarnUpdateSeconds="This ARK server will shutdown for an update in %d seconds"
msgWarnRestartMinutes="This ARK server will shutdown for a restart in %d minutes"
msgWarnRestartSeconds="This ARK server will shutdown for a restart in %d seconds"
msgWarnShutdownMinutes="This ARK server will shutdown in %d minutes"
msgWarnShutdownSeconds="This ARK server will shutdown in %d seconds"

# config environment
arkwarnminutes="60"                                                 # number of minutes to warn players when using update --warn
arkBackupPreUpdate="true"                                          # set this to true if you want to perform a backup before updating

# Options to automatically remove old backups to keep backup size in check
# Each compressed backup is generally about 1-2MB in size.
arkMaxBackupSizeMB="500"                                            # Set to automatically remove old backups when size exceeds this limit
#arkMaxBackupSizeGB="2"                                             # Uncomment this and comment the above to specify the limit in whole GB
`

**Comment by klightspeed** [comment]
Wildcard removed libEOSSDK-Linux-Shipping.so

https://steamdb.info/patchnotes/5153126/

> Removed file – ShooterGame/Binaries/Linux/libEOSSDK-Linux-Shipping.so (18.21 MiB)
> Modified file – ShooterGame/Binaries/Linux/ShooterGameServer (+4.00 KiB)
> Modified file – ShooterGame/Binaries/Win64/ShooterGameServer.exe (+1.00 KiB)
> Modified file – ShooterGame/Binaries/Win64/ShooterGameServer.pdb
> Modified file – version.txt

It's not the first time that Wildcard has broken the Linux build.

**Comment by lettucetrail** [comment]
Yikes. Well after updating I'm no longer receiving the missing file issue. However I'm still unable to connect? So they changed something with rawports? But mine are commented out.
