### ISSUE TITLE
Error when using arkmanager upgrade

### ISSUE THREAD

**Issue by karl-ulyanov** [FezVrasta/ark-server-tools#111]
curl -sL http://git.io/vtf5N | sudo bash -s ircd
did not work, so I replaced the contents of the CFG and arkmanager bin manually, manually changed my version to 1.1 and attempted to update. This is the result.

ircd@ark:~$ arkmanager upgrade
arkmanager v1.1: Checking for updates...
/usr/local/bin/arkmanager: line 375: A new version was found! Do you want to upgrade ARK Server Tools to v${$arkstLatestVersion}?: bad substitution
ircd@ark:~$

**Comment by Atriusftw** [comment]
https://github.com/FezVrasta/ark-server-tools/issues/109
