### ISSUE TITLE
Please ensure the server is running the latest version of all mod content

### ISSUE THREAD

**Issue by Sc0r** [FezVrasta/ark-server-tools#1112]
I get this issue whenever I try to join my [server](https://ark-servers.net/server/230157/).
"Please ensure the server you are trying to join is running the latest version of all mod content"
Why?

```
~$ arkmanager checkmodupdate --updatemods  @crystal
Running command 'checkmodupdate' for instance 'crystal'
All mods are up to date

```
EDIT
huh, now it works without anything changing. odd.

**Comment by klightspeed** [comment]
It could have been that the client hadn't finished updating its mods.  Since mods do not have any inherent version, there is no way to tell whether the server or client has more up-to-date mods.
