### ISSUE TITLE
New Character with half attributes

### ISSUE THREAD

**Issue by Sc0r** [FezVrasta/ark-server-tools#1118]
Not sure how this happened, but when I create a new character on my server, all attributes start at 50.
game.ini has nothing changeing the basestatmultiplier (its empty actually)

![image](https://user-images.githubusercontent.com/10654417/85198292-e35e0280-b2e7-11ea-9c88-5f845deafd8f.png)

**Comment by Sc0r** [comment]
I believe the culprit is the mod "the hunted"  even though its not directly stated in the description

**Comment by klightspeed** [comment]
https://steamcommunity.com/workshop/filedetails/discussion/2112724006/2281582783368408310/ - Character Updates says it halves the starting stats.
