### ISSUE TITLE
/path/to/instance/ ???

### ISSUE THREAD

**Issue by slitterell** [FezVrasta/ark-server-tools#1120]
I copied and pasted my Game.ini and GameUserSetting.ini to the same folder on a new server /ShooterGame/Config/LinuxServer/ and neither are working. Look at the readme and it says /path/to/instance/config.*******. I have no idea what this means. I also don't know why the game.ini and gameusersettings.ini are not working when they previously worked on another server and I haven''t the slightest what it means by /path/to/instance/. Does that mean in that instance folder with ShooterGame folder? or Config/LinuxServer? I can't tell if it just isn't working for me or they have relocated the folder in which it is supposed to be in for arkmanager.

**Comment by klightspeed** [comment]
Replace `/path/to/instance/config` with the path to the instance config

**Comment by slitterell** [comment]
so in my scenario, /etc/arkmanager/instances/config.game.ini file.

I have tried there and it is not loading my game.ini file. Unless "config" relates to the name of the config instead of just "config.game.ini", run it as "**nameofinstance**.game.ini"

**Comment by klightspeed** [comment]
Your `Game.ini` and `GameUserSettings.ini` belong in `ShooterGameServer/Saved/Config/LinuxServer`.  The ini files specified by `arkGameUserSettingsIniFile` and `arkGameIniFile` (which by default have the same basename and path as your instance config) overwrite those files.

Assuming your instance config is `/etc/arkmanager/instances/crystal.cfg`, then `/etc/arkmanager/instances/crystal.GameUserSettings.ini` will overwrite `ShooterGameServer/Saved/Config/LinuxServer/GameUserSettings.ini`

**Comment by slitterell** [comment]
permissions in Linux are a $%#@ that's all. :) Thank you!
