### ISSUE TITLE
Add summer bash 2020

### ISSUE THREAD

**Issue by ajreissig** [FezVrasta/ark-server-tools#1122]
This is probably pretty simple, but I want to add the summer bash 2020 to my server.  The statement from Wildcard says you need to add -activeevent=Summer to your server console.  Do you know how to set this up using ark server tools?  thanks for any help!

**Comment by klightspeed** [comment]
`arkopt_activeevent=Summer`

**Comment by ajreissig** [comment]
Awesome! thanks!
