### ISSUE TITLE
arkGameIniFile may not work as expected

### ISSUE THREAD

**Issue by beegerous** [FezVrasta/ark-server-tools#1123]
thanks for your work, this tools is really helpful.

i try to modify arkGameIniFile setting in arkmanager.cfg, but after the server started, i open Game.ini file in arkserverroot, it is empty, but the last modified time is the current timestamp.
then i change arkGameIniFile directly to Game.ini in arkserverroot, when restart, it says "cp xxx yyy is the same file.", so i think it is working, but something happened after that overwrite this file.
i tried add arkGameIniFile in both arkmanager.cfg and instance.cfg, and still not working.

**Comment by klightspeed** [comment]
If the game server (i.e. `ShooterGameServer`) can't parse the file, then it will usually replace it with the default file (which for `Game.ini` is empty).

**Comment by beegerous** [comment]
> If the game server (i.e. `ShooterGameServer`) can't parse the file, then it will usually replace it with the default file (which for `Game.ini` is empty).

thanks very much. this is helpful.

after check Game.ini in my client machine, it seems this file has to start with [/Script/ShooterGame.ShooterGameMode] to declare its session. after add this on top of file, it worked.
