### ISSUE TITLE
Please consider renaming the command upgrade

### ISSUE THREAD

**Issue by StuartWhelan** [FezVrasta/ark-server-tools#115]
I think the command upgrade is a little dangerous, it would be easy to confuse upgrade and update.

Please consider renaming it to something like scriptupgrade or scriptupdate.

**Comment by pereirtc** [comment]
My advice to keep consistency of the script:


Option                                 Description
update --arkserver              Check for a new ARK server version
update --arkserver -safe     Wait for server to perform world save and update.
update --servertools           Check for a new ARK Server Tools version and upgrades it if needed

**Comment by Atriusftw** [comment]
``arkmanager upgrade`` is now ``arkmanager upgrade-tools`` as of 1.4-dev
