### ISSUE TITLE
/usr/local/bin/arkmanager: line 228: ulimit: open files: cannot modify limit: Operation not permitted

### ISSUE THREAD

**Issue by metaDom** [FezVrasta/ark-server-tools#117]
$ arkmanager status
 Server running:   Yes
 Server online:   No
 Server version:   694428

user steam owns all files and folders, limit was also modified manually. startting arkmanager as user steam, too.

ports are open

**Comment by metaDom** [comment]
ports are open btw

**Comment by klightspeed** [comment]
The error in the subject suggests that the open files limit did not actually apply, and that you likely still have the default open files limit of 1024.

However, from my testing, it looks like the high ulimit is no longer required, as on my system the latest version of the server has at most about 400 files open at any one time.

Note that the server usually takes a few minutes to start up.  On my system, it takes about 7 minutes to start and uses about 3.4GB of RAM.

Trying to run with e.g. 1GB of RAM plus a lot of swap will make it take longer to start up, as it will push about 3GB into swap.

**Comment by Kahn** [comment]
@metaDom can you please give us more details. Details like your OS, log files etc will help to narrow down this issue.

**Comment by metaDom** [comment]
@Kahn:I simply changed the ulimit manually and commented out the line to bypass the error so far
