### ISSUE TITLE
file limit?

### ISSUE THREAD

**Issue by Sispheor** [FezVrasta/ark-server-tools#122]
We do not need anymore to change file limit ont the system?
This prerequisite is still present in the official wiki:
http://ark.gamepedia.com/Dedicated_Server_Setup

**Comment by klightspeed** [comment]
In my testing, the most files the ShooterGameServer process has open at any one time is 401, and the server starts successfully with the default open file limit of 1024.

**Comment by Sispheor** [comment]
Ok, I'm just saying that because it's in the official doc. I'll monitor my opened file and re open this issue if it exceed the default limit.

**Comment by klightspeed** [comment]
@Sispheor ShooterGameServer used to open over 1000 files at any one time; however, this was remedied around v186

**Comment by Sispheor** [comment]
OK, thank you.

2015-07-19 17:54 GMT+02:00 Ben Peddell <notifications@github.com>:

> @Sispheor <https://github.com/Sispheor> ShooterGameServer used to open
> over 1000 files at any one time; however, this was remedied around v186
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/122#issuecomment-122674256>
> .
>



-- 
*Nicolas MARCQ*
