### ISSUE TITLE
Please drop the sudo requirement

### ISSUE THREAD

**Issue by seitzbg** [FezVrasta/ark-server-tools#123]
App should not need sudo.  Startup script should be additional work by user per instructions.  All binaries and such should live in a normal user's directory.

**Comment by Sispheor** [comment]
Sudo seems only be requiered for the installation
https://github.com/FezVrasta/ark-server-tools/search?utf8=%E2%9C%93&q=sudo

**Comment by seitzbg** [comment]
Yes, it should not be needed at all.  Everything can be done as a normal user if the ark manager is installed in the home directory as well.

**Comment by klightspeed** [comment]
Should we perhaps have a user-install option, which would:
* copy `arkmanager` to `~/bin/arkmanager`
* create `~/logs/arktools`
* copy `arkmanager.cfg` to `~/.arkmanager.cfg` (or `~/.arkmanager.cfg.new` if that already exists)
* modify `.arkmanager.cfg` (or `.arkmanager.cfg.new` if that already existed), pointing logdir to `~/logs/arktools`

The user-install option wouldn't give the user any of the init scripts, so they would need to start it on their own.

**Comment by Kahn** [comment]
A per user install would allow for multiple servers to be run per host as well. I think implementing both options would be ideal

**Comment by klightspeed** [comment]
This issue should have been satisfied by f58645c
