### ISSUE TITLE
Saveworld and restart problem

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#129]
arkmanager update --safe
do you plane to add a saveworld also for the restart ?
 
otherwise when i perform a restart it only stop the server, it doesn't start it again. i need to perform an arkmanager start

**Comment by Atriusftw** [comment]
You got the answer to your question in PR https://github.com/FezVrasta/ark-server-tools/pull/128 that you created.

**Comment by klightspeed** [comment]
@arkfrancegaming The fact that you say that arkmanager restart doesn't start the server sounds like you are terminating the script when it doesn't return after a few seconds.

**Comment by arkfrancegaming** [comment]
When i try a restart, the return command is : the server has been stop
