### ISSUE TITLE
/usr/local/bin/arkmanager: line 189: lsof: command not found

### ISSUE THREAD

**Issue by OnigamiSama** [FezVrasta/ark-server-tools#132]
$ arkmanager status
Server running:   Yes 
/usr/local/bin/arkmanager: line 189: lsof: command not found
Server online:   No 
Server version:   708279

It's doesn't seems to be critical since I can see my server on the Steam server list and play on it.

Server OS : Archlinux (latest)
CPU : Intel Xeon E3 1245v2
RAM : 32 Go

**Comment by Lihis** [comment]
Do you have lsof package installed? iirc it is not installed by default.

**Comment by OnigamiSama** [comment]
Just installed lsof fix the issue, thanks !. But it still show "server Online : No" might come from something else

**Comment by Q11x** [comment]
It can take up to 10 minutes when starting a Ark server before it's online.
