### ISSUE TITLE
Running more than one server

### ISSUE THREAD

**Issue by Ulthrin** [FezVrasta/ark-server-tools#136]
Im trying to look into running a extra server beside the one i allready have.

If i understand the info i read i need to add something to arkmanager.cfg but what ?

**Comment by klightspeed** [comment]
At the moment, you need to run the servers under two different users, and put the server-specific settings into $HOME/.arkmanager.cfg

**Comment by Ulthrin** [comment]
So if i get you right i could do something like this:
Server 1:
etc/arkmanager/arkmanager.cfg
media/Ark/server1
(run it as user1)

Server 2:
Home/(user)/arkmanager.cfg
media/Ark/server2
(run it as user2)

**Comment by klightspeed** [comment]
Common settings are in `/etc/arkmanager/arkmanager.cfg`

Settings for user1 are in `/home/user1/.arkmanager.cfg`

Settings for user2 are in `/home/user2/.arkmanager.cfg`

Each of the user-specific configs would specify the `steamcmdroot`, `steamcmd_appinfocache`, `arkserverroot`, `arkbackupdir`, `logdir`, and any `ark_*` options.

**Comment by Ulthrin** [comment]
After updating to 1.3 i been trying to run 2 servers again but im still running into problems.
My link to  the second users .cfg is:

arkmanager.cfg(main file)
 # alternate configs
 # example for config name "ark1":
 #config_ark1="/path/to/config/file"
 config_HCP="/home/HCPrime/HCP.cfg"

when i try to use: arkmanager useconfig HCP install
/usr/local/bin/arkmanager: line 600: HCP: No such file or directory
"then it starts to run a check on server 1"

i tested with the status command: arkmanager useconfig HCP status
/usr/local/bin/arkmanager: line 600: HCP: No such file or directory
 Server running:   Yes
 Server online:   Yes
 Server version:   755631

i have different steamcmd user so thats not the issue but its clear i made a error somwhere

**Comment by klightspeed** [comment]
Sorry, there is an inconsistency between the config file and the arkmanager script - the script uses configfile_<cfg>, not config_<cfg>.  Try using `configfile_HCP="/home/HCPrime/HCP.cfg"` in your config file.

**Comment by Ulthrin** [comment]
Thanks it work :)
