### ISSUE TITLE
Server is not connect-able

### ISSUE THREAD

**Issue by Shawak** [FezVrasta/ark-server-tools#138]
Hey,

i've got following problem. I've followed every instruction and opened the ports on my firewall and created a steam user and so on. "arkmanager status" gives me this:

Server running: Yes
Server online: Yes
Server version: 712950

But i can't connect to the server. I cannot find it on any list, also a shortcut with steam://connect/<ip>:7778 is not working.

Any idea what's the problem?

**Comment by Shawak** [comment]
I reinstalled everything, it still doesn't want to work. Here is what I did:`

```
useradd steam
su - steam
mkdir ~/steamcmd
cd ~/steamcmd
wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
tar -xvzf steamcmd_linux.tar.gz

su - steam
Steam > login username password
Steam > force_install_dir /home/steam/ARK
Steam > app_update 376030 validate
Steam > exit

su - root
iptables -I INPUT -p udp --dport 27016 -j ACCEPT
iptables -I INPUT -p tcp --dport 27016 -j ACCEPT
iptables -I INPUT -p udp --dport 7778 -j ACCEPT
iptables -I INPUT -p tcp --dport 7778 -j ACCEPT
iptables -I INPUT -p tcp --dport 32330 -j ACCEPT

curl -sL http://git.io/vtf5N | sudo bash -s steam

su - steam
arkmanager install
nano /etc/arkmanager/arkmanager.cfg
arkmanager start
```

**Comment by Kahn** [comment]
You can try running with Ansible to see if better error handling helps highlight where your deployment is failing https://github.com/Kahn/ansible-arkservertools

**Comment by Shawak** [comment]
Is there any way to check whether the ports are open or not?

**Comment by FezVrasta** [comment]
Try canyouseeme.org

**Comment by Shawak** [comment]
I don't have any gui on my vpn to access this page.

**Comment by FezVrasta** [comment]
You should use it from the outside, it will tell you if a port is listening (and then is open)

**Comment by Shawak** [comment]
What do you mean by "from the outside"? As far as i know, canyouseeme.org doesn't support checking another ip then the own.

**Comment by FezVrasta** [comment]
Sorry I didn't notice it.

You may try this one http://www.yougetsignal.com/tools/open-ports/

or just google for one you like

**Comment by pereirtc** [comment]
People really don't have idea how to use github....

that's why i don't make my ark manager avaliable =(

**Comment by Shawak** [comment]
No idea why you're hating instead of just hating, but congratz for you uneccessary post.

It seems like the ports are not open, is there anything  wrong with the iptable settings?

**Comment by pereirtc** [comment]
i'm not extending this discussion, if you are saying "No idea why you're hating instead of just helping, but congratz for you unnecessary post."

yes, my post is unnecessary , but this sections is to report only bugs or problems regarding the ark-manager code.

This isn't  a forum for admin kiddies. if people don't know how to open a question on stackoverflow or search on google about how to properly use iptables, this isn't the place to find it.

**Comment by Shawak** [comment]
I am able to use google and stackoverflow, but my ports are definitly open. If not it seems to be a problem with the installtion of the script and/or the instructions, doesn't it?

I don't see what's wrong with my post Your post doesn't include any usefull information, it's just you saying "haha its working for me but iI don't share it". Which is absolutly okay, but if you decide so don't annoy us with this.

I did follow all of the steps and it is not working, finding a solution may help other people later to fix the same problem. But if FezVrasta decides that this is not necessary, it's okay and I will close my issue.

**Comment by pereirtc** [comment]
throw me a message and i'll help you with the issue, but i wont polute this with a problem outside of the scope of ark-manager =)

**Comment by FezVrasta** [comment]
I just wonder what is wrong with your setup, I'd like to know it so maybe we can include some specific feature to make it easier for others to spot the problem.

**Comment by Shawak** [comment]
You can contact me on skype (shawak1) and we may talk a bit there.

I would like to try a clean install since I really can't get it running, which OS may I use?

**Comment by FezVrasta** [comment]
You should use an LTS of Ubuntu, I think the ark devs used 14.04

**Comment by Shawak** [comment]
I am now using a clean instlalation of Ubuntu 14.04 and set up the server using following commands

```
su - root
apt-get install lib32gcc1
adduser steam

su - steam
mkdir ~/steamcmd
cd ~/steamcmd
wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
tar -xvzf steamcmd_linux.tar.gz
./steamcmd.sh
Steam > login username password
Steam > force_install_dir /home/steam/ARK
Steam > app_update 376030 validate
Steam > exit

su - root
iptables -I INPUT -p udp --dport 27016 -j ACCEPT
iptables -I INPUT -p tcp --dport 27016 -j ACCEPT
iptables -I INPUT -p udp --dport 7778 -j ACCEPT
iptables -I INPUT -p tcp --dport 7778 -j ACCEPT
iptables -I INPUT -p tcp --dport 32330 -j ACCEPT
curl -sL http://git.io/vtf5N | sudo bash -s steam

su - steam
arkmanager install
nano /etc/arkmanager/arkmanager.cfg
arkmanager start
```

And I still can not connect. I can't find the server in steam server list or on arkservers.net and steam://connect/<ip>:7778 also don't work.

**Comment by FezVrasta** [comment]
The server list Is not reliable..

**Comment by Shawak** [comment]
I know, but the clean install of Ubuntu 14.04 fixed my problem that i was not able to connect.

Adding the server as favourite didnt work, same for:
steam://connect/ip:27016
steam://connect/ip:7778

Now it works.

**Comment by Shawak** [comment]
Just for the protocol: Server List works now too after waiting only one hour. Yesterday I tried waiting ten hours and nothing happened, strange.

Maybe it was a problem with debian wheezy.
