### ISSUE TITLE
Kind of Dos attack

### ISSUE THREAD

**Issue by N0F3X** [FezVrasta/ark-server-tools#139]
Hello maybe someone can help me here.
My server is unreachable from the steam or top page, after some analysis I found the problem.
My tcpdump log look like this:

`
21:35:28.149627 IP 19.52.123.202.49447 > 188.138.105.178.27016: UDP, length 25
E..5.........4{...i..'i..!......TSource Engine Query.
`
`
21:35:28.149628 IP 144.123.235.217.52692 > 188.138.105.178.27016: UDP, length 25
E(.5.....o..{....i...i..!......TSource Engine Query.
`
`
21:35:28.149630 IP 176.57.144.243.60599 > 188.138.105.178.27016: UDP, length 25
E..5......._.9....i...i..!......TSource Engine Query.
`
`
21:35:28.149631 IP 73.174.104.52.19025 > 188.138.105.178.27016: UDP, length 25
E(.5'.......I.h4..i.JQi..!......TSource Engine Query.
`
`
21:35:28.149633 IP 22.231.167.11.51825 > 188.138.105.178.27016: UDP, length 25
E..5.;....UK......i..qi..!......TSource Engine Query.
`
`
21:35:28.149635 IP 209.96.155.201.51746 > 188.138.105.178.27016: UDP, length 25
E(.5......}^.....i.."i..!......TSource Engine Query
`

and it is without end, I searched in the internet for some solution, but found nothing that can help.

**Comment by N0F3X** [comment]
##### My iptables look like this right now:

*raw
:PREROUTING ACCEPT [7516:515281]
:OUTPUT ACCEPT [3896:365411]
-A PREROUTING -p udp -m udp --dport 27016 -m length --length 25 -j DROP
-A PREROUTING -p udp -m udp --dport 27016 -m length --length 0:32 -j DROP
-A PREROUTING -p udp -m udp --dport 27016 -m string --string "Source Engine Query" --algo kmp --to 65535 -j DROP
COMMIT
*mangle
:PREROUTING ACCEPT [23414968:1241116862]
:INPUT ACCEPT [23306835:1235349388]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [5198:709397]
:POSTROUTING ACCEPT [5198:709397]
COMMIT
*nat
:PREROUTING ACCEPT [23411579:1240874013]
:INPUT ACCEPT [65968:3499243]
:OUTPUT ACCEPT [1070:74105]
:POSTROUTING ACCEPT [1070:74105]
COMMIT
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:filter - [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -d xx.xx.xx.xx/32 -p tcp -m tcp --dport 22 -m state --state NEW -m hashlimit --hashlimit-upto 1/sec --hashlimit-burst 20 --hashlimit-mode srcip,dstport --hashlimit-name SSHPROTECT --hashlimit-htable-expire 3600000 -j ACCEPT
-A INPUT -d xx.xx.xx.xx/32 -p tcp -m tcp --dport 22 -m state --state NEW -m recent --set --name SSHLIMIT --mask 255.255.255.255 --rsource
-A INPUT -d xx.xx.xx.xx/32 -p tcp -m tcp --dport 22 -m state --state NEW -m recent --update --seconds 300 --hitcount 4 --name SSHLIMIT --mask 255.255.255.255 --rsource -j DROP
-A INPUT -d xx.xx.xx.xx/32 -p tcp -m tcp --dport 22 -m state --state NEW -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 8/0 -m limit --limit 1/sec -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 11/0 -m limit --limit 1/sec -j ACCEPT
-A INPUT -d 188.138.105.178/32 -p udp -m udp --dport 7980:7881 -m state --state NEW -m recent --set --name ARKLIMITUDP --mask 255.255.255.255 --rsource
-A INPUT -d 188.138.105.178/32 -p udp -m udp --dport 7980:7881 -m state --state NEW -m recent --update --seconds 60 --hitcount 10 --name ARKLIMITUDP --mask 255.255.255.255 --rsource -j DROP
-A INPUT -d 188.138.105.178/32 -p udp -m udp --dport 7980:7881 -j ACCEPT
-A INPUT -p udp -m udp --dport 27016 -m length --length 25 -j DROP
-A INPUT -p udp -m udp --dport 27016 -m length --length 0:32 -j DROP
-A INPUT -p udp -m udp --dport 27016 -m length --length 2521:65535 -j DROP
-A INPUT -d 188.138.105.178/32 -p tcp -m tcp --dport 27016 -j filter
-A INPUT -d 188.138.105.178/32 -p udp -m udp --dport 27016 -j filter
-A INPUT -j DROP
-A FORWARD -j DROP
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -m conntrack --ctstate NEW,RELATED,ESTABLISHED -j ACCEPT
-A OUTPUT -j ACCEPT
-A filter -m state --state NEW -m hashlimit --hashlimit-upto 1/sec --hashlimit-burst 5 --hashlimit-mode srcip,dstport --hashlimit-name DOSPROTECT --hashlimit-htable-expire 3600000 -j ACCEPT
COMMIT

**Comment by Saiboogu** [comment]
You know this is just the issues section for a script that helps run ARK servers? Nothing to do with the game itself.

**Comment by klightspeed** [comment]
@N0F3X You know of course that the iptables rules you put in to block this apparent DDoS attack will actually prevent anybody from actually connecting.

**Comment by FezVrasta** [comment]
Use sysdig to analyze your server

**Comment by N0F3X** [comment]
I know that isn't the place to ask about it. Sorry for that.
@klightspeed oh, and I missed it, thanks.
@FezVrasta Thank you, I will try.
