### ISSUE TITLE
arkmanager stop doesn't work

### ISSUE THREAD

**Issue by loconox** [FezVrasta/ark-server-tools#14]
Hi,
I'm not able to stop the server using arkmanager stop.
I'm not very familiar with screen, but when I try to retach the session it fails.
screen -r arkserv or screen -r

**Comment by loconox** [comment]
Well, as soon as we can't call for a save before stop and stop the server properly, maybe this command should print a warning to ask confirmation before kill the process.

**Comment by FezVrasta** [comment]
added the confirmation message

**Comment by Atriusftw** [comment]
Pull request https://github.com/FezVrasta/ark-server-tools/pull/20 should resolve this.

Now properly closes the active screen session and terminates the process inside.
