### ISSUE TITLE
Auto backup

### ISSUE THREAD

**Issue by Ulthrin** [FezVrasta/ark-server-tools#141]
I know we have the backup command and it works like a charm for me:)
Due some hardware issues i started to use rsync and cron to make a extra backup.
Im by far expert in programming and linux in general, but is that a option that could be put into the script so it runs a backup on a timer?

**Comment by klightspeed** [comment]
Using the latest 1.3-dev arkmanager:

```bash
VISUAL= EDITOR=ed crontab -e <<EOE
g/^0,15,30,45 [*] [*] [*] [*] arkmanager saveworld backup/d
$r !echo "0,15,30,45 * * * * arkmanager saveworld backup >/dev/null 2>&1"
!sleep 1
wq
EOE
```
