### ISSUE TITLE
arkmanager supports this as of xxxxxxx

### ISSUE THREAD

**Issue by OnigamiSama** [FezVrasta/ark-server-tools#145]
I see alot of "arkmanager supports this as of" but when I do arkmanager upgrade nothing happens. I'm new to Github and how it work so I'm a little confused right now

my arkmanager is 1.2

**Comment by klightspeed** [comment]
The support for those things is in 1.3-dev, which we are looking at stabilizing.

**Comment by OnigamiSama** [comment]
Is there any ETA on when 1.3 will be replacing 1.2 ?
