### ISSUE TITLE
Totalconversion mod

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#147]
Hi,

is it possible to add the new TotalConversionMod from ARK in lauch option ?

http://steamcommunity.com/app/346110/discussions/10/530649887204866610/

thanks

**Comment by FezVrasta** [comment]
You should already be able to load this mod like any other mod.

**Comment by arkfrancegaming** [comment]
Totalconversion is something else that the mod id

**Comment by FezVrasta** [comment]
You can already define any additional options, just as them to the config prefixed by ark_

**Comment by sicco0803** [comment]
How can i start SOTF i don#t now how add the start parameter -TotalConversionMod=496735411. Please i need to know.

Thank you
Sicco

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/ark-server-tools#configuration

**Comment by klightspeed** [comment]
You can add ark_TotalConversionMod="496735411" to your arkmanager.cfg file.

Note that the version of the mod as copied from a Linux client is currently crashing, and there are multiple reports of people having issues with the mod causing crashes on clients when connecting to a Linux server.
