### ISSUE TITLE
configureable Steamcmd User

### ISSUE THREAD

**Issue by high-voltages** [FezVrasta/ark-server-tools#149]
It would be nice to use another steam login as anonymous.
The setting could be placed in the arkmanager config.

Greetings
high-voltages

**Comment by FezVrasta** [comment]
why would you need to specify a steam user when anonymous can do everything you need?

**Comment by high-voltages** [comment]
I had problems with my downloadspeed by updating the Server.
So i think that Steam throttle the speed for anoymouns Users.

But in the moment i am not sure about it because now the speed is higher after some changes in my DNS Server settings.
