### ISSUE TITLE
Space in session name

### ISSUE THREAD

**Issue by loconox** [FezVrasta/ark-server-tools#15]
Not sure if it's a limitation in the script or a limitation of the game, but we can't add spaces into the server name.

**Comment by FezVrasta** [comment]
I'm not sure, I'm open to suggestions

**Comment by puseidr** [comment]
you need to set the sessionname in the ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini 

[SessionSettings]
SessionName=Your Server Name 



and change the /usr/bin/arkmanager  to:
``arkserveropts="TheIsland?QueryPort=$arkserverport?ServerPassword=$arkserverpass?ServerAdminPassword=$arkserverapass?listen"
``

**Comment by Atriusftw** [comment]
I'm just going to throw some ideas out here;
Maybe use sed to append those two lines to the end of the .ini file?
