### ISSUE TITLE
Dropping items disappear instantly

### ISSUE THREAD

**Issue by JoshAldridge** [FezVrasta/ark-server-tools#150]
So I have the issue described int he title, all the fixes I find are about changing a config optopn in arkmanager however that option is no longer avaliable but my issue still exists.

**Comment by klightspeed** [comment]
Does the same thing occur if you run the ShooterGameServer executable directly, using the same ark options as you have configured in the arkmanager.cfg?

**Comment by Atriusftw** [comment]
Check the structure in your ARK configuration, and make sure things are put in the correct order.
That have been causing some problems for me in the past.

**Comment by crckdns** [comment]
that's a problem with Ark and mods itself, not the ark tools. Appears to be linux-only for now.
v210.0 update brought the bug back, v210.2 fixed this bug.. and no one can track back what the real problem is.
From my observation it has something to do with mods, as this bug never happened to my server without mods.

**Comment by FezVrasta** [comment]
I remember this was happen if you set an empty password to the arkmanager config.. but I'm not sure if this was the real problem

**Comment by Atriusftw** [comment]
Not directly related to arkmanager, unless you append the same configuration settings to both GameUserSettings.ini and arkmanager.cfg

**Comment by crckdns** [comment]
This problem disappeared to me after adding the global decomposing timers in the game.ini

GlobalSpoilingTimeMultiplier=1
GlobalItemDecompositionTimeMultiplier=1
GlobalCorpseDecompositionTimeMultiplier=1

**Comment by Atriusftw** [comment]
Thanks for the input @crckdns
