### ISSUE TITLE
Upgrade problems with ubuntu 10.04

### ISSUE THREAD

**Issue by jaahaavi** [FezVrasta/ark-server-tools#154]
I tried to upgrade the newest version of the script, but then my "steam" user didn't have sudo rights. Then I added sudo rights to steam user and got these errors:

arkmanager v1.2: Checking for updates...
A new version was found! Do you want to upgrade ARK Server Tools to v1.3?y
install.sh: 3: [: steam: unexpected operator
install.sh: 11: [: steam: unexpected operator
install.sh: 31: [: steam: unexpected operator
WARNING: A previous version of ARK Server Tools was detected in your system, your old configuration was not overwritten. You may need to manually update it.
ARK Server Tools were correctly installed in your system inside the home directory of steam!

It didn't install it correctly because it's still 1.2 version.

**Comment by klightspeed** [comment]
@FezVrasta The version of the script really should live in the script itself and not its config.

We probably should also get rid of some bashisms in the scripts, since e.g. /bin/sh on Ubuntu is actually dash, which doesn't understand `[ "a" == "b" ]` (which is actually non-standard syntax).

**Comment by klightspeed** [comment]
This should be resolved with 8a7f6d24bc2e4ac6dd6ddbc6aa97512e15e39450
