### ISSUE TITLE
multiserver config issue

### ISSUE THREAD

**Issue by Ulthrin** [FezVrasta/ark-server-tools#155]
After some guiding i been able to get my 2nd server go online.

Problem is that its not password protected  shows 0 / 0 player and no map.

The 1st server runs without problems, but if i start 2nd server first, the issues goes to 1st server.

Both servers use the right configfiles but password/maxplayers/map is "blocked" on the second server i  online.

**Comment by klightspeed** [comment]
Are the two servers using different ports - i.e. are you specifying the Port, QueryPort and RCONPort in both server config files?

If both servers use the same Port or RCONPort, then the second server to start will load up to where it tries to bind to the game / RCON ports, and it sounds like the servers hang if something is already bound to those ports.
