### ISSUE TITLE
Feature Request: Mod-fetching / updates on linux servers

### ISSUE THREAD

**Issue by crckdns** [FezVrasta/ark-server-tools#157]
Hey there,

is it possible to make the tool fetch newest version of the mods (workshop item), so the server isn't rendered unusable after a mod-creator decides to update his mod?
For now the only solution I know is working about ..is to update the mod on our windows steam machine and then upload the new, ready folder/file structure on the linux server.
A simple workshop_download_item won't do it, as you just get a bunch of archives you have to deal with.. 

..Just a suggestion, sorry if I missed something.

**Comment by klightspeed** [comment]
That sort of thing was on the [ARK patch roadmap](http://steamcommunity.com/app/346110/discussions/0/594820656447032287/), but it seems to have been removed when they created their [ARK Server Launcher](http://steamcommunity.com/app/346110/discussions/10/530649887219814834/).

**Comment by OnigamiSama** [comment]
I really hope this feature will be implemented in ArkServerTool, Ark Server Laucher server side require mono to run on linux and the client look like to be Windows only.

**Comment by klightspeed** [comment]
I suspect that it would require determining what ArkRemote does when installing mods.  The archives that are downloaded by workshop_download_item are Unreal Engine compressed assets.  Unless ArkRemote includes code to decompress them and create the `.mod` files, or the server launcher client is sending them over to the server, I suspect that it'd be putting the workshop files into a directory and asking the ShooterGameServer to install them.

**Comment by klightspeed** [comment]
It appears that the ARK server launcher decompresses the `.uasset.z` files writes the .mod files itself.

Fortunately, the `.uasset.z` files are just zlib-compressed files with a 48-byte unreal header.  These can be decompressed with one of zlib-flate (part of qpdf), some perl code, or gzip (with a header prepended).

The .mod files that ARKServerLauncher writes have the Mod ID (as a 32-bit little-endian integer), a ModName field with the mod name, a special `33 FF 22 FF 02 00 00 00` marker, followed by `01` and either the contents of the modmeta.info file or a ModType field.

The .mod files that the client writes have the Mod ID (as a 32-bit little-endian integer), the friendly name, the path, the mod name, a special `33 FF 22 FF 02 00 00 00` marker, followed by either `01` followed by the contents of the modmeta.info file, or 5 `00` bytes.

**Comment by klightspeed** [comment]
Do we want to update mods - e.g. those in `ARK_GameModIds`, `ARK_TotalConversionMod`, and `serverMapModId` - when the `arkmanager update` command is run?

**Comment by FezVrasta** [comment]
I'd probably add an option (--update-mods) to the `update` command.

**Comment by Atriusftw** [comment]
Done: https://github.com/FezVrasta/ark-server-tools/commit/e9b987f19ae50aed4b98f37c996b8ceeb71fb3a6, great work @klightspeed!
Anyone running with mods and able to verify that this isn't semi-broken before we close the feature request? :)

**Comment by TheCherry** [comment]
https://github.com/TheCherry/ark-server-manager/blob/master/src/z_unpack.py
With that you can decompress the z files.

**Comment by klightspeed** [comment]
@TheCherry This has already been implemented in 2ef86c9 `tools/arkmanager` lines 469-502

**Comment by klightspeed** [comment]
e4d4218 in #206 should resolve the issue where the server crashes due to the Linux version of the mods apparently being incompatible with the Linux server; it switches to using the Windows version of the mods by default.

The mods written into place after this fix should be identical to the mods written by ARKRemote.

**Comment by crckdns** [comment]
the --update-mods option works how it should~ Thanks so far!

One thing maybe to improve:  it is logging in for each mod ..so if I have 10 mod folders to "update" ..it logs in, downloads the files, quit, log in, download, quit, etc etc~  I can't believe Steam will like that "spam" :D 
Isn't it possible to log-in, check all mods for updates and then download the needed files without disconnecting whole time?

**Comment by klightspeed** [comment]
@crckdns `doDownloadMod` would need to download multiple mods in a single shot, which would increase its complexity.  If you want the retries to also be in the same steamcmd process, then it'd need to be run as a coprocess, and `doDownloadMod` would get even more complex.

**Comment by HenryGarle** [comment]
In reguards to where TheCherry got the code, he decompiled my tool (ASL) without permission and made a python implementation based off of it. Not impressed.
