### ISSUE TITLE
Start development of next release

### ISSUE THREAD

**Issue by klightspeed** [FezVrasta/ark-server-tools#158]
Now that 1.3 has been stabilized, shall we start development on 1.4?

**Comment by FezVrasta** [comment]
yup probably... do we want to try to close all the feature requests or do you have any good idea?

**Comment by Atriusftw** [comment]
I went through all the active issues yesterday and performed some clean up to make it easier for you.
Unfortunately i don't have that much time to code at the moment, but i'll be helping out the way i can meanwhile.
