### ISSUE TITLE
Your SteamCMD user is not valid

### ISSUE THREAD

**Issue by williamrussellajb** [FezVrasta/ark-server-tools#163]
Hello, 
I'm trying to setup a dedicated server using Ark-Server-Tools, however, I've hit a snag.

I've logged into steamcmd.sh successfully and it's been cached.
When I run arkmanager start.. I receive  Your SteamCMD user is not valid.

where in ark-server-tools do I specify my username/password?

Thanks.

**Comment by klightspeed** [comment]
This means that the `steamcmd_user` specified in your `/etc/arkmanager/arkmanager.cfg` is not a valid user on your machine.  This is only of consequence if you are using the init scripts.

If this is a user-install (i.e. you specified `--me` when installing), then ignore it - this is a bug we need to fix.

**Comment by williamrussellajb** [comment]
I've uninstall arkmanager, and re-installed. 

My system username is "steam"
cd ~/ takes me to /home/steam
I've installed steamCMD and logged into my awesomebilly_dev account (from here I exit out of steamcmd)
I'm not quite sure what I've done wrong, but I only get "Your SteamCMD user is not valid." and it defaults to annoymous.

**Comment by klightspeed** [comment]
The `steamcmd_user` is your system user, not your steam user - i.e. `steamcmd_user` is the system user under which steamcmd runs.
