### ISSUE TITLE
Upgrade bad subtitution line 380

### ISSUE THREAD

**Issue by Sasuke31** [FezVrasta/ark-server-tools#166]
Hi,
When using arkmanager upgrade, I get this error:

/usr/local/bin/arkmanager: line 380: A new version was found! Do you want to upgrade ARK Server Tools to v${$arkstLatestVersion}?: bad substitution

Server is on debian.
On Ark Server Tools 1.2
Sorry for my bad english.

**Comment by Sasuke31** [comment]
Now this error

/usr/local/bin/arkmanager: ligne 383: sudo : commande introuvable
(23) Failed writing body

**Comment by klightspeed** [comment]
In relation to your first error, this is a duplicate of #153, #134, #111 and #109.

Please try re-installing arkmanager as suggested in https://github.com/FezVrasta/ark-server-tools#install-ark-server-tools

Perhaps we should add to the readme these sorts of known issues with older versions.

In relation to your second error ([FR]`command introuvable` = [EN]`command not found`), this means you don't have sudo installed.
