### ISSUE TITLE
Error Connecting to server at -e line 31.

### ISSUE THREAD

**Issue by kyle142** [FezVrasta/ark-server-tools#168]
Server runs flawlessly and able to connect to it remotely, however - when trying "arkmanager saveworld", this error appears.   Any help\suggestions?

Only appears to of happened since the last arkmanager update, however I have also been playing with the .cfg and gameusersettings.ini  if that matters...

**Comment by klightspeed** [comment]
Do you have `ark_RCONPort` and `ark_RCONEnabled` defined in your `arkmanager.cfg` file?

That "Error connecting to server" error means that the script was unable to connect to the defined RCON port on the server.

**Comment by kyle142** [comment]
No I don't, I removed it because I was connecting via ssh - I'll add them in and enable rcon for this, thanks!

**Comment by klightspeed** [comment]
If you don't want the RCON port to be connectable externally, and you're not using firewalld, then you can either implement a default-deny policy in your iptables rules (which I think both Debian and CentOS do by default) and only allow the ports you want, or you can add a `-A INPUT -m tcp -p tcp --dport 32330 -j DROP` rule to your iptables rules.

**Comment by dahlskebank** [comment]
Um... I'm a noob here, but why do I need RCON? I noticed this error message while updating our local server, but I can't understand why RCON needs to be enabled? I have set it to disabled. Although the port is defined.

**Comment by Atriusftw** [comment]
If you don't know what RCON is, you're better off having it disabled.

**Comment by dahlskebank** [comment]
That doesn't really help me, as I understand from the answers here that this error message will go away if I enable RCON.

**Comment by Atriusftw** [comment]
RCON is needed to execute in-game commands remotely. (I.e out of game.)

The command you're refering to uses RCON, as there's no interactive console available.

**Comment by klightspeed** [comment]
This would be due to the "Save world before update" added in #175.

1.4-dev makes the saveworld optional, by adding the `--saveworld` option to the `update` command.

**Comment by dahlskebank** [comment]
Thanks! Guess it'll sort itself out when we upgrade arkmanager.
