### ISSUE TITLE
arkmanager upgrade issue

### ISSUE THREAD

**Issue by daervik** [FezVrasta/ark-server-tools#173]
I'm getting an issue while attempting to upgrade arkmanager. I have checked all related issues here, but have not found any mention of this.

I'm accessing the server via ssh. It is running Ubuntu Server 14.04.

steam@... arkmanager upgrade
arkmanger v1.2: Checking for updates...
Your ARK server tools are already up to date.

I know this is wrong, as v1.3 is on github and has additional features such as broadcastmessage and rcon commands.

I have looked over the cfg and check relative to the new ones. I have updated it to the new standard (except I left the version number in for now).

**Comment by klightspeed** [comment]
What is `arkstChannel` set to in your config file?

**Comment by FezVrasta** [comment]
@daervik: `arkstChannel` should be set to `master`.

**Comment by daervik** [comment]
It is set to master, so that's not it.

arkstVersion is set to 1.2. I've tried changing this or even removing the parameter, but there is no difference there either.

**Comment by klightspeed** [comment]
Please try re-installing using `curl -sL http://git.io/vtf5N | sudo bash -s steam`, replacing `steam` with the username under which you are running ARK.

**Comment by daervik** [comment]
when doing curl -sL http://git.io/vtf5N | sudo bash -s steam nothing apparent happens (and the files are still version 1.2)

when doing curl -L http://git.io/vtf5N | sudo bash -s steam It gives the message "0curl: (6) Could not resolve host: git.io"

**Comment by FezVrasta** [comment]
what if you try `ping git.io` or `ping google.com` ?

**Comment by daervik** [comment]
hmm. I got ping: unknown host for both

**Comment by klightspeed** [comment]
Does `/etc/resolv.conf` contain the correct nameservers?

**Comment by daervik** [comment]
I updated the nameserver as klightspeed suggested, and I am now able to ping servers, and the arkmanager upgrade now finds the update to 1.3. Thanks :)

Now I have another issue however, where the steam user is not in the sudoers file, and my root account is not allowed to use arkmanager. Should I open a new ticket for this issue?

**Comment by FezVrasta** [comment]
Open a new issue explaining the problem please
