### ISSUE TITLE
WarnUpdate

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#174]
Hi,
doesn the --warnUpdate perform a saveworld before the update ?

Thanks

**Comment by klightspeed** [comment]
Stopping the server using `SIGINT` (which is what `doStop` does) saved the world the last time I checked.

We can add a `--saveworld` option to `doUpdate` in 1.4, and add a `saveworld` before shutdown to `forceUpdate` in the master branch if necessary, just to be doubly sure.

**Comment by arkfrancegaming** [comment]
yep it will be great ! thanks

**Comment by klightspeed** [comment]
This is now implemented with #175 and #176.
