### ISSUE TITLE
Upgrading Arkmanager on non-sudo account

### ISSUE THREAD

**Issue by daervik** [FezVrasta/ark-server-tools#177]
Hi,

I am running Arkmanager on a Ubuntu Server 14.04.
On this server I have an account for steam which is not root due to security reasons.

When trying to use "arkmanager upgrade" while on the steam account I get the following error:
"steam is not in the sudoers file. This incident will be reported"

When trying to do the same while on the root account I get the following error:
"This script must NOT be run as root"

How can I upgrade the account on a secure account?
Do I need to add the steam account to the sudoers file?
Wouldn't adding the steam account to the sudoers file defeat the purpose of having said account in the first place?

Thanks

**Comment by klightspeed** [comment]
We could extract the upgrade logic from the arkmanager script into e.g. an arkmanager-upgrade script, which would be designed to be able to be run as root.

**Comment by FezVrasta** [comment]
I'd prefer a --root option to allow run as root. lot of scripts do like that

**Comment by daervik** [comment]
The option to be able to run the arkmanager as the root user without logging into the steam user would be a great feature, especially when running commands over ssh.

For now though, I would assume that there is a way to run arkmanager on a non-root "steam" account on ubuntu server. What is the normal setup here? to have the steam account be in sudoers? or is something broken?

**Comment by FezVrasta** [comment]
i think sudoers is the common way

**Comment by daervik** [comment]
Sounds good for now :)

For others looking into the same issue I added the steam account to sudoers using the following command from the main root account:
sudo adduser steam sudo

after logging into the steam account again I can now initiate the arkmanager upgrade command successfully.

Thanks for your good answers :)
