### ISSUE TITLE
custom variable

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#178]
Hi, 
a new command from ark is out : ?bRawSockets

i tried to put ark_?bRawSockets

but i've got that result : /etc/arkmanager/arkmanager.cfg: line 28: ark_?bRawSockets: command not found

**Comment by klightspeed** [comment]
Try omitting the `?` character.

**Comment by arkfrancegaming** [comment]
the ? is a part of the command unfortunaly

**Comment by klightspeed** [comment]
The `?` character is also used to separate options in the command.

Try adding `ark_bRawSockets=true` to your config.

**Comment by arkfrancegaming** [comment]
they say that "You just need "?bRawSockets" I see UDP connection in my fw log file now :-)"

**Comment by klightspeed** [comment]
Specifying a boolean option without a value is equivalent to assigning it a True value.

**Comment by arkfrancegaming** [comment]
is there a way to find the actual lauch options ?

**Comment by BlackLampone** [comment]
"ps aux" will show all running process

ark_bRawSockets=true worked for me

**Comment by arkfrancegaming** [comment]
yep it works but is cause a very bad ping in game :(

**Comment by Atriusftw** [comment]
Yes, i've noticed large spikes in latency aswell.
Normally i'm sitting at 20-40 ms, but after enabling raw UDP sockets it may spike up to 85 at some points.

Hopefully this will be resolved in an upcoming patch.

**Comment by arkfrancegaming** [comment]
does you cpu usage is getting low when you have this spike ?

**Comment by Atriusftw** [comment]
Haven't really been monitoring anything when it happens, but i'll check next time.
Though CPU usage _shouldnt_ be related with network issues.

**Comment by arkfrancegaming** [comment]
i know but for me it seems to be related, usally the process is using about 18% cpu(s) but sometimes it goes low about 12%cpu (s) and big lag for a few seconds ...

**Comment by Atriusftw** [comment]
Well, in that matter it makes sense.
When the latency increases to a certain point, you'll most likely end up getting packet loss (Especially with UDP). That means lost elements to render, which then again lowers CPU usage.

Though, i'm prettu sure the CPU usage increases significally when the latency returns to normal.

**Comment by arkfrancegaming** [comment]
yep it is ! so weird, is it possible to fix it ? for now i've disable the bRawSockets

**Comment by Atriusftw** [comment]
I'm not that familiar with Unreal Engine or game coding in general, but i'm positive that this isn't related to the server itself.
It seems to me that there is indeed some faulty code in the server _files_
When i measured the network traffic from ARK, it used around 1 Megabit per second TX with around 20 players connected, though this was with Steam P2P i can't picture it being much more with raw UDP.

I think we just have to wait for the ARK engineers to polish their netcode.

**Comment by arkfrancegaming** [comment]
DEV form ark said that ?bRawSockets=True is not correct to the lauch command files, is it possible to add only ark_?bRawSockets ?

thanks

**Comment by FezVrasta** [comment]
If you want to monitor consider using sysdig, it will give you all the hints you need

**Comment by arkfrancegaming** [comment]
thanks an about the ark_?bRawSockets

is the command working with ark server tools even there is no =    ?

**Comment by arkfrancegaming** [comment]
great thanks !
