### ISSUE TITLE
Issue with arkmanager start

### ISSUE THREAD

**Issue by PhuriousGeorge** [FezVrasta/ark-server-tools#18]
arkmanager start or stop
/usr/bin/arkmanager: line 44: [665073: command not found

Server appears to start/stop even with this error

**Comment by Atriusftw** [comment]
Pull request https://github.com/FezVrasta/ark-server-tools/issues/18 should correct this.

**Comment by PhuriousGeorge** [comment]
Thanks, made the changes manually.

**Comment by Atriusftw** [comment]
Might aswell merge the pull request, added some more fixes.
