### ISSUE TITLE
arkmanager update --warn - infinite loop

### ISSUE THREAD

**Issue by FleOxm** [FezVrasta/ark-server-tools#180]
Using warn parameter, it seems that script make a loop and do not switch from minutes to seconds

This ARK server will shutdown for an update in 15 minutes
This ARK server will shutdown for an update in 10 minutes
This ARK server will shutdown for an update in 5 minutes
This ARK server will shutdown for an update in 4 minutes
This ARK server will shutdown for an update in 3 minutes
This ARK server will shutdown for an update in 2 minutes
This ARK server will shutdown for an update in 90 seconds
This ARK server will shutdown for an update in 90 seconds
This ARK server will shutdown for an update in 90 seconds
This ARK server will shutdown for an update in 90 seconds
This ARK server will shutdown for an update in 90 seconds

(Thanks for your efforts :) )

**Comment by arkfrancegaming** [comment]
same for me

**Comment by FleOxm** [comment]
Thanks a lot klightspeed !
Fast answer/fix :+1:
