### ISSUE TITLE
updating arkstChannel to 1.4-dev doesn't allow me to grab the dev branch.

### ISSUE THREAD

**Issue by ddanese** [FezVrasta/ark-server-tools#183]
I am attempting to update my 1.3 to 1.4-dev to try some of the new features. Yes, I know it is an unstable branch. 

The config file says to change the arkstChannel to grab unstable branches.  I assume this means to set the branch name, but this has no effect.  Running arkmanager upgrade after resetting that only returns that my arkmanager is already up to date.

**Comment by Atriusftw** [comment]
The file that gets checked wasn't updated.

I updated it now, could you please try again? :)

**Comment by ddanese** [comment]
Thanks, this is working now.
