### ISSUE TITLE
Weird things happening to /etc/arkmanager/arkmanager.cfg after install

### ISSUE THREAD

**Issue by Techrev9999** [FezVrasta/ark-server-tools#188]
Something seems to be deleting every instance of the word 'steam'.  I have to re do it.  Also, without warning, it's started adding a .arkmanager.cfg to the home directory.  This threw me off as well.

**Comment by klightspeed** [comment]
install.sh had a bug that was causing it to modify arkmanager.cfg instead of arkmanager.cfg.NEW; #191 should fix this.

**Comment by Techrev9999** [comment]
I will, thanks!!

**Comment by Techrev9999** [comment]
This seems fixed in #191, thank you!
