### ISSUE TITLE
Not sure why, but mods don't seem to be moving to /home/steam/Steam/ArkServer/Shootergame/Content/Mods

### ISSUE THREAD

**Issue by Techrev9999** [FezVrasta/ark-server-tools#189]
This is my mod directory, I don't know why they aren't copying there.  When I copy them manually Ark crashes trying to connect.  It's possible this is my configuration.

**Comment by klightspeed** [comment]
Does `arkserverroot="/home/steam/Steam/ArkServer"` in your config file?

Does `mod_appid=346110` in your config file?  If it doesn't, then the steamcmd `workshop_download_item` command will fail - all ARK mods are associated with the client appid (346110) and not the server appid (376030).

**Comment by Techrev9999** [comment]
In the arkmanager.cfg?  Because I don't see that line in there.  Sadly I can't test all this until I find out how to load a TC mod with this script :/.

**Comment by klightspeed** [comment]
install.sh had a bug that was modifying arkmanager.cfg instead of arkmanager.cfg.NEW;  Once #191 goes through, would you please check if this resolves your problem.

**Comment by Atriusftw** [comment]
@Techrev9999 

Might have been removed after you got reverted to 1.3 as described on the steam forums.
Just manually add it below this line in `arkmanager.cfg`

`appid=376030                                                        # Linux server App ID`

**Comment by Techrev9999** [comment]
This looks fixed by adding the mod_appid=346110 line.
