### ISSUE TITLE
Arkmanager not detecting updates

### ISSUE THREAD

**Issue by tselling** [FezVrasta/ark-server-tools#190]
Arkmanager is not detecting updates when I use the update command.  I have to use the --force to get any updates.

**Comment by Atriusftw** [comment]
Assuming you're on 1.4-dev, the update command was altered to take arguments for users to specify what type of update-process they would like to perform.

`update [OPTION ...]   Check for a new ARK server version, if needed, stops the server, updates it, and starts it again`

`arkmanager -h` should give you a simple guideline on this;

     Update command takes the below options:
             --force        Apply update without checking the current version
             --safe         Wait for server to perform world save and update.
             --warn         Warn players before updating server
             --validate     Validates all ARK server files
             --saveworld    Saves world before update
             --update-mods  Updates installed and requested mods
             --backup       Takes a backup of the save files before updating

**Comment by tselling** [comment]
The --force but regular update or checkupdate says the version is current even when its not.

**Comment by james-d-elliott** [comment]
It's not arkmanager not detecting updates, it's steamcmd not showing the correct current build (probably a distributed computing issue on steam's end "C" in the CAP theorem). This may be impossible to fix for arkmanager.. not sure if there is any other way to find build numbers.

**Comment by Atriusftw** [comment]
Ah, you're trying to update to version 214.4?
That is a client-side update only :)

**Comment by tselling** [comment]
I think I started a server about 1 month ago with arkmanager and checkupdates and update without --force has never gotten an update for me.  I have always had to use the --force in order to get a server update.    Does anyone get updates without using the --force?

**Comment by klightspeed** [comment]
It is showing for me that the latest build ID is 785930, which matches the build ID at https://steamdb.info/depot/376031/

```
$ arkmanager checkupdate
Querying Steam database for latest version...
Current version:  780996 
Available version:  785930 
Your server needs to be restarted in order to receive the latest update.
Run "arkmanager update" to do so
```

**Comment by tselling** [comment]
Official servers are updating to 215 at 10:00 EST.  After the official servers update is when I normally try to update my server... so far I have always had to use the --force.  Not a crisis, just annoying.

**Comment by Techrev9999** [comment]
Could you do a file compare.  If the new files are different from the old files, reboot?

**Comment by Atriusftw** [comment]
@tselling As far as i know, SteamCMD is also a part of their global CDN which may effect the time it takes before you actually get new content, depending on your ISP etc.

**Comment by ty2u** [comment]
My server is on 216.1 but doesn't detect a 216.2 update. I have to assume it's a server update due to the patch notes which say, "More server crash protection". Plus it says Healthy (v216.2) on the server select screen which leads me to believe most other servers are on 216.2. Yet when I do arkamanger checkupdate it says it's updated at build 792947. Using --force causes it to update.
