### ISSUE TITLE
Not starting fresh install

### ISSUE THREAD

**Issue by giogimic** [FezVrasta/ark-server-tools#199]
06:49:52: start
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

**Comment by giogimic** [comment]
Server running:   Yes
 Server online:   No
 Server version:   789143

**Comment by klightspeed** [comment]
The most common reason for the server not to show as online after a new install is that `lsof` is not installed.

**Comment by giogimic** [comment]
Sorry didn't close this, It says no but it is online and reachable idk why it says no but thats a non-issue now, But now the issue i have is all the mods i have are in game but no one can learn the engrams for them any of them

**Comment by klightspeed** [comment]
Please open a new issue for your new problem.

For your original issue, please ensure that `lsof` is installed.

**Comment by giogimic** [comment]
Package lsof-4.82-5.el6.x86_64 already installed and latest version - btw so that wasn't the issue on this one.
