### ISSUE TITLE
ShooterGameServer missing

### ISSUE THREAD

**Issue by laurentL** [FezVrasta/ark-server-tools#2]
hi,

after "arkmanager install" ShooterGameServer is missing

$ find /home/steam/ARK/
/home/steam/ARK/
/home/steam/ARK/steamclient.so
/home/steam/ARK/steamapps
/home/steam/ARK/steamapps/appmanifest_376030.acf
/home/steam/ARK/steamapps/downloading
/home/steam/ARK/steamapps/temp
/home/steam/ARK/steamapps/libraryfolders.vdf
/home/steam/ARK/linux64
/home/steam/ARK/linux64/steamclient.so

**Comment by FezVrasta** [comment]
The ARK Linux Server has not been released yet, we have to wait it before this script can be used :P

**Comment by lexat** [comment]
I'm a bad person, so use:

echo "echo \"placeholder\"" > /home/steam/ARK/ShooterGameServer
chmod +x ShooterGameServer
*loughing* now you got it ;)

http://steamcommunity.com/app/346110/discussions/0/594820656447032287/ -> for "upcoming time"

**Comment by FezVrasta** [comment]
Why not just `touch /home/steam/ARK/ShooterGameServer`? :p

**Comment by lexat** [comment]
i like runables that do something =)
