### ISSUE TITLE
Tutorial multi server

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#201]
Hi,

i want to try the multi server config,

is there some kind of tutorial for this ?

Thanks

**Comment by FezVrasta** [comment]
No that I'm aware of.

By the way you have just to create a system user for each ARK server and put inside it the .arkmanager.cfg for it

**Comment by klightspeed** [comment]
You can also create a local config file (containing all of the `ark_<option>` and `arkflag_<option>` options, as well as the `arkserverroot`, `serverMap` and/or `serverMapModId` options) for each server and add the paths of those config files as `configfile_<name>` settings in the main `/etc/arkmanager/arkmanager.cfg` file.  Then to control each instance, use `arkmanager useconfig <name> <command> [<command> ...]`.

**Comment by arkfrancegaming** [comment]
so that will be the main config :

arkstChannel="master"                                               # change it to a different branch to get non-stable versions

# config SteamCMD
steamcmdroot="/home/foufinette"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="foufinette"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/foufinette/Steam/appcache/appinfo.vdf"      # cache of the appinfo command

# config environment
arkserverroot="/game/ARK"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/foufinette/ARK-Backups"                              # path to backup directory
arkwarnminutes="5"                                                 # number of minutes to warn players when using update --warn
# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
ark_RCONEnabled="True"                                            # Enable RCON Protocol
ark_RCONPort="32330"                                                # RCON Port
ark_SessionName="[FR] ARK FRANCE GAMING - arkfrancegaming.com"  # if your session name needs special characters please use the .ini instead
ark_Port="7778"                                                  # ARK server port (default 7778)
ark_QueryPort="27015"                                               # ARK query port (default 27016)
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="****"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="90"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
# config Service
servicename="arkserv"                                               # Name of the service (don't change if you don't know what are you doing)
logdir="/var/log/arktools"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID

# alternate configs
# example for config name "ark1":
config_ark1="/etc/arkmanager/arkmanager2.cfg"

**Comment by arkfrancegaming** [comment]
and that the second config 

arkstChannel="master"                                               # change it to a different branch to get non-stable versions

# config SteamCMD
steamcmdroot="/home/pve"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="pve"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/pve/Steam/appcache/appinfo.vdf"      # cache of the appinfo command

# config environment
arkserverroot="/game/PVE"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/pve/ARK-Backups"                              # path to backup directory
arkwarnminutes="5"                                                 # number of minutes to warn players when using update --warn
# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
ark_RCONEnabled="True"                                            # Enable RCON Protocol
ark_RCONPort="32331"                                                # RCON Port
ark_SessionName="[FR] ARK FRANCE GAMING - arkfrancegaming.com"  # if your session name needs special characters please use the .ini instead
ark_Port="7777"                                                  # ARK server port (default 7778)
ark_QueryPort="27016"                                               # ARK query port (default 27016)
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="******"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="90"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
# config Service
servicename="arkserv"                                               # Name of the service (don't change if you don't know what are you doing)
logdir="/var/log/arktools"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID

# alternate configs
# example for config name "ark1":
#config_ark1="/path/to/config/file"

**Comment by klightspeed** [comment]
If you're using the `useconfig` command, then you need to make sure your ARK user is able to access all directories you specify.  The steamcmd directory does not need to duplicated between configs if you use the same user.

The comment in the default config file in 1.3 on what option to use for alternative configs is incorrect, and should be `configfile_<name>`, not `config_<name>`.

As of 1.4, the init scripts should start all ARK instances specified using alternate configs.

`/etc/arkmanager/arkmanager.cfg`:
```
arkstChannel="master"                                               # change it to a different branch to get non-stable versions

# config SteamCMD
steamcmdroot="/home/foufinette/steamcmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="foufinette"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/foufinette/Steam/appcache/appinfo.vdf"      # cache of the appinfo command

# config environment
arkserverroot="/game/ARK"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/foufinette/ARK-Backups"                              # path to backup directory
arkwarnminutes="5"                                                 # number of minutes to warn players when using update --warn
# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
ark_RCONEnabled="True"                                            # Enable RCON Protocol
ark_RCONPort="32330"                                                # RCON Port
ark_SessionName="[FR] ARK FRANCE GAMING - arkfrancegaming.com"  # if your session name needs special characters please use the .ini instead
ark_Port="7778"                                                  # ARK server port (default 7778)
ark_QueryPort="27015"                                               # ARK query port (default 27016)
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="****"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="90"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
# config Service
servicename="arkserv"                                               # Name of the service (don't change if you don't know what are you doing)
logdir="/var/log/arktools"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID

# alternate configs
# example for config name "ark1":
configfile_pve="/etc/arkmanager/arkmanager-pve.cfg"
```

`/etc/arkmanager/arkmanager-pve.cfg`
```
# config environment
arkserverroot="/game/PVE"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/pve/ARK-Backups"                              # path to backup directory
arkwarnminutes="5"                                                 # number of minutes to warn players when using update --warn
# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
ark_RCONEnabled="True"                                            # Enable RCON Protocol
ark_RCONPort="32331"                                                # RCON Port
ark_SessionName="[FR] ARK FRANCE GAMING - arkfrancegaming.com"  # if your session name needs special characters please use the .ini instead
ark_Port="7777"                                                  # ARK server port (default 7778)
ark_QueryPort="27016"                                               # ARK query port (default 27016)
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="******"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="90"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
```

If instead you're using the per-user config, then the per-server options should include the steamcmd settings and the log directory.  Note that the init scripts do not support per-user configs.

`/home/foufinette/.arkmanager.cfg`:
```
# config SteamCMD
steamcmdroot="/home/foufinette/steamcmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="foufinette"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/foufinette/Steam/appcache/appinfo.vdf"      # cache of the appinfo command

# config environment
arkserverroot="/game/ARK"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/foufinette/ARK-Backups"                              # path to backup directory
arkwarnminutes="5"                                                 # number of minutes to warn players when using update --warn
# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
ark_RCONEnabled="True"                                            # Enable RCON Protocol
ark_RCONPort="32330"                                                # RCON Port
ark_SessionName="[FR] ARK FRANCE GAMING - arkfrancegaming.com"  # if your session name needs special characters please use the .ini instead
ark_Port="7778"                                                  # ARK server port (default 7778)
ark_QueryPort="27015"                                               # ARK query port (default 27016)
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="****"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="90"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
logdir="/home/foufinette/ark-logs"                                          # Logs path (default /var/log/arktools)

```

`/home/pve/.arkmanager.cfg`:
```
# config SteamCMD
steamcmdroot="/home/pve/steamcmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="pve"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/pve/Steam/appcache/appinfo.vdf"      # cache of the appinfo command

# config environment
arkserverroot="/game/PVE"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/pve/ARK-Backups"                              # path to backup directory
arkwarnminutes="5"                                                 # number of minutes to warn players when using update --warn
# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
ark_RCONEnabled="True"                                            # Enable RCON Protocol
ark_RCONPort="32331"                                                # RCON Port
ark_SessionName="[FR] ARK FRANCE GAMING - arkfrancegaming.com"  # if your session name needs special characters please use the .ini instead
ark_Port="7777"                                                  # ARK server port (default 7778)
ark_QueryPort="27016"                                               # ARK query port (default 27016)
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="******"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="90"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
logdir="/home/pve/ark-logs"                                          # Logs path (default /var/log/arktools)
```

**Comment by arkfrancegaming** [comment]
that means that if i reboot one game instance it will reboot both ?

**Comment by klightspeed** [comment]
`arkmanager restart` will only restart the main instance.
`arkamanger useconfig pve restart` will only restart the pve instance
`arkmanager restart --all` as of 1.4 will restart all instances.

**Comment by arkfrancegaming** [comment]
ok so if i'm right 

that's my main cfg :+1:  

arkstChannel="master"                                               # change it to a different branch to get non-stable versions

# config SteamCMD
steamcmdroot="/home/foufinette"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="foufinette"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/foufinette/Steam/appcache/appinfo.vdf"      # cache of the appinfo command

# config environment
arkserverroot="/game/ARK"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/foufinette/ARK-Backups"                              # path to backup directory
arkwarnminutes="5"                                                 # number of minutes to warn players when using update --warn
# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
ark_RCONEnabled="True"                                            # Enable RCON Protocol
ark_RCONPort="32330"                                                # RCON Port
ark_SessionName="[FR] ARK FRANCE GAMING - arkfrancegaming.com"  # if your session name needs special characters please use the .ini instead
ark_Port="7778"                                                  # ARK server port (default 7778)
ark_QueryPort="27015"                                               # ARK query port (default 27016)
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="*****"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="90"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
# config Service
servicename="arkserv"                                               # Name of the service (don't change if you don't know what are you doing)
logdir="/var/log/arktools"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID

# alternate configs
# example for config name "ark1":
configfile_pve="/etc/arkmanager/arkmanager-pve.cfg"

**Comment by arkfrancegaming** [comment]
and that's my arkmanager-pve.cfg with the same steam cfg

arkstChannel="master"                                               # change it to a different branch to get non-stable versions

# config SteamCMD
steamcmdroot="/home/foufinette"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="foufinette"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/foufinette/Steam/appcache/appinfo.vdf"      # cache of the appinfo command

# config environment
arkserverroot="/game/PVE"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/pve/ARK-Backups"                              # path to backup directory
arkwarnminutes="5"                                                 # number of minutes to warn players when using update --warn
# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
ark_RCONEnabled="True"                                            # Enable RCON Protocol
ark_RCONPort="32331"                                                # RCON Port
ark_SessionName="[FR] ARK FRANCE GAMING PVE - arkfrancegaming.com"  # if your session name needs special characters please use the .ini instead
ark_Port="7777"                                                  # ARK server port (default 7778)
ark_QueryPort="27016"                                               # ARK query port (default 27016)
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="taboulet"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="90"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
# config Service
servicename="arkserv"                                               # Name of the service (don't change if you don't know what are you doing)
logdir="/var/log/arktools"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID

# alternate configs
# example for config name "ark1":
#config_ark1="/path/to/config/file"

**Comment by arkfrancegaming** [comment]
is it correct ?

**Comment by klightspeed** [comment]
Yes, that should work.

**Comment by arkfrancegaming** [comment]
then after that, do i need to start another install ?

**Comment by klightspeed** [comment]
You would install the second instance of ARK server the same way you installed the first, except using the `useconfig pve` command before the install command - i.e. `arkmanager useconfig pve install`.  Any other commands - e.g. updating, starting, stopping, executing rcon commands - would be specified the same way - e.g. `arkmanager useconfig pve update`, `arkmanager useconfig pve broadcast "hello"`

**Comment by arkfrancegaming** [comment]
ok thanks, i'm downloading the game, it won't be a problem that there will be twice shootgamer instances ?

**Comment by klightspeed** [comment]
As long as you have enough resources (RAM, CPU cores, HDD space), put the ARK server instances in separate directories, and specify different ports for the different instances, there should be no issue with running multiple instances on the same computer.

**Comment by arkfrancegaming** [comment]
thanks it works :) just one more question about de "-" value like "-log -server" it will be available on 1.4 ?

**Comment by klightspeed** [comment]
With 1.4, to specify an option such as `-log`, add `arkflag_log=true` to arkmanager.cfg.

With PR #206, to specify an option such as `-StructureDestructionTag=DestroySwampSnowStructures`, add `arkopt_StructureDestructionTag=DestroySwampSnowStructures` to arkmanager.cfg.

**Comment by arkfrancegaming** [comment]
ok, when does the 1.4 comes out ?

**Comment by Atriusftw** [comment]
@arkfrancegaming curl -sL http://git.io/vcZd7 | sudo bash -s steam 1.4-dev

**Comment by arkfrancegaming** [comment]
thanks, there is a small problem when i install it :

mkdir: cannot create directory ‘’: No such file or directory

**Comment by klightspeed** [comment]
That error shouldn't cause any harm if you've already previously installed ARK Server Tools - it is a typo in the line that tries to create the directory that holds the Debian systemd arkmanager.init script.

**Comment by arkfrancegaming** [comment]
allright thanks

got a issue for you  :

arkmanager useconfig pve saveworld
Error connecting to server at -e line 31.

arkmanager useconfig pve status
 Server running:   Yes
 Server online:   Yes

i guess the useconfig saveworld doesn't work for now

**Comment by Atriusftw** [comment]
Is RCON configured?

**Comment by arkfrancegaming** [comment]
arkmanager useconfig pve rconcmd "saveworld"
Error connecting to server at -e line 31.
ark_RCONEnabled="True"                                              
ark_RCONPort="32331" 

 iptables -I INPUT -p tcp --dport 32331 -j ACCEPT

**Comment by klightspeed** [comment]
You don't have RCONPort in GameUserSettings.ini do you?

**Comment by arkfrancegaming** [comment]
it's already set but it's the same as the main cfg, any problem with that ?

**Comment by arkfrancegaming** [comment]
it seems to be a rcon connexion problem i can't connect on port 32331

**Comment by klightspeed** [comment]
I found no problem with the passwords being the same.

I was able to duplicate the RCON port not opening by not having the ServerAdminPassword set, and was able to resolve it on my install by setting ServerAdminPassword in GameUserSettings.ini or ark_ServerAdminPassword in the arkmanager config.

**Comment by arkfrancegaming** [comment]
find out the problem, the serveradminpassword in GameUserSettings.ini is not the same as the cfg

**Comment by arkfrancegaming** [comment]
still can't connect, i tried with an rcon software 

1st server 

ark_RCONEnabled="True"                                      
ark_QueryPort="27015" 
ark_RCONPort="32330"   
ark_Port="7778"   

2nd server  
ark_RCONEnabled="True"   
ark_QueryPort="27016"  
ark_RCONPort="32331" 
ark_Port="7777"

**Comment by arkfrancegaming** [comment]
still can't connect to the rcon second server 

arkmanager useconfig pve broadcast "test"
Error connecting to server at -e line 28.

what command do you use to open port 32331 ?

iptables -I INPUT -p tcp --dport 32331 -j ACCEPT ?

thanks

**Comment by klightspeed** [comment]
Please make sure your config is valid.

Does the problem still occur if you comment out `ark_ServerPassword=""` from both of your config files?

Does the problem still occur if you start the problem server first?

Does the problem still occur if you start the server directly?  Since #206, the server command-line is written to `/var/log/arktools/arkserver.log`.  e.g.:
```
Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=10\?OnlyAdminRejoinAsSpectator=true\?Port=7777\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=keyboardcat\?listen -log -server
```

**Comment by arkfrancegaming** [comment]
that's my arkserver.log looks like

i tried another rcon port 

12:00:54: start
12:00:54: Running /game/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=80\?Port=7776\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32333\?ServerAdminPassword=****\?ServerPassword\?SessionName=\[FR\] ARK\ FRANCE\ GAMING\ PVE\ -\ XPx5/TAMx5/DIFFx3\?listen -log
12:00:54: Server PID: 6312
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager: line 461:  4539 Aborted                 "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
12:00:56: Bad PID '6312'; expected '4539'
12:00:56: exited with status 0
12:01:29: server is up

**Comment by klightspeed** [comment]
That says that two servers are running from the same path.

**Comment by arkfrancegaming** [comment]
one is from /game/ARK and the second one /game/PVE

**Comment by arkfrancegaming** [comment]
thanks i will try that :)

**Comment by arkfrancegaming** [comment]
nope the problem still here, it's look like the game isn't using the rcon port

**Comment by klightspeed** [comment]
So the problem stays with that server even if you start it first or start it alone, and it still occurs if you start the server directly?

Do you have any custom settings in GameUserSettings.ini?  It sounds like there may be a setting in there that the game doesn't like.

Try removing GameUserSettings.ini and restarting the problem server.  If that still doesn't work, try removing all of the config files from `ShooterGame/Saved/Config/LinuxServer` and restarting the problem server.

**Comment by arkfrancegaming** [comment]
great ! it's working with a default gameusersettings.ini, i need to find now which command is the problem.

One more thing, in 1.4 when i use a arkmanager update --warn, it doesn't say "saving world" but it does

And when i use arkmanager upgrade-tools
arkmanager v1.4: Checking for updates...
A hotfix is available for v1.3.  Do you wish to install it?

it downgrade the tools.

**Comment by klightspeed** [comment]
> One more thing, in 1.4 when i use a arkmanager update --warn, it doesn't say "saving world" but it does

The server automatically saves the world when it is shut down gracefully.  The `--saveworld` option is just an option for the paranoid.

> And when i use arkmanager upgrade-tools
> arkmanager v1.4: Checking for updates...
> A hotfix is available for v1.3. Do you wish to install it?

That suggests that you have `arkstChannel` set to `master`.

**Comment by arkfrancegaming** [comment]
how can i change that ?

**Comment by klightspeed** [comment]
> how can i change that ?

How do you change what?  Automatically saving the world when the server is shut down gracefully, or changing the `arkstChannel`?

**Comment by arkfrancegaming** [comment]
sorry, the arkstchannel to automatically get the latest 1.4 version

**Comment by klightspeed** [comment]
Change `arkstChannel="master"` to `arkstChannel="1.4-dev"` in /etc/arkmanager/arkmanager.cfg

**Comment by arkfrancegaming** [comment]
thank you !
