### ISSUE TITLE
Negative length at -e line 13. (1.4-dev)

### ISSUE THREAD

**Issue by Atriusftw** [FezVrasta/ark-server-tools#202]
Anyone else getting `Negative length at -e line 13.` when using arkmanager rconcmd?

Can't seem to track down the root cause of this.

Edit: Server version 215.4 (build 789143)

**Comment by klightspeed** [comment]
I was able to replicate it by changing the ServerAdminPassword after starting the server.

```
$ ./arkmanager rconcmd "broadcast hello"
Server received, But no response!! 
 
$ echo 'ark_ServerAdminPassword="penguin"' >>/etc/arkmanager/arkmanager.cfg
$ ./arkmanager rconcmd "broadcast hello"
Negative length at -e line 13.
```

**Comment by Atriusftw** [comment]
@klightspeed I have completely removed that line in the `arkmanager.cfg`
It should fetch the password from `GameUserSettings.ini` in that case.

Haven't changed the password since i launched the server for the first time either.
Maybe the ARK devs did some hidden changes to their RCON?

**Comment by Atriusftw** [comment]
Solved. Turns out that my `GameUserSettings.ini` randomly got corrupt for some reason. Restored from a backup and everything works as usual.
