### ISSUE TITLE
The Parameter "StructureDestructionTag"

### ISSUE THREAD

**Issue by mauzao9** [FezVrasta/ark-server-tools#204]
"* Server Admin Note: One-Time Auto-Structure Demolish on Swamp and Snow Zones: To do this, which you can only execute once after updating to v216, run your server or game with this commandline: -StructureDestructionTag=DestroySwampSnowStructures"

I tried to place StructureDestructionTag=DestroySwampSnowStructures // StructureDestructionTag="DestroySwampSnowStructures"

It didn't delete the structures, how to make this happen using arkmanager?

**Comment by klightspeed** [comment]
Try adding `ark_StructureDestructionTag=DestroySwampSnowStructures` to your arkmanager.cfg

**Comment by mauzao9** [comment]
Had already did so, it ignored it. =/

**Comment by klightspeed** [comment]
@mauzao9 Does upgrading to the latest 1.4-dev (by setting your `arkstChannel` to `1.4-dev` and upgrading), and adding `arkopt_StructureDestructionTag=DestroySwampSnowStructures` resolve this?

**Comment by mauzao9** [comment]
It seems it worked, however the upgrade kinda says 1.2 still i think i need to save config and re-install.

**Comment by klightspeed** [comment]
Remove the `arkstVersion="1.2"` line in your config file.
