### ISSUE TITLE
Can't install private mod

### ISSUE THREAD

**Issue by ty2u** [FezVrasta/ark-server-tools#205]
Hi there,

I know why I can't install, it's private. Well more precisely its friends only. However it tries to publicly download the mod. Where can I input the steam user?

Thanks for the awesome software!

**Comment by FezVrasta** [comment]
We should implement a config setting to specify a custom steam user...

**Comment by ty2u** [comment]
Ok cools. Thanks!

I went and replaced +login anonymous with +login myusername then but I'm still not able to install it for some reason. It says:

ERROR!  Download item ######## failed (File Not Found).

Where ######## is the mod id number. I have tried both being subscribed and unsubscribed to the mod but it doesn't seem to change anything.

Maybe this last ARK update marks it incompatible or something? Tis a shame. I guess we are done until they release a dev kit update if that's the case. Can't even turn my server on.

**Comment by ty2u** [comment]
Well I got my server to run at least. But I had to copy the mod files manually. I'm not sure if there's a difference between windows and linux versions but I had to get it to install the mod on my windows version of ARK and I copied the files off there to the server and it seems to work fine so far. That install mod command doesn't install it properly is all. Perhaps something to do with being for friends only? But that's odd considering the account that I logged in with created it and is subscribed to it. Ah well. Keep up the great work!!!

**Comment by klightspeed** [comment]
Perhaps we should default to mod_branch=Windows instead of mod_branch=Linux.

We could also add a configuration option - e.g. `steamuser=user` - to enable non-anonymous steamcmd login.  The person would need to initialize steamcmd, logging in as their steam user.

**Comment by ty2u** [comment]
I'm not sure if that was the issue because I actually tried on the windows branch but it also produced the same error for me. Maybe it didn't actually try on the windows branch properly? I did switch the option in the config to say Windows and tried but maybe it wasn't implemented yet?

I'm not sure what the deal was but I figured maybe something to do with being a friends only mod but that didn't really make sense to me.

**Comment by klightspeed** [comment]
@ty2u Does the latest 1.4-dev resolve this issue?

**Comment by ty2u** [comment]
Well I did upgrade-tools and I tried to update just now with arkmanager update --update-mods but it gave this:

ERROR!  Download item ########## failed (File Not Found).Mod ########## was not successfully downloaded

Then continues to update the server successfully.

I tried with both Linux and Windows for mod_branch.

**Comment by klightspeed** [comment]
The `mod_branch` is only used for extracting the mod after downloading it.  It won't make any difference with actually downloading it.

`File Not Found` means that the mod associated with the Mod ID you are using either doesn't yet exist or has been deleted.
If the mod were not visible to the steam login you're using, then you'd get an `Access Denied` failure message.
If you were using the wrong App ID, then you would probably get a `Failure` failure message.

**Comment by ty2u** [comment]
The mod definitely exists, but it's accessible to friends only though, 
and the account I configured ark-server-tools to log in with is the 
account that uploaded the mod and I can go to steam and see the mod and 
see I am subscribed to it. It seemed to login fine from what I could see.

The mod was created and uploaded via the ARK dev kit where I set it to 
friends only and works fine when I manually install it on the server. 
Friends who log into the server automatically subscribe and download the 
mod.

Maybe it's a bug in steamcmd then where it's looking for the wrong file?

**Comment by klightspeed** [comment]
With `<ModID>` being the Mod ID you've been using (i.e. what the `##########` you put in above is covering), what does `http://steamcommunity.com/sharedfiles/filedetails/?id=<ModID>` get you?

**Comment by ty2u** [comment]
It shows me the mod like normal when I'm logged in and says the mod does 
not exist when I'm not logged in:

Sorry!
An error was encountered while processing your request:

That item does not exist. It may have been removed by the author.

**Comment by klightspeed** [comment]
The mod needs to be removed from `$steamcmdroot/steamapps/workshop/appworkshop_346110.acf` - either by editing that file and removing the section from the file, or by simply removing the file.

The section will be under `"AppWorkshop"` -> `"WorkshopItemDetails"` -> `"##########"`

```
                "##########"
                {
                        "manifest"              "-1"
                        "timeupdated"           "0"
                        "timetouched"           "1443926927"
                }
```

Details:

I created a Hidden mod, and tried to download it using steam on a separate account:

```
Steam>login xxxxxxxx

Logging in user 'xxxxxxxx' to Steam Public...
Using cached credentials. . .
Logged in OK
Waiting for license info...OK

Steam>workshop_download_item 346110 #########
Downloading item ######### ...
ERROR!  Download item ######### failed (Access Denied).
Steam>quit
```

I also tried to download it as anonymous, first removing its entry from the `appworkshop_346110.acf` file.

```
Steam>login anonymous

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK

Steam>workshop_download_item 346110 #########
Downloading item ######### ...
ERROR!  Download item ######### failed (Access Denied).
Steam>quit
```

I then changed its visibility to Friends only, removed its entry from the appworkshop_346110.acf file, and tried to download it anonymously:

```
Steam>login anonymous

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK

Steam>workshop_download_item 346110 #########
Downloading item ######### ...
ERROR!  Download item ######### failed (Access Denied).
Steam>quit
```

I then tried to download it as my other account, but forgot to remove its entry first:

```
Steam>login xxxxxxxx

Logging in user 'xxxxxxxx' to Steam Public...
Using cached credentials. . .
Logged in OK
Waiting for license info...OK

Steam>workshop_download_item 346110 #########
Downloading item ######### ...
ERROR!  Download item ######### failed (File Not Found).
Steam>quit
```

Ahah - so I removed the entry from appworkshop_346110.acf and tried again (this often times out, especially for large mods):

```
Steam>login killerwolves_cam

Logging in user 'killerwolves_cam' to Steam Public...
Using cached credentials. . .
Logged in OK
Waiting for license info...OK

Steam>workshop_download_item 346110 #########
Downloading item ######### ...ERROR! Timeout downloading item #########
Steam>workshop_download_item 346110 #########
Downloading item ######### ...
Success. Downloaded item ######### to "/home/steam/steamcmd/steamapps/workshop/content/346110/#########" (8441934 bytes) 
Steam>quit
```

**Comment by ty2u** [comment]
Wow awesome!!! I will remove the file and try again when I get the 
chance but sounds like it will do the trick. Thank you very much!!!

**Comment by ty2u** [comment]
Just confirming that this works! Thanks again!
