### ISSUE TITLE
Ark v216.2

### ISSUE THREAD

**Issue by nexxoz** [FezVrasta/ark-server-tools#207]
I updated my ark server to 216.2 and now i cant start my server with arkmanager.This is what i get in my log files on arkmanager

23:28:09: start
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:F:\UE4\UnrealEngine\Engine\Source\Runtime\Engine\Private\SkeletalMesh.cpp] [Li$
Invalid number of texture coordinates
Signal 11 caught.
/usr/local/bin/arkmanager: line 298:  1681 Segmentation fault      (core dumped) "$arkserverroot/$arkse$
23:28:31: exited with status 0

**Comment by klightspeed** [comment]
If you're on 1.3, try `arkmanager install`

If you're on 1.4-dev, try `arkmanager update --validate`

**Comment by justinmasse** [comment]
I'm getting the same thing with ark_TotalConversionMod="506221645"

**Comment by klightspeed** [comment]
@justimmasse is this before or after #206?  Your problem is a known problem where Linux mods don't work with the Linux server, and is different problem to what the OP experienced.

**Comment by justinmasse** [comment]
After #206, is there an available workaround or eta?

**Comment by klightspeed** [comment]
So you've already upgraded arkmanager in the last couple of hours on the 1.4-dev branch?  Is `mod_branch` set in your arkmanager.cfg file?  It should be set to `Windows` if it is set.

**Comment by justinmasse** [comment]
That might be it, I have it set to Linux currently. I'll give that a shot and report back.

**Comment by klightspeed** [comment]
@nexxoz did you fix your problem?

**Comment by nexxoz** [comment]
Yes, i re-install everything and upgrade the server!
