### ISSUE TITLE
bash: line 1: Not: command not found

### ISSUE THREAD

**Issue by justinmasse** [FezVrasta/ark-server-tools#209]
Upgrading from 1.3 to 1.4 for fun but am getting this:

arkmanager upgrade
arkmanager v1.3: Checking for updates...
A new version was found! Do you want to upgrade ARK Server Tools to vNot Found?y
bash: line 1: Not: command not found

I've set arkstchannel="1.4" as well. Any ideas?

**Comment by klightspeed** [comment]
404 Not Found.

The channel "1.4" does not exist.  Try `arkstchannel="1.4-dev"`

**Comment by justinmasse** [comment]
That was the issue, my mistake!

**Comment by justinmasse** [comment]
Solved.
