### ISSUE TITLE
Automatic scheduled updates with broadcast warn messages

### ISSUE THREAD

**Issue by Levistras** [FezVrasta/ark-server-tools#21]
Hi there,

Awesome little server manager, getting it all ready to go on my VPS.

I see in the files that it checks for an update hourly, and if it finds one, broadcasts a reboot warning to the server, and then reboots the server on the next hourly check.

Any option to configure this?  I'd prefer the server check for updates perhaps every 30 minutes, and then once an update is found, Broadcast a server message saying an update is coming in 15 minutes, (and if I'm asking for awesome stuff, perhaps an additional broadcast message 5 minutes before the update happens).

I'd like to make this a little more quick to respond to available server updates.

Cheers,
Levi

**Comment by puseidr** [comment]
its not possible yet, maybe next week when we got rcon support
atm its not possible to send input to the gameserver from outside the game

**Comment by Atriusftw** [comment]
What you are requesting is actually exactly the way i'm going to implement it when RCON becomes available. Initial broadcast when a new update is found, informing players that the server will restart in a set amount of time, then initiate a countdown with broadcasts every 5 minutes or so.

**Comment by Betaman2k** [comment]
Heya
full automatic update ( update / restart ) , with broadcasts ingame that the server will restart ?

**Comment by puseidr** [comment]
read?

**Comment by Atriusftw** [comment]
@Betaman2k That is my plan, yes.

**Comment by Sispheor** [comment]
What you want is not available from now until RCON is released by ARK devs. But you can use the arkdaemon script with crontab to apply update at some fixed time. Yu can also leave a message of the day to notify your connected user. 
The arkdaemon script only work on Debian/Ubuntu and sysinit. Systemd version is comming.

**Comment by Betaman2k** [comment]
can u give me the bash script 4 update and message ingame ( update, message ingame and restart the server )
thx

**Comment by Sispheor** [comment]
the script is called arkdaemon and it's in the repo. Checkout the dev1.1 branch to get the last revision of the file.
Then use
```
/etc/init.d/arkdaemon update
```

**Comment by Betaman2k** [comment]
Heya
ok, and now only a crontab
example 0 0 * * *	/etc/init.d/arkdaemon update

**Comment by FezVrasta** [comment]
- [ ] for an empty checkbox
- [x] for a checked checkbox

**Comment by allquixotic** [comment]
I wrote a little Ruby script that does a check for an update every 10 minutes (adjust as desired) using the rcon native program (released on some guy's blog site) to check for players before updating.

https://gist.github.com/allquixotic/f847a6fd8b606d628694

This script will update the server if the following conditions are satisfied:

 - The server is up. If it's down, we won't try to do anything.
 - No one is currently playing. For most servers there should be at least some time where there are 0 players. We can use this window to update without disturbing anyone.
 - There is an update available on Steam (arkmanager checkupdate).

If any of the conditions is not true, the script will just wait another 10 minutes.

It repeats this process endlessly, forked in the background :)

**Comment by klightspeed** [comment]
Should we perhaps add a --warn option to update (or make it warn by default) if the number of players connected is not zero, in order to support this?  The admin could configure the amount of time it will warn the players for, and it could warn at decreasing intervals - e.g. 1h, 45m, 30m, 20m, 15m, 10m, 5m, 4m, 3m, 2m, 1m30s, 1m, 45s, 30s, 15s, 10s, 5s

**Comment by FezVrasta** [comment]
I like the idea

**Comment by FezVrasta** [comment]
@klightspeed this feature should be implemented with 1.3 right?

**Comment by klightspeed** [comment]
Commit f3df26e would add this.

I can create a pull request with it into either 1.3 or master.

**Comment by klightspeed** [comment]
Unfortunately this is not in master.  Do we want to add it as a hotfix, or add it to 1.4?

**Comment by Atriusftw** [comment]
How can't this be in master? Didn't we just release 1.3?
If we can hotfix it into the release, then lets do that.

**Comment by FezVrasta** [comment]
agree
