### ISSUE TITLE
Cron and arkmanager

### ISSUE THREAD

**Issue by lagonnebula** [FezVrasta/ark-server-tools#213]
Hello, 
I have an issue with some cron on Debian, i put an user specified cron, the one who is set in the arkmanager.cfg, and the commande doesn't seem to be launch. 
I've seen that using root isn't working.
When I launch the script manually with the same user it's working.

``` Bash
arkmanager broadcast "Saving World"
arkmanager saveworld
arkmanager broadcast "Checking update"
arkmanager update --safe
```

``` Bash
chmod 775 update.sh #with steam user
```

When i do 
``` Bash
./update.sh
``` 
There is no problem it's working

but in the crontab -e on the steam user
``` Bash 
*/1 * * * * /directory/to/script/update.sh
```
arkmanager cmd isn't working, if i put some echo "something" >> log i have "something" in the file :/

if you can light my path, it would be great :D

**Comment by klightspeed** [comment]
You need a `#!/bin/sh` at the top of your script file in order to have Linux execute the script as a shell script.

```
#!/bin/sh

arkmanager broadcast "Saving World"
arkmanager saveworld
arkmanager broadcast "Checking update"
arkmanager update --safe
```

**Comment by lagonnebula** [comment]
Oh yeah ! You right, thanks :D I forgot it ... 
But i have the same issue ...

**Comment by klightspeed** [comment]
1.3 also supports specifying multiple commands in a single command.

So if you wanted to e.g. save the world every 10 minutes and check for an update every half hour, you could add the following lines to the steam crontab:
```
*/10 * * * * arkmanager broadcast "Saving World" saveworld
15,45 * * * * arkmanager update --warn
```

**Comment by klightspeed** [comment]
So the following cron line works:
```
*/1 * * * * echo something >>$HOME/test.log
```
yet the following does not work:
```
*/1 * * * * $HOME/ark-update.sh >>$HOME/ark-update.log 2>&1
```

**Comment by lagonnebula** [comment]
it's the idea, it's like all the arkmanager command doesn't work

**Comment by klightspeed** [comment]
Is arkmanager in /usr/local/bin?  i.e. does `type arkmanager` print `arkmanager is /usr/local/bin/arkmanager`?
You may need to specify the full path to arkmanager in the update script:
```
#!/bin/sh

/usr/local/bin/arkmanager broadcast "Saving World"
/usr/local/bin/arkmanager saveworld
/usr/local/bin/arkmanager broadcast "Checking update"
/usr/local/bin/arkmanager update --safe
```

**Comment by lagonnebula** [comment]
Thanks for you answer ! That was the problem !
