### ISSUE TITLE
Add upgrade-config command

### ISSUE THREAD

**Issue by klightspeed** [FezVrasta/ark-server-tools#215]
What are your thoughts on adding a new `upgrade-config` command, which adds new options (such as `mod_appid`) and removes deprecated options (such as `arkstVersion`) from the configuration file?

My current implementation of this is at 25242ce

**Comment by Atriusftw** [comment]
Why don't we just bake it into the installer script, and execute it at a completed upgrade?

**Comment by FezVrasta** [comment]
Yes I think it would make more sense having it as feature of the net installer

**Comment by klightspeed** [comment]
#224 adds this to the install script.
