### ISSUE TITLE
Installation ( curl net installer ) fails with unprivileged user.

### ISSUE THREAD

**Issue by crckdns** [FezVrasta/ark-server-tools#217]
How am I supposed to install the tools without jailing my default shell user and without using sudo?

the documentaion doesn't say anything about it ..and from what I see in the installer shell script, there is no option for nonroot users~

The installation just exits with code 1:
$ curl -sL http://git.io/vtf5N | bash
Something where wrong :(

**Comment by klightspeed** [comment]
`curl -sL http://git.io/vtf5N | bash -s -- --me`

**Comment by crckdns** [comment]
thanks, that helped :) damn.. some stuff I still need to learn about bash :/
hmm why isn't this option listed in the documentation? I'm for sure not alone who isn't creating an extra user and dedicated server for that..

**Comment by klightspeed** [comment]
The `-s` argument tells `bash` to process standard input as a script.
The `--` argument tells `bash` to stop processing arguments - any following arguments are passed to the script.
The `--me` argument is passed to the `netinstall.sh` script, which in turn passes it to the `install.sh` script, to which it means to perform a user-install.

**Comment by crckdns** [comment]
thanks for the explanation!  
hmm while configuration I couldn't find the argument for enabling of bRawSockets which is to be passed via commandline parameter to enable UDP protocol~
I guess, it's not yet planed in v1.4 ~ so I need to modify the script till then?

**Comment by klightspeed** [comment]
```
ark_bRawSockets=""
```

This was added by hotfix #185

**Comment by crckdns** [comment]
wow..damn ok, the repo search didn't show it up :/ 
ok, thanks a lot, I think, it will work for now :)
