### ISSUE TITLE
Port Problem

### ISSUE THREAD

**Issue by obensch** [FezVrasta/ark-server-tools#219]
Hi,
Ubuntu 14.04.3, steamCMD installed, iptables added, router forwarded.
arkmanager status:
Server running:   Yes 
 Server online:   Yes 
Server Name: beoc Server - (v217.2)
Players: 0 / 70
 Server version:   799915 

netstat -lputen:
...
tcp   0  0 0.0.0.0:32330           0.0.0.0:*       LISTEN      1001       122425     3484/ShooterGameSer
...
udp  0  0 0.0.0.0:7778            0.0.0.0:*                       1001       125011      3484/ShooterGameSer
udp  0  0 0.0.0.0:27016          0.0.0.0:*                       1001       113754      3484/ShooterGameSer

I can see/access the server over LAN, but can't find it on arkservers.net and under unofficial servers.
Testing Ports from outside: i can reach 32330, but 27016& 7778 closed...  
TS,Minecraft etc. worked fine in the past :/
any ideas ?

**Comment by crckdns** [comment]
show your iptables rules for those ports please

**Comment by obensch** [comment]
~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:32330
ACCEPT     udp  --  anywhere             anywhere             udp dpt:7778
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:7778
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:27016
ACCEPT     udp  --  anywhere             anywhere             udp dpt:27016

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by klightspeed** [comment]
I'm guessing by "testing your ports from outside", you mean that you used a service that queries TCP ports?  UDP ports 7778 and 27016 are open, not TCP ports 7778 and 27016.  Do you have UDP ports 7778 and 27016 forwarded on your router?

**Comment by TaskManager91** [comment]
Yes we have forwarded the UDP ports definitly in our router too. 

Is port 25 necessary for this game? cause this is one of the ports our ISP blocks (Telekom).

PS: I work on the same server as OP

**Comment by klightspeed** [comment]
No, SMTP (port 25) is not necessary for the server to work.

Could your ISP be blocking well-known gaming ports (including 7778 and 27016)?  If you specify e.g. ports 37778 and 37016, does it work?

**Comment by obensch** [comment]
We changed ark_Port to 37778 and ark_QueryPort to 37016  in arkmanager.cfg.
The server wasn't visible in LAN/arkservers.net, but arkmanager and the logs said everthing was ok. After changing the Ports back to 7778 and 27016 it's visible in LAN only again.

**Comment by klightspeed** [comment]
When you changed the ports, did you also change the Router port forwarding?

I wonder if the Steam only queries a certain range of ports (e.g. 27000-27099)?

**Comment by obensch** [comment]
Every Port was forwarded in our Router. Server wasn't visible in LAN on Ports 27066/8127.
I tried to connect via Shortcut -> steam://connect/192.168.2.200:27066 and got the Error "Unable to query server info to invite"

**Comment by obensch** [comment]
I updated the server to 218, changed the ports to 7777/27015 & cleard entries from iptables.

Server still not visible on arkservers.net or under unofficial, but our friends can now add the server to their favorites via Steam-Client, and join the server ingame (not through their Steam-Client, wired Error there)
Doesn't work fine, but it works :tada: 
So anyone having the same Problem:
clear iptables
open steam client and go to View/Servers/Favorites Tab 
add your server address:port there
open Ark Client, go to favorites -> join server
