### ISSUE TITLE
Autorestart 

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#223]
How the autorestart works ? does it means that when there is a crash server, it will auto reboot ?

Thanks

**Comment by Atriusftw** [comment]
Correct.

If the process closes unexpectedly, it will start up again. (I.e if the server goes down without your order, for example by arkmanager stop, arkmanager update etc.)

**Comment by arkfrancegaming** [comment]
ok great, one more thing i've got an error;

arkmanager saveworld
Negative length at -e line 13.

**Comment by Atriusftw** [comment]
That means that there are some problems with your configuration.
The RCON script can't find your admin password.

If you are using UTF-8 characters in your configuration, it makes it corrupt.

**Comment by arkfrancegaming** [comment]
the last addition in my cfg was that command : ark_bRawSockets=""

**Comment by Atriusftw** [comment]
I was aiming at `GameUserSettings.ini`

ARK doesn't support UTF-8 characters in that configuration.
If your admin password isn't defined in `arkmanager.cfg` the script checks in `GameUserSettings.ini`

**Comment by arkfrancegaming** [comment]
seems to work again after the update

does the .autorestart file is empty, is it normal ?

**Comment by Atriusftw** [comment]
That is normal :) It is just there for removal in-case of a normal shut-down.
