### ISSUE TITLE
Server Tools are ignoring my GameUserSettings.ini

### ISSUE THREAD

**Issue by PromptlyDev** [FezVrasta/ark-server-tools#229]
Hey,

first thanks for the awesome tool.

But I can't configure my server. For example, I added the following to my ShooterGame/Saved/Config/GameUserSettings.ini

allowThirdPersonPlayer=1
AllowCaveBuildingPvE=0
alwaysNotifyPlayerJoined=1
alwaysNotifyPlayerLeft=1
HarvestAmountMultiplier=2.00000
HarvestHealthMultiplier=2.00000
globalVoiceChat=0
TamingSpeedMultiplier=4.00000
XPMultiplier=2.00000
serverPVE=1
ShowMapPlayerLocation=1

After that I restarted 2 times. But the server still has vanilla settings.

My arkmanager.cfg: http://pastebin.com/bmfdR2Q4

**Comment by klightspeed** [comment]
You're putting the config in the wrong place - it belongs in `ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini`

**Comment by PromptlyDev** [comment]
Yep, that is working. But today my file was crypted?
There were no more settings in it, just the following:
^@o^@u^@n^@d^@C^@l^@u^@t^@t^@e^@r^@D^@e^@n^@s^@i^@t^@y^@=^@1^@.^@0^@0^@0^@0^@0^@0^@
^@b^@F^@i^@l^@m^@G^@r^@a^@i^@n^@=^@F^@a^@l^@s^@e^@
^@b^@M^@o^@t^@i^@o^@n^@B^@l^@u^@r^@=^@T^@r^@u^@e^@
^@b^@U^@s^@e^@D^@F^@A^@O^@=^@T^@r^@u^@e^@
^@b^@U^@s^@e^@S^@S^@A^@O^@=^@T^@r^@u^@e^@

**Comment by Atriusftw** [comment]
Your configuration appears to have been corrupted upon start. Make sure you don't have any UTF-8 characters in it. This includes MOTD as it's stored in `GameUserSettings.ini`

**Comment by klightspeed** [comment]
@PromptlyDev that looks like the file was written in UCS16.  Remove the null characters (`tr -d '\0'`), and it should work.
