### ISSUE TITLE
Different Server Instances

### ISSUE THREAD

**Issue by PromptlyDev** [FezVrasta/ark-server-tools#230]
Could you are different server instances to ARK Server Tools? Would be great to manage more then one Server with it.

**Comment by klightspeed** [comment]
Different server instances on the same linux server are already supported:
 - create a config file with instance-specific settings (including `arkserverroot`) for each instance
 - point to each instance-specific config file using the `configfile_<name>=<path>` settings in /etc/arkmanager/arkmanager.cfg
 - use the `useconfig <name>` command to select the instance when running a command - e.g. `arkmanager useconfig ark1 start`

**Comment by PromptlyDev** [comment]
What must I change in the instance specific configs? Only the config eviroment and the ARK server options? A documentation would be nice!

**Comment by klightspeed** [comment]
Any arkmanager.cfg options that are different between instances go into the instance-specific config files.  The settings in the instance-specific config files override those in the main config file.

At a minimum, the following settings should be in the instance-specific config files, as all of these should be different between instances.
* arkserverroot
* ark_RCONPort
* ark_Port
* ark_QueryPort

**Comment by PromptlyDev** [comment]
The /etc/arkmanager/arkmanager.cfg: http://hastebin.com/ayifigoret.cs
The /etc/arkmanager/pve.cfg: http://hastebin.com/izetaripum.cs
The /etc/arkmanager/pvp.cfg: http://hastebin.com/uxabasunap.cs

For example I use the command: arkmanager useconfig pve backup then the backup is creating in the dir PVE-Backups (defined in arkmanager.cfg). Same with starting, stoping etc. Also:
arkmanager useconfig pvp status is returning the status from arkmanager.cfg

**Comment by klightspeed** [comment]
The config pointers in /etc/arkmanager/arkmanager.cfg need to be prefixed with `configfile_`, not `config_`.

**Comment by PromptlyDev** [comment]
Ah, is that new? The default config was with config_

Now, after I enter arkmanager useconfig pvp status I get the following (no server installed):
 Server running:   No
 Server online:   Yes
Server Name: [GER]PlayArk.de PvE Server - Alles auf Anfang - (v218.7)
Players: 29 / 66
 Server version:

When I change the ports, it is working. Doesn't the script support multiple IP's, does it?

Thanks for the fast support!

**Comment by klightspeed** [comment]
The script doesn't currently support getting the status on multi-homed servers.  This can be added as a feature.

**Comment by PromptlyDev** [comment]
Would be great!
