### ISSUE TITLE
Feature: Automatic updates

### ISSUE THREAD

**Issue by Shawak** [FezVrasta/ark-server-tools#233]
First of all, this tool is pretty awesome at the current stage already.

I want to suggess an feature to turn automatic updates on and off, for example there could be a option in the config file like:

```
# enable automatic updates (0 = off, 1 = on, 2 = as soon as the patch occours)
updateModus=1
updateHour=0300 (0300 = 03:00, 1500 = 15:00, etc..)
updateBroadcast="Ark has been updated, the server will update and restart within 15 minutes"
updateTimer=15
```

Something like this would make the tool perfect

Regards

**Comment by klightspeed** [comment]
This can already be done with a cron job and the `arkmanager update --warn` command.

For updating at 03:00, put this in your crontab:
```
0 3 * * * /usr/local/bin/arkmanager update --warn
```

For checking for updates every hour, put this in your crontab:
```
0 * * * * /usr/local/bin/arkmanager update --warn
```

**Comment by Shawak** [comment]
Oh sorry, forgot about the cron jobs, thank you =)
