### ISSUE TITLE
Segmentation fault on arkmanager start

### ISSUE THREAD

**Issue by Torath0071** [FezVrasta/ark-server-tools#239]
Hi, i have an error when i use arkmanager start. 
My server is running correctly with command line : 
```
./ShooterGameServer TheIsland?listen?MaxPlayers=30?ServerAdminPassword=XXXXX?QueryPort=27015?GameModIds=479295136,497086514,499751025 -nosteamclient -game -server -log
```

Thx for your help.

## Error
```
Signal 11 caught.
/usr/local/bin/arkmanager : line 298 : 17484 Segmentation fault  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts"
20:33:40: exited with status 0
20:35:25: start
/usr/local/bin/arkmanager: ligne 328 : ulimit: open files :can not change the limit: Operation not permitted
```

## Config file
```
arkstChannel="master"

steamcmdroot="/home/desktop/steamcmd"
steamcmdexec="steamcmd.sh"
steamcmd_user="desktop"
steamcmd_appinfocache="/home/desktop/Steam/appcache/appinfo.vdf"

arkserverroot="/home/desktop/ARK"
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"
arkbackupdir="/home/desktop/ARK-Backups"
arkwarnminutes="10"

serverMap="TheIsland"
#serverMapModId=""
ark_RCONEnabled="True"
ark_RCONPort="32330"
ark_SessionName="[FR][PVE]Masters of War[LVL200][X10]"
ark_Port="7778"
ark_QueryPort="27015"
ark_ServerPassword=""
ark_ServerAdminPassword="XXXXX"
ark_MaxPlayers="30"
ark_GameModIds="479295136,497086514,499751025"

servicename="MoW-Ark"
logdir="/home/desktop/Bureau/logs"

appid=376030
```

**Comment by klightspeed** [comment]
What are the few lines in the log before that `Signal 11` line?

**Comment by Torath0071** [comment]
it's better in good order :) 
There is the all log 

16:11:16: start
/usr/local/bin/arkmanager: ligne 328 : ulimit: open files : can not change the limit: Operation not permitted
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
/usr/local/bin/arkmanager : line 298 : 17587 Segmentation fault  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts"
16:12:24: exited with status 0

**Comment by Torath0071** [comment]
Any tips for me ?
When i installed the server manually, i've change the limit manually

**Comment by klightspeed** [comment]
I'm guessing that you translated some of the French (as evidenced by the `ligne 328`) to English (as evidenced by `can not change the limit`)?

> Any tips for me ?
> When i installed the server manually, i've change the limit manually

If you are talking about the `ulimit: open files: cannot modify limit: Operation not permitted` line, you can ignore that warning, as it is no longer necessary to increase the open files limit above 1000 with recent versions of the ARK Server.

**Comment by Torath0071** [comment]
yeah i've translated some words.
 i'm talking about 
Signal 11 caught.
/usr/local/bin/arkmanager : line 298 : 17587 Segmentation fault (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts"

What can I try to start the server with arkmanager ?

**Comment by klightspeed** [comment]
What is your current working directory when you run arkmanager?

Given your config, does the following command work:
```
/home/desktop/ARK/ShooterGame/Binaries/Linux/ShooterGameServer "TheIsland?RCONEnabled=True?RCONPort=32330?SessionName=[FR][PVE]Masters of War[LVL200][X10]?Port=7777?QueryPort=27015?ServerPassword?ServerAdminPassword=XXXXX?MaxPlayers=30?GameModIds=479295136,497086514,499751025?listen"
```

**Comment by FezVrasta** [comment]
@Torath0071 may you provide the informations requested? Thanks

**Comment by Torath0071** [comment]
Sorry, I thought I had answered.
I made some changes to the master configuration (mainly in ports) and everything works properly.
Thanks for your help
