### ISSUE TITLE
Add the iptables rules to install script

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#24]
We should add the iptables rules inside the install script, to open the ports automatically.

or at least write a little tutorial in the README to do so.

**Comment by Atriusftw** [comment]
Place it in the README.
The people using these scripts should be able to atleast use iptables.

I know i wouldn't appreciate a script touching my iptables atleast.

**Comment by FezVrasta** [comment]
Yes probably is the way to go

**Comment by FezVrasta** [comment]
I'm not a iptables guru... could these rules work?

```sh
iptables -I INPUT -p tcp --dport 27016 -j ACCEPT
iptables -I INPUT -p udp --dport 27016 -j ACCEPT
iptables -I INPUT -p tcp --dport 7778 -j ACCEPT
iptables -I INPUT -p udp --dport 7778 -j ACCEPT
```

**Comment by N0F3X** [comment]
Yes, it should work, here is mine:
iptables -A INPUT -p udp -d $IP --dport 7778 -j ACCEPT
iptables -A INPUT -p udp -d $IP --dport 27016 -j ACCEPT

**Comment by FezVrasta** [comment]
@N0F3X just UDP? No need for TCP?

**Comment by N0F3X** [comment]
When I do `netstat -plunt` I see that it use only udp and it work fine for me.

**Comment by FezVrasta** [comment]
I'm monitoring with sysdig to see if I see any TCP connection.. so far I see only UDP but I'm waiting a friend to connect so I see how it works when someone is online

**Comment by FezVrasta** [comment]
yup, just udp connection

**Comment by N0F3X** [comment]
Found a problem with closed TCP ports, when they closed the server does not appear in the STEAM server list.

**Comment by FezVrasta** [comment]
Ah
