### ISSUE TITLE
Server dont save engrams!

### ISSUE THREAD

**Issue by Murdock2k** [FezVrasta/ark-server-tools#247]
Hey guys,

i like the script bec im not good with linux, but after i changed servers von g-portal to my linux root server, the engrams reset all the time i restart the server...
i copy/paste all the files in SavedArks and it works , all the dinos/houses are ok and in there place but the engram problem fucks me up...
can someone help with that? sry for my bad english

**Comment by klightspeed** [comment]
What are the permissions on the SavedArks directory and the files therein?

If the ARK server doesn't have permission to write to the `.arkprofile` files, then every time the server restarts any character settings (i.e. engrams, engram points, name, level, etc) will likely reset to the state they were in when you copied the files.

**Comment by Murdock2k** [comment]
ok i try to change them, but i have to wait, i test it in a few hours, thx so far

**Comment by klightspeed** [comment]
A permissions change should take effect immediately.  It will not however take effect retroactively - `.arkprofile` files are only saved when the user logs off, and changing the permissions after stopping the server will only prevent loss of newly acquired EP and Engrams, and will not recover EP or Engrams that should have been saved but were not before the permissions change.

**Comment by Murdock2k** [comment]
yeah you are right, i changed them and after a relogg i have all my engrams i learned before. Thx for the quick help!
Before the change i fast traveled and than i had to skill my skillpoints again for 4 levels (all 4 were made on the new server) and after the change it works like normal :-)

gj and thx again for the quick help ^^
