### ISSUE TITLE
Something went wrong :(

### ISSUE THREAD

**Issue by KongGal** [FezVrasta/ark-server-tools#248]
SteamCMD = Installed & steam user created
when i try and run the "curl -sL http://git.io/vtf5N | sudo bash -s steam" as root it just errors out with Something went wrong :(
When i run it as su - steam it installs fine, creates the /home/steam/bin/arkmanager file but it don't create a log folder, or the arkmanager.cfg file.

Any ideas what to do?

Running Debian

**Comment by klightspeed** [comment]
A workaround for the first error is to run `curl -sL http://git.io/vtf5N | sudo bash -s steam master`

When you run as `su - steam`, it sounds like you are running it with `--me`, as it is performing a user-install.  When it does this, it creates `~/.arkmanager.cfg` and `~/logs/arktools`.
