### ISSUE TITLE
Unknow error 

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#252]
18:32:21: start
18:32:21: Running /game/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?GameModIds=479295136\?MaxPlayers=80\?Port=7776\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32333\?ServerAdminPassword=*****\?SessionName=\[FR\] ARK\ FRANCE\ GAMING\ PVE\ -\ XPx5/TAMx5/DIFFx3\?listen -log -server
18:32:21: Server PID: 29285
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:F:\UE4\UnrealEngine\Engine\Source\Runtime\CoreUObject\Private\UObject\LinkerLoad.cpp] [Line: 3783] 
Bad name index 1497762104/117
Signal 11 caught.
/usr/local/bin/arkmanager: line 513: 29285 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
18:32:32: Bad PID ''; expected '29285'
18:32:32: exited with status 0

**Comment by klightspeed** [comment]
Did you use `installmod` to install the mod, or did you copy it from another install of ARK?  

If it was copied from a Linux install of ARK, we have found that the Linux version of many mods is incompatible with the Linux server.

If it was installed using `installmod` or `--update-mods`, is `modbranch` set in your config file?  If it is set, make sure that it is set to `Windows`, for the above reason.

**Comment by arkfrancegaming** [comment]
it's not causing by a mod aparently, when i desactivate it, it still doesn't work

**Comment by klightspeed** [comment]
Does `arkmanager update --validate` resolve this?

**Comment by arkfrancegaming** [comment]
already did, i did an arkmanager using config pve start, it launch but directly crash

**Comment by arkfrancegaming** [comment]
19:19:52: start
19:19:52: Running /game/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?GameModIds=479295136\?MaxPlayers=80\?Port=7776\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32333\?ServerAdminPassword=\?SessionName=\[FR\] ARK\ FRANCE\ GAMING\ PVE\ -\ XPx5/TAMx5/DIFFx3\?listen -log -server
19:19:52: Server PID: 4469
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:F:\UE4\UnrealEngine\Engine\Source\Runtime\CoreUObject\Private\UObject\LinkerLoad.cpp] [Line: 3783] 
Bad name index 1497762104/117
Signal 11 caught.
/usr/local/bin/arkmanager: line 513:  4469 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
19:20:02: Bad PID ''; expected '4469'
19:20:02: exited with status 0

**Comment by arkfrancegaming** [comment]
still the same start error

**Comment by klightspeed** [comment]
You said that it still happens with the mod disabled, yet I still see `GameModIds=479295136` in your commandline.

**Comment by arkfrancegaming** [comment]
i don't know why, it's remove everywere ...and it still use it in the launch command

**Comment by arkfrancegaming** [comment]
arkstChannel="1.4-dev"                                               # change it to a different branch to get non-stable versions
install_bindir="/usr/local/bin"
install_libexecdir="/usr/local/libexec/arkmanager"
install_datadir="/usr/local/share/arkmanager"

# config SteamCMD
steamcmdroot="/home/foufinette"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="foufinette"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/foufinette/Steam/appcache/appinfo.vdf"      # cache of the appinfo command

# config environment
arkserverroot="/game/PVE"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/foufinette/ARK-Backupspve"                              # path to backup directory
arkwarnminutes="5"                                                 # number of minutes to warn players when using update --warn
arkautorestartfile="ShooterGame/Saved/.autorestart"                 # path to autorestart file
arkBackupPreUpdate="false"                                          # set this to true if you want to perform a backup before updating

# Update warning messages
# Modify as desired, putting the %d replacement operator where the number belongs
msgWarnUpdateMinutes="Le serveur va redemarer pour faire la mise a jour ARK dans %d minutes. Les modifications sont disponibles sur notre site"
msgWarnUpdateSeconds="Le serveur va redemarer pour faire la mise a jour ARK dans %d secondes. Les modifications sont disponibles sur notre site"

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort="32333"                                                # RCON Port
ark_SessionName="[FR] ARK FRANCE GAMING PVE - XPx5/TAMx5/DIFFx3"                                  # if your session name needs special characters please use the .ini instead
ark_Port="7777"                                                     # ARK server port (default 7778)
ark_QueryPort="27016"                                               # ARK query port (default 27016)
#ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword=""                                    # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="80"
#ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
arkflag_log=true
arkflag_server=true
# config Service
servicename="arkserv"                                               # Name of the service (don't change if you don't know what are you doing)
logdir="/var/log/arktools/pve"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID
mod_appid=346110                                                    # App ID for mods

# Mod OS Selection
mod_branch=Linux
# Add mod-specific OS selection below:
#mod_branch_496735411=Windows

# alternate configs
# example for config name "ark1":
# configfile_pve="/etc/arkmanager/arkmanager-pve.cfg"

**Comment by arkfrancegaming** [comment]
[ServerSettings]
ServerAdminPassword=
RCONEnabled=True
RCONPort=32333
PvEDinoDecayPeriodMultiplier=1.000000
KickIdlePlayersPeriod=2400.000000
PerPlatformMaxStructuresMultiplier=1.000000
AutoSavePeriodMinutes=50
DifficultyOffset=3
ListenServerTetherDistanceMultiplier=1.000000
allowThirdPersonPlayer=True
globalVoiceChat=False
ShowMapPlayerLocation=True
AllowFlyerCarryPVE=True
noTributeDownloads=True
NewMaxStructuresInRange=3000
XPMultiplier=5
PvEStructureDecayDestructionPeriod=1
TamingSpeedMultiplier=5
HarvestAmountMultiplier=5
EnablePVPGamma=False
BanListURL="http://playark.com/banlist.txt"
MaxTamedDinos=5000.000000
ResourcesRespawnPeriodMultiplier=0.3
ServerPVE=True
AllowCaveBuildingPvE=true

[/Script/ShooterGame.ShooterGameUserSettings]
MasterAudioVolume=1.000000
MusicAudioVolume=1.000000
SFXAudioVolume=1.000000
VoiceAudioVolume=1.000000
CameraShakeScale=1.000000
bFirstPersonRiding=False
bThirdPersonPlayer=False
bShowStatusNotificationMessages=True
TrueSkyQuality=0.270000
FOVMultiplier=1.000000
GroundClutterDensity=1.000000
bFilmGrain=False
bMotionBlur=True
bUseDFAO=True
bUseSSAO=True
bShowChatBox=True
bCameraViewBob=True
bInvertLookY=False
bFloatingNames=True
bChatBubbles=True
bHideServerInfo=False
bJoinNotifications=False
bCraftablesShowAllItems=True
bLocalInventoryShowAllItems=False
bRemoteInventoryShowAllItems=False
LookLeftRightSensitivity=1.000000
LookUpDownSensitivity=1.000000
GraphicsQuality=2
ActiveLingeringWorldTiles=10
ClientNetQuality=3
LastServerSearchType=0
LastServerSearchHideFull=False
LastServerSearchProtected=False
HideItemTextOverlay=False
bDistanceFieldShadowing=True
LODScalar=1.000000
bToggleToTalk=False
HighQualityMaterials=True
HighQualitySurfaces=True
bTemperatureF=False
bDisableTorporEffect=False
bChatShowSteamName=False
bChatShowTribeName=True
EmoteKeyBind1=0
EmoteKeyBind2=0
bNoBloodEffects=False
bLowQualityVFX=False
bUseVSync=False
MacroCtrl0=
MacroCtrl1=
MacroCtrl2=
MacroCtrl3=
MacroCtrl4=
MacroCtrl5=
MacroCtrl6=
MacroCtrl7=
MacroCtrl8=
MacroCtrl9=
ResolutionSizeX=1280
ResolutionSizeY=720
LastUserConfirmedResolutionSizeX=1280
LastUserConfirmedResolutionSizeY=720
WindowPosX=-1
WindowPosY=-1
bUseDesktopResolutionForFullscreen=False
FullscreenMode=2
LastConfirmedFullscreenMode=2
Version=5

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=3
sg.ShadowQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=3
sg.EffectsQuality=3
sg.TrueSkyQuality=3
sg.GroundClutterQuality=3
sg.IBLQuality=1
sg.HeightFieldShadowQuality=3

[SessionSettings]
SessionName=[FR] ARK FRANCE GAMING PVE - XPx5/TAMx5/DIFFx3

[/Script/Engine.GameSession]
MaxPlayers=80

**Comment by klightspeed** [comment]
First, make sure to change `modbranch=Linux` to `modbranch=Windows` - I was able to exactly duplicate your error by having the Linux version of Mod 479295136 installed and enabled.

Second, is `ark_GameModIds` set in `/etc/arkmanager/arkmanager.cfg`?  If so, and you don't want it in this instance, add `unset ark_GameModIds` to your PVE config.

**Comment by arkfrancegaming** [comment]
i think i've figure it out, the mod is coming from arkmanager.cfg not my arkmanager-pve.cfg don't know why

**Comment by arkfrancegaming** [comment]
20:28:50: start
20:28:50: Running /game/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=80\?Port=7776\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32333\?ServerAdminPassword=****\?SessionName=\[FR\] ARK\ FRANCE\ GAMING\ PVE\ -\ XPx5/TAMx5/DIFFx3\?listen -log -server
20:28:50: Server PID: 14672
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:F:\UE4\UnrealEngine\Engine\Source\Runtime\CoreUObject\Private\UObject\LinkerLoad.cpp] [Line: 3783] 
Bad name index 1497762104/117
Signal 11 caught.
/usr/local/bin/arkmanager: line 513: 14672 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
20:29:00: Bad PID ''; expected '14672'
20:29:00: exited with status 0

**Comment by arkfrancegaming** [comment]
now the mod is off but i still have this error

the second server is working correctly

**Comment by klightspeed** [comment]
What happens if you remove `/game/PVE/ShooterGame/Content/Mods/479295136`?

**Comment by arkfrancegaming** [comment]
20:42:16: start
20:42:16: Running /game/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=80\?Port=7776\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32333\?ServerAdminPassword=\?SessionName=\[FR\] ARK\ FRANCE\ GAMING\ PVE\ -\ XPx5/TAMx5/DIFFx3\?listen -log -server
20:42:16: Server PID: 16711
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
/usr/local/bin/arkmanager: line 513: 16711 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
20:42:58: Bad PID ''; expected '16711'
20:42:58: exited with status 0

**Comment by arkfrancegaming** [comment]
same when i remove it, it starts for some second and then crash

**Comment by klightspeed** [comment]
Sounds like something is still trying to reference that mod, and it's now crashing earlier now that the mod has been removed.

What does `grep -r '479295136' /game/PVE/ShooterGame/Saved` get you?

**Comment by arkfrancegaming** [comment]
but the mod was working fine, but after a restart it does that

**Comment by arkfrancegaming** [comment]
it still crash but a little bit longer

**Comment by arkfrancegaming** [comment]
20:53:37: start
20:53:37: Running /game/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=80\?Port=7776\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32333\?ServerAdminPassword=\?SessionName=\[FR\] ARK\ FRANCE\ GAMING\ PVE\ -\ XPx5/TAMx5/DIFFx3\?listen -log -server
20:53:37: Server PID: 18362
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
/usr/local/bin/arkmanager: line 513: 18362 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
20:54:19: Bad PID ''; expected '18362'
20:54:19: exited with status 0

**Comment by klightspeed** [comment]
The `grep -r '479295136' /game/PVE/ShooterGame/Saved` was to track down **where** the mod is being referenced.

Have you tried replacing `modbranch=Linux` with `modbranch=Windows` in your config file, and running `arkmanager installmod 479295136`?

**Comment by arkfrancegaming** [comment]
it result to nothing, that's means it not here anymore

mod_branch=Windows

in already in, i'm trying arkmanager installmod 479295136 right now

**Comment by arkfrancegaming** [comment]
Mod 479295136 installed

working now !!!

weird story, thanks for the help

**Comment by arkfrancegaming** [comment]
caused by the ark_GameModIds="515195633"  from the arkmanager.cfg to my arkmanager-pve.cfg

**Comment by arkfrancegaming** [comment]
maybe there is a confusion between more than one ark_GameModIds="515195633" in different cfg

**Comment by klightspeed** [comment]
> caused by the ark_GameModIds="515195633" from the arkmanager.cfg to my arkmanager-pve.cfg

The lack of a `GameModIds` parameter in the commandline in the previous few attempts suggests that this was not the cause.  Also, the fact that re-installing mod 479295136 resolved the problem suggests that this mod is being referenced somewhere.

**Comment by arkfrancegaming** [comment]
ok then, thanks for your help
