### ISSUE TITLE
Rconcmd won't take parameters

### ISSUE THREAD

**Issue by pantheis** [FezVrasta/ark-server-tools#253]
When issuing an Rconcmd request, any parameters of the rcon command aren't passed to the server but instead are captured by the arkmanager script.

This results is being unable to issue server commands that require parameters to be passed.

**Comment by klightspeed** [comment]
Pass the entire RCON command as a single argument to `rconcmd` - e.g. `arkmanager rconcmd "broadcast Hello"`

**Comment by pantheis** [comment]
Thanks for the information, you are correct that this works. My suggestion on this would be to update the help included with the script to show the proper way to call the rconcmd command.
