### ISSUE TITLE
Bad Name Index 1641380927/176

### ISSUE THREAD

**Issue by levo-man** [FezVrasta/ark-server-tools#254]
Just installed ark server for the first time and getting this error. Don't know what it means , could anyone help.

**Comment by FezVrasta** [comment]
May you provide more details and context please?

**Comment by levo-man** [comment]
It is ok now. had to re-install four times before i got there but it is working now.
Thank you for your response.

**Comment by klightspeed** [comment]
Sounds like Steam was being a bit silly.
