### ISSUE TITLE
Feature Request: Append to command line arguments via value in .arkmanager.cfg

### ISSUE THREAD

**Issue by Levistras** [FezVrasta/ark-server-tools#26]
Can we add an option in the .arkmanager.cfg to append command line arguments for launch?

I've gone in and manually changed /usr/bin/arkmanager, but this is probably not the best solution.

arkserveropts="TheIsland?SessionName=[ The Saurian Isles ]?QueryPort=$arkserverport?ServerPassword=$arkserverpass?ServerAdminPassword=$arkserverapass?listen?MaxPlayers=30?AllowThirdPersonPlayer=True?ServerCrosshair=True?ServerPVE=True?MapPlayerLocation=True?DifficultyOffset=0"

It would be nice if I could put the part that I'm appending, "?MaxPlayers=30?AllowThirdPersonPlayer=True?ServerCrosshair=True?ServerPVE=True?MapPlayerLocation=True?DifficultyOffset=0?SessionName=[ The Saurian Isles ]", in the .arkmanager.cfg so that it will carry over once the main arkmanager is updated.

Cheers!

**Comment by Atriusftw** [comment]
Might do that. Meanwhile you can add your settings in `/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini`

```
[/script/engine.gamesession]
MaxPlayers=30

[ServerSettings]
AllowThirdPersonPlayer=True
ServerCrosshair=True
ServerPVE=True
MapPlayerLocation=True
DifficultyOffset=0
```

**Comment by Levistras** [comment]
We can't put the Session Name in there though, correct?  
With the current arkmanager setup, I was getting a server with the default "ARK ######" server name.

Also.. another issue I'm having related to this:

Previously I was launching the server with my launch.sh containing this:

# !/bin/sh
ulimit -n 100000
./ShooterGameServer TheIsland?SessionName="[ The Saurian Isles ]"?QueryPort=27015?ServerPassword=<omitted>?ServerAdminPassword=<omitted>?MaxPlayers=30?AllowThirdPersonPlayer=True?ServerCrosshair=True?ServerPVE=True?MapPlayerLocation=True?DifficultyOffset=0?listen -server -log

Placing the " quotes around my Session Name allowed me to have [ The Saurian Isles ] in the server list, no quotes showing around it in the in-game list.


Now that I've moved over to arkmanager and have changed the arkserveropts, I can't get the session name back to the same.  Obviously if I use double-quotes within the existing double-quotes, it doesn't work.  So I've employed the below solution:

 arkserveropts="TheIsland?SessionName="\""[ The Saurian Isles ]"\""?QueryPort=$arkserverp...

Unfortunately now my server name in the game is "[ The Saurian Isles ]" (WITH the quotes).  Is there something I'm missing here to keep my spaces in the Session Name but not show quotes in the game?

It looks alright in the running process but still those quotes show up in game.. thoughts?

30206 pts/5    Ssl+   6:53 /home/steam/ARKServer/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?SessionName="[ The Saurian Isles ]"?QueryPort=27015?ServerPassword=<omitted>?ServerAdminPassword=<omitted>?listen?MaxPlayers=30?AllowThirdPersonPlayer=True?ServerCrosshair=True?ServerPVE=True?MapPlayerLocation=True?DifficultyOffset=0

**Comment by Levistras** [comment]
From what I can see, setting MaxPlayers via the ini files doesn't seem to stick, the server is always 70 players without the command line argument for MaxPlayers 

The rest of my command line arguments seem to load fine from within the INI as you suggest.

**Comment by Atriusftw** [comment]
Hm, thats weird.
Might add maxplayers to the config and arkmanager then.

Thank you for the information :)

**Comment by FezVrasta** [comment]
Related with #36

**Comment by FezVrasta** [comment]
supported in 1.1 dev
