### ISSUE TITLE
Compressed backups

### ISSUE THREAD

**Issue by cronner** [FezVrasta/ark-server-tools#263]
Compressed backups with option for 7z, bz2, gz, xz would be really nice
Around 96MB into:
![backup](https://cloud.githubusercontent.com/assets/5718401/10892713/5de3a4d4-81a5-11e5-94a3-4c41b47178ce.jpg)

**Comment by Budman17r** [comment]
https://github.com/FezVrasta/ark-server-tools/pull/261 would add a partial feature of this

**Comment by klightspeed** [comment]
Are we happy that this is implemented with #275?

**Comment by cronner** [comment]
Maybe update this with option for pigz, option for XX cores, compression level
