### ISSUE TITLE
Convert Steamcmd to arkmanager for reboot/startup

### ISSUE THREAD

**Issue by williamrussellajb** [FezVrasta/ark-server-tools#264]
Hello, 

I've converted my steamcmd install to use your service, everything is working, however, I cannot reboot my server and have it startup normally.

What, where? do I need to edit to get it to reboot normally again?

Thanks.

**Comment by Lihis** [comment]
What is your distro?

**Comment by williamrussellajb** [comment]
Ubuntu 15.04

**Comment by klightspeed** [comment]
I'm guessing that this is with v1.4?

What does `systemctl status arkmanager@main` get you?

**Comment by FezVrasta** [comment]
Do you have problems rebooting the host server (the machine) or just the ARK server instance?

**Comment by williamrussellajb** [comment]
Sorry for the lack of information

@klightspeed 
systemctl status arkmanager@main
● arkmanager@main.service - Daemon to start an ark server instance
   Loaded: loaded (/etc/systemd/system/arkmanager@.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2015-11-02 21:46:41 PST; 12h ago
  Process: 881 ExecStart=/usr/bin/arkmanager useconfig %i run (code=exited, status=203/EXEC)
 Main PID: 881 (code=exited, status=203/EXEC)


@FezVrasta 
When I powercycle the machine (reboot), I wanted to have the server automatically startup, instead I have to ssh in and manually do a "arkmanager start"

Thanks guys!

**Comment by klightspeed** [comment]
What do you get if you search for `arkmanager` in `/var/log/messages`?

Does `/var/log/arktools/arkmanager.log` or `/var/log/arktools/arkserver.log` contain any entries from around 21:46?

**Comment by williamrussellajb** [comment]
arkmanager
username@user:/var/log/arktools$ cat arkmanager.log
02:20:12: stopping
02:20:14: stopped
02:25:42: start
02:31:45: start
02:32:43: start
02:33:35: start
02:33:36: start
02:34:04: start
02:34:59: start
02:35:10: stopping
02:35:30: stopped
02:35:30: start
03:27:05: stopping
03:27:07: stopped
03:27:10: start
20:56:06: start
21:37:43: start
21:52:12: start
22:03:28: stopping
22:03:31: stopped
22:03:37: start
22:20:19: stopping
22:20:22: stopped
22:23:34: start
00:15:39: stopping
00:15:42: stopped
00:16:10: start
00:47:26: stopping
00:47:29: stopped
00:47:35: start
00:53:07: stopping
00:53:10: stopped
00:53:14: start
00:55:06: stopping
00:55:09: stopped
00:59:44: start
11:02:44: stopping
11:02:47: stopped
11:02:47: stop
11:02:48: start
11:02:48: start
11:02:48: restart


arkserverlog
00:16:10: Running /home/steam/servers/ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=70\?Port=7777\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=####?ServerPassword\?SessionName=NAMElisten
00:16:10: Server PID: 12871
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
00:16:57: server is up
Using binned.
4.5.1-0+UE4 7038 3077 402 4
CtrlCHandler: Signal=2
/usr/local/bin/arkmanager: line 516: 12871 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
00:47:33: Bad PID ''; expected '12871'
00:47:33: exited with status 0
00:47:35: start
/usr/local/bin/arkmanager: line 510: ulimit: open files: cannot modify limit: Operation not permitted
00:47:35: Running /home/steam/servers/ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=70\?Port=7776\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=######\?ServerPassword\?SessionName=NAME\?listen
00:47:35: Server PID: 15706
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
00:48:23: server is up
Using binned.
4.5.1-0+UE4 7038 3077 402 4
CtrlCHandler: Signal=2
/usr/local/bin/arkmanager: line 516: 15706 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
00:53:14: Bad PID ''; expected '15706'
00:53:14: exited with status 0
00:53:14: start
/usr/local/bin/arkmanager: line 510: ulimit: open files: cannot modify limit: Operation not permitted
00:53:14: Running /home/steam/servers/ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=70\?Port=7776\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=#####\?ServerPassword\?SessionName=NAME?listen
00:53:14: Server PID: 16281
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
00:54:01: server is up
Using binned.
4.5.1-0+UE4 7038 3077 402 4
CtrlCHandler: Signal=2
/usr/local/bin/arkmanager: line 516: 16281 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
00:55:11: Bad PID ''; expected '16281'
00:55:11: exited with status 0
00:59:44: start
/usr/local/bin/arkmanager: line 510: ulimit: open files: cannot modify limit: Operation not permitted
00:59:44: Running /home/steam/servers/ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=70\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=####?ServerPassword\?SessionName=NAME\?listen
00:59:44: Server PID: 16675
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
01:00:32: server is up
Using binned.
4.5.1-0+UE4 7038 3077 402 4
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
CtrlCHandler: Signal=2
11:02:48: start
/usr/local/bin/arkmanager: line 510: ulimit: open files: cannot modify limit: Operation not permitted
11:02:48: Running /home/steam/servers/ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=70\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=#####\?ServerPassword\?SessionName=NAME?listen
11:02:48: Server PID: 28518
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager: line 516: 16675 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
11:02:50: Bad PID '28518'; expected '16675'
11:02:50: exited with status 0
11:03:40: server is up
@user/var/log/arktools$

**Comment by klightspeed** [comment]
What does `grep 'arkmanager' /var/log/messages` get you?

**Comment by FezVrasta** [comment]
(please wrap your code between &#x60;&#x60;&#x60; to add the needed style
