### ISSUE TITLE
Unable to start the daemon

### ISSUE THREAD

**Issue by ProfX66** [FezVrasta/ark-server-tools#27]
I use Centos 7 and I can't seem to start the daemon at all.

I noticed it wouldn't start after running 'arkmanager start' and just getting the start line print in the log and no screen session.

After that I tried running ''/etc/init.d/arkdaemon start" and it printed out
`Starting ARK manager daemon used to start the server and keep it updated: /etc/init.d/arkdaemon: line 22: daemon: command not found`

I noticed that since I'm using centos I needed to add the following to '/etc/init.d/arkdaemon'
`. /etc/init.d/functions`

After doing that I now get the following when trying to run ''/etc/init.d/arkdaemon start" or "systemctl start arkdaemon"
`Job for arkdaemon.service failed. See 'systemctl status arkdaemon.service' and 'journalctl -xn' for details.`

I ran 'systemctl status arkdaemon.service' and the output was: http://pastebin.com/raw.php?i=sjSCCCzv

I realize using centos seems to be non-standard, but any help would be greatly appreciated.

**Comment by FezVrasta** [comment]
I'm on CentOS as well, I'm going to merge a PR to fix the lot of stuff in debian/ubuntu. then we'll have to write an alternative daemon for centos, because it uses a different init method.

**Comment by ProfX66** [comment]
Alright, sounds good, I'm avail for any testing of the centos stuff once you have it made.

**Comment by Sispheor** [comment]
It should be ok now with the last version

**Comment by ProfX66** [comment]
I am now receiving a similar but different error: http://pastebin.com/raw.php?i=BRDAQUWP

Also on centos 7 `. /lib/lsb/init-functions` does not exist, I modified it to `. /etc/init.d/functions` because that's where my daemon functions seem to be located.

**Comment by Sispheor** [comment]
can you try to add this line on the top of the file

#!/bin/bash

2015-06-21 21:03 GMT+02:00 ProfX66 <notifications@github.com>:

> I am now receiving a similar but different error:
> http://pastebin.com/raw.php?i=BRDAQUWP
>
> Also on centos 7 . /lib/lsb/init-functions does not exist, I modified it
> to . /etc/init.d/functions because that's where my daemon functions seem
> to be located.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/27#issuecomment-113941816>
> .
>



-- 
*Nicolas MARCQ*

**Comment by ProfX66** [comment]
Received a different exit code but same type of error: http://pastebin.com/raw.php?i=4Zw37wRp

**Comment by Sispheor** [comment]
Even with SELINUX disable?

**Comment by ProfX66** [comment]
Yes, SELINUX is disabled on the system.

**Comment by Sispheor** [comment]
Ok, I didn't try the script on this system. Maybe /lib/lsb/init-functions doesn't exist on CentOS7.

@FezVrasta Do we provide support for both Debian and RH familly? ARK dev seems to support only Ubuntu 14.04 from now.

**Comment by FezVrasta** [comment]
Yes I'd love to support support for both. I have a CentOS 6.6 system and honestly I think the RHEL family is the best suited for servers (imho).

**Comment by Sispheor** [comment]
I can see you have an error with log_daemon_msg
/lib/lsb/init-functions doesn't seem to work well under bash. Can you try with this shell:
```
#!/bin/sh 
```
instead of 
```
#!/bin/bash
```
Does the file /lib/lsb/init-functions exist?

**Comment by ProfX66** [comment]
No change.

The entire `/lib/lsb` directory does not exist.

Is there a library I'm missing? or is it just another centos oddity?

**Comment by Sispheor** [comment]
I think the current script will only work on Debian family system. I work on RH version and I'll push it when ready.

**Comment by FezVrasta** [comment]
continue on #30
