### ISSUE TITLE
Option "installmod" question

### ISSUE THREAD

**Issue by tenten36** [FezVrasta/ark-server-tools#270]
Sorry I'm new in the mod business and a little stuck here...
I try to make 

arkmanager installmod 544598236 

happen but only get

```
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
"@NoPromptForPassword" = "1"
```
Also, can you make a small entry on the wiki how all the mod business works with arkmanager. That would be great :D

**Comment by Budman17r** [comment]
is that all that you see, what do you see after that?

Should say downloading and then extracting. 

Also in Arkmanager.cfg you have to modify it to add the mod. 

For example. 
this line

#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify 

After its installed uncomment it (Remove the #) and add the mod to the list.  Remove the ones you do not have.

**Comment by klightspeed** [comment]
For game mods, you put the comma-delimited list of mod ids you want into the `ark_GameModIds` configuration variable.

For a map mod, you put the mod id you want into the `serverMapModId` configuration variable.

For a total-conversion mod, you put the mod id you want into the `ark_TotalConversionMod` configuration variable.

**Comment by tenten36** [comment]
Thanks for the responses, it worked now. Yesterday it just stopped at "Waiting for license info" and nothing happened. I think there was just a problem on valves side.
