### ISSUE TITLE
Dinos not Pooping and Boxes Disappearing

### ISSUE THREAD

**Issue by MithrimTAoW** [FezVrasta/ark-server-tools#276]
I'm running a server using Arkmanager and having the issues pointed out in the title. I've commented out anything that appears in the /etc/arkmanager/arkmanager.cfg AND the gameusersettings.ini file so they don't bump heads, unless this isn't what i should have done. If anyone knows of a permenant fix to these issues please let me know. Thank you! below is a copy of my GameUserSettings.ini file

[/Script/ShooterGame.ShooterGameUserSettings]
MasterAudioVolume=1.000000
MusicAudioVolume=1.000000
SFXAudioVolume=1.000000
VoiceAudioVolume=1.000000
CameraShakeScale=1.000000
bFirstPersonRiding=False
bThirdPersonPlayer=False
bShowStatusNotificationMessages=True
TrueSkyQuality=0.270000
FOVMultiplier=1.000000
GroundClutterDensity=1.000000
bFilmGrain=False
bMotionBlur=True
bUseDFAO=True
bUseSSAO=True
bShowChatBox=True
bCameraViewBob=True
bInvertLookY=False
bFloatingNames=True
bChatBubbles=True
bHideServerInfo=False
bJoinNotifications=False
bCraftablesShowAllItems=True
LookLeftRightSensitivity=1.000000
LookUpDownSensitivity=1.000000
GraphicsQuality=2
ActiveLingeringWorldTiles=10
ClientNetQuality=3
LastServerSearchType=0
LastServerSearchHideFull=False
LastServerSearchProtected=False
HideItemTextOverlay=False
bDistanceFieldShadowing=True
LODScalar=1.000000
bToggleToTalk=False
HighQualityMaterials=True
HighQualitySurfaces=True
bTemperatureF=False
bDisableTorporEffect=False
bChatShowSteamName=False
bChatShowTribeName=True
EmoteKeyBind1=0
EmoteKeyBind2=0
bNoBloodEffects=False
bLowQualityVFX=False
bUseVSync=False
MacroCtrl0=
MacroCtrl1=
MacroCtrl2=
MacroCtrl3=
MacroCtrl4=
MacroCtrl5=
MacroCtrl6=
MacroCtrl7=
MacroCtrl8=
MacroCtrl9=
ResolutionSizeX=1280
ResolutionSizeY=720
LastUserConfirmedResolutionSizeX=1280
LastUserConfirmedResolutionSizeY=720
WindowPosX=-1
WindowPosY=-1
bUseDesktopResolutionForFullscreen=False
FullscreenMode=2
LastConfirmedFullscreenMode=2
Version=5

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=3
sg.ShadowQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=3
sg.EffectsQuality=3
sg.TrueSkyQuality=3
sg.GroundClutterQuality=3
sg.IBLQuality=1
sg.HeightFieldShadowQuality=3

[ServerSettings]
ShowMapPlayerLocation=True
ProximityChat=False
NoTributeDownloads=True
AllowThirdPersonPlayer=True
DontAlwaysNotifyPlayerJoined=False
AdminLogging=True
ServerAdminPassword=REDACTED
DifficultyOffset=4.000000
NewMaxStructuresInRange=10000.000000
NightTimeSpeedScale=2.000000
DayTimeSpeedScale=0.500000
XPMultiplier=4.000000
TamingSpeedMultiplier=4.000000
HarvestAmountMultiplier=4.000000
PlayerCharacterWaterDrainMultiplier=0.500000
PlayerCharacterFoodDrainMultiplier=0.500000
DinoCharacterHealthRecoveryMultiplier=2.000000
DinoCountMultiplier=1.25
PvEDinoDecayPeriodMultiplier=1.000000
KickIdlePlayersPeriod=2400.000000
PerPlatformMaxStructuresMultiplier=4.0000
AutoSavePeriodMinutes=45.000000
ListenServerTetherDistanceMultiplier=1.000000
MaxTamedDinos=4000.000000
AllowFlyerCarryPvE=True
PreventDownloadSurvivors=True
PreventDownloadItems=True
PreventDownloadDinos=True
pvpstructuredecay=true
ResourceNoReplenishRadiusPlayers=.4
ResourceNoReplenishRadiusStructures=.4
MaxPlatformSaddleStructureLimit=4000
PvEStructureDecayPeriodMultiplier=0.5
EnablePvPGamma=False
ServerPassword=
RCONEnabled=True
RCONPort=32330

[MessageOfTheDay]
Message=

[SessionSettings]
SessionName=The Ark of War 4x All WIPED 10/28

[/Script/Engine.GameSession]
MaxPlayers=100

**Comment by klightspeed** [comment]
This sounds like the `GlobalItemDecompositionTimeMultiplier` is 0

Check your `Game.ini` file.

**Comment by MithrimTAoW** [comment]
my Game.ini file

[/script/shootergame.shootergamemode]
OverrideMaxExperiencePointsPlayer=250000
OverrideMaxExperiencePointsDino=250000
LevelExperienceRampOverrides=(ExperiencePointsForLevel[0]=5,ExperiencePointsForLevel[1]=20,ExperiencePointsForLevel[2]=40,ExperiencePointsForLevel[3]=70,ExperiencePointsForLevel[4]=120,ExperiencePointsForLevel[5]=190,ExperiencePointsForLevel[6]=270,ExperiencePointsForLevel[7]=360,ExperiencePointsForLevel[8]=450,ExperiencePointsForLevel[9]=550,ExperiencePointsForLevel[10]=660,ExperiencePointsForLevel[11]=780,ExperiencePointsForLevel[12]=910,ExperiencePointsForLevel[13]=1050,ExperiencePointsForLevel[14]=1200,ExperiencePointsForLevel[15]=1360,ExperiencePointsForLevel[16]=1530,ExperiencePointsForLevel[17]=1710,ExperiencePointsForLevel[18]=1900,ExperiencePointsForLevel[19]=2100,ExperiencePointsForLevel[20]=2310,ExperiencePointsForLevel[21]=2530,ExperiencePointsForLevel[22]=2760,ExperiencePointsForLevel[23]=3000,ExperiencePointsForLevel[24]=3250,ExperiencePointsForLevel[25]=3510,ExperiencePointsForLevel[26]=3780,ExperiencePointsForLevel[27]=4060,ExperiencePointsForLevel[28]=4350,ExperiencePointsForLevel[29]=4650,ExperiencePointsForLevel[30]=4960,ExperiencePointsForLevel[31]=5280,ExperiencePointsForLevel[32]=5610,ExperiencePointsForLevel[33]=5950,ExperiencePointsForLevel[34]=6300,ExperiencePointsForLevel[35]=6660,ExperiencePointsForLevel[36]=7030,ExperiencePointsForLevel[37]=7410,ExperiencePointsForLevel[38]=7800,ExperiencePointsForLevel[39]=8200,ExperiencePointsForLevel[40]=8610,ExperiencePointsForLevel[41]=9030,ExperiencePointsForLevel[42]=9460,ExperiencePointsForLevel[43]=9900,ExperiencePointsForLevel[44]=10350,ExperiencePointsForLevel[45]=10810,ExperiencePointsForLevel[46]=11280,ExperiencePointsForLevel[47]=11760,ExperiencePointsForLevel[48]=12250,ExperiencePointsForLevel[49]=12750,ExperiencePointsForLevel[50]=13260,ExperiencePointsForLevel[51]=13780,ExperiencePointsForLevel[52]=14310,ExperiencePointsForLevel[53]=14850,ExperiencePointsForLevel[54]=15400,ExperiencePointsForLevel[55]=15960,ExperiencePointsForLevel[56]=16530,ExperiencePointsForLevel[57]=17110,ExperiencePointsForLevel[58]=17700,ExperiencePointsForLevel[59]=18850,ExperiencePointsForLevel[60]=21078,ExperiencePointsForLevel[61]=22448,ExperiencePointsForLevel[62]=23908,ExperiencePointsForLevel[63]=25462,ExperiencePointsForLevel[64]=27498,ExperiencePointsForLevel[65]=30248,ExperiencePointsForLevel[66]=34786,ExperiencePointsForLevel[67]=40004,ExperiencePointsForLevel[68]=46804,ExperiencePointsForLevel[69]=54761,ExperiencePointsForLevel[70]=63713,ExperiencePointsForLevel[71]=73000,ExperiencePointsForLevel[72]=85000,ExperiencePointsForLevel[73]=98000,ExperiencePointsForLevel[74]=112000,ExperiencePointsForLevel[75]=127500,ExperiencePointsForLevel[76]=144500,ExperiencePointsForLevel[77]=163500,ExperiencePointsForLevel[78]=184500,ExperiencePointsForLevel[79]=188250,ExperiencePointsForLevel[80]=191500,ExperiencePointsForLevel[81]=194750,ExperiencePointsForLevel[82]=198000,ExperiencePointsForLevel[83]=201250,ExperiencePointsForLevel[84]=204500,ExperiencePointsForLevel[85]=207750,ExperiencePointsForLevel[85]=207750,ExperiencePointsForLevel[86]=211000,ExperiencePointsForLevel[87]=214250,ExperiencePointsForLevel[88]=217500,ExperiencePointsForLevel[89]=220750,ExperiencePointsForLevel[90]=224000,ExperiencePointsForLevel[91]=227250,ExperiencePointsForLevel[92]=230500,ExperiencePointsForLevel[93]=233750,ExperiencePointsForLevel[94]=237000,ExperiencePointsForLevel[95]=240250,ExperiencePointsForLevel[96]=243500,ExperiencePointsForLevel[97]=246750,ExperiencePointsForLevel[98]=248000,ExperiencePointsForLevel[99]=250000)
LevelExperienceRampOverrides=(ExperiencePointsForLevel[0]=5,ExperiencePointsForLevel[1]=20,ExperiencePointsForLevel[2]=40,ExperiencePointsForLevel[3]=70,ExperiencePointsForLevel[4]=120,ExperiencePointsForLevel[5]=190,ExperiencePointsForLevel[6]=270,ExperiencePointsForLevel[7]=360,ExperiencePointsForLevel[8]=450,ExperiencePointsForLevel[9]=550,ExperiencePointsForLevel[10]=660,ExperiencePointsForLevel[11]=780,ExperiencePointsForLevel[12]=910,ExperiencePointsForLevel[13]=1050,ExperiencePointsForLevel[14]=1200,ExperiencePointsForLevel[15]=1360,ExperiencePointsForLevel[16]=1530,ExperiencePointsForLevel[17]=1710,ExperiencePointsForLevel[18]=1900,ExperiencePointsForLevel[19]=2100,ExperiencePointsForLevel[20]=2310,ExperiencePointsForLevel[21]=2530,ExperiencePointsForLevel[22]=2760,ExperiencePointsForLevel[23]=3000,ExperiencePointsForLevel[24]=3250,ExperiencePointsForLevel[25]=3510,ExperiencePointsForLevel[26]=3780,ExperiencePointsForLevel[27]=4060,ExperiencePointsForLevel[28]=4350,ExperiencePointsForLevel[29]=4650,ExperiencePointsForLevel[30]=4960,ExperiencePointsForLevel[31]=5280,ExperiencePointsForLevel[32]=5610,ExperiencePointsForLevel[33]=5950,ExperiencePointsForLevel[34]=6300,ExperiencePointsForLevel[35]=6660,ExperiencePointsForLevel[36]=7030,ExperiencePointsForLevel[37]=7410,ExperiencePointsForLevel[38]=7800,ExperiencePointsForLevel[39]=8200,ExperiencePointsForLevel[40]=8610,ExperiencePointsForLevel[41]=9030,ExperiencePointsForLevel[42]=9460,ExperiencePointsForLevel[43]=9900,ExperiencePointsForLevel[44]=10350,ExperiencePointsForLevel[45]=10810,ExperiencePointsForLevel[46]=11280,ExperiencePointsForLevel[47]=11760,ExperiencePointsForLevel[48]=12250,ExperiencePointsForLevel[49]=12750
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=34
OverridePlayerLevelEngramPoints=34
OverridePlayerLevelEngramPoints=34
OverridePlayerLevelEngramPoints=34
OverridePlayerLevelEngramPoints=34
OverridePlayerLevelEngramPoints=34
OverridePlayerLevelEngramPoints=34
OverridePlayerLevelEngramPoints=35
OverridePlayerLevelEngramPoints=36
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=200
Banlist="http://playark.com/banlist.txt"
CropGrowthSpeedMultiplier=4
CropDecaySpeedMultiplier=4
GlobalSpoilingTimeMultiplier=4
GlobalItemDecompositionTimeMultiplier=4
GlobalCorpseDecompositionTimeMultiplier=4
PerLevelStatsMultiplier_Player[7]=2.0
DinoSpawnWeightMultipliers=(DinoNameTag=Direwolf,SpawnWeightMultiplier=1.0,OverrideSpawnLimitPercentage=true,SpawnLimitPercentage=50.0)
DinoSpawnWeightMultipliers=(DinoNameTag=Trilobite,SpawnWeightMultiplier=0.1,OverrideSpawnLimitPercentage=true,SpawnLimitPercentage=1.0)
DinoSpawnWeightMultipliers=(DinoNameTag=Ant,SpawnWeightMultiplier=0.1,OverrideSpawnLimitPercentage=true,SpawnLimitPercentage=3.0)
DinoSpawnWeightMultipliers=(DinoNameTag=Coel,SpawnWeightMultiplier=0.1,OverrideSpawnLimitPercentage=true,SpawnLimitPercentage=3.0)
DinoSpawnWeightMultipliers=(DinoNameTag=Piranha,SpawnWeightMultiplier=0.1,OverrideSpawnLimitPercentage=true,SpawnLimitPercentage=3.0)
DinoSpawnWeightMultipliers=(DinoNameTag=Bat,SpawnWeightMultiplier=0.1,OverrideSpawnLimitPercentage=true,SpawnLimitPercentage=1.0)
MatingIntervalMultiplier=0.75
EggHatchSpeedMultiplier=4.0
BabyMatureSpeedMultiplier=4.0
PerPlatformMaxStructureMultiplier=2.0
ResourceNoReplenishRadiusPlayers=0.5
ResourceNoReplenishRadiusStructures=0.5

**Comment by Lihis** [comment]
You could check that yourself without pasting game.ini. The value seems to be 4 for the option @kliightspeed asked.

Have you tried restarting the server?

**Comment by klightspeed** [comment]
Does appending `.0` (i.e. changing `=4` to `=4.0`) to the multipliers resolve this?
There's also a `PoopIntervalMultiplier` setting that was added in 218.0 - does adding this fix the dinos not pooping

**Comment by MithrimTAoW** [comment]
My apologies for the spam Lihis, I just wanted to give him the option to see what was in there in case I was missing/overlooking something. I will add the .0 to the end of the multipliers as well as add the poopintervalmultiplier string and get back to you, will append changes for next server restart

**Comment by Lihis** [comment]
No problem. I have not faced dino pooping issue, but dropped items disappearing bug I have fixed by restarting the server.
