### ISSUE TITLE
ark_PvPStructureDecay="true".... no?

### ISSUE THREAD

**Issue by dahlskebank** [FezVrasta/ark-server-tools#277]
Am I the idiot here? All other changes to arkmanager.cfg are added to GameUserSettings.ini. At least the minor changes I have made.

Is it a flag now?

**Comment by klightspeed** [comment]
The `ark_...` settings in `arkmanager.cfg` are passed to `ShooterGameServer` as options.  They are not directly added to `GameUserSettings.ini` by arkmanager.  It is the `ShooterGameServer` itself that adds certain options into `GameUserSettings.ini`.

It's possible that `PvPStructureDecay` is not one of the options that is copied from the command-line options to `GameUserSettings.ini`

**Comment by dahlskebank** [comment]
Ah... I'll look more into it then.
