### ISSUE TITLE
Server command

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#278]
Hi,

i wanted to add those two commandlines 

arkopt_bForceAllStructureLocking=True
arkopt_AutoDestroyOldStructuresMultiplier=1.0

Is that correct ?

thanks

**Comment by klightspeed** [comment]
Those options should add the following options to the `ShooterGameServer` commandline:
```
ShooterGameServer ... -bForceAllStructureLocking=True -AutoDestroyOldStructuresMultiplier=1.0
```

**Comment by arkfrancegaming** [comment]
GameUserSettings.ini ?

**Comment by klightspeed** [comment]
There is currently no arkmanager command or option that directly adds or removes options in a section of `GameUserSettings.ini` or `Game.ini`.

**Comment by arkfrancegaming** [comment]
thanks i will try that then :)

**Comment by arkfrancegaming** [comment]
how about this one : 

?ForceAllStructureLocking=true

**Comment by klightspeed** [comment]
For that, you'd add `ark_ForceAllStructureLocking=true` to your `arkmanager.cfg` file.

**Comment by arkfrancegaming** [comment]
and if there is a value like ForceAllStructureLocking=1.0 ?
