### ISSUE TITLE
Crontab example

### ISSUE THREAD

**Issue by williamrussellajb** [FezVrasta/ark-server-tools#279]
Im running ubuntu 15.04, 

Under my steam user I've tried to add a cronjob

crontab -e
```
*/15 * * * * arkmanager update --safe --warn
 * * * * * arkmanager broadcast "hello"
```
I'm trying to have it check for updates every 15 minutes, if one is available, save and warn the user.
The broadcast is just a test to see if I can send "Hello" if anything is working.

Does this look correct?

**Comment by klightspeed** [comment]
The first cronjob should check for updates every 15 minutes, and if an update is detected, then it should warn players for a certain amount of time (60 minutes by default) then update the server.
I'm not sure if the second cronjob will work, though if it does (you may need to remove the leading space or specify an interval in the minute column - e.g. `*/1`) it should broadcast "hello" once every minute.

**Comment by TuRz4m** [comment]
I don't think arkmanager is in the cron path. Try putting the full path to arkmanage (`whereis arkmanager`).
You can check cron logs with `grep CRON /var/log/syslog` on a default installation.

**Comment by williamrussellajb** [comment]
Thanks guys!

```
*/15 * * * * /usr/local/bin/arkmanager arkmanager update --safe --warn
*/1 * * * * /usr/local/bin/arkmanager arkmanager broadcast "hello"
```

The broadcast worked, so I will assume the update will too :) 
I set my update warning to 5 minutes, and it checks for an update every 15 minutes, do you think that is to frequent?

**Comment by FezVrasta** [comment]
I think it's not a problem as long your server can handle it. Maybe 5 minutes of delay from the warning is a bit short, I'd set at least 15 minutes between the warning and the update/restart.

**Comment by Lihis** [comment]
@FezVrasta @klightspeed I'm writing script that should automate the ARK updates with help of arkmanager, currently the script updates the server as soon as there is no players on the server. I wrote it for myself so it does more than just the automatic update and it need more testing but if you're interested I will publish.

**Comment by FezVrasta** [comment]
Yes feel free to share, we may add it inside the wiki or integrate in the source.

**Comment by Lihis** [comment]
Great, I will let you know when it's released.

**Comment by arkfrancegaming** [comment]
Will it possible to add an auto check up update and do a warn after that in the next release? Thanks

**Comment by Lihis** [comment]
I made some script which can perform automatic updates, and manual updates too.

Use it with:
``*/5 * * * * /usr/bin/arkwrapper --cron-update``

Script checks updates every hour. If update found, then the script updates the server when there is no players connected.

Script is "arkwrapper" and can be found from: http://git.lihis.net/Lihis/arkwrapper. Before using the script make folder "/etc/arkwrapper".

**Comment by arkfrancegaming** [comment]
The problem is that there are always players on my server :)

**Comment by Lihis** [comment]
That is the only down side on my script :(

**Comment by FezVrasta** [comment]
We may include the features on arkmanager

**Comment by TuRz4m** [comment]
Why not add a `--ifempty` option which checks if the server is empty and updates it ?
Then you can `update --ifempty` every half hour with a crontab and add another crontab at midnight with a `update --warn` which forces the update like this :  
`0 0 * * * /usr/local/bin/arkmanager update --warn` 
`*/30 * * * * /usr/local/bin/arkmanager update --ifempty `

**Comment by FezVrasta** [comment]
I think we already support it, I'm not sure...

**Comment by klightspeed** [comment]
ARK Server Tools doesn't currently support this, but support can be added in v1.5

**Comment by FezVrasta** [comment]
Umh I was sure someone mentioned it somewhere in the issues then

**Comment by arkfrancegaming** [comment]
great !

**Comment by arkfrancegaming** [comment]
can you also add when there is players connect warned by a --warn please

**Comment by klightspeed** [comment]
As in stop the warnings and immediately perform the update if nobody is connected?

**Comment by arkfrancegaming** [comment]
nope just simply do a checkupdate every x minutes and if there is an update, do it with the --warn even if there are players on it

**Comment by klightspeed** [comment]
`arkmanager update --warn` will:

* Perform a `checkupdate`. If an update is not available then exit.  Otherwise, if an update is available, then continue to the next step.
* Warn the players for the configured interval.  Continue to the next step only after the configured interval has expired
* If the server has already been restarted (e.g. for a manually-initiated update), then exit.
* Shutdown the server
* Update the server
* Restart the server if it had been running.

Unfortunately, without monitoring who is connecting, it can't send server messages to the players connecting telling them that the server will be restarting in x minutes for an update.  To do that, it'd have to do a `rconcmd "ServerChatToPlayer $player $msg"` for each player in `rconcmd ListPlayers` every x minutes.  Either that, or it'd require a mod that can do that.

**Comment by Lihis** [comment]
Is ``ServerChatTo`` and ``ServerChatToPlayer`` even implemented to the ARK's rcon? I have been unable to send those messages via rcon program and now tested with ``arkmanager rconcmd`` but I always get error like: 

``'ServerChatToPlayer': Bad or missing property 'PlayerName'``
``'ServerChatTo': Bad or missing property 'SteamID'``

Works from ARK admin-manager though, but that does not help if you can't be in the server at that moment.

**Comment by klightspeed** [comment]
You need to quote the entire RCON command - e.g. `arkmanager rconcmd "ServerChatToPlayer <player> <message>"`

**Comment by arkfrancegaming** [comment]
klightspeed, the --warn command use a broadcast so it can works no ?

**Comment by klightspeed** [comment]
`arkmanager update --warn` broadcasts the time remaining at regular intervals.

**Comment by arkfrancegaming** [comment]
i know, is it possible to do it auto with a cron or something, for exemple : the command do a checkupdate every 10 min, if there is an update the server use an arkmanager update --warn and do the update on is own. no need to do it manually

**Comment by klightspeed** [comment]
Cron job:
```
*/10 * * * * /usr/local/bin/arkmanager update --warn
```

**Comment by arkfrancegaming** [comment]
great thanks

**Comment by Lihis** [comment]
@klightspeed Still no go, I tried it as you suggested, eg: ``arkmanager rconcmd "ServerChatToPlayer Lihis Test"``. Still same error, ``Bad or missing property 'PlayerName'``. But, I found that it works when you quote the player name, like this ``arkmanager rconcmd "ServerChatToPlayer \"Lihis\" Test"``.

**Comment by arkfrancegaming** [comment]
hi again, i'm writing back, the cron is working but the arkmanager update --warn does a restart even if there is no update. is it possible to check it first and then do an update and if there is no update it does nothing
