### ISSUE TITLE
Keep the master branch stable

### ISSUE THREAD

**Issue by Sispheor** [FezVrasta/ark-server-tools#28]
I think we should keep the master branch stable. It's best practice that can help us a lot.
What to do:
- Tag the current version like v1.0
- Create a new branch called dev-1.1
- Create a millestone called v1.1
- Bind opened issues to the millestone

When a dev branch is ready and tested we can merge it into the master.

**Comment by Atriusftw** [comment]
:+1:

**Comment by FezVrasta** [comment]
Yup good idea, this project is growing fast :) I didn't expect it

**Comment by FezVrasta** [comment]
Created the development branch dev#1.1, any new feature should be pushed there.

Any fix of the current features should be pushed to the master stable branch instead.
