### ISSUE TITLE
Hung on Update:  

### ISSUE THREAD

**Issue by Budman17r** [FezVrasta/ark-server-tools#282]
![image](https://cloud.githubusercontent.com/assets/8853458/10971016/a5aa47ca-8397-11e5-8dd0-e887dc403836.png)

Appears to get hung, if I back out, and "install the mod again" it will work the next time.

**Comment by klightspeed** [comment]
Is this during the mod update (i.e. `arkmanager update --update-mods`) or during the mod install (`arkmanager installmod 543828831`)?

It it's during `arkmanager update --update-mods`, then note that immediately after downloading the mods it will check the modification times of the downloaded mods against those of the installed mods, and this can take a while, especially with mods with lots of files, and especially if those files haven't been accessed in a while and their inodes are no longer in cache.

**Comment by klightspeed** [comment]
ping @Budman17r Is this still occurring?

**Comment by FezVrasta** [comment]
Closing for lack of feedback, feel free to reply if there's any follow up.
