### ISSUE TITLE
Server Wont Start?

### ISSUE THREAD

**Issue by FiberSprite** [FezVrasta/ark-server-tools#284]
My server wont start apparently. it says its on but its not in my favorites list. when i start it using a start.sh file it works just fine though..

**Comment by Atriusftw** [comment]
Post your `arkmanager.cfg`
Blank out any sensitive information, like passwords for example.

**Comment by FezVrasta** [comment]
and wrap it in this way:

    ```
    pasted text
    ```

Thanks :)

**Comment by FiberSprite** [comment]
`arkstChannel="master"                                               # change it to a different branch to get non-stable versions
install_bindir="/usr/local/bin"
install_libexecdir="/usr/local/libexec/arkmanager"
install_datadir="/usr/local/share/arkmanager"

# config SteamCMD
steamcmdroot="/home/steam/steamcmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="steam"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/steam/Steam/appcache/appinfo.vdf"      # cache of the appinfo command
#steamlogin="flashman787"                                             # Uncomment this to specify steam login instead of using anonymous login

# config environment
arkserverroot="/home/steam/ark_dedi"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/steam/ARK-Backups"                              # path to backup directory
arkwarnminutes="60"                                                 # number of minutes to warn players when using update --warn
arkautorestartfile="ShooterGame/Saved/.autorestart"                 # path to autorestart file
arkBackupPreUpdate="false"                                          # set this to true if you want to perform a backup before updating

# Update warning messages
# Modify as desired, putting the %d replacement operator where the number belongs
msgWarnUpdateMinutes="This ARK server will shutdown for an update in %d minutes"
msgWarnUpdateSeconds="This ARK server will shutdown for an update in %d seconds"

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort="32330"                                                # RCON Port
ark_SessionName="WBT Servers / PVE / Mods"                                  # if your session name needs special characters please use the .ini instead
ark_ServerPVE=true
ark_Port="7778"                                                     # ARK server port (default 7778)
ark_QueryPort="27016"                                               # ARK query port (default 27016)
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="PASSWORD"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="70"
ark_GameModIds="479295136,496483916,502341381,503911420,506506101,507648142,510590313,51168000,520879363"                     # Uncomment to specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures

# config Service
servicename="arkserv"                                               # Name of the service (don't change if you don't know what are you doing)
logdir="/var/log/arktools"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID
mod_appid=346110                                                    # App ID for mods

# Mod OS Selection
mod_branch=Windows
# Add mod-specific OS selection below:
#mod_branch_496735411=Windows

# alternate configs
# example for config name "ark1":
#configfile_ark1="/path/to/config/file"`

**Comment by FiberSprite** [comment]
http://pastebin.com/7qDBA1QB

**Comment by klightspeed** [comment]
> My server wont start apparently. it says its on but its not in my favorites list. when i start it using a start.sh file it works just fine though..

By "it says it's on", do you mean that it says that it is online and gives you an arkservers.net link?

Does `start.sh` use Port=7777 and QueryPort=27016?

**Comment by FiberSprite** [comment]
It says its online and gives me a arkservers.net link. i tried it on many different ports nothing seems to work besides 27014. i tried 7778 and then it gave me a ark servers link.

**Comment by verticalavenue** [comment]
In your start.sh file do you have the port and query port specified? Like this?

http://pastebin.com/UApg9JGq

arkservers.net link will show a value as long as a server instance is alive. It really has nothing to do with Ark-server-tools

**Comment by FiberSprite** [comment]
#! /bin/bash
./ShooterGameServer TheIsland?listen?ServerAdminPassword=PASSWORD?Port=27014?ServerPVE=1?AllowThirdPersonPlayer=True?GameModIds=479295136,496483916,502341381,503911420,506506101,507648142,510590313,51168000,520879363  -server -log

is my exact startup file. i tried switching ports in ark server tools to 27014 and it still wouldnt work.

**Comment by verticalavenue** [comment]
I had a problem with the listening just hanging and eventually crashing. I compressed my saved folder and moved it to a temp place then deleted the entire ark folder and ran arkmanager install (took me about  12 mins to download but I am on a 150M connection. not sure of your connection). I then let the server fire up until listening , checked all the configs with arkmanager , then uncompressed the saved folder in its original location. I found some of the core files and addons no matter what would not let the server fire up. a fresh install let me know it was not my sever nore the core game nor the ark server tools. I then proceeded to eliminate the core issue then started looking in the addons. Just a thought to get to a root cause.

**Comment by verticalavenue** [comment]
I looked at your mods too. Possibly 2 or 3 could be causing you issue as feedback from the community goes. Doubt they really disable your startup but not 100% sure.
Firstly 51168000 I have no clue what this is in your mod list.

Aku shima
WickWillow Island map
Total Conversions: Ordens Overhaul
Cooking Extras
Better Beacons
Baby dinos Enhanced --Has not updated since 11/7
Metal with glass
stairs mod - This mod has a few bugs but don't know how well they are being handled.

**Comment by FiberSprite** [comment]
It gives me a arkservers.net link here. http://arkservers.net/server/76.101.200.47:27016

but it isnt up. i dont get it?

**Comment by klightspeed** [comment]
So this is the command-line in start.sh:
```
#! /bin/bash
./ShooterGameServer TheIsland?listen?ServerAdminPassword=PASSWORD?Port=27014? ServerPVE=1?AllowThirdPersonPlayer=True?GameModIds=479295136,496483916,502341381,503911420,506506101,507648142,510590313,51168000,520879363 -server -log
```

And this is the command-line used by ark-server-tools:
```
/home/steam/ark_dedi/ShooterGame/Binaries/Linux/ShooterGameServer "TheIsland?RCONEnabled=True?RCONPort=32330?SessionName=WBT Servers / PVE / Mods?ServerPVE=true?Port=7777?QueryPort=27016?ServerPassword?ServerAdminPassword=PASSWORD?MaxPlayers=70?GameModIds=479295136,496483916,502341381,503911420,506506101,507648142,510590313,51168000,520879363"
```

So your start.sh is using port 27015 as the game port and port 27016 as the query port.
Meanwhile, you've set arkmanager to use port 7778 as the game port and port 27016 as the query port.

It's probably not showing up in your favourites because it's on a different port.

Try setting `ark_Port=27015` in your arkmanager.cfg

**Comment by FiberSprite** [comment]
Because im testing out different ports. they are all added to my favorites.

**Comment by klightspeed** [comment]
@FiberSprite is this working?

**Comment by FezVrasta** [comment]
closing for lack of feedback, feel free to reply for any follow up.
