### ISSUE TITLE
server wont start with workshop map

### ISSUE THREAD

**Issue by C0kkie** [FezVrasta/ark-server-tools#288]
how can i install a map on linux (Debian 8)? I installed the manager and then 

arkmanager installmod 504122600

then i editied the config

http://pastebin.com/9YqkZ6YD

but i get the error

```
23:00:26: start
23:00:26: Running /home/arkserver/ARK/ShooterGame/Binaries/Linux/ShooterGameServer -MapModID=504122600\?MaxPlayers=70\?Port=7777\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=keyboardcat\?ServerPassword\?SessionName=ARK\ Server\ Tools\?listen
23:00:26: Server PID: 7353
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
/usr/local/bin/arkmanager: line 516: 7353 Segmentation fault "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
23:00:42: Bad PID ''; expected '7353'
23:00:42: exited with status 0
```

map is saved in `/home/arkserver/ARK/ShooterGame/Content/Mods`
but there is just the folder and no .mod file in /mods

**Comment by klightspeed** [comment]
What was the output of `arkmanager installmod 504122600`?

What are the contents of `/home/arkserver/steamcmd/steamapps/workshop/content/346110/504122600`?

Does `/home/arkserver/steamcmd/steamapps/workshop/downloads/346110/504122600` exist?

**Comment by C0kkie** [comment]
![c0kkie_15_11_15-11_47_50](https://cloud.githubusercontent.com/assets/1337858/11168462/7fdcc24c-8b90-11e5-9410-3145d77af077.png)

![c0kkie_15_11_15-12_00_59](https://cloud.githubusercontent.com/assets/1337858/11168465/8fe5b11c-8b90-11e5-9792-63a956f1b0e1.png)

Does /home/arkserver/steamcmd/steamapps/workshop/downloads/346110/504122600 exist?

nop

**Comment by klightspeed** [comment]
Had you previously started the server before installing the mod?  You will probably need to either remove the /home/arkserver/ARK/ShooterGame/Saved directory, or move it somewhere else if you want to keep it.

**Comment by C0kkie** [comment]
when i start with the normal map, it works. ok.
And what i have to add in the config?

**Comment by C0kkie** [comment]
btw how do i edit the ark settings? when i change something in the 

/home/arkserver/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

it do not work

**Comment by Lihis** [comment]
Server must be restarted before changes GameUserSettings.ini take effect, same goes for Game.ini.

**Comment by C0kkie** [comment]
i restarted the server after i changed something

**Comment by Lihis** [comment]
Can you give example which values you're trying to change?

**Comment by C0kkie** [comment]
HarvestAmountMultiplier=2
TamingSpeedMultiplier=5
DayTimeSpeedScale=1
NightTimeSpeedScale=1.67
DayCycleSpeedScale=0.42857148
NoTributeDownloads=False
ServerCrosshair=False
ServerForceNoHUD=False
ServerHardcore=False
AutoSavePeriodMinutes=5.000000
ListenServerTetherDistanceMultiplier=1.000000
MaxTamedDinos=5000.000000
AllowThirdPersonPlayer=True
ServerPVE=False
ShowMapPlayerLocation=True

**Comment by klightspeed** [comment]
Is that the entire contents of the `GameUserSettings.ini` file, or just the `[ServerSettings]` section of that file?

As for the crontab entry, the following cron job should have it checking for both app and mod updates every half-hour:
```
*/30 * * * * /home/arkserver/bin/arkmanager update --warn --update-mods
```

**Comment by C0kkie** [comment]
its in the serversettings sections

**Comment by klightspeed** [comment]
Be sure to block out / remove passwords from your configs when you post them.

Any settings you want to set in `GameUserSettings.ini` need to be removed or commented-out in `arkmanager.cfg`.

**Comment by C0kkie** [comment]
there is nothing set in the arkmanager cfg which is set in the gameusersettings

**Comment by morggin** [comment]
@C0kkie i would seriously reconsider doing autosave every 5 minutes.  causes a LOT of lag.  I have mine set to 90 minutes.

**Comment by BlackLampone** [comment]
@C0kkie do you still know what you changed to get it working? Facing the same problem and also trying to install Valhalla. Getting the same error as well.

**Comment by FezVrasta** [comment]
**guys** this is the issue section of the ARK Server Tools, not a Q&A of ARK server.

If your questions are not related to problems with this tool, post them somewhere else.
This will help to keep clean this repository and focus on the real problems.
