### ISSUE TITLE
Can i run more than one server with the arkmanager?

### ISSUE THREAD

**Issue by axi92** [FezVrasta/ark-server-tools#289]
Hi is there a way to run more than one server?
I read about an issue at v1.3 with 2 different users, is this now easier?

**Comment by klightspeed** [comment]
* Make a copy of `arkmanager.cfg` to e.g. `/etc/arkmanager/arkmanager-server2.cfg`
* Modify the new config, making sure that `arkserverroot`, `ark_Port`, `ark_QueryPort`, and `ark_RCONPort` are different to those in the main config
* Add a `configfile_server2=/etc/arkmanager/arkmanager-server2.cfg` line to the main `arkmanager.cfg`, where `server2` is the name you want for the instance, and `/etc/arkmanager/arkmanager-server2.cfg` is the path to the new config file for the instance.
* If you already have a copy of the ARK server, then you can copy it to the new location, and remove any mods (from `ShooterGame/Content/Mods`) or saved files (from `ShooterGame/Saved`) you don't want in the new instance.

When you want to execute a command for that instance, use `arkmanager useconfig server2 <commands>` - e.g. `arkmanager useconfig server2 install`

Idea: perhaps we could create a `createinstance` command that does all of the above?

**Comment by FezVrasta** [comment]
@klightspeed yes I think it would be awesome, maybe even make the `status` command list the status of every running server and things like that.

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/ark-server-tools/issues/290
