### ISSUE TITLE
Package script to DEB and RPM packages

### ISSUE THREAD

**Issue by Sispheor** [FezVrasta/ark-server-tools#29]
Create a deb and RPM package instead of the current install script.

For RPM it's really easy with maven RPM plugin.

**Comment by FezVrasta** [comment]
I never packaged in RPM/DEB, surely it would be really neat. But maybe we should first get a stable and complete version of the script before we package it?

**Comment by Sispheor** [comment]
Yep

**Comment by FezVrasta** [comment]
I have prepared a net installer, I think it's really the easier way to install our package.

When we'll reach a stable phase we can consider packaging to RPM and DEB

**Comment by pandabear41** [comment]
Please don't package in a DEB or RPM, they are horrible to maintain and only work for certain linux builds. I would recommend just creating one shell script that you download and execute with one paste into the console.
For example have a single shell script that will do everything for you.
wget http://someurl/bootstrap.sh && chmod +x bootstrap.sh && ./bootstrap.sh
Inside the shell bootstrap.sh you would download a tar and run through some prompts to install the management script.

**Comment by FezVrasta** [comment]
@pandabear41 yes I have already did it!

    curl -s https://raw.githubusercontent.com/FezVrasta/ark-server-tools/master/netinstall.sh | sudo bash -s steam

**Comment by pandabear41** [comment]
@FezVrasta You read my mind as I was writing my message. I have managed DEB and RPM packages in the past and they are time consuming to maintain and not all users will be able to install a package correctly.

**Comment by FezVrasta** [comment]
yes this is what I had in mind as well. by the way we could consider them in the future if really needed
