### ISSUE TITLE
multi instances commands

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#290]
Here a list of commands which could be adapted to work with multiple ARK instances:

- [x] `start <server1> <server2> <serverN>`
- [x] `stop <server1> <server2> <serverN>`
- [x] `restart <server1> <server2> <serverN>`
- [x] `stop <server1> <server2> <serverN>`
- [x] `update <server1> <server2> <serverN>`
- [x] `status <server1> <server2> <serverN>`
- [x] `backup <server1> <server2> <serverN>`
- [x] `broadcast <server1> <server2> <serverN>`
- [x] `saveworld <server1> <server2> <serverN>`
- [x] `rconcmd <server1> <server2> <serverN>`

If no server is specified, the command will be executed on all the server after having warned the user, eg:

```
this command will be executed on all the available ARK instances managed by ARK Server Tools, do you want to proceed? [y/N]
```

if some of them already support it, just check them as completed.

**Comment by klightspeed** [comment]
As specified, this would conflict with multi-command support, and for the `broadcast` and `rconcmd` commands the server names would need to come after the argument.

An alternative might be to have a `--instances` option, followed by one or more instance names, then a `--command` or `--commands` option followed by the command(s).

e.g.:
```
arkmanager --instances server1 server2 serverN --command update --warn
arkmanager --instances server1 server2 serverN --commands saveworld backup
arkmanager broadcast --instance server1 "Hello" broadcast --instance server2 "Hola" broadcast --instance serverN "Bonjour"
arkmanager stop --all
arkmanager start --instances server1,server2,serverN
arkmanager backup --instances main,server1,server2
```

Another alternative might be to require each of the server names be preceded by e.g. `@` or `+`

e.g.
```
arkmanager update --warn @server1 @server2 @serverN
arkmanager broadcast @server1 "Hello" broadcast @server2 "Hola" broadcast @serverN "Bonjour"
```

Would we want to continue to have a `main` instance?

**Comment by FezVrasta** [comment]
I don't think we should have a main instance, it's okay to have global configuration overridable by instance-specific configurations tho.

I prefer the `@server1` format. Having an `--instances` and `--command` seems hacky to me.

**Comment by axi92** [comment]
you guys are awesome

**Comment by FezVrasta** [comment]
@axi I'm just the one that press the "merge" button :(

@klightspeed and @Atriusftw are the awesome guys :)

**Comment by klightspeed** [comment]
For the instance configs, shall we have e.g. a `/etc/arkmanager/instances` and/or `~/.config/arkmanager/instances` directory with named instance configs, which would supplement the `configfile_*` options currently in the core config?

In the install script, during upgrade, should we also pull the instance-specific settings (e.g. `arkserverroot`, `ark_RCONPort`, `ark_Port`, `ark_QueryPort`) to a separate `main.cfg` file?

Shall we also create e.g. a `instance.cfg.example` file in that `instances` directory?

**Comment by FezVrasta** [comment]
1. I think it's a good idea, lets try to make the multi-instance support easier as possible, but don't force people to think in a "multi instance way" if they don't need it.
2. this to make the automatic config update?
3. I think so

**Comment by klightspeed** [comment]
>> In the install script, during upgrade, should we also pull the instance-specific settings (e.g. `arkserverroot`, `ark_RCONPort`, `ark_Port`, `ark_QueryPort`) to a separate `main.cfg` file?

> this to make the automatic config update?

Since we want to retire the `main` instance support, and only have common settings in the core config file, once the instance-specific settings are moved out of the `arkmanager.cfg` template and into a separate `instance.cfg.example` file, my idea would be to have the configuration update part of the install script would check if `arkserverroot` exists in the core config, and if it does it would ask the installer if they want to move the instance-specific settings into `instances/main.cfg`.  If so, it would move the instance-specific settings (`arkserverroot`, `ark_RCONPort`, `ark_Port`, `ark_QueryPort`) and copy the common ARK settings (`serverMap`, `serverMapModId`, `ark_*`, `arkopt_*`, `arkflag_*`) into `instances/main.cfg`.

**Comment by FezVrasta** [comment]
@klightspeed yes I think it's good, try to don't mix that part with the rest of the install script so we can get rid of it in future versions if needed.

**Comment by klightspeed** [comment]
I have split the config file migration to a separate script (`migrate-config.sh`), and have created a new script (`migrate-main-instance.sh`) to migrate the main instance options to `main.cfg`.

The `main` instance is now treated the same as any other instance.
