### ISSUE TITLE
Choose update channel main/sub

### ISSUE THREAD

**Issue by axi92** [FezVrasta/ark-server-tools#292]
Is there a way to choose between the update channels?
http://ark.gamepedia.com/Web_API#version

main: 223
sub: 223.3

something like this
Often the sub updates break the game^^ so I would only like to update to the main version automatically at the cronjob.

**Comment by klightspeed** [comment]
Unfortunately it isn't possible to update to anything other than the latest version using Steam.

In fact, the return from http://arkdedicated.com/version is out of date, as it shows the latest version being `223.2`, yet https://steamcommunity.com/app/346110/discussions/0/594820656447032287/ says the latest version is `223.3`

**Comment by Lihis** [comment]
@axi92 @klightspeed The ``http://arkdedicated.com/version`` is very often out of date and it can take long time before it is "up to date" again.  That's why I think it should not be used to determine the latest version.

**Comment by axi92** [comment]
Ok i understand
