### ISSUE TITLE
New log option

### ISSUE THREAD

**Issue by tenten36** [FezVrasta/ark-server-tools#293]
From steam:

How can i add this `-servergamelog` via the arkmanager.cfg ?

`ark_servergamelog=""` makes it as `?servergamelog `not `-servergamelog` and not logs in "Logs" and i think it has to work also without rcon but the server dosen't write any logs

**Comment by klightspeed** [comment]
Use `arkflag_servergamelog=""` to add the `-servergamelog` option.

**Comment by tenten36** [comment]
Thanks, the server starts now with - servergamelog, but I still get "Server received, But no response!!" with arkmanager rconcmd "getgamelog".

**Comment by Atriusftw** [comment]
@tenten36 Doublecheck that a file starting with 'ServerGame' have been created in '~/ARK/ShooterGame/Saved/Logs'

Also make sure do define RCON buffer with ark_RCONServerGameLogBuffer=600 in 'arkmanager.cfg'
You can swap out the number with your desired amount of lines to print.

**Comment by tenten36** [comment]
Yup, works now. The GameLogBuffer did the trick. Thanks!

**Comment by klightspeed** [comment]
The `Server received, But no response!!` response by the ARK server appears to mean that there are no log entries to return.
