### ISSUE TITLE
Config override problem

### ISSUE THREAD

**Issue by axi92** [FezVrasta/ark-server-tools#294]
Normaly on linux the configs are taken in 
ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
ShooterGame/Saved/Config/LinuxServer/Game.ini

But if i put my config lines there every start it overrides it -.-
So I can't modify anything
Whats wrong?

**Comment by FezVrasta** [comment]
If you define some configurations in the arkmanager.cfg they will override the values in GameUserSettings.ini, this is by default on ARK.
