### ISSUE TITLE
Crontab Auto Backup world and Auto reboot

### ISSUE THREAD

**Issue by ryan1161** [FezVrasta/ark-server-tools#295]
I was hopping you could tell me how to do this right so it works because Iv'e been searching the issues on here to see if you have these but I couldn't find any but I did manage to get the saving in crontab and check for updates. This is what my crontab looks like so far.

#Ark Checks for Updates
*/10 * * * * /usr/local/bin/arkmanager update --warn

#Ark Save the World every 10 mins
*/10 * * * * arkmanager broadcast "Saving World" saveworld

#Ark Backsup World every 30 mins
?

#Ark autorestart
?

**Comment by klightspeed** [comment]
As `/usr/local/bin` often isn't in `cron`'s `PATH`, you need to specify the full path to arkmanager.

For a backup:
```
*/30 * * * * /usr/local/bin/arkmanager backup
```

For a restart at 3:15AM:

```
15 3 * * * /usr/local/bin/arkmanager restart
```

**Comment by ryan1161** [comment]
Opps I meant like if the server lost power and booted back up how would I add something to the crontab to tell it to start the ark server back up. Plus right now I'm trying to get it to run and getting "server running: no" but every thing else is green that is red. Plus where do I edit the config for the server cause I cant seem to find my saved folder for the ark server. Now when I try to save the game with "arkmanager savewold" it gives me an output of  "Negative length at -e line 13"

**Comment by klightspeed** [comment]
> Opps I meant like if the server lost power and booted back up how would I add something to the crontab to tell it to start the ark server back up.

It should be possible to use the init script to do that.

> Plus right now I'm trying to get it to run and getting "server running: no" but every thing else is green that is red.

Are you attempting to run multiple servers?  Each server must run from a different directory and use different ports.

> Plus where do I edit the config for the server cause I cant seem to find my saved folder for the ark server.

The `GameUserSettings.ini` file etc should be in `$arkserverroot/ShooterGame/Saved/Config/Linux`.

> Now when I try to save the game with "arkmanager savewold" it gives me an output of "Negative length at -e line 13"

Is the `ServerAdminPassword` set in the `GameUserSettings.ini`, or is `ark_ServerAdminPassword` set in `arkmanager.cfg`?

**Comment by ryan1161** [comment]
Init script ? Iv'e usually just used the crontab command @reboot and the the exicutiable file. If you could give an example of the init script that would be great.

I'm only running one server but I have a minecraft server running on this linux machine. But I can connetect to my server ingame and from the Rcon so It's running just thought that was weird.

Well I don't have a "/ShooterGame/Saved/Config/Linux" I only find "/home/steam/ARK/ShooterGame"

 Plus when I was downloading the Ark through steamcmd it came up with a  Error! App '376030' state isa 0x502 after update job.

I setup the ServerAdminPassword in the arkmanager.cfg

**Comment by klightspeed** [comment]
> I'm only running one server but I have a minecraft server running on this linux machine. But I can connetect to my server ingame and from the Rcon so It's running just thought that was weird.

You need to make sure the ARK server is on different ports to the Minecraft server.

> Well I don't have a "/ShooterGame/Saved/Config/Linux" I only find "/home/steam/ARK/ShooterGame"

So there's nothing under `/home/steam/ARK/ShooterGame`?

> Plus when I was downloading the Ark through steamcmd it came up with a Error! App '376030' state isa 0x502 after update job.

Was this during an update or during an install?  Try using `arkmanager update --validate`.

**Comment by ryan1161** [comment]
The Minecraft ports are 2015 and 25565 so there no where close to the Ark ports.

In the "/home/steam/ARK/ShooterGame" there is ContentStreamers, Content, Config, Binaries folders and  one file named AssetRegistry.bin

This happened during the install. I got the same error with arkmanager update --validate. I have even tried deleting it and still happens.

**Comment by ryan1161** [comment]
arktools logfile

/usr/local/bin/arkmanager: line 516:  1655 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
19:14:18: Bad PID ''; expected '1655'
19:14:18: exited with status 0
19:53:50: start
19:53:50: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=25\?Port=7776\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=Ilovejake2\!\?ServerPassword\?SessionName=TafariCraft\?listen
19:53:50: Server PID: 2020
Using binned.
4.5.1-0+UE4 7038 3077 402 5
/usr/local/bin/arkmanager: line 516:  2020 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
19:53:56: Bad PID ''; expected '2020'
19:53:56: exited with status 0

**Comment by klightspeed** [comment]
Be sure to blank out passwords in config files or logs that you post.

Do you have enough memory to run both the Minecraft server and the ARK server?  The ARK server needs at least 3.5GB of RAM.

Do you also have enough disk space?

**Comment by ryan1161** [comment]
Okay will do

I have 64GB it's my game server so I know it can run both. its only using 18GB out of my 64GB

Yes it has a 5tb drive

**Comment by ryan1161** [comment]
I got it to upadate valilidate worked this time since I kill all steamcmd and arkmanagers running and the server says running now but listening on the wrong port though so its in red as no. I changed it to 7777 but its still 7776 Idk where it's getting that from.

**Comment by ryan1161** [comment]
23:20:52: start
23:20:52: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=25\?Port=7776\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=*******\?ServerPassword\?SessionName=TafariCraft\?listen
23:20:52: Server PID: 1092
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
23:22:45: server is up
Using binned.

**Comment by klightspeed** [comment]
The `ark_Port=7777` is what port the server actually listens on.  Since the server adds 1 to the `Port` that it's given (i.e. if you give it `Port=7777`, it'll actually listen on port 7778), arkmanager subtracts 1 from the `ark_Port` to get the `Port` that it passes to the server.

If you want to give it `Port=7777`, you need to set `ark_Port=7778`.

> 23:20:52: start
> 23:22:45: server is up

That's a pretty quick startup.

>  I'm just afraid it's still broke because of the pids that start up all at once on but I have 3 arksmanagers and 3 steamscmds

Do you have multiple instances of `arkmanager update` in your crontab?

**Comment by ryan1161** [comment]
Okay so I got the port but the server listening is sill a red No and found out what I was doing to arkmanager was starting it three times manually now on reboot it starts up perfectly fine now.

**Comment by klightspeed** [comment]
Are you waiting a few minutes after starting the server before deciding it's not working?  On my computer (which uses SATA drives), it usually takes about 7 minutes to start up.  

The fact that it logged `server is up` before the server printed `Using binned` suggests that you have something else listening on that port.

**Comment by ryan1161** [comment]
Okay its now open on all ports and game version is 224.2 everything works now so you can close this. Iv'e got it running and it's loads supper fast than it did on windows lol;)

**Comment by ryan1161** [comment]
Well it's just really annoying all this work to get it running and now it's timing me out every couple of minutes I can't even create a character. I'm going to bed been working all day on this let me know if you have anymore suggestions I will look at them tomorrow.

**Comment by klightspeed** [comment]
> Is my Server version supposed to be 0?

Is that the `Server version: ` number?  This is the `buildid` of the app, and a `buildid` of 0 means that it hasn't finished installing.

What is the output of `du -i /home/steam/ARK`, and the output of `du /home/steam/ARK`?

Are there any recent errors in `dmesg`?

> I port-forward on my router ports 7778 for Ark and port 27015 for query. or am I supposed to port-forward 7777 since that what it actually listening on?

When `Port=7777` (`ark_Port=7778`) is specified, the server listens on TCP and UDP ports 7778.

> Is this a common error? [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.

That just means that the devs haven't disabled that check.  It's harmless, and yes, everybody gets it.

**Comment by ryan1161** [comment]
Well I got the server version at 868725 after the validate last night.

steam@ryandward:~$ df -i /home/steam/ARK
Filesystem      Inodes  IUsed   IFree IUse% Mounted on
/dev/sda1      6725632 298363 6427269    5% /

steam@ryandward:~$ df  /home/steam/ARK
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda1      105749624 48334656  52020128  49% /

**Comment by ryan1161** [comment]
Okay so I just tested the connection on the lan and I get connection time-out still so this has to be a problem with the server it's self not my actual network. The server network has 100M up and 3M down so it can't be a network issues from getting out it's a internal problem with this server on my Ubuntu the problem is I'm at a stuck point on what to do cause Iv'e just about tried everything I could think of.

**Comment by ryan1161** [comment]
Figured it out it's a glitch with the actual game update "Ark v224.2" If you spend to much time creating a chater you will get timed out so I just clicked create default one and Iv'e been in my server for 20 mins with a ping of 20:) I'm now closing this.

**Comment by Atriusftw** [comment]
That is not a bug. It's been in the game for a while.
It's actually autokick. If you stay at the spawn selection screen for too long, the server will drop your connection.
