### ISSUE TITLE
Port offset by 1

### ISSUE THREAD

**Issue by mohlerm** [FezVrasta/ark-server-tools#298]
I specified the game port in `.arkmanager.cfg` as 7777
``ark_Port="7777"`` 
When examining the logs or arkservers.net I realize the server is running on 7776.
``?Port=7776\``

Netstat shows the server actually listens on 7777:
```
$ netstat --listen
udp        0      0 *:7777  
```

Found this comment in the code.
```    
# Port is actually one higher than specified
# i.e. specifying port 7777 will have the server
# use port 7778
if [ "$name" == "Port" ]; then
  (( val = val - 1 ))
fi
```
https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager

What is the reason for this, is this actually an ARK issue? Nevertheless, the comment suggests specifying 7777 results in 7778 but it's actually the other way around (we decrease the defined port).

**Comment by Atriusftw** [comment]
This is due to Unreal Engine. They for some reason add one to the specified port number.

**Comment by mohlerm** [comment]
Okay, I suggest to add this in the README somewhere as it's confusing.

Otherwise, this can be closed since it's an ARK issue.

**Comment by SirWilli** [comment]
I have the same issue. It first started on the correct port but after I changed few things it did the offset
