### ISSUE TITLE
arkmanager crashes

### ISSUE THREAD

**Issue by axi92** [FezVrasta/ark-server-tools#299]
If i start my server with arkmanager it crashes
```
./arkdedicated/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?listen -server -log
```

If i start normaly it wont...

```
ark@ns215329:~$ arkmanager run
19:56:57: start
/usr/local/bin/arkmanager: line 510: ulimit: open files: cannot modify limit: Operation not permitted
19:56:57: Running /home/ark/arkdedicated/ShooterGame/Binaries/Linux/ShooterGameServer \?listen -servergamelog
19:56:57: Server PID: 23885
Using binned.
4.5.1-0+UE4 7038 3077 402 5
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
lsof: unacceptable port specification in: -i :
lsof 4.86
 latest revision: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/
 latest FAQ: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/FAQ
 latest man page: ftp://lsof.itap.purdue.edu/pub/tools/unix/lsof/lsof_man
 usage: [-?abhKlnNoOPRtUvVX] [+|-c c] [+|-d s] [+D D] [+|-f[gG]] [+|-e s]
 [-F [f]] [-g [s]] [-i [i]] [+|-L [l]] [+m [m]] [+|-M] [-o [o]] [-p s]
[+|-r [t]] [-s [p:s]] [-S [t]] [-T [t]] [-u s] [+|-w] [-x [fl]] [--] [names]
Use the ``-h'' option to get more help information.
Signal 11 caught.
EngineCrashHandler: Signal=11
/usr/local/bin/arkmanager: line 516: 23885 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
19:57:07: Bad PID ''; expected '23885'
19:57:07: exited with status 0
```
Is it normal that it has at this line
19:56:57: Running /home/ark/arkdedicated/ShooterGame/Binaries/Linux/ShooterGameServer \?listen -servergamelog

A backslash infront of "?" ?

**Comment by klightspeed** [comment]
It looks like you have removed **all** of the ARK options from the `arkmanager.cfg`, including `serverMap`.

The following settings must be present in `arkmanager.cfg`:
* `serverMap` or `serverMapModId`
* `ark_RCONPort`
* `ark_Port`
* `ark_QueryPort`

**Comment by axi92** [comment]
Oh ok I thought i can remove it anyways becaus its the default value so if it is not set it takes it anyways, ooops xD

Because I comment out all except serverMap and it worked.
On the weekend I dont know why but I commented serverMap out too but restarted yesterday and dont thought it was that^^

I try it again whenn less players are on and post feedback =)
ty for now

**Comment by klightspeed** [comment]
Be aware that at the moment, without the `ark_RCONPort` setting, the `arkmanager rconcmd` command won't work, and without `ark_Port` and `ark_QueryPort`, the `arkmanager status` command and server auto-restart won't work.

**Comment by axi92** [comment]
Oh ok good to know really important information maybe should be included in the # coment lines in the file?
But its also logical, where else should the arkmanager get the information^^
