### ISSUE TITLE
Create a sysinit and systemd startup script

### ISSUE THREAD

**Issue by Sispheor** [FezVrasta/ark-server-tools#30]
Both have to call the start function of arkmanager on the server statup

**Comment by Sispheor** [comment]
Sysinit script done. Tested on Ubuntu 14.04.

Todo: systemd unit script

**Comment by FezVrasta** [comment]
I think we have everything now with #43 right?

**Comment by Sispheor** [comment]
Systemd unit script is missing

**Comment by FezVrasta** [comment]
which distros use it? We can keep it for 1.2 I guess? We are already supporting the major systems.

**Comment by Sispheor** [comment]
Debian 8 / CentOS 7 and all other distro on Systemd

2015-06-24 18:19 GMT+02:00 Fez Vrasta <notifications@github.com>:

> which distros use it? We can keep it for 1.2 I guess? We are already
> supporting the major systems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/30#issuecomment-114930163>
> .
>



-- 
*Nicolas MARCQ*

**Comment by FezVrasta** [comment]
ah ok something new, I'm still on centos 7 and ubuntu 14.04 :p 
waiting for it to release the 1.1 so

**Comment by FezVrasta** [comment]
If I'm not wrong, now we have systemd support (even if bugged #47).
