### ISSUE TITLE
Crontab Auto Update error

### ISSUE THREAD

**Issue by ryan1161** [FezVrasta/ark-server-tools#300]
Nov 25 16:45:01 ryandward CRON[2009]: (steam) CMD (arkmanager update --safe --wa                                                  rn)
Nov 25 16:45:01 ryandward CRON[2008]: (CRON) info (No MTA installed, discarding 

It's not updating my server what does this mean?   

Crontab file for my steam user:

#Ark Checks for Updates
*/1 * * * * arkmanager update --safe --warn
#
#Ark Save the World every 10 mins
*/10 * * * * arkmanager broadcast "Saving World" saveworld
#
#Ark Backsup World every 24 hours
0 9 * * * /usr/local/bin/arkmanager backup
#
#Ark removes backups older than 30 days
If you could give me an example of this for my crontab

**Comment by klightspeed** [comment]
You need to specify the full path to arkmanager - e.g. `/usr/local/bin/arkmanager`.

The `No MTA installed` simply means that the command exited with output (probably `sh: arkmanager: command not found`), and as there was no Mail Transport Agent with which cron could send the message, the message was discarded.

**Comment by ryan1161** [comment]
Well I just found it by making a output in my crontab for that line so I add that /usr/local/bin/arkmanager and it's updating now. I just hope it broadcast it to tell my players it will update apply the update in 1 hour.

**Comment by ryan1161** [comment]
Is there anyway to do this:

Ark remove backups older than 30 days so that way you can only have 30 and not fill up hdd fast with backups.

Would be awesome if this was a feature you could add to the Ark-Server-Tools.

**Comment by ajostergaard** [comment]
You could try adding something like `find /home/steam/<PATHTOBACKUPS>/ -name '<FILENAMEPREFIX>*' -type f -mtime +30 -exec rm '{}' \;` to your crontab.

This will delete all files in, and under, `/home/steam/<PATHTOBACKUPS>/` which start with `<FILENAMEPREFIX>` modified more than than 30 days ago.

I'm no arkmanager or ark or steam expert so have no clue what the path or filename should be - sorry.

**Comment by verticalavenue** [comment]
I use this method to clean out old security videos on my Linux DVr and it works great. I think I'll apply it to the ark saved arks folder to see if I can get it working

**Comment by ryan1161** [comment]
Well the crontab tells me somthing is wrong and tells me to edit the crontab cause the command is causing a error so it doesn't work for me plus its not files it's folder really wish they would make the backup tar files. My folder location is this: /home/steam/ARK-Backups

The crontab command I typed in was: find /home/steam/ARK-Backups/ -name '<09.00.01>*' -type f -mtime +30 -exec rm '$

Also tried removing the <> around my folder name and it still gave me the error.

Also the folder are named 2015-11-28_09.00.01 so its kinda hard to have it delete them unless I use the time it was backup cause the date changes.

**Comment by ryan1161** [comment]
Okay so another thing I hate is that every time there is a arkmanager tools hot fix update I always have  a file named arkmanager.cfg.NEW and another one arkmanager.cfg - which this has my configurations already setup.

**Comment by klightspeed** [comment]
> The crontab command I typed in was: find /home/steam/ARK-Backups/ -name '<09.00.01>*' -type f -mtime +30 -exec rm '$

It looks like you grabbed that from an editor that wraps using the `$` character.  The fact that the `$` was at the 80th character suggests that you did not fill in the minute, hour, day, month or weekday fields of the cron job.

Since you're probably on v1.4, you'll have to remove the dated backup directory.

Try:
```
45 8 * * * find /home/steam/ARK-Backups/ -type d -name '*_09.0?.??' -mtime +30 -exec rm -rf '{}' \;
```

>  Okay so another thing I hate is that every time there is a arkmanager tools hot fix update I always have a file named arkmanager.cfg.NEW and another one arkmanager.cfg - which this has my configurations already setup.

The `.NEW` file can be thought of as an example file, which may have new settings that can be used.

**Comment by ryan1161** [comment]
Well that worked in the crontab.
