### ISSUE TITLE
STEAMPS3 - AsncTCPSocket destroyed

### ISSUE THREAD

**Issue by ryan1161** [FezVrasta/ark-server-tools#304]
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed

I found a how to fix here: https://steamcommunity.com/app/346110/discussions/0/523890046884387404/

But I can't figurure out how to add the: "gdb --args" to the startup script for the server with your tools.

**Comment by klightspeed** [comment]
If the server doesn't crash when this happens, then the linked fix won't work.  All the lined fix does is ignores SIGPIPE; it does not stop the `AsyncTCPSocket created` and `AsncTCPSocket destroyed` lines from being logged, and does not prevent any associated lag spike.

I could create an enhancement that ignores SIGPIPE (e.g. `trap "" PIPE`).

**Comment by klightspeed** [comment]
I just checked the current version of the server using `strace`.

It already ignores `SIGPIPE`:
```
3079  21:39:41.089408 [00007f8e6931b34d] rt_sigaction(SIGPIPE, {SIG_IGN, [PIPE], SA_RESTORER|SA_RESTART, 0x7f8e6931b240}, {SIG_DFL, [], 0}, 8) = 0
```

`kill -PIPE $serverpid` does nothing.

Therefore, the "fix" will do nothing.

**Comment by ryan1161** [comment]
Well I keep getting timeout every now and then just wanted a fix.
