### ISSUE TITLE
Base protection help

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#305]
Hi guys, 

i'm asking there if anyone knows about a base protection for linux ?

this one is just fine but only for windows  : http://steamcommunity.com/app/346110/discussions/0/594821545177819162/

Thanks for your help :)

**Comment by Lihis** [comment]
No offense but does these type of questions belong here? As this is not related to arkmanager currently.

**Comment by arkfrancegaming** [comment]
You're right, just asking if someone who use arkmanager that I also use knows about it
