### ISSUE TITLE
24 Hour Day With Time Skewed

### ISSUE THREAD

**Issue by ryan1161** [FezVrasta/ark-server-tools#313]
We set the DayCycleSpeedScale=0.03571429 for a 24 hour day.  Since some of us work during the day, we skewed the actual time in the game to be 6 hours behind.  Is there already a way to set the time in the game with the the current time minus 6 hours?

**Comment by klightspeed** [comment]
`arkmanager rconcmd "SetTimeOfDay $(date +"%H:%M:%S" --date="now - 6 hours")"`

**Comment by ryan1161** [comment]
Well I'm trying to make a alias to run this so when I start the server it will set that time so I don't have to do it every time I stop the server or it stops to check for updates.

**Comment by ryan1161** [comment]
Well I I guess I could have a crontab job run this after the check for update runs at 9 a.m. I'm having trouble getting this to run in my crontab though. 

*/1 * * * * /usr/local/bin/arkmanager rconcmd "SetTimeOfDay $(date +"%H:%M:%S" --date="now - 6 hours")" >> /home/steam/crontab.log 2>&1

**Comment by klightspeed** [comment]
cron may have choked on the first cron job attempt as you were attempting to run it every minute.  Either that, or the default shell doesn't understand `$(command substitution)`, and you need to use backtick command substitution:

```
0 11 * * * /usr/local/bin/arkmanager rconcmd "SetTimeOfDay `date +"%H:%M:%S" --date="now - 6 hours"`"
```

The second attempt may not work without a shebang (the `#!/bin/bash`) on the first line.

```
#!/bin/bash

/usr/local/bin/arkmanager rconcmd "SetTimeOfDay $(date +"%H:%M:%S" --date="now - 6 hours")"
```

Is your second attempt working with correct spelling and capitalization?

```
0 11 * * * /home/steam/ArkSyncTime.sh
```

**Comment by ryan1161** [comment]
The second attempt is working like the way I want it too.
