### ISSUE TITLE
Negative length

### ISSUE THREAD

**Issue by BlueSelune** [FezVrasta/ark-server-tools#314]
Hi.
When I perform a rcon related command, I get an error : 

steam@cyrcee:~$ arkmanager broadcast "Maintenance prévue à 14h30."
Negative length at -e line 13.
steam@cyrcee:~$ arkmanager saveworld
Negative length at -e line 13.

What's wrong ?
Thanks for your help

**Comment by klightspeed** [comment]
Please note that ARK's RCON support does not permit non-ascii characters.  Therefore, passwords and commands with special characters are unsupported.  Your `Maintenance prévue à 14h30.` will become `Maintenance pr?vue ? 14h30.`

**Comment by BlueSelune** [comment]
Ok thank you but even with ASCII characters, the command fails with the "Negative length" error message. Does it mean the ARK server is not properly launched with the tool ?

**Comment by BlueSelune** [comment]
Thanks for the hotfix. Unfortunately it still doesn't work : 

steam@cyrcee:~$ arkmanager rconcmd "ListPlayers"
Negative length at -e line 13.
steam@cyrcee:~$ arkmanager saveworld
Negative length at -e line 13.
steam@cyrcee:~$

**Comment by klightspeed** [comment]
Do you have `ark_ServerAdminPassword` set in your arkmanager.cfg, or do you have `ServerAdminPassword` set under `ServerSettings` in your `GameUserSettings.ini`?

RCON support requires a server admin password be set.  The support for RCON in arkmanager attempts to retrieve the password from either the `ark_ServerAdminPassword` setting in `arkmanager.cfg` or the `ServerAdminPassword` setting under `ServerSettings` in `GameUserSettings.ini`.

**Comment by BlueSelune** [comment]
Hi

Indeed the ark_ServerAdminPassword is set both in arkmanager.cfg and in the GameUserSettings.ini

I tried some hours ago to reinstall everything (ie. arkmanager + ark server) with a clean config, the ARK server was unable to start properly (it seems arkmanager cannot access the GameUserSettings.ini for an unknown reason)
Some binary files had even been corrupted. Had to remove completely arkmanager and the ark server, reinstall the ARK server in manual mode, and start again with my old systemd script.
I'd really like make it work on our server, since this tools set would be very useful for us (we have 4 Mods installed and often updates)

Rgs
Selune
