### ISSUE TITLE
ARK Pirate world launch command line

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#317]
Hi, 

i wanted to add this launch command  : 

/Game/Mods/547377246/ShooterGame/Content/Mods/arkpirateworld/PirateWorld?

How can i add that to my cfg ?

Thanks

**Comment by klightspeed** [comment]
If that's the map for that map mod, you should be able to use the `serverMapModId=547377246` setting in `arkmanager.cfg`

**Comment by arkfrancegaming** [comment]
i've already try, check this 

http://steamcommunity.com/workshop/filedetails/discussion/547377246/490124466478664872/

**Comment by klightspeed** [comment]
SInce this is a total conversion mod, you'd use the following two settings in `arkmanager.cfg`:

```
serverMap=/Game/Mods/547377246/ShooterGame/Content/Mods/arkpirateworld/PirateWorld
ark_TotalConversionMod=547377246
```

You should also be able to use `arkmanager installmod 547377246` to install the latest version of the mod.

**Comment by arkfrancegaming** [comment]
Good thanks!
