### ISSUE TITLE
exclusivejoin

### ISSUE THREAD

**Issue by benzon** [FezVrasta/ark-server-tools#321]
Hi

We need integration of -exclusivejoin in arkmanager currently it's not there and for a community server it's a must have to be honest

This is from the steam forum, is there a way i can add the -exclusivejoin in current version of arkmanager?

-----------------------

Survivor, Spenz asks, “Can we have a whitelist, so only players on the list are able to join a server?”

Answer:

We’ve got this setup and you guys can now make use of it too!

Launch your server with this commandline option:

-exclusivejoin

and put the STEAM ID’s of the players who are on the exclusivity list in this file, with each SteamID on it’s own line:

PlayersExclusiveJoinList.txt

It’ll go in the same place as your whitelist file.

**Comment by Lihis** [comment]
I think the ``arkflag_exclusivejoin=""`` should do the job?

**Comment by benzon** [comment]
Not sure on that think that would ad = in the end of -exclusivejoin not sure that will work.

**Comment by FezVrasta** [comment]
If I remember it correctly, we use the `=""` convention to define parameters without a `=`, adding `=""` will just add the parameter

**Comment by Lihis** [comment]
Had to check on my server, ``arkflag_servergamelog=""`` adds just ``-servergamelog``. So the ``arkflag_exclusivejoin=""`` should work.

**Comment by FezVrasta** [comment]
I've noticed that we mention it even in our README:

https://github.com/FezVrasta/ark-server-tools#configuration

**Comment by benzon** [comment]
Hehe sometime shit is confusing :D Just a question why not add a arkmanager command for whitelist, etc?

Where you can do something like arkmanager whitelist=id or arkmanager exclusivejoin=id, and it adds it to the respective text files.

**Comment by FezVrasta** [comment]
We try to be as generic as possible to be able to support any new feature without have to write custom code, I think this is the reason.

**Comment by benzon** [comment]
The whitelists and exclusivejoins are quite generic looks like more and more uses that stuff but i understand why you try and keep it clean :)

**Comment by klightspeed** [comment]
> I'm not sure about the difference between arguments and flags tho :sweat_smile: 

An argument to an option (or option-argument) is the value of that option.  i.e. with `-a=b`, `-a` is the option, and `b` is the argument to that option.

A flag is an option that does not take an argument - its value is determined by its presence or absence, and is usually true if present and false if absent.

See http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html

**Comment by FezVrasta** [comment]
So what's the difference between a `dash-option` and an `option without an argument`?

**Comment by klightspeed** [comment]
The ARK server accepts two types of options - questionmark-delimited options (`map?opt1=arg?opt2`) and dash-options (those introduced with a dash - e.g. `-server`).

Each of those may or may not have an argument.

So you can have:

* question-mark options with an argument - `...?SessionName=My Awesome Server?...`
* question-mark options without an argument - `...?bRawSockets?...`
* dash-options with an argument - `-StructureDestructionTag=DestroySwampSnowStructures`
* dash-options without an argument - `-server`

**Comment by FezVrasta** [comment]
I see thanks
