### ISSUE TITLE
problem with other config since the last patch

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#332]
Hi,

since the last update (1.5) i can't use arkmanager useconfig pve

# alternate configs
# example for config name "ark1":
configfile_pve="/etc/arkmanager/arkmanager-pve.cfg"
configfile_pirate="/etc/arkmanager/arkmanager-pirate.cfg"

i tried arkmanager useconfig pve status but nothing 

/usr/local/bin/arkmanager: ligne 1481:  No such files or folders of this type

**Comment by klightspeed** [comment]
#329 should fix that.

**Comment by arkfrancegaming** [comment]
thanks
