### ISSUE TITLE
Player status

### ISSUE THREAD

**Issue by tenten36** [FezVrasta/ark-server-tools#334]
When I do the arkmanager status thing, I sometimes get a player +1 for my server. For example it shows 1/50 players, but there is noone connected. Not sure if this is a arkmanager or rcon problem?

**Comment by Lihis** [comment]
I have noticed same issue when getting players from query port (27015) while rcon shows the right amount of players. Must be problem on the ARK side I think.

**Comment by FezVrasta** [comment]
it's most probably an ark problem
