### ISSUE TITLE
ArkServer  Logs

### ISSUE THREAD

**Issue by BMDao** [FezVrasta/ark-server-tools#337]
Hi,

I have a little problem with the log savings, because the log data´s are saved without anything is in there... Here is the path of the logs im talking about :ARK/ShooterGame/Saved/Logs

Thanks for ur help buddy!

**Comment by klightspeed** [comment]
The server log being empty is probably an interaction between `-servergamelog` and `-log` - If I remember correctly, it looks like it writes it at the start, then moves the new file to a new name and creates the server log again.  If this is the case, then it is a bug in the game, not in the server tools.

The game log only contains chat and server messages.  It will be empty or non-existent if there have been no chat or server messages.

**Comment by BMDao** [comment]
on the server are always online between 5-20 players. among top I see no -servergamelog in start command. may it be because? how can I add it?

**Comment by Lihis** [comment]
Read the manual :) if I recall correctly it is ``arkflag_servergamelog=""``.

**Comment by BMDao** [comment]
I read it. but that I did not see .... thank you :)
