### ISSUE TITLE
arkmanager modifying inis?

### ISSUE THREAD

**Issue by axi92** [FezVrasta/ark-server-tools#338]
Is the tool modifying any Game.ini or GameUserSettings.ini?
Because on every start my configs get blank or changed.

**Comment by klightspeed** [comment]
The tool does not modify the ini files.

The ARK server rewrites the ini files on every startup.  If the file cannot be parsed as an ini file, or if it contains the UTF-16 Byte Order Mark (the `FE FF` bytes at the start) and cannot be decoded as UTF-16, then the ShooterGameServer will write defaults to the file.
