### ISSUE TITLE
How to install required versions of glibc and gcc on CentOS 6.6

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#34]
Credits:
http://steamcommunity.com/app/346110/discussions/0/594820656473094010/

I'm following this thread and trying to report here every problem I get running these scripts, so you can just follow my commands and hopefully everything will work.

# prerequisites
```
yum groupinstall "Development tools"
yum install glibc-devel.i686 glibc-i686
```

# glibc

```
cd /tmp
wget http://ftp.gnu.org/gnu/glibc/glibc-2.16.0.tar.gz
tar -xvzf glibc-2.16.0.tar.gz
cd glibc-2.16.0
mkdir glibc-build
cd glibc-build
../configure --prefix='/usr'
```

We have to fix a little typo, so run:

```
nano +171 ../scripts/test-installation.pl
```
and **replace** `if (/$ld_so_name/) {` with `if (/\Q$ld_so_name\E/) {`

then install it:

```
make
sudo make install
```

# gcc

This operation takes a lot of space! be sure to have enough!

```
cd /tmp
wget ftp://ftp.gwdg.de/pub/misc/gcc/releases/gcc-4.6.4/gcc-4.6.4.tar.gz
tar -xvzf gcc-4.6.4.tar.gz
cd gcc-4.6.4
./contrib/download_prerequisites
mkdir objdir
cd objdir
../configure --prefix=/opt/gcc-4.6.4
make
make install
mv /usr/lib64/libstdc++.so.6 /usr/lib64/libstdc++.so.6.bak
mv /opt/gcc-4.6.4/lib64/libstdc++.so.6 /usr/lib64/libstdc++.so.6
mv /opt/gcc-4.6.4/lib64/libstdc++.so.6.0.16 /usr/lib64/libstdc++.so.6.0.16
```

**Comment by FezVrasta** [comment]
moved to wiki

**Comment by dgibbs64** [comment]
This is potentially dangerous as you are messing a core function of the distro. I would not recommend this for production servers.

**Comment by klightspeed** [comment]
@dgibbs64 one alternative would be to have a libc and libstdc++ package extracted to e.g. `$arkserverroot/lib`, point `LD_LIBRARY_PATH` at that directory, and use the `ld-linux-x86_64.so.2` contained therein to run the ShooterGameServer executable.

Another alternative might be to install those libraries into `$arkserverroot/Engine/Binaries/Linux`, since the executable requests the dynamic linker to search there for any necessary libraries.

**Comment by klightspeed** [comment]
@dgibbs64 one alternative might be to put the necessary libraries into `$arkserverroot/Engine/Binaries/Linux`.

**Comment by dgibbs64** [comment]
@klightspeed yeah I will be investigating that to see if I can get ark working in that way :)
