### ISSUE TITLE
When attempting to run any rconcmd command/broadcast

### ISSUE THREAD

**Issue by dilbaggins** [FezVrasta/ark-server-tools#340]
i recieve this error:  Negative length at -e line 13.

this is a great script keep up the great work Fez!

/ARK/ShooterGame/Config$ arkmanager rconcmd "getgamelog"
Negative length at -e line 13.

**Comment by klightspeed** [comment]
This suggests that for some reason arkmanager is unable to get the ServerAdminPassword from either arkmanager.cfg or the ServerSettings section of GameUserSettings.ini

**Comment by dilbaggins** [comment]
i have this value in DefaultGameUsersettings.ini.  however i do not in arkmanager.cfg.  should i add to both?  i actually checked permissions on both files and they are set to my "steam" user.  odd one.

**Comment by dilbaggins** [comment]
added  ServerAdminPassword  details to arkmanager.cfg restarted and it works.  i would think the DefaultGameUsersettings.ini value would be the one of note vs on both but whatever works is fine with me.  thank you @klightspeed

**Comment by Lihis** [comment]
You should edit ``GameUserSettings.ini`` not the ``DefaultGameUserSettings.ini``. But good you got it working.
