### ISSUE TITLE
Error receiving response from server: at -e line 11.

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#346]
steam@arkfrancegaming:/root$ arkmanager useconfig pvp saveworld
Running command 'saveworld' for instance 'pvp'
Error receiving response from server: at -e line 11.

steam@arkfrancegaming:/root$ arkmanager useconfig pvp restart
Running command 'restart' for instance 'pvp'
Error receiving response from server: at -e line 11.

Still got the same issue since the last update

**Comment by klightspeed** [comment]
Is this returning immediately or is it giving the error after about 30 seconds?

**Comment by arkfrancegaming** [comment]
immediately

**Comment by arkfrancegaming** [comment]
start seems to work 

steam@arkfrancegaming:/root$ arkmanager useconfig pvp start
Running command 'start' for instance 'pvp'
The server is already running

**Comment by arkfrancegaming** [comment]
got that one now 

steam@arkfrancegaming:/root$ arkmanager useconfig valhalla saveworld
Running command 'saveworld' for instance 'valhalla'
Undefined subroutine &main::len called at -e line 12.

**Comment by klightspeed** [comment]
Sorry, I don't have access to the computer on which I would normally develop and test.  

#348 should fix the latest issue.

**Comment by arkfrancegaming** [comment]
nope it doesn't, i'm having this after the #348 

steam@arkfrancegaming:/root$ arkmanager useconfig valhalla saveworld
Running command 'saveworld' for instance 'valhalla'
Undefined subroutine &main::len called at -e line 12.

**Comment by klightspeed** [comment]
Pull Request #348 hasn't been merged yet.

Try downloading arkmanager directly from https://raw.githubusercontent.com/klightspeed/ark-server-tools/1.5-dev%23fixlenrcon/tools/arkmanager, making it executable, and trying to run commands using that until the pull request is merged.

**Comment by arkfrancegaming** [comment]
True, working fine for me now :) thanks
