### ISSUE TITLE
arkmanager update dosn't get the latest version

### ISSUE THREAD

**Issue by morggin** [FezVrasta/ark-server-tools#350]
when running arkmanger update it dosn't seem to be pulling down the latest version.  I have to do arkmanager update --force and it will pull down.  arkmanager version check is not reporting properly.  or the file that get's written to is not updating properly. Any suggestions to fix this?  I have already done a wipe and reinstall of all the services involved. (using rm -rf ark, then removing steam and steamcmd folders the same way and reinstalling steamcmd)

**Comment by morggin** [comment]
today i ran arkmanager checkupdate
Querying Steam database for latest version...
Current version:  914664
Available version:  914664
Your server is up to date!

Then i ran arkmanager update --force
Stopping server...
The server has been stopped
Performing ARK update
Redirecting stderr to '/home/morggin/steamcmd/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x61) downloading, progress: 14.58 (196947225 / 1350878017)
 Update state (0x61) downloading, progress: 32.62 (440700145 / 1350878017)
 Update state (0x61) downloading, progress: 38.84 (524638020 / 1350878017)
 Update state (0x61) downloading, progress: 51.62 (697258167 / 1350878017)
 Update state (0x61) downloading, progress: 60.79 (821139928 / 1350878017)
 Update state (0x61) downloading, progress: 65.67 (887144391 / 1350878017)
 Update state (0x61) downloading, progress: 87.54 (1182524267 / 1350878017)
 Update state (0x61) downloading, progress: 100.00 (198264432 / 198264432)
 Update state (0x61) downloading, progress: 100.00 (198264432 / 198264432)
Success! App '376030' fully installed.
The server is starting...
The server is now up

arkmanager checkupdate
Querying Steam database for latest version...
Current version:  916153
Available version:  916153
Your server is up to date!

**Comment by klightspeed** [comment]
Does `/home/morggin/Steam/appcache/appinfo.vdf` exist after an update?

In `arkmanager.cfg`, is `steamcmd_appinfocache` set to `/home/morggin/Steam/appcache/appinfo.vdf`?

**Comment by morggin** [comment]
yes that entry is in my config.  But it looks like i removed my steam directory during my cleanup.  i have a .steam but no Steam folder under /home/morggin

i just did mkdir Steam followed by mkdir Steam/appcache, then did touch appinfo.vdf.  I'll see if that works.

**Comment by klightspeed** [comment]
Is there an appcache directory anywhere under the home directory of whoever you're running arkmanager under?

```
find "$HOME" -type d -name "appcache"
```

**Comment by morggin** [comment]
i found one under /home/morggin/steamcmd/appcache with appinfo.vdf i pointed the config file at it instead and seems to have resolved the issue.

**Comment by morggin** [comment]
This issue seems to be resolved once i pointed the appcache at /home/morggin/Steam/appcache/appinfo.vdf

Thanks for your assistance klightspeed.
