### ISSUE TITLE
RCon Required?

### ISSUE THREAD

**Issue by PureLoneWolf** [FezVrasta/ark-server-tools#351]
Hi

Does the server need rcon to be enabled to send the warning message before the update takes place?  I don't want to trigger it, only to discover that noone got any warning.

Many thanks

**Comment by klightspeed** [comment]
Yes, RCON needs to be enabled in order to communicate with the server, including sending broadcasts and forcing a saveworld.

**Comment by PureLoneWolf** [comment]
Great, thanks for the info :)
