### ISSUE TITLE
Server is not loading arkmanager.ini settings from /etc/arkmanager

### ISSUE THREAD

**Issue by kylekoch012186** [FezVrasta/ark-server-tools#352]
When launching the server everything starts up normally but when you go to connect to it the server name says "ark-server-tools" and does not ask for my password so its not loading the ini file.  where is it pulling the ini file from and how can i force it to pull from the /etc/arkmanager folder?

What else do i need to supply?

**Comment by kylekoch012186** [comment]
Things to note:
Running as user steam which is same accounts steamcmd uses
all files installed to default locations

**Comment by kylekoch012186** [comment]
Fixed it!

the ini-file the server is pulling is inside the home folder /home/steam/.arkmanager.cfg

when looking at the arkmanager script in the bin folder on lines 120 to 127 it first pulls from the etc folder then immediately pulls from the home folder afterwards; thereby making the one in etc folder useless.

**Comment by klightspeed** [comment]
First, it's not an ini file but a bash config file that ARK Server Tools uses.

The name of the file it uses is `arkmanager.cfg`, not `arkmanager.ini`

The script pulls first from the global config `/etc/arkmanager/arkmanager.cfg` then from the user-local config `~/.arkmanager.cfg` so that the settings in the latter file can override those in the former file.

**Comment by kylekoch012186** [comment]
You are absolutely correct sir... in my haste to write that post I did not stop to put myself in check.

As for the scripts, the install guide says to modify only the one in etc.  following those instructions yielded me 2 hours of frustrations and only after looking at the arkmanager code in /bin did we notice that it was pulling from the $home location.

However we now have it working and are playing with mods.
