### ISSUE TITLE
arkmanager.cfg code mistype

### ISSUE THREAD

**Issue by kylekoch012186** [FezVrasta/ark-server-tools#355]
line 30
#serverMapModId="469987622"  
(causes Signal 11: Segmentation Fault)

should be

#ark_MapModId="469987622"

**Comment by klightspeed** [comment]
`serverMapModId=469987622` is used for replacing the `TheIsland` map name with `-MapModID=469987622`, as shown in http://ark.gamepedia.com/193.0

**Comment by klightspeed** [comment]
Additionally, that mod (http://steamcommunity.com/sharedfiles/filedetails/?id=469987622) hasn't been updated since July last year, so is guaranteed not to be compatible with the current version of the game.

**Comment by kylekoch012186** [comment]
I was just using the code that is preincluded with the arkmanager.cfg file from here

**Comment by klightspeed** [comment]
So, you were not uncommenting the `serverMapModId` line?  Lines that start with a comment character `#` are ignored.

**Comment by FezVrasta** [comment]
Closing for lack of reply.
