### ISSUE TITLE
Server running: NO [After adding Mods]

### ISSUE THREAD

**Issue by NLBlackEagle** [FezVrasta/ark-server-tools#356]
Hello,

After getting the server online and working I decided to trow on some mods, here's a breakdown of what I did:

Opened file: arkmanager.cfg in etc/arkmanager and adjusted the following setting:

#ark_GameModIds="487516323,487516324,487516325"    to:
ark_GameModIds="505861851,520879363,533828549,511168000,539464369,510590313"   

These are the following mods:

Metal with Glass Set 510590313
Advanced Architecture 539464369
Many New Items 511168000
No colossion mod 533828549
Stairs Mod 520879363
security mod 505861851
pandora isle 584076324

After saving the file I used the following command to install/update the mods:
arkmanager update --update-mods

After all mods where installed I typed
arkmanager start
arkmanager status
which gave me the following result:

Server running: no
server listening: no
server version: 927005

I have tried to remove the mods from the arkmanager.cfg using the # but this didnt changed anything at all. I Also tried renaming the workshop map.

arkmanager.cfg:
http://hastebin.com/ejegavenoc.vala

GameUserSettings.ini:
http://hastebin.com/adolirurab.hs

Game.ini:
http://hastebin.com/equnucoxec.ini

Workshop_lag:
http://hastebin.com/pedijepupa.vbs

[Fix: Install each mod independent from each other using]

arkmanager installmod INSERT-MOD-ID-HERE
Also note that I havent installed pandora isle's since I suspect that one from causing the issue.

**Comment by tmtylblog** [comment]
Hey BlackEagle. I'm having the exact same issue. It worked when I installed it. Then I ran the mods update in the same way you did and I got the same result of it not running.

I did install them each individually though, but I can't get the server to start back up to save my life.

**Comment by tmtylblog** [comment]
On a side note this is driving me nuts. :(

**Comment by klightspeed** [comment]
@NLBlackEagle do the last two lines mean that you solved your issue?

**Comment by NLBlackEagle** [comment]
I found out that the mods werent installed at all while this is needed to get it all working ofcourse.
Installing the mods independant from each other resolved my issue like this:

arkmanager installmod MODIDHERE

( If this doesnt work try: arkmanager --installmod MODIDHERE )

Have fun playing on your servers guys! I'm currently working on getting the ARK dev Kit working again to make a couple of floating islands! See you there if it becomes a success :)
