### ISSUE TITLE
sleep 5 on parent process is causing lag

### ISSUE THREAD

**Issue by toxster** [FezVrasta/ark-server-tools#357]
There is a 'sleep 5' that's looping on the parent that spawned the server, this have an impact on the performance on the server.

**Comment by klightspeed** [comment]
`sleep 5` does nothing for 5 seconds.  The purpose of calling it is to delay 5 seconds between each status check on the server, to detect when the server comes up, and if it successfully starts then restart it if it crashes.

The `sleep` program should have essentially zero impact on the server.  If it does have an impact on the server, then your `sleep` program isn't sleeping, and/or your environment is broken.

It might be possible to have sleep spawned only once by using process redirection and the `read -t 5` command.

If you have a lot of processes on the server, then `lsof`, which the status check calls, could cause some performance impact.

**Comment by toxster** [comment]
Yeah but even after a start/restart i can see a sleep 5 popping up each 5 seconds and its spawned from the main thread

V1.4
