### ISSUE TITLE
False "Server is up" message

### ISSUE THREAD

**Issue by axi92** [FezVrasta/ark-server-tools#358]
When I start the Server it says starting and instantly after that "Server is up"
It doesnt matter to me but its a bit of a false info.
I just look up the cpu and when its not on 100% the server is up thats how i do it for now^^

**Comment by klightspeed** [comment]
`arkmanager` should log `server is up` in arkserver.log when the server goes online.

**Comment by FezVrasta** [comment]
:+1:

**Comment by axi92** [comment]
Would make more sense =)
