### ISSUE TITLE
GameUserSettings.ini overwritten on start?

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#36]
If I edit:

```
home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
```
then, when I start the server, this file is overwritten by default values.

How can I fix it?

**Comment by Atriusftw** [comment]
Are you appending any arguments in the launch options that include any of the settings?

**Comment by FezVrasta** [comment]
I'll try and let you know

**Comment by FezVrasta** [comment]
This is mi GameuserSettings.ini

```ini
[/script/engine.gamesession]
MaxPlayers=70

[ServerSettings]
ShowMapPlayerLocation=True
ServerHardcore=False
GlobalVoiceChat=True
ProximityChat=True
NoTributeDownloads=False
AllowThirdPersonPlayer=True
AlwaysNotifyPlayerLeft=True
DontAlwaysNotifyPlayerJoined=True
ServerPVE=False
ServerCrosshair=True
ServerForceNoHUD=False
DifficultyOffset=0.7
```

It doesn't define anything defined in the start script.

**Comment by Kerdian** [comment]
The instructions : [/script/engine.gamesession] and [ServerSettings] it does not launch

**Comment by FezVrasta** [comment]
Sorry @Kerdian I don't get what you mean

**Comment by Kerdian** [comment]
@FezVrasta : same problem as you

**Comment by Atriusftw** [comment]
Strange. Did you copy the .ini from windows maybe? Permissions issue?

**Comment by FezVrasta** [comment]
No, written directly with nano

**Comment by FezVrasta** [comment]
after the last update the configuration file seems to work. weird!
