### ISSUE TITLE
World not being saved

### ISSUE THREAD

**Issue by zanatarp** [FezVrasta/ark-server-tools#360]
Hello,

Personal'm testing in a virtual machine, where I used an already saved world (before the Windows server)

I changed the name of the folder to LinuxServer WindowsServer everything worked just right, but when I use the command "arkmanager saveworld" wait 20 minutes and turn off the server.

Connecting to the server I see that the world is not saved, it comes back to where it was before turning on the server.

**Comment by klightspeed** [comment]
Make sure the world files and the SavedArks directory are owned by and writeable by the user running the ARK server.

i.e. if the ARK server user is `steam`, make sure that the files and directories are owned by steam (`chown -R steam /home/steam/ARK/ShooterGame/Saved`) and that the files and directories are writeable by the owner (`chmod -R u+w /home/steam/ARK/ShooterGame/Saved`).

**Comment by Lihis** [comment]
Sounds like a permission issue. I have migrated ARK server to another server couple times and never had issues, this is of course between linux servers.

**Comment by dmfelix** [comment]
Hey!

Im having the same issue, tried permissions, running the server in sudo.

tried force saving the world but its still not creating a save file

**Comment by Valdm** [comment]
Hi,

Im also having the same issue, but when executed command he say "Cannot
connect to server" but server running..

Thank you for our work.

Le mer. 27 janv. 2016 à 09:51, dmfelix <notifications@github.com> a écrit :

> Hey!
>
> Im having the same issue, tried permissions, running the server in sudo.
>
> tried force saving the world but its still not creating a save file
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/360#issuecomment-175489534>
> .
>
-- 
Cordialement,

Valentin LANDEMAINE

**Comment by Valdm** [comment]
your*


Le mer. 27 janv. 2016 à 10:00, Valentin Landemaine <val.landemaine@gmail.com>
a écrit :

> Hi,
>
> Im also having the same issue, but when executed command he say "Cannot
> connect to server" but server running..
>
> Thank you for our work.
>
> Le mer. 27 janv. 2016 à 09:51, dmfelix <notifications@github.com> a
> écrit :
>
>> Hey!
>>
>> Im having the same issue, tried permissions, running the server in sudo.
>>
>> tried force saving the world but its still not creating a save file
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/FezVrasta/ark-server-tools/issues/360#issuecomment-175489534>
>> .
>>
> --
> Cordialement,
>
> Valentin LANDEMAINE
>
-- 
Cordialement,

Valentin LANDEMAINE

**Comment by klightspeed** [comment]
@dmfelix Do you have `ark_AltSaveDirectoryName` set?

If the ARK server root is in `/home/steam/ARK`, what does the following command give you:
```
ls -l /home/steam/ARK/ShooterGame/Saved
```

@Valdm if the exact error is `Error connecting to server`, then this suggests that RCON is disabled.

**Comment by Nodens-** [comment]
Error message `Error connecting to server at -e line 32.`also means the same thing. Make sure the RCON port is set properly and that RCON is enabled by setting:
`RCONEnabled=True
RCONPort=32330`

Setting the port alone won't do it. Also make sure the port is open for TCP on your firewall.

**Comment by Nitric81** [comment]
I have this issue too on top of my other issue. When the server is launched it gives me a warning that the SavedArk folder is not writable. I have performed the following, `chown -R steam /home/steam/ARK/ShooterGame/Saved` and `chmod -R u+w /home/steam/ARK/ShooterGame/Saved`

Also I have checked the arkmanager.cfg and RCON is enable. Also the port is set to 32330. I have also made sure the port is set in iptables.

**Comment by Nodens-** [comment]
Do these to ensure proper default permissions:
`chown -R steam:steam /home/steam`
`chmod -R 755 /home/steam/ARK`
`chmod -R 775 /home/steam/Steam`
`chmod -R 775 /home/steam/steamcmd`

Assuming ark is in ARK as deducted from the commands you listed and that steamcmd is in the default steamcmd directory.

RCON should be irrelevant, you certainly have a permissions issue and looks like your other issue is also related to permissions. If after doing the above you still get the issue, try `su -c "touch /home/steam/ARK/ShooterGame/Saved/SavedArks/test" steam` That will show you if user steam can actually write in the exact directory specified in the error message.

**Comment by klightspeed** [comment]
@Nitric81 The script will give this warning when the server is launched for the first time, as the server hasn't yet created the SavedArks directory.

**Comment by klightspeed** [comment]
Is this fixed with the hotfix to v1.5?

**Comment by klightspeed** [comment]
Closing old issues
