### ISSUE TITLE
Mods don't get loaded

### ISSUE THREAD

**Issue by SirWilli** [FezVrasta/ark-server-tools#362]
hey,

I added this line to `.arkmanager.cfg` but it doesn't add the mods to the server.
```
ark_GameModIds="558651608,576432474"
```

**Comment by ajziehl** [comment]
Have you done this for each mod:

    arkmanager installmod #########

**Comment by SirWilli** [comment]
No, I wasn't aware that you have to run a command to add mods. I thought it auto installs it if it is defined in the config.

**Comment by axi92** [comment]
Normally, yes!

**Comment by SirWilli** [comment]
@axi92 default config shows something else: https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager.cfg#L40

With your formatting it is not needed to run the command?

**Comment by axi92** [comment]
Lol your right but i have it like this and its working?^^

**Comment by SirWilli** [comment]
It did work after running the command mentioned above. It just would be great if there is a way without running the command.

**Comment by axi92** [comment]
Now what does your config look like?

**Comment by SirWilli** [comment]
Hm, what exactly do you want to know and for what?

**Comment by axi92** [comment]
You performed the command now the command must change something in the config.
Is it now like this
```
ark_GameModIds="558651608,576432474"
```
or like this
```
ark_GameModIds="558651608","576432474"
```

**Comment by SirWilli** [comment]
It still shows it as
```
ark_GameModIds="558651608,576432474"
```

**Comment by axi92** [comment]
Oh ok thats funny xD

**Comment by FezVrasta** [comment]
Closing the issue as it doesn't seem related to a problem of the script.

**Comment by SirWilli** [comment]
I did leave it open as feature request ;)

**Comment by FezVrasta** [comment]
I've opened an issue with the feature request and has been implemented.
