### ISSUE TITLE
Remove servicename variable from systemctl script

### ISSUE THREAD

**Issue by barfinup** [FezVrasta/ark-server-tools#366]
I'm not sure if this was your intended use of the variable, but since I use systemd to handle auto restarts on crash, I put in sections just to use the service

I added the following at the top of the doRun routine:
    if [ "$servicename" ]; then
      systemctl start "$servicename"
      return $?
    fi

and this to doStop just above the '#kill the server with the PID' comment:
    if [ "$servicename" ]; then
      systemctl stop "$servicename"
    else

Of course if you add that in, then you may want to comment out the $servicename variable from the .cfg file by default so people must add it if they want that behaviour
Probably also need a new variable for people to set whether they want to use service, systemctl, or other as their service command (or auto detect this for them..)

**Comment by klightspeed** [comment]
This would introduce a loop, since with that:
 * `systemctl start arkmanager` calls
   * `systemctl start arkmanager@instance` calls
     * `arkmanager useconfig instance run` calls function
       * `doRun` calls
         * `systemctl start arkmanager` calls
           * `systemctl start arkmanager@instance` calls
             * `arkmanager useconfig instance run` calls function
               * `doRun` calls ...

And
 * `systemctl stop arkmanager` calls
   * `systemctl stop arkmanager@instance` calls
     * `arkmanager useconfig instance stop` calls function
       * `doStop` calls
         * `systemctl stop arkmanager` calls
           * `systemctl stop arkmanager@instance` calls
             * `arkmanager useconfig instance stop` calls function
               * `doStop` calls ...

Also, at the moment the arkmanager executable itself is handling auto-restarts.

I think the `servicename` variable, like the old `servermail` variable, can be removed, as it has never been used.

**Comment by barfinup** [comment]
I see you intended 'servicename' to mean the arkmanager service, not the ark service

Since I already had my ark.service set up however, I do not have a loop because it is calling 'systemctl start ark' not 'systemctl start arkmanager'

Thanks for the clarification
