### ISSUE TITLE
ark-server-tools overwrites GameUserSettings.ini?

### ISSUE THREAD

**Issue by Bubelbub** [FezVrasta/ark-server-tools#367]
Hello,

Is it possible that the server tools overwrites my configuration each time I enter `arkmanager start`?

I put something in `/home/ark/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini` or `/home/ark/ARK/ShooterGame/Saved/Config/CleanSourceConfigs/GameUserSettings.ini` and after a start it's deleted.

Can I search the problem here or somewhere else? Maybe you can help?
Thanks in Advance!

**Comment by FezVrasta** [comment]
https://github.com/FezVrasta/ark-server-tools/issues/294

and

https://github.com/FezVrasta/ark-server-tools/issues/260

**Comment by axi92** [comment]
Your config is invalid therefore ark itself cleans it up.

**Comment by Bubelbub** [comment]
Oh that's bad :-1: 

First try generated through http://ini.arkforum.de/.
Second try generated through ARK Server Manager. (The Windows GUI one)

And it's overwritten with both.

Maybe encoding is different!?

**Comment by FezVrasta** [comment]
Are all the settings being overwritten or just some of them?

**Comment by klightspeed** [comment]
Only write `/home/ark/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini`.  Do not write `/home/ark/ARK/ShooterGame/Saved/Config/CleanSourceConfigs/GameUserSettings.ini`

How are you writing to the file?

**Comment by Bubelbub** [comment]
@FezVrasta:
Yes the whole file is overwritten. (Game.ini and GameUserSettings.ini)

@klightspeed:
I write only the first one.
I tried to delete this `/home/ark/ARK/ShooterGame/Saved/Config/CleanSourceConfigs/` and `/home/ark/ARK/ShooterGame/Config/` Folder.

Maybe the attachments are helpfull to help me? :)

[My-GameUserSettings.ini.txt](https://github.com/FezVrasta/ark-server-tools/files/108382/My-GameUserSettings.ini.txt)
[My-Game.ini.txt](https://github.com/FezVrasta/ark-server-tools/files/108383/My-Game.ini.txt)

And after start and stop:

[Overwritten-GameUserSettings.ini.txt](https://github.com/FezVrasta/ark-server-tools/files/108389/Overwritten-GameUserSettings.ini.txt)
[Overwritten-Game.ini.txt](https://github.com/FezVrasta/ark-server-tools/files/108390/Overwritten-Game.ini.txt)

**Comment by klightspeed** [comment]
Your GameUserSettings.ini contains UTF8 characters (i.e. characters with codepoints above 127 - e.g. your ß character).  The last time I checked, the ARK server did not support UTF8, and instead used UTF16 when writing configs with non-ascii characters.

**Comment by Bubelbub** [comment]
@klightspeed ;
Hmm it's not working if I remove them.

And very funny:
I set the files read only with `chattr +i GameUserSettings.ini` and can't modify it manually.
After server start the whole folder is deleted and recreated.
I don't know what's wrong with this :-1:

**Comment by klightspeed** [comment]
Of course setting the file immutable is going to cause you to be unable to modify it.

Setting the file immutable does not prevent it from being deleted.

**Comment by Bubelbub** [comment]
Ah and before you mean I should change the windows crlf to unix lf? Let me try it :+1:

**Comment by klightspeed** [comment]
> Ah and before you mean I should change the windows crlf to unix lf? Let me try it :+1: 

Negative, no, nein.

The server will just change the Unix LF newlines back to Windows CRLF newlines.  If you use a decent editor, it should have no problem with Windows CRLF newlines.

**Comment by Bubelbub** [comment]
Ok so what could I try?

By the way: Thanks for help!

**Comment by klightspeed** [comment]
1. Do not set the file immutable or read-only, and make sure the ARK server has permission to write the file
2. Ensure that there are only ASCII characters in the ini file, or that you convert the file to a UTF16 encoding with Byte Order Mark (BOM) using e.g. `iconv -f utf8 -t utf16 My-GameUserSettings.ini.txt -o GameUserSettings.ini`
3. Do not write the CleanSourceConfigs

**Comment by Bubelbub** [comment]
With your command the file looks in `nano` like...
![2016-01-28 18_10_21](https://cloud.githubusercontent.com/assets/319352/12652290/6d5a4ec0-c5ea-11e5-81fa-fd55e24465b2.png)

And its annoying -.-
Each time I enter `arkmanager start` the whole directory is overwritten I think.
![2016-01-28 18_14_21](https://cloud.githubusercontent.com/assets/319352/12652406/fafdd4b8-c5ea-11e5-916c-bc314dda35a7.png)

I replaced all `ß` with `ss` and the `ä` with `a`.


Something about permissions... I tried:

1. Folder LinuxServer deleted and server started
![2016-01-28 18_18_57](https://cloud.githubusercontent.com/assets/319352/12652560/9f22f00a-c5eb-11e5-96d1-1c3194db22eb.png)

2.1. File permissions changed AND files replaced with mine (if not then there is no change)
![2016-01-28 18_20_16](https://cloud.githubusercontent.com/assets/319352/12652598/cd50a3d2-c5eb-11e5-8e10-5af0e8ca232c.png)

2.2. After server start
![2016-01-28 18_21_24](https://cloud.githubusercontent.com/assets/319352/12652630/f72a5e14-c5eb-11e5-9b1a-43ab703c2fc8.png)

Don't know what's wrong :-1:

**Comment by Bubelbub** [comment]
Ok how I fixed this after few hours of testing...

- Reinstalling server folder with `arkmanager install` (and `rm -rf /home/ark/ARK` before)
- Starting the server `arkmanager start`
- Stopping the server `arkmanager stop`
- Editing the server configuration via Notepad++ (Downloaded file and uploaded after) and added only the variables to the sections. Not deleting existing ones. So at the end I removed only duplicated entries. Then I had for example RCON Options at the top. (Which are default)
- Starting

I think the problem is either the missing RCON configuration or some things which are important or it was an encoding problem or dont know some file related things and because I add only things it doesnt affect the header of the file.


But I'm happy now - It work's :+1:

**Comment by axi92** [comment]
This is how to fix it, had the same problem.
And dont delete something out of the generated files.

**Comment by Nightreaver** [comment]
> This is how to fix it, had the same problem. http://survivetheark.com/index.php?/forums/topic/1614-gameini-wont-save-and-gets-blank-on-server-start/&do=findComment&comment=47538 And dont delete something of the generated files.

Almost 10 years later, most useless answer - but thank you anyways.

Whoever stubles across this issue again:

`iconv -f utf16 -t utf8 GameUserSettings.ini.txt -o GameUserSettings-fixed.ini`

**Comment by klightspeed** [comment]
> > This is how to fix it, had the same problem. http://survivetheark.com/index.php?/forums/topic/1614-gameini-wont-save-and-gets-blank-on-server-start/&do=findComment&comment=47538 And dont delete something of the generated files.
> 
> Almost 10 years later, most useless answer - but thank you anyways.
> 
> Whoever stumbles across this issue again:
> 
> `iconv -f utf16 -t utf8 GameUserSettings.ini -o GameUserSettings-fixed.ini`

Does the ARK server now support UTF8?
