### ISSUE TITLE
Add a warning if a mod added to the cfg has not been installed

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#368]
Seen that most of the people try to add mods just putting the ID in the configuration, is there a way to make the script check if the mod is installed and warn the user about it?

ping @klightspeed

**Comment by SirWilli** [comment]
or auto install the mod if it is not installed :)

**Comment by FezVrasta** [comment]
I prefer the warning and let he user decide what to do.

**Comment by SirWilli** [comment]
Not sure why you would want to add the mod id to the config if you don't want to install it but ok.

**Comment by klightspeed** [comment]
#364 would add the option to automatically update on startup.
