### ISSUE TITLE
too many arguments

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#373]
Since the last 1.5 update, i've got that issue :

steam@arkfrancegaming:/root$ arkmanager useconfig pve status
/usr/local/bin/arkmanager: ligne 207 : [: too many arguments
Running command 'status' for instance 'pve'
/usr/local/bin/arkmanager: ligne 207 : [: too many arguments
 Server running:   Yes
 Server listening:   Yes
Server Name: [FR] ARK FRANCE - PvE x5 - (v233.1)
Players: 26 / 80
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/149.202.86.142:27016
 Server version:   952146

**Comment by FezVrasta** [comment]
Ping @klightspeed (sorry I've no idea about this problem).

@arkfrancegaming remember that 1.5 is not stable yet, thanks for the bug report.
