### ISSUE TITLE
--update-mods not working correctly...

### ISSUE THREAD

**Issue by thakyZ** [FezVrasta/ark-server-tools#377]
When I execute the command `arkmanager update --update-mods` it goes to steam command like it should, then logs in, and after "Waiting for license info...OK" it stops and does absolutely nothing at all.
The parameter on the arkmanager.cfg is as follows:
`ark_GameModIds="547099024,542073905,520275192,517605531,496483916"  # Uncomment to specify additional mods by Mod Id separated by commas`

**Comment by klightspeed** [comment]
You will find that after a few minutes it will either fail and retry, or complete the download.

steamcmd's `workshop_download_item` gives no progress info, and in fact the `Downloading item nnnnnnnnn ...` is not `fflush`ed to the screen until just before it either completes or gives up waiting.

**Comment by thakyZ** [comment]
Oh ok I will try again but they should really fix that...

**Comment by Evilcious** [comment]
I second that. I had to deactivate the mods on my server for that reason.

**Comment by FezVrasta** [comment]
We maybe add a warning before the steam shell is enabled letting the user know that we have no way to show a progress bar...

Or we may just hide at all the steam shell and just show a dummy spinner during the update?

**Comment by Evilcious** [comment]
When I add some mods in my config files, the `arkmanager update --update-mods `works but the Ark client dosn't display the server. When I try to join using the steam URL, the client complaints that some of the mods are not up to date.

Any idea ?

**Comment by axi92** [comment]
You cant join a server that is running with old mods you have to have always the newest mods from the workshop.

**Comment by klightspeed** [comment]
@Evilcious what version does `arkmanager status` show the server being at (both the version after the server name and the build ID), and what version does the client say it is?

The latest server build ID according to steamdb.info as at 2016-02-03 08:45 UTC is 954561.

The current server (build ID 954561) says it's version 234.1

The current client (build ID 954571) says it's version 234.0

It also appears that we'll probably have to change the fully downloaded logic to see if any directories exist in the workshop downloads directory or remove the `appworkshop_${modappid}.acf` file before updating a mod, as steamcmd will try to update all of the mods it has ever installed when you ask it to download a specific mod.

**Comment by Evilcious** [comment]
@axi92 : I know about that. I know I can manually update the mods but that's not the goal here ^^

@klightspeed : My server is in build ID 954561 (version 234.1). When I comment the mods line in my .cfg and restart my server, it works fine.
When I uncomment the mods line in the cfg, I tried to use "installmod <id>" command, "--update-mods" command and the client still says that there may be one or more outdated mods.

So, if I want to manually update the mods, in which directory do I have to copy the files ?

**Comment by klightspeed** [comment]
@Evilcious Please try removing the `/home/steam/steamcmd/steamapps/workshop/appworkshop_346110.acf` file and try again.

**Comment by Evilcious** [comment]
I tried your method. I also tried to remove the mods from both places : 
`/home/steam/servers/ark/ShooterGame/Content/Mods/` and `/home/steam/steamcmd/steamapps/workshop/content/346110/`

It still doesn't work.

Maybe it's one of the mods that don't go well with current client. I'll try to find the culprit !

Thanks anyway ;)

**Comment by Evilcious** [comment]
I found the problem. I had two mods that weren't compatible. Sorry about that.
