### ISSUE TITLE
Can't figure out systemd implementation.

### ISSUE THREAD

**Issue by Nodens-** [FezVrasta/ark-server-tools#378]
I am trying to figure out the exact flow of the systemd implementation. Prior to using ark-server-tools
I had made a custom systemd service in order to start the server.

Now with arkmanager, I can't figure out exactly how it implements systemd support. I see two service files, a one-shot calling arkmanager.init and a arkmanager@.service which is normally used for multiuser service support.

 At this point I am assuming that enabling the arkmanager service is the thing to do for autostarting the server on reboots. The way this service is set up though means that checking the service via systemd is not possible anymore and one should resort only to "arkmanager status", correct?

 What I want to know is exactly how does the script handle checking if the service is up and restart it if it has failed, if it does at all. Do I have to use a cron job for that? The way I had setup my systemd unit, it would restart if the service died for any reason. Couldn't the systemd unit implementation be changed so that the script uses a failsafe service unit and calls that to do all of it's start/stop/restart operations? Would not that be much cleaner than having to use cronjobs? If the script does handle that indeed, shouldn't the systemd unit that calls the script make sure the script is always running? Unless there's something at play here that I do not understand. While I am a software developer my area of expertise is asm and C, I have never done any shell scripting and while it's kind of easy to read I'm not accustomed to it.

 I also do not understand where servicename="arkserv"  in arkmanager.cfg is used. There is no systemd unit, script or elf binary called arkserv. And I don't see the "servicename" variable referenced in the script as well.

I also see this in ps -aux when starting via systemctl start arkmanager:
root      6635  0.0  0.0 115240  1592 ?        Ss   19:55   0:00 /bin/bash /usr/local/bin/arkmanager useconfig main run
root      6670  0.0  0.0 185728  2404 ?        S    19:55   0:00 su steam -c /usr/local/bin/arkmanager useconfig main run
steam     6671  0.0  0.0 113516  1912 ?        Ss   19:55   0:00 /bin/bash /usr/local/bin/arkmanager useconfig main run
steam     6678 29.0 54.1 5341564 4324112 ?     Sl   19:55   6:06 /home/steam/ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?SessionName=Not_important?listen

Executing as root, running again with su before we land to the actual process run by the steam user. Shouldn't the systemd unit run directly as the steam user and not do the above which is rather insecure as well?

**Comment by klightspeed** [comment]
arkmanager is init system agnostic, and doesn't have any deep systemd integration.

The arkmanager@.service is used for multi-instance support - to e.g. start the "main" instance, one would run `systemctl start arkmanager@main`

The arkmanager@.service spawns and monitors `arkmanager useconfig %i run`

To avoid the explicit su, we could add `User=steam` to arkmanager@.service, and modify that during install.

`arkmanager run` then runs the ARK server using the parameters specified in the arkmanager.cfg and instance config files, monitors the server, and restarts it if it exits after having gone online.

After #379 is applied, the `arkmanager` and `su -c arkmanager` processes running as root should no longer be spawned, and `systemctl stop arkmanager@main` should work properly.

**Comment by Nodens-** [comment]
Ok this makes more sense now. So basically for general system reboots, should I enable arkmanager@main or plain arkmanager? From your explanation on single server instance setup arkmanager.service just calls arkmanager@main so they are identical, correct?

Also from my understanding `systemctl status arkmanager@main` should show if the script is currently running via systemctl?

I agree that adding `User=steam` to the unit and modify it via the install script if another user is being used, hence dropping the su dependency altogether, is better design. Running the script with root privileges is never a good idea on a server environment, if you can avoid it. Systemd should just start it as the steam user.

**Comment by klightspeed** [comment]
Is this resolved?

**Comment by klightspeed** [comment]
Closing old requests
