### ISSUE TITLE
(dev#1.1) isUpdateNeeded function is not working

### ISSUE THREAD

**Issue by Atriusftw** [FezVrasta/ark-server-tools#38]
When checking for new updates, it always prints that there isn't any updates available.

It only works when updating manually with steamcmd first.

**Comment by Sispheor** [comment]
Yes, we should call getCurrentVersion and setCurrentVersion after the install to get the installed version for the first time.

**Comment by FezVrasta** [comment]
Isn't it already fixed?

https://github.com/FezVrasta/ark-server-tools/blob/dev%231.1/tools/arkmanager#L186-L187

**Comment by Atriusftw** [comment]
I'm running dev1.1, and it's not working as intended.
Still get No update available (Trying to fetch patch 179.3 right now)

**Comment by Sispheor** [comment]
Open the file arkversion in ARK folder and change de number of version.
Then try again.

2015-06-23 14:58 GMT+02:00 Marius Linge <notifications@github.com>:

> I'm running dev1.1, and it's not working as intended.
> Still get No update available (Trying to fetch patch 179.3 right now)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/38#issuecomment-114491118>
> .
>



-- 
*Nicolas MARCQ*

**Comment by FezVrasta** [comment]
Should this print the most recent version?

because it doesn't return anything on my server

```steamcmd/steamcmd.sh +login anonymous +app_info_print 376031 +quit | grep -EA 5 "^\s+\"public\"$" | grep -E "^\s+\"buildid\"\s+" | tr '[:blank:]"' ' ' | tr -s ' ' | cut -f3 | sed 's/^ //' | cut -c9-14```

**Comment by Sispheor** [comment]
I can't tell you if it works for me right now but it was yestarday on my
Ubuntu.

2015-06-23 15:06 GMT+02:00 Fez Vrasta <notifications@github.com>:

> Should this print the most recent version?
>
> because it doesn't return anything on my server
>
> steamcmd/steamcmd.sh +login anonymous +app_info_print 376031 +quit | grep
> -EA 5 "^\s+\"public\"$" | grep -E "^\s+\"buildid\"\s+" | tr '[:blank:]"' '
> ' | tr -s ' ' | cut -f3 | sed 's/^ //' | cut -c9-14
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/38#issuecomment-114494169>
> .
>



-- 
*Nicolas MARCQ*

**Comment by FezVrasta** [comment]
It seems to be a bit too prone to errors when the output changes..

the command returns a json, can't we just parse it?

**Comment by FezVrasta** [comment]
By the way it seems to work now. Closing.
