### ISSUE TITLE
Need Help - Server not listening

### ISSUE THREAD

**Issue by Bakes182** [FezVrasta/ark-server-tools#380]
Hi,

Im not entirely sure of the issue that I have, but since updating my server (arkmanager update) the server itself has disappeared offline. When i run "arkmanager status" I get:

steam@IS-29832:~$ arkmanager status
 Server running:   Yes
 Server listening:   No
 Server version:   954561

Tried netstat and recieved:

steam@IS-29832:~$ netstat -atunp | grep ShooterGame
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 0.0.0.0:32330           0.0.0.0:*               LISTEN      29826/ShooterGameSe
udp      768      0 0.0.0.0:7777            0.0.0.0:*                           29826/ShooterGameSe

I am really not that good at Linux, so if there is anything else i can provide for diagnostics please let me know!

I have also increased ulimit to 100000.

Thanks in advance!

**Comment by Bakes182** [comment]
Update: I have now managed to get a server running off the machine, however this only works after a complete uninstall of arkmanager, and even then the server launches with default values (ie. servername is Ark Server Tools - (v234.1). I have changed the name of the server in both arkmanager.cfg (/etc/arkmanager/arkmanager.cfg) and the game user settings (/home/steam/ARK/ShooterGame/Saved/Config/gameusersettings.ini).

Upon restart of server, it fails to listen at all until i re-install or manually stop and wait half hour then re-start the server in arkmanager. When it restarts, all defaults again!

**Comment by klightspeed** [comment]
That seems to be a normal restart, though it doesn't show the server ever coming online.

> Using binned.
> 4.5.1-0+UE4 7038 3077 402 5
> CtrlCHandler: Signal=2

Here SIGINT was sent to the old server

> 16:01:28: start
> 16:01:28: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?ActiveMods=506506101\?AllowThirdPersonPlayer=True\?MaxPlayers=70\?NoTributeDownloads=True\?Port=7777\?ProximityChat=False\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ResourceNoReplenishRadiusStructures=0.1\?ServerAdminPassword=keyboardcat\?ServerCrosshair=True\?ServerPVE=False\?ServerPassword\?SessionName=ARK\ Server\ Tools\?ShowMapPlayerLocation=True\?listen
> 16:01:28: Server PID: 17053

Here the new server was started after the old server had exited

> /home/steam/bin/arkmanager: line 558: 14920 Aborted "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
> 16:01:28: Bad PID '17053'; expected '14920'
> 16:01:28: exited with status 0

This is due to doStop not checking the status of the monitor process

> [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
> Setting breakpad minidump AppID = 346110

These are output by the new server

> Update: I have now managed to get a server running off the machine, however this only works after a complete uninstall of arkmanager, and even then the server launches with default values (ie. servername is Ark Server Tools - (v234.1). I have changed the name of the server in both arkmanager.cfg (/etc/arkmanager/arkmanager.cfg) and the game user settings (/home/steam/ARK/ShooterGame/Saved/Config/gameusersettings.ini).

Did you perform a user-install at some point?  Does `/home/steam/.arkmanager.cfg` exist?

**Comment by Bakes182** [comment]
The path you specified does not exist, and by user-install what do you mean? I had to "manually update" ark server tools as the automatic update failed... could this be where the error occurred?

**Comment by klightspeed** [comment]
Since `/home/steam/.arkmanager.cfg` doesn't exist, it means you didn't perform a user-install.

@Bakes182 What do you mean by automatic update vs manual update?

**Comment by Bakes182** [comment]
How do I do a user-install?

Instead of using command:

arkmanager  upgrade-tools  

I used uninstall command and then latest version download and install!

Thanks for your help, I'm very new to Linux and it's greatly appreciated!

**Comment by Bakes182** [comment]
Have figured it out.

I'm an idiot. The arkmanager.cfg file within /home/steam/ was a hidden file and winscp wasn't set up to show them. Sorry for the goosechase!

Thanks for your help! @klightspeed
