### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#385]
Error :

17:29:51: start
17:29:51: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?ForceAllStructureLocking=true\?GameModIds=604969053\,558079412\?MaxPlayers=80\?Port=7776\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32333\?ServerAdminPassword=****\?SessionName=\[FR\]\ ARK\ FRANCE\ -\ PvE\ x5\?listen -log -server -servergamelog
17:29:51: Server PID: 17323
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
/usr/local/bin/arkmanager : ligne 631 : 17323 Segmentation fault  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
17:30:44: Bad PID ''; expected '17323'
17:30:44: exited with status 0

**Comment by klightspeed** [comment]
If this is with `mod_branch=Linux`, then see how you fixed it in #252

**Comment by arkfrancegaming** [comment]
# config Service
servicename="arkserv"                                               # Name of the service (don't change if you don't know what are you doing)
logdir="/var/log/arktools/pve"                                      # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID
mod_appid=346110                                                    # App ID for mods

# Mod OS Selection
mod_branch=Linux
# Add mod-specific OS selection below:
#mod_branch_496735411=Windows

# alternate configs
# example for config name "ark1":
configfile_pve="/etc/arkmanager/arkmanager-pve.cfg"

**Comment by klightspeed** [comment]
Change `mod_branch=Linux` to `mod_branch=Windows`

**Comment by arkfrancegaming** [comment]
i tried both when i comment the #ark_GameModIds="572277026,558079412,534838287,544598236,599476919,602214046,564895376"

is says that 


Running command 'start' for instance 'pve'
[  ERROR  ]     Mod 604969053 is requested but not installed.  Run 'arkmanager installmod 604969053' to install this mod.

this mod is in my arkmanager.cfg

**Comment by arkfrancegaming** [comment]
even if i ark_GameModIds=""

i've got the Signal 11 caught.
/usr/local/bin/arkmanager : ligne 631 :  7381 Segmentation fault  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
17:55:23: Bad PID ''; expected '7381'
17:55:23: exited with status 0

**Comment by klightspeed** [comment]
> [ ERROR ] Mod 604969053 is requested but not installed. Run 'arkmanager installmod 604969053' to install this mod.
> this mod is in my arkmanager.cfg

So, are you saying it's telling you to install a mod that you have asked it to load?

> even if i ark_GameModIds=""
> i've got the Signal 11 caught.

Check that you don't have ActiveMods set in your GameUserSettings.ini.

This seems eerily similar to your crashes in #252, where mod 479295136 was apparently being referenced somewhere.

**Comment by arkfrancegaming** [comment]
i've tried to re install the mods with arkmanager useconfig install mod and now i've got that :+1:

**Comment by arkfrancegaming** [comment]
18:09:49: start
18:09:49: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?ForceAllStructureLocking=true\?GameModIds=534838287\,544598236\,558079412\,564895376\,572277026\,599476919\,602214046\?MaxPlayers=80\?Port=7776\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32333\?ServerAdminPassword=*****\?SessionName=\[FR\]\ ARK\ FRANCE\ -\ PvE\ x5\?listen -log -server -servergamelog
18:09:49: Server PID: 18381
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:C:\SVN_Ark\Engine\Source\Runtime\CoreUObject\Private\UObject\LinkerLoad.cpp] [Line: 3814] 
Bad name index -466335544/69
Signal 11 caught.
/usr/local/bin/arkmanager : ligne 631 : 18381 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
18:10:05: Bad PID ''; expected '18381'
18:10:05: exited with status 0

**Comment by arkfrancegaming** [comment]
no activemods in my ini

**Comment by arkfrancegaming** [comment]
i'm downloading the mods manually to try if it changes

**Comment by klightspeed** [comment]
What size is `/home/PVE/ShooterGame/Content/Mods/558079412/Extras/M_ACM_DS.uasset`?

**Comment by arkfrancegaming** [comment]
924 198

**Comment by klightspeed** [comment]
Is this the mod installed by `installmod`, or the mod you uploaded?

**Comment by arkfrancegaming** [comment]
no one was installed by the installmod commend, i always install it manually, but i've tried the command to check if it works but either are not working

**Comment by arkfrancegaming** [comment]
i'm back with the segmentation error event when i upload the mod manually

18:42:43: start
18:42:43: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?ForceAllStructureLocking=true\?GameModIds=572277026\,534838287\,544598236\,558079412\,564895376\,599476919\,602214046\?MaxPlayers=80\?Port=7776\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32333\?ServerAdminPassword=***\?SessionName=\[FR\]\ ARK\ FRANCE\ -\ PvE\ x5\?listen -log -server -servergamelog
18:42:43: Server PID: 29738
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
/usr/local/bin/arkmanager : ligne 631 : 29738 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
18:43:57: Bad PID ''; expected '29738'
18:43:57: exited with status 0

**Comment by arkfrancegaming** [comment]
the server is online for 1 min and then crash

**Comment by arkfrancegaming** [comment]
even with no mods ark_GameModIds=""

**Comment by klightspeed** [comment]
Do you already have a saved world in this install?  Are the mods compatible with the world, and have you removed any mods since you created the world?

The first and last segfaults you posted suggest that there may be something wrong with the saved world, while the middle one suggested that one or more mods were incompatible with the server.

**Comment by arkfrancegaming** [comment]
ok but why when i use no mods it doesn't boot well, that's weird

**Comment by arkfrancegaming** [comment]
no there are the same, i've just update one of my mod and after that no boot at all

**Comment by klightspeed** [comment]
Would you please test whether it's a saved world issue by going into `/home/PVE/ShooterGame/Saved` and renaming `SavedArks` to e.g. `SavedArks-20160205`, and then trying to start the server again with no mods.

**Comment by arkfrancegaming** [comment]
it starts well with a new save and mods ...

**Comment by arkfrancegaming** [comment]
i've found another save which is working i don't know what happen

**Comment by klightspeed** [comment]
It sounds like the save was corrupted.

**Comment by arkfrancegaming** [comment]
it corrupted it self, i've tried the closest save and it was corrupted too, only one from the begining of the after noon

**Comment by D9IDbKA** [comment]
Is serverMapModId line commented in your arkmanager.cfg file?

**Comment by arkfrancegaming** [comment]
yep it's commentend

**Comment by klightspeed** [comment]
@arkfrancegaming Is this resolved?  Was it a corrupt game save?

**Comment by arkfrancegaming** [comment]
corrupt game save :) thanks for the help
