### ISSUE TITLE
maxplayers as startparams 

### ISSUE THREAD

**Issue by puseidr** [FezVrasta/ark-server-tools#39]
it looks like maxplayers in ini file does'nt work, but as a start param.
you should add a new variable to arkmanager.cfg to define the playerlimit and add
```
?MaxPlayers=$arkservermaxplayers
``` 
to the arkserveropts in /usr/bin/arkmanager

**Comment by puseidr** [comment]
maybe its better to build the arkserveropts in the /etc/arkmanager/arkmanager.cfg instead of the /usr/bin/arkmanager

so ppl can modify the opts without changing 2 files

**Comment by Atriusftw** [comment]
Duplicate with https://github.com/FezVrasta/ark-server-tools/issues/26
