### ISSUE TITLE
BattlEye

### ISSUE THREAD

**Issue by kiluMD** [FezVrasta/ark-server-tools#390]
Hello, how I set the BattlEye Anti Cheat into?

-BattlEye is the command

But how I start with this?

**Comment by klightspeed** [comment]
Add `arkflag_BattlEye=""` to your arkmanager.cfg

**Comment by EstSoft87** [comment]
I've tried to do this, but it doesn't works fine. I don't see the icon "BattlEye" on my Ark server

**Comment by EstSoft87** [comment]
I've worked out my problem. Now we have to add this string: arkflag_UseBattlEye="" to arkmanager.cfg

**Comment by klightspeed** [comment]
In that case, the command-line option to the server was not `-BattlEye`, but instead `-UseBattlEye`.
