### ISSUE TITLE
abort update --warn process

### ISSUE THREAD

**Issue by kiluMD** [FezVrasta/ark-server-tools#391]
Hello I wish a command :) 

I want to abort the "update --warn" process,
Or have this arkmanager?

greetz

**Comment by klightspeed** [comment]
To abort an `update --warn`, terminate the arkmanager process running the `update --warn` by e.g. pressing Ctrl+C.

**Comment by klightspeed** [comment]
1.6-dev (4109717) adds a `cancelshutdown` command to do this.

**Comment by klightspeed** [comment]
Added in v1.6
