### ISSUE TITLE
Backup Game.ini as well

### ISSUE THREAD

**Issue by Durros** [FezVrasta/ark-server-tools#393]
Hey, our server just installed your script for our private server. We are using a custom Game.ini and I noticed that when we do a backup it saved everything except the Game.ini. Any chance you could add this to the list of things to backup?

**Comment by jedcooper** [comment]
+1

**Comment by axi92** [comment]
Maybe check all the inis for "not empty" and backup just those who needs a backup

**Comment by klightspeed** [comment]
1.5-dev includes backing up Game.ini - see edaea14
