### ISSUE TITLE
Problem with mod and Configuration server maybe

### ISSUE THREAD

**Issue by Raztoux** [FezVrasta/ark-server-tools#394]
Hello,

My team working on implementing mod with news objects.
Unfortunately, when we install on the server and we click on an engram , the server crash and reboot .

The mod is functional on a server Nitrado example and solo part.
The impression is that the Primal Game Data mod is not greater than the server . Should succeed in overloading the server with the PGM mod.
Does the server needs additional configuration?

If someone in a track, let me know! : D

Pending read you

Raztoux

**Comment by StevenB83** [comment]
I have nothing to do with theese tools, but it may help if you include which mod and how you are trying to install and load it.

Is it only one mod or several? You have to choose the correct load order in the `/etc/arkmanager/arkmanager.cfg` or the nameofinstance.cfg file in `/etc/arkmanager/instances` folder.
To install a mod you do `arkmanager installmod modid` or if not main instance `arkmanager installmod @nameofinstance modid` and add it under `ark_GameModIds="modid,modid"` in the cfg file for your server instance. replace modid with the modid numbers for your mod(s)

Hope this helps.

Steven.

**Comment by Raztoux** [comment]
Hi Steven,

Thanks for your response.
I have 1 mod and 1 map (valhalla). The mod does not work with or without the map.
In the /etc/arkmanager/ i haven't the folder "instances". Is this normal?

My arkmanager.cfg : 

```
# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Valhalla"                                               # server map (default TheIsland)
#Ancienne map ="TheIsland"
#serverMapModId="504122600"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#Ancienne map: "469987622"
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort="XXXX"                                                # RCON Port
ark_SessionName="[FR] Reyha - Ark-RP.fr"                                  # if your session name needs special characters please use the .ini instead
ark_Port="7777"                                                     # ARK server port (default 7778)
ark_QueryPort="27015"                                               # ARK query port (default 27015)
ark_ServerPassword="XXXXX"                                        # ARK server password, empty: no password required to login
ark_ServerAdminPassword="XXXXXX"                                     # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="50"
ark_GameModIds="623289965"                                          # Uncomment to specify additional mods by Mod Id separated by commas
#Mod Aless : 619012911 - 620214576 - 621846940 - 623289965
#ark_GameModIds="487516323,487516324,487516325"                     # Save Command specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF" 
```
And in my case mods I have it (I even tried to transfer my files from my steam directly because I have heard of problems with steamCMD for ARK) :

http://i68.servimg.com/u/f68/11/72/42/70/captur10.png

Are there any log that I can use ? I can not find anything significant : /

Pending read you

Raztoux

**Comment by StevenB83** [comment]
Hi,

If you are running arkmanager 1.4 (which you should if you don't need any features in 1.5-dev) it is normal that you do not have the instances folder. I forgot that when I typed my post.

I haven't yet had an issue with SteamCMD for linux other than an occasional failure to download (which arkmanager 1.5-dev has lately worked aroud by retrying download).

```
steam@ARK:~$ arkmanager installmod 623289965
Running command 'installmod' for instance 'vanilla'
Downloading mod 623289965 ... Mod 623289965 downloaded
Copying files to /home/steam/ARK/ShooterGame/Content/Mods/623289965
Mod 623289965 installed
```

added `ark_GameModIds="623289965"` to my `instances/vanilla.cfg` my instance is called this on my test server. if you run 1.4 just put it in arkmanager.cfg like you already did.

then I just started the server with `arkmanager start`

[Image of mod working](https://lh3.googleusercontent.com/-ploUVE_RgYg/VsFb67wBEtI/AAAAAAAAEvM/gZpAObMrSuI/s0/ShooterGame_2016-02-15_06-01-52.png)

Everything works fine for me.

One thing I do notice in your config file is that you put 7777 as port number, do you wish to run the server on the standard port? if so the correct is 7778 :)

Regards Steven.

**Comment by Raztoux** [comment]
Hi Steven,

I'm sorry for my forgot, but the mod 623289965 work on my server too.
But the mod 621846940 didn't work.

Ok for the version of my arkmanager.
I will change the port of my server tonight.

Thanks a lot Steven !

Best Regards

**Comment by StevenB83** [comment]
Well I don't find that very strange as it doesn't exist according to my findings. https://steamcommunity.com/sharedfiles/filedetails/?id=621846940

Steven

**Comment by Raztoux** [comment]
Ah, this is my modder who had privately ...

Here is the link to download the github if needed ( I ask him to board the public ) : https://github.com/Raztoux/Reyha/commit/b7164a851fe1cb90e54a3e14d1c0eace3cd6d773

Raztoux

**Comment by StevenB83** [comment]
That explains why I did not find it ;)
Will do some more testing after work for you.

Steven

**Comment by Raztoux** [comment]
Ok thanks you very much Steven.
The mod is now available

Raztoux

**Comment by StevenB83** [comment]
Ok, I did test with the one from github, but it still seemed to download ingame when connecting to the server and it worked for me.

Still at work so only tested via remoting into my PC so I do not know if the items work, but you can see in [screenshot](https://lh3.googleusercontent.com/-bA3A2uF4Rto/VsHSuDkaWMI/AAAAAAAAEvc/YC6-0FsUSxk/s0/ShooterGame_2016-02-15_14-28-46.png) that it loaded.
All I did was copy the folder and the .mod file into Mods on both server and client, added the modid to arkmanager.cfg (same as you correctly did).

Steven

**Comment by Raztoux** [comment]
Hi Steven,

The server work with this mod, but when we click on an engram , the server crash and reboot.
But not all engrams. Exemple the gunsmith (or "Armurerier" in french), my server crash.

If you can try to click on all new engrams created and see what happens it will let me know if this is the mod / server / both have a problem.
You are a Linux Server isn't it?

Raztoux

**Comment by StevenB83** [comment]
Hi,

Yes server is running on Ubuntu Server 15.10. Crashed when trying to learn Electrician thing.
I don't know what it could be, but I can do some more testing when I get home.

Steven

**Comment by Raztoux** [comment]
Hi,

Ok thanks a lot !
I await your return

Best Regards

Raztoux

**Comment by StevenB83** [comment]
I did test without arkmanager and it still crashes, you could try to run a GDB Backtrace on the ARK server process to try and figure out why the mod is crashing, then modmaker might be able to figure out a way around it. Is the Nitrado server a windows server or maybe a different flavor of linux?
I haven't done enough GDB backtraces and no experience in ARK modding (yet) to be able to make any sense of the results, but maybe you are able to.

I have been able to figure out why our ARK server itself has crashed in the past with GDB and reported the bugs to Wildcard so they could fix it, so maybe, just maybe it can help you.

Best of luck!

Steven

**Comment by Raztoux** [comment]
Hi Steven,

Thanks a lot for your help.
I try with GDB and modmaker, I don't know this soft.

I think Nitrado runs on windows but I don't really know.
I check this source.

Thanks again !

Raztoux

**Comment by klightspeed** [comment]
Does this work when using the `-automanagemods` option to the ARK server?

**Comment by klightspeed** [comment]
Closing old issues
