### ISSUE TITLE
1.5 release?

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#396]
@klightspeed do you think we could release the 1.5 version?

**Comment by axi92** [comment]
#393 would be nice in 1.5 =)))

**Comment by klightspeed** [comment]
Remaining issues with milestone of v1.5 are the node.js web api (#335) and possible `uninstallmod` and `reinstallmod` commands (#242).

I don't think we have any other blockers.

**Comment by FezVrasta** [comment]
I think the web api can be moved to backlog till we find someone willing to maintain it.
