### ISSUE TITLE
@ALL

### ISSUE THREAD

**Issue by tenten36** [FezVrasta/ark-server-tools#400]
Hi,
after the upgrade to 1.5 I found a small problem. --help says `@all` for instances, but it's actually case sensitive: `@ALL`.

Also, it's not clear what to use for "Do you wish to run this command for all instances?".  Nothing seems to work (`y/Y/yes/n/N/no`). It just stops working.

**Comment by FezVrasta** [comment]
ping @klightspeed

**Comment by klightspeed** [comment]
> after the upgrade to 1.5 I found a small problem. --help says `@all` for instances, but it's actually case sensitive: `@ALL`.

@tenten36 so the following command doesn't work:
```
arkmanager status @all
```

For me:
```
$ arkmanager status @all
Running command 'status' for instance 'main'
 Server running:   No
 Server listening:   No
 Server version:   978345
Running command 'status' for instance 'test'
 Server running:   No
 Server listening:   No
 Server version:   978345
```

Refer https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L1742

> Also, it's not clear what to use for "Do you wish to run this command for all instances?". Nothing seems to work (y/Y/yes/n/N/no). It just stops working.

Pressing `y` or `Y` should confirm.  Pressing any other key should cancel.

For me:
```
$ arkmanager status
No instances supplied for command status
Do you wish to run this command for all instances?y
Running command 'status' for instance 'main'
 Server running:   No
 Server listening:   No
 Server version:   978345
Running command 'status' for instance 'test'
 Server running:   No
 Server listening:   No
 Server version:   978345
```

**Comment by tenten36** [comment]
Thanks for the reply.
arkmanager status @all
`steam@cloudsrv1:~$ arkmanager status @all`
 `steam@cloudsrv1:~$`

arkmanager status @ALL works
`steam@cloudsrv1:~$ arkmanager status @ALL`
`Running command 'status' for instance 'ALL'`
 `Server running:   Yes` 
 `Server listening:  Yes`
 `Server Name:`
 `Players:`
 `Server online:   Yes`
 `ARKServers link:`
 `Server version:   979476`


arkmanager list-instances doesn't work as well.
`steam@cloudsrv1:~$ arkmanager list-instances`
`The following instances are available:`
`steam@cloudsrv1:~$`

Maybe I should make a fresh install of arkmanager?I only upgraded the tool since the earliest versions.

**Comment by klightspeed** [comment]
Does `/etc/arkmanager/instances/main.cfg` exist?

It looks like your settings didn't transfer from `/etc/arkmanager/arkmanager.cfg` to `/etc/arkmanager/instances/main.cfg` during the upgrade.

**Comment by tenten36** [comment]
Jup, that was the problem. Copied the file manually and it works as intended.

Thanks!
