### ISSUE TITLE
Server autostart?

### ISSUE THREAD

**Issue by tenten36** [FezVrasta/ark-server-tools#401]
Did something change for the autostart option? Server doesn't seem to autostart after reboot anymore, I have to start it manually? Ubuntu 14.02. LTS

**Comment by klightspeed** [comment]
What does `arkmanager list-instances` get you?

If you upgraded, what does `systemctl start arkmanager@main` get you?

**Comment by tenten36** [comment]
Closed, problem was the main.cfg
