### ISSUE TITLE
Upgrade wants su rights, but I installed as user

### ISSUE THREAD

**Issue by jedcooper** [FezVrasta/ark-server-tools#402]
How do I upgrade correctly with my steam user named "steam"? "arkmanager upgrade-tools" wants su rights.
I installed the ark stuff locally in /home/steam of regarding user "steam". 
Like that: 
$ curl -sL http://git.io/vtf5N | bash -s -- --me

**Comment by klightspeed** [comment]
Check whether `steamcmd_user` in `~/.arkmanager.cfg` is defined to `--me`.

**Comment by klightspeed** [comment]
No response in 5 months - closing issue.
