### ISSUE TITLE
Cannot install Ark-server-tools again

### ISSUE THREAD

**Issue by wafebreaker** [FezVrasta/ark-server-tools#404]
Hey guys, my english is not that good, so please bear in mind.

I installed ark-server-tools exactly as it say in readme, and it worked, more or less. But i then i got an error which is not important but i deinstalled it, with that command: arkmanager uninstall-tools

After that i tried to reinstall it again, but now the installation does not create new cfg in /etc/arkmanager,
so everytime i want to start it, or install it with arkmanager install, it tells me that:

root@Server-PC:/etc# arkmanager install
/usr/local/bin/arkmanager: Zeile 81: /etc/arkmanager/arkmanager.cfg: Datei oder Verzeichnis nicht gefunden
/usr/local/bin/arkmanager: Zeile 81: /etc/arkmanager/arkmanager.cfg: Datei oder Verzeichnis nicht gefunden
/usr/local/bin/arkmanager: Zeile 81: /etc/arkmanager/arkmanager.cfg: Datei oder Verzeichnis nicht gefunden
/usr/local/bin/arkmanager: Zeile 81: /etc/arkmanager/arkmanager.cfg: Datei oder Verzeichnis nicht gefunden
/usr/local/bin/arkmanager: Zeile 81: /etc/arkmanager/arkmanager.cfg: Datei oder Verzeichnis nicht gefunden

So what can i do for now ?

**Comment by klightspeed** [comment]
Did you re-install it using the install script?

**Comment by wafebreaker** [comment]
i used uninstall.sh, deleted every directory i found about arkmanager, like dot files in /etc/arkmanager or in home directory of my steam user.

When i try to install it, via netinstall.sh or curl on my user steam, and try to use a command like arkmanager, it tells me that: command not found

**Comment by wafebreaker** [comment]
First installation everything worked fine. It created a cfg file in /etc/arkmanager, etc, but after i used arkmanager uninstall-tools and deleted every folder, it does not create a new arkmanager.cfg file

**Comment by klightspeed** [comment]
Please move `/etc/arkmanager/arkmanager.cfg.cfg` to `/etc/arkmanager/arkmanager.cfg`

**Comment by wafebreaker** [comment]
but its not that cfg i had at first installation, there is so much missing. And i already done that, the next problem is, that when i use arkmanager install, it asked me which instance i want to use 'install'.

Why is it me asking that now and not at first time?

Thx for helping btw

**Comment by klightspeed** [comment]
Please copy `/etc/arkmanager/instances/instance.cfg.example` to `/etc/arkmanager/instances/main.cfg`, and edit it with the server options.

If you don't want to run multiple instances, then uncomment `defaultinstance="main"` in /etc/arkmanager/arkmanager.cfg

@FezVrasta should we default to having a `main` instance and have `defaultInstance="main"` uncommented in `arkmanager.cfg`?

**Comment by wafebreaker** [comment]
Alright, and my last question is, do i have to download the ark server with ark server tools, or can i use my installed server?

Thx a lot

**Comment by klightspeed** [comment]
You should be able to use an existing server - set `arkserverroot` in your `main.cfg` to the install directory of your ARK server.

**Comment by wafebreaker** [comment]
Alright, i added the line _defaultinstance="main" to config_ and used arkmanager install again,
now i have this screen for a while: 

root@Server-PC:/etc/arkmanager/instances# arkmanager install
Running command 'install' for instance 'main'
 ... \

**Comment by wafebreaker** [comment]
And how do i get the new config? Im really confused right now and im sorry that i steal your time because i do mistakes, but i dont know what to do. As i said, first installation everything worked fine, and now every file is not the same as earlier

**Comment by klightspeed** [comment]
Did you point `arkserverroot` to your ARK install?

Is your ARK install up-to-date?

`arkmanager install` will perform a full re-validation of the server install, and update it if necessary.

> And how do i get the new config?

Since there was a bug in the installer script, the new config will be in `/etc/arkmanager/.arkmanager.cfg.cfg`

**Comment by wafebreaker** [comment]
Okay, this cfg is definitly better, but btw,_ defaultInstance="main"_ is still missing there.

I renamed instances.cfg.example to main.cfg and pointed to my ark installed directory, and changed everything in arkmanager.cfg and added the line with defaultinstance, and i used arkmanager install again, and now there are again these lines:

root@Server-PC:/etc/arkmanager/instances# arkmanager install
Running command 'install' for instance 'main'
... \


Could you tell me why the installation now is so much harder than the installation at the beginning? I want that back, because that was way easier..

**Comment by dragnod0** [comment]
[GER] 
Laut deinem ersten Post ist deine Muttersprache deutsch. Daher antworte ich dir auch mal auf deutsch ;) 
Der Entwickler hat die Möglichkeit eingeführt mehl als einen ark Server auf einem Rechner parralel laufen zu lassen. Das macht die Konfiguration leider etwas komplizierter als vorher. Aber nicht sehr viel. Wenn du hilfe brauchst kannst du dich auch in den Portalen arkforum.de oder arksurvivalevolved.de per PN an mich (dragnod0) wenden. Ich denke ich kann dir da twas bei helfen.

[ENG-mostly Goggle Translate]
According to your first post, your native language is German. Therefore I answer you in german.
The developer has the option introduced more than one ark Server to run parralel on one computer. This makes the configuration unfortunately more complicated than before. But not very much. If you need help you can easily also in the portals arkforum.de or arksurvivalevolved.de contact me via PM (dragnod0). I think I can help you.

**Comment by klightspeed** [comment]
Closing old issues.
