### ISSUE TITLE
Information about game.ini

### ISSUE THREAD

**Issue by terryb8s** [FezVrasta/ark-server-tools#408]
First off thank you for making this utility, makes life much easier, much appreciated!

I cannot find any infomation on adding settings for [Game.ini](http://ark.gamepedia.com/Server_Configuration#Game.ini) to arkmanager.cfg, is there a specific prefix e.g. arkadv_ or something?

Can I please request either some documentation or this to be added as a feature?

Thank you

**Comment by klightspeed** [comment]
Arkmanager does not directly modify the game ini files.  It provides command-line arguments to the ARK server, many of which that server then stores in GameUserSettings.ini

**Comment by terryb8s** [comment]
Ok great, it might be worth adding a comment about this to the readme.md, i guess it would be nice to only have to modify one file (arkmanager.cfg) to change all server settings but I guess that makes sense as to why this would not be a priority, why go recreate the wheel when its already been made.

Will just modify my Game.ini file as per normal.

Thank you for the clarification.

**Comment by klightspeed** [comment]
Closing old issues.

**Comment by aaronrunkle** [comment]
Please do add the note about the game.ini settings to the readme.md file.  I wasn't sure if this tool could also modify the game.ini until I found this - it does everything else.
