### ISSUE TITLE
broatcast dosn´t work

### ISSUE THREAD

**Issue by dragnod0** [FezVrasta/ark-server-tools#409]
If i type the command `arkmanager broadcast "Hi, admin here"` there come no Messages ingame. 

No error message, only `Running command 'broadcast' for instance 'main'`

**Comment by klightspeed** [comment]
Is RCON enabled?

**Comment by dragnod0** [comment]
yes RCON is enabled. i haven´t change the port.

**Comment by klightspeed** [comment]
What does the following command get you:
```
arkmanager rconcmd "broadcast Hi, admin here"
```

**Comment by dragnod0** [comment]
ok, now it works. After setting up the Admin PW inside the arkmanager.cfg (before set inside the ini files) and restart the server.

THX for your help :)

**Comment by axi92** [comment]
Admin PW must be in the arkmanager.cfg other wise arkmanager could not know the pw.
@klightspeed is there a way to check the password? To print "Wrong password, check arkmanager.cfg" or something like that?

**Comment by klightspeed** [comment]
arkmanager looks first for the `ark_ServerAdminPassword` setting from its config, then for the `ServerAdminPassword` setting in the `[ServerSettings]` section of `ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini`.  Refer https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L233

If it can't get the password from either source, it will print `ServerAdminPassword is empty - unable to execute RCON command`.  Refer https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L280

If the password contains non-ascii characters, it will print `ServerAdminPassword contains invalid characters`.  Refer https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L283

If the server rejects the password, then arkmanager will print `Authentication failed`.  Refer https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L309
