### ISSUE TITLE
Cannot find .cfg file (Instances)

### ISSUE THREAD

**Issue by chopsuey40** [FezVrasta/ark-server-tools#414]
I updated to the new version of Arkmanager, and it gives me this error:

arkmanager install
Running command 'install' for instance 'main'
Error: config file /home/steam/.config/arkmanager/instances/main.cfg does not exist

The file does exist in that directory and it's readable.  But for some reason, Arkmanager cannot find it.  Any help would really be appreciated.  Thanks.

**Comment by dragnod0** [comment]
same for me 
`Error: config file /etc/arkmanager/instances/main.cfg does not exist`
main.cfg is existing ;)

Version is
`Version: 1.5
Channel: master
Commit: 5e8b53b
`

Thx For help

**Comment by 5pHiNxX** [comment]
The solution of @klightspeed is working... just tried it by manually updating the arkmanager file.

**Comment by dragnod0** [comment]
yes It Works, thx. :)

**Comment by cronner** [comment]
I can't get it to work

defaultinstance="main" is in arkmanager.cfg

Error: config file /etc/arkmanager/instances/main.cfg does not exist

main.cfg is there with arkserverroot="/home/steam/ARK" :/

**Comment by pugmaster15** [comment]
How do you apply the patch? Sorry, I'm fairly new to Ubuntu and GitHub...

**Comment by dragnod0** [comment]
open the arkmanager executable
`sudo nano /usr/local/bin/arkmanager`


press STRG+w
Enter or past this into the search line:
`if [ -a "$configfile" ]; then`

change -a  to -z


the line must now look so:
`if [ -z "$configfile" ]; then`

exit (STRG+x) and save the file.
Thats all

**Comment by pugmaster15** [comment]
Thanks dragnod0 for the quick and detailed response! This got my much further now.
However, I don't believe my system has enough disk space to actually install the steamcmd ARK files...
I ran the bash script located here (http://www.kpheasey.com/2015/07/03/ark-survival-evolved-private-dedicated-server-setup-beginners-guide/#comments) but I don't see the directory /home/steam/ark; all I see is /home/steam/steamcmd.
I ran the command "./steamcmd.sh +login anonymous +force_install_dir /home/steam/ark +app_update 376030 validate +quit" to try to install the tools, but it failed with the following errors:

> Loading Steam API...applicationmanager.cpp (3091) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
> applicationmanager.cpp (3091) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
> applicationmanager.cpp (3242) : Assertion Failed: m_vecInstallBaseFolders.Count() > 0
> Created shared memory when not owner SteamController_Shared_mem
> OK.
> 
> Connecting anonymously to Steam Public...Logged in OK
> Waiting for license info...OK
> applicationmanager.cpp (3242) : Assertion Failed: m_vecInstallBaseFolders.Count() > 0
>  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
>  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
>  Update state (0x5) validating, progress: 92.35 (18030962965 / 19524444079)
> Error! App '376030' state is 0x202 after update job.
> 
Any I have approximately 10GB of free space on this digital ocean droplet, but isn't the install close to 20GB? 

Thanks again for all of the help!

**Comment by dragnod0** [comment]
For the ARK server you need ~18 GB free disk space (say steam) 

you can simplie install the server with `arkmanager install`

**Comment by Pictureclass** [comment]
thx to @dragnod0 and @klightspeed. Working now again
