### ISSUE TITLE
Cannot Execute Binary File

### ISSUE THREAD

**Issue by jrohnerx** [FezVrasta/ark-server-tools#416]
Hello,

When running the command "arkserver start" I receive the following error in the arkserver.log.

> 15:13:19: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=10\?Port=7776\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?Se$
> 15:13:19: Server PID: 3104
> /usr/local/bin/arkmanager: line 667: /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer: cannot execute binary file
> 15:13:24: Bad PID ''; expected '3104'
> 15:13:24: exited with status 0
> 

Any tips on what to do?

**Comment by klightspeed** [comment]
Are you running a 32-bit or 64-bit server?  ARK server requires a 64-bit OS.

If neither `/lib/ld-linux-x86-64.so.2` nor `/lib64/ld-linux-x86-64.so.2` exist, then you're most likely running a 32-bit OS.

**Comment by jrohnerx** [comment]
Ahh that was the problem. Swapped it over to a 64bit OS and now it's working fine. Thanks for your great feedback!

**Comment by klightspeed** [comment]
Issue resolved
