### ISSUE TITLE
Creation of <ModID>.mod

### ISSUE THREAD

**Issue by McBane87** [FezVrasta/ark-server-tools#419]
Hi,

Is your Script somewhere creating the "\<ModID\>.mod" File?

If not, maybe the changes to your "doExtractMod()" Function can help.
Just for clarification: I don't have a clue of perl and the modification was nothing more then "Trial and Error" until it worked.

    steamurl="http://steamcommunity.com/sharedfiles/filedetails/?id="
    ModName=$(wget -qO- $steamurl$modid 2>/dev/null | grep "workshopItemTitle" | sed 's/.*workshopItemTitle">//g;s/<.*$//g' 2>/dev/null)
    if [[ $ModName == "" ]]; then
        ModName="ModName"
    fi
    ModNameLength=$((${#ModName}+1))
    ModPath="../../../ShooterGame/Content/Mods/$modid"
    ModPathLength=$((${#ModPath}+1))
    perl -e '
      my $modid = $ARGV[0];
      my $modname = $ARGV[1];
      my $modnamelen = $ARGV[2];
      my $modpath = $ARGV[3];
      my $modpathlen = $ARGV[4];
      my $data;
      { local $/; $data = <STDIN>; }
      my $mapnamelen = unpack("@0 L<", $data);
      my $mapname = substr($data, 4, $mapnamelen - 1);
      $mapnamelen += 4;
      my $mapfilelen = unpack("@" . ($mapnamelen + 4) . " L<", $data);
      my $mapfile = substr($data, $mapnamelen + 8, $mapfilelen);
      print pack("L< L< L< Z$modnamelen Z2 C C Z$modpathlen L< L<", $modid, 0, $modnamelen, "$modname", ",", 0, 0, "$modpath", 1, $mapfilelen);
      print $mapfile;
      print "\x33\xFF\x22\xFF\x02\x00\x00\x00\x01";
    ' $modid "$ModName" $ModNameLength "$ModPath" $ModPathLength <"$moddestdir/mod.info" >"$moddestdir/.mod"`

After that you need to Copy the "$moddestdir/.mod" to "\<ModID\>.mod" and place it outside the MOD-Folder. So something like that:
`cp $moddestdir/.mod $moddestdir/../$modid.mod`

This way I was able to create an exact Copy of the \<ModID\>.mod File which was normally created by my Windows-Client.

**Comment by klightspeed** [comment]
The creation of `$modid/.mod` was based on what an earlier version of what ARK Server Manager did, and has been working.

I have been working on essentially the same thing implemented slightly differently: c4f9171

**Comment by McBane87** [comment]
Oh OK. So you just added it already. 
Just thought I need to share my finding. Maybe it could have helped :D 

However I can't find it in the master-branch it is only displayed when clicking on the commit-link you posted above.

**Comment by klightspeed** [comment]
I haven't actually pulled it into master (or 1.6-dev when it gets created) yet.

**Comment by klightspeed** [comment]
This is in 1.6-dev

**Comment by klightspeed** [comment]
Added in v1.6
