### ISSUE TITLE
Error with Server restart....pls help

### ISSUE THREAD

**Issue by BMDao** [FezVrasta/ark-server-tools#420]
/usr/local/bin/arkmanager: Zeile 592: 23162 Speicherzugriffsfehler  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
11:21:13: Bad PID ''; expected '23162'
11:21:13: exited with status 0
11:21:13: restarting server
11:21:13: Running /home/ark/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=100\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=#####\?ServerPassword\?SessionName=.....
11:21:13: Server PID: 15562
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
11:22:32: server is up

**Comment by klightspeed** [comment]
OK - so the server exited due to a segmentation fault, and the script automatically restarted the server, after which it successfully came up.

What happened when the server crashed?

**Comment by BMDao** [comment]
The server starts regularly reassessed with this error. 1-2 times a day
The server looks every 30 minutes for updates.

The script automatically restarted the server.

**Comment by klightspeed** [comment]
What mods are you using?  Is anything special occurring just before the server restarts?

**Comment by BMDao** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=510590313
http://steamcommunity.com/sharedfiles/filedetails/?id=503245171
http://steamcommunity.com/sharedfiles/filedetails/?id=534838287

No nothing happens special

**Comment by klightspeed** [comment]
Mod 503245171 was last updated 6 months ago, says it is discontinued, and points to http://steamcommunity.com/sharedfiles/filedetails/?id=533175507 as a replacement, which itself was last updated 4 months ago.

**Comment by BMDao** [comment]
why should it but be because when it comes only so irregular?

I'm going to mod uninstall and watch it once, thank you

**Comment by klightspeed** [comment]
Closing old issues.
