### ISSUE TITLE
arkmanager rconcmd does not work

### ISSUE THREAD

**Issue by kdulep** [FezVrasta/ark-server-tools#422]
still not working after close issue

**Comment by klightspeed** [comment]
What is the output of `arkmanager --version`

**Comment by kdulep** [comment]
Version: 1.5
Channel: master
but it wasn't working from git also

**Comment by kdulep** [comment]
before that update it was working

**Comment by klightspeed** [comment]
The lack of a Commit: line means that you did not install it using the netinstall script.

What is the output of `grep -C3 'Server received' /usr/local/bin/arkmanager`

It should be:
```
    auth($socket, $password);
    sendpkt($socket, 2, 2, $command);
    my ($resid, $restype, $rcvbody) = recvpkt($socket);
    if ($rcvbody eq "Server received, But no response!!") {
      print "Command processed\n";
    } else {
      print $rcvbody, "\n";
```

**Comment by kdulep** [comment]
auth($socket, $password);
    sendpkt($socket, 2, 2, $command);
    my ($resid, $restype, $rcvbody) = recvpkt($socket);
    if ($rcvbody eq "Server received, But no response!!") {
      print "Command processed\n";
    } else {
      print $rcvbody, "\n";

**Comment by kdulep** [comment]
strange it stopped working after missing main instance bug

**Comment by kdulep** [comment]
ARKON is working

**Comment by klightspeed** [comment]
What is the output of the non-working `arkmanager rconcmd listplayers`

**Comment by kdulep** [comment]
Running command 'rconcmd' for instance 'main'
Command processed

**Comment by klightspeed** [comment]
Try prepending lines 323-325 and 327 of /usr/local/bin/arkmanager with `#`

This should cause lines 320-330 to look like:
```
    auth($socket, $password);
    sendpkt($socket, 2, 2, $command);
    my ($resid, $restype, $rcvbody) = recvpkt($socket);
#    if ($rcvbody eq "Server received, But no response!!") {
#      print "Command processed\n";
#    } else {
      print $rcvbody, "\n";
#    }
    ' "$(getRconPort)" "${ark_MultiHome:-127.0.0.1}" "$adminpass" "$1"
}

```

Then try running `arkmanager rconcmd listplayers` again.

If you still get the same error, make sure you don't have another copy of arkmanager somewhere in your `$PATH` - i.e. `type arkmanager` should return `/usr/local/bin/arkmanager`

**Comment by kdulep** [comment]
i had several arkmanager in /home and usr/local ... for some reason
i removed tools , reinstalleed as root and now all good
