### ISSUE TITLE
What is the best way to have two instances running with arktools 1.5 ?

### ISSUE THREAD

**Issue by Evilcious** [FezVrasta/ark-server-tools#423]
I  have to say you did a wonderful job with this version guys !

My only concern is that I don't really get how to use the multi instance options... To have two ark server instances running on the same linux host, what do I have to do ?
- Have another copy of which directories ?
- How to configure properly my main instance ? My second instance ?

Maybe you have a guide written somewhere to help me :D

**Comment by klightspeed** [comment]
Configure the common options in `/etc/arkmanager/arkmanager.cfg`

Configure the settings for your first instance in `/etc/arkmanager/instances/<name1>.cfg` where `<name1>` is a single-word name for the instance.

Configure the settings for your second instance in `/etc/arkmanager/instances/<name2>.cfg` where `<name2>` is a single-word name for the instance.

Remove `/etc/arkmanager/instances/main.cfg` if you don't want it.

The `arkserverroot` needs to be in a separate directory for each instance.  The instances can share the `steamcmdroot` and `arkStagingDir` directories.

If the `arkserverroot` for both instances is on the same filesystem, and you set a shared `arkStagingDir` on that same filesystem, then each additional instance will only take the disk space for its mods, config and saved data.

**Comment by Evilcious** [comment]
Will try. Thank you. I'll update this issue if needed ;)
