### ISSUE TITLE
how can/must i add "OverridePlayerLevelEngramPoints=x" inside the main.cfg

### ISSUE THREAD

**Issue by dragnod0** [FezVrasta/ark-server-tools#424]
Hi,
the problem is, the Game.ini file will be always overwritten on Server start and the 
`OverridePlayerLevelEngramPoints=x` option can´t be placed Inside the DefaultGame.ini.

how must i add this inside the main.cfg file?
As Flag: 
`arkflag_OverridePlayerLevelEngramPoints=x
arkflag_OverridePlayerLevelEngramPoints=x
arkflag_OverridePlayerLevelEngramPoints=x
arkflag_OverridePlayerLevelEngramPoints=x
[...]` (every entry in a new line)

or as server option?
`arkopt_OverridePlayerLevelEngramPoints=x
arkopt_OverridePlayerLevelEngramPoints=x
arkopt_OverridePlayerLevelEngramPoints=x
arkopt_OverridePlayerLevelEngramPoints=x
[...]` (every entry in a new line)

Thanks for the help

**Comment by axi92** [comment]
That has nothing todo with the arkmanager

You put it into `ShooterGame\Saved\Config\WindowsServer\Game.ini` under `[/script/shootergame.shootergamemode]`

**Comment by klightspeed** [comment]
If the ARK server is resetting your Game.ini file, that means that it is detecting that it is invalid - e.g. an option not in a section, or a non-ascii character.
