### ISSUE TITLE
Suggestion: Auto update (cron?)

### ISSUE THREAD

**Issue by omega117** [FezVrasta/ark-server-tools#425]
Hey everyone,

I am new to github and have no clue how it's advanced functions work.
But I see more than one topics here that will be goals for Arkmanager V1.6
I also have a suggestion to improve the overall functionality of Arkmanager.

Is it possible to include an autoupdate function on basis of cron jobs simplified in a section in the ~/.arkmanager.cfg.

**Example: 
Auto_update=true**
**Auto_update_timer=1D12H15M** (this will let the autoupdate check for updates every 1day, at 12:15 in the afternoon (prefer 24H clock display instead of AM/PM)
**Auto_update_option="saveworld, warn, etc"** (options that will be issued when the autoupdate detects an update is available. for example : saveworld, stop, update, update-mods, start.)

any feedback would be awesome.

Greetings from a daily user of arkmanager :)

**Comment by axi92** [comment]
I personaly wont use that, a simple cronjob is much easier and just 1 line

**Comment by Technoblazed** [comment]
15 2 * * * /usr/local/bin/arkmanager update --warn

As far as I'm aware, this is all you need. Just enable saving and backups in your arkmanager. This is far easier than what you're talking about.

**Comment by omega117** [comment]
Yes but so is manually running the Shootergameserver as a service... 
And configuring everything in the command line (just a txt document that you run containing all the necessary options and flags + the config in game.ini/gameusersettings.ini)
This is how I used to run the server. There were no problems with that.
Just 1 command to start the server and 1 command to check for updates, and when found it updates the server.
The whole reason that arkmanager exists is to give admins advanced configuration options as easy as it gets and to avoid using other commands than "arkmanager [command]" right?
So why not implement a layman's option for autoupdates?
As there are a lot of features implemented that can simply also be replaced by a 1 line command...

**Comment by klightspeed** [comment]
So something like `arkmanager install-cronjob --hourly --minute=30 update @instance --saveworld --backup --warn --update-mods`?

```
doInstallCronJob(){
  hour='*'
  minute='*'
  extraopts="${arkCronExtraOpts}"
  command="$1"
  shift
  
  for opt in "$@"; do
    case "$opt" in
      --hourly)
        hour='*'
      ;;
      --hour=*)
        hour="${opt#--hour=}"
      ;;
      --minute=*)
        minute="${opt#--minute=}"
      ;;
      --minutes=*)
        minute="[*]/${opt#--minutes=}"
      ;;
      --opt=*)
        extraopts="${extraopts} $(printf "%q" "${opt}")"
      ;;
      *)
        extraopts="${extraopts} $(printf "%q" "${opt}")"
      ;;
    esac
  done

  VISUAL= EDITOR=ed crontab -e <<EOE
g/ [*] [*] [*] arkmanager ${command} @${instance} /d
$r !echo "${minute} ${hour} * * * arkmanager ${command} @${instance} ${extraopts} >/dev/null 2>&1"
!sleep 1
wq
EOE
}
```

**Comment by omega117** [comment]
Yes that would also be a way :)
Maybe interactive or show an example since it is a long command.

**Comment by klightspeed** [comment]
Does 1.6-dev get this for you?

**Comment by omega117** [comment]
I have not tried 1.6 yet. But i will as soon as it updates on the normal branch :)

**Comment by klightspeed** [comment]
The installer should already create a `arkmanager.cfg.NEW

**Comment by omega117** [comment]
Yes it has the instance part. but there is no arkmanager.cfg.new.... i just installed the hotfix for 1.5 and it completely messed up the server... it no longer reads the users .arkmanager.cfg so i had to remove and replace the arkmanager.cfg in the /etc/ folder.... and now with the same settings people cant join anymore... any information on this?

**Comment by klightspeed** [comment]
Was this a user-install or a system-wide install?

If you had the instance options in `$HOME/.arkmanager.cfg`, then delete everything from `/etc/arkmanager/instances/main.cfg` and/or `$HOME/.config/arkmanager/instances/main.cfg`

**Comment by omega117** [comment]
it is a user install.
User: Admin. and i used to have everything in $home/.config/instances(instancefiles)
i still do after giving the configfile path in the /etc/arkmanager/arkmanager.cfg and absolute path.
but i dont get it why the /etc/arkmanager files overwrite the $home/.arkmanager and .config files.

Its hotfixed now but i am afraid to upgrade the tools if such changes happen again.

**Comment by klightspeed** [comment]
#535 should prevent the installer from overwriting the config files, and puts the onus on the user to check what changes are needed.

**Comment by omega117** [comment]
That would be great. but i never had any issue with the configs after the hotfix update. 
the problem was that arkmanager now has a priority issue.
arkmanager should use $home/.arkmanager.cfg > /etc/arkmanager/arkmanager.cfg
but it does the opposite.

**Comment by klightspeed** [comment]
`$HOME/.arkmanager.cfg` should override settings in `/etc/arkmanager/arkmanager.cfg`, as `$HOME/.arkmanager.cfg` is sourced after `/etc/arkmanager/arkmanager.cfg`.  Note that this means that if a setting is in `/etc/arkmanager/arkmanager.cfg` but not in `$HOME/.arkmanager.cfg`, then the setting from `/etc/arkmanager/arkmanager.cfg` will be used.

An explicitly specified config file should take precedence over `$HOME/.config/arkmanager/instances/$instance.cfg` which in turn should take precedence over `/etc/arkmanager/instances/$instance.cfg`.  Unlike the global options, only one instance config file is used, and any lower precedence config files are ignored.  Therefore, if `configfile_main` is set, then both `$HOME/.config/arkmanager/main.cfg` and `/etc/arkmanager/instances/main.cfg` will be ignored (unless of course `configfile_main` points to one of those files).

**Comment by omega117** [comment]
Yes that is how it should work and worked before.
But as of the last update (called a hotfix) for V1.5 (updated about 12 hours ago) if i have 2 identical config files in both the /etc/arkmanager and $home/ and i change something like the name or port in the /etc/arkmanager config it overwrites the config in $home/

**Comment by klightspeed** [comment]
If settings are specified in `/etc/arkmanager/instances/$instance.cfg` (where `$instance` defaults to `main`), and you have neither `$HOME/.arkmanager/instances/$instance.cfg` nor `configfile_$instance`, then the settings in `/etc/arkmanager/instances/$instance.cfg` will take precedence over `$HOME/.arkmanager.cfg`, as `$HOME/.arkmanager.cfg` is meant to contain global settings, which are overridden by instance settings.  This has been in place since multiple instances have been in ark server tools, and was not changed by any of the commits that were recently added to v1.5

**Comment by omega117** [comment]
ok, than can you explane the following:
i have the following files:
1- /etc/arkmanager/arkmanager.cfg (vanilla unedited)
2- /etc/arkmanager/instances/main.cfg (vanilla unedited)
3- $home/.arkmanager.cfg (custom settings)
4- $home/.config/arkmanager/instances/arkworld.cfg (custom instance)

before the update i got my world and settings from 3 and 4 and everything worked fine.
after updating arkservertools i got many errors when requesting "status" in arkmanager. (like warning ark savefolder is not writable)

so i looked at the problem and the problem is that now arkmanager ignores file 3 and 4. it automatically uses file 1 and 2 so i had to copy paste the content of file 3 in file 1.
inside the custom settings i specified that i want to have "/home/Admin/.config/arkmanager/instances/arkworld.cfg" as my config. so it uses file 4.

but i dont understand why arkmanager prefers to use file 1 over file 3?
is it possible this is a bug that sneaked in my system? or is it a bug in arkmanager?

**Comment by klightspeed** [comment]
What is the output of the following commands:

```
arkmanager --version
arkmanager list-instances
```

Are you using `arkmanager <command> @<instance>` or `arkmanager useconfig <instance> <command>`, and if not, do you have `defaultinstance` set to the instance you want as default.

Also, are you running `arkmanager` as root or as the user?  If you're running it as root, does the `steamcmd_user` setting match the user under which ARK is installed?

**Comment by omega117** [comment]
Hey Srry for the late response. its 6:30 AM here now XD
I figured out my error... everything is set up correctly and works perfect. but the new update added the default config line to the /etc/arkmanager/arkmanager.cfg.
i uncommented that out of the $home/.arkmanager.cfg because i dont use the default.
so it added the config located at /etc/arkmanager/instances to the instances used by arkmanager. 
the other 2 configs i run were still there .. i am sorry it took me so long to realise!

Again tnx a million for the tool!

**Comment by klightspeed** [comment]
Closing old requests
