### ISSUE TITLE
Ark server flags are added alphabetically, causing issues with -servergamelog

### ISSUE THREAD

**Issue by dorsey** [FezVrasta/ark-server-tools#426]
I've seen reports that -servergamelog doesn't work when it's the last flag on the command line, so I have flags in my config file set up as follows:
```
# anticheat
arkflag_battleye=""

# logs?
arkflag_servergamelog=""

# stuff
arkflag_server=""
arkflag_log=""
```

However it appears that they are sorted alphabetically, so this ends up being the command line for the server:
```
/srv/ark/ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland? ... config stuff ... ?listen -battleye -log -server -servergamelog
```

This puts -servergamelog at the end, which I'm trying to avoid.

Is there a way to ensure that flags are added to the command line in the order from the config file?

**Comment by dorsey** [comment]
OK, apparently I was wrong and flag order doesn't affect -servergamelog, or that was already fixed.  My logs are working.

I don't know if it's a major issue that flags aren't added in the order from the config file, so I'm leaving this issue open for now.  If that's not a major problem, feel free to close this.

**Comment by klightspeed** [comment]
1.6-dev (326bb55) should add the options in config file order.

**Comment by klightspeed** [comment]
This should now work properly with v1.6
