### ISSUE TITLE
Problem to see my online server

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#428]
Hi guys,

i'm hosting 2 new server on a new dedicated 

i've got that when i do a status :

Running command 'status' for instance 'pve'
 Server running:   Yes
 Server listening:   Yes
Server Name: [FR] ARK FRANCE - PvE x5 DinoOverhaul - (v236.2)
Players: 6 / 70
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/149.202.65.50:27019
 Server version:   994960

The problem is that the server is online and listening but it shows up rarely online on steam ...

How is that possible ?

Thanks

**Comment by klightspeed** [comment]
The steam server list can be slow to refresh, and may need refreshing a couple of times before the server will show up.

**Comment by arkfrancegaming** [comment]
Weird because when i try to add it to http://arkservers.net/server/149.202.65.50:27019

it says that it's not online

**Comment by klightspeed** [comment]
- Server running: This means that the executable for the server is currently in the process list.
- Server listening: This means that the game port is open, or the server is responding to the query port and is reporting a non-zero maximum player count.
- Server name: This is the server name that the server sends in its query port response
- Players: This is the number of players the server reports are connected in its query port response
- Server online: This means that the server has advertised itself in the Steam server list.
- ARKServers link: This is the public IP address and port the server has advertised itself on.

Check that the required ports are open in your firewall.

**Comment by Nitric81** [comment]
Wait the arkserver status command is suppose to show all of that? Mine only shows running, listening, and verison.

**Comment by arkfrancegaming** [comment]
it's 1.5 version

14:58:01: start
14:58:01: Running /home/PRI/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?ForceAllStructureLocking=true\?GameModIds=600705968\,558079412\?MaxPlayers=70\?Port=7779\?QueryPort=27018\?RCONEnabled=True\?RCONPort=27027\?ServerAdminPassword=****\?ServerPassword\?SessionName=\[FR\]\ ARK\ FRANCE\ -\ PvP\ x1\ Primitif\ +\?TotalConversionMod=504360469\?listen -BattlEye -log -servergamelog
14:58:01: Server PID: 12881
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager : line 651 :  3204 Abandon                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
14:58:02: Bad PID '12881'; expected '3204'
14:58:03: exited with status 0
15:00:28: server is up

Is it an error line 651 ?

**Comment by klightspeed** [comment]
@arkfrancegaming Is this during a restart?

That looks like a normal restart.  At the moment, `arkmanager stop` only checks the status of the ARK server, and not of the monitor process.  Therefore, the monitor process will exit up to 5 seconds after the ARK server exits, and therefore will often print its closing messages after the new server has started.

**Comment by arkfrancegaming** [comment]
yep it is :) ok fine then :)
