### ISSUE TITLE
Server not Listening

### ISSUE THREAD

**Issue by Nitric81** [FezVrasta/ark-server-tools#434]
When I run arkmanager status it shows 3 things. One is server running Yes next it shows Server Listening No. How do I fix this? Does this mean the server is not accepting connections?

**Comment by klightspeed** [comment]
Server-Running=Yes and Server-Listening=No generally means the server hasn't finished starting.

What is the output of `lsof -i` when run as the `steam` user?

**Comment by Nitric81** [comment]
It returns nothing. If I run it as root it shows my ssh connection but thats about it.

**Comment by klightspeed** [comment]
If you run `top`, how much CPU and memory is `ShooterGameServer` using?

**Comment by Nitric81** [comment]
3% cpu 24% mem

**Comment by Nitric81** [comment]
Im at work right now so I can't test to see if it is actually accepting connections.

**Comment by klightspeed** [comment]
Assuming you have 16GB of RAM, at that CPU and memory usage it should be up.

Do you have any mods installed?

**Comment by Nitric81** [comment]
Im trying to run the Valhalla Map and the Warmap mod that goes with it.

**Comment by klightspeed** [comment]
This along with the post you added in #360 suggests that the server is not even getting to the stage where it creates the SavedArks directory.

How much RAM does your server have?
Do you have sufficient disk space?
Is the ARK server able to start up without any mods?

**Comment by Nitric81** [comment]
8gb RAM 20gb free disk space currently.
If i run ./ShooterGameServer the server does show available in my Steam Favorites Server list and shows the session. if i run arkmanager start it does not show as responding. Also I just commented out the valhalla mod and it does the same thing. I also tried the suggestion in #395

**Comment by klightspeed** [comment]
Is this still a problem for you?

**Comment by klightspeed** [comment]
Closing old requests
