### ISSUE TITLE
Battleye multi instance

### ISSUE THREAD

**Issue by d4nn13** [FezVrasta/ark-server-tools#435]
How can i activate battleeye for all instances?
I have two instances up and running but only one starts battleeye, 
also the one two does not update from v235.9 regarding to the "status" / serverbrowser
but arkmanager says they are up2date (994960). I have tried "update --force" already with no luck.

**Comment by klightspeed** [comment]
Is this still occurring?

**Comment by klightspeed** [comment]
Closing old requests
