### ISSUE TITLE
Ark Server does not run when changing the map

### ISSUE THREAD

**Issue by Vintschente** [FezVrasta/ark-server-tools#436]
So the server is normally running when not changing the config files and players can connect.

I now downloaded the mod "504122600" which is the map  "Valhalla". I then edited the config file of the instance main. I commented out the "serverMap="TheIsland" and activated the "serverMapModId=504122600" and also tried with and without the "ark_GameModIds="504122600".

When I then start the server with "arkmanager run" I get the following errors:

"/home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/gameserver.cpp (715) : Assertion Failed: usGamePort != usQueryPort"

followed by the normal line: "Setting breakpad minidump AppID = 346110"

After this line the server would normally write the "server is up" after some time. Instead the line:

"CreateBoundSocket: ::bind returned error `[no name available] (13)`"

occurs every then and now. Sometime 3 times in a row after some seconds and sometimes only after 3 minutes.

Am I missing something? Do I need to change the arkmanager.cfg or is the main.cfg the correct one? Do I need to specify the start options at "arkmanager run" again?

Thank you in advance!

**Comment by klightspeed** [comment]
This sounds like your ark_Port and ark_QueryPort are the same in the config.

**Comment by Vintschente** [comment]
Everything is still set to the default value. my "ark_Port" is "7778" and my "ark_QueryPort" is 27015. As I said if I start the server normally with the default settings it runs normally. If I want to change the map it shows up this error. What is the normal way to change the map? I guess I am missing something.

**Comment by klightspeed** [comment]
Please try adding `serverMap=Valhalla` to your config, and changing `serverMapModId=504122600` to `ark_MapModID=504122600`

**Comment by dm0nkey** [comment]
my settings are:
serverMap="TheCenter"
ark_MapModID="614734500"

if I start the server with: arkmanager run, it works. But if I start the server with arkmanager start it isnt loading the map correctly, what I have to do to start it as deamon?

**Comment by klightspeed** [comment]
@dm0nkey Does the user under which arkmanager runs have access to the logs directory (set by the `logdir` setting in arkmanager.cfg)?

**Comment by dm0nkey** [comment]
yeah, access is granted to my steam user. That big thing is, that this server is running for about 6 months already, everything works perfect. But yesterday we changed the map and the server just can't startup correctly - I searched for an error or mistake in my configs but came up with that the start command is causing this. with run comman everything works fine. On running the server with run the command in htop is looking like this: "...ShooterGameServer TheCenter?GameModIds=..." but if I run it with start it looks like this: "...ShooterGameServer mapmodeid=IDOFMAP?GameModIds=..."

**Comment by dm0nkey** [comment]
had you the time to take a look at it? Is the run command maybe customizing the options a litle bit in other way than the start command? Like I said before, if I run it with run, it works with command: "...ShooterGameServer TheCenter?GameModIds=..." with start it looks like this:  "...ShooterGameServer mapmodeid=IDOFMAP?GameModIds=..."

**Comment by klightspeed** [comment]
Do you have "serverMapModID" in one of your config files?

`start` should use the same options as `run`, as `start` simply runs the `run` command in a separate process and backgrounds that.

**Comment by dm0nkey** [comment]
nope, in both configs I have set: ark_MapModID="614734500"

**Comment by klightspeed** [comment]
Is this fixed for you?

**Comment by klightspeed** [comment]
Closing old requests
