### ISSUE TITLE
Second instance launching with wrong port

### ISSUE THREAD

**Issue by Evilcious** [FezVrasta/ark-server-tools#437]
I have two instances : main and server2

**main.cfg** have those settings : 
- Port=7777
- PvPStructureDecay=true
- QueryPort=27016
- RCONEnabled=True
- RCONPort=32330

**server2.cfg** have those settings : 

- Port=7775\
- PvPStructureDecay=true\
- QueryPort=27020\
- RCONEnabled=True\
- RCONPort=32331\

Bottom of my **arkmanager.cfg** have this : 

- config_main="/etc/arkmanager/instances/main.cfg"
- config_server2="/etc/arkmanager/instances/server2.cfg"
- arkautorestartfile='ShooterGame/Saved/.autorestart'
- install_bindir='/usr/local/bin'
- install_libexecdir='/usr/local/libexec/arkmanager'
- install_datadir='/usr/local/share/arkmanager'
- mod_appid='346110'
- defaultinstance="main"

My **server2** command line looks like this : 

> /home/steam/servers/ark2/ShooterGame/Binaries/Linux/ShooterGameServer -MapModID=504122600\
AllowCaveBuildingPvE=False\
BabyFoodConsumptionSpeedMultiplier=3.0\
BabyMatureSpeedMultiplier=20\
BanListURL=http://playark.com/banlist.txt\
CropDecaySpeedMultiplier=1.5\
CropGrowthSpeedMultiplier=0.8\
DayTimeSpeedScale=0.3\
DifficultyOffset=1.3\
DinoCountMultiplier=1.5\
EggHatchSpeedMultiplier=20\
GameModIds=609380111\,558651608\,547099024\,564895376\,572277026\,536214294\
GlobalCorpseDecompositionTimeMultiplier=2.0\
HarvestAmountMultiplier=4.0\
LayEggIntervalMultiplier=0.8\
MatingIntervalMultiplier=0.8\
MaxPlayers=5\
NightTimeSpeedScale=1.7\
PerPlatformMaxStructureMultiplier=1.0\
**Port=7769\**
PvPStructureDecay=true\
QueryPort=27020\
RCONEnabled=True\
RCONPort=32331\
ResourceNoReplenishRadiusPlayers=0.5\
ResourceNoReplenishRadiusStructures=0.5\
ResourcesRespawnPeriodMultiplier=0.3\
ServerAdminPassword=PASSWORD
ServerCrosshair=True\
ServerPassword=SERVPASSWORD
SessionName=SERVER TEST
ShowMapPlayerLocation=True\
TamingSpeedMultiplier=4.3\
XPMultiplier=4.0\
allowThirdPersonPlayer=True\
alwaysNotifyPlayerJoined=True\
alwaysNotifyPlayerLeft=True\
globalVoiceChat=True\
noTributeDownloads=True\
proximityChat=True\
listen -UseBattlEye

As you can see, the port defined in **server2.cfg** is different in the command line ! It changes everytime I launch this instance. which results in the message : 

`/home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/gameserver.cpp (715) : Assertion Failed: usGamePort != usQueryPort
CreateBoundSocket: ::bind returned error [no name available](13)
`

I don't get why it tells me that the GamePort must be different than the QueryPort as they are not defined as the same.

My main instance is working fine. Any idea ?

**Comment by Evilcious** [comment]
[server2.txt](https://github.com/FezVrasta/ark-server-tools/files/152741/server2.txt)
[main.txt](https://github.com/FezVrasta/ark-server-tools/files/152742/main.txt)
[arkmanager.txt](https://github.com/FezVrasta/ark-server-tools/files/152743/arkmanager.txt)

**Comment by klightspeed** [comment]
What is the output of `arkmanager --version`

**Comment by Evilcious** [comment]
```
Version: 1.5
Channel: master
Commit: ed9d382

```

**Comment by klightspeed** [comment]
I can't see anything that would do anything except subtract 1 from `ark_Port` to get the `Port` value passed to the server.  Only `ark_Port=7770` should result in `Port=7769` being passed to the server.

I was able to duplicate the `Assertion Failed: usGamePort != usQueryPort` using the parameters in your configs, and was able to work around it by commenting out the `serverMapModId` line and adding  mod 504122600 as the first mod in the `GameModIds` list.

It looks like the `-MapModID=<modid>?...` syntax no longer works with the ARK server.  Instead, one needs to specify MapModID as a separate parameter while still providing the map name - e.g. `-MapModID=<modid> <mapname>?...` or `<mapname>?MapModID=<modid>?...`

* `-MapModID=504122600?...` results in the assertion failure
* `-MapModID=504122600 ?...` results in the map name being `ShooterEntry`
* `?MapModID=504122600?...` also results in the map name being `ShooterEntry`
* `-MapModID=504122600 Valhalla?...` results in the map name being `Valhalla`
* `Valhalla?MapModID=504122600?...` also results in the map name being `Valhalla`

**Comment by Evilcious** [comment]
Ok. So, right now, it's impossible to use ArkManager with another map ?

**Comment by klightspeed** [comment]
@Evilcious a workaround is to change `serverMapModId` to `ark_MapModID`.

**Comment by Evilcious** [comment]
Works like a charm now. Thanks a lot !
