### ISSUE TITLE
How to manually download mod for server?

### ISSUE THREAD

**Issue by joebywan** [FezVrasta/ark-server-tools#439]
This is less of an issue and more of a question, couldn't find a way to contact you guys otherwise.

I've tried using arkmanager, but it was having issues not reading the cfg files in /etc/arkmanager so I've been trying to do it without a server wrapper.

Just wondering what exactly you guys are executing for downloading a mod for the server (more specifically the valhalla mod)?

I've tried /home/steam/steamcmd.steamcmd.sh +login anonymous +workshop_download_item 346110 504122600 +quit

This returns that it's failed "ERROR! Download item 504122600 failed (No match)."

What syntax do you guys use with steamcmd to download mods for the dedicated server?

**Comment by axi92** [comment]
There is the line what you are searching for: https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L1178

**Comment by klightspeed** [comment]
@joebywan the command you are using is the correct command.

```
cd /home/steam/steamcmd
./steamcmd.sh +login anonymous +workshop_download_item 346110 504122600 +quit
```

Note however that with large mods it takes a few attempts to fully download the mod, as steamcmd will timeout after a couple of minutes.

**Comment by joebywan** [comment]
Oh cool, so will it automatically download to the app's install folder?  I was getting the regular timeout when running it with mod_appid:-346110 instead of just 346110.  When just running as 346110 it gave the above error.

I'll keep at it then.

Appreciate the tips, thanks!
