### ISSUE TITLE
SessionName with spaces in the .cfg file will not work.

### ISSUE THREAD

**Issue by Levistras** [FezVrasta/ark-server-tools#44]
In /etc/arkmanager/arkmanager.cfg I have:

sessioname="[The Saurian Isles][PvE]"

If I let this go through, my server name in game will be "[The".

Instead what I've been doing, is putting the Session Name in my INI file:

[SessionSettings]
SessionName=[The Saurian Isles][PvE]

This seems to work fine.  However whenver I update ark-server-tools I manually edit /usr/bin/arkmanager after install, and remove the session name parameters from the doStart() section.

**Comment by FezVrasta** [comment]
in 1.1 I'm fixing it, I've a little issue but I hope to sort it out soon.

By the way, you can just escape your spaces in the config file in the meanwhile
```
sessioname="[The\ Saurian\ Isles][PvE]"
```

**Comment by Levistras** [comment]
Thanks for this fix!
