### ISSUE TITLE
config error 1.6

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#440]
Hi, i've just updated to 1.6 and i got that 

steam@arkfrancegaming:/etc$ arkmanager useconfig pvp saveworld
Running command 'saveworld' for instance 'pvp'
Error: config file /etc/arkmanager/arkmanager.cfgdefaultinstance=main does not exist

Got the main.cfg in /etc/arkmanager/instances

**Comment by klightspeed** [comment]
What are the contents of your arkmanager.cfg around `configfile_pvp=...`

**Comment by arkfrancegaming** [comment]
configfile_pvp="/etc/arkmanager/arkmanager.cfg"

**Comment by arkfrancegaming** [comment]
the arkserverroot has been remove during the update i guess

**Comment by arkfrancegaming** [comment]
i've re added it now i've got :+1: 


steam@arkfrancegaming:/etc$ arkmanager useconfig pvp status
Running command 'status' for instance 'pvp'
 Server running:   Yes
 Server listening:   No
 Server version:   1003475

**Comment by arkfrancegaming** [comment]
the : 
ark_RCONPort="32330"   
ark_Port="7779"                                                    
ark_QueryPort="27019"   

have also been remove

**Comment by klightspeed** [comment]
You have pointed `configfile_pvp` back at the common config file.  You need to point it at its own config file.

**Comment by arkfrancegaming** [comment]
it was but the update added and removed some line in the arkmanager.cfg

**Comment by klightspeed** [comment]
If you had an `arkserverroot` line in `arkmanager.cfg`, and `/etc/arkmanager/instances/main.cfg` did not exist, then the install script will have moved the `main` instance config out to `/etc/arkmanager/instances/main.cfg`, and added a `defaultinstance="main"` line to `arkmanager.cfg`.
