### ISSUE TITLE
Hardlinking instances together & backups named by instance, not just by date

### ISSUE THREAD

**Issue by joebywan** [FezVrasta/ark-server-tools#443]
On this topic: https://github.com/FezVrasta/ark-server-tools/issues/441 klightspeed mentioned

> Yes. However, the files outside ShooterGame/Saved on one instance can be hard-linked to the files outside ShooterGame/Saved in the other instance in order to save disk space.

wouldn't this give file in use errors? I'm guessing this is making the system think it has two copies, but the 2nd is just links to the initial one? If not, how would I do this?

Also when running backups, it's just naming them date_time. Is there any plans to include some instance identifier for them? Otherwise if I need to restore a particular server, I am going to have to wade through backups, restoring them to find the one I'm after & testing by logging in to make sure it's the right map.

**Comment by klightspeed** [comment]
> On this topic: #441 klightspeed mentioned "Yes. However, the files outside ShooterGame/Saved on one instance can be hard-linked to the files outside ShooterGame/Saved in the other instance in order to save disk space.", wouldn't this give file in use errors?

Under Linux, it will only give a "Text File Busy" error if one attempts to write to an executable that is running.  Unlike Windows, deleting (unlinking) an in-use file will not cause an error - the file will continue to exist without a name until it is closed.  See http://linux.die.net/man/2/unlink or `man 2 unlink`

The way that steamcmd updates files is to create a new file from the contents of the old file, patch the new file, then delete the old file and put the new file in its place.

> I'm guessing this is making the system think it has two copies, but the 2nd is just links to the initial one?

Under linux filesystems, with hard-linked files, there is no first file.  Both files link to the same inode.  See http://linux.die.net/man/2/link or `man 2 link`

> If not, how would I do this?

When the `arkStagingDir` setting is set to a directory on the same filesystem as the instances, the `update` command update the instance by linking files from the staging directory.  When all instances are updated from the same staging directory, then the static files in the instances will be linked together.

> Also when running backups, it's just naming them date_time. Is there any plans to include some instance identifier for them? Otherwise if I need to restore a particular server, I am going to have to wade through backups, restoring them to find the one I'm after & testing by logging in to make sure it's the right map.

We can add a `arkbackupprefix` setting which can be set per-instance, and have this default to the instance name.

The `arkbackupdir` setting also specifies where to store the backups, and can be specified per-instance.

**Comment by joebywan** [comment]
> When the arkStagingDir setting is set to a directory on the same filesystem as the instances, the update command update the instance by linking files from the staging directory. When all instances are updated from the same staging directory, then the static files in the instances will be linked together.

So all I have to do is set a folder for arkstagingdir & after it runs an update it'll link the instances meaning I'm effectively storing 1 copy, but it's looking like two?

**Comment by FezVrasta** [comment]
@klightspeed any change to get your email to contact you privately?
Thanks.

**Comment by klightspeed** [comment]
@joebywan pretty much yes.

**Comment by joebywan** [comment]
Hey dude, so I installed the latest 237 update for the server, have the arkstagingdir set.  I checked storage on the hard drive by right clicking computer>properties in nautilus, and it's reading like it's seeing both instances on the drive as taking up storage instead of them being linked together.  Do you have a set of instructions on how to hardlink instances?

**Comment by joebywan** [comment]
nvm, think I got it.  cp -al <sourcefolder> <destinationfolder> then delete the shootergame/saved folder.
