### ISSUE TITLE
mod Variable 

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#446]
Hi,

is it possible to add a variable in the update warn message to show which mod is going to be update ?

For exemple : Serveur is restarting to update the mod $modname

Thanks

**Comment by klightspeed** [comment]
i.e. something like the following?

```
msgWarnReason="This ARK server will shutdown for {reason} in {time}"
msgTimeMinutes="{minutes} minutes"
msgTimeSeconds="{seconds} seconds"
msgReasonUpdateApp="an update to the game"
msgReasonUpdateMod="an update to mod(s) {modnamesupdated}"
msgReasonUpdateAppMod="an update to the game and an update to mod(s) {modnamesupdated}"
msgReasonRestart="a restart"
```

where 
* `{reason}` is replaced by the reason selected from the msgReason* variables
* `{time}` is replaced by the time string selected from the msgTime* variables
* `{minutes}` is replaced by the number of minutes remaining
* `{seconds}` is replaced by the number of seconds remaining
* `{modnames}` is replaced by the comma-separated list of mod names

**Comment by arkfrancegaming** [comment]
Would be perfect yep !

**Comment by arkfrancegaming** [comment]
Is it possible to impliment that ?

**Comment by arkfrancegaming** [comment]
@klightspeed  ?

**Comment by klightspeed** [comment]
Are you happy with the options added with 1.6-dev?

**Comment by klightspeed** [comment]
Closing old requests
