### ISSUE TITLE
Server Config not taking

### ISSUE THREAD

**Issue by konfuzedwon** [FezVrasta/ark-server-tools#447]
Hello,

I appear to be having an issue on my server, running on Debian with this awesome tool.  I've added commands to the instance config, which does convert over to the ARK GameUserSettings.ini (I looked and verified) however the rates in-game seem to not change.  The main one I notice is the HarvestAmountMultiplier, I have set to 3 (tried 3, 3.0, 3.000000) and it doesn't want to get 3x resources.  It used to work fine, and now it isn't and I'm not sure if there's another config that would override these settings?  It was at 2, but now with the latest ARK server update it's seems to be at 1x, even with it set to 3.

ark_XPMultiplier="3.000000"
ark_HarvestAmountMultiplier="3.000000"
ark_TamingSpeedMultiplier="6.000000"
ark_HarvestHealthMultiplier="2.000000"
ark_noTributeDownloads="True"

These are my custom commands in the main.cfg instance config.  Thoughts?

**Comment by klightspeed** [comment]
The fact that the setting is being written to the GameUserSettings.ini file means that the server is processing the option.  If the server is not honouring the option, then this would probably be either a bug with the game or a mod overriding the setting.
