### ISSUE TITLE
Resource Utilization 

### ISSUE THREAD

**Issue by Lamira** [FezVrasta/ark-server-tools#449]
Hi,

This may not be the right place but i'm running an instance on a dedicated server, during peak times we're getting some rubber banding and lag but when i look only 15% of server resources are being used (CPU usage, Memory etc), no matter how much load the server is under it only uses 15%, is there anyway to force the machine to use more?

**Comment by f0rkz** [comment]
Sounds like an ARK issue rather than the tool's issue.

**Comment by arkfrancegaming** [comment]
How big is the savegame ?

**Comment by 7h3ju57** [comment]
Happens to me whenever the server saves the world to disk.  This is an issue with ark unfortunately.
