### ISSUE TITLE
Can breeding multipliers be changed using arkmanager?

### ISSUE THREAD

**Issue by joebywan** [FezVrasta/ark-server-tools#450]
So from what I can gather the changes have to be made to game.ini.  Is there a way to use arkmanager for managing breeding speed increase settings? or is it a manual thing in game.ini?

**Comment by arkfrancegaming** [comment]
Game.ini option 

EggHatchSpeedMultiplier=10
BabyMatureSpeedMultiplier=10

**Comment by joebywan** [comment]
I get that it needs to be put in game.ini, just wondering if there's a way for arkmanager to manage it without us having to dig into the config files.

**Comment by klightspeed** [comment]
So which config files do you want to edit - main.cfg or game.ini?

**Comment by joebywan** [comment]
game.ini & options for gameusersettings.ini would be cool too.

**Comment by klightspeed** [comment]
So you're wanting to edit Game.ini options ... by editing instance cfg options...

**Comment by joebywan** [comment]
I’d like to edit all of the options in one place.  Your response could be applied to using the instance.cfg for any of this.

**Comment by KaneHart** [comment]
lmao good idea but confused why I keep googling game.ini and knlightspeed seems so against it.
