### ISSUE TITLE
Your SteamCMD root seems not valid.

### ISSUE THREAD

**Issue by masjason1** [FezVrasta/ark-server-tools#454]
Heres the error code "/usr/local/bin/arkmanager: line 81: /etc/arkmanager/arkmanager.cfg: No such file or directory
/usr/local/bin/arkmanager: line 81: /etc/arkmanager/arkmanager.cfg: No such file or directory
/usr/local/bin/arkmanager: line 81: /etc/arkmanager/arkmanager.cfg: No such file or directory
/usr/local/bin/arkmanager: line 81: /etc/arkmanager/arkmanager.cfg: No such file or directory
/usr/local/bin/arkmanager: line 81: /etc/arkmanager/arkmanager.cfg: No such file or directory
[  ERROR  ]     Your SteamCMD root seems not valid.
[  ERROR  ]     Your SteamCMD exec could not be found.
[  ERROR  ]     You have not rights to write in the log directory.
Running command 'restart' for instance 'pvp'
Error: no config files for instance pvp
Error: no config files for instance pvp
....

please tell me how i can fix this . right now i have a pve server that is up and running but i cant seem to figure out how to fix this error

**Comment by klightspeed** [comment]
The first few errors suggest that you are running the script as root.  Try running the script as your steam user.

**Comment by masjason1** [comment]
right now my one server is running as root. and my server thats not working is also running as root so why would
 this be a problem?

**Comment by f0rkz** [comment]
Because running processes as root is generally a bad idea.

**Comment by masjason1** [comment]
How would i change it back to steam then?

**Comment by masjason1** [comment]
ok well i changed it and im getting same error code

**Comment by f0rkz** [comment]
Are all of your game files and configs and steamcmd owned as root?

**Comment by masjason1** [comment]
They have root permission , thats all i really know im not that linux savy yet

**Comment by masjason1** [comment]
ok well i fixed that problem and now i have this one. 
[ [1;31m ERROR [0;39m ] 	Mod 510854250 is requested but not installed.  Run 'arkmanager installmod 510854250' to install this mod.
[ [1;31m ERROR [0;39m ] 	Mod 534838287 is requested but not installed.  Run 'arkmanager installmod 534838287' to install this mod.
[ [1;31m ERROR [0;39m ] 	Mod 566887000 is requested but not installed.  Run 'arkmanager installmod 566887000' to install this mod.
Running command 'restart' for instance 'pvp'
Error: no config files for instance pvp
Error: no config files for instance pvp

**Comment by klightspeed** [comment]
Did you resolve this by ensuring that either `/etc/arkmanager/instances/pvp.cfg` or `~/.config/arkmanager/instances/pvp.cfg` exists?

**Comment by klightspeed** [comment]
Continued in #455
