### ISSUE TITLE
Error saying no config files for my server

### ISSUE THREAD

**Issue by masjason1** [FezVrasta/ark-server-tools#455]
Heres error code 
Running command 'restart' for instance 'pvp'
Error: no config files for instance pvp
Error: no config files for instance pvp

also the files are actually there but idk why its not reading it

**Comment by klightspeed** [comment]
This was a continuation of #454.

Did you resolve this by ensuring that either `/etc/arkmanager/instances/pvp.cfg` or `~/.config/arkmanager/instances/pvp.cfg` exists?
