### ISSUE TITLE
Ark Server are Running down´t listen on Ark Client

### ISSUE THREAD

**Issue by Bluppy** [FezVrasta/ark-server-tools#456]
Hello Guys,

i have a very curious problem. The ark server are starting fine und on status page i see him to listen.

Running command 'status' for instance 'main'
 Server running:   Yes
 Server listening:   Yes
Server Name: PVE Simu4you German Diff 1.0 TAM/2.5 XP/1.5 - (v238.3)
Players: 0 / 50
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/138.201.49.140:27016
 Server version:   1055048

On Webseite link you see the Server is on. When your use the app start link your can join the server. When your are search on Ark Client with name "Simu4you" you downt find the server.

on the Log i see this error:

20:15:01: start
20:15:01: Running /home/arkpve/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=50\?Port=7777\?QueryPort=27016\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=************\?ServerPassword\?SessionName=PVE\ Simu4you\ German\ Diff\ 1.0\ TAM/2.5\ XP/1.5\?listen -OnlyAdminRejoinAsSpectator -UseBattlEye
20:15:01: Server PID: 2032
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
20:16:25: server is up

but i review the ulimit and this ouput is fine.

arkpve@yoda:~$ ulimit -n
1000000

have any where a idea how can i fix my problem?

**Comment by arkfrancegaming** [comment]
Where is your server hosted ?

**Comment by Bluppy** [comment]
this is hosted on my own root. i transfer the setup to new root hardware and i become the problem with upgrade die arkmanager version

**Comment by arkfrancegaming** [comment]
it should be a firewall issue

**Comment by Bluppy** [comment]
i have no firewalls or other running.

root@yoda ~ # iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

**Comment by klightspeed** [comment]
Due to the huge number of servers out there, the ARK client is known to often not be able to search for a particular server, or take a long time until the server shows up.

The fact that Arkservers.net shows the server up and currently has 3 people connected suggests that the server doesn't have any problems.

You said:
> on the Log i see this error:
...
> [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.

This "error" is harmless - it just means that the ARK server (or perhaps the Steam API library that it uses to advertise its presence on the Steam server list) is trying to connect to the Steam client.   Being a server, it ignores this error and continues, as requiring the Steam client to be running on a headless server would be insane.

**Comment by Bluppy** [comment]
yes your are right. The 3 Users are have joint the server over the Website.

but we have befor transfer the hostsystem old hardware to new we found the server with ark client.

But i have create 2 Screenshots

But the first when i Search with Name Simu4you on unoffical:
http://www.bilder-upload.eu/show.php?file=8bd6b9-1464379679.jpg
But i downt found this server

here is the Screenshot with same Word and use my fav. list
http://www.bilder-upload.eu/show.php?file=23248d-1464379723.jpg

**Comment by klightspeed** [comment]
With the huge number of unofficial ARK servers, the server list has problems listing all of the servers.  This is a client-side problem, not a server-side problem.
