### ISSUE TITLE
I can't update my server

### ISSUE THREAD

**Issue by thymon13** [FezVrasta/ark-server-tools#458]
Hi all,

```
steam@HomeServer:~$ arkmanager update --warn
Running command 'update' for instance 'main'
Downloading ARK update ... Update download interrupted
```
How can i fix my problem ?

Thanks in advance

Thymon

**Comment by thymon13** [comment]
Ok so,

I updated my server, with steamcmd manually.
But I would like use arkmanager tools for my update. :-(

**Comment by thymon13** [comment]
New update (v239) and same issue.
I must use steamcmd because arkmanager tool doesn't work correctly. "Download update interrupted"

**Comment by thymon13** [comment]
Commande update with --verbose option :

```
steam@HomeServer:~$ arkmanager update --verbose --warn --backup
Running command 'update' for instance 'main'
Downloading ARK update
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Success! App '376030' already up to date.
Update download interrupted
```

Don't understand why the download is interrupted.

**Comment by klightspeed** [comment]
What is the output of `arkmanager checkupdate`

The fact that it is trying to download an update suggests that the version that `steamcmd +app_info_print 376030` gives is different to the version that is running.

It saying that the download was interrupted suggests that steamcmd returned a non-zero status - i.e. the return status said it failed.  It's probably returning a non-zero status due to `Created shared memory when not owner SteamController_Shared_mem`.

**Comment by thymon13** [comment]
Output of `arkmanager checkupdate` :

```
steam@HomeServer:~$ arkmanager checkupdate
Running command 'checkupdate' for instance 'main'
Querying Steam database for latest version...
Current version:  1086598
Available version:  1088277
Your server needs to be restarted in order to receive the latest update.
Run "arkmanager update" to do so

```

I found nothing about : `Created shared memory when not owner SteamController_Shared_mem`

**Comment by thymon13** [comment]
I found it !! :-D

It was on my arkmanager.cgf
At the line `arkStagingDir="/home/steam/ARK-Staging"   `   
I should add : `#`
like : `#arkStagingDir="/home/steam/ARK-Staging"   `   

It was my mistake         ...as usual

**Comment by Romaq** [comment]
This should stay closed... but I also have "ARK-Staging" set and this is killing my ability to update as well. Either "a" staging is broken, or "b" there should be a warning not to use this except in VERY specific circumstances.

If pulling the line doesn't fix the problem, I'll reply back here. If I don't post, this is resolved when I comment it out same as for @thymon13.
