### ISSUE TITLE
2nd instance started showing 0/0 player slots

### ISSUE THREAD

**Issue by joebywan** [FezVrasta/ark-server-tools#459]
I've got two instances setup on my machine.  Both work fine when they're the first instance started.

The problem is that when either one is started 2nd, the arkmanager status shows as having 0/0 slots & the server won't show in the server browser.

I've attached a zip containing the arkmanager.cfg aswell as the instance cfg files.

[arkmanager.zip](https://github.com/FezVrasta/ark-server-tools/files/216985/arkmanager.zip)

**Comment by blackgolddragon** [comment]
Tried to give your servers different rcon ports?

**Comment by joebywan** [comment]
rcon's only for remote control, and they've never been available to the outside world.  I've had this working briefly in the past, then shut it down.  I then needed a 2nd instance again, but now I'm having this issue.

**Comment by Destructor** [comment]
I Have this problem (Dedicated OVH)

No Firewall on my dedicated.

**Comment by Destructor** [comment]
I have changed ip of my server and is work....

Blacklisted ???

**Comment by joebywan** [comment]
I can't change the public IP, and it won't be blacklisted/blocked as I'm using the same IP to host my original server.

**Comment by badboysgaming** [comment]
check ports you need to open ports up for both instances iptables -I INPUT -p udp --dport 27015 -j ACCEPT
iptables -I INPUT -p tcp --dport 27015 -j ACCEPT
iptables -I INPUT -p udp --dport 7777 -j ACCEPT
iptables -I INPUT -p tcp --dport 7777 -j ACCEPT
iptables -I INPUT -p tcp --dport 32330 -j ACCEPT

iptables -I INPUT -p udp --dport 27016 -j ACCEPT
iptables -I INPUT -p tcp --dport 27016 -j ACCEPT
iptables -I INPUT -p udp --dport 7778 -j ACCEPT
iptables -I INPUT -p tcp --dport 7778 -j ACCEPT
iptables -I INPUT -p tcp --dport 32331 -j ACCEPT

**Comment by joebywan** [comment]
It shouldn’t be a port thing, I’ve not had to open ports for the other server.

**Comment by badboysgaming** [comment]
well i'm running two servers they are working fine and showing up

**Comment by klightspeed** [comment]
Is this still a problem?

**Comment by joebywan** [comment]
Yea it is.  Still unresolved.

**Comment by klightspeed** [comment]
In your configs, your RCON is enabled, and both servers are trying to listen to the same port.  This would cause the second server to fail to properly start, thus your 0/0 players.  Give the servers different RCON ports.

**Comment by joebywan** [comment]
legend, worked a treat.  Resolved.
