### ISSUE TITLE
Monitoring command

### ISSUE THREAD

**Issue by Saij** [FezVrasta/ark-server-tools#461]
Hi,

is it possible to add a monitoring command? The goal is to run a command from a cronjob that checks if the servers are up (and do not hang) and if not starting them. 
Maybe additionally add an e-mail option that will send an e-mail if there were any problems with the server.

Greetings
Saij

**Comment by dm0nkey** [comment]
arkmanager status is all you need. for the mailing status to your email adress, just write an own script

**Comment by TOXid** [comment]
arkmanager status  do restart server if it fall?

**Comment by rob-bb** [comment]
I have a possible error/problem with the status command.  It reports 4 user on the servers, but here http://ark-servers.net/server/46184/ it reports none.   Is this a problem with arkmanager or the actual ark server?

**Comment by klightspeed** [comment]
The player count part of `arkmanager status` uses the `Players` field of the [Source Engine Query Response](https://developer.valvesoftware.com/wiki/Server_queries#Response_Format)

**Comment by rob-bb** [comment]
Thanks, I'll have a play with that :)

**Comment by klightspeed** [comment]
Indeed, arkservers.net uses the [`A2S_PLAYERS`](https://developer.valvesoftware.com/wiki/Server_queries#A2S_PLAYER) query to get the players connected, and takes any difference between that player count and the player count returned by the `A2S_INFO` query to be unknown / connecting.
