### ISSUE TITLE
Can't install / update Mods

### ISSUE THREAD

**Issue by Thund3rEye81** [FezVrasta/ark-server-tools#462]
Hi everyone,

i am facing the problem that I can't update or (re) install Mods.
Everytime I get the following prompt: 
`
Downloading mod 647457163 ... Mod 647457163 was not successfully downloaded
`
At the first installation everything went good.
No Errors or so on in the Arkmanager Logfiles.
I would be glad if anyone could help

**Comment by morggin** [comment]
i'm having this same issue on a new server install.  In fact i was not able to "arkmanager install" (never completed) and had to resort to SCP the server files from my other linux server to get it to running.

**Comment by spitfire1081** [comment]
Can anybody PLEASE give us some support with modded servers? I am having really a bad time with this tool and mods...
Could any of the writers do a step-by-step tutorial?

**Comment by arkfrancegaming** [comment]
same for me

**Comment by badboysgaming** [comment]
# steamdb specific
appid=376030                                                        # Linux server App ID
mod_appid=346110 

male sure on arkmanager.cfg is set with proper id mod_appid=346110

**Comment by Thund3rEye81** [comment]
Checked it.
is set to the right IDs

**Comment by klightspeed** [comment]
@Thund3rEye81 Given the `Mod 647457163 was not successfully downloaded` error without any error message, this suggests that steamcmd reported success, yet the mod directory `$steamcmdroot/steamapps/workshop/content/346110/647457163` did not have a `mod.info` file.

What is your `$steamcmdroot` directory?  Is there a `steamapps` directory in that, containing a `workshop` directory?

**Comment by klightspeed** [comment]
Is this still a problem?

**Comment by rob-bb** [comment]
I am having this problem right now, weiord
