### ISSUE TITLE
How can modify game.ini file ?

### ISSUE THREAD

**Issue by zazira** [FezVrasta/ark-server-tools#464]
Hi,

I want to add to game.ini this line : 
OverridePlayerLevelEngramPoints=200000
MatingIntervalMultiplier=3.0
EggHatchSpeedMultiplier=3.0
BabyMatureSpeedMultiplier=3.0

I have try to modify directly game.ini, and add ark_Ove... in main.cfg, but this fail.

I'm waiting ur help.

Thanks :)

**Comment by dm0nkey** [comment]
the Game.ini has to begin with this line: [/script/shootergame.shootergamemode]

than you have to shutdown the server, edit the file and start the server than. Otherwise the server will overwrite your changes with current running settings.

**Comment by zazira** [comment]
Thanks man :)
