### ISSUE TITLE
Permission error when updating Ubuntu Host

### ISSUE THREAD

**Issue by FrostyMonster626** [FezVrasta/ark-server-tools#466]
Hi
It seems whenever a host update is done (apt-get upgrade etc.) the permissions go all wonky.
What I do is the following:
1. arkmanager stop
2. apt-get update and apt-get upgrade
3. restart host
4. arkmanager start -- get no access permission errors regarding the ark world file - "fresh" ark server
5. restore older ark data
6. chmod -R 777 on the ark server directory
7. arkmanager start
8. all works fine.

doing a chmod -R 777 on the ark server directory does not work until the older data is restored.

**Comment by thymon13** [comment]
Do you use the correct user ? as Steam for exemple

**Comment by FrostyMonster626** [comment]
Yes I do

**Comment by klightspeed** [comment]
Is this fixed with the hotfix to v1.5?
