### ISSUE TITLE
Arkmanagar backup fails on linux because of case sensitivity

### ISSUE THREAD

**Issue by marcus-no** [FezVrasta/ark-server-tools#468]
<server>:/ark/server/ShooterGame/Saved/SavedArks$ ls *alhalla.ark
valhalla.ark <- lower case first letter

Below - upper case first letter:
Copying ARK world file cp: cannot stat '/ark/server/ShooterGame/Saved/SavedArks/Valhalla.ark': No such file or directory
cp: cannot stat '/ark/server/ShooterGame/Saved/SavedArks/Valhalla.ark': No such file or directory
cp: cannot stat '/ark/server/ShooterGame/Saved/SavedArks/Valhalla.tmp': No such file or directory
[ FAILED ]

**Comment by klightspeed** [comment]
1.6-dev should fix this.
