### ISSUE TITLE
Error when executing "Any" ArkManager commands ( Linux )

### ISSUE THREAD

**Issue by NLBlackEagle** [FezVrasta/ark-server-tools#469]
It's been a while since this started to bug me. As it appears it doesnt affects anything yet, however when new functions are implemented it might cause a issue.

Also, I dont think the orgin of the issue lies within ArkManager but I do think that the develloper of ArkManager should keep this in mind.

The error:
find: failed to restore initial working directory: Permission denied.

The error showed up when instances where implemented. I personally think that "Somehow" arkmanager was able to make the new instances file but did not got the permissions granted to actually modify the file.

I tried a complete reinstall which did not solved this issue aswell.

**Comment by klightspeed** [comment]
> find: failed to restore initial working directory: Permission denied.

Are you running the script as root from /root?

The steam user does not have permission to /root, thus the error.
