### ISSUE TITLE
Arkmanager Failed to start server.

### ISSUE THREAD

**Issue by NLBlackEagle** [FezVrasta/ark-server-tools#470]
This error gets created when trying to start up the server:

17:58:13: start
/usr/local/bin/arkmanager: line 552: ulimit: open files: cannot modify limit: Operation not permitted
17:58:13: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=70\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=keyboardcat\?ServerPassword\?SessionName=ArkRealms\ \[A-R\]\ craftrealms.org\?listen
17:58:13: Server PID: 27895
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
/usr/local/bin/arkmanager: line 434: lsof: command not found
17:59:58: Bad PID ''; expected '27895'
/usr/local/bin/arkmanager: line 609: 27895 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
17:59:58: exited with status 0

Ulimit -a result:

core file size          (blocks, -c) 100000
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 64119
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) 100000
open files                      (-n) 2048
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 64119
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by NLBlackEagle** [comment]
Eddited the Soft & Hard limits in limits.conf:

*               soft    core            100000
*               hard    rss             100000
*               soft    nofile          100000
*               hard    nofile          100000

Then tried to start up which resulted in this error:

19:02:43: start
19:02:43: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer -MapModID=614734500\?MaxPlayers=70\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=keyboardcat\?ServerPassword\?listen
19:02:43: Server PID: 5077
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:C:\SVN_Ark\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectGlobals.cpp] [Line: 1737] 
Objects have the same fully qualified name but different paths.
	New Object: DinoCharacterStatusComponent_BP_Trike_C /Game/Mods/614734500/TheCenter.TheCenter:PersistentLevel.Human
	Existing Object: DinoCharacterStatusComponent_BP_Bigfoot_C /Game/Mods/614734500/TheCenter.TheCenter:PersistentLevel.Human
Signal 11 caught.
/usr/local/bin/arkmanager: line 651:  5077 Segmentation fault      (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
19:04:13: Bad PID ''; expected '5077'
19:04:13: exited with status 0
19:13:09: start
19:13:09: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer -MapModID=614734500\?MaxPlayers=70\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=keyboardcat\?ServerPassword\?listen
19:13:09: Server PID: 5805
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

**Comment by klightspeed** [comment]
> /usr/local/bin/arkmanager: line 434: lsof: command not found

That means that you didn't have `lsof` installed.

> Objects have the same fully qualified name but different paths.
New Object: DinoCharacterStatusComponent_BP_Trike_C /Game/Mods/614734500/TheCenter.TheCenter:PersistentLevel.Human
Existing Object: DinoCharacterStatusComponent_BP_Bigfoot_C /Game/Mods/614734500/TheCenter.TheCenter:PersistentLevel.Human

That means there's an error in Mod 614734500

**Comment by NLBlackEagle** [comment]
Weird though that removing all mods from startup line makes the server not being able to start up but when all mods previously installed are in the startup line the server does start up.

Anyway, I'll be reinstalling the whole ark server since it became a gigantic mess.

**Comment by klightspeed** [comment]
> Weird though that removing all mods from startup line makes the server not being able to start up but when all mods previously installed are in the startup line the server does start up.

It's likely that when anything from a mod is used, the saved world will require files from that mod in order for the server to start.  The ARK server (and possibly UE4) does not gracefully handle mods being missing.

If it's a mod that only adds items, then destroying or replacing all of those items before removing the mod __may__ work.

If the mod contains engrams, then having everyone unlearn those engrams __may__ work.

If the mod modifies anything else, then removing the mod will likely require a world reset.
