### ISSUE TITLE
Mods not loading since update 240

### ISSUE THREAD

**Issue by Braste** [FezVrasta/ark-server-tools#471]
Since update 240 mods downloaded / updated with arkmanager does not get loaded. At worst the server crashes. This is because of the .mod file, it does not get created properly and is missing important entries

**Comment by arkfrancegaming** [comment]
Mod not fully downloaded for me

**Comment by Braste** [comment]
Did some testing, even with the changes in Pull request #472 it does not work, when a map extension is loading multiple sublevels:

How the .mod file should look:

`â.:'........Map Extension: Streichelzoo.,...../../../ShooterGame/Content/Mods/658112994.....,.../Game/Maps/TheIslandSubMaps/Streichelzoo_01.,.../Game/Maps/TheIslandSubMaps/Streichelzoo_02.,.../Game/Maps/TheIslandSubMaps/Streichelzoo_03.,.../Game/Maps/TheIslandSubMaps/Streichelzoo_04.,.../Game/Maps/TheIslandSubMaps/Streichelzoo_05.3ÿ"ÿ.............ModType.....4.....GameModBaseAsset.....TODO.....PrimalGameData.........Version.....2.....GUID.!...EDFDB166436D8EA3B0072F9058F44B08.`

How it acutally looks:

`â.:'........Map Extension: Streichelzoo.,...../../../ShooterGame/Content/Mods/658112994.....,.../Game/Maps/TheIslandSubMaps/Streichelzoo_01.3ÿ"ÿ.............ModType.....4.....GameModBaseAsset.....TODO.....PrimalGameData.........Version.....2.....GUID.!...EDFDB166436D8EA3B0072F9058F44B08.`

**Comment by Braste** [comment]
Forgett my comment about the .mod file. It is because of the .modbranche file in the folder.

I don't know, why it works with "normal" mods, but when this file is present in the map extension folder, the server does not load. I renamed the .modbranche file to modbranche.info and it works without problems.

line 1277 and 1324: `if [ \( ! -f "$moddestdir/modbranch.info" \) ] || [ "$(<"$moddestdir/modbranch.info")" != "$modbranch" ]; then`

line 1428: `echo "$modbranch" >"$moddestdir/modbranch.info"`

**Comment by klightspeed** [comment]
The "How the .mod file should look" suggests that the mod in question lists multiple maps, while all of the mods I had seen until now only had one map.  A commit I have added to 1.6-dev.unstable should fix that issue.

**Comment by Braste** [comment]
This is a map extension, so it can have multiple sublevels and the .mod file is from the windows client, so ark creates it this way. But as i said, it is the .modbranch file. When it is present, the server can not load map extensions with more than one sublevel. If it is renamed to modbranche.info, the server can load the extension (Tested with data from Pull request #472)

**Comment by klightspeed** [comment]
1.6-dev should resolve this.
