### ISSUE TITLE
crontab automation 

### ISSUE THREAD

**Issue by TOXid** [FezVrasta/ark-server-tools#473]
Help me to do right configuration crontab job for: 
1. check server status and restart if it down
2. check for server update and warn players if it needs restart for update.
In LinuxGameServermanager I use this:

```
*/15 * * * * su - arkserver -c '/home/arkserver/arkserver monitor' > /dev/null $
*/120 * * * * su - arkserver -c '/home/arkserver/arkserver update' > /dev/null $
```

What I need write for ark-server-tools? It's realy not clear in readme how to use daemon in cronjob...

I suppose about something like this: 

```
*/15 * * * * su - steam -c '/usr/local/bin/arkmanager status' > /dev/null $
*/120 * * * * su - steam -c '/usr/local/bin/arkmanager updatate --warn' > /dev/null $
```

Any system configuration need if this crontab jobs are right?

**Comment by Lihis** [comment]
To answer question 2., I wrote a script which can do that, and it also can send email for you if there is update available and after update have been done, after update monitors server and if server is not up in 10 minutes sends email that server is not running. I have been busy sometime and have not kept my eys so closely the arkmanager so some of the my script functionality may be available through arkmanager already. Grab my script from https://github.com/Lihis/arkwrapper

**Comment by juergen963** [comment]
Your cron shoud work, if you correct your typo error...
*/120 * * * * su - steam -c '/usr/local/bin/arkmanager upda**tat**e --warn' > /dev/null $
replace it with update.

I put the following into a script which is run by cron once a night:
date +'%Y-%m-%d-%H:%M:%S' >> /home/steam/ark-update.log
/usr/local/bin/arkmanager status >> /home/steam/ark-update.log
/usr/local/bin/arkmanager update --safe >> /home/steam/ark-update.log
