### ISSUE TITLE
-- warn result "Server received, But no response!!"

### ISSUE THREAD

**Issue by TOXid** [FezVrasta/ark-server-tools#474]
When use stop with --warn argument recieve:

```
This ARK server will shutdown for an update in 1 minutes
Server received, But no response!!
```

I have seen broadcast message ingame, but server not stopping. 
Message shown only few seconds, how to increase the time?

Without online players recieved:

```
This ARK server will shutdown for an update in 1 minutes
Server received, But no response!!

Nobody is connected.  Shutting down immediately
Stopping server...
The server has been stopped
```

**Comment by klightspeed** [comment]
The `--warn` currently assumes you want at least 2 minutes warning.

With your setup above, it should have broadcast:
0:00:  This ARK server will shutdown for an update in 1 minutes
0:30:  This ARK server will shutdown for an update in 90 seconds
1:00:  This ARK server will shutdown for an update in 60 seconds
1:15:  This ARK server will shutdown for an update in 45 seconds
1:30:  This ARK server will shutdown for an update in 30 seconds
1:40:  This ARK server will shutdown for an update in 20 seconds
1:45:  This ARK server will shutdown for an update in 15 seconds
1:50:  This ARK server will shutdown for an update in 10 seconds
1:55:  This ARK server will shutdown for an update in 5 seconds
2:00:  Connection Lost

**Comment by TOXid** [comment]
Default it was 60 minutes and:
```
This ARK server will shutdown for an update in 60 minutes
Server received, But no response!!
```
and only one broadcast about 60 minutes and no any other actions...

**Comment by klightspeed** [comment]
So, with the "One broadcast about 60 minutes", did the script continue running after the broadcast, or did it exit?

**Comment by klightspeed** [comment]
Are you still having problems with this?  Does 1.6-dev fix it?
