### ISSUE TITLE
process arkmanager keeps duplicating himself

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#475]
Hi, 

i don't know why but the arkmanager process keeps duplicating using more and more cpu

![capture](https://cloud.githubusercontent.com/assets/13471860/15100780/cbb9b6c6-157d-11e6-8cd2-4d886629a8c8.JPG)

**Comment by klightspeed** [comment]
What does the following command show:
```
ps -HF
```

**Comment by arkfrancegaming** [comment]
i've tried to restart the dedicated but it does the same thing
![2](https://cloud.githubusercontent.com/assets/13471860/15105487/55fb4400-15c2-11e6-9034-7eb2df50372a.JPG)

**Comment by klightspeed** [comment]
Sorry, try `ps -AHF | grep 'arkmanager'`

**Comment by arkfrancegaming** [comment]
![3](https://cloud.githubusercontent.com/assets/13471860/15105596/3b671f1e-15c3-11e6-83fb-e461d54b3d2c.JPG)

It might be due at the useconfig over that it doesn't existe anymore but still in my crontab

**Comment by klightspeed** [comment]
To kill all of those processes, try:

```
kill $(ps -A -o pid,args | sed -n 's|^ *\([0-9][0-9]*\) /bin/bash /usr/local/bin/arkmanager useconfig over .*|\1|p')
```

**Comment by arkfrancegaming** [comment]
ok done i'm rebooting the dedicated and go back to you :) Thanks

Just one question, is this still in developpement ? https://github.com/FezVrasta/ark-server-tools/issues/446

**Comment by arkfrancegaming** [comment]
same thing the arkmanager auto launch
![3](https://cloud.githubusercontent.com/assets/13471860/15107454/26922b9e-15d0-11e6-82e4-b57f5250bcf8.JPG)
![capture](https://cloud.githubusercontent.com/assets/13471860/15107483/4aab3584-15d0-11e6-9afa-1d9e1e9870d7.JPG)

**Comment by klightspeed** [comment]
What are the common ancestors of those processes?

**Comment by arkfrancegaming** [comment]
![capture](https://cloud.githubusercontent.com/assets/13471860/15108391/f865f100-15d5-11e6-965a-22e0badb2569.JPG)

Seems to work again, i think it was related to the crontab

**Comment by arkfrancegaming** [comment]
About https://github.com/FezVrasta/ark-server-tools/issues/446 anything yet ? @klightspeed
