### ISSUE TITLE
Mai 16 12:32:51 xxx.xxx arkmanager.init[807]: /usr/local/libexec/arkmanager/arkmanager.init: Zeile 5: /usr/bin/arkmanager: Datei oder Verzeichnis nicht gefunden

### ISSUE THREAD

**Issue by Lenny-Hai** [FezVrasta/ark-server-tools#479]
Version 1.6-dev.unstable
Output of journalctl while try to start via systemctl
In /usr/local/libexec/arkmanager/arkmanager.init the Path of the Daemon is wrong. In my case it shoud be /usr/local/bin/arkmanager.

Bye Sven

**Comment by klightspeed** [comment]
Did you use the installer to install arkmanager?  install.sh should have updated the DAEMON variable in arkmanager.init

**Comment by Lenny-Hai** [comment]
Yes, id did.
I also reinstalled it... same issue.


Am 16.05.2016 um 23:21 schrieb Ben Peddell:

**Comment by klightspeed** [comment]
This should be fixed in 1.6-dev
