### ISSUE TITLE
Cron autoupdate cancellation

### ISSUE THREAD

**Issue by Uskaanax** [FezVrasta/ark-server-tools#481]
I checked the documentation and there's no way to cancel a _update_ that's been initiated? I have that command set to check hourly due to all the updates of late and a player wanted to delay while they were doing a dino train as a result of the biome changes coming. Sadly, I don't think that's possible, according to what I've read. Maybe I missed it? It is late at night and I'm tired so it's entirely possible.

**Comment by klightspeed** [comment]
The `cancelshutdown` should cancel an update that is in the warning stage.
