### ISSUE TITLE
New warn message

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#485]
Hey, 

is that correct ? 

msgReasonUpdateMod="Le serveur va redemarrer dans %d minutes pour mettre a jour le mod {modnamesupdate}"

**Comment by klightspeed** [comment]
There is a typo in the documentation - it should be `{modnamesupdated}`, not `{modnamesupdate}`

At the moment, it would need something like (I don't speak French, so the grammar may be off):

```
msgWarnReason="Le serveur redemarrera dans {time} {reason}"
msgTimeMinutes="{minutes} minutes"
msgTimeSeconds="{seconds} secondes"
msgReasonUpdateMod="pour mettre a jour le mod {modnamesupdated}"
msgReasonUpdateApp="pour mettre a jour le serveur"
msgReasonUpdateAppMod="pour mettre a jour le serveur et le mod {modnamesupdated}"
msgReasonRestart=""
msgReasonShutdown="pour l'entretien"
```

I have pushed an update to 1.6-dev.unstable that allows the `{time}` replacement string to appear in `msgReason*`, and to fix the typo in the documentation.

Once this has been merged, you will be able to use something like:
```
msgWarnReason="{reason}"
msgTimeMinutes="{minutes} minutes"
msgTimeSeconds="{seconds} secondes"
msgReasonUpdateMod="Le serveur redemarrera dans {time} pour mettre a jour le mod {modnamesupdated}"
msgReasonUpdateApp="Le serveur redemarrera dans {time} pour mettre a jour le serveur"
msgReasonUpdateAppMod="Le serveur redemarrera dans {time} pour mettre a jour le serveur et le mod {modnamesupdated}"
msgReasonRestart="Le serveur redemarrera dans {time}"
msgReasonShutdown="Le serveur arretera dans {time}"

```

**Comment by arkfrancegaming** [comment]
Thanks,

msgWarnReason="Le serveur redemarrera dans {time} {reason}"

The {time} will display minutes and seconds ?

**Comment by arkfrancegaming** [comment]
By the way what's the difference between msgReasonUpdateMod and msgReasonUpdateAppMod ?

Thanks

**Comment by klightspeed** [comment]
`{time}` is replaced by `msgTimeMinutes` (**x minutes**) when there are 2 or more minutes remaining, and `msgTimeSeconds` (**x seconds**) when there are less than 120 seconds remaining.

`msgReasonUpdateApp` is used when the app 376030 is updated but no mods are updated.
`msgReasonUpdateMod` is used when one or more mods are updated but app 376030 is not updated.
`msgReasonUpdateAppMod` is used when the app 376030 is updated and one or more mods are updated.

**Comment by arkfrancegaming** [comment]
Ok great job,

that's my warn messages 

# Update warning messages

msgWarnReason="Le serveur va redemarrer dans {time} pour {reason}"
msgTimeMinutes="{minutes} minutes"
msgTimeSeconds="{seconds} secondes"
msgReasonUpdateMod="pour mettre a jour le mod {modnamesupdated}"
msgReasonUpdateApp="pour faire la mise a jour de ARK dans (Reboot for ARK update) %d minutes. Les modifications sont disponibles sur notre site http://arkfrancegaming.com/. IL Y A UNE SAVE ET CELA NE POSE PAS DE PROBLEME POUR LE TAMING, AUGMENTEZ JUSTE LA TORPEUR"
msgReasonUpdateAppMod="pour mettre a jour le serveur et le mod {modnamesupdated}"
msgReasonRestart="modifier des parametres"
msgReasonShutdown="une mise a jour de la machine, il y en a pour 25 min en tout"

**Comment by klightspeed** [comment]
That will print:

For an app update (i.e. where the ARK server needs an update but none of the mods need to be updated):
 - Le serveur va redemarrer dans 5 minutes pour pour faire la mise a jour de ARK dans (Reboot for ARK update) %d minutes. Les modifications sont disponibles sur notre site http://arkfrancegaming.com/. IL Y A UNE SAVE ET CELA NE POSE PAS DE PROBLEME POUR LE TAMING, AUGMENTEZ JUSTE LA TORPEUR

For a mod update (i.e. where one or more mods need to be update but the ARK server does not need to be updated):
 - Le serveur va redemarrer dans 5 minutes pour pour mettre a jour le mod GateMod

For a mod and app update (i.e. where the ARK server needs an update and one or more mods need an update):
 - Le serveur va redemarrer dans 5 minutes pour pour mettre a jour le serveur et le mod GateMod

Shutdown:
 - Le serveur va redemarrer dans 5 minutes pour une mise a jour de la machine, il y en a pour 25 min en tout

Restart:
 - Le serveur va redemarrer dans 5 minutes pour modifier des parametres

**Comment by arkfrancegaming** [comment]
Epic :+1: 

Thanks for all :)
