### ISSUE TITLE
Broadcast message issue

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#487]
Hi,

i've got a broadcast message issue

arkmanager useconfig pve broadcast le nouveau ARK diggest avec toutes les prochaines nouveautés disponible sur notre site
Running command 'broadcast' for instance 'pve'
Server received, But no response!!

Running command 'nouveau' for instance 'pve'
arkmanager v1.6: unknown command 'nouveau' specifiedUsage: arkmanager [Commands]

**Comment by klightspeed** [comment]
The argument to the broadcast command needs to be quoted.  Also note that ARK doesn't understand characters with accents (i.e. characters with character codes greater than 127 or characters that would need to be UTF-8 encoded).
