### ISSUE TITLE
Warn command false

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#489]
i've got the wrong message when i do 

steam@arkfrancegaming:/root$ arkmanager useconfig pve restart --warn
Running command 'restart' for instance 'pve'
Le serveur va redemarrer dans 5 minutes pour une mise a jour de la machine, il y en a pour 25 min en tout

msgWarnReason="Le serveur va redemarrer dans {time} pour {reason}"
msgTimeMinutes="{minutes} minutes"
msgTimeSeconds="{seconds} secondes"
msgReasonUpdateMod="pour mettre a jour le mod {modnamesupdated}"
msgReasonUpdateApp="pour faire la mise a jour de ARK dans (Reboot for ARK update) %d minutes. Les modifications sont disponibles sur notre site http://arkfrancegaming.com/. IL Y A UNE SAVE ET CELA NE POSE PAS DE PROBLEME POUR LE TAMING, AUGMENTEZ JUSTE LA TORPEUR"
msgReasonUpdateAppMod="pour mettre a jour le serveur et le mod {modnamesupdated}"
msgReasonRestart="modifier des parametres"
msgReasonShutdown="une mise a jour de la machine, il y en a pour 25 min en tout"

Got the shutdown instead of the restart

**Comment by klightspeed** [comment]
ca3ff1e should fix this.

**Comment by arkfrancegaming** [comment]
Also : 

steam@ns3013274:/root$ arkmanager useconfig centpvp status
Running command 'status' for instance 'centpvp'
 Server running:   Yes
 Server listening:   Yes
Server Name: ARK FRANCE OFFICIEL - PvP x10 [ANTI RAID OFF] - (v241.5)
Players: 122 / 70
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/149.202.65.50:27017
 Server version:   1139842

players display pb

**Comment by klightspeed** [comment]
`arkmanager status` only reports the results of the server query - the same query used by ARKservers.net

I don't know why the server would have reported that 122 players were connected, unless that is how many were trying to connect.
