### ISSUE TITLE
bug with ark_ServerPassword

### ISSUE THREAD

**Issue by Sispheor** [FezVrasta/ark-server-tools#49]
I leave empty the password but my server appear protected in steam list.

**Comment by FezVrasta** [comment]
What if you comment out the variable?

**Comment by Sispheor** [comment]
It's the same. With or without the variable.
And if I check the process when the server is running I can see the password isn't including. 
```
ps aux |grep Shooter
steam     1544 55.6  2.6 481240 164192 pts/1   Rl   22:50   0:05 /data/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?MaxPlayers=70?Port=7777?QueryPort=27016?ServerAdminPassword=keyboardcat?SessionName=FRANCEtest?listen
````

Maybe the last launch has set a variable in a file somewhere. It's the same for you?

**Comment by FezVrasta** [comment]
Check the GameUserSettings.ini
