### ISSUE TITLE
SavedArks Directory is not writable

### ISSUE THREAD

**Issue by NLBlackEagle** [FezVrasta/ark-server-tools#490]
Hello forum users and/or devellopers. First of all I would like to thank you guys for the existance of ArkManager as it is a great tool, however I have encountered a issue while reinstalling arkmanager.

Since I was experiencing issues with ArkManager I decided to completely remove steamcmd aswell as arkmanager in the following steps:

1) arkmanager uninstall-tools
2) manually remove /var/log/arktools & /etc/arkmanager
3) manually removed the whole steam folder using the rm command
4) installed steamcmd using this guide: http://danielgibbs.co.uk/2014/02/steamcmd/
5) downloaded arkmanager as su root
5) installed arkmanager tools as su steam following this guide: https://github.com/FezVrasta/ark-server-tools

I have double checked the iptables, users & group aswell as file permissions.

This is the error:
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail

thanks for your help in advance :)

**Comment by klightspeed** [comment]
This means that the Saved ARKs directory either doesn't exist or isn't writable.  If you have never started ARK, then this is normal, and can be ignored, as the ARK server will create the SavedArks directory on startup.

**Comment by NLBlackEagle** [comment]
@klightspeed Thanks for the help, it works at the moment! I'm currently dealing with a new issue though but I'll make a new topic for that.
