### ISSUE TITLE
usr/local/bin/arkmanager: line 509: lsof: command not found

### ISSUE THREAD

**Issue by spitfire1081** [FezVrasta/ark-server-tools#493]
Please, what is this error? Somebody could pls help?

**Comment by klightspeed** [comment]
Is `lsof` installed?

What is the output of `which lsof`

**Comment by spitfire1081** [comment]
I just folowed the tutorial in the main page, i didn't install anything called lsof... can you teach me how to do that?

**Comment by klightspeed** [comment]
Debian / Ubuntu: `apt-get install lsof`
CentOS / Fedora: `yum install lsof`
SUSE: `zypper install lsof`
Gentoo / Funtoo: `emerge lsof`

**Comment by spitfire1081** [comment]
Thank you. Now that error is vanished.
but I got a new one...

Running command 'status' for instance 'main'
 Server running:   Yes
 Server listening:   No
 Server version:   1139842

How do I make the server listen???

**Comment by klightspeed** [comment]
How long ago did you start the server?  The ARK server takes several minutes to start.

**Comment by spitfire1081** [comment]
About 4 minutes

**Comment by klightspeed** [comment]
You can watch the status (assuming you did a normal install) by running:
```
tail -f /var/log/arktools/arkserver.log
```

**Comment by spitfire1081** [comment]
I got this:

/usr/local/bin/arkmanager: line 645: ulimit: open files: cannot modify limit: Operation not permitted
03:01:11: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?GameModIds=538986229\,612504284\?MaxPlayers=50\?Port=7777\?QueryPort=27015\?ServerAdminPassword=C3f09@dm\?ServerPassword=allright\?SessionName=TESTE\?listen
03:01:11: Server PID: 32003
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

**Comment by klightspeed** [comment]
When the server has finished starting, you should get:
```
03:xx:xx: server is up
```

**Comment by spitfire1081** [comment]
What should be wrong?
What setting control listening the server?

**Comment by klightspeed** [comment]
Question: how much RAM do you have?  
The ARK server requires at least 4GB of RAM.

If you have 2GB of RAM and 4GB of swap, the server may start, but it will take longer and perform worse.

**Comment by spitfire1081** [comment]
My server has 20GB of ram and 8 processors running. I was running it without arkmanager since january 1st, but updating the mods were terrible than a friend pointed me arkmanager.

Could a problem with the 2 .cfg files? there are only 2 i need to edit according to the tutorial in the main page...

**Comment by spitfire1081** [comment]
I run this command:

xxxx@xxxxxx:/home/steam$ sudo netstat -puln | grep ShooterGame
udp     3072      0 0.0.0.0:27015           0.0.0.0:*                           2179/ShooterGameSer

**Comment by spitfire1081** [comment]
My config:

# config environment
arkserverroot="/home/steam/ARK"                                     # path of your ARK server files (default ~/ARK)

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheCenter"                                               # server map (default TheIsland)
#serverMapModId=""                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
#ark_RCONEnabled="True"                                              # Enable RCON Protocol
#ark_RCONPort="27016"                                                # RCON Port
ark_SessionName="TESTE"                                  # if your session name needs special characters please use the .ini instead
ark_Port="7777"                                                     # ARK server port (default 7778)
ark_QueryPort="27015"                                               # ARK query port (default 27015)
ark_ServerPassword="xxx"                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="xxxx"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="50"
ark_GameModIds="538986229,612504284"                     # Uncomment to specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures

**Comment by spitfire1081** [comment]
# config environment
arkserverroot="/home/steam/ARK"                                    

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheCenter"                                               
#serverMapModId=""                                         
#ark_TotalConversionMod="496735411"                                 
#ark_RCONEnabled="True"                                              
#ark_RCONPort="27016"                                               
ark_SessionName="TESTE"                                  
ark_Port="7777"                                                    
ark_QueryPort="27015"                                               
ark_ServerPassword="xxx"                                               
ark_ServerAdminPassword="xxx"                               
ark_MaxPlayers="50"
ark_GameModIds="538986229,612504284"                    
#ark_AltSaveDirectoryName="SotF"                                    

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            
#arkflag_DisableDeathSpectator=true                                 

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures

**Comment by klightspeed** [comment]
Looking at the commandline in https://github.com/FezVrasta/ark-server-tools/issues/493#issuecomment-222583171, you will want to obfuscate the `ServerAdminPassword` above, and if it's your real password, you will need to change it.

I don't see any issues with the above config.

**Comment by spitfire1081** [comment]
This is not the real password.
If there's nothing wrong with the config, why the server is not listening?

**Comment by klightspeed** [comment]
Your log shows:
<pre>
03:01:11: Server PID: <b>32003</b>
</pre>

Your netstat shows:
<pre>
udp 3072 0 0.0.0.0:27015 0.0.0.0:* <b>2179</b>/ShooterGameSer
</pre>

That means that arkmanager started the server as PID 32003, and 20 minutes later the server process had a different PID.

If you look in `/var/log/arktools/arkserver.log`, do you find a line `Server PID: 2179`, and if so are there any errors above that line?

**Comment by spitfire1081** [comment]
03:01:11: start
/usr/local/bin/arkmanager: line 645: ulimit: open files: cannot modify limit: Operation not permitted
03:01:11: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?GameModIds=538986229\,612504284\?MaxPlayers=50\?Port=7777\?QueryPort=27015\?ServerAdminPassword=C3f09@dm\?ServerPassword=allright\?SessionName=TESTE\?listen
03:01:11: Server PID: 32003
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager: line 651: 32003 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
03:13:52: Bad PID ''; expected '32003'
03:13:52: exited with status 0
03:15:57: start
/usr/local/bin/arkmanager: line 645: ulimit: open files: cannot modify limit: Operation not permitted
03:15:57: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?GameModIds=538986229\,612504284\?MaxPlayers=50\?Port=7777\?QueryPort=27015\?ServerAdminPassword=C3f09@dm\?ServerPassword=allright\?SessionName=TESTE\?listen
03:15:57: Server PID: 1503
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Using binned.
4.5.1-0+UE4 7038 3077 402 5
CtrlCHandler: Signal=2
CtrlCHandler: Signal=2
/usr/local/bin/arkmanager: line 651:  1503 Aborted                 "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
03:18:14: Bad PID ''; expected '1503'
03:18:14: exited with status 0
03:23:18: start
/usr/local/bin/arkmanager: line 645: ulimit: open files: cannot modify limit: Operation not permitted
03:23:18: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?GameModIds=538986229\,612504284\?MaxPlayers=50\?Port=7777\?QueryPort=27015\?ServerAdminPassword=C3f09@dm\?ServerPassword=allright\?SessionName=TESTE\?listen
03:23:18: Server PID: 2179
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager: line 651:  2179 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
03:31:09: Bad PID ''; expected '2179'
03:31:09: exited with status 0
03:31:26: start
/usr/local/bin/arkmanager: line 645: ulimit: open files: cannot modify limit: Operation not permitted
03:31:26: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?GameModIds=538986229\,612504284\?MaxPlayers=50\?Port=7776\?QueryPort=27015\?ServerAdminPassword=C3f09@dm\?ServerPassword=allright\?SessionName=TESTE\?listen
03:31:26: Server PID: 3429
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager: line 651:  3429 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
03:38:07: Bad PID ''; expected '3429'
03:38:07: exited with status 0

**Comment by klightspeed** [comment]
If you run `dmesg`, are there any kernel errors around the time of those `Killed` messages?  `Killed` often means that the kernel killed the process, e.g. due to an out-of-memory condition.

**Comment by spitfire1081** [comment]
That's not memmory issue...
I can start the server if i download the server and start it with a command line
Some configuration in the script is preventing the server to be listened...

**Comment by klightspeed** [comment]
```
/usr/local/bin/arkmanager: line 651: 32003 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
/usr/local/bin/arkmanager: line 651:  2179 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
/usr/local/bin/arkmanager: line 651:  3429 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
```

Something is killing the server (with SIGKILL) before it can start listening.

Are you using the same commandline as above when testing the server without the script?

The commandline that is being used is:
```
/home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer "TheCenter?GameModIds=538986229,612504284?MaxPlayers=50?Port=7777?QueryPort=27015?ServerAdminPassword=C3f09@dm?ServerPassword=allright?SessionName=TESTE?listen"
```

**Comment by spitfire1081** [comment]
No, the command line i run is just simple:

#! /bin/bash
./ShooterGameServer TheCenter?listen?MaxPlayers=50 -server -log -UseBattlEye

**Comment by klightspeed** [comment]
In that case, try commenting out the following settings:
```
#ark_SessionName="TESTE"                                  
#ark_ServerPassword="xxx"                                               
#ark_ServerAdminPassword="xxx"                               
#ark_GameModIds="538986229,612504284"
```
and adding the following settings:
```
arkflag_server=true
arkflag_log=true
arkflag_UseBattlEye=true
```

i.e. `main.cfg` should look like:
```
# config environment
arkserverroot="/home/steam/ARK"                                    

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheCenter"                                               
#serverMapModId=""                                         
#ark_TotalConversionMod="496735411"                                 
#ark_RCONEnabled="True"                                              
#ark_RCONPort="27016"                                               
#ark_SessionName="TESTE"                                  
ark_Port="7777"                                                    
ark_QueryPort="27015"                                               
#ark_ServerPassword="xxx"                                               
#ark_ServerAdminPassword="xxx"                               
ark_MaxPlayers="50"
#ark_GameModIds="538986229,612504284"                    
#ark_AltSaveDirectoryName="SotF"                                    

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            
#arkflag_DisableDeathSpectator=true                                 
arkflag_server=true
arkflag_log=true
arkflag_UseBattlEye=true

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures
```

**Comment by spitfire1081** [comment]
Dont. Nothing different, still not listening.

I was checking all the logs, and i found some error messages during the installation:

Running command 'install' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
Installing ARK server ... /
Message from syslogd@arkterranova at May 31 12:02:13 ...
 ash_20160531120213_7.dmp[2936]: Finished uploading minidump (out-of-process): success = no
Message from syslogd@arkterranova at May 31 12:02:13 ...
 ash_20160531120213_7.dmp[2936]: error: libcurl.so: cannot open shared object file: No such file or directory
Message from syslogd@arkterranova at May 31 12:02:13 ...
 ash_20160531120213_7.dmp[2936]: file ''/tmp/dumps/crash_20160531120213_7.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such fil
e or directory''

Could this be related to the problem?

**Comment by spitfire1081** [comment]
I got the server to be listened. Finnally. Now I am trying to install mods. Still getting the errors:

Running command 'installmod' for instance 'main'
Downloading mod 538986229 ... /
Message from syslogd@arkterranova at May 31 12:26:50 ...
 ash_20160531122650_7.dmp[5070]: Finished uploading minidump (out-of-process): success = no
Message from syslogd@arkterranova at May 31 12:26:50 ...
 ash_20160531122650_7.dmp[5070]: error: libcurl.so: cannot open shared object file: No such file or directory
Message from syslogd@arkterranova at May 31 12:26:50 ...
 ash_20160531122650_7.dmp[5070]: file ''/tmp/dumps/crash_20160531122650_7.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such fil
e or directory''

But the files download. Any idea why the errors are poping like this?

**Comment by klightspeed** [comment]
That looks like Steam is crashing, and that the 32-bit version of libcurl isn't installed.  According to https://forums.gentoo.org/viewtopic-t-959784-start-0.html, setting `STEAM_RUNTIME=1` might work.

What distribution are you running?

**Comment by spitfire1081** [comment]
Debian 8
i just type that in the command input?
Or do I need to download something?

**Comment by klightspeed** [comment]
To install libcurl:
```
sudo apt-get install libcurl3:i386
```
To set STEAM_RUNTIME=1:
```
export STEAM_RUNTIME=1
```

**Comment by spitfire1081** [comment]
That fixed it. Thank you for your answers and for you patience.
One more question: if i want to install 22 mods, i need to run arkmanager install for each one of them, or i can install them in some sort of queue?

**Comment by klightspeed** [comment]
You could add the mods you want to `ark_GameModIds` in `main.cfg`, then run:
```
arkmanager update --update-mods
```

**Comment by spitfire1081** [comment]
Thank you again klinghtspeed.
You saved me with this tutorial.
This script is really a lifesaver, but as everything in linux it´s a bit trickier for begginers.
Thank you again.
