### ISSUE TITLE
Random Restarts

### ISSUE THREAD

**Issue by 6zeus6** [FezVrasta/ark-server-tools#494]
So the server is restarting at random times.
It seems like the server is crashing and then restarting.

ERROR:
Signal 11 caught.
/usr/local/bin/arkmanager: Zeile 651: 30340 Speicherzugriffsfehler  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"

18:47:38: Bad PID ''; expected '30340'
18:47:38: exited with status 0
18:47:38: restarting server

Server has no mods and 32GB RAM

**Comment by klightspeed** [comment]
Are there any errors above the `ERROR: Signal 11 caught` line?

If you take the `xx:xx:xx: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?...` line, does the server still occasionally crash when you run the command after `Running`?

**Comment by 6zeus6** [comment]
ARK01@x184:~$ tail -f /var/log/arktools/arkserver.log
Signal 11 caught.
/usr/local/bin/arkmanager: Zeile 651: 12221 Speicherzugriffsfehler  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
19:25:16: Bad PID ''; expected '12221'
19:25:16: exited with status 0
19:25:16: restarting server
19:25:16: Running /home/ARK01/Ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=127\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27015\?ServerAdminPassword=hulumulu\?ServerPassword\?SessionName=DinoSharks\?listen -log -server -servergamelog
19:25:16: Server PID: 22065
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
19:26:25: server is up

**Comment by klightspeed** [comment]
`tail` only prints the last 10 lines by default.

Try `tail -f -n 50 /var/log/arktools/arkserver.log`

**Comment by 6zeus6** [comment]
07:02:23: server is up
Signal 11 caught.
/usr/local/bin/arkmanager: Zeile 651: 27455 Speicherzugriffsfehler  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
18:59:31: Bad PID ''; expected '27455'
18:59:31: exited with status 0
18:59:31: restarting server
18:59:31: Running /home/ARK01/Ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=127\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27015\?ServerAdminPassword=hulumulu\?ServerPassword\?SessionName=DinoSharks\?listen -log -server -servergamelog
18:59:31: Server PID: 1737
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
19:00:44: server is up
Signal 11 caught.
/usr/local/bin/arkmanager: Zeile 651:  1737 Speicherzugriffsfehler  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
20:58:48: Bad PID ''; expected '1737'
20:58:48: exited with status 0
20:58:48: restarting server
20:58:48: Running /home/ARK01/Ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=127\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=27015\?ServerAdminPassword=hulumulu\?ServerPassword\?SessionName=DinoSharks\?listen -log -server -servergamelog
20:58:48: Server PID: 11278
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
21:00:07: server is up

**Comment by klightspeed** [comment]
A possible issue is that you should use different ports for the query port and RCON port.

Does the server still randomly crash when you run:
```
/home/ARK01/Ark/ShooterGame/Binaries/Linux/ShooterGameServer "TheIsland?MaxPlayers=127?Port=7777?QueryPort=27015?RCONEnabled=True?RCONPort=27015?ServerAdminPassword=hulumulu?ServerPassword?SessionName=DinoSharks?listen -log -server -servergamelog
```

**Comment by 6zeus6** [comment]
Is it possible when you change something at the config in the game.ini while the server is running the server will crash?

**Comment by klightspeed** [comment]
> Is it possible that the server will crash when you change something at the Game.ini while the server is running?

I don't know - you'd have to ask @StudioWildcard1.
