### ISSUE TITLE
restart without saveworld

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#495]
Hi, is it possible to restart without any saveworld to make a wipe for exemple

**Comment by klightspeed** [comment]
There isn't currently a command to do a non-graceful shutdown of the server.  The standard shutdown uses `SIGINT`, which when caught by the server causes a graceful shutdown.

If you want to go back to the last save, then you'd probably send a `SIGKILL` to the server - i.e. 
```
killall -KILL /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer
```
We we can add e.g. a `--kill` to `stop` and `restart` to do that.

If you want a full wipe, then you'd stop the server, remove the `SavedArks` directory, and restart the server.  We can add e.g. a `--wipe` to `stop` and `restart` to do that.

**Comment by arkfrancegaming** [comment]
Yep or maybe an arkmanager restart --warn --nosave

then remove the dosave line

**Comment by klightspeed** [comment]
`doSaveWorld` is only called if `--saveworld` is used.

**Comment by arkfrancegaming** [comment]
it also does when you arkmanager restart, it saves world before restarting
