### ISSUE TITLE
TheCenter, how to add the DLC?

### ISSUE THREAD

**Issue by NLBlackEagle** [FezVrasta/ark-server-tools#497]
After googeling and searching through github for anwsers I found myself aloss, how can I add TheCenter as the map? Installing the mod itself gives a error and using:

serverMap="TheCenter" instead of serverMap="TheIsland" will result in well, nothing. I've waited 24 hours for the server to start up which ended in the server not being able to listen.

Could anyone help me with this issue? Thanks in advance!

**Comment by NLBlackEagle** [comment]
Oh wait, somehow it does work now, will need to update my client to confirm this.

**Comment by klightspeed** [comment]
Yes, the saved world needs to be removed when adding or removing map mods or total conversion mods, as well as some game mods.

**Comment by NLBlackEagle** [comment]
Everything confirmed working, thanks for all the help!
