### ISSUE TITLE
Broadcast

### ISSUE THREAD

**Issue by spitfire1081** [FezVrasta/ark-server-tools#498]
I can´t use the command BROADCAST. Don´t know what I am doing wrong.
I am giving the command like this:

$arkmanager broadcast this is my message

What am I doing wrong?

**Comment by spitfire1081** [comment]
Tried with a single word msg, got this:

$ arkmanager broadcast teste
Running command 'broadcast' for instance 'main'
Server received, But no response!!

This is important for me because the players aren´t receiving the WARN messages about restarts and updates

**Comment by klightspeed** [comment]
The message needs to be quoted - e.g:
```
arkmanager broadcast "this is my message"
```

> Running command 'broadcast' for instance 'main'
> Server received, But no response!!

This `Server received, But no response!!` message is returned by the ARK server when an RCON command (such as `broadcast`) returns nothing.  In 1.6-dev.unstable, I have fixed the code that converts this response to `Command processed`.

**Comment by spitfire1081** [comment]
well, i tried to quote the msg, but stil get

Server received, But no response!!

**Comment by klightspeed** [comment]
That message is normal.  It means that the server processed the message, and because the `broadcast` command does not return anything, the server returns `Server received, But no response!!`.  1.6-dev.unstable checks for this response, and when the server returns this response, the script converts it into `Command processed`.

**Comment by spitfire1081** [comment]
Ok. Thank you for your answers. Everything is fine. The script is mandatory for my servers now. Can´t even remember how to manage things without it. Great work.
