### ISSUE TITLE
Running Mods

### ISSUE THREAD

**Issue by Vindomire** [FezVrasta/ark-server-tools#499]
Install seems to download and copy fine however when i start the server the mods are not run, i know i can in the arkmanager configs set the mods that run but my users wont have access to these configs, how do i alter the command line to run the mod IDs without those main configs having to be altered when a user wants a new mod or drop an old one?

**Comment by klightspeed** [comment]
So you have multiple users managing their own installs of the ARK server?  They can put the mods to be enabled into `~/.config/arkmanager/instances/main.cfg` (assuming the instance name is `main`)

**Comment by Vindomire** [comment]
arkmanager installed to etc/arkmanager they dont have access to their instance CFGs so i guess i have to give them that access? seems like a lot of directory changing for other users to have to modify the ini there.

**Comment by klightspeed** [comment]
arkmanager will read instance configs from either `/etc/arkmanager/instances/${instance}.cfg` or from `${HOME}/.config/arkmanager/instances/${instance}.cfg`

**Comment by Vindomire** [comment]
that arkmanager folder doesnt exist on my system in home/steam/.config

**Comment by klightspeed** [comment]
When you say "my users", do you mean users who will manage their own ARK instances, or do you mean users who have the ability to set options on a single instance?

**Comment by Vindomire** [comment]
im in testing right now, im debating moving my ark servers from windows server 2008 r2 to linux. i have a few friends that host on my machine. So what im trying to make happen is make them a user and allow them to shell in and run the arkmanager commands for their own servers seperate from the others. so there will likely be 3 - 4 user accounts that need to run their own instances of an ark server.

**Comment by klightspeed** [comment]
`arkmanager` support loading per-user configs, with `$HOME/.arkmanager.cfg` containing the common options (such as SteamCMD path), and `$HOME/.config/arkmanager/instances` containing the instance configs.

For each user (replacing `$USERNAME` with the username)
```
su $USERNAME
mkdir -p "$HOME/.config/arkmanager/instances"
cp "/etc/arkmanager/instances/main.cfg" "$HOME/.config/arkmanager/instances/main.cfg"
sed -i 's@/home/steam/@$HOME/@' "$HOME/.config/arkmanager/instances/main.cfg"
cp "/etc/arkmanager/arkmanager.cfg" "$HOME/.arkmanager.cfg"
sed -i 's@/home/steam/@$HOME/@' "$HOME/.arkmanager.cfg"
```

To automatically start the servers, one can add the following line for each user to /etc/crontab, replacing `$user` with the username:
```
@reboot $user sleep 300 && /usr/local/bin/arkmanager start @main
```

**Comment by Vindomire** [comment]
Thanks a lot for your time and patience, i will look into this when i build the new server later this week and give it a try.

**Comment by klightspeed** [comment]
Is this still an issue?
