### ISSUE TITLE
--update-mods --downloadonly  then update will re-download the mods

### ISSUE THREAD

**Issue by rob-bb** [FezVrasta/ark-server-tools#500]
Hi, how do I do update the server and the mods quickly, I thought doing 'update --update-mods --downloadonly' and then then 'update --updatemods' would work but it re-downloads the mods the second time. 

Here is some trimmed console output.

> Updating...
> 
> Running command 'update' for instance 'main'
> Downloading mod 489596581 ... Mod 489596581 downloaded
> 
> --cut--
> 
> Downloading mod 679529026 ... Mod 679529026 downloaded
> Mod update downloaded
> Not applying update - download-only enabled
> 
> Updating...
> 
> Running command 'update' for instance 'main'
> Downloading mod 489596581 ... Mod 489596581 downloaded
> 
> --cut--
> 
> Downloading mod 679529026 ... Mod 679529026 downloaded
> The server is already stopped
> Updating mod 539464369
> Copying files to /home/steam/ARK/ShooterGame/Content/Mods/539464369
> -e
> Starting...
> 

And here is the script I am running.
```
#!/bin/sh

echo -e "\nBackup and Update...\n"

arkmanager update --downloadonly
arkmanager update --update-mods --downloadonly

arkmanager broadcast "The server will be shutting down for backup and update in 5 minutes"
sleep 60;
arkmanager broadcast "The server will be shutting down for backup and update in 4 minutes"
sleep 60;
arkmanager broadcast "The server will be shutting down for backup and update in 3 minutes"
sleep 60;
arkmanager broadcast "The server will be shutting down for backup and update in 2 minutes"
sleep 60;
arkmanager broadcast "The server will be shutting down for backup and update in 1 minute"
sleep 30;
arkmanager broadcast "The server will be shutting down for backup and update in 30 seconds"
sleep 10;
arkmanager broadcast "The server will be shutting down for backup and update in 20 seconds"
sleep 10;
arkmanager broadcast "The server will be shutting down for backup and update in 10 seconds"
sleep 10;
arkmanager broadcast "The server is shutting down for backup and update - online again in 5 minutes"
sleep 10;

arkmanager broadcast "Saving the Ark"
echo -e "\nSaving the world...\n"
arkmanager saveworld;
sleep 1;
echo -e "\nStopping...\n"
arkmanager broadcast "Stopping the Ark"
#arkmanager stop;
sleep 2;
echo -e "\nUpdating...\n"
arkmanager update --update-mods
sleep 2;
echo -e "\nStarting...\n"
arkmanager start;
sleep 20;

# Give the server time to get started
sleep 20;

# Now increase the server cpu and disk priority
sudo renice -n -3 -p `pgrep -f ShooterGame | tail -n1`; 
sleep 2;
sudo ionice -c2 -n0 -p `pgrep -f ShooterGame | tail -n1`;

# Now make rotating backups 
nice -n 19 ionice -c 3  rsync -a --delete-after --exclude-from=/home/steam/rsync-ignore.txt /home/steam/ARK/ShooterGame/Saved /Backups/ARK/

#Todays date in ISO-8601 format:
DAY0=`date -I`
 
#Yesterdays date in ISO-8601 format:
DAY1=`date -I -d "1 day ago"`
 
#The source directory:
SRC="/Backups/ARK/Saved"
 
#The target directory:
TRG="/Backups/ARK/$DAY0"
 
#The link destination directory:
LNK="/Backups/ARK/$DAY1"
 
#The rsync options:
OPT="-avh --delete --link-dest=$LNK"
 
#Execute the backup
nice -n 19 ionice -c 3 rsync $OPT $SRC $TRG

#29 days ago in ISO-8601 format
DAY7=`date -I -d "7 days ago"`
 
#Delete the backup from 7 days ago, if it exists
if [ -d /Backups/ARK/$DAY7 ]
then
nice -n 19 ionice -c 3 rm /Backups/ARK/$DAY7
fi



```

**Comment by klightspeed** [comment]
`arkmanager update --update-mods --warn --backup` will do most of what you're doing here.

I have added a `--no-download` option to `update` in 1.6-dev.unstable

**Comment by rob-bb** [comment]
What I was looking for was a way to download the mods to staging area like the server update can do.  Then update from the staging dir.  Does this do that or am I misunderstanding what --downloadonly does?

**Comment by klightspeed** [comment]
The `--update-mods` option updates mods in addition to updating the application.  It first downloads the mod from the workshop to the steamcmd workshop directory using `steamcmd +workshop_download_item` (steamcmd doesn't provide a way of determining what the latest version of a mod is without downloading it).  Then if the `--downloadonly` option is not specified and any of the files in the steamcmd workshop directory (`$steamcmdroot/steamapps/workshop/content/$mod_appid/$modid`) are newer than those in the mod directory (`$arkserverroot/ShooterGame/Content/Mods/$modid`) then it extracts the mod to the mod directory.

The `--downloadonly` option just skips applying the updates to the server.

**Comment by rob-bb** [comment]
Hi, I am still a bit confused with this, is it possible to get arkmanager to download the mods to a staging directory before running the update --updatemods command.

Or can you tell me what happens when I run update --updatemods on a running server?  What I am trying to do is achieve as little downtime as possible while still keeping pace with mods and server updates and doing so via cron.

**Comment by klightspeed** [comment]
Assuming `arkStagingDir` is set:

`arkmanager update` does the following:

 - If the `--update-mods` option is specified, then it uses `steamcmd +workshop_download_item` to download the installed mods to `$steamcmdroot/steamapps/workshop/content`
 - Requests the info on the app from Steam (`steamcmd +app_info_print`)
 - Checks if the public depot BuildID matches the BuildID of the installed server
 - If the version doesn't match, then it uses `steamcmd +app_update` to download the app to a staging directory
 - If an app or mod update was required, and the `--downloadonly` option is not specified:
   - If the `--warn` option is specified, then it warns players on the server for the configured amount of time that the server is going down for an update
   - Shuts down the game server
   - If `--backup` is specified, then it performs a backup
   - If an app update was required, then it copies the updated files from the staging directory
   - If a mod update was required, then it extracts the required mods from `$steamcmdroot/steamapps/workshop/content` to `$arkserverroot/ShooterGame/Content/Mods`
   - Starts the server if it was running before the update

**Comment by rob-bb** [comment]
Thanks for explaining that.

**Comment by rob-bb** [comment]
or is there a force restart option that wont also do a needles update, if I read it correctly the --force will do an update regardless of if required or not?

**Comment by klightspeed** [comment]
Specifying `--force` will ignore the Build ID and always perform a `steamcmd +app_update`.

Specifying `--validate` will request `steamcmd` to validate the installed files.

Currently, one must specify `--stagingdir=` for them to work.
