### ISSUE TITLE
Update download interrupted

### ISSUE THREAD

**Issue by cronner** [FezVrasta/ark-server-tools#503]
Getting last hours:

Downloading ARK update ... Update download interrupted

with --verbose i can see it's stuck at:
Update state (0x61) downloading, progress: 79.27 (274934996 / 346819760)

plenty of hdd storage available

**Comment by klightspeed** [comment]
This appears to be a duplicate of #502

**Comment by klightspeed** [comment]
@cronner Is this resolved?

**Comment by cronner** [comment]
Yes I think it was Steam releated? seems to update fine again
