### ISSUE TITLE
Systemd timer for auto-update

### ISSUE THREAD

**Issue by OnigamiSama** [FezVrasta/ark-server-tools#504]
I try to setup a systemd timer to auto update and warn users every hours running arkupdate.sh in my ARK user home ( arkmanager update --warn ) I have two file 

arkupdate.timer : 

```
[Unit]
Description=Runs Ark Update every hour

[Timer]
# Time to wait after booting before we run first time
OnBootSec=10min
# Time between running each consecutive time
OnUnitActiveSec=1h
Unit=arkupdate.service

[Install]
WantedBy=multi-user.target
```

arkupdate.service : 

```
[Unit]
Description=ARK update Script

[Service]
User=gameserver
Type=simple
ExecStart=/home/gameserver/arkupdate.sh
```

But it look like it don't work as I have to run the update manually

**Comment by klightspeed** [comment]
You may wish to change the service `Type` from `simple` to `oneshot`.

The `WantedBy` in the `Install` section of the timer should probably be `timers.target`.

Also, I presume you know how to make an executable script?  It should have a shebang (e.g. `#!/bin/sh`) at the top, and be set executable.

**Comment by OnigamiSama** [comment]
@klightspeed my arkupdate.sh is


```
#!/bin/bash
# Ark Update Script
arkmanager update --warn
```

I have changed the WantedBy=multi-user.target to WantedBy=timers.target in arkupdate.timer

Now systemctl status arkupdate.service return an error

```
[gameserver@kaijuu ~]$ sudo systemctl status arkupdate.service
● arkupdate.service - ARK Server Update
   Loaded: loaded (/etc/systemd/system/arkupdate.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since jeu 2016-06-09 19:04:44 CEST; 9min ago
  Process: 10871 ExecStart=/home/gameserver/arkupdate.sh (code=exited, status=203/EXEC)
 Main PID: 10871 (code=exited, status=203/EXEC)

jun 09 19:04:44 kaijuu systemd[1]: Started ARK Server Update.
jun 09 19:04:44 kaijuu systemd[10871]: arkupdate.service: Failed at step EXEC spawning /home/gameserver/arkupdate.sh: Not a directory
jun 09 19:04:44 kaijuu systemd[1]: arkupdate.service: Main process exited, code=exited, status=203/EXEC
jun 09 19:04:44 kaijuu systemd[1]: arkupdate.service: Unit entered failed state.
jun 09 19:04:44 kaijuu systemd[1]: arkupdate.service: Failed with result 'exit-code'
```.

**Comment by klightspeed** [comment]
> ```
#!/bin/bash
# Ark Update Script
arkmanager update --warn
```

In arkupdate.sh, you will want to specify the absolute path to arkmanager, especially if it is in `/usr/local/bin` or `$HOME/bin`, as it's likely that neither of those will be in `$PATH` as passed by systemd.

> ```
jun 09 19:04:44 kaijuu systemd[10871]: arkupdate.service: Failed at step EXEC spawning /home/gameserver/arkupdate.sh: Not a directory
```

That suggests that one of `/home` or `/home/gameserver` is something other than either a directory or a symlink to a directory.  See http://man7.org/linux/man-pages/man2/execve.2.html#ERRORS - "Not a directory" is `ENOTDIR`

> ENOTDIR: A component of the path prefix of *filename* or a script or ELF interpreter is not a directory.

**Comment by OnigamiSama** [comment]
My arkmanager is in /usr/local/bin so I have modified my script to

```
#!/bin/bash
#Ark Update Script
/usr/local/bin/arkmanager update --warn
```

I'm absolutly sure that both /home and /home/gameserver are folders ^^
