### ISSUE TITLE
arkmanager command not found

### ISSUE THREAD

**Issue by MrYoshii** [FezVrasta/ark-server-tools#506]
hi i have installt arkmanager as described in readme but when I enter arkmanager install I get the error message arkmanager command not found

can someone help?

**Comment by klightspeed** [comment]
Does the output of `echo "$PATH"` contain `/usr/local/bin`?

**Comment by MrYoshiiLP** [comment]
here is the output of `echo "$PHATH"`  `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

**Comment by klightspeed** [comment]
Did you perform a normal install (i.e. specifying a username to install it) or a username (i.e. running as the user and specifying `--me`)?

**Comment by MrYoshii** [comment]
i installed it as root with this command `curl -sL http://git.io/vtf5N | sudo bash -s steam`

**Comment by klightspeed** [comment]
What is the output of `ls -l /usr/local/bin/arkmanager`?

**Comment by MrYoshii** [comment]
`ls: Zugriff auf '/usr/local/bin/arkmanager' nicht möglich: Datei oder Verzeichnis nicht gefunden
`

**Comment by klightspeed** [comment]
Were there any error messages when you ran `curl -sL http://git.io/vtf5N | sudo bash -s steam`?

**Comment by MrYoshii** [comment]
no it says installed successfully

**Comment by klightspeed** [comment]
Try running `curl -sL http://git.io/vtf5N | sudo bash -s -- steam master --verbose`

**Comment by MrYoshii** [comment]
`curl -sL http://git.io/vtf5N | sudo bash -s -- steam master --verbose
cp: reguläre Datei '/usr/local/bin/arkmanager' kann nicht angelegt werden: Datei oder Verzeichnis nicht gefunden
chmod: Zugriff auf '/usr/local/bin/arkmanager' nicht möglich: Datei oder Verzeichnis nicht gefunden
Ark server will now start on boot, if you want to remove this feature run the following line
systemctl disable arkmanager.service
A previous version of ARK Server Tools was detected in your system, your old configuration was not overwritten. You may need to manually update it.
A copy of the new configuration file was included in /etc/arkmanager. Make sure to review any changes and update your config accordingly!
WARNING: A previous version of ARK Server Tools was detected in your system, your old configuration was not overwritten. You may need to manually update it.
ARK Server Tools were correctly installed in your system inside the home directory of steam!
`

**Comment by klightspeed** [comment]
That sounds like `/usr/local/bin` doesn't exist.

Please try running `sudo mkdir /usr/local/bin` and running the above command again.

**Comment by MrYoshii** [comment]
thank that was the problem but if i change the Server name, port, slots nothing changes server name remains ark-server-tools

**Comment by klightspeed** [comment]
Changes to `main.cfg` do not take effect until you restart the server.

**Comment by MrYoshii** [comment]
the gameserver or the host server?

**Comment by klightspeed** [comment]
The gameserver.

**Comment by MrYoshii** [comment]
i have stopt the server change it start the server but nothing changes

**Comment by klightspeed** [comment]
Check that `/home/steam/.config/arkmanager/instances/main.cfg` doesn't exist.

**Comment by MrYoshii** [comment]
oh god thanks :)

**Comment by MrYoshii** [comment]
ok so now the GameUserSettings.ini overrides again when i copy my existing ini on the server and start it its gone and all the Multiplier are on stock values

**Comment by klightspeed** [comment]
The server removing GameUserSettings.ini and writing defaults to it suggests that it isn't valid.  Make sure it doesn't contain special characters - e.g. characters with accents.

**Comment by MrYoshii** [comment]
i have the exact same ini on my stock server without the arkmanager on it nothing overrides

**Comment by klightspeed** [comment]
So assuming your `arkserverroot` is `/home/steam/ARK`, then the file `GameUserSettings.ini` should be in `/home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini`

`head -n 1 /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini | od -a` should output something like:
```
0000000   [   /   S   c   r   i   p   t   /   S   h   o   o   t   e   r
0000020   G   a   m   e   .   S   h   o   o   t   e   r   G   a   m   e
0000040   U   s   e   r   S   e   t   t   i   n   g   s   ]  \n
0000056
```

Make sure it isn't something like:
```
0000000 357 277 276   [   /   S   c   r   i   p   t   /   S   h   o   o
0000020   t   e   r   G   a   m   e   .   S   h   o   o   t   e   r   G
0000040   a   m   e   U   s   e   r   S   e   t   t   i   n   g   s   ]
0000060  \n
0000061
```
or
```
0000000 376 377   [  \0   /  \0   S  \0   c  \0   r  \0   i  \0   p  \0
0000020   t  \0   /  \0   S  \0   h  \0   o  \0   o  \0   t  \0   e  \0
0000040   r  \0   G  \0   a  \0   m  \0   e  \0   .  \0   S  \0   h  \0
0000060   o  \0   o  \0   t  \0   e  \0   r  \0   G  \0   a  \0   m  \0
0000100   e  \0   U  \0   s  \0   e  \0   r  \0   S  \0   e  \0   t  \0
0000120   t  \0   i  \0   n  \0   g  \0   s  \0   ]  \0  \n  \0
0000136
```
or
```
0000000 376 377   [   /   S   c   r   i   p   t   /   S   h   o   o   t
0000020   e   r   G   a   m   e   .   S   h   o   o   t   e   r   G   a
0000040   m   e   U   s   e   r   S   e   t   t   i   n   g   s   ]  \n
0000060
```
The first means that it was saved as UTF-8, which the ARK: Survival Evolved server does not understand.

The second means that it is saved as UTF16, which one needs to be careful with when editing.

The third means that it was originally UTF-16, but then likely copied and pasted from the terminal, which removes the null '\0' bytes.

Also make sure that the following command does not output anything:
```
grep $'[\177-\377]' /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
```

The ARK: Survival Evolved server cannot handle special characters in the GameUserSettings.ini file unless it is UTF16 encoded.

**Comment by MrYoshii** [comment]
`head -n 1 /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini | od -a` :  `0000000   [   S   e   r   v   e   r   S   e   t   t   i   n   g   s   ]
0000020  nl
0000021
`
`grep $'[\177-\377]' /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini` : `root@Server:/home/steam# grep $'[\177-\377]' /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
grep: Ungültiges Sortierzeichen
`

**Comment by klightspeed** [comment]
Try:
```
LC_COLLATE=C grep $'[\177-\377]' /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini
```

**Comment by MrYoshii** [comment]
`LC_COLLATE=C grep $'[\177-\377]' /home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini` no output

**Comment by klightspeed** [comment]
Is this before or after it was overwritten by the server?

**Comment by MrYoshii** [comment]
before and after

**Comment by klightspeed** [comment]
With any passwords XXed out, what are the contents you are trying to put into `GameUserSettings.ini`?

**Comment by MrYoshii** [comment]
`[ServerSettings]
allowThirdPersonPlayer=1
AllowCaveBuildingPvE=1
alwaysNotifyPlayerJoined=1
alwaysNotifyPlayerLeft=1
bAllowFlyerCarryPvE=1
bDisableStructureDecayPvE=1
DayCycleSpeedScale=1.00000
DayTimeSpeedScale=1.00000
NightTimeSpeedScale=1.00000
DinoCharacterFoodDrainMultiplier=1.00000
DinoCharacterHealthRecoveryMultiplier=1.00000
DinoCharacterStaminaDrainMultiplier=1.00000
DinoCountMultiplier=1.00000
DinoDamageMultiplier=1.00000
DinoResistanceMultiplier=1.00000
globalVoiceChat=0
HarvestAmountMultiplier=2.00000
HarvestHealthMultiplier=1.00000
MaxStructuresInRange=6700
noTributeDownloads=0
PreventDownloadSurvivors=0
PreventDownloadItems=0
PreventDownloadDinos=0
PlayerCharacterFoodDrainMultiplier=1.00000
PlayerCharacterHealthRecoveryMultiplier=1.00000
PlayerCharacterStaminaDrainMultiplier=1.00000
PlayerCharacterWaterDrainMultiplier=1.00000
PlayerDamageMultiplier=1.00000
PlayerResistanceMultiplier=1.00000
proximityChat=0
ResourceNoReplenishRadiusPlayers=1.00000
ResourceNoReplenishRadiusStructures=1.00000
ResourcesRespawnPeriodMultiplier=1.00000
ServerAdminPassword=*****
ServerCrosshair=0
serverForceNoHud=0
serverHardcore=0
ServerPassword=
serverPVE=0
ShowMapPlayerLocation=1
StructureDamageMultiplier=1.00000
StructureResistanceMultiplier=1.00000
TamedDinoDamageMultiplier=1.00000
TamedDinoResistanceMultiplier=1.00000
TamingSpeedMultiplier=6.00000
XPMultiplier=5.00000
EnablePVPGamma=1
EnablePVEGamma=1
SpectatorPassword=
DifficultyOffset=0.50000
PvEStructureDecayPeriodMultiplier=1.00000
PvEStructureDecayDestructionPeriod=1.00000
Banlist="http://playark.com/banlist.txt"
PvPStructureDecay=0
DisableDinoDecayPvE=0
PvEDinoDecayPeriodMultiplier=1.00000
AdminLogging=0
MaxTamedDinos=8000
MaxNumbersofPlayersInTribe=2
BattleNumOfTribestoStartGame=2
TimeToCollapseROD=100
BattleAutoStartGameInterval=100
BattleSuddenDeathInterval=300
KickIdlePlayersPeriod=1800
PerPlatformMaxStructuresMultiplier=1.00000
StructureDamageRepairCooldown=180
bForceAllStructureLocking=1
AutoDestroyOldStructuresMultiplier=0.00000
bUseVSync=0
MaxPlatformSaddleStructureLimit=100
bPassiveDefensesDamageRiderlessDinos=1
RCONPort=27020
AutoSavePeriodMinutes=5
RCONServerGameLogBuffer=600
OverrideStructurePlatformPrevention=0
bPreventOfflinePvP=1
PreventOfflinePvPInterval=60.0
bPvPDinoDecay=1
bPvPStructureDecay=1
NewMaxStructuresInRange=6700
DisableImprintDinoBuff=1
AllowAnyoneBabyImprintCuddle=1
EnableExtraStructurePreventionVolumes=1
ShowFloatingDamageText=1
[/script/engine.gamesession]
MaxPlayers=127
[SessionSettings]
SessionName=!![EU/GER]!!HanfBude/10x Harvest/20x XP/40x Taming/hostet by DarkSide-Gaming
[MessageOfTheDay]
Duration=30
Message=Need an Admin? (GER/AT)TeamSpeak3: darkside-gaming.at
`

**Comment by klightspeed** [comment]
It would appear that if the ini file is missing the `[/Script/ShooterGame.ShooterGameUserSettings]` section, then the ARK: Survival Evolved server will overwrite the file with default settings.

Try adding the following lines to the top of the file:
```
[/Script/ShooterGame.ShooterGameUserSettings]
bFirstPersonRiding=False
bThirdPersonPlayer=False
```

**Comment by MrYoshii** [comment]
i addet your lines but after server starting it overwrite it again with this config 
`[ServerSettings]
DifficultyOffset=0.500000
NewMaxStructuresInRange=6700.000000
XPMultiplier=5.000000
TamingSpeedMultiplier=6.000000
HarvestAmountMultiplier=2.000000
ShowMapPlayerLocation=False
globalVoiceChat=False
proximityChat=False
noTributeDownloads=False
allowThirdPersonPlayer=False
alwaysNotifyPlayerLeft=False
serverHardcore=False
serverPVE=False
OverrideStructurePlatformPrevention=False
AllowAnyoneBabyImprintCuddle=False
DisableImprintDinoBuff=False
ServerCrosshair=False
serverForceNoHud=False
EnablePVPGamma=False
DisableDinoDecayPvE=False
AdminLogging=False
ServerPassword=
ServerAdminPassword=
SpectatorPassword=
RCONEnabled=True
RCONPort=27020
PreventOfflinePvPInterval=60.000000
AutoDestroyOldStructuresMultiplier=0.000000
StructurePreventResourceRadiusMultiplier=1.000000
PvEDinoDecayPeriodMultiplier=1.000000
KickIdlePlayersPeriod=1800.000000
PerPlatformMaxStructuresMultiplier=1.000000
AutoSavePeriodMinutes=5.000000
ListenServerTetherDistanceMultiplier=1.000000
MaxTamedDinos=8000.000000
RCONServerGameLogBuffer=600.000000
EnableExtraStructurePreventionVolumes=False
ShowFloatingDamageText=False
PreventDownloadSurvivors=False
PreventDownloadItems=False
PreventDownloadDinos=False

[/Script/ShooterGame.ShooterGameUserSettings]
MasterAudioVolume=1.000000
MusicAudioVolume=1.000000
SFXAudioVolume=1.000000
VoiceAudioVolume=1.000000
CameraShakeScale=1.000000
bFirstPersonRiding=False
bThirdPersonPlayer=True
bShowStatusNotificationMessages=True
TrueSkyQuality=0.000000
FOVMultiplier=1.000000
GroundClutterDensity=0.000000
bFilmGrain=False
bMotionBlur=False
bUseDFAO=False
bUseSSAO=False
bShowChatBox=True
bCameraViewBob=True
bInvertLookY=False
bFloatingNames=True
bChatBubbles=True
bHideServerInfo=False
bJoinNotifications=False
bCraftablesShowAllItems=True
bLocalInventoryShowAllItems=False
bRemoteInventoryShowAllItems=False
LookLeftRightSensitivity=1.000000
LookUpDownSensitivity=1.000000
GraphicsQuality=1
ActiveLingeringWorldTiles=6
ClientNetQuality=3
LastServerSearchType=0
LastServerSearchHideFull=False
LastServerSearchProtected=False
HideItemTextOverlay=False
bDistanceFieldShadowing=False
LODScalar=0.780000
bToggleToTalk=False
HighQualityMaterials=True
HighQualitySurfaces=True
bTemperatureF=False
bDisableTorporEffect=False
bChatShowSteamName=False
bChatShowTribeName=True
EmoteKeyBind1=0
EmoteKeyBind2=0
bNoBloodEffects=False
bLowQualityVFX=False
bSpectatorManualFloatingNames=False
bSuppressAdminIcon=False
bUseSimpleDistanceMovement=False
bDisableMeleeCameraSwingAnims=False
bUseVSync=False
MacroCtrl0=
MacroCtrl1=
MacroCtrl2=
MacroCtrl3=
MacroCtrl4=
MacroCtrl5=
MacroCtrl6=
MacroCtrl7=
MacroCtrl8=
MacroCtrl9=
ResolutionSizeX=1280
ResolutionSizeY=720
LastUserConfirmedResolutionSizeX=1280
LastUserConfirmedResolutionSizeY=720
WindowPosX=-1
WindowPosY=-1
bUseDesktopResolutionForFullscreen=False
FullscreenMode=2
LastConfirmedFullscreenMode=2
Version=5

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=3
sg.ShadowQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=3
sg.EffectsQuality=3
sg.TrueSkyQuality=3
sg.GroundClutterQuality=3
sg.IBLQuality=1
sg.HeightFieldShadowQuality=3


`

**Comment by klightspeed** [comment]
I tested the following config, and it worked:
```
[/Script/ShooterGame.ShooterGameUserSettings]
bFirstPersonRiding=False
bThirdPersonPlayer=False
Version=5

[ServerSettings]
allowThirdPersonPlayer=1
AllowCaveBuildingPvE=1
alwaysNotifyPlayerJoined=1
alwaysNotifyPlayerLeft=1
bAllowFlyerCarryPvE=1
bDisableStructureDecayPvE=1
globalVoiceChat=0
HarvestAmountMultiplier=2.00000
MaxStructuresInRange=6700
noTributeDownloads=0
PreventDownloadSurvivors=0
PreventDownloadItems=0
PreventDownloadDinos=0
proximityChat=0
ResourceNoReplenishRadiusPlayers=1.00000
ResourceNoReplenishRadiusStructures=1.00000
ServerAdminPassword=redelephant
ServerCrosshair=0
serverForceNoHud=0
serverHardcore=0
ServerPassword=
serverPVE=0
ShowMapPlayerLocation=1
TamedDinoDamageMultiplier=1.00000
TamedDinoResistanceMultiplier=1.00000
TamingSpeedMultiplier=6.00000
XPMultiplier=5.00000
EnablePVPGamma=1
EnablePVEGamma=1
SpectatorPassword=
DifficultyOffset=0.50000
PvEStructureDecayDestructionPeriod=1.00000
Banlist="http://playark.com/banlist.txt"
PvPStructureDecay=0
DisableDinoDecayPvE=0
PvEDinoDecayPeriodMultiplier=1.00000
AdminLogging=0
MaxTamedDinos=8000
MaxNumbersofPlayersInTribe=2
BattleNumOfTribestoStartGame=2
TimeToCollapseROD=100
BattleAutoStartGameInterval=100
BattleSuddenDeathInterval=300
KickIdlePlayersPeriod=1800
PerPlatformMaxStructuresMultiplier=1.00000
StructureDamageRepairCooldown=180
bForceAllStructureLocking=1
AutoDestroyOldStructuresMultiplier=0.00000
bUseVSync=0
MaxPlatformSaddleStructureLimit=100
bPassiveDefensesDamageRiderlessDinos=1
RCONPort=27020
AutoSavePeriodMinutes=5
RCONServerGameLogBuffer=600
OverrideStructurePlatformPrevention=0
bPreventOfflinePvP=1
PreventOfflinePvPInterval=60.0
bPvPDinoDecay=1
bPvPStructureDecay=1
NewMaxStructuresInRange=6700
DisableImprintDinoBuff=1
AllowAnyoneBabyImprintCuddle=1
EnableExtraStructurePreventionVolumes=1
ShowFloatingDamageText=1

[/script/engine.gamesession]
MaxPlayers=127

[SessionSettings]
SessionName=!![EU/GER]!!HanfBude/10x Harvest/20x XP/40x Taming/hostet by DarkSide-Gaming

[MessageOfTheDay]
Duration=30
Message=Need an Admin? (GER/AT)TeamSpeak3: darkside-gaming.at
```

**Comment by MrYoshii** [comment]
i put the ini you post in start the server and it overwrite it again 

[/Script/ShooterGame.ShooterGameUserSettings]
bFirstPersonRiding=False
bThirdPersonPlayer=False
Version=5

[ServerSettings]
allowThirdPersonPlayer=False
AllowCaveBuildingPvE=1
alwaysNotifyPlayerJoined=1
alwaysNotifyPlayerLeft=False
bAllowFlyerCarryPvE=1
bDisableStructureDecayPvE=1
globalVoiceChat=False
HarvestAmountMultiplier=2.000000
MaxStructuresInRange=6700
noTributeDownloads=False
PreventDownloadSurvivors=False
PreventDownloadItems=False
PreventDownloadDinos=False
proximityChat=False
ResourceNoReplenishRadiusPlayers=1.00000
ResourceNoReplenishRadiusStructures=1.00000
ServerAdminPassword=
ServerCrosshair=False
serverForceNoHud=False
serverHardcore=False
ServerPassword=
serverPVE=False
ShowMapPlayerLocation=False
TamedDinoDamageMultiplier=1.00000
TamedDinoResistanceMultiplier=1.00000
TamingSpeedMultiplier=6.000000
XPMultiplier=5.000000
EnablePVPGamma=False
EnablePVEGamma=1
SpectatorPassword=
DifficultyOffset=0.500000
PvEStructureDecayDestructionPeriod=1.00000
Banlist="http://playark.com/banlist.txt"
PvPStructureDecay=0
DisableDinoDecayPvE=False
PvEDinoDecayPeriodMultiplier=1.000000
AdminLogging=False
MaxTamedDinos=8000.000000
MaxNumbersofPlayersInTribe=2
BattleNumOfTribestoStartGame=2
TimeToCollapseROD=100
BattleAutoStartGameInterval=100
BattleSuddenDeathInterval=300
KickIdlePlayersPeriod=1800.000000
PerPlatformMaxStructuresMultiplier=1.000000
StructureDamageRepairCooldown=180
bForceAllStructureLocking=1
AutoDestroyOldStructuresMultiplier=0.000000
bUseVSync=0
MaxPlatformSaddleStructureLimit=100
bPassiveDefensesDamageRiderlessDinos=1
RCONPort=27020
AutoSavePeriodMinutes=5.000000
RCONServerGameLogBuffer=600.000000
OverrideStructurePlatformPrevention=False
bPreventOfflinePvP=1
PreventOfflinePvPInterval=60.000000
bPvPDinoDecay=1
bPvPStructureDecay=1
NewMaxStructuresInRange=6700.000000
DisableImprintDinoBuff=False
AllowAnyoneBabyImprintCuddle=False
EnableExtraStructurePreventionVolumes=False
ShowFloatingDamageText=False
RCONEnabled=True
StructurePreventResourceRadiusMultiplier=1.000000
ListenServerTetherDistanceMultiplier=1.000000

[/script/engine.gamesession]
MaxPlayers=127

[SessionSettings]
SessionName=!![EU/GER]!!HanfBude/10x Harvest/20x XP/40x Taming/hostet by DarkSide-Gaming

[MessageOfTheDay]
Duration=30
Message=Need an Admin? (GER/AT)TeamSpeak3: darkside-gaming.at

**Comment by klightspeed** [comment]
It looks like it just changed some boolean parameters from integers to booleans.  Apart from that, I'm not seeing any problems.  It looks like the config has taken.

**Comment by MrYoshii** [comment]
if i chance `allowThirdPersonPlayer=False` to `allowThirdPersonPlayer=True` and i start the server it goes back to False again... same thing to all other lines

**Comment by klightspeed** [comment]
Are you setting those options in `main.cfg` - the ARK: Survival Evolved server will override any settings in `GameUserSettings.ini` with those setting on the command-line, which are set in arkmanager by settings in `main.cfg`.

**Comment by MrYoshii** [comment]
thanks man

**Comment by MrYoshii** [comment]
I have the override issue again.. my main.cfg `
# config environment
arkserverroot="/home/steam/ARK"                                     # path of your ARK server files (default ~/ARK)

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
#serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<file$
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
#ark_RCONEnabled="True"                                              # Enable RCON Protocol
#ark_RCONPort="32330"                                                # RCON Port
#ark_SessionName="[GER-Only]ALLx10-TAMx14-PVP-ISLAND-NO-MODS]"                                  # if your session name needs special characters please use the .ini instead
#ark_Port="7778"                                                     # ARK server port (default 7778)
#ark_QueryPort="27015"                                               # ARK query port (default 27015)
#ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
#ark_ServerAdminPassword="*************"                               # ARK server admin password, KEEP IT SAFE!
#ark_MaxPlayers="70"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures
`

and my GAMEUSERSETTINGS.INI: `[ServerSettings]
allowThirdPersonPlayer=1
AllowCaveBuildingPvE=0
alwaysNotifyPlayerJoined=1
alwaysNotifyPlayerLeft=1
bAllowFlyerCarryPvE=1
bDisableStructureDecayPvE=0
DayCycleSpeedScale=1.00000
DayTimeSpeedScale=1.00000
NightTimeSpeedScale=1.00000
DinoCharacterFoodDrainMultiplier=1.00000
DinoCharacterHealthRecoveryMultiplier=1.00000
DinoCharacterStaminaDrainMultiplier=1.00000
DinoCountMultiplier=1.00000
DinoDamageMultiplier=1.00000
DinoResistanceMultiplier=1.00000
globalVoiceChat=0
HarvestAmountMultiplier=10.00000
HarvestHealthMultiplier=1.00000
MaxStructuresInRange=6700
noTributeDownloads=1
PreventDownloadSurvivors=1
PreventDownloadItems=1
PreventDownloadDinos=1
PlayerCharacterFoodDrainMultiplier=1.00000
PlayerCharacterHealthRecoveryMultiplier=1.00000
PlayerCharacterStaminaDrainMultiplier=1.00000
PlayerCharacterWaterDrainMultiplier=0.80000
PlayerDamageMultiplier=1.00000
PlayerResistanceMultiplier=1.00000
proximityChat=0
ResourceNoReplenishRadiusPlayers=1.00000
ResourceNoReplenishRadiusStructures=1.00000
ResourcesRespawnPeriodMultiplier=1.00000
ServerAdminPassword=****************
ServerCrosshair=1
serverForceNoHud=0
serverHardcore=0
ServerPassword=
serverPVE=0
ShowMapPlayerLocation=1
StructureDamageMultiplier=1.00000
StructureResistanceMultiplier=1.00000
TamedDinoDamageMultiplier=1.00000
TamedDinoResistanceMultiplier=1.00000
TamingSpeedMultiplier=14.00000
XPMultiplier=10.00000
EnablePVPGamma=0
EnablePVEGamma=0
SpectatorPassword=
DifficultyOffset=0.50000
PvEStructureDecayPeriodMultiplier=1.00000
PvEStructureDecayDestructionPeriod=1.00000
Banlist="http://playark.com/banlist.txt"
PvPStructureDecay=0
DisableDinoDecayPvE=0
PvEDinoDecayPeriodMultiplier=1.00000
AdminLogging=0
MaxTamedDinos=8000
MaxNumbersofPlayersInTribe=2
BattleNumOfTribestoStartGame=2
TimeToCollapseROD=100
BattleAutoStartGameInterval=100
BattleSuddenDeathInterval=300
KickIdlePlayersPeriod=1800
PerPlatformMaxStructuresMultiplier=1.00000
StructureDamageRepairCooldown=180
bForceAllStructureLocking=1
AutoDestroyOldStructuresMultiplier=0.00000
bUseVSync=0
MaxPlatformSaddleStructureLimit=100
bPassiveDefensesDamageRiderlessDinos=1
RCONPort=27020
AutoSavePeriodMinutes=20
RCONServerGameLogBuffer=600
OverrideStructurePlatformPrevention=0
bPreventOfflinePvP=1
PreventOfflinePvPInterval=60.0
bPvPDinoDecay=1
bPvPStructureDecay=1
DisableImprintDinoBuff=1
AllowAnyoneBabyImprintCuddle=1
EnableExtraStructurePreventionVolumes=1
ShowFloatingDamageText=1
DestroyUnconnectedWaterPipes=0
OverrideOfficialDifficulty=1.0
TheMaxStructuresInRange=10500
MinimumDinoReuploadInterval=0
PvEAllowStructuresAtSupplyDrops=0
[/script/engine.gamesession]
MaxPlayers=70
[SessionSettings]
SessionName=[GER-Only]ALLx10-TAMx14-PVP-ISLAND-NO-MODS]
[MessageOfTheDay]
Duration=30
Message=Willkommen bitte lest die Regeln auf www.darkside-gaming.at
`

**Comment by MrYoshii** [comment]
i have the override issue again... 
my main.cfg `# config environment
arkserverroot="/home/steam/ARK"                                     # path of your ARK server files (default ~/ARK)

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
#serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<file$
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
#ark_RCONEnabled="True"                                              # Enable RCON Protocol
#ark_RCONPort="32330"                                                # RCON Port
#ark_SessionName="[GER-Only]ALLx10-TAMx14-PVP-ISLAND-NO-MODS]"                                  # if your session name needs special characters please use the .ini instead
#ark_Port="7778"                                                     # ARK server port (default 7778)
#ark_QueryPort="27015"                                               # ARK query port (default 27015)
#ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
#ark_ServerAdminPassword="**************"                               # ARK server admin password, KEEP IT SAFE!
#ark_MaxPlayers="70"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures
`
and my GAMEUSERSETTINGS.INI: `[ServerSettings]
allowThirdPersonPlayer=1
AllowCaveBuildingPvE=0
alwaysNotifyPlayerJoined=1
alwaysNotifyPlayerLeft=1
bAllowFlyerCarryPvE=1
bDisableStructureDecayPvE=0
DayCycleSpeedScale=1.00000
DayTimeSpeedScale=1.00000
NightTimeSpeedScale=1.00000
DinoCharacterFoodDrainMultiplier=1.00000
DinoCharacterHealthRecoveryMultiplier=1.00000
DinoCharacterStaminaDrainMultiplier=1.00000
DinoCountMultiplier=1.00000
DinoDamageMultiplier=1.00000
DinoResistanceMultiplier=1.00000
globalVoiceChat=0
HarvestAmountMultiplier=10.00000
HarvestHealthMultiplier=1.00000
MaxStructuresInRange=6700
noTributeDownloads=1
PreventDownloadSurvivors=1
PreventDownloadItems=1
PreventDownloadDinos=1
PlayerCharacterFoodDrainMultiplier=1.00000
PlayerCharacterHealthRecoveryMultiplier=1.00000
PlayerCharacterStaminaDrainMultiplier=1.00000
PlayerCharacterWaterDrainMultiplier=0.80000
PlayerDamageMultiplier=1.00000
PlayerResistanceMultiplier=1.00000
proximityChat=0
ResourceNoReplenishRadiusPlayers=1.00000
ResourceNoReplenishRadiusStructures=1.00000
ResourcesRespawnPeriodMultiplier=1.00000
ServerAdminPassword=
ServerCrosshair=1
serverForceNoHud=0
serverHardcore=0
ServerPassword=
serverPVE=0
ShowMapPlayerLocation=1
StructureDamageMultiplier=1.00000
StructureResistanceMultiplier=1.00000
TamedDinoDamageMultiplier=1.00000
TamedDinoResistanceMultiplier=1.00000
TamingSpeedMultiplier=14.00000
XPMultiplier=10.00000
EnablePVPGamma=0
EnablePVEGamma=0
SpectatorPassword=
DifficultyOffset=0.50000
PvEStructureDecayPeriodMultiplier=1.00000
PvEStructureDecayDestructionPeriod=1.00000
Banlist="http://playark.com/banlist.txt"
PvPStructureDecay=0
DisableDinoDecayPvE=0
PvEDinoDecayPeriodMultiplier=1.00000
AdminLogging=0
MaxTamedDinos=8000
MaxNumbersofPlayersInTribe=2
BattleNumOfTribestoStartGame=2
TimeToCollapseROD=100
BattleAutoStartGameInterval=100
BattleSuddenDeathInterval=300
KickIdlePlayersPeriod=1800
PerPlatformMaxStructuresMultiplier=1.00000
StructureDamageRepairCooldown=180
bForceAllStructureLocking=1
AutoDestroyOldStructuresMultiplier=0.00000
bUseVSync=0
MaxPlatformSaddleStructureLimit=100
bPassiveDefensesDamageRiderlessDinos=1
RCONPort=27020
AutoSavePeriodMinutes=20
RCONServerGameLogBuffer=600
OverrideStructurePlatformPrevention=0
bPreventOfflinePvP=1
PreventOfflinePvPInterval=60.0
bPvPDinoDecay=1
bPvPStructureDecay=1
DisableImprintDinoBuff=1
AllowAnyoneBabyImprintCuddle=1
EnableExtraStructurePreventionVolumes=1
ShowFloatingDamageText=1
DestroyUnconnectedWaterPipes=0
OverrideOfficialDifficulty=1.0
TheMaxStructuresInRange=10500
MinimumDinoReuploadInterval=0
PvEAllowStructuresAtSupplyDrops=0
[/script/engine.gamesession]
MaxPlayers=70
[SessionSettings]
SessionName=[GER-Only]ALLx10-TAMx14-PVP-ISLAND-NO-MODS]
[MessageOfTheDay]
Duration=30
Message=Willkommen bitte lest die Regeln auf www.darkside-gaming.at
`
