### ISSUE TITLE
PreventOfflinePvP

### ISSUE THREAD

**Issue by spitfire1081** [FezVrasta/ark-server-tools#507]
The instruction to run this new feature is to put this in the command line:

?PreventOfflinePvP=true?PreventOfflinePvPInterval=60.0?PvPDinoDecay=true?PvPStructureDecay=true

How can we do that with the Ark Server Tools?
Is there some new Configuration in main.cfg that we can do to run it?

**Comment by klightspeed** [comment]
```
ark_PreventOfflinePvP=true
ark_PreventOfflinePvPInterval=60.0
ark_PvPDinoDecay=true
ark_PvPStructureDecay=true
```

**Comment by spitfire1081** [comment]
I just put that in main.cfg?

**Comment by klightspeed** [comment]
Yes.

**Comment by arkfrancegaming** [comment]
You can also add it in your GameUserSettings.ini

**Comment by spitfire1081** [comment]
@arkfrancegaming how could I add it to GameUserSettings.ini? I tried to put the command as it is written in the command line it didn't work.

@klightspeed Is i want to add a command in command line that isn't introduced by "?" but for a "-", like -ForceAllowCaveFlyers how do I need to proceed?

**Comment by arkfrancegaming** [comment]
just add that in your gameusersettings.ini 

PreventOfflinePvP=true
PreventOfflinePvPInterval=900
PvPDinoDecay=true

it works for me

**Comment by spitfire1081** [comment]
@arkfrancegaming it did work. Thank you.
@klightspeed solution´s also worked. But I prefer to keep all my configurations on the .ini and let less information for the command line.

**Comment by klightspeed** [comment]
@spitfire1081 to add a dash option without an argument (e.g. `-ForceAllowCaveFlyers`), add `arkflag_ForceAllowCaveFlyers=true` to main.cfg

**Comment by spitfire1081** [comment]
@klightspeed Thank you very much.
