### ISSUE TITLE
Line 651: Segmentation fault - server crash

### ISSUE THREAD

**Issue by vladdlen** [FezVrasta/ark-server-tools#508]
`/usr/local/bin/arkmanager: line 651:  2416 Segmentation fault      (core dumped)`
`"$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"`
`14:14:26: Bad PID ''; expected '2416'`
`14:14:26: exited with status 0`
`14:14:26: restarting server`
`14:14:26: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?MaxPlayers=120\?Port=7777\?QueryPort=27016\?RCONEnabled=True\?RCONPort=XX\?ServerAdminPassword=XX\?listen -ForceAllowCaveFlyers`
`14:14:26: Server PID: 20022`
`[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.`
`Setting breakpad minidump AppID = 346110`
`14:14:57: server is up`

I'm not sure if this is an arkmanager issue or an ARK issue, but I've had a few random crashes these past few days and I get this error message in the arkserver.log file. We can play like normal up until we have a few seconds of "lag", then everyone gets kicked off the server. The server is then back up after a few seconds, but have rolled back to the last save. Any sollution to this?

**Comment by klightspeed** [comment]
This sounds like the same or similar issue to what @6zeus6 had in #494.

Try stopping arkmanager and running the command shown on the line `14:14:26: Running ...`
```
/home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer 'TheCenter?MaxPlayers=120?Port=7777?QueryPort=27016?RCONEnabled=True?RCONPort=XX?ServerAdminPassword=XX?listen' -ForceAllowCaveFlyers
```

**Comment by 6zeus6** [comment]
Did you changed something in the Game.ini or GameUserSettings.ini while the server was running? Like klightspeed said I had the same issue. Then I changed my rcon Port (because it was the same like the Gameport). Then I had a few days without any crashes. On the next day I changed something in the Game.ini while the server was running. A few minutes later the server crashed. I am no longer changing the config files without an immediately restart. So far it looks good. But I am still observing...

**Comment by arkfrancegaming** [comment]
Another one for me : 

Signal 11 caught.
/usr/local/bin/arkmanager : ligne 714 : 26541 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
16:36:36: Bad PID ''; expected '26541'
16:36:36: exited with status 0
16:36:36: restarting server
16:36:36: Running /home/CENTPVP/ShooterGame/Binaries/Linux/ShooterGameServer Thecenter\?RCONEnabled=True\?RCONPort=27029\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvP\ x10\ \[ANTI\ RAID\ OFF\]\?Port=7780\?QueryPort=27017\?ServerPassword\?ServerAdminPassword=***\?MaxPlayers=75\?GameModIds=684959100\,558079412\,656525905\?ForceAllStructureLocking=true\?listen -log -UseBattlEye -servergamelog
16:36:36: Server PID: 12102
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
16:36:41: server is up

**Comment by 6zeus6** [comment]
Problem still does exist.
Server was fine for about 2 weeks now. 
And then  suddenly crash =/
Same error log as every time

**Comment by arkfrancegaming** [comment]
remove the ark_servergamelog line

**Comment by 6zeus6** [comment]
Did this help to you?
I like to get the gamelog via rcon smartmobile app, so I would appreciate when I don't have to remove it.

you mean:
arkflag_servergamelog="" 
in the main.cfg ?

**Comment by arkfrancegaming** [comment]
It did a lot yep a lot of issues are coming from that according the dev, just comment the line like that 

#arkflag_servergamelog=""

**Comment by 6zeus6** [comment]
Ok thank you. I will try this
