### ISSUE TITLE
Auto Restart --warn --saveworld 

### ISSUE THREAD

**Issue by MrYoshii** [FezVrasta/ark-server-tools#510]
Hi i have setup auto restart every 6h with crontab but it say restart in 15 min and kills the server without waiting 15 minuts 
i have used the command: `arkmanager restart --warn --saveworld`

**Comment by klightspeed** [comment]
What version are you using?

**Comment by MrYoshii** [comment]
1.5

**Comment by radonn24** [comment]
This probably won't fix your issue, but, your command is wrong...

`saveworld` not `safeworld`

**Comment by MrYoshii** [comment]
in my crontab its saveworld sry had a typo

**Comment by klightspeed** [comment]
Please try the 1.6-dev channel.

**Comment by MrYoshii** [comment]
how can i make this?

**Comment by arkfrancegaming** [comment]
change it in top of your arkmanager.cfg and then run arkmanager upgrade-tools

**Comment by MrYoshii** [comment]
thanks man restart works with 1.6
