### ISSUE TITLE
3 different segfault in a raw

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#512]
Signal 11 caught.
/usr/local/bin/arkmanager : ligne 714 : 13425 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
11:21:46: Bad PID ''; expected '13425'
11:21:46: exited with status 0
11:21:46: restarting server
11:21:46: Running /home/CENTPVP/ShooterGame/Binaries/Linux/ShooterGameServer Thecenter\?RCONEnabled=True\?RCONPort=27029\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvP\ x10\ \[ANTI\ RAID\ OFF\]\?Port=7780\?QueryPort=27017\?ServerPassword\?ServerAdminPassword=****\?MaxPlayers=75\?GameModIds=684959100\,558079412\,656525905\?ForceAllStructureLocking=true\?listen -log -UseBattlEye -servergamelog
11:21:46: Server PID: 18146
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
11:21:51: server is up

Signal 11 caught.
/usr/local/bin/arkmanager : ligne 714 : 18146 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
11:40:02: Bad PID ''; expected '18146'
11:40:02: exited with status 0
11:40:02: restarting server
11:40:02: Running /home/CENTPVP/ShooterGame/Binaries/Linux/ShooterGameServer Thecenter\?RCONEnabled=True\?RCONPort=27029\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvP\ x10\ \[ANTI\ RAID\ OFF\]\?Port=7780\?QueryPort=27017\?ServerPassword\?ServerAdminPassword=****\?MaxPlayers=75\?GameModIds=684959100\,558079412\,656525905\?ForceAllStructureLocking=true\?listen -log -UseBattlEye -servergamelog
11:40:02: Server PID: 26131
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
11:40:07: server is up

Signal 11 caught.
/usr/local/bin/arkmanager : ligne 714 : 26131 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
11:46:17: Bad PID ''; expected '26131'
11:46:17: exited with status 0
11:46:17: restarting server
11:46:17: Running /home/CENTPVP/ShooterGame/Binaries/Linux/ShooterGameServer Thecenter\?RCONEnabled=True\?RCONPort=27029\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvP\ x10\ \[ANTI\ RAID\ OFF\]\?Port=7780\?QueryPort=27017\?ServerPassword\?ServerAdminPassword=****\?MaxPlayers=75\?GameModIds=684959100\,558079412\,656525905\?ForceAllStructureLocking=true\?listen -log -UseBattlEye -servergamelog
11:46:17: Server PID: 29603
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
11:46:22: server is up

Anyone know where it's coming from ? Thanks

**Comment by Lihis** [comment]
Here server happily running since latest patch came out. But to name at least few differences between my and your setup: my server does not have any mods and I do not have BattlEye enabled and my map is TheIsland.

And segfaults comes from ARK server itself so it is not problem in arkmanager..?

**Comment by arkfrancegaming** [comment]
/usr/local/bin/arkmanager : ligne 714 : 26131 Erreur de segmentation (core dumped) 

this might related to an issue

**Comment by Lihis** [comment]
Look pretty same as in issue #133.

**Comment by arkfrancegaming** [comment]
seems to happen on the center only

**Comment by arkfrancegaming** [comment]
i'm having the same 714 line issue on my other server on the center and now i'm getting 

Signal 11 caught.
21:24:00: Bad PID ''; expected '29603'
/usr/local/bin/arkmanager : ligne 765 : 29603 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
21:24:00: exited with status 0
21:24:00: restarting server
21:24:00: Running /home/CENTPVE/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?RCONEnabled=True\?RCONPort=27027\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\ The\ Center\?Port=7779\?QueryPort=27018\?ServerPassword\?ServerAdminPassword=****\?MaxPlayers=50\?GameModIds=684959100\,572277026\,558079412\,670764308\,543859212\,558651608\,600015460\,680798000\,566887000\?ForceAllStructureLocking=true\?listen -log -BattlEye -servergamelog -UseBattlEye
21:24:00: Server PID: 21653
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
21:24:05: server is up

**Comment by klightspeed** [comment]
@arkfrancegaming Did you have TheCenter installed as a mod?  You may need to remove the `614734500` and/or `TheCenter` directories from `$arkserverroot/ShooterGame/Content/Mods`.

Also check that none of the mods you have installed are contributing to the crash.

**Comment by arkfrancegaming** [comment]
i've did everything fine, it was working fine no reason that happens now. The server has been running for two weeks without any trouble

**Comment by arkfrancegaming** [comment]
Might help someone you need to desactivate that command like that in the arkmanager.ini #arkflag_servergamelog=true

when someone using that command and write % symbol in the tchat it auto crash the server instantly

Dev source :)
