### ISSUE TITLE
serverMap & ark_SessionName not working

### ISSUE THREAD

**Issue by 4g3nt0r4ng3** [FezVrasta/ark-server-tools#513]
As the subject states those 2 arguments dnt do anything when changed in ~.arkmanager.cfg.
The map wasnt much of a problem, i just edited the corresponding line 593 "arkserveropts="TheCenter"".
But its different with ark_SessionName , no matter if i change it in ~.arkmanager.cfg or remove it there and just add it to my GameUserSettings.ini , it allways appears as "?SessionName=ARK\ Server\ Tools" in the start parameters.

Did i miss anything?

Thanks in advance.

**Comment by klightspeed** [comment]
`ark_SessionName` belongs in the instance config - look in `/etc/arkmanager/instances/main.cfg` or `~/.config/arkmanager/instances/main.cfg`

**Comment by 4g3nt0r4ng3** [comment]
*facepalm* 
Thanks alot.
