### ISSUE TITLE
Suddenly, when I tried to update one of my servers today,  I got this

### ISSUE THREAD

**Issue by spitfire1081** [FezVrasta/ark-server-tools#516]
This is happening when I try to update one of my servers:

Downloading mod 693416678 ...  
Mod 693416678 download failed
Mod 693416678 downloaded
/home/steam/steamcmd/linux32/steamcmd: error while loading shared libraries: libstdc++.so.6: cannot open shared 
object file: No such file or directory

How should I proceed?

**Comment by klightspeed** [comment]
Are you still having this problem?
