### ISSUE TITLE
Duplication message 

### ISSUE THREAD

**Issue by arkfrancegaming** [FezVrasta/ark-server-tools#518]
Hi all, 

still have a duplication at every messages :

![capture](https://cloud.githubusercontent.com/assets/13471860/16374722/0e16e9ac-3c58-11e6-9cb4-c4b7a5c4f155.JPG)

**Comment by klightspeed** [comment]
Commit 8aad9cd in branch 1.6-dev.unstable should fix this.

**Comment by arkfrancegaming** [comment]
is does thanks !
