### ISSUE TITLE
additional startparameter

### ISSUE THREAD

**Issue by MrYoshii** [FezVrasta/ark-server-tools#519]
is it possiple to insert additional startparameter like -USEALLAVAILABLECORES

thanks for help

**Comment by klightspeed** [comment]
https://github.com/FezVrasta/ark-server-tools#instance-config-files

To add `-USEALLAVAILABLECORES` to the commandline of the ARK server, add `arkflag_USEALLAVAILABLECORES=true` to your `main.cfg` (or whatever instance you're using).

**Comment by arkfrancegaming** [comment]
what the USEALLAVAILABLECORES does ?

**Comment by MrYoshii** [comment]
it use "all available cores" on your host system since i add it the rubberbanding was less

**Comment by arkfrancegaming** [comment]
It's not automatic per default?
