### ISSUE TITLE
Daily Restart

### ISSUE THREAD

**Issue by talpidae** [FezVrasta/ark-server-tools#520]
Hey there!

I have created some crontabs to update my server. Now i have the question is it possible to do an restart every 24h if there is no update availible?

Dont want to do a simple "arkmanager restart" ever 24h, maybe there was an update 15min ago.

Thanks, talpidae

**Comment by klightspeed** [comment]
```
0 3 * * * [ -z "$(find ~/ARK/steamapps/appmanifest_376030.acf -mtime -1)" ] && arkmanager restart --warn
```

**Comment by talpidae** [comment]
Very nice! Thank you <3 :D
