### ISSUE TITLE
Failed to open descriptor file

### ISSUE THREAD

**Issue by LvZeeland** [FezVrasta/ark-server-tools#521]
I get a failure when starting the server.

When starting ShooterGameServer: 

`thebierfontein@theBierfonteinServer:~/steamcmd$ arkmanager run
Running command 'run' for instance 'main'
23:03:18: start
/usr/local/bin/arkmanager: line 645: ulimit: open files: cannot modify limit: Operation not permitted
23:03:18: Running /home/thebierfontein/steamcmd/~/ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=20\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=2326415\?ServerPassword=starK\?SessionName=theBierfontein\?listen
Using binned.
23:03:18: Server PID: 5746
4.5.1-0+UE4 7038 3077 402 5`

The following error pops-up:
[Screenshot](http://i.imgur.com/5Ku48Yo.png)
 `Failed to open descriptor file '../../../ShooterGame/ShooterGame.uproject'`

My config Files:
[arkmanager.cfg](https://github.com/FezVrasta/ark-server-tools/files/342376/arkmanager.txt)
[main.cfg](https://github.com/FezVrasta/ark-server-tools/files/342374/main.txt)

**Comment by klightspeed** [comment]
The `arkserverroot` would be the absolute path `/home/thebierfontein/steamcmd/~/ark`.  It's possible that the tilde `~` could be confusing the server or steamcmd.

The comment `default ~/ARK` means that the default directory is the `ARK` directory in the home directory.  `~/ARK` expands to `/home/thebierfontein/ARK` for user `thebierfontein` only when `~` is not preceded by anything and is either not followed by anything or is immediately followed by a `/`.

From the bash manual:
```
DEFINITIONS
       word   A  sequence  of  characters  considered  as a single unit by the
              shell.  Also known as a token.

EXPANSION
   Tilde Expansion
       If  a  word  begins  with an unquoted tilde character (`~'), all of the
       characters preceding the first unquoted slash (or  all  characters,  if
       there  is no unquoted slash) are considered a tilde-prefix.  If none of
       the characters in the tilde-prefix are quoted, the  characters  in  the
       tilde-prefix  following the tilde are treated as a possible login name.
       If this login name is the null string, the tilde is replaced  with  the
       value  of  the shell parameter HOME.  If HOME is unset, the home direc-
       tory of the user executing the shell is  substituted  instead.   Other-
       wise,  the  tilde-prefix is replaced with the home directory associated
       with the specified login name.
```

**Comment by LvZeeland** [comment]
Thank you for your reply, Klightspeed.
I've copied the ark server files to ~/ark and changed the paths in main.cfg and arkmanager.cfg. This fixed the error. 
And the server is now running successful.

**Comment by helpmepleaz** [comment]
what do i do please help
