### ISSUE TITLE
arkmanager command to do wild dino wipe?

### ISSUE THREAD

**Issue by rob-bb** [FezVrasta/ark-server-tools#522]
Hi,  I would like to do a wild dino wipe by cron once a week or so.  Is it capable of issuing console commands to the server as if sent by the admin similar to the broadcast command?

**Comment by klightspeed** [comment]
```
0 1 * * 6 /usr/local/bin/arkmanager rconcmd "DestroyWildDinos"
```

**Comment by rob-bb** [comment]
Nice, t hats so easy.  So can we issue any of the admin commands via arkmanager rconcmd "some command"

**Comment by klightspeed** [comment]
Any command that doesn't either target the player executing it or bring up a GUI should work through RCON.
