### ISSUE TITLE
command not found: workshop_download_item

### ISSUE THREAD

**Issue by 14nickel** [FezVrasta/ark-server-tools#524]
Been banging my head against this wall for too long, I'm sure there's a config setting I missed somewhere, but I'm not even sure where to troubleshoot anymore.

Trying to install a mod, and it looks like it can't find the workshop_download_item command. 
```
minecraft@proxmox:~/Steam$ arkmanager installmod 691195806 --verbose
Running command 'installmod' for instance 'main'
Downloading mod 691195806
Redirecting stderr to '/home/minecraft/.steam/steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
>>> command not found: workshop_download_item
Mod 691195806 was not successfully downloaded
```
Even running straight through the steamcmd.sh, I'm getting that same error. 
```
minecraft@proxmox:~/Steam$ ./steamcmd.sh +login anonymous +workshop_download_item 376030 691195806
Redirecting stderr to '/home/minecraft/.steam/steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
>>> command not found: workshop_download_item

Steam>quit

Steam>minecraft@proxmox:~/S
```
Any suggestions? Bribing the computer with tasty data files didn't help. Other than this little hiccup, this is an amazing tool.

**Comment by klightspeed** [comment]
Try installing it under a user that doesn't already have Steam installed, and installing it in a directory other than ~/Steam.

Note that the mod appid needs to be the client appid (346110), as mods will not match the server appid (376030).

**Comment by 14nickel** [comment]
Try reinstalling ARK, SteamCMD, or the mod?

I tried both appIds, same result.

**Comment by klightspeed** [comment]
SteamCMD

**Comment by 14nickel** [comment]
This seems to have worked. Thanks!
