### ISSUE TITLE
Unable to update server

### ISSUE THREAD

**Issue by LvZeeland** [FezVrasta/ark-server-tools#525]
When running arkmanager update. everything seems good. But when it ends and I check if the server has been updated, I get the same old version number as before.

The version before:
`thebierfontein@theBierfonteinServer:~$ arkmanager checkupdate`
`Running command 'checkupdate' for instance 'main'`
`Querying Steam database for latest version...`
`Current version:  1205880`
`Available version:  1210588`
`Your server needs to be restarted in order to receive the latest update.`
Run "arkmanager update" to do so`
`

The update
`thebierfontein@theBierfonteinServer:~$ sudo arkmanager update`
`Running command 'update' for instance 'main'`
`Stopping server...`
`The server has been stopped`
`Copying ARK world file                                            [   OK   ]`
`Copying ARK profile files`
`76561198011414022.arkprofile                                    [   OK   ]`
`76561198045521683.arkprofile                                    [   OK   ]`
`76561198073878058.arkprofile                                    [   OK   ]`
`76561198116793021.arkprofile                                    [   OK   ]`
`76561198158445892.arkprofile                                    [   OK   ]`
`Copying ARK tribe files`
`1830223016.arktribe                                             [   OK   ]`
`1912826626.arktribe                                             [   OK   ]`
 `Copying GameUserSettings.ini                                      [   OK   ]`
 `Copying Game.ini                                                  [   OK   ]`
 `Compressing Backup                                                [   OK   ]`
`Created Backup:  2016-07-04_13.43.03.tar.bz2`
`Performing ARK update ... The server is starting...`
                          The server is now running, and should be up within 10 minutes`

Version check after update:
`thebierfontein@theBierfonteinServer:~$ arkmanager checkupdate`
`Running command 'checkupdate' for instance 'main'`
`Querying Steam database for latest version...`
`Current version:  1205880`
`Available version:  1210588`
`Your server needs to be restarted in order to receive the latest update.`
`Run "arkmanager update" to do so`

I feel like am doing something wrong, but I can't figure out what.

**Comment by klightspeed** [comment]
You don't need sudo to run `arkmanager update` as long as you are running as the user under which ARK is installed.

What is the output when you add `--verbose` to the update command-line?

i.e.:
```
arkmanager update --verbose
```

**Comment by LvZeeland** [comment]
You're right, there's something wrong with Steam.

`thebierfontein@theBierfonteinServer:~$ arkmanager update --verbose
Running command 'update' for instance 'main'
Stopping server...
The server has been stopped
 Copying ARK world file                                            [   OK   ]
 Copying ARK profile files
   76561198011414022.arkprofile                                    [   OK   ]
   76561198045521683.arkprofile                                    [   OK   ]
   76561198073878058.arkprofile                                    [   OK   ]
   76561198116793021.arkprofile                                    [   OK   ]
   76561198158445892.arkprofile                                    [   OK   ]
 Copying ARK tribe files 
   1830223016.arktribe                                             [   OK   ]
   1912826626.arktribe                                             [   OK   ]
 Copying GameUserSettings.ini                                      [   OK   ]
 Copying Game.ini                                                  [   OK   ]
 Compressing Backup                                                [   OK   ]
 Created Backup:  2016-07-04_14.02.27.tar.bz2
Performing ARK update
Redirecting stderr to '/home/thebierfontein/steamcmd/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
applicationmanager.cpp (1048) : Assertion Failed: Failed to write app state file /home/thebierfontein/ARK/steamapps/appmanifest_376030.acf
applicationmanager.cpp (1048) : Assertion Failed: Failed to write app state file /home/thebierfontein/ARK/steamapps/appmanifest_376030.acf
 Update state (0x3) reconfiguring, progress: 0,00 (0 / 0)
Error! App '376030' state is 0x206 after update job.
applicationmanager.cpp (1048) : Assertion Failed: Failed to write app state file /home/thebierfontein/ARK/steamapps/appmanifest_376030.acf
applicationmanager.cpp (803) : Assertion Failed: m_bStateChangesSavedToDisk
The server is starting...
The server is now running, and should be up within 10 minutes`

**Comment by klightspeed** [comment]
Check that the files under `/home/thebierfontein/ARK` are owned by `thebierfontein`, and that write permission is granted.

i.e.
```
sudo chown -R thebierfontein /home/thebierfontein/ARK
sudo chmod -R u+rw /home/thebierfontein/ARK
```
