### ISSUE TITLE
Add more than one reason to restart

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#526]
Hey, i was thinking about asking if you can add more than one reason to restart like :+1: 

arkmanager restart --warnreason1
arkmanager restart --warnreason1

and adding in the arkmanager.cfg different lines for that

That would be great to add custom restart like a restart every night etc..

Thanks

**Comment by klightspeed** [comment]
One can currently use:

```
shutdownreason="Nightly restart" arkmanager restart --warn
```

We can add a `--reason="..."` option.

**Comment by arkfrancegaming** [comment]
that would be great too yep

**Comment by arkfrancegaming** [comment]
or maybe a --reason="1" related to the reason in the arkmanager.cfg

**Comment by arkfrance** [comment]
any update ? :)

**Comment by klightspeed** [comment]
I've fixed the `--warnreason` option I added in May, and have added it to `arkmanager update`.

It can now accept either a plain reason (e.g. "Nightly restart") or a reason identifier (i.e. `--warnreason=1` will look at the `warnreason_1=...` setting in your config)

This won't currently work if you don't have `msgWarnReason=...` in your config.

**Comment by arkfrance** [comment]
ok so for exemple

i will add warnreason_1=Nightly Restart in my arkmanager.cfg

to launch it i will use arkmanager restart --warnreason=1

is that allright ?

**Comment by klightspeed** [comment]
You need to quote strings in the config, so use:
```
warnreason_1="Nightly Restart"
```

Apart from that, it should work.

**Comment by arkfrance** [comment]
ok i will check that tomorrow

**Comment by arkfrance** [comment]
it seems to restart but no warning

**Comment by klightspeed** [comment]
What is the output of your `arkmanager restart --warn --warnreason=1` run?

**Comment by arkfrance** [comment]
warnreason_1="Reboot quotidien, il est temps d'aller au lit les geeks !"

my bad 

30 5 * * * /usr/local/bin/arkmanager useconfig val restart --warnreason=1

**Comment by arkfrance** [comment]
30 5 * * * /usr/local/bin/arkmanager useconfig val restart --warn --warnreason=1

that will work

**Comment by klightspeed** [comment]
That should work.

**Comment by arkfrance** [comment]
it does :)
