### ISSUE TITLE
Delay to auto restart

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#527]
hey is it normal that my server autorestart that long ?

Signal 11 caught.
/usr/local/bin/arkmanager : ligne 714 :  2010 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
04:56:55: Bad PID ''; expected '2010'
04:56:55: exited with status 0
10:35:20: start
10:35:20: Running /home/PVP/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32330\?Port=7778\?QueryPort=27019\?SessionName=\[Wiped\ 28/06\]ARK\ FRANCE\ OFFICIEL\ -\ PvP\ x10\?ServerAdminPassword=****\?MaxPlayers=70\?GameModIds=684959100\,558079412\,656525905\,572174950\,566432022\?ForceAllStructureLocking=true\?PreventTribeAlliances=true\?listen -log -UseBattlEye
10:35:20: Server PID: 8207
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Using binned.

**Comment by thymon13** [comment]
Désolé, rien a voir. Mais Où trouve t-on les log comme cela ? 
---
Sorry off topic : Where can I find the log ?

**Comment by klightspeed** [comment]
By default, the server log is in `/var/log/arktools/arkserver.log`

This is controlled by the `logdir` setting in `arkmanager.cfg`

**Comment by arkfrancegaming** [comment]
The server was already online when it segfault and auto restart 5 hours later weird, i don't have any unused mods. But it already happens once at almost the same time

**Comment by 6zeus6** [comment]
Welcome to the random server crashes:

https://github.com/FezVrasta/ark-server-tools/issues/494
https://github.com/FezVrasta/ark-server-tools/issues/508


Couldn't fix those errors so far. I think it is a problem by wildcard to their linux server verions. But I don't know.

**Comment by arkfrance** [comment]
Same error this morning 

Signal 11 caught.
/usr/local/bin/arkmanager : ligne 714 :  6598 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
06:08:36: Bad PID ''; expected '6598'
06:08:36: exited with status 0

no autorestart back

**Comment by arkfrance** [comment]
Is it possible to add a pid check to start another session in x seconds after a crash?

**Comment by arkfrance** [comment]
Or if I add a arkmanager start cron every 30 min

**Comment by klightspeed** [comment]
`arkmanager start @instance` will start the server if it's not already running.

Do you want an option to try to automatically restart the server, possibly after a delay, when the server crashes without successfully becoming ready?

**Comment by arkfrance** [comment]
Yep it won't fixes crashes but at least it will restart correctly because now when there is a segfault crash even if the server was correctly online et ready it doesn't auto restart as usual

**Comment by klightspeed** [comment]
An option `arkAlwaysRestartOnCrash=true` can be added to the instance config.  This can also be specified using `arkmanager start --alwaysrestart`

**Comment by arkfrance** [comment]
thanks :) epic

**Comment by arkfrance** [comment]
doesn't seems to auto restart

Signal 11 caught.
/usr/local/bin/arkmanager : ligne 722 : 11446 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
00:25:34: Bad PID ''; expected '11446'
00:25:34: exited with status 0
00:26:53: start
00:26:53: Running /home/VAL/ShooterGame/Binaries/Linux/ShooterGameServer Valhalla\?RCONEnabled=True\?RCONPort=32332\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\ Valhalla\?Port=7779\?QueryPort=27017\?ServerPassword\?ServerAdminPassword=tabou\?MaxPlayers=50\?GameModIds=684959100\,572277026\,558079412\,558651608\,564895376\,670764308\,704420972\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -UseBattlEye
00:26:53: Server PID: 28933
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

i had to start it back my self

i've got arkAlwaysRestartOnCrash=true in my cfg

**Comment by klightspeed** [comment]
6d20795 should fix this.
