### ISSUE TITLE
update not detected?

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#53]
Looks like the latest version is 179.4 but arkmanager says I'm already on the most recent version, even if I'm on 179.3.

Any info?

**Comment by FezVrasta** [comment]
actually, even querying the latest version manually it says:

```
	"public"
			{
				"buildid"		"668810"
			}
```

**Comment by FezVrasta** [comment]
I have forced an update and now when I check for updates it says that the latest version is 669428...

is it possible that the command we use fetches the installed version and not the remote version?

**Comment by Atriusftw** [comment]
@FezVrasta I got in touch with Jat (community manager) and notified them about this. It was as i suspected - the devs had forgot to push the latest build to linux. 180.0 is right around the corner though, and Jat will make sure that they remember to push it to linux aswell =)

**Comment by FezVrasta** [comment]
well my problem was with the 179.3 and the 179.4, and there wasn't problem with them.

I'll check again once the 180 is out to see if the problem persists

**Comment by Atriusftw** [comment]
Well, im actually stuck on 179.4, even when manually updating with steamcmd. Latest version is supposed to be 179.5 according to patch notes.

**Comment by FezVrasta** [comment]
ok this is another problem tho

**Comment by Atriusftw** [comment]
checkupdate is working as intended =)

http://atrius.net/~random/arkmanager-checkupdate.PNG

**Comment by FezVrasta** [comment]
```
[steam ~]$ arkmanager checkupdate
Current version:  669428
Available version:  669428
Your server is up to date!
```

:/

**Comment by klightspeed** [comment]
I ran into this issue too, and it resolved itself after running steamcmd interactively.

It looks like the issue here is that steamcmd is using cached info - see https://steamdb.info/forum/362/

Perhaps we could add +app_info_update 1

**Comment by FezVrasta** [comment]
Yes we could try

**Comment by FezVrasta** [comment]
even with the app_info_update I got the same problem

**Comment by klightspeed** [comment]
As of 2015-06-26 11:54 UTC, steamdb.info shows the last update being 12 hours ago.

The current version appears to be buildid 672599.

What buildid are you getting?

**Comment by Atriusftw** [comment]
My server is running build 672599 (Which is game version 180.1), updated a few hours ago.

**Comment by FezVrasta** [comment]
This guys seems to have found a solution but I can't find that folder

https://github.com/dgibbs64/linuxgsm/issues/301#issuecomment-83247693

**Comment by klightspeed** [comment]
The appcache directory is in $HOME/Steam/appcache

**Comment by FezVrasta** [comment]
so if we clear that folder before we check for updates everything should work I guess. @klightspeed I can implement it, let me know if you prefer if I assign it to you

**Comment by Atriusftw** [comment]
https://gist.github.com/Atriusftw/5a051df2c1f7a5c960db Should do it, yes?

**Comment by FezVrasta** [comment]
probably is enough delete the appinfo.vdf

**Comment by FezVrasta** [comment]
implemented, we can ship
