### ISSUE TITLE
enabling -USEALLAVAILABLECORES

### ISSUE THREAD

**Issue by badboysgaming** [FezVrasta/ark-server-tools#533]
can't get this to work -USEALLAVAILABLECORES
i have tried arkflag_useallavailablecores
ark_USEALLAVAILABLECORES
but says command not found?

**Comment by klightspeed** [comment]
https://github.com/FezVrasta/ark-server-tools#global-configuration

Try `arkflag_USEALLAVAILABLECORES=true`

**Comment by badboysgaming** [comment]
hmm no errors let me check logs

**Comment by badboysgaming** [comment]
hmmm `[2016.07.09-14.34.33:040][  0]Commandline:  TheIsland?AllowFlyerCarryPVE=true?DifficultyOffset=4?EnableExtraStructurePreventionVolumes=true?ForceAllStructureLocking=true?GameModIds=679529026,670764308,658112994,695998908,670764308,510854250,668032387,719928795,536214294,708807240?MaxPlayers=70?Port=7777?PreventOfflinePvP=true?PreventOfflinePvPInterval=60.0?PvPDinoDecay=true?PvPStructureDecay=true?QueryPort=27015?RCONEnabled=True?RCONPort=32330?ServerAdminPassword=********?ServerPassword?ShowFloatingDamageText=true?bRawSockets?bUseVSync=1?lowmemory?usecache?listen -ForceAllowCaveFlyers -USEALLAVAILABLECORES
[2016.07.09-14.34.33:040][  0]Full Startup: 84.77 seconds (BP compile: 0.00 seconds)
[2016.07.09-14.34.33:040][  0]Number of cores 1` still only using 1 core

**Comment by klightspeed** [comment]
See https://forums.unrealengine.com/showthread.php?62272-Linux-Server-multi-core-thread-support

If Wildcard is doing everything on the game thread, then the game server will only ever use one core, and asking it to use multiple cores will do nothing.

**Comment by rob-bb** [comment]
I can confirm it does not work with servers, I tried it about 3 weeks ago,  no difference in behavior or cpu usage with approx 30 players online.  It's a client only option.

**Comment by TOXid** [comment]
There is no way to run Linux ARK server on multicore sytem today? It use only 1 core (100% of one or equivalent 10-25% of all cores but not more than 100% of one....)
