### ISSUE TITLE
serverchat command

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#537]
Hey, 

is it possible to add the serverchat command (cheat serverchat test)

same as the broadcast : arkmanager broadcast "message"

but arkmanager tchatmessage "message"

Thanks :)

**Comment by klightspeed** [comment]
```
arkmanager rconcmd "serverchat message"
```

**Comment by arkfrance** [comment]
true i forgot that ! 

another thing 

root@ns3013274:~# arkmanager useconfig centpve status
[  ERROR  ]     You have not rights to write in the log directory.
Running command 'status' for instance 'centpve'
 Server running:   Yes
 Server listening:   Yes

i've got no right to right on the log directory, in root or steam user

**Comment by klightspeed** [comment]
Check the permissions on your log directory (default `/var/log/arktools`)

**Comment by arkfrance** [comment]
a simple server restart did it ... weird
