### ISSUE TITLE
new command

### ISSUE THREAD

**Issue by badboysgaming** [FezVrasta/ark-server-tools#538]
- Experimental fast save/load code implemented for servers. Approximately 4x faster and 75% smaller. We strongly recommend backing up your save games if you intend to try this out, as we're still testing it. Use with launch commandline "-newsaveformat"  so is it ark_flag or just ark_

**Comment by klightspeed** [comment]
```
arkflag_newsaveformat=true
```

**Comment by cronner** [comment]
isn't this default now?

**Comment by rob-bb** [comment]
Yes, it is the default, it got almost no testing before being made the default.  :(
