### ISSUE TITLE
[SOLVED]map mod failing to start 

### ISSUE THREAD

**Issue by badboysgaming** [FezVrasta/ark-server-tools#539]
trying to add shingo islands but server will not start

`# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
#serverMap="TheIsland"                                               # server map (default TheIsland)
serverMapModId="661564024"                                         # Uncomment this to specify the Map Mod
#ark_TotalConversionMod="496735411" `

so what is going on

**Comment by klightspeed** [comment]
What is the output of `arkmanager --version`?
What is logged in `/var/log/arktools/arkserver.log` (or `$HOME/logs/arktools/arkserver.log` if that exists)?

**Comment by badboysgaming** [comment]
i have tried adding 
serverMap="ShigoIslands"  
adding modid 
ark_GameModIds="661564024
but keep getting same errors in log 

> 06:41:34: start
/usr/local/bin/arkmanager: line 656: ulimit: open files: cannot modify limit: Operation not permitted
06:41:34: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer ShigoIslands\?AllowFlyerCarryPVE=true\?DifficultyOffset=1\?DinoCountMultiplier=1\?EnableExtraStructurePreventionVolumes=true\?ForceAllStructureLocking=true\?GameModIds=661564024\,635723262\,538986229\,676288311\,519536568\,631279858\,663827368\,609773783\,539464369\,670764308\,695998908\,609380111\?MaxPlayers=70\?Port=7776\?PreventOfflinePvP=true\?PreventOfflinePvPInterval=60.0\?PvPDinoDecay=true\?PvPStructureDecay=true\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=\?ServerPassword\?bRawSockets\?listen -ForceAllowCaveFlyers -log -server -servergamelog -useallavailablecores
06:41:34: Server PID: 14654
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:E:\SVN_Ark\Engine\Source\Runtime\CoreUObject\Private\Serialization\AsyncLoading.cpp] [Line: 1311] 
LoadPackageAsync failed to begin to load a level because the supplied package name was neither a valid long package name nor a filename of a map within a content folder: '/Game/Mods/3224383872/'
Signal 11 caught.
/usr/local/bin/arkmanager: line 662: 14654 Segmentation fault      (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
06:42:00: Bad PID ''; expected '14654'
06:42:00: exited with status 0

**Comment by klightspeed** [comment]
Make sure you don't have any mods you don't use in your `$arkserverroot/ShooterGame/Content/Mods` directory.  

The error suggests that one of the following is true:
* You have mod 3224383872 in your mods directory
* One of the mods you have installed has mod 3224383872 (which the author has deleted, hidden or not made public) as a dependency; or
* Your saved world uses something in mod 3224383872.

**Comment by badboysgaming** [comment]
there is no mods 3224383872 in my mod folder as for that id it keeps changing every time server crashes.

**Comment by badboysgaming** [comment]
and there is now saveworld

**Comment by badboysgaming** [comment]
it appears to be issues with mods checking closer loading mods one by one till i locate the problem

**Comment by klightspeed** [comment]
What are the content of the `/home/steam/ARK/ShooterGame/Contents/Mods` directory?
What is the output of `/usr/local/bin/arkmanager --version`?

If you have both `661564024` and `661564024.mod` in your mods directory, try the following:
* Create a directory `/home/steam/Mods`
* Move everything except `661564024` and `661564024.mod` into `/home/steam/Mods`
* Comment out your `ark_GameModIds` setting in your config
* Add the following line to your config:
  `ark_MapModId=661564024`

**Comment by badboysgaming** [comment]
found this issue was sub mods the author had added to map mod they caused crash with server
