### ISSUE TITLE
Fix broadcast command

### ISSUE THREAD

**Issue by longlostbro** [FezVrasta/ark-server-tools#54]
Broadcast not working.

**Comment by Atriusftw** [comment]
It's not fully implemented yet. We have to wait for RCON before it can be used.

**Comment by klightspeed** [comment]
This should be working with the rconcmd feature in 1.3-dev.

**Comment by FezVrasta** [comment]
should we release it?

**Comment by klightspeed** [comment]
I think we can close this issue since it should have been satisfied by 61068b2
