### ISSUE TITLE
Error: another server instance is running from the same directory

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#541]
10:32:20: start
10:32:20: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32333\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\?Port=7776\?QueryPort=27016\?ServerAdminPassword=***\?MaxPlayers=60\?GameModIds=684959100\,558079412\,534838287\,704420972\,572277026\,670764308\,564895376\,519536568\,600015460\,680798000\,566887000\,543859212\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -newsaveformat -server -UseBattlEye
10:32:20: Server PID: 8063
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager : ligne 723 : 25020 Abandon                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
10:32:21: Bad PID '8063'; expected '25020'
Error: another server instance is running from the same directory
Aborting - two servers MUST NOT run from the same directory
10:32:21: exited with status 0
Using binned.
4.5.1-0+UE4 7038 3077 402 5
STEAMPS3 - TCPPort::OnAcceptEvent (tcpport=0x665af0050ae0), (socket=0x665af00874a8), (incoming.addr=2.5.132.234:53872)(incoming_=0)
STEAMPS3 - AsyncTCPSocket created

What does those mean ? 

Error: another server instance is running from the same directory
Aborting - two servers MUST NOT run from the same directory

**Comment by klightspeed** [comment]
Is this after an update or a restart?

**Comment by arkfrance** [comment]
That's the full log

CtrlCHandler: Signal=2
/usr/local/bin/arkmanager : ligne 722 : 10951 Abandon                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
11:02:54: Bad PID ''; expected '10951'
11:02:54: exited with status 0
11:02:55: start
11:02:55: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32333\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\?Port=7776\?QueryPort=27016\?ServerAdminPassword=****\?MaxPlayers=60\?GameModIds=684959100\,558079412\,534838287\,704420972\,572277026\,670764308\,564895376\,519536568\,600015460\,680798000\,566887000\,543859212\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -newsaveformat -server -UseBattlEye
11:02:55: Server PID: 20556
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
/usr/local/bin/arkmanager : ligne 723 : 20556 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
18:46:44: Bad PID ''; expected '20556'
18:46:44: exited with status 0
18:46:44: restarting server
18:46:44: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32333\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\?Port=7776\?QueryPort=27016\?ServerAdminPassword=****\?MaxPlayers=60\?GameModIds=684959100\,558079412\,534838287\,704420972\,572277026\,670764308\,564895376\,519536568\,600015460\,680798000\,566887000\,543859212\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -newsaveformat -server -UseBattlEye
18:46:44: Server PID: 944
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Using binned.
4.5.1-0+UE4 7038 3077 402 5
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
CtrlCHandler: Signal=2
/usr/local/bin/arkmanager : ligne 723 :   944 Abandon                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
20:48:12: Bad PID ''; expected '944'
20:48:12: exited with status 0
20:48:32: start
20:48:32: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32333\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\?Port=7776\?QueryPort=27016\?ServerAdminPassword=*****\?MaxPlayers=60\?GameModIds=684959100\,558079412\,534838287\,704420972\,572277026\,670764308\,564895376\,519536568\,600015460\,680798000\,566887000\,543859212\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -newsaveformat -server -UseBattlEye
20:48:32: Server PID: 25020
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Using binned.
4.5.1-0+UE4 7038 3077 402 5
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - TCPPort::OnAcceptEvent (tcpport=0x750f7c511280), (socket=0x750f7c39f468), (incoming.addr=92.132.61.40:50733)(incoming_=0)
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - TCPPort::OnAcceptEvent (tcpport=0x750f7c2e1280), (socket=0x750f7c2dc718), (incoming.addr=109.20.138.158:49777)(incoming_=0)
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - TCPPort::OnAcceptEvent (tcpport=0x750f7c618c10), (socket=0x750f7c7501d8), (incoming.addr=188.44.91.207:55904)(incoming_=0)
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
CtrlCHandler: Signal=2
10:32:20: start
10:32:20: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32333\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\?Port=7776\?QueryPort=27016\?ServerAdminPassword=****\?MaxPlayers=60\?GameModIds=684959100\,558079412\,534838287\,704420972\,572277026\,670764308\,564895376\,519536568\,600015460\,680798000\,566887000\,543859212\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -newsaveformat -server -UseBattlEye
10:32:20: Server PID: 8063
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager : ligne 723 : 25020 Abandon                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
10:32:21: Bad PID '8063'; expected '25020'
Error: another server instance is running from the same directory
Aborting - two servers MUST NOT run from the same directory
10:32:21: exited with status 0
Using binned.

**Comment by klightspeed** [comment]
The commit I pushed should fix this - `arkmanager stop` should now kill the monitor process (though the first restart after upgrading won't do this, as the pid file won't yet exist).

**Comment by arkfrance** [comment]
ok i've just updated it another thing :+1: 


root@arkfrancegaming:~# su steam
steam@arkfrancegaming:/root$ arkmanager useconfig pve update --update-mods --warn
Running command 'update' for instance 'pve'
/etc/arkmanager/arkmanager-pve.cfg: ligne 60: arkflag_automanagemods : command not found
Downloading mod 519536568 ... Mod 519536568 downloaded
Downloading mod 534838287 ... Mod 534838287 downloaded
Downloading mod 543859212 ... Mod 543859212 downloaded
Downloading mod 558079412 ... Mod 558079412 downloaded
Downloading mod 564895376 ... Mod 564895376 downloaded
Downloading mod 566887000 ... Mod 566887000 downloaded
Downloading mod 572277026 ... Mod 572277026 downloaded
Downloading mod 600015460 ... Mod 600015460 downloaded
Downloading mod 670764308 ... Mod 670764308 downloaded
Downloading mod 680798000 ... Mod 680798000 downloaded
Downloading mod 684959100 ... Mod 684959100 downloaded
Downloading mod 704420972 ... Mod 704420972 downloaded
Your server is already up to date! The most recent version is 1222386.
steam@arkfrancegaming:/root$

**Comment by klightspeed** [comment]
> ```
/etc/arkmanager/arkmanager-pve.cfg: ligne 60: arkflag_automanagemods : command not found
```

Use `arkflag_automanagemods=true`

**Comment by arkfrance** [comment]
it's inside but maybe i need to restart to enable it, the server is already online

**Comment by arkfrance** [comment]
seems to be the same with a restart 

CtrlCHandler: Signal=2
16:04:18: start
16:04:18: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32333\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\?Port=7776\?QueryPort=27016\?ServerAdminPassword=**\?MaxPlayers=60\?GameModIds=684959100\,558079412\,534838287\,704420972\,572277026\,670764308\,564895376\,519536568\,600015460\,680798000\,566887000\,543859212\?AllowRaidDinoFeeding=true\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -newsaveformat -server -UseBattlEye
16:04:18: Server PID: 27120
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager : ligne 723 :  8063 Abandon                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
16:04:19: Bad PID '27120'; expected '8063'
Error: another server instance is running from the same directory
Aborting - two servers MUST NOT run from the same directory
16:04:19: exited with status 0

**Comment by klightspeed** [comment]
I did say that the error will still occur the first time restarting after upgrading, as the pid file won't yet exist.

**Comment by arkfrance** [comment]
ok :)
