### ISSUE TITLE
Mods keeps updating

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#542]
Hi,

a mod updated in the workshop still updating even if i don't use it anymore in my arkmanager.cfg

714672786 / indominus rex

i tried to arkmanager remove-mods 714672786

but it re download back

any clue ?

**Comment by klightspeed** [comment]
Does the `714672786` directory exist in `$arkserverroot/ShooterGame/Content/Mods`?

`arkmanager remove-mods` only removes the mod from the steamcmd workshop directory and manifest.

Try running `arkmanager uninstallmod @instance 714672786`

**Comment by arkfrance** [comment]
i've finally manage to remove it ! shit indominus rex :dart:
