### ISSUE TITLE
Error in cpp when i've updated arkmanager

### ISSUE THREAD

**Issue by Torath0071** [FezVrasta/ark-server-tools#545]
Hi,
After an upgrade of arkmanager, i restart my server and it would not start because of an error

> 14:06:22: start
14:06:22: Running /home/torath/ARK/Server/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?EnableExtraStructurePreventionVolumes=true\?GameModIds=569786012\,630601751\,538986229\,572277026\,510590313\,693416678\,655581765\?MaxPlayers=50\?NonPermanentDiseases=true\?Port=3007\?QueryPort=3005\?RCONEnabled=True\?RCONPort=3000\?RCONServerGameLogBuffer=10000\?ServerAdminPassword=Plkna27\?ServerPassword\?SessionName=\[FR\]\[PVE\]Masters\ of\ War\[Allx10\]\?ShowFloatingDamageText=true\?listen -DisableDeathSpectator -OnlyAdminRejoinAsSpectator -USEALLAVAILABLECORES -UseBattlEye -automanagedmods -nomansky -nomemorybias -servergamelog -usecache
14:06:22: Server PID: 25137
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:G:\SVN_Ark\Engine\Source\Runtime\Core\Private\Linux\LinuxPlatformProcess.cpp] [Line: 652] 
FLinuxPlatformProcess::WaitForProc: waitid for pid -1 failed (errno=22, Invalid argument)
Signal 11 caught.
/usr/local/bin/arkmanager : ligne 662 : 25137 Erreur de segmentation  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
14:06:27: Bad PID ''; expected '25137'
14:06:27: exited with status 0

Any idea ?

**Comment by Torath0071** [comment]
the error occur when i start the server with the option -automanagedmods and the section in Game.ini

**Comment by klightspeed** [comment]
arkmanager should have downloaded `steamcmd` into `$arkserverroot/Engine/Binaries/ThirdParty/SteamCMD/Linux`, which is where the ARK server expects to find it when using the `-automanagedmods` option.

Does `/home/torath/ARK/Server/PVE/Engine/Binaries/ThirdParty/SteamCMD/Linux` exist, and if it does, what are its contents?

**Comment by Torath0071** [comment]
`/home/torath/ARK/Server/PVE/Engine/Binaries/ThirdParty/SteamCMD/Linux` does not exist 
i have only `Win64/steamcmd.exe` in SteamCMD directory

**Comment by klightspeed** [comment]
Are there any lines immediately above the `start` line in the log?

**Comment by Torath0071** [comment]
No, when start is printed, the next line is "Running ..."

**Comment by klightspeed** [comment]
What are the lines **before** the `start` line?

**Comment by Torath0071** [comment]
Oh sorry ^^
the lines before are from previous run

> 14:05:11: Bad PID ''; expected '24777'
14:05:11: exited with status 0

**Comment by klightspeed** [comment]
What is the output of `arkmanager --version`?

**Comment by Torath0071** [comment]
> Version: 1.5
Channel: master
Commit: 3486d03

**Comment by klightspeed** [comment]
You'll have to create `/home/torath/ARK/Server/PVE/Engine/Binaries/ThirdParty/SteamCMD/Linux` and extract steamcmd directly to that directory, as 1.5 doesn't include the `automanagedmods` support.

**Comment by Torath0071** [comment]
Ok ty, i will try later and report to you

**Comment by Torath0071** [comment]
Hi, sorry for the long time.
i've solved the issue by remove lines in GameUserSettings.ini ( for automanagemod ) 
Thx for your help
