### ISSUE TITLE
server stops and restarts 

### ISSUE THREAD

**Issue by badboysgaming** [FezVrasta/ark-server-tools#546]
been having issues lately server will just dc everyone and restart

> 04:40:58: start
/usr/local/bin/arkmanager: line 656: ulimit: open files: cannot modify limit: Operation not permitted
04:40:58: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?MapModID=699345617\?AllowFlyerCarryPVE=true\?DifficultyOffset=4\?DinoCountMultiplier=1.5\?EnableExtraStructurePreventionVolumes=true\?ForceAllStructureLocking=true\?GameModIds=635723262\,609380111\,572277026\,539464369\,719928795\,706319066\,722649005\,676288311\,519536568\,670764308\,723139322\,708807240\,566887000\,725398419\,695998908\,715894094\,680481868\,569786012\?MaxPlayers=200\?Port=7776\?PreventOfflinePvP=true\?PreventOfflinePvPInterval=60.0\?PvPDinoDecay=true\?PvPStructureDecay=true\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=*********\?ServerPassword\?bRawSockets\?listen -ForceAllowCaveFlyers -log -server -servergamelog -useallavailablecores
04:40:58: Server PID: 4495
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
04:43:05: server is up
Signal 11 caught.
/usr/local/bin/arkmanager: line 662:  4495 Segmentation fault      (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
05:08:19: Bad PID ''; expected '4495'
05:08:19: exited with status 0
05:08:19: restarting server
05:08:19: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?MapModID=699345617\?AllowFlyerCarryPVE=true\?DifficultyOffset=4\?DinoCountMultiplier=1.5\?EnableExtraStructurePreventionVolumes=true\?ForceAllStructureLocking=true\?GameModIds=635723262\,609380111\,572277026\,539464369\,719928795\,706319066\,722649005\,676288311\,519536568\,670764308\,723139322\,708807240\,566887000\,725398419\,695998908\,715894094\,680481868\,569786012\?MaxPlayers=200\?Port=7776\?PreventOfflinePvP=true\?PreventOfflinePvPInterval=60.0\?PvPDinoDecay=true\?PvPStructureDecay=true\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=*******\?ServerPassword\?bRawSockets\?listen -ForceAllowCaveFlyers -log -server -servergamelog -useallavailablecores
05:08:19: Server PID: 8139
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
05:10:26: server is up

**Comment by klightspeed** [comment]
@arkfrance mentioned that some characters in chat (specifically the % symbol) can cause the server to crash when using `-servergamelog`

**Comment by klightspeed** [comment]
I have confirmed that Wildcard appears to be using `fprintf` with the second argument (the format) being set to the message.  Therefore e.g. someone saying "Hello %f" will write "Hello 0.000000" to the log, and someone saying "Hello %s %s %s" will crash the server.

**Comment by arkfrance** [comment]
https://survivetheark.com/index.php?/forums/topic/8280-server-game-log-server-stability-note-for-server-admins/

**Comment by badboysgaming** [comment]
-servergamelog was disabled but still crashing and restarting if i try to do certain in game commands like tame or forcetame

**Comment by rob-bb** [comment]
I have been getting the same issue, pretty sure its Ark server and not ark-server-tools that is the issue.
