### ISSUE TITLE
crash line 740

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#547]
A lot of that 740 line crash these days, anyone got the same ?

/usr/local/bin/arkmanager : ligne 740 : 30797 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
17:41:15: Bad PID ''; expected '30797'
17:41:15: exited with status 0
17:41:15: restarting server
17:41:15: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32333\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\?Port=7776\?QueryPort=27016\?ServerAdminPassword=****\?MaxPlayers=60\?GameModIds=684959100\,558079412\,534838287\,704420972\,572277026\,670764308\,564895376\,600015460\,680798000\,566887000\,543859212\?AllowRaidDinoFeeding=true\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -newsaveformat -automanagemods -server -UseBattlEye
17:41:15: Server PID: 5208
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
/usr/local/bin/arkmanager : ligne 740 :  5208 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
21:39:05: Bad PID ''; expected '5208'
21:39:05: exited with status 0
21:39:05: restarting server
21:39:05: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32333\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\?Port=7776\?QueryPort=27016\?ServerAdminPassword=****\?MaxPlayers=60\?GameModIds=684959100\,558079412\,534838287\,704420972\,572277026\,670764308\,564895376\,600015460\,680798000\,566887000\,543859212\?AllowRaidDinoFeeding=true\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -newsaveformat -automanagemods -server -UseBattlEye
21:39:05: Server PID: 23743
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
/usr/local/bin/arkmanager : ligne 740 : 23743 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
23:03:36: Bad PID ''; expected '23743'
23:03:36: exited with status 0
23:03:36: restarting server
23:03:36: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32333\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\?Port=7776\?QueryPort=27016\?ServerAdminPassword=****\?MaxPlayers=60\?GameModIds=684959100\,558079412\,534838287\,704420972\,572277026\,670764308\,564895376\,600015460\,680798000\,566887000\,543859212\?AllowRaidDinoFeeding=true\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -newsaveformat -automanagemods -server -UseBattlEye
23:03:36: Server PID: 21596
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.
/usr/local/bin/arkmanager : ligne 740 : 21596 Erreur de segmentation  (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
14:22:28: Bad PID ''; expected '21596'
14:22:28: exited with status 0
14:22:28: restarting server
14:22:28: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32333\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\?Port=7776\?QueryPort=27016\?ServerAdminPassword=****\?MaxPlayers=60\?GameModIds=684959100\,558079412\,534838287\,704420972\,572277026\,670764308\,564895376\,600015460\,680798000\,566887000\,543859212\?AllowRaidDinoFeeding=true\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -newsaveformat -automanagemods -server -UseBattlEye
14:22:28: Server PID: 17547
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

**Comment by badboysgaming** [comment]
mine seem to happen when i use cheat dotame or forcetame very strange
