### ISSUE TITLE
incorrect display of online players

### ISSUE THREAD

**Issue by lafaetos** [FezVrasta/ark-server-tools#548]
Hello, sorry for trouble you, but i have a problem
in status writes wrong count players online. sometimes writes 5/10 but server is empty
can you help my? thanks
have a good day
sorry for my bad english

i install version of tools - 1.5
of server - 244.7

**Comment by klightspeed** [comment]
The player count is what is reported by the [A2S_INFO](https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO) query, which is the same as what is reported by the Steam client and the ARK client.  As evidenced by arkservers.net, the player count reported by this query seems to be the number of people trying to connect to the server.

**Comment by lafaetos** [comment]
hello, thks for your reply

I drew attention to the fact that if you go right from the game, it shows the correct number of players, and if you turn off in the middle of downloading, it is not

maybe i can set timeout, and after "n" minutes this fake player disconnect? but i don't know what this parametr :(
or this count It has no effect on the parameter ifempty?

**Comment by klightspeed** [comment]
`1.6-dev.unstable` now has the option to use the `A2S_PLAYERS` query to get the number of players that are active on the server.
With `1.6-dev.unstable`, add `arkUsePlayerList=true` to enable using the `A2S_PLAYERS` query instead of the `A2S_INFO` query to determine whether the server is empty.

**Comment by lafaetos** [comment]
ok,thks 
i try to use 1.6-dev.unstable

**Comment by StevenB83** [comment]
This would be a nice feature as heavily modded servers are almost never "empty" even if it actually is.

Is this feature currently working? I have the latest ``1.6-dev.unstable`` and have put ``arkUsePlayerList=true`` in both the arkmanager.cfg and instance config file to be sure.
``arkmanager status`` and updating the server still reports the same amount of ghost players.

Steven.

**Comment by klightspeed** [comment]
`arkUsePlayerList=true` changes `--ifempty` and `--warn` to use the player list to determine if anybody is on the server.

The number of active players should be on the `Active players` line of the status output.

**Comment by StevenB83** [comment]
Hi, there was only one actual player on the server when I ran this command. Steam shows 5/50 and ARK 1/50 on another computer.

Should ``Active Players`` use the ``A2S_PLAYERS`` instead of ``A2S_INFO`` if the setting ``arkUsePlayerList=true`` is enabled?

```
arkmanager useconfig thecenter status
Running command 'status' for instance 'thecenter'
 Server running:   Yes
 Server listening:   Yes
Server Name:  - (v245.92)
Players: 5 / 50
Active Players: 5
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/
 Server build ID:   1254550
 Server version:   245.92
```

Steven.

**Comment by klightspeed** [comment]
What does the arkservers.net link report?

**Comment by StevenB83** [comment]
It reports the incorrect 5/50 as well.

Steven.

**Comment by klightspeed** [comment]
If it reports 5 players, and gives names for all 5, then there's nothing we can do to but report that 5 players are connected.

**Comment by StevenB83** [comment]
There is no names listed for the players except the one actually on the server.

**Comment by klightspeed** [comment]
That sounds like we need to count the number of players that have a name.

**Comment by StevenB83** [comment]
The rcon playerlist shows only the current player that is actually on the server,

**Comment by klightspeed** [comment]
I have pushed a change to 1.6-dev.unstable that counts the number of players that are named.  This should return the correct number of players.

**Comment by StevenB83** [comment]
Here is the output while there is one actual player online on the server and one connecting (me).
Before I tried connecting it said 1 / 50 on Players and 0 Active.

```
arkmanager useconfig thecenter status
Running command 'status' for instance 'thecenter'
 Server running:   Yes
 Server listening:   Yes
Server Name:   - (v245.93)
Players: 2 / 50
Active Players: 0
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/ 
 Server build ID:   1255371
 Server version:   245.92
```

**Comment by klightspeed** [comment]
I made a mistake using `!=` instead of `ne` when comparing strings in perl.  Try with the latest commit to 1.6-dev.unstable.

**Comment by lafaetos** [comment]
Just updated versib and I normally shows the number of players

In general, I use a mini script:

```
#!/bin/bash
arkmanager rconcmd listplayers > /steam/scripts/ponline
a=$(cat /steam/scripts/ponline| wc -l /steam/scripts/ponline|cut -c1-2)
echo $[$a-3] >/steam/scripts/nponline
cp -rf /steam/scripts/nponline /var/www/html/nponline.html
```

then the data is loaded to the site and zabbix

**Comment by StevenB83** [comment]
The latest commit seems to be working, shows 2 / 50 but only 1 Active player (which is correct).
