### ISSUE TITLE
Downloading mod 111111111 ...

### ISSUE THREAD

**Issue by StevenB83** [FezVrasta/ark-server-tools#551]
Hi,
arkmanager started acting very strange after 245.0 update.

Before update it checked for updates to all the mods listed in ``/etc/arkmanager/instances/theisland.cfg`` and updated the server to 245.0 (went fine as usual :+1:)

After 245.0 update (never seen this before) it just tries to download mod 111111111 which I cannot find in any config files anywhere also it doesn't try to download the mods in the config files.
The config files and arkmanager has not been altered for a long time and I have quadruplechecked the config files just to be sure.

``/usr/local/bin/arkmanager``, ``/etc/arkmanager/arkmanager.cfg`` and ``/etc/arkmanager/instances/theisland.cfg`` has NOT been altered in over a month, also they are identical to my backups (checked with diff).
I cannot see any reason for this change in behaviour.
Is this happening for others?

Upon further investigation it seems that ``111111111.mod`` in ``/home/steam/theisland/ShooterGame/Content/Mods`` is related to Primitive+ dlc..

Perhaps this should be excluded from update checking? gg Wildcard :p

```
$ arkmanager useconfig theisland update --update-mods --warn --saveworld --backup --verbose
Running command 'update' for instance 'theisland'
Downloading mod 111111111Executing /home/steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +workshop_download_item 346110 111111111 +quit
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Downloading item 111111111 ...
ERROR! Download item 111111111 failed (File Not Found).Mod 111111111 was not successfully downloaded
/usr/local/bin/arkmanager: line 1594: /home/steam/steamcmd/steamapps/workshop/content/346110/111111111/mod.info: No such file or directory
Your server is already up to date! The most recent version is 1250570.
```

EDIT:  After removal of ``111111111.mod`` and ``111111111`` directory ``--update-mods`` works fine again.

**Comment by boranblok** [comment]
I can confirm this issue and workaround. Moving 111111111 to a temporary subfolder fixed my update issues.

**Comment by klightspeed** [comment]
So did Wildcard Studios put a "111111111" directory in their Mods directory?

**Comment by megoix** [comment]
Editing the 111111111.mod file would seem to indicate its the new DLC; Primitive Plus.

**Comment by astappev** [comment]
I also can confirm the issue.
And yes, the 111111111.mod and 111111111 folder were placed directly in the ./ShooterGame/Content/Mods folder.

**Comment by klightspeed** [comment]
I have pushed a hotfix to ignore mod 111111111

**Comment by arkfrance** [comment]
don't have any folder on my /mods, only have the 111111111.mod

**Comment by arkfrance** [comment]
i had to upload my folder to the server

**Comment by Micha-N** [comment]
Running a Prim+ server.
Seems that with this hotfix the mod folder gets removed and so the server is unable to launch.
Copying it back from staging the server launches and restart due to an "update". After that the folder is gone and the server crashes

**Comment by klightspeed** [comment]
This hotfix (8a59a8c) should resolve this.

**Comment by StevenB83** [comment]
Sorry for not responding sooner, the first patch caused false updates from time to time.
However the latest ( https://github.com/FezVrasta/ark-server-tools/commit/8a59a8c78c2b1cc052207474e5be132a54fb10b5 ) did solve the issue for me. :+1: 

Steven.
