### ISSUE TITLE
Primitive+

### ISSUE THREAD

**Issue by thymon13** [FezVrasta/ark-server-tools#552]
I all !

I'm sorry but I don't understand, how I can use the new primitive + (DLC) on my Dedicated server ?
ark_TotalConversionMod="111111111"  doesn't works...

**Comment by klightspeed** [comment]
https://steamcommunity.com/app/346110/discussions/0/353915309338029984

One person in that discussion used both `TotalConversionMod=111111111` and `GameModIds=111111111`.

If the `111111111` directory does not exist in your mods directory (that isn't a valid mod ID, so it can't be downloaded from the workshop), then try using `arkmanager update --validate`

**Comment by thymon13** [comment]
Really thank you !
