### ISSUE TITLE
Double updateing

### ISSUE THREAD

**Issue by Chingis-Khan** [FezVrasta/ark-server-tools#553]
Hi, 

I have a cron job that checks for updates every 30 mins. with this:
/usr/local/bin/arkmanager update --update-mods --warn --saveworld 

But all weekend it seesm to be updateing, then 30 misn later shuting down for an update but the second update seems to do nothing, the client does not update nor does it download any mods on the second one, but does first pass. 

Any idea what is happening?

**Comment by rob-bb** [comment]
Yes I know, but it's not that.,   

When the arkmanger then the clients usually do as well, if it is a mod update then they definitely will, and most server updates are also client updates (but not always)

But what I have been seeing today is when ark updates the next cron job will also trigger the shutdown for update but nothing is updated as far as I can tell.  All day it has been this way.

**Comment by klightspeed** [comment]
Do you have `111111111` in your `ShooterGame/Content/Mods` directory?  If so, then the hotfix that ignores the Primitive+ "mod" will be needed.

**Comment by rob-bb** [comment]
Ok, installing the hotfix, cheers, do I need to worry about this message?


WARNING: A previous version of ARK Server Tools was detected in your system, your old configuration was not overwritten. You may need to manually update it.
ARK Server Tools were correctly installed in your system inside the home directory of steam!

**Comment by klightspeed** [comment]
This message just means that an existing config was found (expected).  Since no changes occurred to the default config, you can ignore this.

**Comment by arkfrance** [comment]
Please, close your ticket if you think it's resolved :)
