### ISSUE TITLE
Your ARK server exec could not be found.

### ISSUE THREAD

**Issue by GyabanT** [FezVrasta/ark-server-tools#554]
Hello,

I have install Arkmanager, and when i try to start, it write me `Your ARK server exec could not be found.`

In my config file i have "arkserverexec="/home/steamsrv/ark/ShooterGame/Binaries/Linux/ShooterGameServer" and it is the good way.

what i have to do ?

**Comment by klightspeed** [comment]
`arkserverexec` should not need to be changed unless you are using arkmanager to run another server where the executable is not located at `ShooterGame/Binaries/Linux/ShooterGameServer` within the ARK server directory.

**Comment by GyabanT** [comment]
ark server is located in "ark" directory and not "ARK" maybe is it the problem ?

**Comment by klightspeed** [comment]
Set the following settings:

```
arkserverroot="/home/steamsrv/ark"
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"
```

**Comment by GyabanT** [comment]
Thank you, problem solved

**Comment by arkfrance** [comment]
Please, close your ticket if you think it's resolved :)

**Comment by douglasg14b** [comment]
@arkfrance Can this be put into the readme? It was very confusing trying to figure out where this tool was trying to start its `relative path` from since that is not mentioned. I only know now that I have found this issue
