### ISSUE TITLE
Servers are offline but running.

### ISSUE THREAD

**Issue by Torath0071** [FezVrasta/ark-server-tools#557]
Hi, 
i've 3 servers on the same dedicated server and they all run perfectly but when i use `arkmanager useconfig pve status` the line Server online always say No

> arkmanager useconfig pve status
Running command 'status' for instance 'pve'
 Server running:   Yes
 Server listening:   Yes
Server Name: [FR][PVE]Masters of War[Allx10] - (v245.93)
Players: 8 / 50
 Server online:   No
 Server version:   1255371

And sometime, players tell me they can't see my server in favorite list.
When they visit my website, the server appear by magic.

Thx for your help

**Comment by Torath0071** [comment]
All mods are up to date and server too

**Comment by klightspeed** [comment]
`Online: no` means that the server isn't showing up on the Steam servers list.

Does the following URL (where `$IP` is replaced with your server IP address, and $port is replaced with your query port) list the server?

http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=$IP:$port&format=json

**Comment by Torath0071** [comment]
> {
	"response": {
		"success": true,
		"servers": [
			{
				"addr": "151.80.230.79:3005",
				"gmsindex": 65534,
				"appid": 346110,
				"gamedir": "ark_survival_evolved",
				"region": -1,
				"secure": true,
				"lan": false,
				"gameport": 3007,
				"specport": 0
			}
		]
		
	}
}

**Comment by klightspeed** [comment]
Is your server multi-homed (i.e. has multiple internet interfaces)?  Is its IP address dynamic?

**Comment by Torath0071** [comment]
yes, 2 days ago i've added multihome option with value 127.0.0.1
i just remove multihome from my test server and the result is the same.
it's a dedicated server rent to SoYouStart ( OVH sub-company ) https://www.soyoustart.com/fr/offres/game-2.xml
The website is on the same server.

Here is the list of all my gameservers on my server 

> {
	"response": {
		"success": true,
		"servers": [
			{
				"addr": "151.80.230.79:3005",
				"gmsindex": 65534,
				"appid": 346110,
				"gamedir": "ark_survival_evolved",
				"region": -1,
				"secure": true,
				"lan": false,
				"gameport": 3007,
				"specport": 0
			},
			{
				"addr": "151.80.230.79:4005",
				"gmsindex": 65534,
				"appid": 346110,
				"gamedir": "ark_survival_evolved",
				"region": -1,
				"secure": true,
				"lan": false,
				"gameport": 4007,
				"specport": 0
			},
			{
				"addr": "151.80.230.79:10005",
				"gmsindex": 65534,
				"appid": 346110,
				"gamedir": "ark_survival_evolved",
				"region": -1,
				"secure": true,
				"lan": false,
				"gameport": 10007,
				"specport": 0
			}
		]
		
	}
}

**Comment by klightspeed** [comment]
Was the pve server the test server?  If so, arkmanager would have been trying to grab the public IP address of your loopback interface and failing.

**Comment by Torath0071** [comment]
no, the test server is on port 10005 and pve on 3005
i've removed multihome from test.
pve and pvp already have multihome

**Comment by klightspeed** [comment]
Multihome is not required if you only have one interface connecting to the internet.

**Comment by Torath0071** [comment]
ok i remove it for the next reboot.

Now my servers are up in steam list. oO
Only the test server is not in it.

it's happen often randomly
