### ISSUE TITLE
error when arkmanager update

### ISSUE THREAD

**Issue by super54** [FezVrasta/ark-server-tools#56]
When I run an update, i have this : 

My script is in /home/steam/steamcmd, i have configure .cfg 

arkmanager.cfg :
```
# config SteamCMD
steamcmdroot="/home/steam/steamcmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="steam"                                               # name of the system user who own steamcmd folder

# config Server
sessioname=YourLinuxSessionName
arkserverroot="/home/steam/steamcmd"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
```

ERROR :
```
arkmanager update
/usr/bin/arkmanager: ligne 70 : [:  : nombre entier attendu comme expression
The server is already stopped
Redirecting stderr to '/root/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API.../home/buildbot/buildslave/steam_rel_client_linux/build/src/clientdll/applicationmanager.cpp (3030) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
/home/buildbot/buildslave/steam_rel_client_linux/build/src/clientdll/applicationmanager.cpp (3030) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
/home/buildbot/buildslave/steam_rel_client_linux/build/src/clientdll/applicationmanager.cpp (3181) : Assertion Failed: m_vecInstallBaseFolders.Count() > 0
/home/buildbot/buildslave/steam_rel_client_linux/build/src/steamconsole/../common/steam/client_api.cpp (393) : Assertion Failed: ClientAPI_Init(GlobalInstance): GetIClientRemoteControlManager returned NULL.
FAILED.
```
Thank you for your responce

**Comment by FezVrasta** [comment]
```
arkserverroot="/home/steam/steamcmd"   
```

this is terribly wrong, you must specify the folder where the ARK server is stored, not the folder where steamcmd is stored

**Comment by klightspeed** [comment]
The "nombre entier attendu comme expression" error (en_US equivalent: "integer expression expected") is printed because you are attempting an update without first having performed an install.

Second, it looks like you have $HOME set to /root, which is not accessible by a normal user, which is likely the reason you are getting the assertion failures from steamcmd.

**Comment by super54** [comment]
Fez : my game is in /home/steam/steamcmd/shooter...

Klight : yes i have create a New installation for this script 

Yes ok its in root $home if i start with root its thé same

**Comment by FezVrasta** [comment]
that's bad, steamcmd and the ARK server should be in two different folders. It can cause problems when steamcmd tries to update because it have to touch the same folder of the steamcmd executable.

steamcmd should be never ran as root, so you should not use the root folder.

If you are not willing to follow the best practice we can't help you.

**Comment by klightspeed** [comment]
It you start it as root, then it should be telling you "This script must NOT be run as root".

It looks like you switched to the steam user using something like `su -p steam`.  Drop the -p, and su should set the correct home directory (/home/steam).

**Comment by super54** [comment]
Ok,
I create new directory :

/home/steam/cmd
/home/steam/ark

I configure .cfg with new directory

I use command with steam user
 - arkmanager install
and
 - arkmanager update

and commands finish with success

Thanks for your help, good deamon :D
