### ISSUE TITLE
Can't install all mods in once

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#560]
arkmanager useconfig mmo installmod
Running command 'installmod' for instance 'mmo'
[  ERROR  ] 	Mod 496026322 is requested but not installed.  Run 'arkmanager installmod 496026322' to install this mod.
[  ERROR  ] 	Mod 510590313 is requested but not installed.  Run 'arkmanager installmod 510590313' to install this mod.
[  ERROR  ] 	Mod 512633537 is requested but not installed.  Run 'arkmanager installmod 512633537' to install this mod.
[  ERROR  ] 	Mod 531713045 is requested but not installed.  Run 'arkmanager installmod 531713045' to install this mod.
[  ERROR  ] 	Mod 538827119 is requested but not installed.  Run 'arkmanager installmod 538827119' to install this mod.
[  ERROR  ] 	Mod 538986229 is requested but not installed.  Run 'arkmanager installmod 538986229' to install this mod.
[  ERROR  ] 	Mod 554678442 is requested but not installed.  Run 'arkmanager installmod 554678442' to install this mod.
[  ERROR  ] 	Mod 558079412 is requested but not installed.  Run 'arkmanager installmod 558079412' to install this mod.
[  ERROR  ] 	Mod 564895376 is requested but not installed.  Run 'arkmanager installmod 564895376' to install this mod.
[  ERROR  ] 	Mod 566885854 is requested but not installed.  Run 'arkmanager installmod 566885854' to install this mod.
[  ERROR  ] 	Mod 566887000 is requested but not installed.  Run 'arkmanager installmod 566887000' to install this mod.
[  ERROR  ] 	Mod 575503459 is requested but not installed.  Run 'arkmanager installmod 575503459' to install this mod.
[  ERROR  ] 	Mod 578592447 is requested but not installed.  Run 'arkmanager installmod 578592447' to install this mod.
[  ERROR  ] 	Mod 599476919 is requested but not installed.  Run 'arkmanager installmod 599476919' to install this mod.
[  ERROR  ] 	Mod 600015460 is requested but not installed.  Run 'arkmanager installmod 600015460' to install this mod.
[  ERROR  ] 	Mod 600705968 is requested but not installed.  Run 'arkmanager installmod 600705968' to install this mod.
[  ERROR  ] 	Mod 605096060 is requested but not installed.  Run 'arkmanager installmod 605096060' to install this mod.
[  ERROR  ] 	Mod 608800320 is requested but not installed.  Run 'arkmanager installmod 608800320' to install this mod.
[  ERROR  ] 	Mod 609380111 is requested but not installed.  Run 'arkmanager installmod 609380111' to install this mod.
[  ERROR  ] 	Mod 639066374 is requested but not installed.  Run 'arkmanager installmod 639066374' to install this mod.
[  ERROR  ] 	Mod 658112994 is requested but not installed.  Run 'arkmanager installmod 658112994' to install this mod.
[  ERROR  ] 	Mod 668650977 is requested but not installed.  Run 'arkmanager installmod 668650977' to install this mod.
[  ERROR  ] 	Mod 670764308 is requested but not installed.  Run 'arkmanager installmod 670764308' to install this mod.
[  ERROR  ] 	Mod 670869235 is requested but not installed.  Run 'arkmanager installmod 670869235' to install this mod.
[  ERROR  ] 	Mod 695610849 is requested but not installed.  Run 'arkmanager installmod 695610849' to install this mod.
[  ERROR  ] 	Mod 704420972 is requested but not installed.  Run 'arkmanager installmod 704420972' to install this mod.
[  ERROR  ] 	Mod 716406300 is requested but not installed.  Run 'arkmanager installmod 716406300' to install this mod.
[  ERROR  ] 	Mod 719928795 is requested but not installed.  Run 'arkmanager installmod 719928795' to install this mod.
[  ERROR  ] 	You have not rights to write in the log directory.
Downloading mod  ...  
Mod  download failed
Mod  was not successfully downloaded

Maybe a command to install all in once would be great ?

**Comment by klightspeed** [comment]
So make `arkmanager installmod` with no argument be a synonym for `arkmanager update --update-mods`?

**Comment by arkfrance** [comment]
something like arkmanager installmod --all

**Comment by arkfrance** [comment]
If that works no need to add more then, i'm gonna try

**Comment by klightspeed** [comment]
I have added a `installmods` command, which just installs all of the requested mods without performing an update.

**Comment by arkfrance** [comment]
great i'm updating the tool

**Comment by arkfrance** [comment]
/usr/local/bin/arkmanager: line 1809: getModids: command not found

**Comment by klightspeed** [comment]
Typo (darn shift).  Should be fixed in 2bc7c3e

**Comment by arkfrance** [comment]
yep very usefull command ! Thanks ! don't forget to add it on the description :)
