### ISSUE TITLE
ARK Session name

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#562]
Hi,

i've re install the whole arkmanager and all of my game server on another engine

i've 2 questions : one of my server's name is 

ark_SessionName="ARK FRANCE OFFICIEL - PvE x5 Valhalla"

but in the ini it shows : 

[SessionSettings]
SessionName=ARK #268937

Where does it comes from ?

is my arkmanager.cfg looks good ?

configfile_centpve="/etc/arkmanager/arkmanager-center-pve.cfg"
configfile_mmo="/etc/arkmanager/arkmanager.cfg"
configfile_centpvp="/etc/arkmanager/arkmanager-center-pvp.cfg"
configfile_pve="/etc/arkmanager/arkmanager-pve.cfg"
configfile_val="/etc/arkmanager/arkmanager-val.cfg"
configfile_pri="/etc/arkmanager/arkmanager-primitive.cfg" defaultinstance="main"

2nd question 

is this line good ? configfile_pri="/etc/arkmanager/arkmanager-primitive.cfg" defaultinstance="main"

arkmanager useconfig pri status
Running command 'status' for instance 'pri'
Error: config file /etc/arkmanager/arkmanager-primitive.cfgdefaultinstance=main does not exist

i want to add an instance only for the primitive one, here is the main.cfg

arkserverroot="/home/PRI" 
serverMap="TheCenter"                                               # server map (default TheIsland)
#serverMapModId="515195633"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
ark_TotalConversionMod="111111111"                                 # Uncomment this to specify a total-conversion mod
ark_RCONEnabled="True"
ark_RCONPort="27033"
ark_Port="7780"                                                     # ARK server port (default 7778)
ark_QueryPort="27018"
ark_SessionName="[NEW]ARK FRANCE - Primitive + PVP x5 The Center"       # if your session name needs special characters please use the .ini instead
#ark_ServerPassword="cucu"                                              # ARK server password, empty: no password required to login
ark_ServerAdminPassword="$$$$"
ark_MaxPlayers="70"
ark_GameModIds=""                                         # Uncomment to specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF"    
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
arkflag_log=True
arkflag_newsaveformat=True
arkflag_UseBattlEye=true
arkflag_server=True
ark_ForceAllStructureLocking=true
ark_PreventTribeAlliances=true

**Comment by klightspeed** [comment]
> one of my server's name is
> 
> ark_SessionName="ARK FRANCE OFFICIEL - PvE x5 Valhalla"
> 
> but in the ini it shows :
> 
> [SessionSettings]
> SessionName=ARK #268937
> 
> Where does it comes from ?

The ARK server automatically creates a `SessionName=ARK #nnnnnn` when no `SessionName` is specified.  Is `SessionName` in the commandline that is being logged in the `arkserver.log` file?

> configfile_pri="/etc/arkmanager/arkmanager-primitive.cfg" defaultinstance="main"

These two settings need to be on separate lines.

> is this line good ? configfile_pri="/etc/arkmanager/arkmanager-primitive.cfg" defaultinstance="main"
> 
> arkmanager useconfig pri status
> Running command 'status' for instance 'pri'
> Error: config file /etc/arkmanager/arkmanager-primitive.cfgdefaultinstance=main does not exist

See above.

> i want to add an instance only for the primitive one, here is the main.cfg

`main.cfg` is only used when you don't specify an instance name.

**Comment by arkfrance** [comment]
it does : 

11:31:02: start
11:31:02: Running /home/VAL/ShooterGame/Binaries/Linux/ShooterGameServer Valhalla\?RCONEnabled=True\?RCONPort=27035\?SessionName=ARK\ FRANCE\ OFFICIEL\ -\ PvE\ x5\ Valhalla\?Port=7781\?QueryPort=27020\?ServerPassword=1\?ServerAdminPassword=ùùùù\?MaxPlayers=50\?GameModIds=684959100\,572277026\,558079412\,558651608\,564895376\,670764308\,704420972\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?listen -log -server -newsaveformat -UseBattlEye
11:31:02: Server PID: 9970
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager: line 771:  9970 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
11:33:42: Bad PID ''; expected '9970'
11:33:42: exited with status 0

**Comment by arkfrance** [comment]
Solved :)

**Comment by arkfrance** [comment]
arkmanager useconfig val stop
Running command 'stop' for instance 'val'
Stopping server...
/usr/local/bin/arkmanager: line 936: kill: (6517) - No such process
The server has been stopped
is that alright ?

**Comment by arkfrance** [comment]
When i launch the primitive, another one of my server shows up : arkmanager useconfig pri stop
Running command 'stop' for instance 'pri'
/etc/arkmanager/arkmanager-primitive.cfg: line 87: unexpected EOF while looking for matching `"'
/etc/arkmanager/arkmanager-primitive.cfg: line 88: syntax error: unexpected end of file
[  ERROR  ] 	Mod 496026322 is requested but not installed.  Run 'arkmanager installmod 496026322' to install this mod.
[  ERROR  ] 	Mod 510590313 is requested but not installed.  Run 'arkmanager installmod 510590313' to install this mod.
[  ERROR  ] 	Mod 512633537 is requested but not installed.  Run 'arkmanager installmod 512633537' to install this mod.
[  ERROR  ] 	Mod 531713045 is requested but not installed.  Run 'arkmanager installmod 531713045' to install this mod.
[  ERROR  ] 	Mod 538827119 is requested but not installed.  Run 'arkmanager installmod 538827119' to install this mod.
[  ERROR  ] 	Mod 538986229 is requested but not installed.  Run 'arkmanager installmod 538986229' to install this mod.
[  ERROR  ] 	Mod 554678442 is requested but not installed.  Run 'arkmanager installmod 554678442' to install this mod.
[  ERROR  ] 	Mod 558079412 is requested but not installed.  Run 'arkmanager installmod 558079412' to install this mod.
[  ERROR  ] 	Mod 564895376 is requested but not installed.  Run 'arkmanager installmod 564895376' to install this mod.
[  ERROR  ] 	Mod 566885854 is requested but not installed.  Run 'arkmanager installmod 566885854' to install this mod.
[  ERROR  ] 	Mod 566887000 is requested but not installed.  Run 'arkmanager installmod 566887000' to install this mod.
[  ERROR  ] 	Mod 575503459 is requested but not installed.  Run 'arkmanager installmod 575503459' to install this mod.
[  ERROR  ] 	Mod 578592447 is requested but not installed.  Run 'arkmanager installmod 578592447' to install this mod.
[  ERROR  ] 	Mod 599476919 is requested but not installed.  Run 'arkmanager installmod 599476919' to install this mod.
[  ERROR  ] 	Mod 600015460 is requested but not installed.  Run 'arkmanager installmod 600015460' to install this mod.
[  ERROR  ] 	Mod 600705968 is requested but not installed.  Run 'arkmanager installmod 600705968' to install this mod.
[  ERROR  ] 	Mod 605096060 is requested but not installed.  Run 'arkmanager installmod 605096060' to install this mod.
[  ERROR  ] 	Mod 608800320 is requested but not installed.  Run 'arkmanager installmod 608800320' to install this mod.
[  ERROR  ] 	Mod 609380111 is requested but not installed.  Run 'arkmanager installmod 609380111' to install this mod.
[  ERROR  ] 	Mod 639066374 is requested but not installed.  Run 'arkmanager installmod 639066374' to install this mod.
[  ERROR  ] 	Mod 658112994 is requested but not installed.  Run 'arkmanager installmod 658112994' to install this mod.
[  ERROR  ] 	Mod 668650977 is requested but not installed.  Run 'arkmanager installmod 668650977' to install this mod.
[  ERROR  ] 	Mod 670764308 is requested but not installed.  Run 'arkmanager installmod 670764308' to install this mod.
[  ERROR  ] 	Mod 670869235 is requested but not installed.  Run 'arkmanager installmod 670869235' to install this mod.
[  ERROR  ] 	Mod 695610849 is requested but not installed.  Run 'arkmanager installmod 695610849' to install this mod.
[  ERROR  ] 	Mod 704420972 is requested but not installed.  Run 'arkmanager installmod 704420972' to install this mod.
[  ERROR  ] 	Mod 716406300 is requested but not installed.  Run 'arkmanager installmod 716406300' to install this mod.
[  ERROR  ] 	Mod 719928795 is requested but not installed.  Run 'arkmanager installmod 719928795' to install this mod.
Stopping server...
/usr/local/bin/arkmanager: line 936: kill: (9879) - No such process
The server has been stopped

**Comment by arkfrance** [comment]
Here is the primitive cfg 

arkstChannel="1.6-dev.unstable"                                               # change it to a different branch to get non-stable versions
install_bindir="/usr/local/bin"
install_libexecdir="/usr/local/libexec/arkmanager"
install_datadir="/usr/local/share/arkmanager"

# config SteamCMD
steamcmdroot="/home/steam/steamcmd/"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="steam"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/steam/Steam/appcache/appinfo.vdf"      # cache of the appinfo command
#steamlogin="anonymous" 

# config environment
arkserverroot="/home/PRI" 
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/ARK-Backups-PVP"                                    # path to backup directory
arkwarnminutes="5"                                                  # number of minutes to warn players when using update --warn
arkautorestartfile="ShooterGame/Saved/.autorestart"                 # path to autorestart file
arkBackupPreUpdate="false"                                          # set this to true if you want to perform a backup before updating
arkTimeToKeepBackupFiles="10"                                       #Set to Automatically Remove backups older than n days
#arkStagingDir="/home/steam/ARK-Staging"                             # Uncomment to enable updates to be fully downloaded before restarting the server (reduces downtime while updating)

# Options to automatically remove old backups to keep backup size in check
# Each compressed backup is generally about 1-2MB in size.
#arkMaxBackupSizeMB="500"                                            # Set to automatically remove old backups when size exceeds this limit
#arkMaxBackupSizeGB="2"                                             # Uncomment this and comment the above to specify the limit in whole GB
arkAutoUpdateOnStart="false"                                        # set this to true if you want to always update before startup

# Update warning messages

msgWarnReason="Le serveur va redemarrer dans {time} pour {reason}"
msgTimeMinutes="{minutes} minutes"
msgTimeSeconds="{seconds} secondes"
msgReasonUpdateMod="mettre a jour le mod {modnamesupdated}"
msgReasonUpdateApp="faire la mise a jour de ARK {version}(Reboot for ARK update). Les modifications sont disponibles sur notre site http://arkfrancegaming.com/. IL Y A UNE SAVE ET CELA NE POSE PAS DE PROBLEME POUR LE TAMING, AUGMENTEZ JUSTE LA TORPEUR"
msgReasonUpdateAppMod="mettre a jour le serveur et le mod {modnamesupdated}"
msgReasonRestart="ajouter la nouvelle méthode de sauvegarde/chargement sur les serveurs (4x plus rapide) et 75% plus petite"
msgReasonShutdown="passer le serveur en mod primitive +"
warnreason_1="Reboot quotidien, il est temps d'aller au lit les geeks !"

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheCenter"                                               # server map (default TheIsland)
#serverMapModId="515195633"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
ark_TotalConversionMod="111111111"                                 # Uncomment this to specify a total-conversion mod
ark_RCONEnabled="True"
ark_RCONPort="27033
ark_Port="7780"                                                     # ARK server port (default 7778)
ark_QueryPort="27018"
ark_SessionName="[NEW]ARK FRANCE OFFICIEL - Primitive + x5 The Center"       # if your session name needs special characters please use the .ini instead
ark_ServerPassword="cucu"                                              # ARK server password, empty: no password required to login
ark_ServerAdminPassword="oooo"
ark_MaxPlayers="70"
ark_GameModIds=""                                         # Uncomment to specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF"    
# Uncomment to specify a different save directory name
# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
arkflag_log=True
arkflag_newsaveformat=True
arkflag_UseBattlEye=true
arkAlwaysRestartOnCrash=true
arkflag_server=True
arkAllowRaidDinoFeeding=true
ark_ForceAllStructureLocking=true
ark_PreventTribeAlliances=true
# config Service
servicename="arkserv"                                               # Name of the service (don't change if you don't know what are you doing)
logdir="/var/log/arktools/pvp"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID
mod_appid=346110    
                                                # App ID for mods

# Mod OS Selection
mod_branch=Windows
# Add mod-specific OS selection below:
#mod_branch_496735411=Windows

# alternate configs
# example for config name "ark1":
#configfile_pve="/etc/arkmanager/arkmanager-pve.cfg"
#configfile_val="/etc/arkmanager/arkmanager-val.cfg"
#configfile_pvp="/etc/arkmanager/arkmanager.cfg"

**Comment by klightspeed** [comment]
Line 48:
> ```
ark_RCONPort="27033
```

You are missing the closing double-quote (`"`) character.

**Comment by arkfrance** [comment]
Very true ! omg 

arkmanager useconfig val stop
Running command 'stop' for instance 'val'
Stopping server...
/usr/local/bin/arkmanager: line 936: kill: (6517) - No such process
The server has been stopped
is that alright ?

**Comment by klightspeed** [comment]
I'll push a fix to silence that - it just means the monitor process exited before the `arkmanager stop` got around to to telling it to exit.

**Comment by arkfrance** [comment]
ok thanks :) just one thing off topic is that correct 

rsync -a ssh 149.202.86.142:/home/ARK-Backups-PVE/ 164.132.203.83:/home 
Unexpected remote arg: 149.202.86.142:/home/ARK-Backups-PVE/
rsync error: syntax or usage error (code 1) at main.c(1348) [sender=3.1.1]

I want to transfert folders from the old serveur to the new one

**Comment by klightspeed** [comment]
Drop the `ssh` argument.

With all but the most ancient versions of `rsync`, the remote shell used for the `host:path` remote path specification is `ssh`.

Also, in order to avoid unexpectedly copying the files to the wrong place, it is usually best to follow the source argument with `.`, and specify the full destination path.  e.g.
```
rsync -a 149.202.86.142:/home/ARK-Backups-PVE/. 164.132.203.83:/home/ARK-Backups-PVE
```

If you want to execute this on a schedule, it might be best to create a ssh key on the backup host, copy the public key into `$HOME/.ssh/authorized_keys` on the host being backed up, and then specify the path to the private key using the `-e "ssh -i /path/to/ssh/key"` argument to rsync.

For example, assuming user `ark-backup` exists on your backup server, and `ark-user` exists on your ARK server with read access to the `/home/ARK-Backups-PVE` directory:

```
user@localhost:~$ ssh ark-backup@164.132.203.83 "ssh-keygen -t rsa -f backup.key -N '' >&2; cat backup.key" | ssh ark-user@149.202.86.142 "cat >>~/.ssh/authorized_keys"
user@localhost:~$ ssh ark-backup@164.132.203.83
ark-backup@backups:~$ ssh ark-user@149.202.86.142
[confirm authenticity of host by typing yes]
ark-user@ark-server:~$ exit
ark-backup@backups:~$ echo "0 * * * * rsync -a -e 'ssh -i /home/ark-backup/backup.key' 149.202.86.142:/home/ARK-Backups-PVE/. /home/ARK-Backups-PVE" >~/ark-backup.crontab
ark-backup@backups:~$ crontab ~/ark-backup.crontab
```

**Comment by arkfrance** [comment]
rsync -a 149.202.86.142:/home/ARK-Backups-PVE/. 164.132.203.83:/home/ARK-Backups-PVE
The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at main.c(1279) [Receiver=3.1.1]

**Comment by klightspeed** [comment]
See above - it might be best to run the `rsync` from the server to which you wish to copy the ARK files.

**Comment by arkfrance** [comment]
164.132.203.83 is the new one, should it do that on the new one then ? ARK-Backups-PVE was a test to see if it works but i will try with the savedark folder next

**Comment by klightspeed** [comment]
Since `rsync` does not support syncing between two remote servers, yes, try running it from the new server.

**Comment by arkfrance** [comment]
root@arkfrance:~# ssh 149.202.86.142 tar -cj -C /home/ARK-Backups-PVE . | ssh 164.132.203.83 tar -xj -C /home/ARK-Backups-PVE
root@164.132.203.83's password: root@149.202.86.142's password: 


Nothing after i've entered my password

When i press ENTER 

Connection to 149.202.86.142 closed by remote host.

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by Lihis** [comment]
It is not good practice to have root account accessible via SSH.

**Comment by klightspeed** [comment]
It's not good practice to use password authentication on a publically accessible server.

Try the following:
* Create a public key / private key pair.
  - Run `ssh-keygen`
  - Press enter to accept the default key path of `$HOME/.ssh/id_rsa`
  - Type in the password you want to use for your key
  - Type in the password again to confirm
* Copy the contents of `$HOME/.ssh/id_rsa.pub`
* Connect to your old server - i.e. `ssh 149.202.86.142`
  - `su` as the non-root user that has access to the ARK directories
  - `mkdir -p "$HOME/.ssh"
  - Create and edit a new `$HOME/.ssh/authorized_keys` file, and paste the above public key into it
* Connect to your new server in a new terminal window - i.e. `ssh 164.132.203.83`
  - `su` as the non-root user that will have access to the ARK directories
  - `mkdir -p "$HOME/.ssh"
  - Create and edit a new `$HOME/.ssh/authorized_keys` file, and paste the above public key into it
  - Run ssh-keygen
  - Press enter to accept the default private key path of `$HOME/.ssh/id_rsa`
  - Press enter to use no password
  - Press enter again to confirm
  - Copy the contents of the `$HOME/.ssh/id_rsa.pub` file
* Switch back to the old server
  - Edit the `$HOME/.ssh/authorized_keys` file, and add a new line containing the above public key
* Switch back to the new server
  - Connect to the old server from the new server - i.e. assuming you're using the `steam` user:
    - `ssh steam@149.202.86.142`
  - Type `yes` to accept the host's public key
  - Type `exit` to disconnect
  - Now you can use `rsync -av "steam@149.202.86.142:/home/ARK-Backups-PVE/." "$HOME/ARK-Backups-PVE"`

**Comment by arkfrance** [comment]
true ! i'm using another user now, just one more thing is it possible to add the : 

[MessageOfTheDay]
Duration=120
Message=

like : 
ark_motd= this is an ARK Server
ark_motd_duration=120

thanks

**Comment by arkfrance** [comment]
Oki doki hope it will! Better to add it in the cfg instead of all the guys.ini
