### ISSUE TITLE
Memory leak, or this a normal?

### ISSUE THREAD

**Issue by lafaetos** [FezVrasta/ark-server-tools#563]
Hello, i have a server
but there is a problem with RAM
he eats it more and more with the fact that people no longer plays (an average of 2-3 players per day) for 4 days, he began to select to 1 GB of RAM more. this is normal?
![123](https://cloud.githubusercontent.com/assets/20566075/17464355/3572c18a-5ce5-11e6-8818-6e9a1c241d3b.png)

i installed this mods:
Advanced Architecture Mod, ORP, Annunaki, Cute Hair, Perfect Hair, No Collision Structures, Ark Advance, Pillar Plus, Extra ARK, Behemoth Wall, GateMod, Small Dragons, Pimp My Dino 
and map TheCenter

**Comment by klightspeed** [comment]
That memory usage looks normal - the ARK server requires about 3-4GB while running.

**Comment by lafaetos** [comment]
i tested some moments:
with annunaki mods server use 8.7Gb ram
without 3.05GB
o_O

**Comment by arkfrance** [comment]
Please, close your ticket if you think it's resolved :)

**Comment by lafaetos** [comment]
hello, the problem was the incompatibility of mods Annunaki and Small Dragons, when I deleted Small Dragons and created dinosaurs respawn everything was ok
