### ISSUE TITLE
Port - 1 no longer needed

### ISSUE THREAD

**Issue by Log1x** [FezVrasta/ark-server-tools#565]
I am new to owning an ARK server, but I noticed you have a workaround in the arkmanager code that adds "-1" to any server Port specified. I don't believe this is needed anymore.

When doing 7777 as my port in config, it's making it 7776, so it appears ARK is no longer adding +1 to Port's when they are specified, so that code should no longer be needed unless I'm missing something. For now, I have made all of my ports in config set to 7778 so I can use my intended port, 7777.

**Comment by klightspeed** [comment]
The `ark_Port` in your cfg file is the port on which the ARK server should listen.  The script subtracts 1 from this to get the `Port` parameter to pass to the ARK server, as Unreal Engine servers always set the Game port to be one higher than the Port value specified.

You will find that with your `ark_Port=7778` setting, if you run `netstat -antup`, you will find that ShooterGameServer will listen on port 7778.

**Comment by Log1x** [comment]
Aha! I see that now. Thanks for that. I was generally confused as most websites such as arkservers.net seem to -1 the port to compensate for Unreal Engine adding +1 to the port, so instead of showing 7777 as seen when previously starting my servers with ?Port=7777 it was showing 7776.

Thanks for the information, and sorry for the false issue report.

**Comment by krobertson** [comment]
On this note, I'm finding that with ark_Port=7778, netstat shows it bound to 7778, but in Steam when showing info on the server, it is showing 7777 as the port.

Confusing the heck out me while trying to troubleshoot why I can't connect to it.
