### ISSUE TITLE
Uninstall?

### ISSUE THREAD

**Issue by DiTechRacer** [FezVrasta/ark-server-tools#568]
How can i uninstall ark Linux Server Tools?

**Comment by klightspeed** [comment]
You should be able to use `arkmanager uninstall-tools`

Alternatively, you can:
* Make sure all `arkmanager` instances are stopped
* Disable the `arkmanager` service
* Delete `/usr/local/bin/arkmanager` if it exists
* Delete the `/usr/local/libexec/arkmanager` directory if it exists
* Delete `/etc/systemd/system/arkmanager.service` if it exists
* Delete `/etc/systemd/system/arkmanager@.service` if it exists
* Delete `/etc/init.d/arkmanager` if it exists
* Delete `/etc/rc.d/init.d/arkmanager` if it exists
* Delete `$HOME/bin/arkmanager` if it exists
* Delete the `$HOME/.local/share/arkmanager` if it exists

**Comment by DiTechRacer** [comment]
Thx!!
