### ISSUE TITLE
Installmod not working

### ISSUE THREAD

**Issue by SgtKrazy** [FezVrasta/ark-server-tools#569]
#I have searched the issues to see if there was something I'm missing. When running "arkmanager installmod "506506101" I get "Running command 'installmod' for instance 'main'
[  ERROR  ]     Mod 504122600 is requested but not installed.  Run 'arkmanager installmod 504122600' to install this mod. Downloading mod 506506101 ... Mod 506506101 was not successfully downloaded" I have checked the mod director for ark and no mods just the initial 3 in there. 

Is there something I'm missing?
EDIT: This error seems to be steam invalid depot config. And can not seem to find the fix for this.

**Comment by klightspeed** [comment]
If it's an invalid steam depot config, try deleting the `$HOME/Steam` and/or `$HOME/steamcmd/steamapps` directories.

**Comment by SgtKrazy** [comment]
Sorry for the delay in response. I was able to get the issue fixed. I removed the steamcmd first and tried to reinstall it. Still had the same problem. However, I removed it again extracted the steamcmd and ran it as sudo. Everything started working normal. Not sure if it was the case that with out installing as sudo cause permission issues or not. The server version I am using is Ubuntu 16.04. I think I did read an issue simular to this not sure which # it was though. Maybe a note could be added to the install instruction to try installing steamcmd as sudo if a problem occurs with issues installing mods and such.

Out standing work with the manager by the way! :-)

**Comment by klightspeed** [comment]
As root, please try changing the ownership in your `steamcmd` and `Steam` directories to the user under which you run arkmanager.  i.e.

```
chown -R steam:steam steamcmd
chown -R steam:steam ~steam/Steam
```
where `steam` is the user under which you run arkmanager.

**Comment by SgtKrazy** [comment]
Thank you. Everything seems to be working fine so far just dont see it in the server list. I have a port issue linux and figured out what is going on with that just working on fixing that. Thanks for the help with getting ark manager working.
