### ISSUE TITLE
Possible RCON Issue

### ISSUE THREAD

**Issue by arkwarrior** [FezVrasta/ark-server-tools#570]

**Comment by arkwarrior** [comment]
Hello,

I'm running into an issue where I can not connect to a server over RCON when setting variables through the config file. Please see the below for more details/clarity.

>steam@ark:~$ arkmanager start
>Running command 'start' for instance 'linuxlocker'
>Updating server
>Downloading mod 558651608 ... Mod 558651608 downloaded
>Downloading mod 566885854 ... Mod 566885854 downloaded
>Downloading mod 637517143 ... Mod 637517143 downloaded
>Downloading mod 655261420 ... Mod 655261420 downloaded
>Downloading mod 693416678 ... Mod 693416678 downloaded
>Your server is already up to date! The most recent version is 1291304.
>The server is now running, and should be up within 10 minutes
>
>steam@ark:~$ ps aux | grep Shooter
>steam    11992  101  5.5 1589292 453248 pts/0  Rl   05:37   0:06 /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter?GameModIds=693416678,655261420,558651608,637517143,566885854?MaxPlayers=120?Port=7779?QueryPort=27015?RCONEnabled=True?RCONPort=32330?ServerAdminPassword=w1nn3r?ServerPassword=w1nn3r?>SessionName=1a2s3d4f?listen -DisableDeathSpectator -OnlyAdminRejoinAsSpectator -Server -UseBattlEye
>
>root@ark:~# ./rcon -Pw1nn3r -a127.0.0.1 -p32340 listplayers
>connect() failed.: Connection refused

If I start an instance from the command line, RCON seems to work just fine:

>steam@ark:~/ARK/ShooterGame/Binaries/Linux$ ./ShooterGameServer TheIsland?MaxPlayers=70?SessionName=a1s2d3f4?QueryPort=27015?Port=7779?QueryPort=27015?RCONEnabled=True?RCONPort=32330 listen -server
>Using binned.
>4.5.1-0+UE4 7038 3077 402 5
>[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
>Setting breakpad minidump AppID = 346110
>
>root@ark:~# ps aux | grep Shooter
>steam    12320  112 25.4 3078816 2083280 pts/1 Rl+  05:38   0:24 ./ShooterGameServer TheIsland?MaxPlayers=70?SessionName=a1s2d3f4?QueryPort=27015?Port=7779?QueryPort=27015?RCONEnabled=True?>RCONPort=32330 listen -server
>
>root@ark:~# ./rcon -Pw1nn3r -a127.0.0.1 -p32330 listplayers
>No Players Connected

**Comment by klightspeed** [comment]
Are you waiting for long enough for the server to have fully started before attempting to run the RCON command?

What is the output of `arkmanager status` immediately before trying to run the RCON command?

**Comment by arkwarrior** [comment]
Well that explains the weirdness with the ark_port setting ^_^

As far as RCON goes, I'm definitely waiting long enough for the server to start. 

Here is the output you requested:

>steam@ark:~$ arkmanager status
>Running command 'status' for instance 'linuxlocker'
>Server running:   Yes
>Server listening:   Yes
>Server Name: 1a2s3d4f - (v245.989)
>Players: 0 / 120
>Server online:   Yes
>ARKServers link:   http://arkservers.net/server/104.250.134.11:27015
>Server version:   1291304
>steam@ark:~$ exit
>logout
>root@ark:~# ./rcon -Pw1nn3r -a127.0.0.1 -p32330 listplayers
>connect() failed.: Connection refused

Thank you!

**Comment by klightspeed** [comment]
What does the following command give you:
```
netstat -antup | grep 'ShooterGameS'
```

**Comment by arkwarrior** [comment]
Looks like ShooterGame isn't listening on 32330... or any port for RCON..

>root@ark:~# netstat -antup | grep 'ShooterGameS'
>udp        0      0 0.0.0.0:27015           0.0.0.0:*                           12685/ShooterGameSe
>udp        0      0 0.0.0.0:7780            0.0.0.0:*                           12685/ShooterGameSe

**Comment by klightspeed** [comment]
Can you duplicate the issue if you use the exact same command-line as arkmanager uses?  I wonder if a mod and/or BattlEye somehow disables RCON?

**Comment by arkwarrior** [comment]
I can indeed duplicate using the arkmanager command-line. I'm going to start turning stuff off one-by-one. I'll start with BattlEye and let you know. 

BTW, is there a better/easier way to stick the below into a codeblock or something? I've been using blockquotes since using the code tags doesn't seem to work correctly.

>steam@ark:~/ARK/ShooterGame/Binaries/Linux$ ./ShooterGameServer TheCenter?GameModIds=693416678,655261420,558651608,637517143,566885854?MaxPlayers=120?Port=7779?QueryPort=27015?RCONEnabled=True?RCONPort=32330?ServerAdminPassword=w1nn3r?ServerPassword=w1nn3r?SessionName=1a2s3d4f?listen -DisableDeathSpectator -OnlyAdminRejoinAsSpectator -Server -UseBattlEye
>Using binned.
>4.5.1-0+UE4 7038 3077 402 5
>[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
>Setting breakpad minidump AppID = 346110


>root@ark:~# netstat -antup | grep 'ShooterGameS'
>udp        0      0 0.0.0.0:27015           0.0.0.0:*                           19909/ShooterGameSe
>udp        0      0 0.0.0.0:7780            0.0.0.0:*                           19909/ShooterGameSe
>root@ark:~# ./rcon -Pw1nn3r -a127.0.0.1 -p32330 listplayers
>connect() failed.: Connection refused

**Comment by klightspeed** [comment]
Use triple-backtick blocks.
<pre>
```
steam@ark:~/ARK/ShooterGame/Binaries/Linux$ ./ShooterGameServer TheCenter?GameModIds=693416678,655261420,558651608,637517143,566885854?MaxPlayers=120?Port=7779?QueryPort=27015?RCONEnabled=True?RCONPort=32330?ServerAdminPassword=w1nn3r?ServerPassword=w1nn3r?SessionName=1a2s3d4f?listen -DisableDeathSpectator -OnlyAdminRejoinAsSpectator -Server -UseBattlEye
Using binned.
4.5.1-0+UE4 7038 3077 402 5
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

root@ark:~# netstat -antup | grep 'ShooterGameS'
udp 0 0 0.0.0.0:27015 0.0.0.0:* 19909/ShooterGameSe
udp 0 0 0.0.0.0:7780 0.0.0.0:* 19909/ShooterGameSe
root@ark:~# ./rcon -Pw1nn3r -a127.0.0.1 -p32330 listplayers
connect() failed.: Connection refused
```
</pre>

**Comment by arkwarrior** [comment]
Alright so it wasn't BattlEye. It seems to have been the set of mods that I was loading up. So... now going to go and individually test those to see which one is causing problems >_<

Thanks for sticking around and helping out. At least I can bring the issue to the mod creators attention!

**Comment by arkwarrior** [comment]
Seems the culprit is the "Reusable Plus" mod. https://steamcommunity.com/sharedfiles/filedetails/?id=693416678

I ran ShooterGame with only one mod enabled each time, and the RCON port would not come up with the above mod enabled.

I'll notify the mod developer, and link him to this report.
