### ISSUE TITLE
Nice Priorities

### ISSUE THREAD

**Issue by Log1x** [FezVrasta/ark-server-tools#571]
I realize to do this we would probably have to use sudo or fork to the steam user as root, but any possibility of adding nice priorities when starting the server?

I'd like to start my server with -5 priority to attempt to help with performance, especially when doing regular updates & backups with cronjobs.

You can read more about nice [here](https://en.wikipedia.org/wiki/Nice_(Unix)).

**Comment by klightspeed** [comment]
I'm guessing you're already running backups and updates etc. at a low priority (such as `nice -n -19`)?

Note that running the server at a higher priority won't help if the CPU is not the bottleneck.

**Comment by klightspeed** [comment]
I have added an `arkPriorityBoost` setting in 7efbbd3 (currently in 1.6-dev.unstable)

**Comment by Log1x** [comment]
perfect!!
