### ISSUE TITLE
[ModInstaller] section issues

### ISSUE THREAD

**Issue by Uskaanax** [FezVrasta/ark-server-tools#574]
I'm trying to enable the automatic mod control from patch 244.3 and arkmanager seems to core dump when I include the ModIDS in the Game.ini file. If I remove/comment out that section and/or disable the option to -automanagedmods then everything loads fine. Is there a conflict created within ARK by listing the mods in the GameUsersettings.ini as ActiveMods, or is this something from Arkmanager? I noticed that, when I leave the command line option, automanagedmods, in but have the ModInstaller section empty, the Game.ini file is rewritten and that section header is deleted and empty space is removed.

22:40:29: Server PID: 21245
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:G:\SVN_Ark\Engine\Source\Runtime\Core\Private\Linux\LinuxPlatformProcess.cpp] [Line: 652]
FLinuxPlatformProcess::WaitForProc: waitid for pid -1 failed (errno=22, Invalid argument)
Signal 11 caught.
/usr/local/bin/arkmanager: line 670: 21245 Segmentation fault      (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
22:40:34: Bad PID ''; expected '21245'
22:40:34: exited with status 0

**Comment by klightspeed** [comment]
You need to extract `steamcmd` into `$arkserverroot/Engine/Binaries/ThirdParty/SteamCMD/Linux` when using the `-automanagedmods` option.

1.6 (which I am hoping to release soon) will do this for you.

**Comment by Uskaanax** [comment]
Thanks! Implemented this and it seemed to correct the issue.
