### ISSUE TITLE
Can't restart the server

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#576]
Since the last comit, the server doesn't auto restart

https://github.com/FezVrasta/ark-server-tools/commit/653006a66c4a70dd3e14444ad790e62944f7c0d3

sometimes it says that an update is already in progress so the start is canceled (An update is currently in progress.  Start aborted)

but there is no update and the server won't restart 

05:41:06: restart
11:57:23: start

i need to cancel shutdown and started it myself

05:36:06: No update needed.
05:38:05: No update needed.
05:44:38: No update needed.
05:46:05: No update needed.
05:48:05: No update needed.
05:55:39: No update needed.
05:56:05: No update needed.
05:58:06: No update needed.

maybe it's caused by the 30 5 * * * /usr/local/bin/arkmanager useconfig mmo restart --warn --warnreason=1

any clue ? it happens only for two of my 6 servers, they have the same config with the warnreason=1

thanks

**Comment by klightspeed** [comment]
Please test with the latest commit (05e8511)

**Comment by arkfrance** [comment]
Ok i will tell you if that works tomorrow

**Comment by arkfrance** [comment]
One of them didn't start

**Comment by klightspeed** [comment]
I have pushed another commit to prevent the "update in progress" from triggering when doStart is called from doUpdate.  Please let me know if this solves the issue.

**Comment by arkfrance** [comment]
same here just for only one server, others works fine

30 5 * * * /usr/local/bin/arkmanager useconfig pvp restart --warn --warnreason=1

/usr/local/bin/arkmanager: line 802: 20870 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
05:36:03: Bad PID ''; expected '20870'
05:36:03: exited with status 0
06:30:38: start
06:30:38: Running /home/PVP/ShooterGame/Binaries/Linux/ShooterGameServer Theisland\?RCONEnabled=True\?RCONPort=27032\?SessionName=\[Wiped\ 22/08\]ARK\ FRANCE\ OFFICIEL\ -\ PvP\ x10\ The\ Island\?Port=7778\?QueryPort=27017\?ServerPassword\?ServerAdminPassword=$$$$$\?MaxPlayers=60\?GameModIds=684959100\,558079412\,656525905\,572174950\,566432022\,566887000\,566885854\?ForceAllStructureLocking=true\?PreventTribeAlliances=true\?OnlyAutoDestroyCoreStructures=true\?OnlyDecayUnsnappedCoreStructures=true\?AllowRaidDinoFeeding=true\?FastDecayUnsnappedCoreStructures=true\?listen -log -UseBattlEye -server -newsaveformat
06:30:38: Server PID: 25951
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Using binned.
4.5.1-0+UE4 7038 3077 402 5
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
STEAMPS3 - AsyncTCPSocket created
STEAMPS3 - AsncTCPSocket destroyed
CtrlCHandler: Signal=2
/usr/local/bin/arkmanager: line 802: 25951 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
 

06:30:38: start
05:36:01: stopping
05:36:03: stopped
05:36:03: stop
05:36:04: start
05:36:04: restart
07:50:53: start

**Comment by klightspeed** [comment]
The restart and update check are probably running at the same time.

a46ef5a now has the update start the server if necessary regardless of whether or not it was the one that stopped the server.

**Comment by arkfrance** [comment]
ok i've changed 

30 5 * * * /usr/local/bin/arkmanager useconfig pvp restart --warn --warnreason=1

to

30 4 * * * /usr/local/bin/arkmanager useconfig pvp restart --warn --warnreason=1

to check if that changes something

**Comment by klightspeed** [comment]
What is your update line?

**Comment by arkfrance** [comment]
Second, to change the restart warn to 4 am

**Comment by arkfrance** [comment]
Seems to be good, just one more thing, we have the arkmanager installmods but can we have the same for uninstallmods please?

**Comment by klightspeed** [comment]
ac56f43 adds the ability to install or uninstall multiple mods in one command.
2e8475c adds an `uninstallmods` command that removes all mods except `TheCenter` and `Primitive+` (since neither of those can be downloaded from the workshop).

**Comment by arkfrance** [comment]
Perfect
