### ISSUE TITLE
Failure to change map

### ISSUE THREAD

**Issue by LvZeeland** [FezVrasta/ark-server-tools#577]
Iḿ trying to change the standard TheIsland map to TheCenter. But I don get it to actually change when I start the server.

I have changed serverMap="TheIsland" to serverMap="TheCenter" and I deleted everything in the saved folder and mods folder.
I started the server. It started updating, but the server still runs TheIsland.

Am I forgetting something?

**Comment by klightspeed** [comment]
Check what commandline is being used in `/var/log/arktools/arkserver.log` or `$HOME/logs/arktools/arkserver.log`.

If it's still specifying `TheIsland`, then you have likely performed both a system install and a user-install, and the main.cfg in `$HOME/.config/arkmanager/instances` is overriding the main.cfg in `/etc/arkmanager/instances`.  In this case, if you want to use `/etc/arkmanager/instances/main.cfg` instead of `$HOME/.config/arkmanager/instances/main.cfg`, then delete the latter.

**Comment by LvZeeland** [comment]
The following is in the log file:
`20:24:54: start
20:24:54: Running /home/thebierfontein/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers=20\?Port=7777\?QueryPort=27015\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=Serveradminpassword\?ServerPassword=0000\?SessionName=theBierfontein\?listen
20:24:54: Server PID: 14609
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
/usr/local/bin/arkmanager: line 670: 14609 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
20:25:20: Bad PID ''; expected '14609'
20:25:20: exited with status 0`

Which line indicates where the `main.cfg` being used is?
I can find the `/etc/arkmanager/instances/main.cfg` but I'm unable to find any other Main.cfg.
The file with the name of the map that should be used is in `/etc/arkmanager/arkmanager.cfg
`

**Comment by klightspeed** [comment]
Check `/home/thebierfontein/.config/arkmanager/instances/main.cfg` and `/home/thebierfontein/.arkmanager.cfg`

**Comment by LvZeeland** [comment]
I still can't find those files. When i go to /home/thebierfontein/.config/ there is no arkmanager folder in the .config folder. (Hidden files are shown)
The same for arkmanager.cfg. There is no .arkmanager.cfg in /home/thebierfontein/

**Comment by klightspeed** [comment]
Please post your arkmanager.cfg and main.cfg with any passwords removed.
