### ISSUE TITLE
ARK: Scorched Earth - Expansion Pack

### ISSUE THREAD

**Issue by BoiseComputer** [FezVrasta/ark-server-tools#578]
Does anyone know the method for implementing the scorched earth expansion on a private server?

**Comment by ryan1161** [comment]
add this to your Instance config.
serverMap="ScorchedEarth_P"

I can't get my Center and ScorchedEarth to work yet cause of the query ports are running on the same port when I've changed them in both the binaries config and my instance config.
![port error](https://cloud.githubusercontent.com/assets/2374149/18183217/fc13de6a-7058-11e6-9448-04d243a36678.png)

**Comment by arkfrance** [comment]
/usr/local/bin/arkmanager: line 802: 17760 Segmentation fault      (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
2016-09-01 22:27:52: Bad PID ''; expected '17760'
2016-09-01 22:27:52: exited with status 0
2016-09-01 22:27:52: restarting server
2016-09-01 22:27:52: Running /home/PVE/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=27030\?SessionName=ARK-FRANCE.FR\ -\ PvE\ x5\ The\ Island\?Port=7776\?QueryPort=27015\?ServerPassword\?ServerAdminPassword=\?MaxPlayers=60\?GameModIds=684959100\,558079412\,534838287\,704420972\,572277026\,670764308\,564895376\,600015460\,680798000\,566887000\,543859212\,729352919\,566885854\?AllowRaidDinoFeeding=true\?PreventTribeAlliances=false\?ForceAllStructureLocking=true\?FastDecayUnsnappedCoreStructures=true\?OnlyAutoDestroyCoreStructures=true\?listen -log -newsaveformat -server -server -UseBattlEye
2016-09-01 22:27:52: Server PID: 19154
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

**Comment by arkfrance** [comment]
crash for me on the island

**Comment by klightspeed** [comment]
@ryan1161 you have two `configfile_TheCenter` lines in your `arkmanager.cfg`, and so the instance `TheCenter` would be using your last one (your `ScorchedEarth` instance config file).

```
configfile_TheIsland="/etc/arkmanager/instances/TheIsland.cfg"
configfile_TheCenter="/etc/arkmanager/instances/TheCenter.cfg"
configfile_TheCenter="/etc/arkmanager/instances/ScorchedEarth.cfg"
```


You should not need those `configfile` lines when your instance configs are in `/etc/arkmanager/instances` or `$HOME/.config/arkmanager/instances`.

@arkfrance it looks like you have two `arkflag_server=something` lines in your instance config.  Also check that it isn't a mod causing the crash.

**Comment by ryan1161** [comment]
omg I can't believe I missed that. Thanks that fixed it.

**Comment by arkfrance** [comment]
i'm trying to check mod by mod ...

**Comment by arkfrance** [comment]
still crashing whithout any mods

**Comment by klightspeed** [comment]
@arkfrance Does it still crash if you remove everything from the `Mods` directory?  Some mods will crash the server if they're installed but not enabled.

Also, what is the full log from when the server starts to when the server crashes and is restarted?

**Comment by ryan1161** [comment]
I was wondering is there away to just have all 3 of my instance to have one folder for running the maps cause it would save me some disk space. If so could you explain or point me in the right direction.

**Comment by klightspeed** [comment]
@ryan1161 Setting the same staging directory for all 3 instances and then performing an update should reduce the disk space taken up by the instances.

**Comment by ryan1161** [comment]
Well I was thinking having one Ark folder and having that run all my maps instead of having 3 folder with ark installed in that. Like I was wanting to point the instances to the saved maps files and point it to the executable file for starting ark for that instance.

Example:
First instance:
arksavedgamedir="Ark/ShooterGame/Saved/TheCenter" then have instead of SavedArks folder have it point to the name of a custom folder like TheCenter. Then repeat for instance two and three.

Executable:
arkexecutable="Ark/ShooterGame/Binaries/Linux/ShooterGameServer"
Put that in all the instances to just point to one executable to run out of the one installed Ark directory.

**Comment by klightspeed** [comment]
There is an option to ShooterGameServer to configure the Saved Arks directory - `AltSaveDirectoryName` (configured by the `ark_AltSaveDirectoryName` option in your arkmanager instance config)

I know of no option to configure Unreal Engine 4 (and by extension the game server) to change the saved config directory to something other than `[ProjectDir]/Saved/Config/[Platform]` (where `[ProjectDir]` is `ShooterGame` and `[Platform]` is `Linux`

**Comment by BoiseComputer** [comment]
https://survivetheark.com/index.php?/forums/topic/85463-scorched-earth-technicaldetail-faq-ongoing/#

**Comment by klightspeed** [comment]
In that case, with the example settings, one would have TheIsland containing:
```
serverMap=TheIsland
ark_AltSaveDirectoryName="Save2"
ark_SessionName="MySession2"
arkflag_NoTransferFromFiltering=true
arkopt_clusterid=mycluster123
```

ScorchedEarth containing:
```
serverMap=ScorchedEarth_P
ark_AltSaveDirectoryName="Save1"
ark_SessionName="MySession1"
arkflag_NoTransferFromFiltering=true
arkopt_clusterid=mycluster123
```

We will need to make arkmanager cluster aware in order for this to work, as it was assumed that bad things would happen if two servers ran from the same directory.  It also means that we need some form of server identification other than its path.

**Comment by caindrac** [comment]
So with the fact that the arkmanager is not aware of the cluster make this not work right now?

**Comment by klightspeed** [comment]
That is correct, arkmanager will not currently allow multiple servers to run from the same directory.

**Comment by caindrac** [comment]
I have not got super deep into your code. Is this going to be a super big deal to change?

**Comment by arkfrance** [comment]
ok so server is working with mods folder changed to mods1

**Comment by klightspeed** [comment]
@caindrac Some things we would need to do are:
* Support grouping instances into a cluster, possibly using a cluster config file
* Change the `getSetverPid` function to use a per-instance PID file
* Change the `doRun` function to write to per-instance PID files
* Change the `doRun` function to read config settings from both a cluster config file and an instance config file 
* Change the `doUpdate` function to start and stop all instances within the cluster when updating
* Change the `doWarn` function to send the warning to a list of instances in order to support sending the warning to all instances in the cluster and to monitor all instances in the cluster for connected players.

@arkfrance Please move your conversation to a new issue.

**Comment by remz1337xXx** [comment]
It would be awesome if someone could get this to work. Ill get a look at the code tomorrow

**Comment by meswrex** [comment]
Hi all,
I might have a work-around until clustering instances are supported by ark-server-tools. I've used symbolic links to allow arkmanager to continue to launch separate instances from separate directories, but effectively work from the same game files. As far as I can tell at the moment, it appears to work; I have two servers concurrently running launched via arkmanager with separate instance configs and with separate backup and save directories. I can transfer characters and tames between servers (albeit losing items, but that may be related to the current patch).

server1.cfg:
```
arkserverroot="<path to server1 game files>"
arkbackupdir="<path to server1 backup dir>"
ark_AltSaveDirectoryName="SavedArks1"
arkflag_NoTransferFromFiltering=true
arkopt_clusterid=Cluster1
```
server2.cfg:
```
arkserverroot="<path to server2 game files>"
arkbackupdir="<path to server2 backup dir>"
ark_AltSaveDirectoryName="SavedArks2"
arkflag_NoTransferFromFiltering=true
arkopt_clusterid=Cluster1
```

Server 1 game files are the original game directories and server 2 are the files symbollicaly linked to server 1. The only changes needed are separate SavedArk? directories for each of the servers (in my case parallel to the original SavedArks directory in ShooterGame/Saved). That way both instances use the same game files but separate save directories.

It might be worthwhile trying to get each server working independently first just to make sure each config is set up correctly (separate ports, etc.). I had this going before trying to shift the one server to the symbolic link.

Hope that helps.

**Comment by BoiseComputer** [comment]
I did implement the linked directory and it is working. Thanks for the suggestion.

**Comment by Gumballz** [comment]
Thanx for those meswrex ... saved me hours of headaches.

On a side note.  I have 2 instances running... both installed in there individual (server1/ARK   & server2/ARK)    directories, both being ran by different users (serveruser1  & serveruser2)  ... and they are connected.

No need to bother with the AltSaveDirectoryName.

Uplaods/Downloads working perfectly

**Comment by MithrimTAoW** [comment]
Hi there, Thats awesome that meswrex's method is working but I feel like a total noob! I can't seem to figure it out. I have two seperate servers working, the center and scorched earth, I tried to setup the arkopt_clusterid but when i go to the terminal on SE it doesn't give me the option to upload anything, I'm certain the problem lies between keyboard and chair but any help someone could provide on this would be greatly appreciated as I would LOVE to get this working for my players so they could experience SE content on the center/the island. Thanks in advance, Mithrim.

**Comment by BoiseComputer** [comment]
So another option I had to change on both configs they don't mention is:
`ark_noTributeDownloads=false`

to do the dynamic link you need to run a command like:
`ln -s /var/ark1 /var/ark2`
In the script have one path be ark1
Script # 1: `arkserverroot="/var/ark1"`
Script # 2: `arkserverroot="/var/ark2"`
This will make it so that the script sees it as two folders, but, it is really the same.
Here is the config inside of the script.

```
ark_PreventDownloadSurvivors=False
ark_PreventDownloadItems=False
ark_PreventDownloadDinos=False
ark_PreventUploadSurvivors=False
ark_PreventUploadItems=False
ark_PreventUploadDinos=False
arkflag_NoTransferFromFiltering=true
arkflag_clusterid=customclusteridhere
ark_AltSaveDirectoryName="customsavefolderpergame"
```
This should be the main changes. Let me know if it still doesn't work.

Note: You might have to change the folder owner and possibly permissions of any folder you create for the save game locations. Keep that in mind.

**Comment by meswrex** [comment]
@MithrimTAoW That's odd; even on a sole-server map I have the option to upload my upload/download my character/tames, albeit to the same server (when I finally spot the 'transmit data' button - for some reason I find the menu layout for this a little obscured). Anyway, if anything, the problem I would expect to see is to be given the option to upload/download, but for the list to be empty on the second server after doing so on the first (i.e. the separate server save files are not linked). Probably not the fastest path, but I would try to revert back to separate servers to check the option is at least available in this state, just to be sure the problem is occurring when you try to cluster them. Hope you sort it out.

**Comment by Gumballz** [comment]
ark_PreventDownloadSurvivors=False
ark_PreventDownloadItems=False
ark_PreventDownloadDinos=False
ark_PreventUploadSurvivors=False
ark_PreventUploadItems=False
ark_PreventUploadDinos=False
goes in your gameusersettings.ini without the ark_not your arkmanager configfile 

    On Sunday, 4 September 2016, 14:53, MithrimTAoW <notifications@github.com> wrote:
 

 Hi there, Thats awesome that meswrex's method is working but I feel like a total noob! I can't seem to figure it out. I have two seperate servers working, the center and scorched earth, I tried to setup the arkopt_clusterid but when i go to the terminal on SE it doesn't give me the option to upload anything, I'm certain the problem lies between keyboard and chair but any help someone could provide on this would be greatly appreciated as I would LOVE to get this working for my players so they could experience SE content on the center/the island. Thanks in advance, Mithrim.—

**Comment by Gumballz** [comment]
ark_noTributeDownloads=falsesame for that too
 

    On Sunday, 4 September 2016, 14:53, MithrimTAoW <notifications@github.com> wrote:
 

 Hi there, Thats awesome that meswrex's method is working but I feel like a total noob! I can't seem to figure it out. I have two seperate servers working, the center and scorched earth, I tried to setup the arkopt_clusterid but when i go to the terminal on SE it doesn't give me the option to upload anything, I'm certain the problem lies between keyboard and chair but any help someone could provide on this would be greatly appreciated as I would LOVE to get this working for my players so they could experience SE content on the center/the island. Thanks in advance, Mithrim.—

**Comment by Gumballz** [comment]
```
ark_PreventDownloadSurvivors=False
ark_PreventDownloadItems=False
ark_PreventDownloadDinos=False
ark_PreventUploadSurvivors=False
ark_PreventUploadItems=False
ark_PreventUploadDinos=False
ark_noTributeDownloads=false

```
put those in your gameusersettings.ini (minus the ark_)

**Comment by arkfrance** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=758608778

very usefull !=

**Comment by ryan1161** [comment]
@meswrex and @BoiseComputer thanks but this was a little still to hard for me to figure especially the symbolic links were not working the way you said to do, so I created another way and it works great now. What I did steps:

**TheIsland.cfg:**

arkserverroot="</home/mc/ARK/TheIsland>"
arkbackupdir="</mnt/Backups/Ark/TheIsland>"
ark_AltSaveDirectoryName="Saved-TheIsland"
arkflag_NoTransferFromFiltering=true
arkopt_clusterid=Cluster1

**TheCenter.cfg:**

arkserverroot="</home/mc/ARK/TheCenter>"
arkbackupdir="</mnt/Backups/Ark/TheCenter>"
ark_AltSaveDirectoryName="Saved-TheCenter"
arkflag_NoTransferFromFiltering=true
arkopt_clusterid=Cluster1

**ScorchedEarth.cfg:**

arkserverroot="</home/mc/ARK/ScorchedEarth>"
arkbackupdir="</mnt/Backups/Ark/ScorchedEarth>"
ark_AltSaveDirectoryName="Saved-ScorchedEarth"
arkflag_NoTransferFromFiltering=true
arkopt_clusterid=Cluster1

Once you get all the configs done now it's time to start symbolic link the files/folders. TheIsland is our master folder with all the files we will point to for the other directory.
Example:

**ln -s /home/mc/ARK/TheIsland/* /home/mc/ARK/TheCenter/
ln -s /home/mc/ARK/TheIsland/ShooterGame/* /home/mc/ARK/TheCenter/ShooterGame/
ln -s /home/mc/ARK/TheIsland/ShooterGame/Saved/* /home/mc/ARK/TheCenter/ShooterGame/Saved/**

**ln -s /home/mc/ARK/TheIsland/* /home/mc/ARK/ScorchedEarth/
ln -s /home/mc/ARK/TheIsland/ShooterGame/* /home/mc/ARK/ScorchedEarth/ShooterGame/
ln -s /home/mc/ARK/TheIsland/ShooterGame/Saved/* /home/mc/ARK/ScorchedEarth/ShooterGame/Saved/**

Saved Games Folder: If you leave these off it will build files under TheIsland or Master directory Saved folder.

**ln -s /home/mc/ARK/TheCenter/ShooterGame/Saved/Saved-TheCenter/ /home/mc/ARK/TheIsland/ShooterGame/Saved/**

**ln -s /home/mc/ARK/ScorchedEarth/ShooterGame/Saved/Saved-ScorchedEarth/ /home/mc/ARK/TheIsland/ShooterGame/Saved/**

Other Options:
**ark_PreventDownloadSurvivors=False
ark_PreventDownloadItems=False
ark_PreventDownloadDinos=False
ark_PreventUploadSurvivors=False
ark_PreventUploadItems=False
ark_PreventUploadDinos=False
ark_noTributeDownloads=False**

Then in gameusersettings.ini under [ServerSettings]:
**PreventDownloadSurvivors=False
PreventDownloadItems=False
PreventDownloadDinos=False
PreventUploadSurvivors=False
PreventUploadItems=False
PreventUploadDinos=False
noTributeDownloads=False**

**Comment by ryan1161** [comment]
Okay so when I travel from scorched earth to theisalnd my character has no crafting recipes on him at all but when I look at the engrams they show them as learned so idk what to do.

**Comment by Gumballz** [comment]
Problems with auto updating....

Currently if I auto-update instance1, everything goes fine. 
But when I run the update against the second instance, it reports the server is up to date (as its just been installed) but the instance is a version behind.

Is it possible to force a restart on instance2 IF instance1 has shutdown due to the update ?

Or check if version running matches installed version and restart is mismatch ?

Or listen in to instance1 for the broadcast, bring down instance2 and then restart it after instance1 is back up and running ?

I know you guys are probably hard thrashing out an update for this awesome tool... hoping for a work around until then.

Cheers

**Comment by klightspeed** [comment]
3dc8ef1 should restart the server if it was updated behind its back.

**Comment by Gumballz** [comment]
Thanx Klightspeed.

Does this check the mods too ?  sorry for being a pita

**Comment by ryan1161** [comment]
One question is there away to only allow these settings to only apply to my server so other can't join from another server I want player to only be aloud to transfer around there stuff when they play on my server not bring it in from other unofficial servers. I'm trying to make it only my server as a hive not other servers out there.

**PreventDownloadSurvivors=False
PreventDownloadItems=False
PreventDownloadDinos=False
PreventUploadSurvivors=False
PreventUploadItems=False
PreventUploadDinos=False
noTributeDownloads=False**

**Comment by Maygus** [comment]
> Once you get all the configs done now it's time to start symbolic link the files/folders. TheIsland is our master folder with all the files we will point to for the other directory.
Example:

> ln -s /home/mc/ARK/TheIsland/* /home/mc/ARK/TheCenter/
> ln -s /home/mc/ARK/TheIsland/ShooterGame/* /home/mc/ARK/TheCenter/ShooterGame/
> ln -s /home/mc/ARK/TheIsland/ShooterGame/Saved/* /home/mc/ARK/TheCenter/ShooterGame/Saved/

> ln -s /home/mc/ARK/TheIsland/* /home/mc/ARK/ScorchedEarth/
> ln -s /home/mc/ARK/TheIsland/ShooterGame/* /home/mc/ARK/ScorchedEarth/ShooterGame/
> ln -s /home/mc/ARK/TheIsland/ShooterGame/Saved/* /home/mc/ARK/ScorchedEarth/ShooterGame/Saved/

Then I run the very first command - it links all the subfolders. Even when I try to create the saved folders the same way you have, says "File exists" and doesn't let me create it...

**Comment by g1franc** [comment]
Why do you put a star '*' at the end of the first path of the symbolic link command. This is the issue as it match possibly several items

**Comment by Maygus** [comment]
I figured as much - so should we not use the * option?

**Comment by klightspeed** [comment]
You should only need to:

```
ln -s /home/mc/ARK/TheIsland /home/mc/ARK/TheCenter
ln -s /home/mc/ARK/TheIsland /home/mc/ARK/ScorchedEarth
```

Also add `arkautorestartfile=ShooterGame/Saved/.autostart-<name>` to your instance config where `<name>` is your instance name.

**Comment by Maygus** [comment]
well in my case I installed my ark to just /ARK/ not /ARK/TheIsland/ so I'm symlinking out of /home/arkuser/ARK/ShooterGame/ essentially.

**Comment by Maygus** [comment]
@ryan1161 from what I read - if you have the -cluster specified, it locks transfers ONLY to the servers you have setup clustering for as it stores the arktribute data on the server itself.

**Comment by Log1x** [comment]
Using symbolic links as seen above does not seem to be working for me.

I did the following:
1. `ln -s center/* scorched/` which was successful.
2. Setup my `scorched.cfg` with it's own save directory, cluster,  and `arkautorestartfile`.
3. Attempted to start my scorched server with `arkmanager start @scorched`

and I get the following error(s):

```
steam@dev:~/servers/arkonia_server$ arkmanager start @scorched
Running command 'start' for instance 'scorched'
[  WARN  ]      Your ARK server exec could not be found.
mkdir: cannot create directory ‘/home/steam/servers/arkonia_server/scorched/ShooterGame’: File exists
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
The server is starting...
The server is now running, and should be up within 10 minutes
steam@dev:~/servers/arkonia_server$
```

which in turn does not actually start the server.

My Center server still starts with no issues which is where my Scorched server is symlinked from.

Any suggestions? Afraid I'm going to have to start my servers without ark-server-tools for the time being as I'm currently doing a freshwipe to setup ARK travels. :cry:

**Comment by klightspeed** [comment]
@Log1x you were using relative symlinks, so it was looking in scorched/center/ShooterGame instead of where you expected.

I would suggest:
```
rm -rf scorched        # Remove the scorched directory
ln -s center scorched  # Create a symbolic link pointing scorched at center
```

If you really want to symlink the contents of the directory instead:
```
cd scorched
rm *  # remove the bad links
ln -s ../center/* .
```

**Comment by Log1x** [comment]
Thank you @klightspeed. I thought I tried `ln -s center scorched` but apparently I had a trailing slash when I attempted it.

Now I am running into the following issue:

```
steam@dev:~/servers/arkonia_server$ arkmanager start @scorched
Running command 'start' for instance 'scorched'
The server is starting...
The server is now running, and should be up within 10 minutes
steam@dev:~/servers/arkonia_server$ arkmanager start @center
Running command 'start' for instance 'center'
The server is already running
2016-09-17 17:31:07: Start aborted due to server already running
```

**Comment by klightspeed** [comment]
What is the output of `ps -ef | grep 'ShooterGameServer'`

What is `arkserverroot` set to in your instance configs?

What are the `configfile_` lines in arkmanager.cfg?

**Comment by Log1x** [comment]
Will grab the output of `ps -ef` for you when my mods finish updating, but I checked `htop` before I stopped it to update mods and only the Scorched server was running out of of its set `arkserverroot`

**scorched.cfg**
`arkserverroot="/home/steam/servers/arkonia_server/scorched"`
arkautorestartfile="ShooterGame/Saved/.autorestart-scorched"

**center.cfg**
`arkserverroot="/home/steam/servers/arkonia_server/center"`
`arkautorestartfile="ShooterGame/Saved/.autorestart-center"`

**.arkmanager.cfg**
`configfile_center="/home/steam/servers/arkonia_server/center.cfg"`
`configfile_scorched="/home/steam/servers/arkonia_server/scorched.cfg"`

**Comment by klightspeed** [comment]
This should be better behaved in the latest version.

In fact, the latest version should no longer require the directory linking workaround.

**Comment by Log1x** [comment]
Is the latest pushed to 1.6-dev? I updated it last night but looks like you just did a commit. Will try it in a moment, thank you very much in advance. :)

**Comment by klightspeed** [comment]
The latest is now on the master branch.

**Comment by Log1x** [comment]
Looks to be working! Thanks a ton @klightspeed. :heart:

**Comment by Maygus** [comment]
@klightspeed to clarify - we won't need the "arkserverroot" anymore and can remove the symlinks?

**Comment by ryan1161** [comment]
If this is true to remove symlinks how should one go about setting this up?

**Comment by Log1x** [comment]
Yup, there is no longer a need for symlinks.

I have both my Center server and Scorched Earth server running out of /home/steam/pvp

To do this I have a `center.cfg` and `scorched.cfg`.

**scorched.cfg**
```
arkserverroot="/home/steam/servers/arkonia_server/pvp"
arkbackupdir="/backup/steam/servers/arkonia_server/scorched"
arkStagingDir="/home/steam/servers/arkonia_server/pvp/.staging"
logdir="/home/steam/servers/arkonia_server/pvp/.logs"
arkautorestartfile="ShooterGame/Saved/.autorestart-scorched"
```

**center.cfg**
```
arkserverroot="/home/steam/servers/arkonia_server/pvp"
arkbackupdir="/backup/steam/servers/arkonia_server/center"
arkStagingDir="/home/steam/servers/arkonia_server/pvp/.staging"
logdir="/home/steam/servers/arkonia_server/pvp/.logs"
arkautorestartfile="ShooterGame/Saved/.autorestart-center"
```

and then of course setting `ark_AltSaveDirectoryName` for example `ark_AltSaveDirectoryName="SavedArksCenter"` as well as your `ark_SessionName`, `ark_MultiHome`, etc.

No additional configuration is needed.

**Comment by ryan1161** [comment]
Could you give a example of the last two "ark_SessionName" and "ark_MultiHome" Cause I just tried this on my config and got a really big error maybe I'm Inputting something wrong.

**TheIsland**
ark_SessionName="TheIsland"
ark_MultiHome="/home/mc/ARK/TheIsland"
arkbackupdir="/mnt/Backups/Ark/TheIsland"
arkserverroot="/home/mc/ARK/TheIsland" 
ark_AltSaveDirectoryName="Saved-TheIsland"  

**TheCenter**
ark_SessionName="TheCenter"
ark_MultiHome="/home/mc/ARK/TheIsland"
arkbackupdir="/mnt/Backups/Ark/TheCenter"
arkserverroot="/home/mc/ARK/TheIsland" 
ark_AltSaveDirectoryName="Saved-TheCenter"

**ScorchedEarth**
ark_SessionName="ScorchedEarth"
ark_MultiHome="/home/mc/ARK/TheIsland"
arkbackupdir="/mnt/Backups/Ark/ScorchedEarth"
arkserverroot="/home/mc/ARK/TheIsland" 
ark_AltSaveDirectoryName="Saved-ScorchedEarth"

**Comment by Log1x** [comment]
Multi home is the IP address of the server. SessionName is the name of the
server shown in the server browser.

**Comment by ryan1161** [comment]
So I'm now getting this after 5 minutes waiting:

**Comment by Log1x** [comment]
I will get you my entire config when I get home.

**Comment by Log1x** [comment]
Here you go. Left out a couple things such as mods, warning messages, etc. but that should get you setup and know what everything does at the least.

By the way, if you have all of your servers on 1 IP with different port's, there is no point in using `ark_MultiHome`. You'd simply just set your different port numbers instead using `ark_Port` and `ark_QueryPort`.

```
# ARK environment configuration
arkserverroot="/home/steam/servers/arkonia_server/pvp"
arkbackupdir="/backup/steam/servers/arkonia_server/center"
arkStagingDir="/home/steam/servers/arkonia_server/pvp/.staging"
logdir="/home/steam/servers/arkonia_server/pvp/.logs"
arkautorestartfile="ShooterGame/Saved/.autorestart-center"
arkwarnminutes="15"

# SteamCMD environment configuration
steamcmdroot="/home/steam/steamcmd"
steamcmdexec="steamcmd.sh"
steamcmd_user="steam"
steamcmd_appinfocache="/home/steam/Steam/appcache/appinfo.vdf"

# Restart cancel chat command
chatCommandRestartCancel="!cancelrestart"

# ARK server configuration
serverMap="TheCenter"
ark_MultiHome="69.65.49.62"
ark_Port="7778"
ark_QueryPort="27015"
ark_MaxPlayers="64"
ark_SessionName="[NA][PvP][ORP] Arkonia.net - 25xALL"
ark_AltSaveDirectoryName="SavedArksCenter"
ark_GameModIds="XXXXXXXX,XXXXXXX"

# ARK server flags
arkflag_log="true"
arkflag_UseBattlEye=true
arkflag_noantispeedhack="true"
arkflag_ForceAllowCaveFlyers="true"
arkflag_gameplaylogging="true"
arkflag_NoTransferFromFiltering="true"

# ARK server options
arkopt_clusterid="cluster1"
```

**Comment by ryan1161** [comment]
I have this on the same ip and the ports are different I attached my configs to the other post. Another thing is my version of arkmanager is 1.5 I try to get 1.6 but it say 1.5 is the latest version of this tool.

**Comment by klightspeed** [comment]
What is the output of `arkmanager --version`?

What is the output of `grep 'git/refs/heads' /usr/local/bin/arkmanager`

**Comment by arkfrance** [comment]
so just need to add those lines to allow transfert for players on 3 différents cfg ?

arkflag_NoTransferFromFiltering=true
arkopt_clusterid=Cluster1

**Comment by klightspeed** [comment]
As shown in #631, as of v247.85, you can use `arkflag_ClusterDirOverride=/path/to/shared/dir` to allow intra-cluster transfer between servers running from different directories.

**Comment by arkfrance** [comment]
anyone has a tutorial to make it happen ?

so what happens if i only add those command below ?

**Comment by arkfrance** [comment]
/home/CENTPVE/ShooterGame/Saved/SavedArks

/home/PVE/ShooterGame/Saved/SavedArks

/home/SCOR/ShooterGame/Saved/SavedArks

that's the path to the 3 servers on the same linux engine

**Comment by klightspeed** [comment]
If for example you wanted to enable intra-cluster transfer between those servers, you could create e.g. `/home/PVECluster`, and add `arkopt_ClusterDirOverride=/home/PVECluster` to all three instances.

**Comment by arkfrance** [comment]
ok and in all cfg i need to add that right : 

arkflag_NoTransferFromFiltering=true
arkopt_clusterid=pve
ark_PreventDownloadSurvivors=False
ark_PreventDownloadItems=False
ark_PreventDownloadDinos=False
ark_PreventUploadSurvivors=False
ark_PreventUploadItems=False
ark_PreventUploadDinos=False
ark_noTributeDownloads=false
arkopt_ClusterDirOverride=/home/PVECluster

**Comment by klightspeed** [comment]
If the v247.85 change notes are to be believed, yes that should enable transfers between servers in that cluster.

I suspect however that if the game servers have different engram mods, the transfers may not work correctly.

**Comment by Maygus** [comment]
No. It works. You just need mindwipes.

**Comment by arkfrance** [comment]
Works for me but tamed dino are not following, got my inventory but no dino with me

**Comment by Maygus** [comment]
Be sure to allow dino downloads explicitly. I had to.

**Comment by arkfrance** [comment]
that ?
PreventDownloadSurvivors=False
PreventDownloadItems=False
PreventDownloadDinos=False
PreventUploadSurvivors=False
PreventUploadItems=False
PreventUploadDinos=False

**Comment by arkfrance** [comment]
anything ?

**Comment by klightspeed** [comment]
If specifying those in the `GameUserSettings.ini`, yes.
If specifying those in your instance config, prefix them with `ark_`

**Comment by arkfrance** [comment]
They are but the tamed dinos are not following
