### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#579]
Hi,

my server is crashing, i've tried to disable the mod folder by rename it to mods1 and the server works fine now, so it's not coming from the 

ark_GameModIds=""

but it's coming from an installed mod in the folder i guess

**Comment by arkfrance** [comment]
ok now it seems to works but all mods structures are vanish, i tried to use an older save but it auto transforme it to 309 mo to 212 mo at start up ...

**Comment by klightspeed** [comment]
I have seen in the past that some mods will crash the server if installed into the Mods directory but not enabled.

It also sounds like the ARK server is deleting structures from mods that are no longer enabled.

You will likely need to check by elimination which mod is causing the server crash, and then restore the latest good save.

**Comment by arkfrance** [comment]
seems to work fine now but ark still deleting stuctures even if the mod is enable, i can place some items from the mod. i've tried to launch a different save and it doesn't work it auto delete mods structure at launch

**Comment by arkfrance** [comment]
the center was 306 mo and at launch 178 now

**Comment by klightspeed** [comment]
So it did it not on just the server that was crashing, but on all of your servers?  Is it the same mod that is affected on all of your servers?  In that case, you might want to talk to the mod author.

**Comment by arkfrance** [comment]
it seems that all the mods are active but after the 246 update it has been a wipe from mods structures, but mods are working fine, i just can't rollback to an old save because it auto remove old mods structures at launch

**Comment by arkfrance** [comment]
Hey guys,

Just wanted to update you on the current save situation. Players have been reporting issues with their save games being wiped upon load, we have identified the root of the problem and it was caused by a bad-merge when porting over some PC code to the Xbox codebase. Unfortunately any saves that were wiped due to this mistake are not restorable. Anyone who attempts to load their save will have it wiped, so we suggest that if you have not loaded your save games so far, you do not do so. Playing on Official Servers will be the safer option for the time being.

We have fixed the problem and are submitting it to Microsoft immediately, alongside some other fixes, and asking for an urgent update so that future saves and those currently unaffected will not be wiped. I understand it does not do any good for those affected, this is a total mess up on our part and we’re terribly sorry that it has occurred.

We’re going to keep looking through the reports we receive and rapidly iterate to get the issues resolved as soon as possible. Here are our current notes which we’ll keep updated as we resolve more bugs:

that should be my problem, should be the same for pc

**Comment by arkfrance** [comment]
it loads wiping mods structures

**Comment by klightspeed** [comment]
The ARK server should itself automatically create backups in the SavedArks directory every few hours, so I would grab those saves and put them somewhere safe for when Wildcard fixes this issue.

**Comment by arkfrance** [comment]
i've been able to rollback to a old save but now it crashs again and again .... pffff

**Comment by arkfrance** [comment]
I already mentioned this in the bug report thread , but if ACM was broken by the V246 update, as a lot of mods were, then only further updates by Wildcard to ARK or a new DevKit(which we won't have for at least two weeks as Drake has suggested) update will get it working again.

Nothing can be done until either of these happen.

-WM
