### ISSUE TITLE
GameUserSettings.ini reset auto

### ISSUE THREAD

**Issue by patograso** [FezVrasta/ark-server-tools#581]
I am trying to change harvestamount in my conf file:
/home/steam/ARK/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

 but each time i start the serv, the conf file reset.

Am i in the wrong file ?

**Comment by klightspeed** [comment]
So is the config file being reset to defaults, or is the HarvestAmountMultiplier just being cleared or reset to 1.0?

**Comment by patograso** [comment]
before my change i have :

`[SessionSettings]
SessionName=Pato test X2 v0.1

[/Script/Engine.GameSession]
MaxPlayers=70

[ServerSettings]
ServerCrosshair=True
RCONPort=27020
StructurePreventResourceRadiusMultiplier=1.000000
RaidDinoCharacterFoodDrainMultiplier=1.000000
PvEDinoDecayPeriodMultiplier=1.000000
KickIdlePlayersPeriod=3600.000000
PerPlatformMaxStructuresMultiplier=1.000000
AutoSavePeriodMinutes=15.000000
ListenServerTetherDistanceMultiplier=1.000000
MaxTamedDinos=5000.000000
RCONServerGameLogBuffer=600.000000
AllowHitMarkers=True
`
At the end of file i add 

`NewMaxStructuresInRange=5000.000000
DayCycleSpeedScale=1.000000
DayTimeSpeedScale=1.000000
NightTimeSpeedScale=1.000000
DinoDamageMultiplier=1.000000
PlayerDamageMultiplier=1.000000
StructureDamageMultiplier=1.000000
PlayerResistanceMultiplier=1.000000
DinoResistanceMultiplier=1.000000
StructureResistanceMultiplier=1.000000
XPMultiplier=2.000000
TamingSpeedMultiplier=2.000000
HarvestAmountMultiplier=2.000000
PlayerCharacterWaterDrainMultiplier=1.000000
PlayerCharacterFoodDrainMultiplier=1.000000
DinoCharacterFoodDrainMultiplier=1.000000
PlayerCharacterStaminaDrainMultiplier=1.000000
DinoCharacterStaminaDrainMultiplier=1.000000
PlayerCharacterHealthRecoveryMultiplier=1.000000
DinoCharacterHealthRecoveryMultiplier=1.000000
DinoCountMultiplier=2.000000
HarvestHealthMultiplier=1.000000
PvEStructureDecayPeriodMultiplier=1.000000
ResourcesRespawnPeriodMultiplier=1.000000`

I save the file and start the serv.

Then i stop serv and check my file, so i went back to the previous state

**Comment by klightspeed** [comment]
Please check and try a few things:

* Make sure there is a blank line at the end of the file
* Make sure your editor isn't adding any non-ascii characters (such as the [UTF-8 BOM](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8))
  - You can check this by running `grep $'[\x7F-\xFF]' GameUserSettings.ini | xxd`
* Make sure all of the settings you are adding are valid (e.g. are listed in http://ark.gamepedia.com/Server_Configuration)

**Comment by patograso** [comment]
ok i will try this

**Comment by patograso** [comment]
grep return me : 

`grep: Invalid collation character`

**Comment by klightspeed** [comment]
Try:

```
LC_COLLATE=C grep $'[\x7F-\xFF]' GameUserSettings.ini | xxd
```

**Comment by patograso** [comment]
return nothing

**Comment by klightspeed** [comment]
Is this with the config you're trying to set?

**Comment by patograso** [comment]
GameUserSettings.ini still reset himself even with empty line at end of file

**Comment by patograso** [comment]
> Is this with the config you're trying to set?

excuse me i didn't understand what do you mean

**Comment by klightspeed** [comment]
Would you please upload the complete config, with any passwords removed.

**Comment by patograso** [comment]
sure just tell me what file you need

**Comment by klightspeed** [comment]
Would you please upload the complete `GameUserSettings.ini` you are trying to set, with any passwords removed.

**Comment by patograso** [comment]
before i make the change : 

http://paste.debian.net/806208/

and after :

http://paste.debian.net/806209/

**Comment by patograso** [comment]
PS : i am on a fresh install

**Comment by klightspeed** [comment]
In my test, it seems to be removing lines that are already set to default settings.

It is keeping the following settings, which are not on your pre-config.
```
DifficultyOffset=1.000000
XPMultiplier=2.000000
TamingSpeedMultiplier=2.000000
HarvestAmountMultiplier=2.000000
DinoCountMultiplier=2.000000
```

Do you have any of the following settings in /etc/arkmanager/instances/main.cfg:
```
ark_DifficultyOffset=0.2
ark_XPMultiplier=1.000000
ark_TamingSpeedMultiplier=1.000000
ark_HarvestAmountMultiplier=1.000000
ark_DinoCountMultiplier=1.000000
```

**Comment by patograso** [comment]
my main.cfg : 
``# config environment
arkserverroot="/home/steam/ARK"                                     # path of your ARK server files (default ~/ARK)

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="ScorchedEarth_P"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
#ark_RCONEnabled="True"                                              # Enable RCON Protocol
#ark_RCONPort="32330"                                                # RCON Port
#ark_SessionName="patograso X2"                                  # if your session name needs special characters please use the .ini instead
#ark_Port="7778"                                                     # ARK server port (default 7778)
#ark_QueryPort="27015"                                               # ARK query port (default 27015)
#ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
#ark_ServerAdminPassword="XXXXXXXXXX"                               # ARK server admin password, KEEP IT SAFE!
#ark_MaxPlayers="30"
#ark_GameModIds="733089781"                     # Uncomment to specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
arkflag_UseBattlEye=true

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures

**Comment by klightspeed** [comment]
Please check for the following settings in `/home/steam/ARK/ShooterGame/Saved/Config/CleanSourceConfigs/GameUserSettings.ini`

```
DifficultyOffset=1.000000
XPMultiplier=2.000000
TamingSpeedMultiplier=2.000000
HarvestAmountMultiplier=2.000000
DinoCountMultiplier=2.000000
```

**Comment by patograso** [comment]
> /home/steam/ARK/ShooterGame/Saved/Config/CleanSourceConfigs/GameUserSettings.ini

DifficultyOffset=1.000000
XPMultiplier=2.000000
TamingSpeedMultiplier=2.000000
HarvestAmountMultiplier=2.000000
DinoCountMultiplier=2.000000

 vok

**Comment by patograso** [comment]
as i am on a fresh install, i can easyly remove everything

**Comment by klightspeed** [comment]
So those settings would have still been getting applied.  However, the ARK server would have been removing them from `LinuxServer/GameUserSettings.ini` because they were present in `CleanSourceConfigs/GameUserSettings.ini`

**Comment by patograso** [comment]
Oh i am really sorry for make you loose this time

**Comment by klightspeed** [comment]
Well, you learn something new every day...

**Comment by patograso** [comment]
Thks a lot so for your time

**Comment by Alphascrypt** [comment]
https://pastebin.com/jX1mZL8B



`<?xml version="1.0" encoding="utf-8"?>
<image>
  <steamgame>S</steamgame>
  <appID>376030</appID>
  <updates>1</updates>
  <shorten>arkse</shorten>
  <description>ARK: Survival Evolved</description>
  <type/>
  <gamebinary>ShooterGameServer</gamebinary>
  <gamebinaryWin/>
  <binarydir>ShooterGame/Binaries/Linux</binarydir>
  <modfolder/>
  <fps/>
  <slots>20</slots>
  <map>TheIsland</map>
  <mapGroup/>
  <cmd>./%binary% %map%?listen?MultiHome=%ip%?Port=%port%?QueryPort=%port2%?RCONPort=%port3%?MaxPlayers=%slots% -server -log</cmd>
  <modcmds/>
  <tic/>
  <gameq>arkse</gameq>
  <gamemod>N</gamemod>
  <gamemod2/>
  <configs>ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini full&#13;
ShooterGame/Saved/Config/LinuxServer/Game.ini full</configs>
  <configedit>[ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini] ini&#13;
MaxPlayers=%slots%</configedit>
  <iptables/>
  <protectedSaveCFGs/>
  <portStep>10</portStep>
  <portMax>3</portMax>
  <portOne>27015</portOne>
  <portTwo>27016</portTwo>
  <portThree>27017</portThree>
  <portFour/>
  <portFive/>
  <useQueryPort>2</useQueryPort>
  <protected>N</protected>
  <ramLimited>N</ramLimited>
  <ftpAccess>Y</ftpAccess>
  <workShop>N</workShop>
  <copyStartBinary>Y</copyStartBinary>
  <os>L</os>
  <liveConsole>Y</liveConsole>
  <steamGameserverToken>N</steamGameserverToken>
  <serverID>376030</serverID>
</image>`
