### ISSUE TITLE
Run multiple instances from the same directory.

### ISSUE THREAD

**Issue by arkmuppet** [FezVrasta/ark-server-tools#587]
From my understanding to be able to have transfer from TheCenter to Scorched Earth you need to have two servers running from the same directory and the cluster flags set. Currently the instances have to be run from separate ark directories. Is there any way to run two instances from the same directory?

**Comment by AnEmortalKid** [comment]
You could copy the configurations, and edit the .cfg files to use the same directory (and have them run on different ports)

**Comment by AnEmortalKid** [comment]
Actually, see this: https://github.com/FezVrasta/ark-server-tools/issues/578 you can't run two instances from the same directory at the moment.

**Comment by arkmuppet** [comment]
Closing the issue. Thankyou!
