### ISSUE TITLE
Ark restarts as root after server reboots

### ISSUE THREAD

**Issue by Kasys** [FezVrasta/ark-server-tools#589]
My server restarts once a day because i had problems with some services, when it ran longer than a day.
Now i hosted an ark server to play on with friends. After we stopped playing i used arkmanager stop to shutdown the server. Now when i came on today, i saw ark was up and running as root.

**Comment by AnEmortalKid** [comment]
I've had this same problem. I recently updated the tools to the latest version too:
```
Version: 1.5
Channel: master
Commit: c0c56ab
```

**Comment by klightspeed** [comment]
What is the output of `ps -AHF` (limited to the top-most arkmanager process and its descendants), with any passwords and other sensitive info removed?

**Comment by Kasys** [comment]
since i shutdown and then restarted the server manually, ps -AHF shows the correct user now
but i think i found the problem
in the arkmanager@.service file the user to run as was set to root, so i changed it to the proper user
as that is what starts the server on boot (i think?)
which file would i have to change, to completely disable automatic startup tho?
i don't need this function since the server should only be up when i'm playing on it

**Comment by klightspeed** [comment]
If you don't want the server to automatically start, then run `systemctl disable arkmanager`

**Comment by Kasys** [comment]
okay i'll do that thanks
