### ISSUE TITLE
Question rather than an issue about updating multiple instances

### ISSUE THREAD

**Issue by Chingis-Khan** [FezVrasta/ark-server-tools#591]
Hi

I have two instances running at the moment.  My question is with the update of the server and mods when they share the same staging directory, I believe that arkmanager has to download the mod before it can check to see if it has been updated.

If the two instances are also sharing the same mods or mostly the same mods does the update process download them twice to check for updates?  Do I need to run an update for each instance separately?

**Comment by klightspeed** [comment]
The mods do not currently share a staging directory (apart from the SteamCMD workshop content directory).  SteamCMD should check whether the mod is up-to-date and return fairly quickly if the latest version of the mod has already been downloaded.

If the instances are not sharing the same physical directory, then each instance must be updated separately.  If the instances do share the same physical directory (which would require them to be part of the same cluster), then only one instance needs to be updated, but both instances need to be stopped before the update.

**Comment by rob-bb** [comment]
I didn't think I could share the directory?  So I have a separate directory tree for each server including mod dirs and saved dirs.  Basically they are duplicates except for the map and save files

**Comment by klightspeed** [comment]
When the `-clusterid=clustername` option is used, the ARK server likely uses inter-process communication to prevent conflicts.

arkmanager is not currently able to allow multiple server instances to run from the same directory.  You would need to follow something like what ryan1161 wrote in https://github.com/FezVrasta/ark-server-tools/issues/578#issuecomment-244962370; I don't know if all game servers in the cluster need to have the same mods enabled.

**Comment by klightspeed** [comment]
v1.6 should now support having multiple instances in a cluster running from the same directory.
