### ISSUE TITLE
Update bug

### ISSUE THREAD

**Issue by Kasys** [FezVrasta/ark-server-tools#592]
I set autoupdateonstart in the the config file (cfg of arkmanager) to true, so i don't have to update the server manually.
But whenever the server updates on startup now after updating i get some error messages.
After that two instances of the ark server start, resulting in nobody being able to connect.
After i shut the server down and start it again, everything works as normal, except all tamed dinos are gone. I guess starting two instances messes something there with the server.
I will add the output from the bugged start when it happens to me again (so probably when the game is next updated)

**Comment by klightspeed** [comment]
0c2bb68 should fix this.

**Comment by Kasys** [comment]
okay i will try that and see if it works when the next ark update is released

**Comment by klightspeed** [comment]
v1.6 has now been released.
