### ISSUE TITLE
Server not showing up on Master List

### ISSUE THREAD

**Issue by ryan1161** [FezVrasta/ark-server-tools#593]
![all green](https://cloud.githubusercontent.com/assets/2374149/18323625/0d35dd70-74fe-11e6-949d-107bc403e409.png)
When I first had one server back when this tool was on version 1.4 it would show up in 5 minutes after coming online. But now with my three servers Ive let them run for months and they never seem to show up at all unless I add them manually in steam client server browsers. I've tried things like port gap of 20 but it doesn't make a differences they still don't show up. I want them to show up cause I have them in cluster now where I can now join it in-game but it has to show up under the master list to do so there is no option to choose favorites in-game unless I completely disconnected from that server. But the real issue is no one out there will ever be-able to play on my server we like the challenge of other survivors on map but right now it's only my 3 friends and they hate that I can't fix this issue I'm just wonder if you have any more solutions that could help me out. I do have full access to my server and router. Ive completely remove the firewall to my server since I'm behind a router.
[arkmanager.zip](https://github.com/FezVrasta/ark-server-tools/files/460031/arkmanager.zip)

**Comment by klightspeed** [comment]
Make sure you have the appropriate port forwards setup on your router.

Your servers are in fact on the master server list - http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=68.191.213.222.  However, they are not reachable from the outside world, and so will not show up on any clients.

Note also that some routers are unable to forward packets coming from inside the router back to a server behind the router (sometimes called Hairpin or Loopback NAT).

**Comment by ryan1161** [comment]
Well I found my issue it was my router had two ISP and my server was going out on one ISP and coming in the other ISP so packs were getting drooped. Closing this issue.
