### ISSUE TITLE
Server hang

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#594]
Hey, 

is this update : 

* Fixed a server hang.
* Added extra hang protection to server where if it hangs for more than 30 minutes at startup and 15 minutes thereafter, it will automatically shut down).

can break the ark server tools ?

**Comment by klightspeed** [comment]
In the first case (hanging at startup), after the server exits, it will be restarted if `arkAlwaysRestartOnCrash` is set.

In the second case (hanging after startup), after the server exits, it will be restarted.

**Comment by badboysgaming** [comment]
wasn't issue with ark server tools was issue with server its self was patched ealier

**Comment by arkfrance** [comment]
ok just one more thing : 

arkmanager useconfig pvp status
Running command 'status' for instance 'pvp'
 Server running:   Yes 
 Server listening:   Yes 
Server Name: ARK-FRANCE.FR - PVE x5 SCORCHED EARTH (1) - (v246.71)
Players: 33 / 60
Active Players: 32
 Server online:   Yes 
 ARKServers link:   http://arkservers.net/server/149.202.86.142:27017 
 Server build ID:   1324084 
/usr/local/bin/arkmanager: line 2289: /home/SCR/version.txt: No such file or directory
 Server version: 

there is no more version.txt file :)

**Comment by klightspeed** [comment]
Looks like Wildcard removed it in the last few weeks.

**Comment by arkfrance** [comment]
Yep you can remove it i guess
