### ISSUE TITLE
number of players

### ISSUE THREAD

**Issue by boistordu** [FezVrasta/ark-server-tools#600]
Hi,

I have at the moment 3 players notified in arkmanager.
but I have only one friend on my server at the moment and steam notify me to have only 1 player too....

**Comment by klightspeed** [comment]
This should be fixed in the latest version.

**Comment by boistordu** [comment]
semmes to for the moment. I will monitor for a few days and then close th eticket if it's still okey

**Comment by boistordu** [comment]
I have this some times xwith the new version : 
```
 Server running:   Yes 
 Server listening:   Yes 
Server Name: Barricade - (v247.5)
Players: 1 / 5
Active Players: 0
 Server online:   Yes 
 ARKServers link:   http://arkservers.net/server/...:...
 Server build ID:   1346321 
 Server version:   245.99 
```

**Comment by klightspeed** [comment]
Delete the `version.txt` file - Wildcard Studios stopped including it with v246.

**Comment by boistordu** [comment]
ok done it.... but we are at the 245.99 isn t that a problem? I will see then rebuild the docker when we go to the 246

**Comment by boistordu** [comment]
my bad we are at 247. seems that I have more deeper problems that I've imagined. I will continue to monitor the situation

**Comment by boistordu** [comment]
by the way it's always on this form : 
 ```
Server running:   Yes 
 Server listening:   Yes 
Server Name: barricade - (v247.998)
Players: 0 / 5
Active Players: 0
 Server online:   Yes 
 ARKServers link:   http://arkservers.net/server/
 Server build ID:   1392953 
```
but even if there are time to time a difference between player and active player it is not very  a problematic situation
