### ISSUE TITLE
Need Help with Auto Update Please

### ISSUE THREAD

**Issue by patograso** [FezVrasta/ark-server-tools#602]
Hi,
i wish to auto update my serv, it seems cron is the best way, i try to search here but i am not sure of what i may to use.

I would like to check for update every 30 minutes i'd like something like that:
```
>Check update > if update available : 
                                >check if serv empty then DoUpdate 
                                >Else  update --warn
>Else do nothing
```

**Comment by klightspeed** [comment]
`arkmanager update --warn` should do exactly this.

It will check if an update is available.
If an update is available, then:
 - If you have `arkStagingDir` set to a staging directory, then it will download the update to that directory
 - It will then begin warning players that the game server will be shutting down for an update
 - Once either nobody is connected to the server or the warning time expires, it will shut down the game server.  This means that if nobody is connected to the server when the update is started then the game server will immediately shut down.
 - Once the game server is shut down, it will apply the update and restart the server.

**Comment by patograso** [comment]
Ho, thank you very much.
