### ISSUE TITLE
Restart Server If Updated While Running

### ISSUE THREAD

**Issue by Gumballz** [FezVrasta/ark-server-tools#603]
Restart If updated while running doesn't appear to be working.

After running update on first instance and then running 
`arkmanager update --update-mods --saveworld --backup --warn @island`
on the 2nd sintance, Arkmanager reported
`Your server is already up to date! The most recent version is 1337837.`

Arkmanager status report..

 ```
Running command 'status' for instance 'scorch'
Server running:   Yes
 Server listening:   Yes
Server Name: sARKarium.com UK PVE Scorched Earth - (v247.3)
Players: 5 / 50
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/164.132.201.19:27015
 Server version:   1337837
Running command 'status' for instance 'island'
 Server running:   Yes
 Server listening:   Yes
Server Name: sARKarium.com UK PVE 2x Modz - (v247.2)
Players: 11 / 50
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/164.132.201.19:27025
 Server version:   1337837
```
@scorch updated as normal.
expecting @island to restart, but didn't

Edit :- 
```
 arkmanager --version
Version: 1.5
Channel: master
Commit: 8c05d7b

```

**Comment by klightspeed** [comment]
A workaround is to set `arkautorestartfile=ShooterGame/Saved/.autorestart-<name>` in the instance config, where `<name>` is the name of the instance.

**Comment by Gumballz** [comment]
thanx for the quick reply :)

**Comment by Gumballz** [comment]
Back Again. 
altering the auto restart works fine for ARK version but it doesn't pick up mods updated in the background.

A possible solution to this could be something like...

`onupdate() {

if exists (updatedby.txt) & contents <> current.instance.name (
  update.command = update.command + --force;
  delete updatedby.txt )
 else run_update as normal.
  if updated (
         save updatedby.txt (contents=current.instance.name) )
}
`
If I knew how to right the code myself, I would do .. but unfortunately I'm inept  :(

Cheers

**Comment by klightspeed** [comment]
Did commit 8c05d7b not fix this?

**Comment by Gumballz** [comment]
Cheers.  Will let you know next time there's an update

**Comment by Gumballz** [comment]
Working as intended :)  Thank you
