### ISSUE TITLE
Problems With Shutdown..

### ISSUE THREAD

**Issue by Gumballz** [FezVrasta/ark-server-tools#608]
Hi, Tools upgraded to V1.6

Ran a stop on instance1 all appeared fine.

Attempted to run a stop on 2nd instance and reported the instances was not running.. although it was.

Decided to try a start instance2 in hopes of a quick workaround... appeared to work.. reported it had started.

Attempted to stop instance2 and it reported the Shutdown was already in progress (PID: 21994)

I'm guessing it was reading the shutdown progress of the first server1 ?

I was running on the same user in 2 instances of putty while attempting this (worked fine previously in v1.5)

After shutdown process was run.   Both servers were still live and running... with the following status reports..

```
Running command 'status' for instance 'scorch'
 Server running:   No
 Server listening:   Yes
Server Name: sARKarium.com UK PVE Scorched Earth - (v247.3)
Players: 4 / 50
Active Players: 2
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/164.132.201.19:27015
 Server build ID:   1337837
Running command 'status' for instance 'island'
 Server running:   No
 Server listening:   Yes
Server Name: sARKarium.com UK PVE 2x Modz - (v247.3)
Players: 1 / 50
Active Players: 0
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/164.132.201.19:27025
 Server build ID:   1337837

```
After killing the 2 servers, restarted the servers as normal. 
Appeared to function correctly with correct information on both servers.

**Comment by klightspeed** [comment]
What are the contents of your instance configs, with any passwords removed?

The "shutdown already in progress" suggests that you used `arkmanager shutdown --warn`

The instance not running suggests that `arkserverpidfile` was set.

What dot files exist in your `ShooterGame/Saved` directory?

**Comment by Gumballz** [comment]
files in the saved directory are ..
`
.autostart-island
.arkserver-island.pid
.arkmanager-island.pid
.autostart-scorch
.arkserver-scorch.pid
.arkmanager-scorch.pid
.autorestart`

Have run updates on both servers since and everything is fine.

I'm guessing the issue was because I ran upgrade-tools on arkmanager while the servers were running ?

**Comment by klightspeed** [comment]
The upgrade switched from using `ps -ef` to using a PID file when `clusterid` is set.  Perhaps we should add an option to use `ps -ef` when stopping in order to stop servers that were running while upgrading.

With the backup, we'll also have to only copy the files if they exist.

**Comment by Gumballz** [comment]
sounds like you have it in hand :)
