### ISSUE TITLE
Unable To Shutdown Multiple Instances Simultaniously

### ISSUE THREAD

**Issue by Gumballz** [FezVrasta/ark-server-tools#609]
Whenever I try to shutdown 2 instances at the same time, it returns the error 
`Shutdown warning already in progress` for the second instance.

To shutdown the 2 instances, I am using the same user in 2 Putty windows.
This method worked previously in earlier version and only stopped working in V1.6.
Initially I thought this didn't work due to upgrading Arkmanager while the servers were running, but still ran into this issue on subsequent shutdown attempts. 

. files in the saved directory are 

```
.arkmanager-island.pid
.arkmanager-scorch.pid
.arkserver-island.pid
.arkserver-scorch.pid
.autorestart
.autorestart-island
.autorestart-scorch
```
Any help appreciated :)
Cheers

**Comment by klightspeed** [comment]
I'll create a fix to link the warning to the instance.

**Comment by klightspeed** [comment]
Please let me know if the latest release fixes your issue.

**Comment by Gumballz** [comment]
Perfect :)
Cheers
