### ISSUE TITLE
Server No start

### ISSUE THREAD

**Issue by super54** [FezVrasta/ark-server-tools#61]
Hi,

When I start my server, no message it's OK but when i try to look status the server is not running
```
steam@:~/cmd$ arkmanager start 
17:48:12: start
steam@:~/cmd$ arkmanager status
 Server running:  No
 Server online:   No
 Server version:  672599
```
I have a create new folder and i have new install, i just copy my saved data => https://github.com/FezVrasta/ark-server-tools/issues/56

my conf :
```
# config SteamCMD
steamcmdroot="/home/steam/cmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="steam"                                               # name of the system user who own steamcmd folder

# config Server
sessioname=YourLinuxSessionName
arkserverroot="/home/steam/ark"                                     # path of your ARK server files (default ~/ARK)
arkserverexec="/home/steam/ark/ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkqueryport="27016"                                                # ARK query port (default 27016)
arkserverport="7778"                                                # ARK server port (default 7778)
arkserverpass=""                                      # ARK server password, empty: no password required to login
arkserverapass="****"                                      # ARK server admin password, KEEP IT SAFE!

# config Service
servicename="arkserv"                                               # Name of the service (don't change if you don't know what are you doing)
logdir="/var/log/arktools"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID

# admin information
servermail=""                                                       # Log email, leave blank if you dont want to receive mail
```

Update.log : 

```                                                                       
12:24:34: update to  complete
12:25:55: update to  complete
15:24:05: No update needed.
17:46:52: No update needed.
```

Arkserver.log :
```
12:28:21: start
12:42:00: stop
17:47:36: start
17:48:12: start
```

I start my server with this command it's OK : 
```
/home/steam/ark/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?listen?SessionName=[FR/PVE][24/7]Super54-SRV?ServerAdminPassword=**** -server -log
```

Thanks for your help

**Comment by Atriusftw** [comment]
What does your GameUserSettings.ini look like? Have you defined some ports in there?

**Comment by super54** [comment]
GameUsersSettings.ini :

[/Script/ShooterGame.ShooterGameUserSettings]
MasterAudioVolume=1.000000
MusicAudioVolume=1.000000
SFXAudioVolume=1.000000
VoiceAudioVolume=1.000000
CameraShakeScale=1.000000
bFirstPersonRiding=False
bThirdPersonPlayer=False
bShowStatusNotificationMessages=True
TrueSkyQuality=0.270000
FOVMultiplier=1.000000
GroundClutterDensity=1.000000
bFilmGrain=False
bMotionBlur=True
bUseDFAO=True
bUseSSAO=True
bShowChatBox=True
bCameraViewBob=True
bInvertLookY=False
bFloatingNames=True
bChatBubbles=True
bHideServerInfo=False
bJoinNotifications=False
bCraftablesShowAllItems=True
LookLeftRightSensitivity=1.000000
LookUpDownSensitivity=1.000000
GraphicsQuality=2
ActiveLingeringWorldTiles=10
LastServerSearchType=0
LastServerSearchHideFull=False
LastServerSearchProtected=False
HideItemTextOverlay=False
bDistanceFieldShadowing=True
LODScalar=1.000000
HighQualityMaterials=True
HighQualitySurfaces=True
bTemperatureF=False
bDisableTorporEffect=False
bUseVSync=False
ResolutionSizeX=1280
ResolutionSizeY=720
LastUserConfirmedResolutionSizeX=1280
LastUserConfirmedResolutionSizeY=720
WindowPosX=-1
WindowPosY=-1
bUseDesktopResolutionForFullscreen=False
FullscreenMode=2
LastConfirmedFullscreenMode=2
Version=5

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=3
sg.ShadowQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=3
sg.EffectsQuality=3
sg.TrueSkyQuality=3
sg.GroundClutterQuality=3
sg.IBLQuality=1
sg.HeightFieldShadowQuality=3

[ServerSettings]
ServerAdminPassword=***
MaxStructuresInRange=1300.000000
ShowMapPlayerLocation=False
ServerHardcore=False
GlobalVoiceChat=False
ProximityChat=True
NoTributeDownloads=True
AllowThirdPersonPlayer=True
AlwaysNotifyPlayerLeft=False
DontAlwaysNotifyPlayerJoined=True
ServerPVE=True
ServerCrosshair=True
ServerForceNoHUD=False
DayCycleSpeedScale=1.000000
NightTimeSpeedScale=1.000000
DayTimeSpeedScale=1.000000
DinoDamageMultiplier=1.000000
PlayerDamageMultiplier=1.000000
StructureDamageMultiplier=1.000000
PlayerResistanceMultiplier=1.000000
DinoResistanceMultiplier=1.000000
StructureResistanceMultiplier=1.000000
XPMultiplier=1.000000
TamingSpeedMultiplier=1.000000
HarvestAmountMultiplier=1.000000
HarvestHealthMultiplier=1.000000
PlayerCharacterWaterDrainMultiplier=1.000000
PlayerCharacterFoodDrainMultiplier=1.000000
DinoCharacterFoodDrainMultiplier=1.000000
PlayerCharacterStaminaDrainMultiplier=1.000000
DinoCharacterStaminaDrainMultiplier=1.000000
PlayerCharacterHealthRecoveryMultiplier=1.000000
DinoCharacterHealthRecoveryMultiplier=1.000000
DinoCountMultiplier=1.000000
ServerPassword=
DifficultyOffset=0.000000
PvEStructureDecayPeriodMultiplier=1.000000
ResourcesRespawnPeriodMultiplier=1.000000

**Comment by Atriusftw** [comment]
Did you edit your firewall accordingly to your config?

```
iptables -I INPUT -p udp --dport 27016 -j ACCEPT
iptables -I INPUT -p tcp --dport 27016 -j ACCEPT
iptables -I INPUT -p udp --dport 7778 -j ACCEPT
iptables -I INPUT -p tcp --dport 7778 -j ACCEPT
```

**Comment by Atriusftw** [comment]
Oh, actally. It is a wrong path in your config file.

Change

```
arkserverexec="/home/steam/ark/ShooterGame/Binaries/Linux/ShooterGameServer"
```

To

```
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"
```

**Comment by super54** [comment]
Ok it's start

steam@sd-47128:~/cmd$ arkmanager status
 Server running:  Yes
 Server online:   No
 Server version:  672599

Why server online = NO ?

Thanks for all

**Comment by Atriusftw** [comment]
Just give it some time. It takes some time before the listening port binds.
Check again after around 3-5~ minutes.

You can also check manually by issuing the following command and checking if port 7778 is bound:

```
netstat -puln | grep ShooterGame
```

**Comment by super54** [comment]
Yes it's OK ^^

 arkmanager status
 Server running:  Yes
 Server online:   Yes
 Server version:  672599

But know i don't see my server on steam and at => http://arkservers.net/server/62.210.217.15:27015

**Comment by Atriusftw** [comment]
You have to open your ports =)

````
Nmap scan report for 62-210-217-15.rev.poneytelecom.eu (62.210.217.15)
Host is up (0.061s latency).
PORT      STATE  SERVICE
27016/tcp closed unknown
````

Starting Nmap 6.47 ( http://nmap.org ) at 2015-06-26 17:34 CEST
Nmap scan report for 62-210-217-15.rev.poneytelecom.eu (62.210.217.15)
Host is up (0.060s latency).
PORT     STATE  SERVICE
7778/tcp closed interwise
````

````
Nmap scan report for 62-210-217-15.rev.poneytelecom.eu (62.210.217.15)
Host is up (0.058s latency).
PORT     STATE  SERVICE
7777/tcp closed cbt
````

**Comment by super54** [comment]
Yes you can connect because i have start my server with command lien dont with script. My port on m'y server are all open. Its work with command line but notre with script

You know what is the problem?

**Comment by Atriusftw** [comment]
Well, you're using port 27015 now. In your config file you are using 27016 (which is closed)
Either you have to open port 27016, or change it to 27015 (which looks open from here, only UDP though) in your config.

**Comment by super54** [comment]
I have dont active any rules in iptable or firewall and the default is all open. My server its an online.net server.

**Comment by Atriusftw** [comment]
Your host might block some ports, i don't know that particular hosting company.

You can change the queryport to 27015 in your config file, and you should be good to go as far as my portscan can tell.

**Comment by super54** [comment]
Ok i test this at sunday night. Thé config is in arkdaemon.cfg ?

**Comment by super54** [comment]
I have configure cfg with 27015 its ok thanks for all
