### ISSUE TITLE
is it possible that the arkmanager doesn't work well with ip change?

### ISSUE THREAD

**Issue by boistordu** [FezVrasta/ark-server-tools#610]
I have regularly this problem: 
```
 Server running:   Yes 
 Server listening:   No 
 Server build ID:   1347876 
 Server version:   245.99 
```
I think it's come with an ip change because I'm not yet on a fixed ip.... could you look into it?

**Comment by klightspeed** [comment]
Are you using the ark_MultiHome setting?

If not, then the ARK server should be listening on all addresses.  What is the output of `netstat -antup | grep 'ShooterGame'`

**Comment by boistordu** [comment]
I don't know what setting it is sorry :( but I guess not
it's a docker version, the one from turzam.
the result of your command is nothing. 
```
root@ea35a94a08b4:/ark# netstat -antup | grep 'ShooterGame'                 
root@ea35a94a08b4:/ark# 
```

**Comment by klightspeed** [comment]
The fact that the above command returned nothing means that the server itself is no longer listening, and has either crashed or hung.

You will need to restart the game server using `arkmanager restart`.

Is it the address on the server itself that changes, or the public address on your router?  If it's the address on your server, then it's possible that Wildcard's ARK Survival Evolved server does not gracefully handle interfaces going up and down, or having the IP address on an interface changed.

**Comment by boistordu** [comment]
public adress of the router actually. it s in lan with a port for the oustide world.

**Comment by boistordu** [comment]
So do you think more about a crash of arkitself? or is it related to your tools?

**Comment by klightspeed** [comment]
The `Server running: Yes` means that the ARK game server executable is running.

The `Listening: No` means that the ARK game server executable is not listening on its game port.

The lack of any output from `netstat -antup | grep 'ShooterGame'` suggests that the ARK game server is not listening on any ports, which is not normal.

What are the contents of `/var/log/arktools/arkserver.log`?

What is the output of `arkmanager --version`?

What is the output of `ps -AHF x | grep -B1 'Shooter[G]ame'`

**Comment by boistordu** [comment]
```
2016-09-18 13:24:17: start
2016-09-18 13:24:17: Running /ark/server/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?MaxPlayers=5\?Port=45110\?QueryPort=45112\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=PqWm8a4\?\?ServerPassword\?SessionName=Barricade\?listen -log
2016-09-18 13:24:17: Server PID: 260
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
2016-09-18 13:27:01: server is up
2016-09-21 08:04:54: start
2016-09-21 08:04:54: Running /ark/server/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?MaxPlayers=5\?Port=45110\?QueryPort=45112\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=PqWm8a4\?\?ServerPassword\?SessionName=Barricade\?listen -log
2016-09-21 08:04:54: Server PID: 650
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
2016-09-21 08:07:27: server is up
Using binned.
4.5.1-0+UE4 7038 3077 402 6
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3004) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3004) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3155) : Assertion Failed: m_vecInstallBaseFolders.Count() > 0
CtrlCHandler: Signal=2
/usr/local/bin/arkmanager: line 882:   650 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
2016-09-21 23:02:43: start
2016-09-21 23:02:43: Running /ark/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?MaxPlayers\?Port=-1\?QueryPort\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword\?ServerPassword\?SessionName\?listen -log
2016-09-21 23:02:43: Server PID: 5940
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
2016-09-21 23:05:21: server is up
```
```

root@ea35a94a08b4:/var/log/arktools# arkmanager --version
Version: 1.6-pre3
Channel: master

```
```

root@ea35a94a08b4:/ark/log# ps -AHF x | grep -B2 'Shooter[G]ame'
steam      647    12  0  4503     4   6 Sep21 ?        S      0:00       bash /home/steam/run.sh
steam     5922     1  0  2802  2304   2 01:02 ?        S      0:03   /bin/bash /usr/bin/arkmanager update --warn --update-mods
steam     5940  5922  6 1378575 4284748 1 01:02 ?      Sl    70:44     /ark/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?MaxPlayers?Port=-1?QueryPort?RCONEnabled=True?RCONPort=32330?ServerAdminPassword?ServerPassword?SessionName?listen -log
```
I don't know if any of that help...?

**Comment by boistordu** [comment]
I have restart the docker container so the ark server. It seems that it missed a lot of update because now it's in 247. Maybe it's because of that... Do you use steam id?

**Comment by klightspeed** [comment]
The log says that it had crashed and restarted, and the last status was that it was up.

The arkmanager version is not the latest.  Please try updating arkmanager.

The "Server version" at the bottom of the version output is from a `version.txt` file that Wildcard had added but had then removed.  See your other ticket, and remove the `version.txt` as I instructed there.

The "Server build" in your status output above was 1347876, which is the latest version according to https://steamdb.info/app/376030/history/

**Comment by boistordu** [comment]
done it in server/version.txt and staging/version.txt 
I will se if it creates it.
is there soimewhere a log where I coudl see why it has crashed? You didn't answer me about if it has any the steamId api failing is important or not?

**Comment by boistordu** [comment]
it still crashing by the way

**Comment by klightspeed** [comment]
```
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
```
This is normal - `ShooterGameGerver` will always output this when starting up.

```
CtrlCHandler: Signal=2
```
This means that it was stopped by e.g. an update or `arkmanager stop`

All we have at our disposal is the output of `ShooterGameServer`, which is logged to `/var/log/arktools/arkserver.log` (or the SystemD journal if running under the SystemD service).

**Comment by boistordu** [comment]
So in other words, I can't debug it right?

**Comment by boistordu** [comment]
again don't know why it doesn't listen anymore since 1.00 AM. 

```
root@a4a578ee0fee:/ark/log# ps -AHF x | grep -B2 'Shooter[G]ame'
steam      185    12  0  4501     4   6 Sep28 ?        S      0:00       bash /home/steam/run.sh
steam    32041     1  0  2816  2332   3 01:01 ?        S      0:01   /bin/bash /usr/bin/arkmanager update --warn --update-mods
steam    32059 32041  7 1273228 4230244 7 01:01 ?      Sl    38:38     /ark/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?Port=-1?QueryPort?RCONEnabled=True?RCONPort=32330?MaxPlayers?ServerAdminPassword?ServerPassword?SessionName?listen -log
```

```
```
root@a4a578ee0fee:/ark/log#   netstat -antup | grep 'ShooterGame'
root@a4a578ee0fee:/ark/log# arkmanager --version
Version: 1.6
Channel: master
Commit: 0a02cc2
Release Tag: v1.6.03
Blob SHA: 9a322896756f522a84997fe882bb8c0470cbedd2
```
2016-09-28 10:46:05: Server PID: 209
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
2016-09-28 10:48:27: server is up
2016-09-28 10:52:28: start
2016-09-28 10:52:28: Running /ark/server/ShooterGame/Binaries/Linux/ShooterGameServer TheCenter\?MaxPlayers=5\?Port=45110\?QueryPort=45112\?RCONEnabled=True\?RCONPort=32330\?ServerAdminPassword=PqWm8a4\?ServerPassword\?SessionName=barricade\?listen -log
2016-09-28 10:52:28: Server PID: 194
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
2016-09-28 10:53:47: server is up
Using binned.
4.5.1-0+UE4 7038 3077 402 6
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3004) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3004) : Assertion Failed: CApplicationManager::GetMountVolume: invalid index
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/clientdll/applicationmanager.cpp (3155) : Assertion Failed: m_vecInstallBaseFolders.Count() > 0
CtrlCHandler: Signal=2
/usr/local/bin/arkmanager: line 894:   194 Aborted                 (core dumped) "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
2016-09-29 01:01:41: start
2016-09-29 01:01:41: Running /ark/server/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?Port=-1\?QueryPort\?RCONEnabled=True\?RCONPort=32330\?MaxPlayers\?ServerAdminPassword\?ServerPassword\?SessionName\?listen -log
2016-09-29 01:01:41: Server PID: 32059
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
2016-09-29 01:04:34: server is up
root@a4a578ee0fee:/ark/log#   netstat -antup | grep 'ShooterGame'
```
should I ask ark dev on their community forums?

**Comment by klightspeed** [comment]
b6c41ca will now restart the server if it stops listening for more than 60 seconds after going online.

**Comment by boistordu** [comment]
thanks seems working or maybe it's because I have change to ZFS:)
