### ISSUE TITLE
unexpected server restart with active players on update

### ISSUE THREAD

**Issue by kdulep** [FezVrasta/ark-server-tools#612]
CentOS7
*/30 *  * * *   root    /usr/local/bin/arkmanager update --update-mods --warn --safe

unexpected restart server on update with active players possibly player death

**Comment by klightspeed** [comment]
What was the output of the update command?

If you have not set up cron to send you emails, then this email will likely be in either `~/dead.letter`, `/var/mail/steam` (assuming you're running under a user named `steam`) or `/var/mail/root`

**Comment by kdulep** [comment]
nothing special its just stop server without warning

**Comment by klightspeed** [comment]
Try removing the `--safe` command-line argument.  It conflicts with the `--warn` command-line argument.

**Comment by kdulep** [comment]
thanks will try it, probably options wanst clean for me
