### ISSUE TITLE
Questions about ark-server-tools

### ISSUE THREAD

**Issue by KGM6911** [FezVrasta/ark-server-tools#614]
Looking for info on the following:

Other than taking up more space on a drive or having to update multiple instances individually is there any reason that I shouldn't run my servers in different directories?  

If I were to run them all out of one directory and share the same executables, will stopping one server stop all of them?

If I want to setup servers on a cluster, is there a better way than the following:   Setup an instance for each server in it's own directory by modifying arkserverroot path.  The insance directories will all reside in the /home directory.   Setup a symbolic link inside each of these for the cluster to point to an additional directory inside /home.

Thanks!

**Comment by klightspeed** [comment]
If you run them all out of the same directory, then they must all have the same cluster ID.

If the servers do not have the same cluster ID, or the `arkopt_clusterid` setting is not set, then the servers must run from different directories.

Server instances start and stop independently.  Stopping one instance in a cluster does not stop all of them.

**Comment by KGM6911** [comment]
Thanks!   Tonight I set it up in different directories and used symbolic links for the cluster.  Seems to be working great.  Thanks!
