### ISSUE TITLE
Server Crashes, perl mismatch?

### ISSUE THREAD

**Issue by Mentaleak** [FezVrasta/ark-server-tools#616]
I began with a fresh install of the Ark  Server Tools on CentOS and I immediately made a new instance config for the instance I wanted to run.

However when I ran the start command the first time I was met with errors, that may be a perl mismatch error but i'm not certain as I don't work with perl much.

So I started trying to figure out why it wasn't listening and a while later I decided to comment out the modID line in the instance config and everything worked.

Can someone guide me towards how to fix this problem. The Mod is ACM so I doubt there is a problem with it I have it running on other servers fine and given its popularity I suspect its not the mod.

As a side note if I wait a while the status goes from not listening to not running, so I assume it crashes.

**Comment by Mentaleak** [comment]
# **Initial run of the start command**

`
[root@ARK02 steam]# arkmanager start @wrath-01-pvp-vanilla --verbose
Running command 'start' for instance 'wrath-01-pvp-vanilla'
[  ERROR  ]     Mod 558079412 is requested but not installed.  Run 'arkmanager installmod 558079412' to install this mod.
Updating server
2016-09-25 12:06:35: checking for update; PID: 24004
Downloading mod 558079412Executing /home/steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +workshop_download_item 346110 558079412 +quit
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for license info...OK
Downloading item 558079412 ...
Success. Downloaded item 558079412 to "/home/steam/steamcmd/steamapps/workshop/content/346110/558079412" (4529185 bytes) Mod 558079412 downloaded
The server is already stopped
 Copying ARK world file                                            [   OK   ]
 Copying ARK profile files
   *.arkprofile cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved/wrath-01-pvp-vanilla/*.arkprofile’: No such file or directory
cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved/wrath-01-pvp-vanilla/*.arkprofile’: No such file or directory
cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved/wrath-01-pvp-vanilla/*.tmpprofile’: No such file or directory
                                                                   [ FAILED ]
 Copying ARK tribe files
   *.arktribe cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved/wrath-01-pvp-vanilla/*.arktribe’: No such file or directory
cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved/wrath-01-pvp-vanilla/*.arktribe’: No such file or directory
cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved/wrath-01-pvp-vanilla/*.tmptribe’: No such file or directory
                                                                   [ FAILED ]
 Copying ARK tribute tribe files
   *.arktributetribe cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved//home/steam/ARK/ShooterGame/Saved/wrath-01-pvp-vanilla/*.arktributetribe’: No such file or directory
cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved//home/steam/ARK/ShooterGame/Saved/wrath-01-pvp-vanilla/*.arktributetribe’: No such file or directory
cp: cannot stat ‘/home/steam/ARK/ShooterGame/Saved//home/steam/ARK/ShooterGame/Saved/wrath-01-pvp-vanilla/*.arktributetribe.tmptributetribe’: No such file or directory
                                                                   [ FAILED ]
 Copying GameUserSettings.ini                                      [   OK   ]
 Copying Game.ini                                                  [   OK   ]
 Compressing Backup tar (child): bzip2: Cannot exec: Permission denied
tar (child): Error is not recoverable: exiting now
                                                                   [   OK   ]
 Created Backup:  2016-09-25_12.07.44.tar.bz2
Updating mod 558079412
Copying files to /home/steam/ARK/ShooterGame/Content/Mods/558079412
     33892  Blueprints/Core/ACM_DS_BP.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      1423  Blueprints/Core/PrimalItemStructure_ACM_DS.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     56206  Blueprints/Core/Buff_ACM.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     14171  Blueprints/EngramModification/Buff_ACM_GiveEngrams.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
       644  Blueprints/ACMMacros.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      7122  Blueprints/ACMFunctions.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      7937  Materials/Buff_Outline.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     36182  Materials/BKG_Wave.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     36044  Materials/BKG_UI_Overlay.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
    204220  Materials/DS_Dis_Mat_Base.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      8652  Materials/Buff_Outline_Fill.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     25160  PrimalEarth/CoreBlueprints/Items/Armor/Icons/ARKDevKitMasterHat_Icon.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     24415  PrimalEarth/CoreBlueprints/Resources/Icons/Dye_Icon.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
       687  PrimalEarth/Items/DinoEgg/HUD_DinoEgg_MIC_Inst_Arthro.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     20422  PrimalEarth/Test_Craig/TempSummon_Icon.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      1499  Structs/PlayerUIStruct.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
       984  Structs/EACMConfirmation.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      1552  Structs/PlayerInfoStruct.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
       910  Structs/SpawnStruct.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      1058  Structs/StorageStruct.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
       938  Structs/TCStruct.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
       469  Structs/GameWorldSettings.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
       577  Structs/PlayerBookmark.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
       781  Structs/ServerTribeInfo.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      2499  Widgets/Textures/Import_Warn_T.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
    240608  Widgets/Textures/ACM_Valhalla_Map.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      1291  Widgets/Textures/ACM_Close_T.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
       690  Widgets/Textures/ACM_Crosshair_T.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      2370  Widgets/Textures/Import_Comp_T.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     80726  Widgets/Textures/DistortedCloudNoise1.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
    262476  Widgets/Textures/ACM_IslandMap.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      4610  Widgets/Textures/ACM_DefaultIcon_T.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
    235843  Widgets/Textures/ACM_CenterMap.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     23509  Widgets/Textures/ACM_DS_Icon.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
       702  Widgets/Textures/ACM_PlayerPin.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      2453  Widgets/Textures/Import_Err_T.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
    257364  Widgets/Textures/ACM_Scorched_Map.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      7839  Widgets/ACM_Buttons.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      3447  Widgets/ACM_ChatMessage.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     10462  Widgets/ACM_ConfirmationBox.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
    233877  Widgets/ACM_SuperUI.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     11524  Widgets/ACM_AdminChat.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      4676  Widgets/ACM_Btn_Player.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      2773  Widgets/ACM_MapPin.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     48786  Widgets/ACM_TC_StatMod.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      1548  Widgets/ACM_Status.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      4109  Widgets/ACM_Engram.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
     19344  Widgets/ACM_Overlay.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      2247  Widgets/ServerInfoWidget.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      1335  ACM.umap  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      3078  PrimalGameData_BP_ACM.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
The server is starting...
The server is now running, and should be up within 10 minutes
[root@ARK02 steam]#  Can't locate Compress/Raw/Zlib.pm^C
[root@ARK02 steam]# arkmanager status
Running command 'status' for instance 'main'
 Server running:   Yes
 Server listening:   No
 Server build ID:   1354299
 Server version:   245.99
`



# ** Instance Config**





`
# config environment
arkserverroot="/home/steam/ARK"                                     # path of your ARK server files (default ~/ARK)

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file


serverMap="TheIsland"                                               # server map (default TheIsland)
#serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)


#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod


ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort="32330"                                                # RCON Port
ark_SessionName="Wrath-01 PVP Vanilla B"                                  # if your session name needs special characters please use the .ini instead
ark_Port="7778"                                                     # ARK server port (default 7778)
ark_QueryPort="27015"                                               # ARK query port (default 27015)
ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
ark_ServerAdminPassword="XXXXX"                                # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="70"
ark_GameModIds="558079412"                    			   # Uncomment to specify additional mods by Mod Id separated by commas
ark_AltSaveDirectoryName="wrath-01-pvp-vanilla"                    # Uncomment to specify a different save directory name
ark_HarvestAmountMultiplier=2.00000
ark_DifficultyOffset=1.00000
ark_Banlist="http://playark.com/banlist.txt"
ark_TamingSpeedMultiplier=3.00000
ark_EggHatchSpeedMultiplier=2.00000
ark_BabyMatureSpeedMultiplier=2.00000

# ARK server flags - use arkflag_<optionname>=true
arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
arkflag_NoTransferFromFiltering=""

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures
arkopt_clusterid="CIDWRATH01CID"

**Comment by klightspeed** [comment]
Please try installing perl-Compress-Zlib and try again.

**Comment by Mentaleak** [comment]
Thanks!
 I was wondering if it was a missing package but of the dozen packages I came across that wasn't one of the ones.

 That solved my Perl issues.
