### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by axi92** [FezVrasta/ark-server-tools#620]
I run this as root:
curl -sL http://git.io/vtf5N | bash -s arkserver

Then with the user arkserver this:
arkmanager install

And get this:
```
[  ERROR  ]     Your SteamCMD root seems not valid.
[  ERROR  ]     Your SteamCMD exec could not be found.
Running command 'install' for instance 'main'
[  ERROR  ]     Your SteamCMD root seems not valid.
[  ERROR  ]     Your SteamCMD exec could not be found.
[  WARN  ]      Your ARK server exec could not be found.
mkdir: cannot create directory ‘/home/steam’: Permission denied
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
Creating the ARK server root directory (/home/steam/ARK)
mkdir: cannot create directory ‘/home/steam’: Permission denied
/usr/local/bin/arkmanager: line 1130: cd: /home/arkserver/steamcmd: No such file or directory
Installing ARK server ... -/usr/local/bin/arkmanager: line 440: /home/arkserver/steamcmd/steamcmd.sh: No such file or directory  
```

There are just 2 lines, and i did it although wrong?

**Comment by KGM6911** [comment]
When I did mine, I left it with steam as the username.  I also installed the steam stuff in the steam users acct.  I'm guessing you have a different account for steam.  I would think you could just install steamcmd in the arkserver users folder if you want.  I followed the steam guide found at:  https://developer.valvesoftware.com/wiki/SteamCMD#Linux   I found it easy to leave it all as the same account.  I am no expert with this stuff.  I'm brand new with this.  Good luck!

**Comment by klightspeed** [comment]
It sounds like you first ran it using `steam` as the user argument, and then with `arkserver` as the user argument.  Either that, or the install script somehow failed to modify the config.

Please open `/etc/arkmanager/arkmanager.cfg` with a text editor, and change the following settings:

* Change `steamcmd_user` from `steam` to `arkserver`
* Change `arkserverroot` from `/home/steam/ARK` to `/home/arkserver/ARK`
* Change `steamcmdroot` from `/home/steam/steamcmd` to `/home/arkserver/steamcmd`
* Change `steamcmd_appinfocache` from `/home/steam/Steam/appcache/appinfo.vdf` to `/home/arkserver/Steam/appcache/appinfo.vdf`

**Comment by axi92** [comment]
I missed the steamcmd install thought it would do that too xD

**Comment by klightspeed** [comment]
v1.6.04 will now install steamcmd if it's not already installed (and if the `steamcmdroot` setting is set correctly).
