### ISSUE TITLE
use of environment variables

### ISSUE THREAD

**Issue by boistordu** [FezVrasta/ark-server-tools#621]
Is it possible to use environment variables for the arkmanager.cfg? 

```
root@cf7bbf8f8224:/ark# arkmanager upgrade-tools
arkmanager v1.6: Checking for updates...
Channel '${BRANCH}' does not exist

Available channels:
api
fix-323
master
1.2-dev
1.3-dev
1.4-dev
1.5-dev
1.6-dev-rc
1.6-dev.unstable
1.6-dev

root@cf7bbf8f8224:/ark# printenv
UPDATEONSTART=1
HOSTNAME=cf7bbf8f8224
BACKUPONSTOP=0
SERVERPASSWORD=
BRANCH=master
STEAMPORT=45111
LS_COLORS=
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
BACKUPONSTART=1
GID=1000
PWD=/ark
WARNMINUTE=30
SHLVL=1
HOME=/root
AUTOBACKUP=60
AUTOUPDATE=120
UID=1000
LESSOPEN=| /usr/bin/lesspipe %s
WARNONSTOP=30
SERVERMAP=TheCenter
SERVERPORT=45112
LESSCLOSE=/usr/bin/lesspipe %s %s
SESSIONNAME=barricade
NBPLAYERS=5
```

**Comment by klightspeed** [comment]
With the latest commits, you now have two options:

* Run as `arkmanager upgrade-tools` as an unprivileged user, and it will use `sudo` to perform the upgrade (and will use the config variables sourced by the script, which will be processed by bash)
* Modify `arkmanager` and change `arkstRootUseEnv=''` to `arkstRootUseEnv='yes'` - this will cause simple environment substitutions to be done.

**Comment by boistordu** [comment]
Sorry I don't see the line you are talking about. in which arkmanager? /etc/arkmanager/arkmanager.conf or /ark/arkmanager.conf or /home/steam/arkmanager.cfg ?

Sorry I don't use the environment variables very often so I'm certainly not an expert with that. Idon't really understand the process here, since this is envrionment variables and not specific to root so I can use them for the user steam for example it will display the same thing:

```
steam@cf7bbf8f8224:~$ env                 
UPDATEONSTART=1
HOSTNAME=cf7bbf8f8224
BACKUPONSTOP=0
SHELL=/bin/bash
SERVERPASSWORD=
BRANCH=master
USER=steam
STEAMPORT=45111
LS_COLORS=
ADMINPASSWORD=PqWm8a4
MAIL=/var/mail/steam
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
BACKUPONSTART=1
GID=1000
PWD=/home/steam
WARNMINUTE=30
HOME=/home/steam
SHLVL=2
AUTOBACKUP=60
AUTOUPDATE=120
LOGNAME=steam
UID=1000
WARNONSTOP=30
LESSOPEN=| /usr/bin/lesspipe %s
SERVERMAP=TheCenter
SERVERPORT=45112
SESSIONNAME=barricade
LESSCLOSE=/usr/bin/lesspipe %s %s
NBPLAYERS=5
_=/usr/bin/env
OLDPWD=/etc/arkmanager/instances
```

If you have some ressources I will be interested... For me it's give me the impression to a syntax problem on my part.... like the system undertsand your line of code as echo `"Channel ${${BRANCH}} does not exist"` and not as `echo "Channel ${master} does not exist"` Anyway any explanation when you have the time would be great .

**Comment by klightspeed** [comment]
What does running `arkmanager upgrade-tools` give you when running as `steam`?

> Sorry I don't see the line you are talking about. in which arkmanager? /etc/arkmanager/arkmanager.conf or /ark/arkmanager.conf or /home/steam/arkmanager.cfg ?

Edit line 14 of `/usr/local/bin/arkmanager` (or wherever you've installed the `arkmanager` executable)

https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L14

**Comment by boistordu** [comment]
your line is nowhere: 
```
#!/bin/bash

# ARK: survival evolved manager
#
# Original author:      LeXaT
# Maintainer:           FezVrasta
# Contributors:         Sispheor, Atriusftw, klightspeed, lexat, puseidr

# Script version
arkstVersion='1.6'
arkstTag='v1.6.02'
arkstCommit='2f1d3cabe5642eeb956be2091f3228ef2e3df7b0'
arkstGithubRepo="FezVrasta/ark-server-tools"

doUpgradeTools() {
  local sudo=sudo
  if [ "$UID" == 0 -o "$steamcmd_user" == "--me" ]; then
    sudo=
  fi

  local reinstall_args=()
  if [ -n "$install_bindir" ]; then
    reinstall_args=( "${reinstall_args[@]}" "--bindir" "$install_bindir" )
  fi
  if [ -n "$install_libexecdir" ]; then
    reinstall_args=( "${reinstall_args[@]}" "--libexecdir" "$install_libexecdir" )
  fi
  if [ -n "$install_datadir" ]; then
    reinstall_args=( "${reinstall_args[@]}" "--datadir" "$install_datadir" )
  fi

  echo "arkmanager v${arkstVersion}: Checking for updates..."

  if [ -n "$arkstUnstable" ] || [ "$arkstChannel" != "master" ]; then
    doUpgradeToolsFromBranch
  else
    doUpgradeToolsFromRelease
  fi
}
```
and /arkstRootUseEnv doesn't find anything so I guess you want me to add the line more than modifying it, right? sorry to ask maybe it's dumb but I prefer to be sure.

with the user steam (without the modification) seems to follow the good syntax and respond well to the command upgrade-tools. I will try to recreate the initial condition just to be sure.

**Comment by klightspeed** [comment]
Upgrade to v1.6.03

**Comment by boistordu** [comment]
docker rebuild.
first confirmation: the syntax with root doesn't recognize ${BRANCH} 
but the user steam does.

**Comment by klightspeed** [comment]
What is the output of `head -n20 '/usr/local/bin/arkmanager'`

What is the output of `arkmanager --version`

**Comment by boistordu** [comment]
don't worry the version is good and the content of the file too. I'm going to change the var...

Ok does the trick seems to, the command works for root and for steam now. 

So can you explain rapidly or maybe a ressource that I could read on it? because basically if I understand correctly it's sort of an interpretation of syntax, no?
