### ISSUE TITLE
Automatic updates help

### ISSUE THREAD

**Issue by KGM6911** [FezVrasta/ark-server-tools#626]
I apologize for starting a new thread about something that so many have done before but I have read all the issues and I'm really quite lost.  

I run 3 servers on one machine and I want them to check for updates every half hour.  I tried this at command line:

arkmanager install-cronjob @island-pve --minute='*/30' update --saveworld --backup --warn --update-mods

Here's the response I get:
Running command 'install-cronjob' for instance 'island-pve'

When I type crontab -e I don't see anything listed there. 

I tried another one on a different instance:
arkmanager install-cronjob @scorched-pve --minute='*/2' broadcast"TEST"

I logged into the server and I get no broadcasts.  

Can anyone tell me what i'm doing wrong?
Thanks

**Comment by klightspeed** [comment]
Are you running `crontab -e` as the user under which you run the ARK server?

With the second cronjob, you need to use `--arg="TEST"` to pass the `"TEST"` argument to `broadcast`.

**Comment by KGM6911** [comment]
Thank you!  Working great now!  Appreciate your help!

**Comment by KGM6911** [comment]
Ok,  so what you wrote did make it so my broadcasts work but the auto backup still won't go.   Here's what's in my crontab -e for the user that runs the servers.  

*/30 * * * * /usr/local/bin/arkmanager --cronjob update @scorched-pvp  --saveworld --backup --warn --update-mods --args  -- >/dev/null 2>&1
*/30 * * * * /usr/local/bin/arkmanager --cronjob update @center-pvp  --saveworld --backup --warn --update-mods --args  -- >/dev/null 2>&1
*/30 * * * * /usr/local/bin/arkmanager --cronjob update @island-pvp  --saveworld --backup --warn --update-mods --args  -- >/dev/null 2>&1

Any ideas why this isn't working?
Thanks again!

**Comment by klightspeed** [comment]
Does `arkmanager update @scorched-pvp --saveworld --backup --warn --update-mods` work?

Are the instances in separate directories, or do they all share the same directory?

**Comment by KGM6911** [comment]
Yes, that works fine at command line.  And they are all in different directories.

**Comment by KGM6911** [comment]
I just ran it again to test and it's saying:

Your server is already up to date! The most recent version is 1366578.

But when I look at the server version it's not.    I have two dedicated servers.  One with PVE servers and one with PVP servers.  The PVE ones show 247.91.   The PVP ones are showing 247.9.   The ones at 247.9 are the ones that are saying that server is up to date.

**Comment by klightspeed** [comment]
That sounds like Steam is applying too much caching again - 1366578 was released on 30th September, and 1368348 (the latest buildid at the moment) was released on 1st October

Does `~/Steam/appcache/appinfo.vdf` exist?  If not, does `~/.local/share/Steam/appcache/appinfo.vdf` exist?

If neither of those exist, are you able to `find -name appinfo.vdf` anywhere in your game server user's home directory?

If `appinfo.vdf` is not in `~/Steam/appcache`, then you will need to update the `steamcmd_appinfocache` setting to point at the absolute path to `appcache/appinfo.vdf`.

**Comment by KGM6911** [comment]
That did it.  Everything else had Steam with a lower case s but the steamcmd_appinfocache was pointed to Steam with upper case.  I changed it and now it's good.   I'm guessing the auto update will start to work now.
I'll know soon and I'll close the ticket if it does.  Thanks again for all the help!

**Comment by KGM6911** [comment]
Ok, so I tested it out on my PVE servers by just doing an update to a UI mod that I have for my server and the server auto updated.   I'm sure the PVP servers will work once there is an update for them.  Thank you klightspeed!   I appreciate your patience with my lack of knowledge!
