### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by badboysgaming** [FezVrasta/ark-server-tools#628]
with out a bunch of editing?

**Comment by klightspeed** [comment]
Please elaborate.

**Comment by badboysgaming** [comment]
well see new release is out but i'm truly confused i understand we can use same ark dir for each but what about different gameusersettings and game.ini for each session lets say i want a pvp server on scorched but on mortem tupiu i want to run pve with different rates are we able to do that really not sure how to do this to start with

**Comment by klightspeed** [comment]
Sharing a single directory is only possible when the servers are in the same cluster.  All servers in the cluster must have the same settings, and should only differ by what map they're running and the `AltSaveDirectoryName` setting.

If the servers need to have different settings, then they need to run from separate directories.

**Comment by badboysgaming** [comment]
so you cant do cross realm travel without it?

**Comment by badboysgaming** [comment]
so how can i install second copy of ark server with arkmanager?

**Comment by klightspeed** [comment]
Copy `/etc/arkmanager/instances/main.cfg` to another named `cfg` file in `/etc/arkmanager/instances`.

Edit that new config file and change the `arkserverroot` setting to point to a separate directory (and change any other settings you want to change), and then run `arkmanager install @instancename` where `instancename` is the name you game your config file without the `.cfg` extension.

**Comment by badboysgaming** [comment]
awesome thanks before was downloading ark and then renaming it to download another copy this much simpler

**Comment by badboysgaming** [comment]
quick question each server if i ran clustered be reading its own cfg file correct? so i can have different mods running on other server
