### ISSUE TITLE
cluster info

### ISSUE THREAD

**Issue by Flukethoughts** [FezVrasta/ark-server-tools#631]
v247.85
* Fixed issue where player collision could get stuck on pipes/cables. Requires Server Update.
* Added "-ClusterDirOverride=C:/TestStorage/" launch parameter to servers (use whatever path you want). This allows you to use a common cross-server storage location that functions between multiple servers running on the same machine. (And you also still need to launch with "-ClusterId=SOMETHINGUNIQUE" in order to get your box's servers to allow cross-transfer.)

**Comment by badboysgaming** [comment]
i notice during character transfer to other server you can carry everything you had on you
