### ISSUE TITLE
settings issue please help asap

### ISSUE THREAD

**Issue by Flukethoughts** [FezVrasta/ark-server-tools#634]
my config I generated
```
[ServerSettings]
PreventDownloadSurvivors=False
PreventDownloadItems=False
PreventDownloadDinos=False
PreventUploadSurvivors=False
PreventUploadItems=False
PreventUploadDinos=False
noTributeDownloads=false
allowThirdPersonPlayer=1
AllowCaveBuildingPvE=1
alwaysNotifyPlayerJoined=1
alwaysNotifyPlayerLeft=1
bAllowFlyerCarryPvE=1
bDisableStructureDecayPvE=0
DayCycleSpeedScale=1.00000
DayTimeSpeedScale=1.00000
NightTimeSpeedScale=1.00000
DinoCharacterFoodDrainMultiplier=1.00000
DinoCharacterHealthRecoveryMultiplier=1.00000
DinoCharacterStaminaDrainMultiplier=1.00000
DinoCountMultiplier=1.00000
DinoDamageMultiplier=1.00000
DinoResistanceMultiplier=1.00000
globalVoiceChat=0
HarvestAmountMultiplier=6.00000
HarvestHealthMultiplier=2.00000
MaxStructuresInRange=6700
noTributeDownloads=0
PreventDownloadSurvivors=0
PreventDownloadItems=0
PreventDownloadDinos=0
PlayerCharacterFoodDrainMultiplier=1.00000
PlayerCharacterHealthRecoveryMultiplier=1.00000
PlayerCharacterStaminaDrainMultiplier=1.00000
PlayerCharacterWaterDrainMultiplier=1.00000
PlayerDamageMultiplier=3.00000
PlayerResistanceMultiplier=0.50000
proximityChat=0
ResourceNoReplenishRadiusPlayers=1.00000
ResourceNoReplenishRadiusStructures=1.00000
ResourcesRespawnPeriodMultiplier=1.00000
ServerCrosshair=1
serverForceNoHud=0
serverHardcore=0
ServerPassword=
serverPVE=0
ShowMapPlayerLocation=1
StructureDamageMultiplier=1.00000
StructureResistanceMultiplier=0.50000
TamedDinoDamageMultiplier=1.00000
TamedDinoResistanceMultiplier=1.00000
TamingSpeedMultiplier=15.00000
XPMultiplier=10.00000
EnablePVPGamma=0
EnablePVEGamma=0
SpectatorPassword=
DifficultyOffset=1.00000
PvEStructureDecayPeriodMultiplier=1.00000
PvEStructureDecayDestructionPeriod=1.00000
Banlist="http://playark.com/banlist.txt"
PvPStructureDecay=0
DisableDinoDecayPvE=0
PvEDinoDecayPeriodMultiplier=1.00000
AdminLogging=0
MaxTamedDinos=8000
MaxNumbersofPlayersInTribe=25
BattleNumOfTribestoStartGame=2
TimeToCollapseROD=100
BattleAutoStartGameInterval=100
BattleSuddenDeathInterval=300
KickIdlePlayersPeriod=1800
PerPlatformMaxStructuresMultiplier=1.00000
StructureDamageRepairCooldown=180
bForceAllStructureLocking=1
AutoDestroyOldStructuresMultiplier=0.00000
bUseVSync=0
MaxPlatformSaddleStructureLimit=100
bPassiveDefensesDamageRiderlessDinos=1
RCONPort=32330
AutoSavePeriodMinutes=15
RCONServerGameLogBuffer=600
OverrideStructurePlatformPrevention=1
bPreventOfflinePvP=0
PreventOfflinePvPInterval=60.0
bPvPDinoDecay=1
bPvPStructureDecay=1
NewMaxStructuresInRange=6700
DisableImprintDinoBuff=1
AllowAnyoneBabyImprintCuddle=1
EnableExtraStructurePreventionVolumes=1
ShowFloatingDamageText=1
TribeLogDestroyedEnemyStructures=1
AllowHitMarkers=True
ActiveMods=538986229,516096294,554678442,558651608,561820195,566887000,567659264,569786012,575017270,600015460,622595587,622608522,630601751,633831197,655261420,656489100,681259857,658667129,689838254,693416678,698238991,707081776,729352919,725398419,730794403,731604991,747539326,748358288,749145707,751991809,754885087,758608778

[SnappySaddles]
AdditionalBuildDistance=25
AdditionalHeight=25
AdditionalStructures=25

[TTArmor]
FunJump=True
FlyControl=True
JumpDisabled=False
AdminOnlyJump=False
MegaJumpOn=True
AdminOnlyMega=False
FlameThrowerOn=True
AdminOnlyFlame=False
AdminFlame=False
WeightBoost=500
StaminaBoost=250
FlightEnabled=True
AdminFlightOnly=False
DontUseFuel=False
LessDamage=True
GigaLaserDMG=55000
GLNoDMGMetal=False

[WeaponDamage]
BarrettDirDamage=300
BarrettExpDamage=2500
ArrowDirDamage=150
ArrowExpDamage=1000
NormalBarrett=1000
ScopedLongneckDamage=380
ScopedSniperDamage=400
ScopedPistolDamage=150
ScopedRevolverDamage=100
ScopedMaschineGunDamage=150
ScopedShotgunDamage=100

[TranqDartsConfig]
RifleDartMultiplitier=5
PistolDartMultiplitier=5
SniperDartMultiplitier=5
BarrettDartMultiplitier=5

[PoisonDamage]
PoisenArrow=20
BarrettPoisonDamage=50

[JoanOil]
OilAmount=80

[JoanGodMod]
NumWildGodling=15
NumWildElder=5
NumWildPuppet=20
NumWildElderPuppet=10
NumWildPuppetMaster=2
NoDragoGodling=false
NoBlackHeartGodling=false
NoPuppet=false
NoGoddess=false
RespawnTime=300.0
NoTameGodlings=false
NoWildAggro=false
NoWildAggroP=false
NoMidasMsg=true
MidasNerf=0.3
MidasDupe=1.5
AllowFireGodBoss=true
AllowDarkGodBoss=true

[JoanIndomMod]
IndomCount=-1
IndomHCount=5
NoWildAggro=false
OrcCount=1
OrcHCount=10

[JoanPetFind]
BedPreventRange=100000.0

[JoanCollector]
MaxPoopStacks=30
CollectInterval=33.0
IncubateDistance=5500.0
IncubateBoostMultiplier=250.5
BlockAutoCompostBins=false
CollectDistance=15000.0
SiloDistance=15000.0

[JoanPhoton]
BaseDamage=600.0
DamageMultiplier=3.0
BonusTierDamage=7
FireInterval=4.0
DisableTribeAlert=False
BlockPlatformBuild=False
RifleTorpMultiplier=55.0
ShieldPlayers=False

[JoanBulk]
TroughRange=100000000
NoFeedingIcon=False

[JoanScorchMod]
NumDino=400
NumFlyer=150
NumBig=50
NumWorm=50
NumWyvern=30
NumBoss=5
EggRarity=6
NoManticore=false

[JoanSpoiler]
DisableMusic=False

[StructuresPlus]
EnableQuickClimb=false
NoFoundationsRequired=false
ElevatorWeightMultiplier=30
DisablePickup=false
DisablePickupWhenDamaged=false
DisableResourcePulling=false
ResourcePullRangeInFoundations=10
DisableAbilityToHideStructures=false

[SessionSettings]
SessionName=Moddedark.com The Center

[MessageOfTheDay]
Message=Invite your friends When the server grows you grow
Duration=5

[/Game/Mods/Genesis/TestGameMode_Genesis.TestGameMode_Genesis_C]
OverrideMaxExperiencePointsPlayer=1000000000
OverrideMaxExperiencePointsDino=1000000000

[/Script/Engine.GameSession]
MaxPlayers=200
```

It removes this and does this
```
[ServerSettings]
ServerCrosshair=True
ServerPassword=
ServerAdminPassword=deleted
RCONEnabled=True
RCONPort=32330
StructurePreventResourceRadiusMultiplier=1.000000
RaidDinoCharacterFoodDrainMultiplier=1.000000
PvEDinoDecayPeriodMultiplier=1.000000
KickIdlePlayersPeriod=3600.000000
PerPlatformMaxStructuresMultiplier=1.000000
AutoSavePeriodMinutes=15.000000
ListenServerTetherDistanceMultiplier=1.000000
MaxTamedDinos=5000.000000
RCONServerGameLogBuffer=600.000000
AllowHitMarkers=True

[/Script/ShooterGame.ShooterGameUserSettings]
MasterAudioVolume=1.000000
MusicAudioVolume=1.000000
SFXAudioVolume=1.000000
VoiceAudioVolume=1.000000
CameraShakeScale=1.000000
bFirstPersonRiding=False
bThirdPersonPlayer=False
bShowStatusNotificationMessages=True
TrueSkyQuality=0.000000
FOVMultiplier=1.000000
GroundClutterDensity=0.000000
bFilmGrain=False
bMotionBlur=False
bUseDFAO=False
bUseSSAO=False
bShowChatBox=True
bCameraViewBob=True
bInvertLookY=False
bFloatingNames=True
bChatBubbles=True
bHideServerInfo=False
bJoinNotifications=False
bCraftablesShowAllItems=True
bLocalInventoryShowAllItems=False
bRemoteInventoryShowAllItems=False
LookLeftRightSensitivity=1.000000
LookUpDownSensitivity=1.000000
GraphicsQuality=1
ActiveLingeringWorldTiles=1
ClientNetQuality=3
LastServerSearchType=0
LastDLCTypeSearchType=-1
LastServerSearchHideFull=False
LastServerSearchProtected=False
HideItemTextOverlay=False
bDistanceFieldShadowing=False
LODScalar=0.780000
bToggleToTalk=False
HighQualityMaterials=True
HighQualitySurfaces=True
bTemperatureF=False
bDisableTorporEffect=False
bChatShowSteamName=False
bChatShowTribeName=True
EmoteKeyBind1=0
EmoteKeyBind2=0
bNoBloodEffects=False
bLowQualityVFX=False
bSpectatorManualFloatingNames=False
bSuppressAdminIcon=False
bUseSimpleDistanceMovement=False
bDisableMeleeCameraSwingAnims=False
bHighQualityAnisotropicFiltering=False
bPreventInventoryOpeningSounds=False
bPreventItemCraftingSounds=False
bPreventHitMarkers=False
bPreventCrosshair=False
bPreventColorizedItemNames=False
bHighQualityLODs=False
bExtraLevelStreamingDistance=False
bEnableColorGrading=True
DOFSettingInterpTime=0.000000
bDisableBloom=False
bDisableLightShafts=False
LastPVESearchType=-1
bUseVSync=False
MacroCtrl0=
MacroCtrl1=
MacroCtrl2=
MacroCtrl3=
MacroCtrl4=
MacroCtrl5=
MacroCtrl6=
MacroCtrl7=
MacroCtrl8=
MacroCtrl9=
ResolutionSizeX=1280
ResolutionSizeY=720
LastUserConfirmedResolutionSizeX=1280
LastUserConfirmedResolutionSizeY=720
WindowPosX=-1
WindowPosY=-1
bUseDesktopResolutionForFullscreen=False
FullscreenMode=2
LastConfirmedFullscreenMode=2
Version=5

[ScalabilityGroups]
sg.ResolutionQuality=100
sg.ViewDistanceQuality=3
sg.AntiAliasingQuality=3
sg.ShadowQuality=3
sg.PostProcessQuality=3
sg.TextureQuality=3
sg.EffectsQuality=3
sg.TrueSkyQuality=3
sg.GroundClutterQuality=3
sg.IBLQuality=1
sg.HeightFieldShadowQuality=3
sg.GroundClutterRadius=10000

[/Game/Mods/Genesis/TestGameMode_Genesis.TestGameMode_Genesis_C]
OverrideMaxExperiencePointsPlayer=1000000000
OverrideMaxExperiencePointsDino=1000000000
bServerGameLogEnabled=True

[SessionSettings]
SessionName=ARK #933604

[/Script/Engine.GameSession]
MaxPlayers=70
```

**Comment by klightspeed** [comment]
I'm guessing this is a GameUserSetting.ini with some settings for various mods?

What problem are you having?

**Comment by Flukethoughts** [comment]
everytime i start the servers it rewrites the config i dont understand why it even has [/Script/ShooterGame.ShooterGameUserSettings] part in it as its a server

**Comment by Flukethoughts** [comment]
Fixed it with my devs help we just made the file unwritable and now we are fine

**Comment by klightspeed** [comment]
Are the settings actually applying?

The fact that Wildcard's ARK server is re-writing the config and writing default settings suggests that it probably is not actually applying the settings in your config file.

**Comment by Flukethoughts** [comment]
yes the settins are applying but new issues popped up
Running command 'update' for instance 'shingo'
2016-10-08 02:46:43: checking for update; PID: 27598
Downloading mod 516096294 ... Mod 516096294 was not successfully downloaded
Your server is already up to date! The most recent version is 1381483.
Running command 'update' for instance 'island'
2016-10-08 02:47:18: checking for update; PID: 28227
Downloading mod 516096294 ... Mod 516096294 was not successfully downloaded
Downloading ARK update ... The server has been stopped
Applying update from staging directory
The server is now running, and should be up within 10 minutes
Running command 'update' for instance 'center'
2016-10-08 02:47:39: checking for update; PID: 28730
Downloading mod 516096294 ... Mod 516096294 was not successfully downloaded
Downloading ARK update ... The server has been stopped
Applying update from staging directory
The server is now running, and should be up within 10 minutes
Running command 'update' for instance 'mortem'
2016-10-08 02:48:02: checking for update; PID: 29287
Downloading mod 516096294 ... Mod 516096294 was not successfully downloaded
Downloading ARK update ... The server has been stopped
Applying update from staging directory
The server is now running, and should be up within 10 minutes
Running command 'update' for instance 'madagascar'
2016-10-08 02:48:22: checking for update; PID: 29808
Downloading mod 516096294 ... Mod 516096294 was not successfully downloaded
Downloading ARK update ... Stopping server...
                           The server has been stopped
Applying update from staging directory
The server is starting...
The server is now running, and should be up within 10 minutes
Running command 'update' for instance 'scorched'
2016-10-08 02:48:43: checking for update; PID: 30307
Downloading mod 516096294 ... Mod 516096294 was not successfully downloaded
Downloading ARK update ... The server has been stopped
Applying update from staging directory
The server is now running, and should be up within 10 minutes

**Comment by klightspeed** [comment]
Check your `~/Steam/logs/workshop_log.txt`

It's possible your Steam workshop directory has a mod that no longer exists, and steamcmd is trying and failing to update that.  Not that we don't have any control over what workshop items steamcmd tries to update when asked to download a mod - it will attempt to update any pre-existing workshop items before downloading the requested workshop item.

One can remove a mod that no longer exists by running `arkmanager removemod <modid>` where `<modid>` is the workshop fileid.

**Comment by Flukethoughts** [comment]
[2016-10-08 02:46:45] [AppID 346110] Loaded workshop items in "/home/steam/steamcmd/steamapps/workshop" (35 installed, 35 needed)
[2016-10-08 02:46:46] [AppID 346110] Starting Workshop download job
[2016-10-08 02:47:12] Update workshop job for app 346110 canceled: Failed to move file /home/steam/steamcmd/steamapps/workshop/content/346110/689838254/LinuxNoEditor/Materials/Particles/PS_JumpBoost_ColoredSmoke_TTA.uasset.z.uncompressed_size (Disk read failure)
[2016-10-08 02:47:12] [AppID 346110] Download item 516096294 result : I/O Operation Failed
[2016-10-08 02:47:12] [AppID 346110] Finished Workshop download job : Disk read failure
[2016-10-08 02:47:12] [AppID 346110] Updating workshop item details failed with Failure

**Comment by Flukethoughts** [comment]
[2016-10-08 00:31:34] [AppID 346110] Loaded workshop items in "/home/steam/steamcmd/steamapps/workshop" (35 installed, 35 needed)
[2016-10-08 00:31:34] [AppID 346110] Starting Workshop download job
[2016-10-08 00:31:34] [AppID 346110] Detected workshop change : changed cached item 689838254, new manifest 3649785517900086279
[2016-10-08 00:32:30] Update workshop job for app 346110 canceled: File commit failed: staging file was missing "/home/steam/steamcmd/steamapps/workshop/downloads/346110/689838254/LinuxNoEditor/Buffs/Buff_AdminFlameOn.uasset.z" (Canceled)
[2016-10-08 00:32:30] [AppID 346110] Download item 689838254 result : Request has been canceled
[2016-10-08 00:32:30] [AppID 346110] Finished Workshop download job : Canceled
[2016-10-08 00:32:30] [AppID 346110] Updating workshop item details failed with Failure
 manifest 3649785517900086279

**Comment by Flukethoughts** [comment]
troubleshooting it by uninstalling and reinstalling

**Comment by Flukethoughts** [comment]
things worked out when trying this method uninstalling and reinstalling maybe a check could be implemented for one loop to uninstall mod and then reinstall mod if this kinda error occurs? @klightspeed

**Comment by klightspeed** [comment]
Commit fe1594b now removes problematic workshop items if they cause a mod download to fail.

**Comment by Flukethoughts** [comment]
but on the setting part, everything read and works fine just had to disable writing of the file by the server which makes me question it a bit on why it happens in the first place @klightspeed

**Comment by klightspeed** [comment]
The Unreal Engine 4 Server seems to read the ini file to its state, add the options from the command-line, then write back its state to the ini file.  It also writes the ini file when you change the MOTD within the admin manager.

It would seem that if the ini file contains either parse errors or settings that are not understood, then the server will typically throw away those settings and write defaults.

The only thing to do to prevent it from writing the ini file is to do what you have done.  It's possible that the server re-reads the ini file after writing defaults, in which case any settings it understands would apply.

The client stuff is probably from Wildcard or Epic including some client-side stuff in their server build.
