### ISSUE TITLE
what would be the best option rawudp

### ISSUE THREAD

**Issue by Flukethoughts** [FezVrasta/ark-server-tools#639]
I have 6 servers going i need to configure rawudp for all of them what would be the best options for this?

**Comment by KGM6911** [comment]
Not sure if this is what you're looking for:  

To specify an option without an argument (e.g. bRawSockets), specify an empty argument (e.g. ark_bRawSockets="").

Also, are you running 6 servers on one machine?  If so, would you mind telling me the ports that you've used?  For some reason I can't get more than 3 to run on a machine reliably.  Any time I try only certain people can connect to the servers.  They run great but there is some sort of connection problem for some.

**Comment by Flukethoughts** [comment]
yea we go all of them to work
take the first server you create and for everything just +1
this means game port +1
query port +1
rcon +1 
Everything works out for us.

However though we have noticed that when connecting to the servers the client port scans the server which can cause some mitigation to go crazy and they get ip banned for about three minutes

**Comment by Flukethoughts** [comment]
figured it out it's gameport -1
