### ISSUE TITLE
daemons should be able to bring server up after crashes

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#64]
currently our daemons are quite useless, I think we should add a feature to allow crashed servers to start over if needed.

I see that upstart has the respawn stanza for this. I think other systems have their methods.

**Comment by Eremes** [comment]
/home/arkcrash.sh:
```
echo "Check server"
su steam -c 'arkmanager start'
```
I put this on my upstart .conf:
```
description "Start server when It crash"

#start and stop
start on stopped arkserv
stop on started arkserv

exec /home/arkcrash.sh
```

I put # before "start" when'll update, I need to automate this :P 
```
#start on stopped arkserv
```

This works?
I can't test this right now, I'm on the job haha

PD: Sorry for my bad english

**Comment by Sispheor** [comment]
I'am not sure if the script has to do this job. On Linux system we usualy use a monitoring system to check if the service is available and just notify if not. But the daemon doesn't restart automaticaly. And how do you know the difference between a legitimate stop and a crash?

**Comment by FezVrasta** [comment]
I would expect that stopping the service should even remove the pid, while when it crash the pid hangs in var/run

I just think that we could easily integrate this feature instead of ask users to install and configure monit or supervisor and so on

**Comment by Sispheor** [comment]
Yes.. why not after all.
I was thinking about split the project into 3 parts. One project would be a
lib. The lib do low level call like stop, start, restart and return a json
or something like this.
A second project would be the startup script. And the last would be a web
GUI. And both startup and web GUI use the lib.

2015-06-30 22:09 GMT+02:00 Fez Vrasta <notifications@github.com>:

> I would expect that stopping the service should even remove the pid, while
> when it crash the pid hangs in var/run
>
> I just think that we could easily integrate this feature instead of ask
> users to install and configure monit or supervisor and so on
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FezVrasta/ark-server-tools/issues/64#issuecomment-117326154>
> .
>



-- 
*Nicolas MARCQ*

**Comment by FezVrasta** [comment]
Yes I thin it's a good plan
