### ISSUE TITLE
unexpected EOF while looking for matching `''

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#641]
steam@arkfrancepve:/root$ arkmanager status
No instances supplied for command status
Do you wish to run this command for all instances?y
Running command 'status' for instance 'centpve'
/etc/arkmanager/arkmanager-center-pve.cfg: line 82: unexpected EOF while looking                                      for matching `''
/etc/arkmanager/arkmanager-center-pve.cfg: line 96: syntax error: unexpected end                                      of file

something is wrong but i don't know where ?

**Comment by arkfrance** [comment]
arkstChannel="1.5-dev"                                               # change it to a different branch to get non-stable versions
install_bindir="/usr/local/bin"
install_libexecdir="/usr/local/libexec/arkmanager"
install_datadir="/usr/local/share/arkmanager"

# config SteamCMD
steamcmdroot="/home/steam/"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamcmd_user="steam"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/steam/Steam/appcache/appinfo.vdf"      # cache of the appinfo command
#steamlogin="anonymous" 

# config environment
arkserverroot="/home/CENTPVE"                                           # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"        # name of ARK server executable
arkbackupdir="/home/ARK-Backups-PVE-CENTER"                                    # path to backup directory
arkwarnminutes="5"                                                  # number of minutes to warn players when using update --warn
arkautorestartfile="ShooterGame/Saved/.autorestart"                 # path to autorestart file
arkBackupPreUpdate="false"                                          # set this to true if you want to perform a backup before updating
arkTimeToKeepBackupFiles="10"                                       #Set to Automatically Remove backups older than n days
#arkStagingDir="/home/steam/ARK-Staging"                             # Uncomment to enable updates to be fully downloaded before restarting the server (reduces downtime while updating)

# Options to automatically remove old backups to keep backup size in check
# Each compressed backup is generally about 1-2MB in size.
#arkMaxBackupSizeMB="500"                                            # Set to automatically remove old backups when size exceeds this limit
#arkMaxBackupSizeGB="2"                                             # Uncomment this and comment the above to specify the limit in whole GB
arkAutoUpdateOnStart="false"                                        # set this to true if you want to always update before startup

# Update warning messages

msgWarnReason="Le serveur va redemarrer dans {time} pour {reason}"
msgTimeMinutes="{minutes} minutes"
msgTimeSeconds="{seconds} secondes"
msgReasonUpdateMod="mettre a jour le mod {modnamesupdated}"
msgReasonUpdateApp="faire la mise a jour de ARK. Les modifications sont disponibles sur notre site http://ark-france.fr/. IL Y A UNE SAVE ET CELA NE POSE PAS DE PROBLEME POUR LE TAMING, AUGMENTEZ JUSTE LA TORPEUR"
msgReasonUpdateAppMod="Installer / Mettre a jour le mod {modnamesupdated}"
msgReasonRestart="Modifier les Airdrops rouge et jaunes""
msgReasonShutdown="une mise a jour de la machine, il y en a pour 15 min en tout"
warnreason_1="Reboot quotidien, il est temps d'aller au lit les geeks !"

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="TheCenter"                                               # server map (default TheIsland)
#serverMapModId="515195633"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="504360469"                                 # Uncomment this to specify a total-conversion mod
ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort="27031"                                                # RCON Port
ark_SessionName="ARK-FRANCE.FR - PvE x5 The Center"                                  # if your session name needs special characters please use the .ini instead
ark_Port="7778"                                                     # ARK server port (default 7778)
ark_QueryPort="27016"                                               # ARK query port (default 27016)
ark_ServerPassword=""                                              # ARK server password, empty: no password required to login
ark_ServerAdminPassword="****"                                    # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="60"
ark_GameModIds="684959100,572277026,670764308,558079412,566885854,758608778,704420972,566887000,729352919,566432022,564895376"                                         # Uncomment to specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF"    
                                # Uncomment to specify a different save directory name
# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
arkflag_log=True
arkflag_newsaveformat=True
arkflag_UseBattlEye=true
arkAlwaysRestartOnCrash=true
arkflag_server=True
ark_PreventTribeAlliances=false
#arkflag_servergamelog=true
ark_ForceAllStructureLocking=true
ark_FastDecayUnsnappedCoreStructures=true
ark_OnlyAutoDestroyCoreStructures=false
arkflag_NoTransferFromFiltering=true
arkopt_clusterid=pve
ark_PreventDownloadSurvivors=False
ark_PreventDownloadItems=False
ark_PreventDownloadDinos=False
ark_PreventUploadSurvivors=False
ark_PreventUploadItems=False
ark_PreventUploadDinos=False
ark_noTributeDownloads=false
arkopt_ClusterDirOverride=/home/Cluster
# config Service
servicename="arkserv"                                               # Name of the service (don't change if you don't know what are you doing)
logdir="/var/log/arktools/pvethecenter"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID
mod_appid=346110                                                    # App ID for mods

# Mod OS Selection
mod_branch=Windows
# Add mod-specific OS selection below:
#mod_branch_496735411=Windows

# alternate configs
# example for config name "ark1":

**Comment by klightspeed** [comment]
```
/etc/arkmanager/arkmanager-center-pve.cfg: line 82: unexpected EOF while looking for matching `''
```

This tells you that there is a missing `"` on line 82

```
msgReasonRestart="Modifier les Airdrops rouge et jaunes""
```

There is a doubled `"` here.

**Comment by arkfrance** [comment]
Damn i don't know why it doubled sometime when i save it ! thanks
