### ISSUE TITLE
Config files gone

### ISSUE THREAD

**Issue by KGM6911** [FezVrasta/ark-server-tools#645]
Today I found that my Game.ini file has been overwritten on multiple servers and replaced with a 1 byte file.    Any idea how this could have happened?

**Comment by thamathar** [comment]
Its was because of the patch, alot of ppl are complaining about it, nothing to do with the ark-server-tools

**Comment by KGM6911** [comment]
Yea, I figured it was something like that.. ark-server-tools is amazing.. I have it setup to backup before every update and the file was there.. Would have sucked to not have the most current versions for 8 servers.. would have been pulling my hair out for hours trying to sort it out... this was easy fix tho.. went in to the backup folder and there it was... Just switched from windows hosting about a month ago.. These tools are the best!
