### ISSUE TITLE
"Can't load world save file, and can't find a valid backup."

### ISSUE THREAD

**Issue by Pallanas** [FezVrasta/ark-server-tools#65]
Hi,

I installed the server on my Debian server. I upped the openfile limit (checked with ulimit -a), opened the firewall ports, re-routed some ports to an internal IP as a tutorial somewhere said, etc.

After quite some time trying to get it to work, it doesn't. Here is the error I get :
```
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:F:\UE4\UnrealEngine\Projects\ShooterGame\Source\ShooterGame\Private\ShooterGameMode.cpp] [Line: 439]
Can't load world save file, and can't find a valid backup.
Signal 11 caught.
/var/log/arktools/arkserver.log (END)
```

If anyone had a similar error and fixed it or know how to fix it, I'd be glad to try the solution out.
Thanks !

**Comment by FezVrasta** [comment]
Do you have permissions to write and read to the ark folder?

**Comment by Atriusftw** [comment]
A path starting with F:\ sounds like a windows install?
Have you transfered server files from a windows install by any chance?

**Comment by timelf123** [comment]
The `F:\` path could be from the debug msg, looks like it is being fired from a source .cpp file

**Comment by Pallanas** [comment]
Nope, I installed it with SteamCMD on Linux, it must be the internal working of the server. I'll check permissions ASAP @FezVrasta

**Comment by Pallanas** [comment]
So I checked the permissions and they are set to allow read/write/exec for the whole Ark folder for the user running ```arkmanager start```. The thing still starts :
```
steam@zephyr:/home/ark/ShooterGame/Binaries/Linux$ arkmanager start
The server is starting...
The server is now up
steam@zephyr:/home/ark/ShooterGame/Binaries/Linux$ arkmanager status
 Server running:   Yes
 Server online:   No
 Server version:   673532
```

then it crashes 1-2 minutes later.

I read some other issues, it isn't a memory problem as I have 16gb dedicated, which I hope should be enough. The problem shouldn't be with the firewall either as the server seems to crash on its own before it could connect to the master server.

```arkmanager checkupdate``` writes that I'm up to date too. I have no idea what could cause this problem. I did not change the map name in the config either.

poke @FezVrasta @Atriusftw

**Comment by FezVrasta** [comment]
I have no idea... there are some people which can't run the server even if everything seems correct...

You may try to install all the developers tools of your distro to see if it helps.

**Comment by Atriusftw** [comment]
@Pallanas 

Your server is not on the latest build though. I'd update it right now and see if that might help you. (Latest build is 674165, run arkmanager forceupdate if you cant get it via checkupdate)
Other than that, have you installed libc6?

**Comment by FezVrasta** [comment]
yes there are problems with cache :/ oh god

**Comment by Atriusftw** [comment]
I'm going to do some tests when 181.0 drops tonight to see if we can resolve the caching.

**Comment by Pallanas** [comment]
I did the forceupdate which went well, yet the server still seems to crash before going live. I'll try to install it on a clean server later, I'm getting fed up with it not working right now !

Anyway, thanks for the help and this great tool guys :)

**Comment by Atriusftw** [comment]
@Pallanas - Your issue relates to segmentation fault, which _may_ mean theres some hardware problems. Basically ShooterGameServer tried to access a memory location that was not assigned.

16GB RAM is more then enough to run an ARK Server. I'd suggest running a memtest of some sort.
