### ISSUE TITLE
Instances not using alternate saved game directory

### ISSUE THREAD

**Issue by richardhendricks** [FezVrasta/ark-server-tools#654]
I have an old vanilla The Center instance, and a new Primitives+ The Center instance, and would like to co-exist the two, however the server tools are not using the alternate save locations.
I have for my P+ instance .cfg file
ark_AltSaveDirectory="primitive"

however it is not putting the files in that directory.

This is with the latest version.  Thanks for a great tool.

**Comment by klightspeed** [comment]
The option is `AltSaveDirectoryName`, not `AltSaveDirectory`.  Try using `ark_AltSaveDirectoryName="primitive"`

**Comment by richardhendricks** [comment]
Ah, my bad.  Thanks for the info.
