### ISSUE TITLE
uninstallmods

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#655]
Hey, 

is it possible to add a command to remove all the unused mods from the mod directory

for exemple : the script check all the used mod from the cfg and then remove all others (unsed one)

Thanks

**Comment by CaspyBXL** [comment]
@klightspeed

Sempai oh Lord klightspeed, please make us the arkmanager removeoldmods command.
I've been looking to ask this for some time now also.

I think arkfrance will be will be saying MERCI GRAND MAITRE klightspeed soon if this would be possible.

Greetings,
ark-server-tools Fanboy Caspy
