### ISSUE TITLE
Question For Cluster Support Scorched And The Center servers

### ISSUE THREAD

**Issue by CaspyBXL** [FezVrasta/ark-server-tools#659]
Dear Support,

I'm so happy with ur work ! 
I'm now trying to get a clustered ark to work.
I woul like some help with this if you can please.

I'm using Ark options like this in my files : 
Server 1 : 
ark_AltSaveDirectoryName="/arkserver/steam/clustersave1"
ark_ClusterDirOverride="/arkserver/steam/clustersaveOverride"      
ark_NoTransferFromFiltering 
ark_clusterid=cluster1

Server 2 : 
ark_AltSaveDirectoryName="/arkserver/steam/clustersave2"
ark_ClusterDirOverride="/arkserver/steam/clustersaveOverride"      
ark_NoTransferFromFiltering 
ark_clusterid=cluster1

Will this work ?

Greetings,

**Comment by klightspeed** [comment]
All settings in the instance config are `key=value`.  `ark_NoTransferFromFiltering` should be `ark_NoTransferFromFiltering=true`

**Comment by CaspyBXL** [comment]
Could it be its : arkflag_NoTransferFromFiltering=true ?

Thanks for responding so fast !

**Comment by klightspeed** [comment]
Yes.

Options that occur in the ...?optname=val?... have the `ark_` prefix.
Options that are of the form `-optname=val` have the `arkopt_` prefix.
Options that are of the form `-optname` have the `arkflag_` prefix.

**Comment by CaspyBXL** [comment]
Thank you klightspeed ! I will test this out when we whipe the servers and install the new versions and mods.

Thank you verry much for the support and quick anwsers !
