### ISSUE TITLE
Old version gets parsed to update.log

### ISSUE THREAD

**Issue by Atriusftw** [FezVrasta/ark-server-tools#66]
While updating today, i noticed that the updatelog had two identical entries in terms of version.

```
atrius@natrium:~/ARK$ cat /var/log/arktools/update.log
~
Jun 26, 11:49:46: update to 672599 complete
Jun 27, 02:26:15: update to 673532 complete
Jun 27, 08:56:04: update to 673532 complete
```

At 02:26 i updated to 180.2 successfully, and now at 08:56 - 180.4.
setCurrentVersion seems to work just fine;

```
atrius@natrium:~/ARK$ cat arkversion
674165
```

**Comment by FezVrasta** [comment]
this happens with the most updated version?

**Comment by Atriusftw** [comment]
Yup, pulled from master yesterday after you merged my PR.

**Comment by klightspeed** [comment]
Looking at it, we should change getAvailableVersion at tools/arkmanager#L232 and tools/arkmanager#L260 to getCurrentVersion, and integrate setCurrentVersion into getCurrentVersion.

The mismatch between arkversion and the printed update version suggests that the version returned by app_info_print doesn't match the version retrieved by the previous app_update.

It also looks steamcmd is still caching the available version somewhere, as despite removing the app info cache, it still only updated the available version after manually running steamcmd:

**[2015-06-27 18:07:37]** Ran `arkmanager checkupdate`
appinfo_log.txt:
```
[2015-06-27 18:07:37] RequestAppInfoUpdate: nNumAppIDs 1
```
arkmanager output: 
```
Querying Steam database for latest version...
Current version:  672599 
Available version:  672599 
Your server is up to date!
```

**[2015-06-27 18:08:12]** Ran steamcmd interactively
appinfo_log.txt:
```
[2015-06-27 18:08:12] RequestAppInfoUpdate: nNumAppIDs 1
[2015-06-27 18:08:13] ProductInfoChanges: change number 0->1135150, apps: 0/0, packages: 0/0
[2015-06-27 18:08:13] UpdatesJob: requesting 84 apps, 1 packages (meta data, 1024 prev attempts)
```

**[2015-06-27 18:09:03]** Ran `arkmanager update`
appinfo_log.txt:
```
[2015-06-27 18:09:03] RequestAppInfoUpdate: nNumAppIDs 1
```
arkmanager output:
```
Querying Steam database for latest version...
Current version:  672599 
Available version:  674165 
Your server needs to be restarted in order to receive the latest update.
Run "arkmanager update" to do so
```

**Comment by Atriusftw** [comment]
@klightspeed We might have to remove packageinfo.vdf before getting available version aswell.

**Comment by klightspeed** [comment]
Gah - I hadn't updated my config file, so arkmanager wasn't actually deleting the appinfo.vdf file.

**Comment by Atriusftw** [comment]
@klightspeed 

Version control usually is beautiful, but sometimes it can be a real bitch :sweat_smile:
