### ISSUE TITLE
-forcerespawndinos

### ISSUE THREAD

**Issue by KGM6911** [FezVrasta/ark-server-tools#662]
Is there a way to issue a command line option in the arkmanager start command without adding the setting to an instance or the arkmanager.cfg file?  I don't want this command to run every time I start the server.  I'm looking to use the -forcerespawndinos command line option.

Thanks

**Comment by klightspeed** [comment]
```
arkflag_forcerespawndinos=true arkmanager start
```

**Comment by KGM6911** [comment]
So if I wanted to put the command in a .sh file, could I use it like this?

/usr/local/bin/arkflag_forcerespawndinos=true arkmanager start @ann-center

**Comment by klightspeed** [comment]
```
arkflag_forcerespawndinos=true /usr/local/bin/arkmanager start @ann-center
```

The `arkflag_forcerespawndinos=true` passes that as an environment variable to the `arkmanager` program.

**Comment by KGM6911** [comment]
Thank you!

**Comment by KGM6911** [comment]
Hi.  I'm trying to do this without a .sh file now.  I want to put it in as a cronjob.  I've tried numerous combinations and I can't get it to work.  I want the server to do a restart at 8:00 am and I also want it to do the forcerespawndinos=true with that restart as well as --warn --saveworld and --backup.  

Thanks!
