### ISSUE TITLE
Kill PID not stopping auto update.

### ISSUE THREAD

**Issue by Gumballz** [FezVrasta/ark-server-tools#669]
I run auto update on my server using cronjobs

`*/17 * * * * ~/bin/arkmanager update --update-mods --saveworld --warn --backup @instance`

Previously, whenever I have wanted to stop an auto update a `Kill <PID>` has done the job and cancelled it.

Now, however, the update continues and the server shuts down as per the cronjob.

After killing the PID, I ran` arkmanager update --update-mods --saveworld --warn --backup @instance` to see if I received the *Update in progress <PID>*  message.  
No message was received and the server got the 15 minute warning broadcast.  ^C to cancel that update.  Minutes later the server received the shutdown warning with the previous cronjob time.. and proceeded to shutdown.

**Comment by arkfrance** [comment]
Same here

**Comment by klightspeed** [comment]
The update PID issue should be fixed with d7d6f3e

**Comment by arkfrance** [comment]
a friend has 

arkmanager update
Running command 'update' for instance 'main'
2016-11-28 16:03:55: checking for update; PID: 9950
Your server is already up to date! The most recent version is 1484056.

**Comment by klightspeed** [comment]
04185be should fix the update loop - i.e. if the staging directory isn't updated, then it will abort the update.

**Comment by arkfrance** [comment]
does it work if no staging directory is selected ?

**Comment by klightspeed** [comment]
If no staging directory is selected, then you are at the mercy of the Steam updating.

**Comment by arkfrance** [comment]
is there a special command for the update with staging ?

**Comment by arkfrance** [comment]
does this cron should work ? 

#*/2 * * * * /usr/local/bin/arkmanager useconfig pve update stagingdir="/home/steam/ARK-StagingPVE" --warn

**Comment by klightspeed** [comment]
```
*/2 * * * * /usr/local/bin/arkmanager useconfig pve update --stagingdir="/home/steam/ARK-StagingPVE" --warn
```

**Comment by arkfrance** [comment]
ok thanks testing right now, normaly it should stop the auto update

**Comment by arkfrance** [comment]
still auto update 

2016-11-28 18:18:18: update to 1484033 complete

**Comment by klightspeed** [comment]
v1.6.10 should fix these issues.

**Comment by arkfrance** [comment]
updating

**Comment by arkfrance** [comment]
seems to work for me

**Comment by Gumballz** [comment]
Doesn't appear to be updating for me.  

`arkmanager update --update-mods  --force @scorch
Running command 'update' for instance 'scorch'
2016-11-28 19:32:23: checking for update; PID: 9899
Downloading mod 510590313 ... Mod 510590313 downloaded
Downloading mod 520879363 ... Mod 520879363 downloaded
Downloading mod 531396658 ... Mod 531396658 downloaded
Downloading mod 531713045 ... Mod 531713045 downloaded
Downloading mod 533884503 ... Mod 533884503 downloaded
Downloading mod 538418918 ... Mod 538418918 downloaded
Downloading mod 538827119 ... Mod 538827119 downloaded
Downloading mod 543859212 ... Mod 543859212 downloaded
Downloading mod 618916953 ... Mod 618916953 downloaded
Downloading mod 626642159 ... Mod 626642159 downloaded
Downloading mod 719928795 ... Mod 719928795 downloaded
Downloading mod 725398419 ... Mod 725398419 downloaded
Downloading mod 757669231 ... Mod 757669231 downloaded
Downloading mod 760865850 ... Mod 760865850 downloaded
Downloading mod 760884349 ... Mod 760884349 downloaded
Downloading mod 775286194 ... Mod 775286194 downloaded
Downloading mod 780376136 ... Mod 780376136 downloaded
Downloading mod 783824157 ... Mod 783824157 downloaded
Downloading mod 795839164 ... Mod 795839164 downloaded
Downloading ARK update ... Update download unsuccessful`

And stops at that
Everything looked fine DLed into the staging directory, just not applying the update

**Comment by Gumballz** [comment]
btw, thanx for the fast responses and updates :)

**Comment by Gumballz** [comment]
Closing thread... New one for this issue https://github.com/FezVrasta/ark-server-tools/issues/671
