### ISSUE TITLE
Server won't start with arkmanager after latest update 180.2

### ISSUE THREAD

**Issue by tenten36** [FezVrasta/ark-server-tools#67]
Today I updated arkmanager via curl -s https://raw.githubusercontent.com/FezVrasta/ark-server-tools/master/netinstall.sh | sudo bash -s steam

then
$ arkmanager update
"Your server is already up to date! The most recent version is 673532."
That was 1 h ago, I knew there was an update, so I did it manually via steamcmd and finally got "Your server is already up to date! The most recent version is 674165." 
This is my update.log:
08:30:17: update to 669428 complete
20:16:34: No update needed.
20:17:17: No update needed.
09:11:33: No update needed.
09:13:01: No update needed.
09:17:17: No update needed.
09:45:38: No update needed.

When I now start ShooterGame via "arkmanager start" with my arkmanager.cfg, I get a Signal11 crash.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 11 caught.

I can start the server manually but can't get it to start via arkmanager. Worked fine until the last ShooterGame Update.
Can you point me in the right direction where to find some logs to the problem?

**Comment by Atriusftw** [comment]
First things first;

:white_circle: What distro are you running?
:white_circle: Did you update your config files accordinly to the update of arkmanager?

**Comment by FezVrasta** [comment]
We have added a variable inside the configuration of arkmanager 1.1 to fix this problem. If you have upgraded your ARK Server Tools but you have not updated your configuration then you'll have this problem.

**Comment by tenten36** [comment]
Fresh Ubuntu 14.04 VPS. 
Checked arkmanager.cfg and gameusersettings.ini. Problem seems when you update arkmanager it keeps the old .cfg file so I was missing the "steamcmd_appinfocache=". Sorry I missed that, it's running now.
Can you make it that the old .cfg will be kept but there is a copy of the new .cfg in /etc/arkmanager?

**Comment by Atriusftw** [comment]
@tenten36 Thank you for your suggestion. I've added that in a PL now.
