### ISSUE TITLE
Which Config File should I use?

### ISSUE THREAD

**Issue by finkwolf** [FezVrasta/ark-server-tools#670]
I've been trying to update the supply drops using the game.ini file. Do the server tools use their own game.ini file, and if so which file should I add the code for updating supply drops?

**Comment by klightspeed** [comment]
arkmanager does not modify the `Game.ini` or `GameUserSettings.ini` files.

Under the Linux ARK game server, these files are found in `ShooterGame/Saved/Config/LinuxServer`

**Comment by finkwolf** [comment]
Must be an issue with the actual configuration I'm trying to put in I guess, thanks!

**Comment by klightspeed** [comment]
Note that the filenames are case sensitive.
