### ISSUE TITLE
Test Server Ram + Linux Swap ?

### ISSUE THREAD

**Issue by CaspyBXL** [FezVrasta/ark-server-tools#674]
Dear Support,

I have a question regarding a friend who want to set up a local test server @home 

He has : 

ArchLinux OS
Intel® Core™ i5-6600K Processor (6M Cache, up to 3.90 GHz)
HDD : Toshiba X300 High-Performance 6TB - SATA 3.0 - 6GB Write Speed - 7200PM - 128M Buffer
Ram : 4GB DDR3-1600Mhz
Swap : 8GB - 64 MB Size Blocks

So in total he would have like 12GB(4+8) to use as memory.

Will he be able to run this stable using arkmanager ?
Is this stable for testing ? Do you see any issue regarding using arkmanager to use, backups, saves, reboots etc ...

I know and told him its not like having 12GB ram, but still swap is good way to compensate for ram if you don't have enough no ? Or did I see this wrong ?

Greetings and thank for the info,

**Comment by klightspeed** [comment]
As long as the person is only running a single ARK gameserver on this server, and isn't running any other memory-hungry processes (e.g. Apache) on the same server, this config should work fine.  The ARK server allocates about 4GB of memory, though this figure may be higher if a total conversion or a large mod is used.  Probably about 2-3GB of this is required most of the time - the rest is probably stuff that isn't used by the server, such as graphics assets.

**Comment by rob-bb** [comment]
I think your friend will struggle, swap is technically like ram, but it is super slow.  He should really get at least 4gb more.  While it should run as Klightspeed has said I suspect the server lag will cause the client to timeout a lot while he is playing.

**Comment by CaspyBXL** [comment]
So after some testing, i can say he is hosting 3 test servers.
No DC's
Runs smoothly, we are using a SSD driver preformated in linux swap.

Now has 32GB ram (4 real + 28 Swap)

Running : 
- The Center with anunaki
- The Island with anunaki
-  Scorched with Bionic Ark

tested with cron jobs ; 
- auto backup
- auto restarts
- auto updates (and mods)

All works fine !!!
So usign swap memory is good

(also tested on different linux distro's
- Arch Linux
- Debian 8
- CentOS 7

All really smooth !

**Comment by klightspeed** [comment]
Using a SSD will have reduced latency in accessing rarely-accessed data.  If you are IOPS limited, then you may see lag with more players, and longer startup times.  Using rotational media would have significantly compromised performance.

**Comment by CaspyBXL** [comment]
USING bs=1G count=1 oflag=direct

WITHOUT SWAP
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB) copied, 7.474 s, 133.1 MB/s

startup time The Center Server : 
Full Startup: 50.59 seconds (BP compile: 0.00 seconds)


bs=1G count=1 oflag=dsync
USING SWAP
1+0 records in
1+0 records out
1073741824 bytes (1.1 GB) copied, 11.474 s, 121.1 MB/s

startup time The Center Server : 
Full Startup: 58.59 seconds (BP compile: 0.00 seconds)

I guess 8 seconds delay on startup is not really an issue.

Server FPS with 2 People --> 29.9(best) - worst(29.1) 
Server FPS with 14 People --> 28.4(best) - worst(26.3) 

Around a base that has 4581 structures --> server FPS --> 29.0 --> Client FPS 105 FPS
