### ISSUE TITLE
Prozess killed every hour?

### ISSUE THREAD

**Issue by bimmelmurks** [FezVrasta/ark-server-tools#675]
arkserver.log:
2016-12-03 11:10:40: server is up
/usr/local/bin/arkmanager: line 929: 25848 Killed                  "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
2016-12-03 14:16:03: Bad PID ''; expected '25848'
2016-12-03 14:16:03: exited with status 0
2016-12-03 14:16:03: restarting server

since Ark 252.61 the server is shutting down every hour...What could be the problem?

**Comment by klightspeed** [comment]
Unless you have a scheduled task that runs something like `killall -KILL ShooterGameServer`, the only reasons that a process should be `Killed` (i.e. killed with `SIGKILL`) are where either your server runs out of memory and the OOM killer is invoked, or where the process attempts to allocate more than 8MB of stack space.

Are there any log entries around `Dec  3 14:16:03` in `/var/log/messages` or `/var/log/kern.log`?

**Comment by bimmelmurks** [comment]
no logs after debian upgrade, sry. i'll reinstall rsyslog now. 
btw: since 23:30 mez no more restarts.... dont know why ^^
