### ISSUE TITLE
support commands concatenation

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#68]
I think we should add support for command concatenation.

This would allow users to run commands like:

```
arkmanager stop update start
```

And in future it could be used to prepare one line commands like:

```
arkmanager update broadcast "Server is again up!"
```

**Comment by Atriusftw** [comment]
Well, once RCON is supported i'm pretty sure most people will set up cronjobs for this purpose.

**Comment by Sispheor** [comment]
+1. each users should use it's own script that call many arkmanager command for this purpose.

**Comment by klightspeed** [comment]
This issue should have been satisfied by b52770f
