### ISSUE TITLE
Can't start!

### ISSUE THREAD

**Issue by peterkristel** [FezVrasta/ark-server-tools#681]
Running command 'start' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
touch: cannot touch `/home/steam/ARK/.startAfterUpdate-main': Permission denied
The server is starting...
The server is now running, and should be up within 10 minutes

**Comment by peterkristel** [comment]
root@server1:/home/Ark# arkmanager run
Running command 'run' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
/usr/local/bin/arkmanager: line 780: cd: /home/steam/ARK/ShooterGame/Binaries/Linux: No such file or directory
/usr/local/bin/arkmanager: line 789: /home/steam/ARK/ShooterGame/Saved/.arkmanager-main.pid: Permission denied
2016-12-10 18:56:18: start
2016-12-10 18:56:18: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32330\?SessionName=ARK\ Server\ Tools\?Port=7777\?QueryPort=27015\?ServerPassword\?ServerAdminPassword=keyboardcat\?MaxPlayers=70\?listen
/usr/local/bin/arkmanager: line 949: /home/steam/ARK/ShooterGame/Saved/.arkserver-main.pid: Permission denied
/usr/local/bin/arkmanager: line 946: /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer: No such file or directory
2016-12-10 18:56:18: Server PID: 4126
2016-12-10 18:56:23: Bad PID ''; expected '4126'
2016-12-10 18:56:23: exited with status 0

**Comment by klightspeed** [comment]
This and your next 2 issues suggest that your `steam` user does not have permissions to either the `/home/steam` directory or to the `/home/steam/ARK` directory (probably because you've created the directory while running as root).

Please try running `chown -R steam:steam /home/steam`

**Comment by peterkristel** [comment]
Now i get this: [  WARN  ]      Your ARK server exec could not be found.

**Comment by klightspeed** [comment]
I presume you haven't tried re-running `arkmanager install` yet?

**Comment by peterkristel** [comment]
thads what i get when i do thad command

**Comment by klightspeed** [comment]
You should no longer get the warning once the install has completed.

**Comment by peterkristel** [comment]
arkmanager install
Running command 'install' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
Installing ARK server ... \


How long it takes?

**Comment by Mysterius** [comment]
Let it run, it's downloading Ark. Depending on your server connection it could take quite a long time (from a few minutes to an hour, I guess).

**Comment by klightspeed** [comment]
You can use `arkmanager install --verbose` to see the output of the install.
The length of time depends on how fast the internet connection and storage are.

**Comment by peterkristel** [comment]
OK thanks!
