### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by peterkristel** [FezVrasta/ark-server-tools#682]
arkmanager install
Running command 'install' for instance 'main'
[  WARN  ]      Your ARK server exec could not be found.
[  ERROR  ]     The ARK SavedArks directory is not writable, and saveworld will fail
Installing ARK server ... |
Message from syslogd@server1 at Dec 10 19:26:52 ...
 sert_20161210192651_7.dmp[4987]: Finished uploading minidump (out-of-process): success = yes

Message from syslogd@server1 at Dec 10 19:26:52 ...
 sert_20161210192651_7.dmp[4987]: response: CrashID=bp-921f0b2e-d41c-4dda-8ed3-606f12161210

Message from syslogd@server1 at Dec 10 19:26:52 ...
 sert_20161210192651_7.dmp[4987]: file ''/tmp/dumps/assert_20161210192651_7.dmp'', upload yes: ''CrashID=bp-921f0b2e-d41c-4dda-8ed3-606f12161210''

**Comment by klightspeed** [comment]
It looks like this was caused by the cause of #681
