### ISSUE TITLE
Backup keeps using same old *.ark file

### ISSUE THREAD

**Issue by PhoenixMage** [FezVrasta/ark-server-tools#685]
Backup keeps using same old *.ark file

Hi,

I am runing arkmanager 1.6-dev currently running commit is 64741f1.

I have an automated backup running every 15 minutes however all the backups contain the same TheIsland.ark file, hash is the same across all version with an old timestamp.

The save file itself is fine and if I restore on of the old ark files from the Saves directory they are ok.

Appreciate you looking into the issue.

**Comment by klightspeed** [comment]
Please try switching to the `master` branch.

**Comment by PhoenixMage** [comment]
ok, switched to the master branch and upgrade-tools, now running 1.6.12, commit 567f899, based on the contents of the last backup, issue is still happening.

**Comment by klightspeed** [comment]
Are you using a total-conversion or map mod (e.g. The Center)?

Please check the contents of your `ShooterGame/Saved/SavedArks` directory.  Does the `TheIsland.ark` file have the same timestamp as in the backup?  Apart from the timestamped backups, are there any other `.ark` files there?

**Comment by PhoenixMage** [comment]
Hi,

This particular instance is only The Island, it has half a dozen steam workshop mods installed, none of them map mods. I have other instances that are not currently backed up for Scorched Earth and The Center. I am not running primitive plus either.

TheIsland.ark file is in ShooterGame/Saved/theIsland as I am using ark_AltSaveDirectoryName in my instance config.

TheIsland.ark in there has a different timestamp that is being updated regularly.

The only other ark files are the timestamped backups.

**Comment by klightspeed** [comment]
So you have `ark_AltSaveDirectoryName=theIsland`?

If you upgrade arkmanager, and perform a manual backup, what does it show the Saved arks directory as?

**Comment by PhoenixMage** [comment]
Correct, I have that line in my cfg.

The output from a manual backup doesnt actually specify the Saved arks directory.

See output below:
Running command 'backup' for instance 'TheIsland'
 Copying ARK world file                                            [   OK   ]
 Copying ARK profile files
   xxx.arkprofile                                    [   OK   ]
 Copying ARK tribe files 
   xxx.arktribe                                             [   OK   ]
 Copying ARK tribute tribe files 
 Copying GameUserSettings.ini                                      [   OK   ]
 Copying Game.ini                                                  [   OK   ]
 Compressing Backup                                                [   OK   ]
 Created Backup:  2016-12-11_06.39.46.tar.bz2

**Comment by klightspeed** [comment]
Please try upgrading arkmanager to v1.6.13, then try again.

**Comment by PhoenixMage** [comment]
No dice, is there a verbose option that will give me more info?

**Comment by klightspeed** [comment]
v1.6.13 adds printing out the detected saved arks directory and the world file name.  The commit should be 481b393

**Comment by PhoenixMage** [comment]
Sorry missed that, it lists the correct directory:
Running command 'backup' for instance 'TheIsland'
\033[0;39m Saved arks directory is /ark/server/ShooterGame/Saved/theIsland
 Copying ARK world file (TheIsland)                                [   OK   ]
 Copying ARK profile files
   76561198001611860.arkprofile                                    [   OK   ]
 Copying ARK tribe files 
   1539113781.arktribe                                             [   OK   ]
 Copying ARK tribute tribe files 
 Copying GameUserSettings.ini                                      [   OK   ]
 Copying Game.ini                                                  [   OK   ]
 Compressing Backup                                                [   OK   ]
 Created Backup:  2016-12-11_06.49.01.tar.bz2

**Comment by klightspeed** [comment]
The saved world file is exactly `TheIsland.ark`, and there are no other `.ark` files in the directory other than the timestamped backups?  Does any file in the directory match the timestamp of the .ark file that is being backed up?

**Comment by PhoenixMage** [comment]
Yes that is the name of the save file, there were no other .ark files in that directory excepot the timestamped backups BUT, I did find a directory in there which had an old TheIsland.ark file in there.

After I removed that directory it seems to have fixed it.

**Comment by TarrX** [comment]
I do have the same issue and it really upsets me, to be honest. There have been a few other .ark files in the directory but I do see no reason why this should happen. It is not really possible to replicate the issue but it cost me alot of time / work ingame.

**Comment by TarrX** [comment]
And after looking at some of the code, getServerMapFilename() is kinda insane to use for a backup function. Or any other function, come to that. A proper behaviour imho would be to check for the regular file name and if that is missing just abort. And offer some sort of command line switch to try a recovery. But not just do this wild find magic without even informing the user that something went wild is just bad.

**Comment by klightspeed** [comment]
Commit 371da71 should fix this, and make any ARK backup failure messages more verbose.

**Comment by TarrX** [comment]
Thank you!
