### ISSUE TITLE
Game.ini overwritten on startup

### ISSUE THREAD

**Issue by dborg92** [FezVrasta/ark-server-tools#689]
As the issue title states, my Game.ini file gets overwritten to a blank file upon boot up. I can't find any reference to what might be causing this anywhere in the readme. 
Do arkmanager.cfg or main.cfg have something to do with this?
Is there an option to remove this so that i can manually set my Game.ini file?

**Comment by Mysterius** [comment]
Hello,

As far as I'm aware, this happens when there's a typo/error in the .ini file. Could you post its content?
In the meantime, double check if everything inside is correct.

**Comment by dborg92** [comment]
Thanks for the quick response. I'll start to do some digging, but the game.ini is one i'd used in the past but not for a while, so some lines may be outdated.

> [/script/shootergame.shootergamemode]
GlobalSpoilingTimeMultiplier=4
GlobalItemDecompositionTimeMultiplier=3
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_RawMeat_C ",Multiplier=.2)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_RawMeat_Fish ",Multiplier=.2)
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_Berry_Narcoberry_C",Multiplier=5.0
HarvestResourceItemAmountClassMultipliers=(ClassName="PrimalItemConsumable_ChitinPaste_C",Multiplier=5.0
DinoSpawnWeightMultipliers=(DinoNameTag=Quetz,SpawnWeightMultiplier=10.0,OverrideSpawnLimitPercentage=true,SpawnLimitPercentage=0.5)
OverrideMaxExperiencePointsPlayer=2771054
ResourceNoReplenishRadiusPlayers=.33
ResourceNoReplenishRadiusStructures=.33
PerLevelStatsMultiplier_Player[7]=2.5
PerLevelStatsMultiplier_Player[11]=2.5
PerLevelStatsMultiplier_DinoTamed[7]=2.0
PerLevelStatsMultiplier_DinoTamed[0]=1.0
PerLevelStatsMultiplier_DinoTamed[8]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[7]=2.0
PerLevelStatsMultiplier_DinoTamed_Add[0]=1.0
PerLevelStatsMultiplier_DinoTamed_Add[8]=1.0
PerLevelStatsMultiplier_DinoTamed_Affinity[9]=2.0
PerLevelStatsMultiplier_DinoTamed_Affinity[1]=2.0
PerLevelStatsMultiplier_DinoTamed_Affinity[0]=1.2
PerLevelStatsMultiplier_DinoTamed_Affinity[8]=1.0
MatingIntervalMultiplier=0.01
EggHatchSpeedMultiplier=15
BabyMatureSpeedMultiplier=5
CropGrowthSpeedMultiplier=1000
LayEggIntervalMultiplier=5
CropDecaySpeedMultiplier=3
StructureDamageRepairCooldown=0
bPassiveDefensesDamageRiderlessDinos=true
DinoHarvestingDamageMultiplier=4
DinoTurretDamageMultiplier=4
BabyCuddleIntervalMultiplier=100
BabyCuddleGracePeriodMultiplier=100
LevelExperienceRampOverrides=(ExperiencePointsForLevel[0]=5,ExperiencePointsForLevel[1]=10,ExperiencePointsForLevel[2]=20,ExperiencePointsForLevel[3]=40,ExperiencePointsForLevel[4]=80,ExperiencePointsForLevel[5]=106,ExperiencePointsForLevel[6]=139,ExperiencePointsForLevel[7]=184,ExperiencePointsForLevel[8]=243,ExperiencePointsForLevel[9]=321,ExperiencePointsForLevel[10]=423,ExperiencePointsForLevel[11]=559,ExperiencePointsForLevel[12]=737,ExperiencePointsForLevel[13]=973,ExperiencePointsForLevel[14]=1119,ExperiencePointsForLevel[15]=1287,ExperiencePointsForLevel[16]=1480,ExperiencePointsForLevel[17]=1702,ExperiencePointsForLevel[18]=1958,ExperiencePointsForLevel[19]=2251,ExperiencePointsForLevel[20]=2476,ExperiencePointsForLevel[21]=2724,ExperiencePointsForLevel[22]=2997,ExperiencePointsForLevel[23]=3296,ExperiencePointsForLevel[24]=3626,ExperiencePointsForLevel[25]=3880,ExperiencePointsForLevel[26]=4151,ExperiencePointsForLevel[27]=4442,ExperiencePointsForLevel[28]=4753,ExperiencePointsForLevel[29]=5085,ExperiencePointsForLevel[30]=5340,ExperiencePointsForLevel[31]=5607,ExperiencePointsForLevel[32]=5887,ExperiencePointsForLevel[33]=6181,ExperiencePointsForLevel[34]=6490,ExperiencePointsForLevel[35]=6750,ExperiencePointsForLevel[36]=7020,ExperiencePointsForLevel[37]=7301,ExperiencePointsForLevel[38]=7593,ExperiencePointsForLevel[39]=7897,ExperiencePointsForLevel[40]=8212,ExperiencePointsForLevel[41]=8541,ExperiencePointsForLevel[42]=8883,ExperiencePointsForLevel[43]=9238,ExperiencePointsForLevel[44]=9607,ExperiencePointsForLevel[45]=9992,ExperiencePointsForLevel[46]=10391,ExperiencePointsForLevel[47]=10807,ExperiencePointsForLevel[48]=11239,ExperiencePointsForLevel[49]=11689,ExperiencePointsForLevel[50]=12156,ExperiencePointsForLevel[51]=12643,ExperiencePointsForLevel[52]=13148,ExperiencePointsForLevel[53]=13674,ExperiencePointsForLevel[54]=14221,ExperiencePointsForLevel[55]=14790,ExperiencePointsForLevel[56]=15382,ExperiencePointsForLevel[57]=15997,ExperiencePointsForLevel[58]=16637,ExperiencePointsForLevel[59]=17302,ExperiencePointsForLevel[60]=17994,ExperiencePointsForLevel[61]=18714,ExperiencePointsForLevel[62]=19463,ExperiencePointsForLevel[63]=20241,ExperiencePointsForLevel[64]=21658,ExperiencePointsForLevel[65]=23174,ExperiencePointsForLevel[66]=24796,ExperiencePointsForLevel[67]=26532,ExperiencePointsForLevel[68]=28389,ExperiencePointsForLevel[69]=30377,ExperiencePointsForLevel[70]=32503,ExperiencePointsForLevel[71]=34778,ExperiencePointsForLevel[72]=37213,ExperiencePointsForLevel[73]=39818,ExperiencePointsForLevel[74]=42605,ExperiencePointsForLevel[75]=45587,ExperiencePointsForLevel[76]=48778,ExperiencePointsForLevel[77]=52193,ExperiencePointsForLevel[78]=55846,ExperiencePointsForLevel[79]=58639,ExperiencePointsForLevel[80]=61571,ExperiencePointsForLevel[81]=64649,ExperiencePointsForLevel[82]=67882,ExperiencePointsForLevel[83]=71276,ExperiencePointsForLevel[84]=74839,ExperiencePointsForLevel[85]=77085,ExperiencePointsForLevel[86]=79397,ExperiencePointsForLevel[87]=81779,ExperiencePointsForLevel[88]=84232,ExperiencePointsForLevel[89]=86759,ExperiencePointsForLevel[90]=89362,ExperiencePointsForLevel[91]=92043,ExperiencePointsForLevel[92]=94804,ExperiencePointsForLevel[93]=97648,ExperiencePointsForLevel[94]=98625,ExperiencePointsForLevel[95]=99611,ExperiencePointsForLevel[96]=100607,ExperiencePointsForLevel[97]=101613,ExperiencePointsForLevel[98]=102630,ExperiencePointsForLevel[99]=103656)
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=8
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=12
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=16
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=20
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=24
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=28
OverridePlayerLevelEngramPoints=32
OverridePlayerLevelEngramPoints=32
OverridePlayerLevelEngramPoints=32
OverridePlayerLevelEngramPoints=32
OverridePlayerLevelEngramPoints=32
OverridePlayerLevelEngramPoints=36
OverridePlayerLevelEngramPoints=36
OverridePlayerLevelEngramPoints=36
OverridePlayerLevelEngramPoints=36
OverridePlayerLevelEngramPoints=36
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=40
OverridePlayerLevelEngramPoints=45
OverridePlayerLevelEngramPoints=45
OverridePlayerLevelEngramPoints=45
OverridePlayerLevelEngramPoints=45
OverridePlayerLevelEngramPoints=45
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=50
OverridePlayerLevelEngramPoints=55
OverridePlayerLevelEngramPoints=55
OverridePlayerLevelEngramPoints=55
OverridePlayerLevelEngramPoints=55
OverridePlayerLevelEngramPoints=55
OverridePlayerLevelEngramPoints=60
OverridePlayerLevelEngramPoints=60
OverridePlayerLevelEngramPoints=60
OverridePlayerLevelEngramPoints=60
OverridePlayerLevelEngramPoints=60
OverridePlayerLevelEngramPoints=65
OverridePlayerLevelEngramPoints=65
OverridePlayerLevelEngramPoints=65
OverridePlayerLevelEngramPoints=65
OverridePlayerLevelEngramPoints=65
OverridePlayerLevelEngramPoints=70
OverridePlayerLevelEngramPoints=70
OverridePlayerLevelEngramPoints=70
OverridePlayerLevelEngramPoints=70
OverridePlayerLevelEngramPoints=70
OverridePlayerLevelEngramPoints=75
OverridePlayerLevelEngramPoints=75
OverridePlayerLevelEngramPoints=75
OverridePlayerLevelEngramPoints=75
OverridePlayerLevelEngramPoints=75
OverridePlayerLevelEngramPoints=80
OverridePlayerLevelEngramPoints=80
OverridePlayerLevelEngramPoints=80
OverridePlayerLevelEngramPoints=80
OverridePlayerLevelEngramPoints=80
OverridePlayerLevelEngramPoints=85
OverridePlayerLevelEngramPoints=85
OverridePlayerLevelEngramPoints=85
OverridePlayerLevelEngramPoints=85
OverridePlayerLevelEngramPoints=85
OverridePlayerLevelEngramPoints=90
OverridePlayerLevelEngramPoints=90
OverridePlayerLevelEngramPoints=90
OverridePlayerLevelEngramPoints=90
OverridePlayerLevelEngramPoints=90
OverridePlayerLevelEngramPoints=95
OverridePlayerLevelEngramPoints=95
OverridePlayerLevelEngramPoints=95
OverridePlayerLevelEngramPoints=95
OverridePlayerLevelEngramPoints=95

**Comment by dborg92** [comment]
I'll attempt using a simpler set of code first to verify if a typo is indeed the problem.

**Comment by dborg92** [comment]
It appears there is a typo. When i shorten my list of commands the file remains as is. thank you.  I'll do some digging on my own to find the typo(s).
