### ISSUE TITLE
Too many arkmanager instances ?

### ISSUE THREAD

**Issue by rob-bb** [FezVrasta/ark-server-tools#691]
I have an over spawning problem with arkmanager :)

I have 2 ark server running on my machine, yet I have 14 instances of arkmanager trying to update them.

`root      3525  0.0  0.0  11284  3228 ?        S    20:37   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
root      3560  0.0  0.0 275400  9892 ?        S    20:37   0:00 su steam -c /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
steam     3561  0.0  0.0  12768  4660 ?        Ss   20:37   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
steam     4393  0.0  0.0  13012  4444 ?        S    20:38   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
steam     4404  0.0  0.0  12900  4196 ?        S    20:38   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
root      5858  0.0  0.0  11284  3112 ?        S    20:39   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
root      5893  0.0  0.0 275400 10020 ?        S    20:39   0:00 su steam -c /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
steam     5894  0.0  0.0  12768  4636 ?        Ss   20:39   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
steam     5899  0.0  0.0  12908  4136 ?        S    20:39   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
steam     6524  0.0  0.0  12900  3464 ?        S    20:39   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
steam     6525  0.0  0.0  12928  4100 ?        S    20:39   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
steam     6529  0.0  0.0  12936  3564 ?        S    20:39   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
steam     6569  0.0  0.0  12908  3468 ?        S    20:39   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
steam     6570  0.0  0.0  12908  3340 ?        S    20:39   0:00 /bin/bash /usr/local/bin/arkmanager update --update-mods --warn --saveworld @all
steam     6578  0.0  0.0  12824  2292 pts/1    S+   20:39   0:00 grep --color=auto arkmanager`

**Comment by rob-bb** [comment]
Nerver Mind, a crontab error I had it running an update ever damn minute instead of every 30

Doh!

**Comment by klightspeed** [comment]
The first 5 processes look like they are for the first update run, updating the first instance, and the next 9 processes look like they're from the second update run, updating the second instance.
