### ISSUE TITLE
Cant update the Tools

### ISSUE THREAD

**Issue by djpanda** [FezVrasta/ark-server-tools#694]
I´m actualy on Version 1.6 and tryed a few times now to update to the actual found Version 1.6.14

> arkmanager v1.6: Checking for updates...
> Getting latest release...
> A new version has been released: v1.6.14
> * Fix typo of getServerPID in doRun
> * Add instance name to arkmanager.log log entries
> * Add timestamp and instance name to arkserver.log log entries
> Do you want to upgrade to v1.6.14? [Y/N] y

But after i accept it with "y" Comes ->>

> Getting commit for latest release...
> Downloading installer
> Running install.sh
> Ark server will now start on boot, if you want to remove this feature run the following line
> systemctl disable arkmanager.service
> A previous version of ARK Server Tools was detected in your system, your old configuration was not overwritten. You may need to manually update it.
> A copy of the new configuration file was included in /etc/arkmanager. Make sure to review any changes and update your config accordingly!
> ARK Server Tools successfully upgraded
> Version: 1.6
> Channel: master
> Commit: b8c6483
> Release Tag: v1.6.09
> Blob SHA: 42672a2c2754752a0216b86dd8a5728ab879ee6a

So the problem is it told it was upgraded but i wasnt. And thats everytime i try it.
I was thinking than ... lets take a look at the new config. and it wrote me a new one with a new line for autorestart in (dont know why, i have multiple instances and every instance had this variable in his own cfg) so i wa thinking i will thest an upgrade with the new config so i renamed it to arkmanager.cfg without the .NEW and started an upgrade-tools  but the install script told me the same text and wrote me another .cfg.NEw into the Folder so plz help what is my problem and how could we fix it.

**Comment by klightspeed** [comment]
What is the output of `type arkmanager`
What is `install_bindir` set to in `/etc/arkmanager/arkmanager.cfg`?
If `install_bindir=/usr/local/bin`, what is the output of `/usr/local/bin/arkmanager --version`

**Comment by djpanda** [comment]
1) arkmanager is hashed (/usr/local/bin/arkmanager)
2) install_bindir="/usr/bin"
3) > Version: 1.6
> Channel: master
> Commit: b8c6483
> Release Tag: v1.6.09
> Blob SHA: 42672a2c2754752a0216b86dd8a5728ab879ee6a

**Comment by djpanda** [comment]
but /usr/bin/arkmanager --Version givs me 
 > Version: 1.6
> Channel: master
> Commit: 37db49f
> Release Tag: v1.6.14
> Blob SHA: 0e92dcd1078a0c936ee4dea96a8a0820ada017f2

damn whats that

**Comment by djpanda** [comment]
the other lines in the arkmanager.cfg are 

arkstChannel="master"                                               # change it to a different branch to get non-stable versions
install_bindir="/usr/bin"
install_libexecdir="/usr/libexec/arkmanager"
install_datadir="/usr/share/arkmanager"

**Comment by klightspeed** [comment]
Since you have set the install binary directory to `/usr/bin`, you can remove `/usr/local/bin/arkmanager`

After removing that, you may need to run `hash -d arkmanager` (or log out and back in)

**Comment by djpanda** [comment]
great thx for your help im something good on Linux but not a pro ;)

> arkmanager upgrade-tools
> arkmanager v1.6: Checking for updates...
> Getting latest release...
> Your ARK server tools are already up to date
