### ISSUE TITLE
Rebase dev 1.2

### ISSUE THREAD

**Issue by Sispheor** [FezVrasta/ark-server-tools#70]
This branch is 27 commits ahead, 37 commits behind master.

This branch should have nothing behind the master.

**Comment by Blackskyliner** [comment]
"Rebase" a public branch seems not to be (never) a desired solution for all ppls branching/basing their work off of it.

I guess you ment merging the lastest changes from master with those laying on the 1.2 branch?

**Comment by Sispheor** [comment]
Yep.
Le 27 juin 2015 12:30 PM, "Blackskyliner" <notifications@github.com> a
écrit :
