### ISSUE TITLE
Server listening.

### ISSUE THREAD

**Issue by peterkristel** [FezVrasta/ark-server-tools#700]
The server listening.
I start the server then i get this: 
Running command 'status' for instance 'main'
 Server running:   Yes
 Server listening:   Yes
Server Name: [GravityPvP] [EU/NL] [PvP] [ALL X20-X10] [MODS] - (v253.51)
Players: 0 / 70
Active Players: 0
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/185.56.60.112:27015

30 seconds later:

Running command 'status' for instance 'main'
 Server running:   Yes
 Server listening:   No

**Comment by peterkristel** [comment]
an then over now yes then no ..

**Comment by peterkristel** [comment]
EngineCrashHandler: Signal=11

**Comment by peterkristel** [comment]
/usr/local/bin/arkmanager: line 937:  6834 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"

**Comment by klightspeed** [comment]
The server crashed.  Then the script saw that it had crashed after successfully starting, and started it up again.

**Comment by peterkristel** [comment]
The problem was a mod
