### ISSUE TITLE
Problem command line

### ISSUE THREAD

**Issue by zazufira** [FezVrasta/ark-server-tools#701]
Where does this command come from?

**"/usr/local/bin/arkmanager: ligne 674: lsof : commande introuvable"**

Whether it is started or not, in the status command, it is there for each server. cordially

_Running command 'status' for instance 'island'
 Server running:   No
/usr/local/bin/arkmanager: ligne 674: lsof : commande introuvable
 Server listening:   No
 Server build ID:   1545015_

**Comment by klightspeed** [comment]
`command introuvable` ("command not found" in english) for lsof suggests that lsof is not installed.

**Comment by zazufira** [comment]
Thanks, I forgot to reinstall lsof ^^
