### ISSUE TITLE
Instance not starting since 253.85 update

### ISSUE THREAD

**Issue by Evilcious** [FezVrasta/ark-server-tools#704]
Hi and Happy new year !
Since 253.85, my server on Ubuntu 16.04 doesn't seem to start (it was starting like a charm yesterday in 253.71).

Someone has an idea ? You can find the log and the config file below

> Running command 'run' for instance 'theIsland'
> 2017-01-03 07:09:06: start
> 2017-01-03 07:09:06: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?GameModIds=817096835\,656525905\,760880376\,630601751\,781821951\,558079412\,752691369\,610732247\,793605978\,566887000\,566885854\,609425335\,813463849\,763230897\,779897534\,766032350\,802922362\,815650546\?ServerPassword\?ServerAdminPassword=PASSWORD\?RCONPort=27031\?Port=7777\?QueryPort=27015\?StructurePreventResourceRadiusMultiplier=1.000000\?PvEDinoDecayPeriodMultiplier=1\?PvEDinoDecayPeriodMultiplier\?KickIdlePlayersPeriod=3600.000000\?PerPlatformMaxStructuresMultiplier=1\?PerPlatformMaxStructuresMultiplier\?AutoSavePeriodMinutes=20\?ListenServerTetherDistanceMultiplier=1.000000\?MaxTamedDinos=5000.000000\?RCONServerGameLogBuffer=600.000000\?ServerCrosshair=true\?alwaysNotifyPlayerJoined=false\?alwaysNotifyPlayerLeft=false\?allowThirdPersonPlayer=true\?globalVoiceChat=false\?ShowMapPlayerLocation=true\?noTributeDownloads=true\?proximityChat=false\?serverPVE=false\?XPMultiplier=5\?TamingSpeedMultiplier=10\?HarvestAmountMultiplier=5\?serverHardcore=false\?serverForceNoHud=false\?DinoDamageMultiplier=0.9\?ResourcesRespawnPeriodMultiplier=1.1\?PlayerCharacterWaterDrainMultiplier=0.9\?DinoCharacterFoodDrainMultiplier=0.8\?AllowCaveBuildingPvE=false\?DinoCountMultiplier=2\?DisableStructureDecayPvE=false\?PvPStructureDecay=true\?DisableDinoDecayPvE=false\?AllowFlyerCarryPvE=false\?DifficultyOffset=1\?DifficultyValue=17\?NightTimeSpeedScale=1.4\?PvEStructureDecayDestructionPeriod=0\?PreventOfflinePvP=True\?AllowAnyoneBabyImprintCuddle=True\?RCONEnabled=True\?PreventOfflinePvPInterval=900.000000\?OverrideOfficialDifficulty=15.000000\?TheMaxStructuresInRange=10500.000000\?AutoDestroyOldStructuresMultiplier=1.000000\?RaidDinoCharacterFoodDrainMultiplier=1.000000\?EnableExtraStructurePreventionVolumes=True\?ShowFloatingDamageText=True\?PreventDiseases=True\?NonPermanentDiseases=True\?TribeLogDestroyedEnemyStructures=True\?PvEAllowStructuresAtSupplyDrops=False\?AllowHitMarkers=True\?SessionName=SERVER\NAME \?Message=Welcome\ to\ the\ Island\ Extinction\ SERVER\ \!\ Please\ respect\ everyone\ and\ everything\ \!\?Duration=10\?OverrideMaxExperiencePointsPlayer=999999999\?OverrideMaxExperiencePointsDino=999999999\?bServerGameLogEnabled=True\?MaxPlayers=70\?listen
> 2017-01-03 07:09:06: Server PID: 2123
> Using binned.
> 4.5.1-0+UE4 7038 3077 402 6
> [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
> Setting breakpad minidump AppID = 346110
> Signal 11 caught.
> EngineCrashHandler: Signal=11
> /usr/local/bin/arkmanager: line 671:  2123 Segmentation fault      "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
> 2017-01-03 07:09:27: Bad PID ''; expected '2123'
> 2017-01-03 07:09:27: exited with status 0
> 

Here is the config :

> # config environment
> arkserverroot="/home/steam/ARK"                                     # path of your ARK server files (default ~/ARK)
> 
> # ARK server options - use ark_<optionname>=<value>
> # comment out these values if you want to define them
> # inside your GameUserSettings.ini file
> serverMap="TheIsland"                                               # server map (default TheIsland)
> #serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
> #ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
> #ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name
> 
> # ARK server flags - use arkflag_<optionname>=true
> #arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
> #arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
> 
> # ARK server options - i.e. for -optname=val, use arkopt_optname=val
> #arkopt_StructureDestructionTag=DestroySwampSnowStructures
> 
> ark_GameModIds="817096835,656525905,760880376,630601751,781821951,558079412,752691369,610732247,793605978,566887000,566885854,609425335,813463849,763230897,779897534,766032350,802922362,815650546"
> ark_ServerPassword=
> ark_ServerAdminPassword=PASSWORD
> ark_RCONPort="27031"                                                # RCON Port
> ark_Port="7778"                                                     # ARK server port (default 7778)
> ark_QueryPort="27015"                                               # ARK query port (default 27015)
> ark_StructurePreventResourceRadiusMultiplier=1.000000
> ark_PvEDinoDecayPeriodMultiplier=1.000000
> ark_PvEDinoDecayPeriodMultiplier=1
> ark_KickIdlePlayersPeriod=3600.000000
> ark_PerPlatformMaxStructuresMultiplier=1.000000
> ark_PerPlatformMaxStructuresMultiplier=1
> ark_AutoSavePeriodMinutes=20
> ark_ListenServerTetherDistanceMultiplier=1.000000
> ark_MaxTamedDinos=5000.000000
> ark_RCONServerGameLogBuffer=600.000000
> ark_ServerCrosshair=true
> ark_alwaysNotifyPlayerJoined=false
> ark_alwaysNotifyPlayerLeft=false
> ark_allowThirdPersonPlayer=true
> ark_globalVoiceChat=false
> ark_ShowMapPlayerLocation=true
> ark_noTributeDownloads=true
> ark_proximityChat=false
> ark_serverPVE=false
> ark_XPMultiplier=5
> ark_TamingSpeedMultiplier=10
> ark_HarvestAmountMultiplier=5
> ark_serverHardcore=false
> ark_serverForceNoHud=false
> ark_DinoDamageMultiplier=0.9
> ark_ResourcesRespawnPeriodMultiplier=1.1
> ark_PlayerCharacterWaterDrainMultiplier=0.9
> ark_DinoCharacterFoodDrainMultiplier=0.8
> ark_AllowCaveBuildingPvE=false
> ark_DinoCountMultiplier=2
> ark_DisableStructureDecayPvE=false
> ark_PvPStructureDecay=true
> ark_DisableDinoDecayPvE=false
> ark_AllowFlyerCarryPvE=false
> ark_DifficultyOffset=1
> ark_DifficultyValue=17
> ark_NightTimeSpeedScale=1.4
> ark_PvEStructureDecayDestructionPeriod=0
> ark_PreventOfflinePvP=True
> ark_AllowAnyoneBabyImprintCuddle=True
> ark_RCONEnabled=True
> ark_PreventOfflinePvPInterval=900.000000
> ark_OverrideOfficialDifficulty=15.000000
> ark_TheMaxStructuresInRange=10500.000000
> ark_AutoDestroyOldStructuresMultiplier=1.000000
> ark_RaidDinoCharacterFoodDrainMultiplier=1.000000
> ark_EnableExtraStructurePreventionVolumes=True
> ark_ShowFloatingDamageText=True
> ark_PreventDiseases=True
> ark_NonPermanentDiseases=True
> ark_TribeLogDestroyedEnemyStructures=True
> ark_PvEAllowStructuresAtSupplyDrops=False
> ark_AllowHitMarkers=True
> 
> ark_SessionName="HIDDEN"
> 
> ark_Message="Welcome to the Island Extinction Server ! Please respect everyone and everything !"
> ark_Duration=10
> 
> ark_OverrideMaxExperiencePointsPlayer=999999999
> ark_OverrideMaxExperiencePointsDino=999999999
> ark_bServerGameLogEnabled=True
> 
> ark_MaxPlayers=70
>

**Comment by omega117** [comment]
Current Version: v253.86
* Fixed server crash when loading mods in previous build.

**Comment by Evilcious** [comment]
Never mind. Last update fixed it. Closing
