### ISSUE TITLE
gameserversettings.ini mod settings entry

### ISSUE THREAD

**Issue by aspeer06** [FezVrasta/ark-server-tools#708]
So I have some mods that require changes to certain sections of the gameserversettings.ini. If i put it directly in it gets overwritten with each launch/update (as intended I believe). I'm just not sure where to put it?

i.e:
```
[StructuresPlus]
EnableQuickClimb=false
NoFoundationsRequired=false
ElevatorWeightMultiplier=0
DisablePickup=false
DisablePickupWhenDamaged=false
DisableResourcePulling=false
```
Is there a way to get this section to post into the gameserversettings.ini by using the instance config files that I'm just being too dense to realize?

Thanks

**Comment by klightspeed** [comment]
If the server is replacing everything with default settings, that suggests it can't parse the file.

If it is just removing the section, then that suggests that it isn't recognized by the server.

If you really don't want the file overwritten by the server, then try making the file read-only.

The instance file contains parameters passed to the server on its command-line.  arkmanager does not itself modify any game setting files.

**Comment by aspeer06** [comment]
So even during the updates on start it doesn't modify the files because it seems like the time stamps on the files always are updated to the most recent update/start/restart time. I'm only asking for clarification, thanks!

**Comment by klightspeed** [comment]
Wildcard's ARK server always updates the GameUserSettings.ini on startup.  This only occurs when the server is started, either as a result of being started, updated or restarted.

**Comment by aspeer06** [comment]
Making them read-only worked fine, although I'm still confused as to why it only became an issue when I started using arkmanager. Great tool for linux servers running mods. Thanks for the help!
