### ISSUE TITLE
Can't run with installed mods

### ISSUE THREAD

**Issue by Lofiet** [FezVrasta/ark-server-tools#714]
I try running server after I have installed mods and it hangs before listening starts.  When I run with no mods installed or I transfer mods from my ark client the server starts up just fine.

My main.cfg:
arkserverroot="/home/steam/ARK"
mod_branch=Windows
serverMap="TheIsland"
ark_RCONEnabled="True"
ark_RCONPort="32330"
ark_SessionName="******" 
ark_Port="7778"
ark_QueryPort="27015"
ark_ServerPassword="*********"
ark_ServerAdminPassword="*********" 
ark_MaxPlayers="70"
ark_GameModIds="680481868,609425335,719928795,708807240,693416678,764755314,772159312,699984901,771393043,668239751,742077869,764241499,741203089,639841665,670764308,685171762,702828089"
ark_XPMultiplier=10
ark_TamingSpeedMultiplier=25
ark_HarvestAmountMultiplier=25
ark_HarvestHealthMultiplier=25
ark_ResourcesRespawnPeriodMultiplier=25
ark_MapPlayerLocation=true
ark_ServerCrosshair=true
ark_AllowThirdPersonPlayer=true
ark_DifficultyOffset=.5

**Comment by klightspeed** [comment]
Are you running `arkmanager installmods` or `arkmanager update --update-mods` before trying to start the server?

What is the output of one of the above commands?

What is the directory listing of `/home/steam/ARK/ShooterGame/Content/Mods` after installing the mods?

**Comment by Lofiet** [comment]
I have tried both commands. here is the output of arkmanager installmods:
Downloading mod 609425335 ... Mod 609425335 downloaded
Copying files to /home/steam/ARK/ShooterGame/Content/Mods/609425335
      1349  BeaconEnhancer.umap  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.
      1788  LootItemSet_SupplyDrop_Level25_Child_1.uasset  Can't locate Compress/Raw/Zlib.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .).
BEGIN failed--compilation aborted.

listing of /home/steam/ARK/ShooterGame/Content/Mods:
609425335      670764308.mod  699984901      719928795.mod  764755314
609425335.mod  680481868      699984901.mod  741203089      764755314.mod
639841665      680481868.mod  702828089      741203089.mod  771393043
639841665.mod  685171762      702828089.mod  742077869      771393043.mod
668239751      685171762.mod  708807240      742077869.mod  772159312
668239751.mod  693416678      708807240.mod  764241499      772159312.mod
670764308      693416678.mod  719928795      764241499.mod

**Comment by klightspeed** [comment]
Please try installing perl-Compress-Zlib and try again.

If you're using CentOS or RHEL:
```
yum install perl-Compress-Zlib
```

If you're using Debian or Ubuntu, it should already be installed (it's part of `perl-modules`).

**Comment by Lofiet** [comment]
that fixed the problem thank you
