### ISSUE TITLE
installmod update

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#715]
Hey guys,

this morning i've intalled a new mod on a server but when i've installed it, it trigger an update to my other server that have the same mod

is it normal ?

thanks

**Comment by klightspeed** [comment]
https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L2122

`installmod` currently forces SteamCMD to re-validate the mod files, which causes SteamCMD to change the modification time on those mod files, resulting in any successive update runs to detect that the mod has been updated.

We can add e.g. a `--validate` option to `installmod` / `installmods` to turn this on or off.

**Comment by arkfrance** [comment]
the problem is that i use a cron to check up mod update every 15 min, i don't know if (after adding this command to my cron) the cron will be able to make difference with the installmod and the --update-mods

*/15 * * * * /usr/local/bin/arkmanager useconfig pve update --update-mods --warn

**Comment by klightspeed** [comment]
7cc3249 should fix this.

**Comment by arkfrance** [comment]
so is there going to be a command ? or the installmod does't do it anymore ?

**Comment by klightspeed** [comment]
`installmod` will now only forcibly re-download the mod if the `--validate` option is specified.
