### ISSUE TITLE
How can i install "primitive+"

### ISSUE THREAD

**Issue by Taxick** [FezVrasta/ark-server-tools#721]
Hi.

It's not an issue, but I hope you can help me anyway.

How can I install primitive+ DLC on the map "The Center" on my ark server..

I use the last ark server tools, and the game is updated to the last version

Kind regards

Taxick

**Comment by vladdlen** [comment]
Uncomment, or add, ark_TotalConversionMod="111111111" in /etc/arkmanager/instances/whatever-it-is-called.cfg
