### ISSUE TITLE
GAMEUSERSETTINGS.INI overrides on server start

### ISSUE THREAD

**Issue by MrYoshii** [FezVrasta/ark-server-tools#722]
i have the override issue again...
my main.cfg: https://darkside-gaming.at/ark/main.cfg
and my GAMEUSERSETTINGS.INI: https://darkside-gaming.at/ark/GAMEUSERSETTINGS.INI

**Comment by klightspeed** [comment]
What settings are being overridden?

**Comment by MrYoshii** [comment]
it override everything

**Comment by klightspeed** [comment]
What is the command-line logged in arkserver.log?

Does the ARK server still re-write the GameUserSettings.ini if you run the `ShooterGameServer` with the given command-line?

**Comment by MrYoshii** [comment]
the log : `2017-01-22 14:16:17: [main] 2017-01-22 14:16:17: start
2017-01-22 14:16:17: [main] 2017-01-22 14:16:17: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?listen
2017-01-22 14:16:17: [main] 2017-01-22 14:16:17: Server PID: 10714
2017-01-22 14:16:17: [main] [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
2017-01-22 14:16:17: [main] Setting breakpad minidump AppID = 346110
2017-01-22 14:17:05: [main] Using binned.
2017-01-22 14:17:05: [main] 4.5.1-0+UE4 7038 3077 402 6
2017-01-22 14:17:05: [main] CtrlCHandler: Signal=2`

if i start the server with this `#! /bin/bash
./ShooterGameServer TheIsland?listen? -server -log
` it also override the GameUserSettings.ini

and i generate the ini with this tool: https://ini.arkforum.de/index.php?mode=all&lang=de

**Comment by klightspeed** [comment]
Is the ini file you have linked the contents of the GameUserSettings.ini file before or after the ARK server has run?

What happens if you surround the session name with double-quotes (`"`):
```
SessionName="[GER-Only]ALLx10-TAMx14-PVP-ISLAND-NO-MODS]"
```

**Comment by MrYoshii** [comment]
this is after the start: https://darkside-gaming.at/ark/gameusersettingsafter.ini
and this before it overrides https://darkside-gaming.at/ark/GAMEUSERSETTINGS.INI

**Comment by klightspeed** [comment]
If it is writing the default settings, this suggests that it can't parse the ini file.

Since you have confirmed that it occurs even if you run the server directly, this excludes arkmanager.

**Comment by klightspeed** [comment]
It looks like a recent change in Wildcard's ARK server means that `GameUserSettings.ini` must have the following 2 lines somewhere ini it, as otherwise the ARK server will overwrite the file with default settings:

```
[/Script/ShooterGame.ShooterGameUserSettings]
Version=5
```

**Comment by MrYoshii** [comment]
fixt it with `[/Script/ShooterGame.ShooterGameUserSettings]
Version=5`

Thanks for the great support
