### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Gumballz** [FezVrasta/ark-server-tools#725]
Hi sorry for the noob question, im trying to help out a friend installing arkmanager on his server.
He previously had it installed as root, then uninstalled it and is trying to install it as the user instead.

Whenever he runs  `curl -sL http://git.io/vtf5N | bash -s -- --me` as the user he gets an error back,

```
You have requested a user-install.  You probably don't want this.
A user-install will create ~/.config/arkmanager/instances/main.cfg
This config file will override /etc/arkmanager/instances/main.cfg
Add --perform-user-install if you really want this.

```

I have checked that the arkmanager service is no longer running  and also the following do not exist ...
 /usr/local/bin/arkmanager
/usr/local/libexec/arkmanager
/etc/systemd/system/arkmanager.service
/etc/systemd/system/arkmanager@.service
/etc/init.d/arkmanager
/etc/rc.d/init.d/arkmanager
$HOME/bin/arkmanager
$HOME/.local/share/arkmanager

but it still throwing up the error.

Any help would be appreciated.  cheers

**Comment by klightspeed** [comment]
Please read and understand the message printed.
```
You have requested a user-install.  You probably don't want this.
A user-install will create ~/.config/arkmanager/instances/main.cfg
This config file will override /etc/arkmanager/instances/main.cfg
Add --perform-user-install if you really want this.
```

Use `curl -sL http://git.io/vtf5N | bash -s -- --me --perform-user-install` if you really want to perform a user-install.

**Comment by Gumballz** [comment]
Cheers for the fast response, I should have expanded slightly.
I have tried all different combinations of `--perform-user-install` in various places.

```
You have requested a user-install.  You probably don't want this.
A user-install will create ~/.config/arkmanager/instances/main.cfg
This config file will override /etc/arkmanager/instances/main.cfg
Add --perform-user-install if you really want this.
```
Is still being returned, even with your suggestion.

**Comment by klightspeed** [comment]
Sorry - try:
```
curl -sL http://git.io/vtf5N | bash -s -- --me master --perform-user-install
```

Option processing in `netinstall.sh` is a bit lacking.

**Comment by Gumballz** [comment]
👍 

cheers.  worked a treat
