### ISSUE TITLE
How to disable battleeye using arkmanager?

### ISSUE THREAD

**Issue by joebywan** [FezVrasta/ark-server-tools#728]
Is there a flag to use for disabling battleeye using arkmanager?

**Comment by klightspeed** [comment]
See https://steamcommunity.com/app/346110/discussions/0/594820656447032287/ in v253.0

To specify the `-NoBattleye` option, add `arkflag_NoBattleye=` to your instance config

**Comment by joebywan** [comment]
Thanks dude, thought it might be something like that, but it was having issues with ark_NoBattleye.
