### ISSUE TITLE
Any Advice on this ?

### ISSUE THREAD

**Issue by CaspyBXL** [FezVrasta/ark-server-tools#730]
Server Updated to 254.71 ....

Now Server won't stay up

Did the following things
- Reinstalled Ark Files
- Update
- Update Mods
- Launch with no mods
- Launch with new map
- Launch with basic .ini files
- Ark Tools is up to date
- SteamCMD is up to date

The Center and The island server are running fine. (same machine same ini's, same mods)
But SE keeps giving this error not even trying to relaunch the server. Just crash and stop.

ERROR : 

2017-02-04 21:03:09: start
2017-02-04 21:03:09: Running /home/steam/ARKSE/ShooterGame/Binaries/Linux/ShooterGameServer ScorchedEarth_P\?RCONEnabled=True\?RCONPort=XXXX\?Port=XXXX\?bRawSockets=True\?QueryPort=XXXX\?ServerPassword\?ServerAdminPassword=XXXXX\?MaxPlayers=35\?GameModIds=731604991\,630601751\,760880376\,793605978\,554678442\,743217220\,716327557\,566885854\,809346967\,730794403\,600669373\,837850140\,844381171\,566887000\,802922362\,670764308\?AltSaveDirectoryName=clustersaveSE\?OverrideOfficialDifficulty=6.0\?clusterid=XXXX\?listen -USEALLAVAILABLECORES -NoTransferFromFiltering -NoBattlEye -ClusterDirOverride=/home/steam/XXXX
2017-02-04 21:03:09: Server PID: 32246
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
Signal 4 caught.
Signal 11 caught.
Using binned.
4.5.1-0+UE4 7038 3077 402 7
EngineCrashHandler: Signal=4
EngineCrashHandler: Signal=11
/usr/local/bin/arkmanager: line 929: 32246 Aborted                 "$arkserverroot/$arkserverexec" "$arkserveropts" "${arkextraopts[@]}"
2017-02-04 21:03:40: Bad PID ''; expected '32246'
2017-02-04 21:03:40: exited with status 0

Anything to help ?

Thank you in advance for the help !

**Comment by klightspeed** [comment]
Signal 4 is SIGILL, which means that the program attempted to execute an instruction that doesn't exist on the CPU you are running on.

It is not automatically restarting the server because it did not start successfully.  

If you really want it to restart the server even if it doesn't start successfully, then set:
```
arkAlwaysRestartOnCrash=1
```
but be aware that this could result in the server keeping on trying and failing to start until you manually stop it.

**Comment by CaspyBXL** [comment]
I did not change anything on this machine, i run 3 servers in cluster.
2 of them are running fine, any idea of what setting or so cause this problem ?

**Comment by klightspeed** [comment]
Is the server instance that is failing using different mods to the ones that are not failing?

**Comment by CaspyBXL** [comment]
Hello, found the issue after some heavy testing.

- Server had same mods, so that was not the problem.
- Server was the only one with SE and same .ini configs.

Now for some reason when i launch the server with a empty .ini it works.

So it has to be a .ini from a mod or official that changed.

I never found out what its was. just made a new .ini

works !

Ark still fucked me over, but its not arkmanager ofc

things like this on official patch note info makes me wanna hang myself : 

v254.87
* Fixed build issue that was deleting foreign Dinos from savegames. 

GG ! in a cluster system all people lost 50% dino's LOL !
