### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by peterkristel** [FezVrasta/ark-server-tools#735]
How i need to fix this error?

Running command 'run' for instance 'main'
2017-02-13 22:19:35: start
2017-02-13 22:19:35: Running /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland\?RCONEnabled=True\?RCONPort=32330\?SessionName=ARK\ Server\ Tools\?Port=7777\?QueryPort=27015\?ServerPassword\?ServerAdminPassword=keyboardcat\?MaxPlayers=70\?listen
/home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by /home/steam/ARK/ShooterGame/Binaries/Linux/../../../Engine/Binaries/Linux/libsteam_api.so)
2017-02-13 22:19:35: Server PID: 7224
2017-02-13 22:19:40: Bad PID ''; expected '7224'
2017-02-13 22:19:40: exited with status 0

**Comment by klightspeed** [comment]
https://github.com/FezVrasta/ark-server-tools/wiki#lib64libcso6-version-glibc_214-not-found

**Comment by peterkristel** [comment]
Where can i find? GameUserSettings.ini

**Comment by peterkristel** [comment]
and idk i did all the other thing on thad page and still nothing working

**Comment by klightspeed** [comment]
Not having at least glibc 2.14 suggests you are using Debian 7 or older, CentOS / RHEL 6 or older, or Ubuntu 11.10 or older.

You need either a more recent distribution (e.g. Debian 8 [Jessie], CentOS 7, or Ubuntu 12.04 or newer), or to compile a newer version of glibc and libgcc.

**Comment by peterkristel** [comment]
Is there Not a other way I use debian 7.11

**Comment by klightspeed** [comment]
The ARK server requires glibc 2.14

Debian 7 (which was end-of-lifed in April 2016) only comes with glibc 2.13

Therefore either you need to upgrade to Debian 8, or compile glibc 2.14 or newer yourself.

**Comment by peterkristel** [comment]
Idk how

**Comment by klightspeed** [comment]
https://www.debian.org/releases/stable/i386/release-notes/ch-upgrading.en.html

**Comment by peterkristel** [comment]
Is this now good?

**Comment by peterkristel** [comment]
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie

**Comment by klightspeed** [comment]
With your distribution upgraded, ARK should now work.

**Comment by peterkristel** [comment]
Server online :D ty for it!
