### ISSUE TITLE
Installation into NON /home/steam

### ISSUE THREAD

**Issue by CaptSilver** [FezVrasta/ark-server-tools#736]
```
arkmanager install

Running command 'install' for instance 'main'

Creating the ARK server root directory (/home/steam/ARK)

mkdir: cannot create directory ‘/home/steam’: Permission denied

Installing ARK server ... -^C

```
It was supposed to install to /home/dave
I created a symlink from /home/steam to /home/dave and it installs. Haven't done anything else yet. Just an FYI.

**Comment by klightspeed** [comment]
What command did you run to install `arkmanager`?

If you either specified the user `steam` or copied the config without modifications, then it will have used `/home/steam`

**Comment by CaptSilver** [comment]
`curl -sL http://git.io/vtf5N | sudo bash -s dave`

Then I did a default install. The problem was apparently the config file was set to /home/steam even though I installed under the user dave. Just an fyi, it would be nice to have a default install with no modifications to the configuration to the default user. Still figuring out all the config files, but it's working great now!

**Comment by klightspeed** [comment]
0b741f4 should fix the installation of the initial config files.
