### ISSUE TITLE
PlayersExclusiveJoinList.txt  deleted after every update

### ISSUE THREAD

**Issue by sMuve** [FezVrasta/ark-server-tools#737]
Hello everyone!

first i want to thanks the developer of this awesome tool :D Works like a charm!

imo i've only one problem:

I've activated the "check for updates before each restart" and the "make a backup before each update" option (can't tell the exact name, because i'm at work ;( ) and this works fine, but I alsp use arkflag_exclusivejoin="" and after each update (not every restart!) the PlayersExclusiveJoinList.txt in my ShooterGame/Binaries/Linux folder is gone.

I also recognized, that my GameUserSettings.ini and Game.ini is little bit messed up after each update.
The content of each of the ini's in still in it, but without breaks.

Any ideas or do you need any additional infos ?

Thanks in advance!

PS: While the whole backup/update/restart process don't appear any error or warning message.
See below (sry for the long text, but i don't find a spoiler command):

> steam@Ubuntu-1610-yakkety-64-minimal:~$ arkmanager restart
Running command 'restart' for instance 'main'
The server has been stopped
Checking for updates before starting
Checking for update; PID: 8869
Downloading mod 679529026 ... Mod 679529026 downloaded
Downloading mod 715028562 ... Mod 715028562 downloaded
Downloading mod 731604991 ... Mod 731604991 downloaded
Downloading mod 741203089 ... Mod 741203089 downloaded
Downloading mod 764755314 ... Mod 764755314 downloaded
Downloading mod 816908578 ... Mod 816908578 downloaded
Downloading ARK update ... The server is already stopped
\033[0;39m Saved arks directory is /home/steam/arkserver/ShooterGame/Saved/Saved                                                                                                                                                             Arks
 Copying ARK world file (TheVolcano)                               [   OK   ]
 Copying ARK profile files
   76561197960430638.arkprofile                                    [   OK   ]
   76561197961965809.arkprofile                                    [   OK   ]
   76561197969107364.arkprofile                                    [   OK   ]
   76561197970376879.arkprofile                                    [   OK   ]
   76561197970420793.arkprofile                                    [   OK   ]
   76561197973090101.arkprofile                                    [   OK   ]
   76561197976196370.arkprofile                                    [   OK   ]
   76561197976454008.arkprofile                                    [   OK   ]
   76561197990276825.arkprofile                                    [   OK   ]
   76561197998545088.arkprofile                                    [   OK   ]
   76561197998885662.arkprofile                                    [   OK   ]
   76561198004758483.arkprofile                                    [   OK   ]
   76561198006882531.arkprofile                                    [   OK   ]
   76561198018405759.arkprofile                                    [   OK   ]
   76561198018933057.arkprofile                                    [   OK   ]
   76561198039408574.arkprofile                                    [   OK   ]
   76561198043100186.arkprofile                                    [   OK   ]
   76561198067287111.arkprofile                                    [   OK   ]
   76561198075713298.arkprofile                                    [   OK   ]
   76561198076084135.arkprofile                                    [   OK   ]
   76561198086453388.arkprofile                                    [   OK   ]
   76561198091276471.arkprofile                                    [   OK   ]
   76561198120838885.arkprofile                                    [   OK   ]
   76561198126794592.arkprofile                                    [   OK   ]
   76561198128029183.arkprofile                                    [   OK   ]
   76561198153821290.arkprofile                                    [   OK   ]
   76561198165376945.arkprofile                                    [   OK   ]
   76561198201584867.arkprofile                                    [   OK   ]
   76561198241567020.arkprofile                                    [   OK   ]
   76561198247637962.arkprofile                                    [   OK   ]
   76561198312660730.arkprofile                                    [   OK   ]
 Copying ARK tribe files
   1097353625.arktribe                                             [   OK   ]
   1553123759.arktribe                                             [   OK   ]
   1558278930.arktribe                                             [   OK   ]
   1696458313.arktribe                                             [   OK   ]
   1836515334.arktribe                                             [   OK   ]
   1880739971.arktribe                                             [   OK   ]
 Copying ARK tribute tribe files
 Copying GameUserSettings.ini                                      [   OK   ]
 Copying Game.ini                                                  [   OK   ]
 Compressing Backup                                                [   OK   ]
 Created Backup:  2017-02-14_15.06.54.tar.bz2
Applying update from staging directory
Update to 1629936 complete
The server is starting...
The server is now running, and should be up within 10 minutes

**Comment by xangold** [comment]
Also experiencing this issue.
Update cron
`*/5 * * * * /home/steam/updatescript.sh >> /home/steam/updatelog.txt`

Contents of /home/steam/updatescript.sh are

`/usr/local/bin/arkmanager update --warn --saveworld --update-mods @all`

**Comment by sMuve** [comment]
this only creats a cron job and updates ark and all mods  with previous warning and saving for all ark instances or am i wrong ?

**Comment by xangold** [comment]
@sMuve that's probably correct. I'm reading through the script to see if I can spot the bug.

I suspect it's not backing up that file, and it gets erased when steam updates the game (update likely meaning delete old, replace with new)

**Comment by sMuve** [comment]
@xangold is your GameUserSettings.ini and Game.ini also "messed up" like i described in my post ?

**Comment by klightspeed** [comment]
3404df7 and b0b10c8 should prevent any .txt files in `ShooterGame/Binaries/Linux` from being deleted or overwritten.

**Comment by xangold** [comment]
@klightspeed I'm not sure what's happening then. It started occurring for me yesterday after using that cron above. Prior to that I'd been manually doing `arkmanager saveworld && arkmanager restart @all`

**Comment by xangold** [comment]
I had to restore the whitelist manually twice since then, once last night, and once this morning (though not every update did it, as the backup script I had has contents in most of the backups)

**Comment by klightspeed** [comment]
I will be releasing a version with those fixes very shortly.

**Comment by xangold** [comment]
Oh, didn't realize those were not merged, my bad!

**Comment by klightspeed** [comment]
v1.6.18 should fix the deleted PlayerExclusiveJoin.txt issue.

**Comment by sMuve** [comment]
@klightspeed do you have any idea why my GameUserSettings and Game.ini are messed up after the updates ? i tried to paste the content via right-click in putty and i also tried to upload the ini's via ftp, but in both cases the ini don't have any breaks after updates where made by the arkservermanager

**Comment by klightspeed** [comment]
What program are you using to open the ini files?

Does `cat /home/steam/arkserver/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini` show any line breaks?

Note that if you are using non-ascii characters in your MOTD or server name, the server will write the ini file as a UCS16 unicode file.

arkmanager will not itself modify any of the game ini files in `ShooterGame/Saved/Config`

**Comment by sMuve** [comment]
i'm using nano on ubuntu 16.10.

cat shows me the correct breaks atm and my server name is without any non-ascii characters, but in my motd was one.

So i'll check the ini after the next ark patch and if there still is an issue with it i'll let you know.

thanks so much!

**Comment by xangold** [comment]
fwiw I've never had my .ini files change. 

@sMuve if this is fixed, mind closing the issue?

**Comment by sMuve** [comment]
yeah it's ok, because the main problem is solved :)

**Comment by sMuve** [comment]
tested everything and it works fine now 👍
