### ISSUE TITLE
Installing second instance

### ISSUE THREAD

**Issue by azzraN** [FezVrasta/ark-server-tools#740]
Hey,  i made a new config file named as "ScorchedEarth.cfg" in /etc/arkmanager/instances with following written in:

```
# config environment
arkserverroot="/home/steam/ScorchedEarth"                                     # path of your ARK server files (default ~/ARK)

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="ScorchedEarth_P"                                               # server map (default TheIsland)
#serverMapModId="661564024"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
#ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort="32331"                                                # RCON Port
#ark_SessionName="ARK Server Tools"                                  # if your session name needs special characters please use the .ini instead
ark_Port="7778"                                                     # ARK server port (default 7778)
ark_QueryPort="27025"                                               # ARK query port (default 27015)
#ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
#ark_ServerAdminPassword="keyboardcat"                               # ARK server admin password, KEEP IT SAFE!
#ark_MaxPlayers="70"
#ark_GameModIds="487516323,487516324,487516325"                     # Uncomment to specify additional mods by Mod Id separated by commas
#ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name
arkbackupdir="/home/steam/ARK-Backups/ScorchedEarthBackup"
arkStagingDir="/home/steam/ARK-Staging"


# ARK server flags - use arkflag_<optionname>=true
#arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
#arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
arkflag_UseBattlEye=true

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
#arkopt_StructureDestructionTag=DestroySwampSnowStructures
```

but when i want to install a new Server now  with `arkmanager install @ScorchedEarth` it says:

```
arkmanager install @ScorchedEarth
Running command 'install' for instance 'ScorchedEarth'
/etc/arkmanager/instances/ScorchedEarth.cfg: line 3: $'\r': command not found
/etc/arkmanager/instances/ScorchedEarth.cfg: line 22: $'\r': command not found
/etc/arkmanager/instances/ScorchedEarth.cfg: line 23: $'\r': command not found
/etc/arkmanager/instances/ScorchedEarth.cfg: line 28: $'\r': command not found
Installing ARK server ... 
```

after waiting very long time, hes still "installing" 

what i made wrong? I also made da ScorchedEarth dir "/home/steam/ScorchedEarth"

**Comment by klightspeed** [comment]
> /etc/arkmanager/instances/ScorchedEarth.cfg: line 3: $'\r': command not found

This suggests that the config file has DOS newlines.

Try running `sed -i 's/\r//' /etc/arkmanager/instances/ScorchedEarth.cfg` to get rid of those carriage returns.

In order to determine what the program is doing, you can try running:
```
arkmanager install @ScorchedEarth --verbose
```

**Comment by azzraN** [comment]
Hey thanks, now it rly trys to install but now a new problem :/ me, as a linux newbie, don't know what to do.. 

> Connecting anonymously to Steam Public...it
Logged in OK
Waiting for license info...OK
applicationmanager.cpp (1106) : Assertion Failed: Failed to write app state file /home/steam/ScorchedEarth/steamapps/appmanifest_376030.acf
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '376030' state is 0x202 after update job.
applicationmanager.cpp (1106) : Assertion Failed: Failed to write app state file /home/steam/ScorchedEarth/steamapps/appmanifest_376030.acf
applicationmanager.cpp (861) : Assertion Failed: m_bStateChangesSavedToDisk
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...Created shared memory when not owner SteamController_Shared_mem
OK.
"@NoPromptForPassword" = "1"

**Comment by klightspeed** [comment]
Check that the `steam` user has full permission on /home/steam/ScorchedEarth - run as root:
```
chown -R steam:steam /home/steam
```

**Comment by azzraN** [comment]
ah ok, now hes doing it.. but why i need to login as steam user, when i already was logged in as root?

**Comment by klightspeed** [comment]
`arkmanager` should not be run as root, and will drop privileges to the `steam` user if run as root.

**Comment by azzraN** [comment]
ah ok, thx :) told you, i don't have many knowledge about linux and his commands :)
