### ISSUE TITLE
game.ini wiping on server startup

### ISSUE THREAD

**Issue by joebywan** [FezVrasta/ark-server-tools#741]
I'm trying to put settings into game.ini, but it's wiping on server startup.  Any suggestions on what it might be or how I can provide more info to troubleshoot it?

Server is running a single instance using staging folder on ubuntu 14.04 x64 in a vm

**Comment by rlex** [comment]
This happened for me when i had bad game.ini with some errors in params, so game reverted it back to empty.

**Comment by slayit** [comment]
Had the same problem. Start with a clean default config and be sure that your values do exist and are applied correctly. If there is a single not existing parameter or if one has a wrongly assigned value it will revert the *.ini files.

Crosscheck everything you add with: http://ark.gamepedia.com/Server_Configuration

**Comment by joebywan** [comment]
I've checked over it and it all looks fine, anything you can see?

```
BabyCuddleIntervalMultiplier=0.2
BabyCuddleGracePeriodMultiplier=100
BabyCuddleLoseImprintQualitySpeedMultiplier=0.01
BabyImprintingStatScaleMultiplier=10
MatingIntervalMultiplier=0.1
EggHatchSpeedMultiplier=50
BabyMatureSpeedMultiplier=50

NPCReplacements=(FromClassName="MegaScubaPikeT_Male_Character_BP_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaCrossbow_Male_Character_BP_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaCrossbowT_Male_Character_BP_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaPikeT_Male_Character_BP_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaCrossbow_MaleMinion_Character_BP_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaCrossbowT_MaleMinion_Character_BP_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaPikeT_MaleMinion_Character_BP_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaCrossbow_Female_Character_BP_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaCrossbowT_Female_Character_BP_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaPikeT_Female_Character_BP_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaCrossbow_Female_Character_BP_NoNude_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaCrossbowT_Female_Character_BP_NoNude_Core",ToClassName="")
NPCReplacements=(FromClassName="ScubaPikeT_Female_Character_BP_NoNude_Core",ToClassName="")
```

**Comment by rlex** [comment]
Try adding 
```
[/script/shootergame.shootergamemode]
```
On top

**Comment by slayit** [comment]
Just a guess:
`BabyCuddleIntervalMultiplier=0.2
BabyCuddleGracePeriodMultiplier=100.0
BabyCuddleLoseImprintQualitySpeedMultiplier=0.01
BabyImprintingStatScaleMultiplier=10.0
MatingIntervalMultiplier=0.1
EggHatchSpeedMultiplier=50.0
BabyMatureSpeedMultiplier=50.0`

I don't know if it makes a difference if you use integer values instead of float values. Never tried it but I could imagine it.

**Comment by joebywan** [comment]
rlex had it, that line fixed things.  So integer values vs float don't make a difference apparently.
