### ISSUE TITLE
Annunaki mod

### ISSUE THREAD

**Issue by Ragehaters** [FezVrasta/ark-server-tools#742]
I am trying to add the Annunaki mod to the Ark Server Manager. Every single mod downloaded fine except that one and it is the most important one.

**Comment by klightspeed** [comment]
What error are you getting when you attempt to download it?

What is the mod ID?  The only "Annunaki" I can find on the workshop is Annunaki Genesis (Mod ID 538986229)

What output do you get when you try to run `arkmanager installmod <modid> --verbose` where `<modid>` is the mod ID on the workshop?

**Comment by EkoJr** [comment]
I have the mod running on my server just fine.

However, you might want to check your File Permissions & Group/Owner. I had a similar conflict that was solved my correcting perms.
