### ISSUE TITLE
Delete old instance?

### ISSUE THREAD

**Issue by tobi-wankenobi** [FezVrasta/ark-server-tools#743]
Hello,

i´ve changed an instance from ragnarok.cfg to center.cfg. but when i list the instances, i will see @ragnarok and @center. 

how can i delete the instance @ragnarok?

**Comment by klightspeed** [comment]
Check that you don't still have `configfile_ragnarok=...` in either `/etc/arkmanager/arkmanager.cfg` or `~/.arkmanager.cfg`, and that neither `/etc/arkmanager/instances/ragnarok.cfg` nor `~/.config/arkmanager/instances/ragnarok,cfg` exist.

**Comment by tobi-wankenobi** [comment]
Thats it. i´ve changed the path but not the name. thanks a lot...
