### ISSUE TITLE
Can't join server!

### ISSUE THREAD

**Issue by peterkristel** [FezVrasta/ark-server-tools#744]
Running command 'status' for instance 'main'
 Server running:   Yes
 Server listening:   Yes
Unable to query server

ports:

  	4	Query port for Steam's server	27015	27015	
  	5	Game client port	7777	7777	
  	6	Raw UDP socket port (always Ga	7778	7778	
  	7	RCON for remote console server	27020	27020

**Comment by klightspeed** [comment]
`Unable to query server` means the server did not respond to a query on its query port.

The fact that it says `listening: Yes` suggests that it (or something else) has bound to the query port, but isn't responding to any queries.

Do you have `ark_MultiHome` set?

If any other servers are running with the same mods, do they have the same problem?

**Comment by peterkristel** [comment]
i restarted my server [The computer] And it was fixed
