### ISSUE TITLE
How to do a whitelist?

### ISSUE THREAD

**Issue by joebywan** [FezVrasta/ark-server-tools#746]
Trying to implement a whitelist to get around the bug where passworded cluster servers won't let you transfer directly without going to main menu.

Found this link: https://steamcommunity.com/app/346110/discussions/0/523890681404544058/

Talks about using exclusivejoin option & accompanying text file to tell who can/can't join.

considering it was a -exclusivejoin, I figured the right flag was arkopt_exclusivejoin=""

Does this command exist?  If so, am I doing it right?

**Comment by klightspeed** [comment]
If it's just `-exclusivejoin`, then you'll need `arkflag_exclusivejoin=""`

**Comment by rlex** [comment]
arkflag_exclusivejoin=""

Note that PlayersExclusiveJoinList.txt goes to ShooterGame/Binaries/Linux/PlayersExclusiveJoinList.txt and not Saved folder.
