### ISSUE TITLE
Hard Links; File Exists

### ISSUE THREAD

**Issue by Uskaanax** [FezVrasta/ark-server-tools#748]
`cp: cannot create hard link '/home/steam/Hell/ShooterGame/Content/Mods/731604991/./Misc/Elevators/Platforms/Medium/PrimalItemStructure_ElevatorPlatform_Medium.uasset' to '/home/steam/ARK-Staging/Mods/731604991/./Misc/Elevators/Platforms/Medium/PrimalItemStructure_ElevatorPlatform_Medium.uasset': File exists
`
Lately, I'm getting a whole screenful of errors like the above for the noted mod and others. This occurs whether running as the steam user or as root (not my ideal situation, but I did it for testing). This occurs when I run _arkmanager update --update-mods @Hell_. Logging in to the server, I'm getting a warning about making sure all my mods are up to date. Should I just delete the mod manually and reinstall it or is there a better way?

**Comment by klightspeed** [comment]
Does v1.6.21 fix this?

**Comment by Uskaanax** [comment]
You know, it might have. I didn't know there was an update to Arkmanager (updated it a week or two ago) and now that I've updated it, and rerun the command, I'm not seeing the same error. Thanks! I'll have to cron an arkmanager update along with my regular checks for Ark updates.

**Comment by Uskaanax** [comment]
Followup, if I use upgrade-tools, there's no flag to answer yes on the upgrade, it seems? That makes it hard to cron if it's going to wait for user input.

**Comment by klightspeed** [comment]
At the moment, you can use `echo y | /usr/local/bin/arkmanager upgrade-tools`

**Comment by Uskaanax** [comment]
Thanks!
