### ISSUE TITLE
Adjustments arkCpuAffinity arkPriorityBoost

### ISSUE THREAD

**Issue by zazufira** [FezVrasta/ark-server-tools#752]
Hello,
How to use arkCpuAffinity, if I understood for my priority server, I need to write arkCpuAffinity = 1,2 and for others arkCpuAffinity = 3,4 having 4 cores on my server, is that good?

And how to use arkPriorityBoost?
thank you

**Comment by zazufira** [comment]
no answer ?
This is not used? :(

**Comment by klightspeed** [comment]
`arkCpuAffinity` should only need to be used if you need to lock the server to certain CPU cores.
`arkPriorityBoost` should only need to be used if you need to give ARK priority over normal processes (such as your login shell), though in this case background processes should really be given a lower priority.

**Comment by zazufira** [comment]
OK thanks a lot
