### ISSUE TITLE
New USEALLAVAILABLECORES=true ?

### ISSUE THREAD

**Issue by CaspyBXL** [FezVrasta/ark-server-tools#764]
Hello,

Just wanting to inform about something ...

there seems to be a new attribute --> arkflag_USEALLAVAILABLECORES=true

Should it now be : 

-allcores	

SO --> 

arkflag_allcores=true

DESC : deprecated option to utilize all available server cores

I found this info on : 

http://www.ark-survival.net/en/server-command-line-arguments-gameusersettings-ini-configuration/

Thanks for informing me

**Comment by klightspeed** [comment]
That lists both options.  It also lists the `-UseBattlEye` option and not the `-NoBattlEye` option (the former was replaced by the latter when BattlEye was changed from defaulting to off to defaulting to on).

**Comment by CaspyBXL** [comment]
So arkflag_USEALLAVAILABLECORES should still work correct ? No reason why it should not I guess !
