### ISSUE TITLE
bzip2 not included as prerequisite but required for backups

### ISSUE THREAD

**Issue by Hulth** [FezVrasta/ark-server-tools#765]
Compressing Backup tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
                                                                   [   OK   ]

**Comment by klightspeed** [comment]
The documentation has been updated to add bzip2 as a prerequisite for CentOS / RHEL.

**Comment by Sibul2k** [comment]
Please add for Debian based as well. Minimal Server setup does not include bzip2 package IIRC.

**Comment by Hulth** [comment]
Sorry for not adding my OS in the thread, an oversight on my part. Just as Sibul2k says the Minimal Server setup for Debian doesn't include bzip2.
