### ISSUE TITLE
deleting .cfg after update

### ISSUE THREAD

**Issue by postpapa** [FezVrasta/ark-server-tools#767]
after updating our server via cron i realized that 2 of our 3 servers running an older version of ark.
so i started a manual update via "arkmanager update @all --warn --update-mods --saveworld --backup"

it was printing some errors:
![message](https://cloud.githubusercontent.com/assets/22226501/24715638/7b3bc716-1a2c-11e7-9726-aecdbaef2bda.PNG)

the arkIsland.cfg is as ".arkIsland.cfg.swp" on our FTP from 2 days ago and the arkEvent.cfg was deleted completly.

sry for my bad english :(

grettings 

EDIT: i've protected the .cfgs now with "chattr +i"

now ark-server-tools is printing this:

`Applying update from staging directory
rm: remove write-protected reular file 'arkEVENT.cfg'?`

then i hit "n" the server is starting with completed update

**Comment by klightspeed** [comment]
If you want to put the config file into the game server directory, please try putting the config file into the `ShooterGame/Saved` directory in the game server directory.

We can add `*.cfg` files to the list of files that are not removed when they are not present in the staging directory.

**Comment by postpapa** [comment]
thanks, this fixed it!

is it normal that the tool does not show any progress during update process?
before V1.6 it was atleast printing "downloading mod XXX"

**Comment by klightspeed** [comment]
arkmanager will now only download mods that need to be updated, rather than always trying to download every mod.

**Comment by postpapa** [comment]
thanks alot!
