### ISSUE TITLE
arkmanager update does not detect new version

### ISSUE THREAD

**Issue by qfather** [FezVrasta/ark-server-tools#770]
Ark Server Tools v1.6.24
Ubuntu x64 16.04.2 LTS

I'm running single instance server for The Island. I do updates manually, the server is just a testing platform with no active players on it.

Whenever I do `arkmanager update` it always tells me that I'm on the latest version. I have to use the `--force` switch for it to download and apply the update. Here's an example from today.

> steam@pandora:~$ arkmanager update
> Running command 'update' for instance 'main'
> Checking for update; PID: 4142
> Your server is already up to date! The most recent version is 1759392.
> 
> steam@pandora:~$ arkmanager update --force
> Running command 'update' for instance 'main'
> Checking for update; PID: 4208
> Downloading ARK update ... The server has been stopped
> ...
> Applying update from staging directory
> Update to 1775376 complete
> ...

This has happened since day one of this server back in January. It's not a big deal since I can still get updates that way. If anyone has an idea why this might be happening I'm all ears.

**Comment by ImmRanneft** [comment]
Are you sure actual update was installed (I mean there was **real** update)? It seems that ``--force`` just runs update via steamcmd without checking version before update.

**Comment by qfather** [comment]
Yes, there was a real update. See the version numbers I posted.

It says
> Your server is already up to date! The most recent version is 1759392.

when in fact the most recent version was (at the time) 1775376.

I agree, my understanding of `--force` is that it goes and downloads the latest version without checking what's currently installed as well. The download and update run fine when using `--force`.

Here's another example from today. This time I used `checkupdate`.

> steam@pandora:~$ arkmanager checkupdate
Running command 'checkupdate' for instance 'main'
Querying Steam database for latest version...
Current version:  1775376
Available version:  1775376
Your server is up to date!

This is however not correct. There has been another patch today, to v256.6, that neither `checkupdate` nor `update` pick up.

Question is thus, why does arkmanager not see the latest version? Is it cached somewhere? Is it in fact a steamcmd problem? Does steamcmd not report point releases? I can't imagine the latter to be the case.

**Comment by qfather** [comment]
Just to add, the `--validate` option also affects a download and update. The problem that neither `checkupdate` or just `update` see the new version still stands though.

**Comment by klightspeed** [comment]
It sounds like either `steamcmd` is caching it somewhere else, or the `steamcmd_appinfocache` isn't pointing to your steamcmd `appinfo.vdf`, which is usually in `%HOME%/Steam/appcache/appinfo.vdf`

**Comment by qfather** [comment]
Spot on, sir. I should have seen this myself really. My Steam location is `%HOME%/.steam`. Adjusted `arkmanager.cfg` and all is good.

**Comment by Maygus** [comment]
I just had this - it used to work but last 3-4 weeks it's not been doing it unless I do --force.
Checked my CFG and it was pointing to /home/steam/Steam... changed it to /home/steam/.steam/... and now working.

**Comment by klightspeed** [comment]
Do you have the Steam client installed?  On most systems, steamcmd stores its data in `$HOME/Steam`, but on some systems it stores it in `$HOME/.steam`

**Comment by qfather** [comment]
This was the problem on my Ubuntu 16.04.2 LTS x64 server. The client was in `$HOME/.steam`. Edited `arkmanager.cfg` and it's all good.
