### ISSUE TITLE
Ip failover

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#775]
Hi, 
i've bought two ip failover for my two 2 servers

that's the /etc/network/interfaces

auto lo
iface lo inet loopback

auto eth1
iface eth1 inet static
	address 164.132.203.83
	netmask 255.255.255.0
	network 164.132.203.0
	broadcast 164.132.203.255
	gateway 164.132.203.254

iface eth1 inet6 static
	address 2001:41d0:1004:1753::
	netmask 64
	dns-nameservers 2001:41d0:3:163::1
	post-up /sbin/ip -family inet6 route add 2001:41d0:1004:17ff:ff:ff:ff:ff dev eth1
	post-up /sbin/ip -family inet6 route add default via 2001:41d0:1004:17ff:ff:ff:ff:ff
	pre-down /sbin/ip -family inet6 route del default via 2001:41d0:1004:17ff:ff:ff:ff:ff
	pre-down /sbin/ip -family inet6 route del 2001:41d0:1004:17ff:ff:ff:ff:ff dev eth1

auto eth1:1
iface eth1:1 inet static
        address 188.165.55.181
        netmask 255.255.255.255
	    broadcast 188.165.55.181
but when i add a server on steam it works with the main ip but not with the failover ip (188.165.55.181), any clue ?

Is there something to edit in arkmanager ?

Thanks

**Comment by klightspeed** [comment]
What do you have set up to change the route when the primary link goes down?  Both IP addresses are set up on the same physical interface (eth1:1 is a virtual interface on eth1)

**Comment by arkfrance** [comment]
so what do i have to do then ? Thanks

**Comment by klightspeed** [comment]
It looks like you followed OVH's failover IP guide (https://www.ovh.com/us/g2043.configure_a_failover_ip_with_ubuntu) without setting up anything to manage that IP.  Usually a failover IP is meant for if you have a main and backup server, and need to have the IP address accessible at all times.  See https://www.zivtech.com/blog/setting-basic-ip-failover-using-ubuntu-linode for an example.  For a game server, this would require replication between servers so if the main server either fails or maintenance needs to be done to the operating system or hardware, the backup server can be brought up with the latest saved state of the world.

**Comment by klightspeed** [comment]
Also note that the failover IP address needs to be attached to the machine - see https://www.ovh.com/us/publiccloud/guides/g1890.migrating_a_failover_ip

**Comment by arkfrance** [comment]
i used ark__MultiHome=188.165.55.181 and it workd :) Thanks !

**Comment by klightspeed** [comment]
So the second IP was just for the game server, and not for failover purposes?  It sounds like it wasn't working on the second IP without MultiHome because the server was responding on the IP address that has the appropriate routing (the primary IP address), and this didn't match the IP address the client sent the query to.  Using MultiHome explicitly binds to that IP address, which means that it'll only be reachable on the second IP address, and not the first IP address.

**Comment by arkfrance** [comment]
yes,

now i've got this issue 

steam@arkfrance:/root$ arkmanager status
No instances supplied for command status
Do you wish to run this command for all instances?y
Running command 'status' for instance 'scor'
 Server running:   Yes
 Server PID:   32685
 Server listening:   No
 Server build ID:   1778884
Running command 'status' for instance 'cent'
 Server running:   Yes
 Server PID:   32727
 Server listening:   No
 Server build ID:   1778884
Running command 'status' for instance 'island'
 Server running:   Yes
 Server PID:   32758
 Server listening:   No
 Server build ID:   1778884
Running command 'status' for instance 'ext'
 Server running:   Yes
 Server PID:   317
 Server listening:   No
 Server build ID:   1778884

but they are online

**Comment by arkfrance** [comment]
Thanks for the help :)
