### ISSUE TITLE
ArkAutoUpdateOnStart doesn't update mods

### ISSUE THREAD

**Issue by dborg92** [FezVrasta/ark-server-tools#779]
As the issue title suggests, I have the **ArkAutoUpdateOnStart** option set true in my arkmanager.cfg config file and this command does update the main ark files, but not mods. Are there plans to include this feature into this command or add an additional one to update mods as well on startup? 

I've chosen to simply restart my server hardware periodically with arkmanager set to run on startup/ in lieu of using CronJob so having an update mods on startup feature would be useful.

**Comment by klightspeed** [comment]
https://github.com/FezVrasta/ark-server-tools/blob/master/tools/arkmanager#L1146 (added in 4ca8617) should already update mods when `arkAutoUpdateOnStart` is set.  Note that if you have `arkflag_automanagedmods` set, then actually updating the mods will be relegated to the ARK server.

**Comment by klightspeed** [comment]
v1.6.25 should honour this when using the systemd or upstart service file.

**Comment by dborg92** [comment]
Appears to be working as intend now.
