### ISSUE TITLE
I would like to extract arkprofile to JSON

### ISSUE THREAD

**Issue by cokll** [FezVrasta/ark-server-tools#780]
If not, can be customized?

**Comment by klightspeed** [comment]
I think that is beyond the scope of this tool.

**Comment by cokll** [comment]
@klightspeed Yes, so I am willing to pay

**Comment by dahlskebank** [comment]
https://survivetheark.com/index.php?/forums/topic/80750-ark-tools-v040-tools-for-reading-and-manipulating-ark-savegame-files/

That program will let you export almost any info to JSON, including player profiles. I've never tried player profiles myself though, but says it's supported since v0.3.0

**Comment by cokll** [comment]
@dahlskebank This tool is out of date,V257 is not supported

**Comment by dahlskebank** [comment]
ark-tools.jar patched for v257 => https://ufile.io/behuv

works with wild, tamed, tribes and players commands, I don't use the others so I don't know if they works

If you want to do it by yourself, rebuild ark savegame toolkit 0.6.0 with this modification => https://github.com/Qowyn/ark-savegame-toolkit/issues/1

then rebuild ark-tools with the new ark-savegame-toolkit-0.6.0.jar

Have fun guys

Haven't tested myself, but seems positive replies in the thread. Also, how do I quote on when replying on mobile?

**Comment by cokll** [comment]
@dahlskebank Thank you,I have seen before, but I will not compile, so I can not use it.
