### ISSUE TITLE
How to disable server autostart on boot

### ISSUE THREAD

**Issue by ashishkotnala29** [FezVrasta/ark-server-tools#787]
I know this is not an issue with the server-tools but I want to disable server autostart when I boot the machine. I want to start it manually instead of it starting itself automatically. Can anybody help?
I'm using Ubuntu Server 14.04.5 LTS (command line only).

**Comment by klightspeed** [comment]
If it uses systemd:

```
systemctl disable arkmanager.service
```

If it uses sysv-init:

```
update-rc.d -f arkmanager remove
```

**Comment by ashishkotnala29** [comment]
@klightspeed Thank you very much! Since I have Ubuntu 14.04 which doesn't have systemctl the latter command worked for me.

**Comment by ISaneI** [comment]
I used the sysv-init, to stop the server from autostarting, how can i activate it again? Im srry for that dump question..
