### ISSUE TITLE
Installing two (non-cluster) server via ASM

### ISSUE THREAD

**Issue by sMuve** [FezVrasta/ark-server-tools#795]
Hello everybody!

After serveral hours of try and fail i hope for some help.

I installed two ARK Server with one steam user, but two seperate ark dirs.

**i'll use a + instead of a hashtag for lines which are commented out**

My first and main instance uses the following ini's:
_/etc/arkmanager/arkmanager.cfg_ 
including the part for starting a second instance:
```
# alternate configs
# example for config name "ark1":
# configfile_ark1="/path/to/config/file"
configfile_server2="/etc/arkmanager/arkmanager-server2.cfg"
defaultinstance="main"
```

It uses the /etc/arkmanager/instances/main.cfg
```
# config environment
arkserverroot="/home/steam/arkserver"                                     # path of your ARK server files (default ~/ARK)

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
# serverMap="TheIsland"                                               # server map (default TheIsland)
# serverMapModId="469987622"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
# ark_TotalConversionMod="496735411"                                 # Uncomment this to specify a total-conversion mod
# ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort="32020"                                                # RCON Port
# ark_SessionName="ARK Server Tools"                                  # if your session name needs special characters please use the .ini instead
ark_Port="7780"                                                     # ARK server port (default 7778)
ark_QueryPort="27020"                                               # ARK query port (default 27015)
# ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
# ark_ServerAdminPassword="keyboardcat"                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="20"
ark_GameModIds="731604991,741203089,764755314,816908578,880887081,670764308,880871931"                     # Uncomment to specify additional mods by Mod Id separated by commas
# ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

# ARK server flags - use arkflag_<optionname>=true
# arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
# arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
arkflag_NoBattlEye=““
arkflag_exclusivejoin=““
arkflag_logging=““
arkflag_servergamelog=““

# ARK server options - i.e. for -optname=val, use arkopt_optname=val
# arkopt_StructureDestructionTag=DestroySwampSnowStructures
```

My second config will follow in the next post

**Comment by sMuve** [comment]
_**/etc/arkmanager/arkmanager-server2.cfg**_
+config environment
arkserverroot="/home/steam/arkserver2"                                         # path of your ARK server files (default ~/ARK)
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"      # name of ARK server executable
arkbackupdir="/home/steam/arkserver2/ARK-Backups"                              # path to backup directory
arkwarnminutes="60"                                                # number of minutes to warn players when using update --warn
arkautorestartfile="ShooterGame/Saved/.autorestart"                 # path to autorestart file
arkAutoUpdateOnStart="True"                                        # set this to true if you want to always update before startup
arkBackupPreUpdate="True"                                          # set this to true if you want to perform a backup before updating
arkStagingDir="/home/steam/arkserver2/ARK-Staging"
+ARK server options - use ark_<optionname>=<value>
+comment out these values if you want to define them
+inside your GameUserSettings.ini file
serverMap="CrystalIsles"                                               # server map (default TheIsland)
serverMapModId="804312798"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
+ark_RCONEnabled="True"                                            # Enable RCON Protocol
+ark_RCONPort="32021"                                                # RCON Port
+ark_SessionName="[GER-PVE] beastmode @ ARK Eternal"  # if your session name needs special characters please use the .ini instead
+ark_Port="7781"                                                  # ARK server port (default 7778)
+ark_QueryPort="27021"                                               # ARK query port (default 27016)
+ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
+ark_ServerAdminPassword=""                               # ARK server admin password, KEEP IT SAFE!
+ark_MaxPlayers="70"
ark_GameModIds="804312798,878297372,731604991"                     # Uncomment to specify additional mods by Mod Id separated by commas
logdir="/var/log/arktools/arkserver2"                                          # Logs path (default /var/log/arktools)

And the second "main.cfg": **_/etc/arkmanager/instances/server2.cfg_** 
+config environment
arkserverroot="/home/steam/arkserver2"                                     # path of your ARK server files (default ~/ARK)

+ARK server options - use ark_<optionname>=<value>
+comment out these values if you want to define them
+inside your GameUserSettings.ini file
serverMap="CrystalIsles"                                               # server map (default TheIsland)
serverMapModId="804312798"                                         # Uncomment this to specify the Map Mod Id (<fileid> in http://steamcommunity.com/sharedfiles/filedetails/?id=<fileid>)
+ark_TotalConversionMod=""                                 # Uncomment this to specify a total-conversion mod
ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort="32021"                                                # RCON Port
+ark_SessionName="ARK Server Tools"                                  # if your session name needs special characters please use the .ini instead
ark_Port="7781"                                                     # ARK server port (default 7778)
ark_QueryPort="27021"                                               # ARK query port (default 27015)
+ark_ServerPassword=""                                               # ARK server password, empty: no password required to login
+ark_ServerAdminPassword=""                               # ARK server admin password, KEEP IT SAFE!
ark_MaxPlayers="20"
ark_GameModIds="804312798,878297372,731604991"                     # Uncomment to specify additional mods by Mod Id separated by commas
+ark_AltSaveDirectoryName="SotF"                                    # Uncomment to specify a different save directory name

+ARK server flags - use arkflag_<optionname>=true
+arkflag_OnlyAdminRejoinAsSpectator=true                            # Uncomment to only allow admins to rejoin as spectator
+arkflag_DisableDeathSpectator=true                                 # Uncomment to disable players from becoming spectators when they die
arkflag_NoBattlEye=““
arkflag_exclusivejoin=““
arkflag_logging=““
arkflag_servergamelog=““

+ARK server options - i.e. for -optname=val, use arkopt_optname=val
+arkopt_StructureDestructionTag=DestroySwampSnowStructures

## The problem is:
My main server works well, but the server2, don't uses the ports from the server2.cfg, but the standard ports. 

What I already tried:
comment out every port config in the arkmanager-server2,cfg and server2.cfg, due i defined the ports also in the GameUserSettings.ini
comment out every port config in the GameUserSettings,, due i defined the ports in the server2.cfg

Could anybody help me :) ?

**Comment by klightspeed** [comment]
This is not ASM (http://arkservermanager.freeforums.net/) and is not affiliated with that.

The following line in `/etc/arkmanager/arkmanager.cfg`:
```
configfile_server2="/etc/arkmanager/arkmanager-server2.cfg"
```

This will cause arkmanager to ignore `/etc/arkmanager/instances/server2.cfg`
Run `arkmanager list-instances` to see what instance file each instance uses.

**Comment by sMuve** [comment]
My bad :-/ Sorry for the wrong description.

So I removed the line and it works now :-) tyvm klightspeed!

I've an additional question regarding the crontab for several instances.
Can I use the following code for a backup/update of both?
i.e.
#checks for updates every 15 minutes, if there is an update the server will make a backup and if no one is online it will be stopped, updated (incl. Mods) and started
*/15 * * * * /usr/local/bin/arkmanager update @main --safe --ifempty --update-mods --backup
*/15 * * * * /usr/local/bin/arkmanager update @server2 --safe --ifempty --update-mods --backup

#makes a backup every 4 hours
0 0,4,8,12,16,20 * * * /usr/local/bin/arkmanager backup @main
0 0,4,8,12,16,20 * * * /usr/local/bin/arkmanager backup @server2

**Comment by klightspeed** [comment]
You can combine multiple instances in one command.  e.g.:
```
*/15 * * * * /usr/local/bin/arkmanager update @main @server2 --saveworld --ifempty --update-mods --backup
0 */4 * * * /usr/local/bin/arkmanager backup @main @server2
```

**Comment by sMuve** [comment]
Sounds good, but i thought if i'll do it that way, the Server Tools would restart both instances, if ONE of them needs an update

**Comment by klightspeed** [comment]
```
/usr/local/bin/arkmanager update @main @server2 --saveworld --ifempty --update-mods --backup
```
currently executes the `update` command on each instance in turn.  i.e. internally it is equivalent to:
```
/usr/local/bin/arkmanager update @main --saveworld --ifempty --update-mods --backup
/usr/local/bin/arkmanager update @server2 --saveworld --ifempty --update-mods --backup
```

**Comment by sMuve** [comment]
Okay, thank you for your help! All questions are answered, so I'll close the issue
