### ISSUE TITLE
258.6 update won't install

### ISSUE THREAD

**Issue by sMuve** [FezVrasta/ark-server-tools#798]
Hi  there,

the official servers and some other from arkserver.net are already on 258.6.

But we're still on 258.51, even if I run arkmanager update, checkupdate or update --force 
The build is actual regarding to the server tools.

Any idea for troubleshooting ?

Thanks in advance

**Comment by wtfcolt** [comment]
There was either a rollback patch, or a typo when setting the new version numbers. All clients today reverted back
