### ISSUE TITLE
restart sequence error

### ISSUE THREAD

**Issue by postpapa** [FezVrasta/ark-server-tools#802]
ive restarted all of our 3 server with 
`arkmanager restart @ark1 --saveworld`

then the restart sequence is starting. while watching that everything goes fine i saw this:
![unbenannt](https://user-images.githubusercontent.com/22226501/27144330-ad801e20-5131-11e7-89e4-66c47bbcd4f3.PNG)

the message settings are default.

**Comment by klightspeed** [comment]
It looks like you set `arkwarnminutes` to 2
d0265eb should fix this.

**Comment by postpapa** [comment]
no, its just a neckline
![unbenannt](https://user-images.githubusercontent.com/22226501/27158730-c71fd7ee-5168-11e7-9984-1be84acf9566.PNG)

**Comment by klightspeed** [comment]
Does v1.6.26 fix this?

**Comment by postpapa** [comment]
yep, fixed it. sry for the late respond. was unable to chekc it
