### ISSUE TITLE
How to change rates per instance

### ISSUE THREAD

**Issue by 2926max** [FezVrasta/ark-server-tools#805]
Hey im using arkmanager to setup my cluster, I would like to be able to change the rates (taming speed and xp) for one instance. Im using The center with x10 rates and Scorched with x5. Idk how to make this happen as currently they both have the same rates. Thanks in advance

**Comment by klightspeed** [comment]
To do this, you would need to put each instance in its own directory, as these rates are stored in the Game.ini and/or GameUserSettings.ini, which are shared between all instances running from the same directory.

You can have different servers in the cluster run from different directories, and use `ark_ClusterDirOverride` to set the cluster data directory.

**Comment by 2926max** [comment]
Hey thats what ive done thanks for responding. I just duplicated the SE server and then i can use the Gameusersettings.ini to edit each one indiviually. Thx for the response klight
