### ISSUE TITLE
Cron wild dino destroy

### ISSUE THREAD

**Issue by KGM6911** [FezVrasta/ark-server-tools#809]
Hi,
I have two machines running arkmanager for different servers.  I setup the first one and made it auto update and do a daily wild dino destroy.  Everything works fine with it.  I did the wild dino destroy in a .sh file and called it from cron once a day.  I copied the same script and text from the crontab to my second server and made the .sh files executable and the script isn't running.  So then I decided to remove the .sh file and put it all right into cron with my auto update command.  That isn't working either.  

Here's what's in file now:
```
*/30 * * * * /usr/local/bin/arkmanager --cronjob update @island --saveworld --backup --warn --update-mods --args  -- >/dev/null 2>&1
00 4 * * * /usr/local/bin/arkmanager broadcast @island "Daily server reboot and wild dino purge in 3 hours"
30 4 * * * /usr/local/bin/arkmanager broadcast @island "Daily server reboot and wild dino purge in 2.5 hours"
00 5 * * * /usr/local/bin/arkmanager broadcast @island "Daily server reboot and wild dino purge in 2 hours"
30 5 * * * /usr/local/bin/arkmanager broadcast @island "Daily server reboot and wild dino purge in 1.5 hour"
00 6 * * * /usr/local/bin/arkmanager broadcast @island "Daily server reboot and wild dino purge in 1 hour"
30 6 * * * /usr/local/bin/arkmanager broadcast @island "Daily server reboot and wild dino purge in 30 minutes"
45 6 * * * /usr/local/bin/arkmanager broadcast @island "Daily server reboot and wild dino purge in 15 minutes"
50 6 * * * /usr/local/bin/arkmanager broadcast @island "Daily server reboot and wild dino purge in 10 minutes"
55 6 * * * /usr/local/bin/arkmanager broadcast @island "Daily server reboot and wild dino purge in 5 minutes"
58 6 * * * /usr/local/bin/arkmanager broadcast @island "Daily server reboot and wild dino purge in 2 minutes"
58 6 * * * /usr/local/bin/arkmanager backup @island
59 6 * * * /usr/local/bin/arkmanager broadcast @island "Daily server reboot and wild dino purge in 1 minute"
00 7 * * 6 /usr/local/bin/arkmanager rconcmd "DestroyWildDinos" @island
```

My auto update job works fine.  It checks for update and updates.  The broadcasts appear to all be working but the wild dino purge never happens.   I have the @island instance in there because I also have some other instances running on the server.

Any help is appreciated, thanks!

**Comment by klightspeed** [comment]
```
00 7 * * 6 /usr/local/bin/arkmanager rconcmd "DestroyWildDinos" @island
```

The 5th field is the day of week, and so this will only run at 7AM every Saturday.

**Comment by KGM6911** [comment]
I want it to run daily.  Do you see any reason why what I posted wouldn't work?

**Comment by klightspeed** [comment]
Replace `6` with `*` in the 5th column.

**Comment by KGM6911** [comment]
Ahh, I never noticed that 6 there!   Thank you!
