### ISSUE TITLE
Ark Update Server Issue .. well not really (got a temp fix) but still weird

### ISSUE THREAD

**Issue by CaspyBXL** [FezVrasta/ark-server-tools#811]
Hello,

Has something changed for ark since the release of Ragnarok ?
The server says its has the last update until I use the  --force Command.
I'm running the server since 1 Year on this machine, Tools are always updated, never changed what so ever on config.
I have tried using the arkStagingDir or not to use it, it changes nothing, it always says last update is the current one, but when I use --force it does update the server and it does get the newest update.
Has something changed ? Is there a new way of build detection ?

Example what happened between yesterday and today : 
Command 1
- arkmanager checkupdate
--> gave me as anwser --> Current Version 1910343 --> Available Version 1910343
Command 2
- arkmanager update --update-mods --warn --saveworld --backup @session 
--> gave me as anwser ; Checking for update ... Your server is up to date!
Command 3
- arkmanager update --update-mods --force --warn --saveworld --backup @session
--> gave me this : Performing ARK update ... Update to 1914262 ... The server is starting ... The server is running, and should be up within 10 minutes

so all is good, server up to date, but i don"t get that it tells me when using update that it is up to date and that when I force it it does all like it should ...
Is it a problem with SteamCMD ? should I try reinstalling Arkmanager once more ?

Thanks for looking into this.
if more info is needed please ask i'll dig it up and sent you all I can, I have looked into the logs and did not find anything related or relevant.

Greetings,
CaspyBXL

**Comment by klightspeed** [comment]
Please check that the `steamcmd_appinfocache` setting points at your steam `appcache/appinfo.vdf`

**Comment by CaspyBXL** [comment]
Hello,

In my CFG : 
steamcmd_appinfocache="/home/steam/Steam/appcache/appinfo.vdf"
steamcmd_workshoplog="/home/steam/Steam/logs/workshop_log.txt"

However in my Folder there is no appinfo.vdf file !

Screenshot of folder with content

https://s12.postimg.org/ayew02wwt/arkmanagerinfo.png

Greetings thanks for the quick response !

**Comment by klightspeed** [comment]
Some distributions put it into `~/.steam` instead of `~/Steam`
Does `/home/steam/.steam/appcache/appinfo.vdf` exist?

**Comment by CaspyBXL** [comment]
Never mind i'm just frustrated with my crazy fault manipulation of steamCMD ...

So old was

# config SteamCMD
steamcmdroot="/home/steam/steamcmd"
steamcmdexec="steamcmd.sh"
steamcmd_user="steam"
steamcmd_appinfocache="/home/steam/Steam/appcache/appinfo.vdf"
steamcmd_workshoplog="/home/steam/Steam/logs/workshop_log.txt"

......

now i changed it to --> steamcmd root folder --> Steam was the name of the old SteamCMD
I seem to have never changed it in the cfg file for Arkmanager ...

# config SteamCMD
steamcmd_appinfocache="/home/steam/steamcmd/appcache/appinfo.vdf"
steamcmd_workshoplog="/home/steam/steamcmd/logs/workshop_log.txt"


And there in that steamcmd it looks way better LOL

https://s15.postimg.org/ttunz4faz/zzz.png

Thanks for helping, I guess this will help I'll keep an eye on it, but it seems logic that now all will be fine

**Comment by klightspeed** [comment]
It seems random whether steamcmd puts the appinfo cache into `~/Steam`, `~/.steam` or the directory it runs from.  Same with the workshop directory.

**Comment by CaspyBXL** [comment]
Well next ark update I'll check it but now in the cfg
it points to the good folder 
--> steamcmd_appinfocache="/home/steam/steamcmd/appcache/appinfo.vdf"
--> steamcmd_workshoplog="/home/steam/steamcmd/logs/workshop_log.txt"
And not the Empty folder of an old steamCMD that is not even updated since march 2016 LOL, it could still I don't even know how the server got updated by my Cron jobs until now ... My cron litteraly does the same commands as I do but not the --force command. So how did it detect the cache from the other SteamCMD is really a weird thing, but now all should be fine, thanks again for a quick response and great help !
#klightspeed4thewin!

Greetings, Have a nice Sunday !
