### ISSUE TITLE
How to use/Where to config "AllowCrateSpawnsOnTopOfStructures"

### ISSUE THREAD

**Issue by sMuve** [FezVrasta/ark-server-tools#812]
Hello everybody,

the command AllowCrateSpawnsOnTopOfStructures should be use as a launch command for ark server (source: [ark wiki](http://ark.gamepedia.com/253.92)) so I decided to add to my main.cfg

`arkflag_AllowCrateSpawnsOnTopOfStructures=false`

but it doesn't work :-/ The crates are still spawning ON TOP of structures. I want them to fly through structures. It worked on our old g-portal server.

Could anyone help me out with this ?

thx in advance!

**Comment by klightspeed** [comment]
`arkflag_*` is used for dash options without an argument.

Try using `ark_AllowCrateSpawnsOnTopOfStructures=false`

**Comment by sMuve** [comment]
Ok I'll give it a try. 

The difference between `ark_ arkopt_' and 'arkflag_` is not obvious for me, because options like 
`OnlyAdminRejoinAsSpectator=true` and `DisableDeathSpectator=true` are also pre-defined in the main.cfg as `arkflag_`

**Comment by sMuve** [comment]
Okay it works with ark_

@klightspeed Do you know if there's a way to display umlaute correctly in ARK, when I use a broadcast? I write and see the ö in terminal (ubuntu) and can use it via the motd, but if I use it in a broadcast there will be only two question marks instead of the ö

**Comment by klightspeed** [comment]
The ARK server's RCON interface does not support UTF8 or characters outside the 7-bit us-ascii character set.

**Comment by klightspeed** [comment]
> The difference between `ark_` `arkopt_` and `arkflag_` is not obvious for me, because options like
`OnlyAdminRejoinAsSpectator=true` and `DisableDeathSpectator=true` are also pre-defined in the main.cfg as `arkflag_`

Please see <http://ark.gamepedia.com/Server_Configuration>

If the option is a dash option without an argument (e.g. `-automanagedmods`), then it is prefixed with `arkflag_`
If the option is a dash option with an argument (e.g. `-culture=en`), then it is prefixed with `arkopt_`
If the option is part of the settings string (e.g. `?NonPermanentDiseases=true`), then it is prefixed with `ark_`

**Comment by sMuve** [comment]
Ah okay! Now I got it! 

@klightspeed This could maybe an addition for the Ark Server Tools documentation

Thanks again and I'll close thise issue!
