### ISSUE TITLE
Mod updating issues (mismatch, checkmodupdate, etc)

### ISSUE THREAD

**Issue by wtfcolt** [FezVrasta/ark-server-tools#814]
I'm having constant modmismatch issues with any way I try to configure the updates. The only workaround at this point is to upload all my .mod files to the server after using the arkmanager update --updatemods, but right before the server starts to load.

These are my config files trying to use arkmanager to update: https://pastebin.com/rfhcSsp8
-Steam directories have been edited to reflect proper location ( /home/user/.steam/xxx as theres no /Steam/ directory)
-arkflag_automanagedmods="False"
-arkmanager checkmodupdate says every mod needs updated

When I try to use the modmanager by enabling it in the arkmanger.cfg and setting the ModIDS in the [ModInstaller] part of Game.ini, it refuses to load any mods

**Comment by klightspeed** [comment]
What does arkmanager v1.6.28 output when you run `arkmanager checkmodupdate`

Note that `arkflag_automanagedmods=anything`, where `anything` is any non-empty string (such as 'true', 'false', 'foo', '?'), will enable `-automanagedmods`

**Comment by wtfcolt** [comment]
Error: appworkshop_346110.acf not found at /home/wtfcolt/steamcmd/steamapps/workshop

after updating from 1.6.27 to 1.6.28. I've used the new config file, but I don't see anywhere to properly set this directory. It seems it should be /home/wtfcolt/arkmod/steamapps

As for the arkflag you mentioned, I also tried commenting it out.

**Comment by klightspeed** [comment]
Try setting `steamdataroot=/home/wtfcolt/.steam`

**Comment by wtfcolt** [comment]
it's looking for /steamapps/ when the director that's created is /SteamApps/

**Comment by klightspeed** [comment]
Please try v1.6.29 and set `steamworkshopdir=/home/wtfcolt/.steam/steamapps/workshop`

**Comment by wtfcolt** [comment]
> wtfcolt@xxx:/etc/arkmanager$ arkmanager checkmodupdate
> Running command 'checkmodupdate' for instance 'solopvp'
> wtfcolt@xxx:/etc/arkmanager$

Seems to find the file correctly, but returns no output.  I'm headed to work soon and there a good handful of players on the servers on the server right now, but I'll try the update command when I return.

**Comment by wtfcolt** [comment]
> Running command 'checkmodupdate' for instance 'solopvp'
> Mod 731604991 [Structures Plus (S+)] has been updated on the Steam workshop
> Local manifest: 5932538190403107604
> Steam manifest: 9118477970324920536
> wtfcolt@xxx:~/arkmod$ ./update.sh
> Running command 'update' for instance 'solopvp'
> Checking for update; PID: 11848
> Downloading mod 731604991 ... Mod 731604991 downloaded
> Stopping server; reason: update
> The server has been stopped

backup blah blah

> Copying files to /home/wtfcolt/arkmod/ShooterGame/Content/Mods/731604991
> Mod 731604991 updated
> The server is starting...
> The server is now running, and should be up within 10 minutes

Server updated mods properly and is online. No mod mismatch. I love you.

**Comment by wtfcolt** [comment]
Oh, I noticed _checkmodupdate_ is not listed in the help printout when you just type _arkmanager_
