### ISSUE TITLE
arkmanager update: arkmanager: line 70: ./arkmanager: No such file or directory

### ISSUE THREAD

**Issue by cronner** [FezVrasta/ark-server-tools#820]
arkmanager v1.6: Checking for updates...
Getting latest release...
A new version has been released: v1.6.32
* Fix installmod and uninstallmod to accept multiple mod ids
* Switch to http for api.ipify.com
Do you want to upgrade to v1.6.32? [Y/N] y
Getting commit for latest release...
Downloading installer
Running install.sh
Synchronizing state of arkmanager.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable arkmanager
Ark server will now start on boot, if you want to remove this feature run the following line
systemctl disable arkmanager.service
A previous version of ARK Server Tools was detected in your system, your old configuration was not overwritten. You may need to manually update it.
A copy of the new configuration file was included in /etc/arkmanager. Make sure to review any changes and update your config accordingly!
ARK Server Tools successfully upgraded
./arkmanager: line 70: ./arkmanager: No such file or directory

Seems to have updated just fine:
Version: 1.6
Channel: master
Commit: 990d568
Release Tag: v1.6.32
Blob SHA: ed9c34dca7486cc64880bc7cc3eda13ac1da2139

But don't know if that line messed something up?

**Comment by klightspeed** [comment]
This suggests that you set the working directory to `/usr/local/bin`, then ran `./arkmanager`

Line 70 of arkmanager simply re-runs arkmanager to get the new version.

**Comment by cronner** [comment]
ok thanks :)
