### ISSUE TITLE
Feature Request Command to install mods by Collection ID

### ISSUE THREAD

**Issue by DaNeo61** [FezVrasta/ark-server-tools#826]
It would be a nice idea to install not every single mod by type installmod ID it would be nice to installCollection ID to install each mod automaticly 

sorry for grammer english is not my main language

**Comment by klightspeed** [comment]
`arkmanager installmods @instance` will install all configured mods for the instance.

**Comment by DaNeo61** [comment]
saw it already iam so sorry

**Comment by Chris230291** [comment]
Hi. I came across this when searching. Is there any chance of adding support for collections?

**Comment by Chris230291** [comment]
A quick example of how to get a list of mod ids from a collection since steamcmd doesn't appear to support collections directly.

curl -s https://steamcommunity.com/workshop/filedetails/?id=2179512899 | grep -Eo 'sharedfile_[0-9]+' | sort --unique | cut -d_ -f2

**Comment by klightspeed** [comment]
I have implemented it in 86b22b4deaff7abdf0353ee716b651e6e763bd84 using the Steam API https://partner.steamgames.com/doc/webapi/ISteamRemoteStorage#GetCollectionDetails

**Comment by Chris230291** [comment]
Awesome thanks. When will it be available for update?
