### ISSUE TITLE
Where can i add the Startparameter -servergamelog ?

### ISSUE THREAD

**Issue by Provokan** [FezVrasta/ark-server-tools#828]
Hello Guys;

where can i add the Server Startparameter -servergamelog?

**Comment by klightspeed** [comment]
See https://github.com/FezVrasta/ark-server-tools#instance-config-files

Add `arkflag_servergamelog=true` to your instance config (`/etc/arkmanager/instances/main.cfg` if you have only one instance).

**Comment by Provokan** [comment]
thx



closed problem solved ;)
