### ISSUE TITLE
Mods not running

### ISSUE THREAD

**Issue by SouplaMC** [FezVrasta/ark-server-tools#830]
Hello.
I have a problem with activation of mods on my server.
I configure my server like this for main.cfg file:
```
arkserverroot="/home/steam/Ark"

# ARK server options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Ragnarok"
ark_RCONEnabled="True"
ark_RCONPort="32330"
ark_SessionName="PlaineDeVigrid
ark_Port="7778"
ark_QueryPort="27015"
ark_ServerPassword="xxx"
ark_ServerAdminPassword="xxx"
ark_MaxPlayers="70"
ark_GameModIds="543859212,630601751,670764308,731604991,736236773,741203089,756389708,758620733,793605978,880871931,880887081,902548451,919494787,949534127,1086678105,1091147617"
```

And for the arkmanager.cfg file:

```
arkstChannel="master"
install_bindir="/usr/local/bin"
install_libexecdir="/usr/local/libexec/arkmanager"
install_datadir="/usr/local/share/arkmanager"

# config SteamCMD
steamcmdroot="/home/steam/Steam"
steamcmdexec="steamcmd.sh"
steamcmd_user="steam"
steamcmd_appinfocache="/home/steam/Steam/appcache/appinfo.vdf"
steamcmd_workshoplog="/home/steam/Steam/logs/workshop_log.txt"
#steamlogin="anonymous"

# config environment
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"
# Restart cancel chat command
#chatCommandRestartCancel="/cancelupdate"

# ARK server common options - use ark_<optionname>=<value>
# comment out these values if you want to define them
# inside your GameUserSettings.ini file
serverMap="Ragnarok"
ark_RCONEnabled="True"
ark_ServerPassword="XXX"
ark_ServerAdminPassword="XXX"
ark_MaxPlayers="70"
ark_GameModIds="543859212,630601751,670764308,731604991,736236773,741203089,756389708,758620733,793605978,880871931,880887081,902548451,919494787,949534127,1086678105,1091147617"

arkflag_automanagemods=true

# config Service
logdir="/var/log/arktools"                                          # Logs path (default /var/log/arktools)

# steamdb specific
appid=376030                                                        # Linux server App ID
mod_appid=346110                                                    # App ID for mods

# Mod OS Selection
mod_branch=Windows
# Add mod-specific OS selection below:
#mod_branch_496735411=Windows

# alternate configs
# example for config name "ark1":
#configfile_ark1="/path/to/config/file"

defaultinstance="main"
```
I run an arkmanager installmods
The mods are well installed in the directory /home/steam/Ark/ShooterGame/Content/Mods
![mods](https://user-images.githubusercontent.com/8726840/29088892-f2a82f0a-7c7a-11e7-8129-414936dcebd1.jpg)
The server throws it well, but when I try to join it, I get this error message.
![server](https://user-images.githubusercontent.com/8726840/29089088-74d05db8-7c7b-11e7-8296-1d46084173fd.jpg)

I run an arkmanager update --update-mods but I get the same result.

Excuse me for my English. :)
Soupla

**Comment by Provokan** [comment]
Please wrote this in the GameUserSettings.ini 

ActiveMods=Modid,Modid 

and delete the line ark_gameModsId

**Comment by Provokan** [comment]
and Please Update your complete modfiles

**Comment by SouplaMC** [comment]
If I add the line "ActiveMods = Modid, Modid" in GameUserSettings.ini
And I remove the line "ark_gameModsId"
I can not use the command "arkmanager update --update-mods" to update the mods?
I need to manually update from my computer?

**Comment by SouplaMC** [comment]
Should I also add the command in Game.ini
```
[ModInstaller]
ModIDS=
ModIDS=
ModIDS=
```

**Comment by SouplaMC** [comment]
I have the command "arkmanager installmod modid" to install all the mods, it works well. :)

I have a final question, must I add the command in the "Game.ini"
[ModInstaller]
ModIDS =
ModIDS =
ModIDS =
And leave "arkflag_automanagemods = true" in the main.cfg file?

thank you very much for your help Provokan. :)

**Comment by Provokan** [comment]
No u dont Need to Add the MODIDs. 

You Need only to Add the Line in the GameUserSettings

**Comment by Provokan** [comment]
This Thread Gab ne Closed!
