### ISSUE TITLE
restore backup

### ISSUE THREAD

**Issue by boistordu** [FezVrasta/ark-server-tools#831]
Hi,

I've configured a new vm centos 7 with ark and ark-server-tools. 
It didn't seem to have used my backup which I've put in /home/steam/ARK-Backups.
Should I uncompress it somewhere ?

**Comment by klightspeed** [comment]
You should be able to use `tar -xzvf {backupfile.tar.bz2}` to uncompress the backup.  The ini files will need to go into `ShooterGame/Saved/Config/LinuxServer`, and the other files into `ShooterGame/Saved/SavedArks`.

**Comment by boistordu** [comment]
okey let me try it because before I was using docker as previously stated a long time ago so it was an automatic process

**Comment by boistordu** [comment]
seems to have worked I'm gonna test ingame later but the name of the server is correct so seems ok.
thanks
