### ISSUE TITLE
Cronjob

### ISSUE THREAD

**Issue by KGM6911** [FezVrasta/ark-server-tools#832]
Is it possible to have my server do the following on one cron line?

saveworld, warn players about restart, backup, restart server, upon restart issue the forcerespawndinos=true flag?  I've tried numerous entries and I can't get it to work properly.  Was trying to get it to go at 2:15 pm on a specific instance named center

Here's my latest attempt:

15 14 * * * arkflag_forcerespawndinos=true /usr/local/bin/arkmanager restart --saveworld --warn --backup @center

Last night I got it to work once while testing (without the --backup) command in.  I verified and it did work and then I added the --backup command and expected it to run today.  It didn't run.  

I have my server checking for updates every half hour with this: 

*/30 * * * * /usr/local/bin/arkmanager --cronjob update @center --saveworld --backup --warn --update-mods --args  -- >/dev/null 2>&1

I considered doing the following but haven't tried them yet.  I was hoping someone could show me how to properly use the arkflag in cron job.  Are any of these the right way to do it?

15 15 * * * arkflag_forcerespawndinos=true /usr/local/bin/arkmanager --cronjob restart @center --saveworld --backup --warn --args  -- >/dev/null 2>&1

15 15 * * * /usr/local/bin/arkmanager --cronjob restart @center --saveworld --backup --warn --arg="arkflag_forcerespawndinos=true" ->/dev/null 2>&1

Any help is appreciated.  I've been trying to get this to work for a while and it's a real pain rebooting over and over again to see if it works.  Thanks!

**Comment by klightspeed** [comment]
Adding `--arkopt,-forcerespawndinos` should add `-forcerespawndinos` to the options passed to the ARK server.

**Comment by KGM6911** [comment]
Thanks.. I've changed it to this and I'll see if it works.. 

15 15 * * * /usr/local/bin/arkmanager restart --saveworld --warn --backup --arkopt,-forcerespawndinos @center

**Comment by KGM6911** [comment]
Worked great!  Thanks again for all the help you've given me!  Does the project or do you accept donations?
