### ISSUE TITLE
Can i Install a Spezific Build Version from ARK?

### ISSUE THREAD

**Issue by dtmaster79** [FezVrasta/ark-server-tools#836]
Sry for my Bad English. It's google Translate. 

Can I install a particular build version of Ark on the Arkmanager? If so how can I do this?

**Comment by klightspeed** [comment]
SteamCMD provides no way of retrieving a specific build, other than by choosing a branch.  As far as I know, the ARK server has no public branches other than `public`, so the only version available is the latest version.
