### ISSUE TITLE
Loading mod but no mod in game

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#838]
Hi, got a big pb lately, mod not seems to load in game
This is set :
`ark_GameModIds="716327557,572277026,758608778,729352919,564895376,898049820,924933745,793605978,898049820,898024391,1089661918" `                                
i tried to make an arkmanager installmods to re install mods but it still the same...

Before this pb, (when all the mod loaded correctly) everytime someone joined the server, it crashs it
Any clues ?

**Comment by Provokan** [comment]
Please read first the other issue  ->

fix 

Please wrote this in the GameUserSettings.ini

ActiveMods=Modid,Modid

and delete the line ark_gameModsId

**Comment by arkfrance** [comment]
it worked before and with all of my others 7 servers

**Comment by klightspeed** [comment]
Are you defining `ark_GameModIds` anywhere else?

What does `arkmanager printconfig @instance` give you, where `@instance` is your instance name

Do you have `ignoreInstalledMods` set in your config for this server?

**Comment by arkfrance** [comment]
1) Only on others cfg
2) Got no instance, only direct cfg
3) no ignoreInstalledMods set

the mod seems to currupt the savegame

**Comment by arkfrance** [comment]
without this mod, the save is working fine... wipe is the best issue and remove this mod
