### ISSUE TITLE
Fetching latest buildid from SteamCMD still broken

### ISSUE THREAD

**Issue by Atriusftw** [FezVrasta/ark-server-tools#84]
Well, here it is again.

SteamCMD is caching the hell out of stuffs, and takes forever to update its depots.
I'm not sure if there actually is anything we can do about this, but i want to hear your thoughts and suggestions.

Im currently at 180.4, trying to update to .42 via forceupdate - even that says im up to date.
SteamCMD is really running on my nerves :-p

**Comment by FezVrasta** [comment]
same problem, couldn't be a problem of ark devs? they may have forgot the linux build again

**Comment by Atriusftw** [comment]
I just ran some queries against 10 different, random servers on version 180.42 from arkservers.net.
All of them were running Windows.

This actually means that your statement might be correct. If it's the ARK devs i'm not sure, i may aswell be SteamCMD.

**Comment by PhuriousGeorge** [comment]
I was under the impression that both 180.41 and 42 were client fixes and did not impact servers?

**Comment by Atriusftw** [comment]
@PhuriousGeorge They are indeed client side fixes, but clients and servers update accordinly to stay on the same version.

**Comment by Sharkking** [comment]
180.41 and 180.42 are just client side. No need for Server updates. As long as the Client and Server have the same Major Version there are no problems to connect. It might be an idea to write a litte check at https://steamdb.info/app/376030/ and give a formal information about any changes (maybe later ingame to the admin once the RCON is implemented)

**Comment by Atriusftw** [comment]
@Sharkking why do windows server get these updates then?

**Comment by klightspeed** [comment]
@Atriusftw The previous instructions pointed Windows servers to AppID 346110 (the same AppID as the client), and Linux servers to AppID 376030.  It looks like they have now combined the Linux and Windows dedicated servers into the Dedicated Server AppID (376030).

I suspect that most Windows servers still use the client AppID.

**Comment by Atriusftw** [comment]
Hm, ok. This doesnt make any sense. During my tests above, i used appid 376030 on windows (i always have though) and got version 180.42.

**Comment by klightspeed** [comment]
@Atriusftw When the platform type is set to windows, steamcmd is downloading depot 346111 (the same one as is used for the client).  When the platform type is set to linux, steamcmd is downloading depot 376031.

Also, despite the Windows server and client having different build IDs (674165 vs 675833), they have the same manifest ID (5072350820543184467).

**Comment by Atriusftw** [comment]
@klightspeed I see. Thank you for explaining. It seems like this issue only happens with minor updates.
181.0 just dropped and i immediately got it upon running checkupdate.
