### ISSUE TITLE
Feature Request - upgrade tools from commit

### ISSUE THREAD

**Issue by Evilcious** [FezVrasta/ark-server-tools#841]
Hi, 
I see that you had implemented a new command (list-mods) but when I try to upgrade the tools, I can't have this feature as it seems it's not tagged or marked as released. 

Would it be possible to have like "beta upgrades"? 

Thanks :)

**Comment by klightspeed** [comment]
Set `arkstUnstable=true` in `arkmanager.cfg` to always upgrade to the latest commit.

**Comment by Evilcious** [comment]
Thanks a lot!
