### ISSUE TITLE
arkmanager update doesn't work. only force

### ISSUE THREAD

**Issue by Evilcious** [FezVrasta/ark-server-tools#843]
Hi,

It's been a few days since I noticed "arkmnager update @instance" didn't work anymore at least for the ARK version. Didn't see for the mods yet.
```
root@server:/home/steam# arkmanager update @ragnarok
Running command 'update' for instance 'ragnarok'
Checking for update; PID: 14417
Your server is already up to date! The most recent version is **2079896**.
root@server:/home/steam# arkmanager update --force @scorched
Running command 'update' for instance 'scorched'
Checking for update; PID: 14562
Downloading ARK update ... Stopping server; reason: update
                           The server has been stopped
Applying update from staging directory
Update to **2087178** complete
The server is starting...
The server is now running, and should be up within 10 minutes
root@root:/home/steam#
```
Note that ragnarok instance indicates version **2079896** doesn't need update but adding --force to scorched downloads and apply version **2087178**

The commands are done like 30 seconds apart and if I want the update to download and apply, I need to add --force. 

I can't do it with crontabes as it will restart the servers each time the crontab runs.

Any idea what could be the problem ?

**Comment by klightspeed** [comment]
Please check that your `steamcmd_appinfocache` points to the most recent `appcache/appinfo.vdf`.

Note that installing `steam` or `steamcmd` as a distribution package can affect where this is put.

At the same time, you might want to check that `steamcmd_workshoplog` points to the most recent `workshop_log.txt` file, and set `steamdataroot` to the active steam data directory (e.g. `/home/steam/.steam` or `/home/steam/Steam`)

**Comment by Evilcious** [comment]
Found it :) Thanks a lot for your reactivity !
