### ISSUE TITLE
Some sort of webinterface possible?

### ISSUE THREAD

**Issue by tenten36** [FezVrasta/ark-server-tools#85]
I think I read something about a small web interface for remote management some time ago, are there any plans for a feature like that? Or is it better to wait for RCON first?

**Comment by Atriusftw** [comment]
This repository mainly focuses on the bash scripts for linux, but some of us have been talking about a Node.js wrap up of some sort.

I personally have thrown together something simple in bootstrap for now (http://atrius.net/~random/ark-web.PNG)

The code is ugly - main focus of the website is simple and fast remote management.

**Comment by Sispheor** [comment]
I think I will start something with Django when RCON become available.

**Comment by tenten36** [comment]
Sounds great, thanks for the feedback
