### ISSUE TITLE
100% SWAP

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#850]
Hi,
does anyone know how all the swap can be used with 2 arkmanager sessions ?

<img width="1100" alt="capture d ecran 2017-09-11 a 18 38 26" src="https://user-images.githubusercontent.com/13471860/30304064-6eee97f6-9720-11e7-9f01-68339b7d0de8.png">

**Comment by klightspeed** [comment]
What do you have `vm.swappiness` set to in `sysctl.conf`?

Since you have lots of memory, you can set it to a low value (such as 10) - see https://en.wikipedia.org/wiki/Swappiness

**Comment by arkfrance** [comment]
now it's set to vm.swappiness = 10
do i have to restart the server ?

**Comment by klightspeed** [comment]
You can use `sysctl -w vm.swappiness=10` to set the swappiness immediately.

> Is it normal that i have all these same process ?

It looks like your `top` is listing all threads.

**Comment by arkfrance** [comment]
The swap seems to still the same

**Comment by klightspeed** [comment]
You may need to turn swap off and back on to swap in everything.
```
swapoff -a
swapon -a
```

Note that the `swapoff` command will not return until everything is swapped back in.

**Comment by arkfrance** [comment]
Worked ! Thanks again !
