### ISSUE TITLE
warnseconds: command not found

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#854]
```
steam@arkfrancepve:/root$ arkmanager useconfig ragna restart --warn
Running command 'restart' for instance 'ragna'
/usr/local/bin/arkmanager: line 1596: warnseconds: command not found
```
arkwarnminutes="1"

When it set to 1 min, it says that the server will reboot in 120 sec instead of 60 sec

any clue ?

Thanks

**Comment by klightspeed** [comment]
There was an error in the 1 minute -> 60 second case.  This has now been fixed in master.

**Comment by arkfrance** [comment]
Thanks for this, can you have a look into : https://github.com/FezVrasta/ark-server-tools/issues/852

Thanks
