### ISSUE TITLE
MultiHome issue

### ISSUE THREAD

**Issue by arkfrance** [FezVrasta/ark-server-tools#855]
Hi, when i use : ark_MultiHome=188.165.55.178 (my ip failover)
the server can't boot
when i don't use it everything is fine...
any clue ?

**Comment by klightspeed** [comment]
Is the IP address you are trying to use set up on an interface on the machine?

**Comment by arkfrance** [comment]
I've re installed the machine
![capture](https://user-images.githubusercontent.com/13471860/30560110-263f0012-9cb7-11e7-8c72-3e3bd839a9c7.JPG)

**Comment by klightspeed** [comment]
If you look at the output of `ifconfig` or `ip address`, is that IP address set up on any of the interfaces?

**Comment by arkfrance** [comment]
i've just re installed my machine on another OS, is there something to do ? On the OVH panel, it seems to be good to me

**Comment by klightspeed** [comment]
Your game server's failure to start suggests that the IP address is not configured on any interfaces.  If the "failover" ip addresses are set up on the same interface as the main IP address, then you will need to configure that IP address on a virtual interface attached to that physical interface.

Refer to your distribution documentation on how to persistently configure such a virtual interface (e.g. eth0:1).

**Comment by arkfrance** [comment]
The second one is working without any config, it was auto set to the machine and the main ip, i've got the same config on the two different machine (nano /etc/network/interfaces)
