### ISSUE TITLE
Can't create or load PGArk map

### ISSUE THREAD

**Issue by Lodur89** [FezVrasta/ark-server-tools#859]
Hi there, 
I'm somehow not able to create or even load procedurally created ark maps with ark server tools. 
Things in the configs I changed ->

arkmanager.cfg
- Outcommented all lines I didn't need in there (especially serverMap="TheIsland" in this case)

pgark-instance.cfg
- arkserverroot="/my/path/blah"
- ServerMap="PGARK"
- [....]

game.ini
- Removed default MapName
- PGMapName=ARKproc
- PGTerrainPropertiesString=[Generated directly by ARK via local game and copied in here]
- [...]

GameUserSettings.ini
- serverMap=PGARK   (added this here, too after it didn't work in my instances config)
- [...]

Each time I'm trying to start a fresh game with the changes made above, it still creates TheIsland. In none of the config files there is any reference to TheIsland left.
Also, if I'm copying a PGmap I created locally to the server and adapt the save-name etc, the PGmap isn't loaded -- instead a clean TheIsland is created (Edit: or loaded if one exists).

Is there something I've missed or isn't this (otherwise great) tool replacing TheIsland by PGARK in the startup string?

Thanks in advance :)

**Comment by Lodur89** [comment]
Oh wow... I just tried it again with serverMap="PGARK" in the arkmanager.cfg aaaand it works. (I wonder what I messed up the first time I've had it that way *scratching my head)
But still: If I'm trying to get the same result by putting it in my instances config or the GameUserSettings it's not working.

**Comment by klightspeed** [comment]
> pgark-instance.cfg
> 
> * arkserverroot="/my/path/blah"
> * ServerMap="PGARK"
> * [....]

`serverMap` is case sensitive.

 > GameUserSettings.ini
> 
> * serverMap=PGARK (added this here, too after it didn't work in my instances config)
> * [...]

`serverMap` is an arkmanager option, not an ARK server option.

Given that the instance file name is `pgark-instance.cfg`, this would require either using `@pgark-instance` as the instance specifier, or linking the instance file under an instance name in arkmanager.cfg - e.g. `configfile_pgark=/etc/arkmanager/instances/pgark-instance.cfg`

**Comment by Lodur89** [comment]
Oh, I didn't even realised that I wrote `ServerMap` instead of `serverMap`. Writing it the correct way actually works ^^
(And that it's an arkmanager option but not a server option is also good to know, if one is too stupid to get it 👍 )

One more question: Since now I used @instanceName because I only run one server at a time, but set multiple up. How does the linking effect the start up parameter? I guess, if I'm using `arkmanager start`, all linked configs with the respective servers are going to be loaded? So in my case, linking them in the `arkmanager.cfg` wouldn't be recommended, right?

**Comment by klightspeed** [comment]
When I said "link", it's just specifying what instance config file is used when you specify a particular instance name.  Starting one instance will start only that instance.  Specifying a main instance in arkmanager.cfg simply means that that instance will be acted upon when no instance name is specified.

**Comment by Lodur89** [comment]
Aaah, alright. I think I got it. And I'm sorry for those questions, but well... Knowledge is power :'D
Thanks again and have a nice weekend! :)
