### ISSUE TITLE
Failed to start Daemon to start ark server on restart

### ISSUE THREAD

**Issue by dschensen** [FezVrasta/ark-server-tools#86]
This is the output of my syslog. 
--------------------------------------------------------------------------------------------------
systemd[1]: arkmanager.service: control process exited, code=exited status=5

kernel: [    0.000000]   00000-9FFFF write-back
kernel: [    0.000000]   A0000-BFFFF uncachable

systemd[1]: Failed to start Daemon to start ark server.
systemd[1]: Unit arkmanager.service entered failed state.

kernel: [    0.000000]   C0000-FFFFF write-protect

---------------------------------------------------------------------------------------------------
i am running Debian 8.
everything else is working normal. after "arkmanager start" the server gets started und after some time the server is online and in the ark Server list..
But after reboot of the server the daemon has a problem with starting the ark server after boot.
any idea ?

**Comment by klightspeed** [comment]
Exit code 5 means that arkmanager does not exist in the location it was supposed to be installed, or it is not executable.

The cause appears to be that we missed modifying the $DAEMON variable in $EXECPREFIX/libexec/arkmanager/arkmanager.init during install.
