### ISSUE TITLE
Cluster Port issues

### ISSUE THREAD

**Issue by Gamewalker** [FezVrasta/ark-server-tools#860]
Hello,

I setup 3 instances with ports: 7778, 7779, 7780.
Is I start my servers with arkmanager start @all, the ps aux shows the following:
```
steam    16420 30.2 15.7 7176708 5171672 pts/0 Sl   16:43   1:44 /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer Ragnarok?RCONEnabled=True?RCONPort=32330?SessionName=Nameless-Gaming - Ragnarok?Port=7777...
steam    16456 26.2 14.9 6907200 4915080 pts/0 Sl   16:43   1:30 /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer TheIsland?RCONEnabled=True?RCONPort=32331?SessionName=Nameless-Gaming - Island?Port=7778...
steam    16479 20.1 12.3 6993988 4064240 pts/0 Sl   16:43   1:09 /home/steam/ARK/ShooterGame/Binaries/Linux/ShooterGameServer ScorchedEarth_P?RCONEnabled=True?RCONPort=32332?SessionName=Nameless-Gaming - Scorched Earth?Port=7779...
```

if I configure the ports: 7777, 7778, 7779
its using 7776, 7777, 7778,

why is it always decrementing my ports? I had really strange problems with server not showing

my configs looks all like this (with+1 port)
```
# config environment
arkserverroot="/home/steam/ARK"                                     # path of your ARK server files (default ~/ARK)

serverMap="Ragnarok"                                               # server map (default TheIsland)

ark_RCONEnabled="True"                                              # Enable RCON Protocol
ark_RCONPort="32330"                                                # RCON Port
ark_SessionName="Nameless-Gaming - Ragnarok"                                  # if your session name needs special characters please use the .ini instead
ark_Port="7777"                                                     # ARK server port (default 7778)
ark_QueryPort="27015"                                               # ARK query port (default 27015)

ark_AltSaveDirectoryName="SavedArks"                                    # Uncomment to specify a different save directory name

arkautorestartfile=ShooterGame/Saved/.autostart-ragnarok
arkflag_NoTransferFromFiltering=true
arkopt_clusterid=ng1337
```

**Comment by klightspeed** [comment]
The game port (the port the game listens on) is always 1 greater than the `Port` parameter passed to the ARK server.  The port number specified in the arkmanager config is the port you want the server to listen on.

**Comment by Gamewalker** [comment]
So I should use +2 on every port?

**Comment by klightspeed** [comment]
Specifying `Port=7777` in the arkmanager config will pass `Port=7776` to the ARK server, which will cause it to listen to port 7777.

**Comment by Gamewalker** [comment]
I had
cfg1:
ark_Port="7778"

cfg2:
ark_Port="7779"

cfg3:
ark_Port="7780"

and only 2 of my 3 instanced showed in the server browser. Thats why I started investigating

**Comment by klightspeed** [comment]
Not showing up in the server browser usually means that either the server hasn't advertised itself to the Steam Master server, or the server isn't answering on its QueryPort.

Do all of the servers show up properly when you use `arkmanager status @all`?

**Comment by Gamewalker** [comment]
yes they did and https://arkservers.net/server/ did too but steam server list and ark didnt show the server. If I started connecting via steam parameter, ark found the server but displayed errors like: couldnt query server or something like this. (and every instance had different ports). I changed it to 7777, 7778, 7779 and now its working (I cant figure out why)
