### ISSUE TITLE
per-compress-zlib

### ISSUE THREAD

**Issue by Hr46ph** [FezVrasta/ark-server-tools#861]
Hello.

I'd like to give this tool a try for my dedicated server but I am running Arch Linux and there is no perl-compress-zlib.

Is there a way to get this tool working on Arch?

Thanks!

**Comment by Lihis** [comment]
It's available in AUR.

**Comment by klightspeed** [comment]
`perl-compress-zlib` is in AUR

https://aur.archlinux.org/packages/perl-compress-zlib/

**Comment by Hr46ph** [comment]
Yeh I should have mentioned that sorry. Its orphaned and it doesn't work. For quite some time actually. No idea what that solution is thats provided to be honest.

**Comment by klightspeed** [comment]
Are you able to use `cpan` to install `Compress::Zlib`?

**Comment by Hr46ph** [comment]
Sorry never heard of cpan. I've done a search with yaourt (AUR) and I get a lot of hits, but a grep on compress or zlib gives no returns.

Needless to say I'm a total noob with perl.

**Comment by klightspeed** [comment]
The `cpan` command is usually included with perl.

Running `cpan` without any arguments should start it interactively, where the first time it is run it will bootstrap its environment.

Note that you will need gcc and some other devel tools and libraries installed to install from cpan.

```
$ cpan
Loading internal null logger. Install Log::Log4perl for logging messages
Sorry, we have to rerun the configuration dialog for CPAN.pm due to
some missing parameters. Configuration will be written to
 <</home/klightspeed/.cpan/CPAN/MyConfig.pm>>


CPAN.pm requires configuration, but most of it can be done automatically.
If you answer 'no' below, you will enter an interactive dialog for each
configuration option instead.

Would you like to configure as much as possible automatically? [yes]

Use of uninitialized value $what in concatenation (.) or string at /usr/lib64/perl5/5.24.1/App/Cpan.pm line 644, <STDIN> line 1.
 <install_help>

Warning: You do not have write permission for Perl library directories.

To install modules, you need to configure a local Perl library directory or
escalate your privileges.  CPAN can help you by bootstrapping the local::lib
module or by configuring itself to use 'sudo' (if available).  You may also
resolve this problem manually if you need to customize your setup.

What approach do you want?  (Choose 'local::lib', 'sudo' or 'manual')
 [local::lib]


Autoconfiguration complete.

Attempting to bootstrap local::lib...

...

You can re-run configuration any time with 'o conf init' in the CPAN shell
Terminal does not support AddHistory.

cpan shell -- CPAN exploration and modules installation (v2.1101)
Enter 'h' for help.

cpan[1]> install Compress::Zlib
Running install for module 'Compress::Zlib'
Fetching with LWP:
...
```

**Comment by Hr46ph** [comment]
`cpan[1]> install Compress:Zlib
Fetching with HTTP::Tiny:
http://www.cpan.org/authors/01mailrc.txt.gz
Reading '/home/user/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with HTTP::Tiny:
http://www.cpan.org/modules/02packages.details.txt.gz
Reading '/home/user/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Sun, 01 Oct 2017 06:29:03 GMT
  HTTP::Date not available
............................................................................DONE
Fetching with HTTP::Tiny:
http://www.cpan.org/modules/03modlist.data.gz
Reading '/home/user/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /home/user/.cpan/Metadata
Compress::Zlib is up to date (2.074).

cpan[2]>`

Was it _really_ that simple? 

I will look at running the tool later today, but it looks promising. I am getting really tired of updating everything manually each update :).

Thanks for the help! I'll let you know when it works (or not :P).

👍

**Comment by klightspeed** [comment]
That looks almost as if you already have Compress::Zlib installed.

**Comment by Hr46ph** [comment]
That's what I was thinking ... I always assumed it wasn't installed as that package wouldn't install so I never tried to just run the tool. Turns out its working just fine (doh!).

Anyway, now I need to figure out how to adapt my already running server in /home/steam/servers/servername and is starting with a systemd unit file. I'm reading the wiki, but not a lot of time the coming 2 weeks since I'm studying for my RHCE.

Thanks again for the help!
