### ISSUE TITLE
Second instance not working correct

### ISSUE THREAD

**Issue by GermanY1337** [FezVrasta/ark-server-tools#862]
I made a second ARK server and it is not shown in the favourits list (In-Game). In Steam Server Browser is always only one server listed, the first one or the second one (if you refresh it multiple times), never both. They are both on different ports and if it helps, multihome is in both configs enabled. Servers run on the same machine with the same IP, they only have a different port. What could I do?

**Comment by klightspeed** [comment]
That sounds more like a problem where the Steam browser is hitting a limit where it starts to randomly cull entries that live on the same IP.

Do both servers show up on their arkservers.net link (as printed by `arkmanager status @instancename`)?

**Comment by MrRoman2k4** [comment]
Yes, both servers show up on their arkservers.net link ( http://prntscr.com/gsud03 ). They are on the other hand not shown in ARK itself, only one of them - the one that is shown in the Steam Servers List.
