### ISSUE TITLE
Update Scripts

### ISSUE THREAD

**Issue by darkcloud784** [FezVrasta/ark-server-tools#865]
I recommend adding a way to update arkmanager through a command. This way it can be automated easier and faster for many people.

**Comment by klightspeed** [comment]
`arkmanager upgrade`

**Comment by darkcloud784** [comment]
@klightspeed Was this just added as its a valid command in my version I updated last week.

**Comment by klightspeed** [comment]
Sorry, it's `arkmanager upgrade-tools`.  This does require a `y` input if you want it to do it automatically.
