### ISSUE TITLE
New Install problem

### ISSUE THREAD

**Issue by KGM6911** [FezVrasta/ark-server-tools#872]
Just setup a server running Ubuntu 17.10.  Also tried it with three prior versions of ubuntu and all are giving me the same problem.  Here's what I'm getting.   Any idea what I've done wrong?   I've set this up on other servers in the past with no problem.

Here's what I get when I try and install an instance.

arkmanager install @annpve
[  ERROR  ]     Your SteamCMD root seems not valid.
[  ERROR  ]     Your SteamCMD exec could not be found.
Running command 'install' for instance 'annpve'
[  ERROR  ]     Your SteamCMD root seems not valid.
[  ERROR  ]     Your SteamCMD exec could not be found.
/usr/local/bin/arkmanager: line 1341: cd: /home/steam/steamcmd: Not a directory
Installing ARK servermkdir: cannot create directory ‘/home/steam/steamcmd’: File exists
tar (child): /home/steam/steamcmd/steamcmd_linux.tar.gz: Cannot open: Not a directory
tar (child): Error is not recoverable: exiting now

gzip: stdin: unexpected end of file
tar: Child returned status 2
tar: Error is not recoverable: exiting now
 ... -/usr/local/bin/arkmanager: line 495: /home/steam/steamcmd/steamcmd.sh: Not a directory

**Comment by klightspeed** [comment]
What is `/home/steam/steamcmd`?

`steamcmdroot` needs to be the directory in which steamcmd has been extracted.

**Comment by KGM6911** [comment]
That was how it installed.  I followed your directions as well as the ones on the steam page that you have linked in the instructions.  I found that it put it in another spot so I changed the text in arkmanager.cfg and now it's working.  Thanks for your help!
