### ISSUE TITLE
AST not updating correctly

### ISSUE THREAD

**Issue by kzarius** [FezVrasta/ark-server-tools#875]
While trying to update to the newest commits, I've hit some problems.

Basically I've been trying to get AST to run the halloween beta. I've set `arkstUnstable=true` in the cfg, ran `arkmanager update-tools`, it's detected a hotfix, downloads it, and installs 1.6.33 instead of the current commit. I've re-installed via curl to 1.6.34 and repeated to it installing 1.6.33 again. It states that AST installs correctly, but it just continually downgrades to 1.6.33 instead of the most recent commits (Which include the extraopts variable)

**Comment by klightspeed** [comment]
That suggests you have arkmanager installed in multiple locations.

What does `type arkmanager` give you?  Does that path match the expected path (set in `/etc/arkmanager/arkmanager.cfg` or `~/.arkmanager.cfg`)?

**Comment by kzarius** [comment]
ah. Yes I did install it locally `arkmanager is hashed (/usr/local/bin/arkmanager)`
But now that you mention it, I do recall installing it on the superuser before, and decided to keep it to a separate user acct. I'll try to wipe it from the su and update.

**Comment by kzarius** [comment]
I'm going to rack this up to my inexperience in linux, as I was unable to wipe the other instances and other larger problems took shape on my install, forcing a reinstall and I have yet to experience the problem again.
