### ISSUE TITLE
Not able to update to 273.58 ?

### ISSUE THREAD

**Issue by JimmyMEG1** [FezVrasta/ark-server-tools#876]
Hi all,

Currently we have our server in 273.56 (halloween) but now we cannot upgrade to post-halloween : 273.58 ?
There is no errors, just saying that our server is up to date.

Any idea or clue to help me ? Thx,

**Comment by klightspeed** [comment]
The halloween branch was last updated 26 hours ago, while the public branch was updated 9 hours ago.  See https://steamdb.info/app/376030/depots/

To update to 273.58, you will need to comment out or remove both the `appbranch` and `steamcmd_appextraopts` options in your config.

**Comment by JimmyMEG1** [comment]
Thanks. I probably mess something as I had done this.

with : arkmanager checkupdate .. I got : 

Current version:  2247869
Available version:  2251307

But, when i launch : arkmanager update // or : arkmanager update --force, I got : 
Checking for update; PID: 4741
The server is already stopped
Performing ARK update ... Update to 2247869 complete

??

**Comment by klightspeed** [comment]
BuildID 2247869 suggests you are still on the halloween beta.  Make sure `steamcmd_appextraopts` is not set (or is commented out), and try `arkmanager update --validate`

**Comment by JimmyMEG1** [comment]
Still not..

Here is my /etc/arkmanager/arkmanager.cfg : 

[arkmanager.cfg.txt](https://github.com/FezVrasta/ark-server-tools/files/1437510/arkmanager.cfg.txt)

And my /etc/arkmanager/instances/main.cfg : 

[main.cfg.txt](https://github.com/FezVrasta/ark-server-tools/files/1437521/main.cfg.txt)

**Comment by klightspeed** [comment]
What do you get when you run `arkmanager update --validate --verbose`

**Comment by JimmyMEG1** [comment]
I got this : 

Running command 'update' for instance 'main'
Checking for update; PID: 5130
The server is already stopped
Performing ARK updateExecuting /home/steam/steamcmd/steamcmd.sh +@NoPromptForPassword 1 +login anonymous +force_install_dir /home/steam/ARK +app_update 376030 validate +quit
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 1.65 (97639316 / 5934393892)
 Update state (0x5) validating, progress: 10.43 (619202887 / 5934393892)
 Update state (0x5) validating, progress: 17.98 (1067036637 / 5934393892)
 Update state (0x5) validating, progress: 29.23 (1734877167 / 5934393892)
 Update state (0x5) validating, progress: 40.77 (2419187385 / 5934393892)
 Update state (0x5) validating, progress: 49.00 (2907875623 / 5934393892)
 Update state (0x5) validating, progress: 51.67 (3066442215 / 5934393892)
 Update state (0x5) validating, progress: 53.87 (3196574566 / 5934393892)
 Update state (0x5) validating, progress: 55.13 (3271693248 / 5934393892)
 Update state (0x5) validating, progress: 58.58 (3476195117 / 5934393892)
 Update state (0x5) validating, progress: 61.61 (3656468301 / 5934393892)
 Update state (0x5) validating, progress: 65.14 (3865886967 / 5934393892)
 Update state (0x5) validating, progress: 67.77 (4021824658 / 5934393892)
 Update state (0x5) validating, progress: 71.16 (4223139665 / 5934393892)
 Update state (0x5) validating, progress: 74.89 (4444187265 / 5934393892)
 Update state (0x5) validating, progress: 78.50 (4658722294 / 5934393892)
 Update state (0x5) validating, progress: 79.98 (4746115749 / 5934393892)
 Update state (0x5) validating, progress: 81.56 (4840242979 / 5934393892)
 Update state (0x5) validating, progress: 83.40 (4949168145 / 5934393892)
 Update state (0x5) validating, progress: 85.29 (5061230841 / 5934393892)
 Update state (0x5) validating, progress: 86.46 (5130727129 / 5934393892)
 Update state (0x5) validating, progress: 88.31 (5240546756 / 5934393892)
 Update state (0x5) validating, progress: 95.29 (5654837764 / 5934393892)
 Update state (0x5) validating, progress: 98.84 (5865356980 / 5934393892)
Success! App '376030' fully installed.
Update to 2247869 complete

**Comment by klightspeed** [comment]
You might need to use `steamcmd_appextraopts="-beta public"` to switch back to the `public` branch.  Either that, or remove `/home/steam/ARK/steamapps/appmanifest_376030.acf`

**Comment by JimmyMEG1** [comment]
Yes that is ! Thanks a million.
