### ISSUE TITLE
MultiHome Variable needed although only one interface / ip exists

### ISSUE THREAD

**Issue by Lenny-Hai** [FezVrasta/ark-server-tools#878]
Hi,

i am a little confused because arkmanager shows "Server online: no".
After a few trieouts i found an inconsistency in your code:

`getMultiHome()` {
  getArkServerSetting "MultiHome" `"${1:-127.0.0.1}"`

Bash ist not that what i use normaly, but i think this means if the result ist empty than it returns 127.0.0.1" So whenever the MultiHome variable is not set, it returns the localhost address.
Because of this the code in the "else" section will never be usesd:

`  if [ -n "$(getMultiHome "")" ]; then
    publicip="$(curl --interface "$(getMultiHome)" -s http://api.ipify.org/)"
  else
    publicip="$(curl -s http://api.ipify.org/)"
  fi`

I can fix the "error" using the MultiHome-Option even though i don't need it.

Kindly regards,

Sven

**Comment by klightspeed** [comment]
Please let me know if commit 6da2c49 fixes this.

**Comment by KGM6911** [comment]
It fixed it for my servers.  Thanks!

**Comment by Lenny-Hai** [comment]
Hi,

now this works, but now there is a "Unable to query server" within the output:

```
arkmanager  useconfig ark1 status
Running command 'status' for instance 'ark1'
 Server running:   Yes
 Server PID:   5691
 Server listening:   Yes
Unable to query server
 Server online:   Yes
 ARKServers link:   http://arkservers.net/server/5.9.106.222:27017
 Server build ID:   2256420
 Server version:   273.62
```

**Comment by klightspeed** [comment]
`Unable to query server` means that even though MultiHome is apparently not set, the server did not respond in a timely manner to a query on the query port when trying to get the server name and number of players online.

Do you have any iptables rules that might affect this - e.g. not having a rule that allows connections on the loopback interface (which would affect any local services that connect on the loopback interface).

**Comment by Lenny-Hai** [comment]
Hmmmm know it works... without any changes....
