### ISSUE TITLE
hosting clusters on same machine issue

### ISSUE THREAD

**Issue by warlordkn** [FezVrasta/ark-server-tools#879]
i believe i have the server running as i desired but i cant seem to transfer between instances.
when in the server browser i can see both servers but once i join one and goto a oblisk attempting to make the jump to the other it does not appear.

did i miss a step?

and since i dont have any browsers installed on the server machine i have to go thru all these convoluted ways to show my code.  the easiest is for me to just post a picture.

my code https://imgur.com/eSChxz6

**Comment by KGM6911** [comment]
Here's what I have:  I notice a few differences.  The clusterid I use isn't in quotes and I have true for my notransferfromfiltering.   I run multiple clusters and I just change the clusterid to keep them seperate. 
 Here's what I have:

arkflag_NoTransferFromFiltering=true
arkopt_ClusterDirOverride=/home/steam/
arkopt_clusterid=ExtinctionCluster

**Comment by warlordkn** [comment]
thank you for the attempt but it did not seem to fix the issue.

i noticed digging around the folders that the cluster folder is in one of the instances instead of where i typed it to.  i think that may be a culprit but i am not fluent enough in linux to understand what is causing it.

i do have my instances installed in their own folders.  is that how yours is set up?

**Comment by KGM6911** [comment]
Yes, I have each instance in it's own folder.  Sorry, I'm not so great with linux either.

**Comment by warlordkn** [comment]
ok i mamaged to solve it  - sort of

since i could not get it to acknowledge the cluster directory and it seemed to have its own built in anyway i ended up running all my servers from the same installation and just changing their alt save directory so they wouldn't interfere with each other.

ALSO it was because i was trying to play this from my lan that i was not able to see (something the devs need to fix) the other servers in my cluster.
so in order to be able to join from within i had to use my vpn.  not the best solution but until the devs implement the ability to see lan servers in the transfer screen this is a workaround

**Comment by warlordkn** [comment]
not sure how to mark this as solved
