### ISSUE TITLE
syntax error when trying to install ark-server-tools

### ISSUE THREAD

**Issue by Hype365** [FezVrasta/ark-server-tools#893]
I type
`curl -sL http://git.io/vtf5n | sudo bash -s steam`
replacing steam with my linux user I have setup for my server and i get
`bash: line 7: syntax error near unexpected token 'newline'
bash: line 7: '<!DOCTYPE html>'`

Not sure what is going wrong...

**Comment by klightspeed** [comment]
The URL is case sensitive.  `http://git.io/vtf5N` leads to the netinstaller, while `http://git.io/vtf5n` leads to a comparison on some other github repo that was url-shortened around the same time.

**Comment by Hype365** [comment]
At work at the moment but I will try that when I get home and report back. Thanks :)

**Comment by Hype365** [comment]
Tried when I got home and sure enough, worked like a charm lol That's what I get for trying to do it half asleep the first time. Now to just figure out how to set this up to manage multiple instances :D Thanks for your help @klightspeed
