### ISSUE TITLE
Aberration Update Failure

### ISSUE THREAD

**Issue by PittiDoe** [FezVrasta/ark-server-tools#895]
Hey i get following error when i try to update ark to Aberration:

command: arkmanager update --validate

 Copying ARK world file (Aberration)  [ FAILED ]

what can i do to update my server?

**Comment by klightspeed** [comment]
That suggests you have auto-backup on update enabled, and the world .ark filename doesn't match the map name specified in your config.

This shouldn't cause update to fail - it just means the backup made during the update won't be complete.

**Comment by PittiDoe** [comment]
Thanks for the help, map name was wrong
