### ISSUE TITLE
Clarification on a few config options...

### ISSUE THREAD

**Issue by Hype365** [FezVrasta/ark-server-tools#902]
I've seen several options for configs that I'm not sure how to use and would like more clarification please. The options I'm interested in are:
arkCpuAffinity
msgWarnReason 
msgTimeMinutes 
msgTimeSeconds 
msgReasonUpdateApp 
msgReasonUpdateMod 
msgReasonUpdateAppMod 
msgReasonRestart 
msgReasonShutdown

**Comment by postpapa** [comment]
https://github.com/FezVrasta/ark-server-tools/issues/766
