### ISSUE TITLE
Arkmanager falsely claims server is up to date

### ISSUE THREAD

**Issue by N-Rico** [FezVrasta/ark-server-tools#903]
Hi,

I recently started running a new Ark (Aberration) instance on my server with an hourly cronjob to run 'arkmanager update --warn --saveworld --update-mods'. But often the server doesn't update, when I run 'arkmanager checkupdate' it says the server is up to date, even though I know that isn't true:

```
Running command 'checkupdate' for instance 'aberration'
Querying Steam database for latest version...
Current version:  2392386
Available version:  2392386
Your server is up to date!
```

Only when I run arkmanager update with the --force flag (or probably with --validate too) it will install the update.

I suspect some cache is corrupted or something, but I can't figure out what it is. (I'm not using a staging dir)

Please advise!

Thanks,
Enrico

**Comment by klightspeed** [comment]
Please check that `steamcmd_appinfocache` points to the `appinfo.vdf` file
in `~/Steam/appcache`

**Comment by N-Rico** [comment]
While troubleshooting this issue earlier this morning I noticed that folder didn't exist, created it manually, restart arkmanager daemon, but folder remains empty. (I have already run an update --force after creating the folder)

**Comment by N-Rico** [comment]
hm, wait...found the appinfo.vdf in a different folder, I will change the path in arkmanager.cfg to that folder and see if that works!

**Comment by BoiseComputer** [comment]
I had the exact same issue. Fixed the path and it found the update.

**Comment by N-Rico** [comment]
Yes, fixed it for me too!
