### ISSUE TITLE
Can't change steamworkshop directory

### ISSUE THREAD

**Issue by DonArtis** [FezVrasta/ark-server-tools#908]
Hi,

I have the problem that I can´t change the `steamworkshopdir`
The tool is always downloading it to  `/home/arkbod/Steam/steamapps/workshop` if I make a mod update 

In my `arkmanger.cfg` is this set:
```
# config SteamCMD
steamcmdroot="/home/arkbod/steamcmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamdataroot="/home/arkbod/steamcmd"
steamcmd_user="arkbod"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/arkbod/steamcmd/appcache/appinfo.vdf"      # cache of the appinfo command
steamcmd_workshoplog="/home/arkbod/steamcmd/logs/workshop_log.txt"
steamworkshopdir="/home/arkbod/steamcmd/steamapps/workshop"
#steamlogin="anonymous"                                             # Uncomment this to specify steam login instead of using anonymous login

```
and my config for my `main` server:
```
# config SteamCMD
steamcmdroot="/home/arkbod/steamcmd"                                 # path of your steamcmd instance
steamcmdexec="steamcmd.sh"                                          # name of steamcmd executable
steamdataroot="/home/arkbod/steamcmd"
steamcmd_user="arkbod"                                               # name of the system user who own steamcmd folder
steamcmd_appinfocache="/home/arkbod/steamcmd/appcache/appinfo.vdf"      # cache of the appinfo command
steamcmd_workshoplog="/home/arkbod/steamcmd/logs/workshop_log.txt"
steamworkshopdir="/home/arkbod/steamcmd/steamapps/workshop"
#steamlogin="anonymous"                                             # Uncomment this to specify steam login instead of using anonymous login
```

If I delete the `/home/arkbod/Steam` directory and I run the command `arkmanager checkmodupdate @main` the output is this:
```
Running command 'checkmodupdate' for instance 'main'
Error: /home/arkbod/Steam/steamapps/workshop does not exist
```

Thanks in advance!

**Comment by klightspeed** [comment]
What version are you using?

Does `/home/arkbod/steamcmd/steamapps/workshop` in fact exist?

Note that the `steamcmd_appinfocache`, `steamcmd_workshoplog`, `steamdataroot` and `steamworkshopdir` do not influence where `steamcmd` stores the downloaded mods, but rather are used to indicate to `arkmanager` where to find those things.

If `$steamworkshopdir` does not exist, then arkmanager will try several directories (including `$steamdataroot/steamapps/workshop`), and will default to `$HOME/Steam/steamapps/workshop` if none of the directories exist.

**Comment by DonArtis** [comment]
Thanks for the fast response

I'm using version `v1.6.38`

No they don't

I added them and now it´s working

thanks for your help
