### ISSUE TITLE
LowLevelFatalError, Signal 11 caught

### ISSUE THREAD

**Issue by JakeDEvans** [FezVrasta/ark-server-tools#91]
steam@hostname:~$ cat /var/log/arktools/arkserver.log
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
LowLevelFatalError [File:F:\UE4\UnrealEngine\Projects\ShooterGame\Source\ShooterGame\Private\ShooterGameMode.cpp] [Line: 457]
Can't load world save file, and can't find a valid backup.
Signal 11 caught.

**Comment by klightspeed** [comment]
Is the ARK server saved arks directory (`${arkserverroot}/ShooterGame/Saved/SavedArks`) writable by the user running the ARK server?

Is the TheIsland.ark file there valid?  If it isn't, is there another recently-created .ark file there you can replace it with?

**Comment by JakeDEvans** [comment]
it's a fresh install, I don't have an TheIsland.ark file.

**Comment by FrostByghte** [comment]
From reading around the net, this appears to be an issue with the latest 183 version.  If you are running a fresh server or hosting a new local game you are hosed.  You need a save file to get things going.  Anyone have a saved file available for download?  :)

**Comment by Atriusftw** [comment]
@JakeDEvans How much RAM does the box have allocated?

**Comment by JakeDEvans** [comment]
found and uploaded a map manually and seems to be running well, @Atriusftw thanks for your help.
