### ISSUE TITLE
Trying to set up Multiple Instances

### ISSUE THREAD

**Issue by Stray-Fenris** [FezVrasta/ark-server-tools#910]
Hello there. I have a question regarding multiple instances or changing Maps on servers. But let me start at the beginning.
I host a small dedicated Server for my Crew(At most 7 people online, commonly three) and we played on the Island until now. However, we wanted to use Ragnarok as our Main Map from now on and have another Instance(Or another solution) for Ragnarok, while keeping the Island accessable(Preferably starting it only, when we want to play there, since the serverpc is a bit older). We would never have two Instances active at the same time, but i can't seem to get it to work, so i hoped, someone could help me. Right now, i got Ark installed twice and each Instance has a different serverroot, but they both start at the same time

**Comment by JamesDonaldChilds** [comment]
arkmanager start @instancename

**Comment by Stray-Fenris** [comment]
arkmanager start @main
Running command 'start' for instance 'main'
The server is starting...
The server is now running, and should be up within 10 minutes


arkmanager status @all
Running command 'status' for instance 'main'
 Server running:   Yes 
 Server PID:   *****
 Server listening:   Yes 
Server Name: Goettersterben - 
Players: 0 / 10
Active Players: 0
 Server online:   Yes 
 ARKServers link:   http://arkservers.net/server/**********
 Server build ID:   ********
 Server version:   276.42 
Running command 'status' for instance 'Island'
 Server running:   No 
 Server listening:   Yes 
Server Name: Goettersterben - (v276.42)
Players: 0 / 10
Active Players: 0
 Server online:   Yes 
 ARKServers link:   http://arkservers.net/server/******** 
 Server build ID:   ********
 Server version:   276.42 

As you can see, both are loaded, but the server is visible in neither Lan nor unofficial
So yeah, i probably configurated something completly wrong. The ***** is what i erased.

**Comment by klightspeed** [comment]
Are the configs using different ports?

**Comment by Stray-Fenris** [comment]
@klightspeed Nope. I thought i didn't have to, as i would never start them at the same time.

**Comment by klightspeed** [comment]
The fact that it shows the arkservers.net link suggests that the server is in the Steam master server list.

If you access the arkservers.net link, and add the server, is it able to see any information on the server?

Also, are the ports forwarded on your router / modem / gateway to your server?

**Comment by Stray-Fenris** [comment]
@klightspeed I had the Island Map working completly fine before, so the ports are working correctly. I see the informations about the server on the weblink, but if i try to find it ingame in the arkserver list, it isn't shown. Neither in the Lan, nor in the unofficial. It could be under some other name than the one that is shown, but i doubt that.

Doo you think it would help if i share my Instances? Maybe the error is easier findable there?(Naturally an altered version with removed passwords and such)

**Comment by JamesDonaldChilds** [comment]
Just make sure your ports are different, if they are the same this will definitely cause issues. The fact that it was working before is very weird to me. Feel free to post the instances, but I would simply try changing the ports first. Just increment each by 1 or 2 on the second server and you should be fine.

**Comment by SinisterSole** [comment]
@Stray-Fenris
Your output of arkmanager status all suggests that main is running but island is not. The ports need to be different even if you do not run them at the same time (saves on confusion)
Configure these in the instance files. The following is how mine are setup and I run three servers from a linux box at home. I also enabled rawsockets

Island
ark_RCONPort="32331"                                                
ark_bRawSockets="True"
ark_Port="8801"                                                     
ark_QueryPort="27016"  

Scorched
ark_RCONPort="32332"                                                
ark_bRawSockets="True"
ark_Port="8803"                                                     
ark_QueryPort="27017" 

Center
ark_RCONPort="32330"                                                
ark_bRawSockets="True"
ark_Port="8799"                                                     
ark_QueryPort="27015"  

Ports that need forwarded to your server are:
27015-27021 TCP,UDP
8788-8803 TCP,UDP
32330-32332 TCP,UDP

**Comment by Stray-Fenris** [comment]
@SinisterSole Are you sure that i have to open that many ports, especially from 8788-8803?

**Comment by SinisterSole** [comment]
@Stray-Fenris
Those are the minimum ports I have open to run 3 servers. If you are worried about security, I recall scanning those ports for specific protocols and was returned unknown. Remember that you have to reserve 2 ports on each protocol (rcon, port and query). So my setup above "Center" for example says to open port 8799 but shows up on arkservers as port 8798.

In you case, you will only need 2/3 the ports open as mine.

**Comment by SinisterSole** [comment]
To be more specific abut the port forwarding:
Those ports are opened in your router to your linux box ip only.

**Comment by Stray-Fenris** [comment]
@SinisterSole  But whopping 15 ports in ther 8k range? or is that is spelling error?
Also, Main doesn't work even when there are now no other instances working on it's ports. So i don't know if there should be some other setting i need.

What should be in these AltSavedirectories? Maybe theres the problem

**Comment by SinisterSole** [comment]
@Stray-Fenris
I am thinking that the AltSavedirectories is a new feature that I do not have enabled. It is nowhere in my setup. 

As for the ports, the ark_Port uses 2 per instance but need to be different ports per instance.
ie. 'main'- ark_Port="8801" and 'Island'- ark_Port="8803"

Can you please share your current instance settings as I have above to rule out port issues in Linux? Then we can move on from there.

**Comment by Stray-Fenris** [comment]
@SinisterSole 
[Instances.zip](https://github.com/FezVrasta/ark-server-tools/files/1628693/Instances.zip)

**Comment by SinisterSole** [comment]
@Stray-Fenris
Now we are getting somewhere. Ports look good but
All the instances are calling on the same server path arkserverroot="/home/ark/ARK"
I would copy the contents from /home/ark/ARK to /home/ark/ARK1 and /home/ark/ARK2, fix their permissions and edit the  arkserverroot= in each instance to the correct path
ie.  
arkserverroot="/home/ark/ARK" for 'main'
arkserverroot="/home/ark/ARK1" for 'Island'
arkserverroot="/home/ark/ARK2" for 'Aberration'

**Comment by Stray-Fenris** [comment]
@So i need to install ARK three times? Last time i did that, everything stopped working. For that reason i use the AltSavedirectories. When i browsed on this site, i saw that you can used them to have the same Arkserverroot, as long as the settings are in a different Save directory.

**Comment by SinisterSole** [comment]
@Stray-Fenris
Also, I would remove the ark_AltSaveDirectoryName= in each instance. The arkserverroot= already specifies the save directory, assuming that is the function of the argument.

**Comment by SinisterSole** [comment]
@Stray-Fenris
No, just copy the files to different locations and edit the instance to reflect each different location

**Comment by Stray-Fenris** [comment]
@SinisterSole okay damn it to Hell.
I set my server up again completly and then take your advices into account. I check back in, when i'm done with that to report if it worked.

**Comment by SinisterSole** [comment]
@Stray-Fenris
Roger that. It really is easier then it sounds :)

**Comment by Stray-Fenris** [comment]
@SinisterSole Yeah but i had installed Ark twice at the same time and probably have some fragmented stuff on this machine, also it doesn't work. Also, to get the other Instances to work, i need to give the guy who manages our Router the ports and he's asleep right now.
By the by, i don't need to open all ports on the Router, do i? Which can stay closed?

**Comment by SinisterSole** [comment]
@Stray-Fenris
Only the ports you are going to use for your servers.
If it was in your instance.cfg file, it needs opened.

**Comment by Stray-Fenris** [comment]
@JamesDonaldChilds  @klightspeed  @SinisterSole 
So just before i start re-setiing the serve up, there is no other way to changed map without setting up different instances and opening different ports for each instance? The Routermanager hates opening ports, so i would like to avoid that, if possible.

**Comment by SinisterSole** [comment]
@Stray-Fenris
If all you want to do is change the map then you can do that in the instance.cfg file but I have heard that it gets messy when you have to restore a world. Just change serverMap="TheCenter" in main.cfg to serverMap="TheIsland" and so on for the other worlds. The server will be slow to start as it is creating the world you specify but will get faster loading once it is created.

**Comment by Stray-Fenris** [comment]
@SinisterSole Less change the Map but being able to return to the maps depending on the mood. But when we tried before, the Characters would get messy. Instances seemed like a good way, but if we have them in the same Folder, the characters are on all maps, and if i use the Altsavedirectory, i still need to open multiple ports, making "our network more vulnerable". You see my problem?

**Comment by SinisterSole** [comment]
I can relate to the "more open ports mean more vulnerable network" idea. 
General consensus of the ports being opened by Ark Survival (excluding 7777 and 7778) are that they are bound to their specific protocol. 
There might be other ways to run multiple servers from limited ports but in the end telling a friend in game to "hang on and I will start the other server for you to join" is awesome.
I am not sure how relevant these are but check them out.
https://github.com/FezVrasta/ark-server-tools/issues/201
https://github.com/FezVrasta/ark-server-tools/issues/441

**Comment by Stray-Fenris** [comment]
@SinisterSole  I have read them before, but must have overread the copying of the Arkdircetory. Also, as they were kinda old, i was not sure how much of it was still correct.

As we all play as a group together, we would either migrate as a whole group or i would go back alone to transfer dinos.

But it seems, the best way would really to take your way to set up the Instances. I will fiddle a around a bit more, before i resort to re-setup. Maybe i get it working my way. I'll report back, as soon as i'm done

**Comment by Stray-Fenris** [comment]
@JamesDonaldChilds  @klightspeed  @SinisterSole 
Thanks for all you help. I just purged everything regarding the arkmanager and ark, after re-installing and copying my Gamesettings, Instances and arkmanager.cfg it worked suprisingly well. Probably destroyed some data with my fidling before, but now it works just fine. So i'm gonna close the thread now. Thanks again for your Patience and Help.
