### ISSUE TITLE
Not All Servers Instances Starting

### ISSUE THREAD

**Issue by ryan1161** [FezVrasta/ark-server-tools#913]
When my all my servers shutdown to check for updates only 3 - 5 come back online and it's random ever time not the same server coming up it's like it depends on which loads the fastest. 

Anyway just thing of a feature request maybe have custom option for sleep timer between starting the servers so that way resource don't max.

**Comment by CaspyBXL** [comment]
Seems like you did not configure PAM correctly, the maximum number of read and write files can be too heavy for 5 instances to load on your machine, this however depends of the machine/linux you are using.
I have a Hexacore Server with 6 instances(2 x 3 clusters) and each server uses 2 of my 12 threads when booting instances. works fine but load is indeed heavy if all go offline and online at once.

In my old config however I used the crontab to manage reboots and updates.

Tested on CentOS7 and Debian8 while editing /etc/crontab

Something like this : 

#reboots@8am and 4pm
0 8,16 * * * arkadmin /usr/local/bin/arkmanager restart --warn --saveworld @center
#reboots@9am and 17pm
0 9,17 * * * arkadmin /usr/local/bin/arkmanager restart --warn --saveworld @Ragnarok
#reboots@10am and 18pm
0 10,18 * * * arkadmin /usr/local/bin/arkmanager restart --warn --saveworld @island

#update check/everyhour@15withbackup@12
12 * * * * arkadmin /usr/local/bin/arkmanager backup @center
15 * * * * arkadmin /usr/local/bin/arkmanager update --update-mods --warn --saveworld @center

#update check/everyhour@48withbackup@42
42 * * * * arkadmin /usr/local/bin/arkmanager backup @ragnarok
48 * * * * arkadmin /usr/local/bin/arkmanager update --update-mods --warn --saveworld @ragnarok

#update check/everyhour@35withbackup@28
28 * * * * arkadmin /usr/local/bin/arkmanager backup @island
35 * * * * arkadmin /usr/local/bin/arkmanager update --update-mods --warn --saveworld @island

Hope this can maybe inspire you ...
Care, with this config I did not use Automanigemods, also if a mod updates, and the check has just been done, player sometimes had to wait 55 minutes ... but hey I did not have to do anything manually and never had to worry about server load even on a small config.

PS this was running on XEON 4 core processor (8Threads) with 16GB ram and 32GB Dedicated SSD swap

Greetings

**Comment by SinisterSole** [comment]
For the sleep timer you could call on a script from cron that has sleep in it like so:
#!/bin/bash
# Ark manager restart
#date +%d-%m-%y/%H:%M:%S
arkmanager restart --warn --saveworld --backup @island
sleep 5m
arkmanager restart --warn --saveworld --backup @center
sleep 5m
arkmanager restart --warn --saveworld --backup @scorched
#date +%d-%m-%y/%H:%M:%S

**Comment by ryan1161** [comment]
Found out what it was I know my server has enough cores cause it's  running in a hyper-v with 5 other game servers but found the issue was a bug with unbuntu 16.04 had a kernel panic and my server only got 7GB when it's supposed to pull 40GB. But this would be a cool addition if add to the instances cfg.
