### ISSUE TITLE
Updating Mods

### ISSUE THREAD

**Issue by KGM6911** [FezVrasta/ark-server-tools#915]
I am looking for a command line string to update mods and not the game itself.  I normally use arkmanager update --update-mods @instance.   I want a command to just check for mod updates and perform them.  Would the command arkmanager installmods @instance be acceptable for that?   Also, would arkmanager installmods modid @instance be ok to use to update a single mod?  If not, is there a way to disable the game update check and just run --update-mods?

**Comment by klightspeed** [comment]
You can use `arkmanager checkmodupdate @instance` to check for any mods that need updating.  That should return 0 if any mods need updating, so you can use it in an `if` statement.

**Comment by KGM6911** [comment]
So if I use that and it returns 0 is using the installmod and installmods commands ok to actually update the mods?  I want to update them without updating the ark server executables.

**Comment by klightspeed** [comment]
You will probably want to stop the server before updating the mods, and start it again after the mods are updated.

**Comment by KGM6911** [comment]
Yes, I intend to.  Is the installmods command ok to use to just update the mods?  It will just force a mod update even if same version is on the server already?
