### ISSUE TITLE
Request: list mod with name and id ?

### ISSUE THREAD

**Issue by MisterFoxi** [FezVrasta/ark-server-tools#919]
Is it possible to have a list of all the active mods with their names ? 
It should be very handy when you want to do some "spring mod cleaning" ;) 

Thanks

**Comment by klightspeed** [comment]
```
arkmanager list-mods @instance
```

**Comment by MisterFoxi** [comment]
Thanks.

**Comment by axi92** [comment]
Why isn't this command/parameter in the --help or documentation?

**Comment by klightspeed** [comment]
Sorry, I had forgotten to add it to the readme.  It has now been added to the readme.
