### ISSUE TITLE
Password hickup

### ISSUE THREAD

**Issue by tenten36** [FezVrasta/ark-server-tools#92]
Somethings fishy with the password feature...
Here is what I did:
Started server (Ubuntu 14.04) with password set in /etc/arkmamanger/arkmanager.cfg (btw, the tools name is ark-server-tools, but the folders read arkmanager...)

Well, I can't make up my mind, so I wanted the server to run password free. Changed the setting in  /etc/arkmamanger/arkmanager.cfg, still wanted a password to connect. I had to change the pw in /home/"user/arkfolder"/ShooterGame/Saved/Config/LinuxServer/GameUserSettings.ini

**Comment by Atriusftw** [comment]
Remove the password from GameUserSettings.ini and comment out the setting in arkmanager.cfg
