### ISSUE TITLE
Server not seeing updates

### ISSUE THREAD

**Issue by thekewee** [FezVrasta/ark-server-tools#922]
My servers didn't manually update to build 277.0 until I stopped them and ran: **arkmanager install**

I have a cron job running hourly running: **arkmanager update --warn --saveworld --backup @all**

Looking in the logs I see the hourly update reported the following before running **arkmanager install**
"Your server is already up to date ! The most recent version is 2495547."

After running **arkmanager install** the logs show
"Your server is already up to date ! The most recent version is 2501107."

Am I missing a command to update the current version in cache or something?

**Comment by thekewee** [comment]
I've just found in the arkserver.log several errors.

[S_API_FAIL] SteamAPI_Init() failed; SteamAPI_IsSteam_Running() failed.
Setting breakpad minidump AppID = 346110
Using binned
4.5.1-0+UE4  7038 3077 403 9
CtrlCHandler: Signal=2
arkmanager: line 1096: 10274 Aborted           (coredumped) ...

**Comment by klightspeed** [comment]
> My servers didn't manually update to build 277.0 until I stopped them and ran: arkmanager install

That suggests that `appinfo.vdf` is somewhere other than the usual `$HOME/Steam/appcache` - please look for `appinfo.vdf` in the game server's home directory and try setting `steamcmd_appinfocache` in `arkmanager.cfg` to the absolute path of that file.

```
[S_API_FAIL] SteamAPI_Init() failed; SteamAPI_IsSteam_Running() failed.
```

This is just the Steam API trying and failing to connect to the non-existent steam client.

```
CtrlCHandler: Signal=2
```

This is the interrupt signal send to the program when shutting down the game server.

```
arkmanager: line 1096: 10274 Aborted (coredumped) ...
```

The game server always aborts when exiting.

**Comment by thekewee** [comment]
@klightspeed thank you so much.  I'd installed in my profile so it was hiding in /.steam/ 

Hopefully that fixes it for the next update.. No more errors anyway!
