### ISSUE TITLE
exec not found with update 278

### ISSUE THREAD

**Issue by postpapa** [FezVrasta/ark-server-tools#924]
our servers updated right now to the ark version 278 and wont start anymore. it says exec not found 
![screenshot_1](https://user-images.githubusercontent.com/22226501/36066876-a9b3733e-0eb2-11e8-898b-1aacd2ea5779.png)

**Comment by cronner** [comment]
got the same tried:
arkserverroot="/home/steam/ARK"
arkserverexec="ShooterGame/Binaries/Linux/ShooterGameServer"

No luck :/

**Comment by postpapa** [comment]
is fixed with new update

**Comment by darkhath0r** [comment]
try "arkmanager install" will make the deal

**Comment by cronner** [comment]
also tried  "arkmanager install"  with no luck, new updated fixed the problem it seems
