### ISSUE TITLE
lsof: Command Not found 

### ISSUE THREAD

**Issue by Azuraxe** [FezVrasta/ark-server-tools#93]
Hey,
When I perform the command arkmanager start I am given this error:
/usr/local/bin/arkmanager: line 145: lsof: command not found

What does this mean? It is preventing me from starting the server!

Cheers

**Comment by Atriusftw** [comment]
Hello, Azuraxe.

You might have to install lsof manually.

If you're running a debian based distro: sudo apt-get install lsof

**Comment by klightspeed** [comment]
In some distributions, lsof is in /usr/sbin (see [http://www.linuxquestions.org/questions/linux-newbie-8/lsof-command-not-found-centos-906882/]).

On other distributions, it's not installed by default.

**Comment by Atriusftw** [comment]
I've created a section in the wiki for troubleshooting now. 

https://github.com/FezVrasta/ark-server-tools/wiki#lsof-command-not-found

**Comment by Azuraxe** [comment]
Awesome, I just did yum install lsof and it worked!
My ARKManager server is starting up fine without any errors but when I do arkmanager status, it says my server is offline.

I went and checked the arkserver.log in /var/log
and had this error:

[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110

Any ideas?

**Comment by klightspeed** [comment]
@Azuraxe that S_API FAIL "error" is normal for the current state of the game server, and can be ignored.

Does the server continue running, and come online after a few minutes?

If not:

* if it sticks at about 100% CPU usage, have you increased the open file limit?
* if it dies after a few minutes, do you have at least 4GB of RAM?

**Comment by Azuraxe** [comment]
@klightspeed The server will not turn on even after a few minutes.
- I'm running 1GB of RAM, could this be the issue lol, but the server won't even turn on in the first place
- CPU usage fine. Not even at 50%.

I'll double check the open file limit.

**Comment by klightspeed** [comment]
The server uses about 3.2GB of memory when running.

I haven't checked how much of that memory is live, but I would guess a significant portion would be live.  I doubt that 1GB of RAM, even with SSD swap, would cut it.

**Comment by Azuraxe** [comment]
Really? I only have myself on, just doing some testing..

Do I still need roughly 3GB?

**Comment by FezVrasta** [comment]
Yes
