### ISSUE TITLE
Server taking hours to appear online/ Query Port Problems

### ISSUE THREAD

**Issue by Thysse** [FezVrasta/ark-server-tools#936]
I set up an ark server which worked perfectly fine for a few days, but then it suddenly started to take hours to appear online. Arkmanager status prints me out everything is working just after starting the server, but from the startup of the server to it actually appearing in the server browser takes many hours. I searched alot but have no clue what could cause the problem. Thank you very much for any suggestion, as I am completely out of ideas. 
PS: I am quite new to both Linux and even more so the ark-server-tools

**Comment by klightspeed** [comment]
This is probably at least in part due to the sheer number of ARK servers registered with Steam.

If you try taking the arkservers.net link, replacing `http://arkservers.net/server/` with `steam://connect/`, then bring up the Run dialog (<kbd>⊞ Win</kbd>-<kbd>R</kbd>) on the computer you have the ARK client on, and run that `steam://connect/{ip}:{port}` link, are you able to connect?

**Comment by Thysse** [comment]
Unfortunately not

**Comment by Thysse** [comment]
I will try to give you as much information as possible, maybe this way you can find the problem. I am running the server on a dedicated linux server (Ubuntu Server) which is located at a friends house, because he has way better internet. The Server is directly conncted to the router over LAN  and is configured as exposed host. I configured the Linux firewall with ufw commands to block all internet traffic except the ports I opened. The server is controlled over SSH from my pc at home. Additionally to the ark server I have an apache server and a garrys mod server. The garrys mod server is not running at the same time the ark server is. I saved my ddns as a favourite server at steam. Usally when I started one of the servers they could be seen under steam favourite servers after a few minutes and ran perfectly fine. This changed approximately a week ago for both ark and garrys mod, without me changing anything ecxept the GameUserSettings.ini of ark. From then on it took many hours for them to show up under favourites. My SSH and Apache Server still run without any problems. Because of the long restart times I decided to run the ark server non stop. The ark server run without any problems for around 3 days. Today morning it didn't appear under favourites any more. I restarted both the linux server and the ark server and still wait for it to appear online. The Internet connection to the server definitely works, otherwise I wouldn't be able to connect over SSH or see my website.

**Comment by Johinator12** [comment]
I have the same problem. Someone help pls 👍

**Comment by Pyraniax** [comment]
Wow I had this problem for days and wasnt able to fix it :/

**Comment by klightspeed** [comment]
> This changed approximately a week ago for both ark and garrys mod, without me changing anything ecxept the GameUserSettings.ini of ark. From then on it took many hours for them to show up under favourites.

It sounds like the GameUserSettings.ini change is probably a red herring.  The taking hours for either ARK or Garry's Mod to show up sounds a bit like it's a Steam issue.

Do ARK and Garry's Mod share the same ports?

During the time between `arkmanager status` saying the server is online and the server appearing in the server browser:
* If you copy/paste the URL `http://api.steampowered.com/ISteamApps/GetServersAtAddress/v0001?addr=` and append the IP address of your server, does the returned text have a line `"appid": 346110`?  If so, then the server would seem to be properly registering itself.
* If you follow the arkservers.net link in the `arkmanager status` output, and add the server, does it properly show the name and player count of the server?  If so, that suggests the server can be queried.

**Comment by klightspeed** [comment]
Makes me wonder if your friend's ISP has blocked game servers?

**Comment by Thysse** [comment]
At least not from the beginning. I don't know whether they have any filters which activate after time

**Comment by klightspeed** [comment]
Yes, you should be able to use any unused port between 1024 and 49151.

**Comment by Thysse** [comment]
Same issue again. So I changed the query port and everything worked fine again for 2 days. When suddenly, we where playing on the server at the time, the query port refused to work again. We were 3 on the server playing, I just joined, but only a few minutes later, when a fourth friend tried to join, the server couldn't be found anymore, for all of us, although we were still playing on it. I shut down the server and changed the query port and the server could be found again. All the while my TTT Server on a different port, which is now set to run permanently, runs fine. Any ideas what could cause the problem and what I can do against it? It's not much fun switching and opening ports every two days.

**Comment by klightspeed** [comment]
This makes me wonder if either the router is blocking port mappings if packets are received from too many hosts (over-eager DDoS Protection?), or if the ISP is blocking ports that appear to them to be hosting servers (does the ISP forbid hosting a server on the connection?)

**Comment by Thysse** [comment]
Installed Server in another friends house, all problems are gone. So it must have been tied to either his router or ISP. Thanks a lot for all the help and to everyone working on this project. It's highly appreciated.
