### ISSUE TITLE
events

### ISSUE THREAD

**Issue by chalhoub37** [FezVrasta/ark-server-tools#937]
hello can i add the easter event to the server ? i used arkflag_ActiveEvents=Easter but it is not working i also added the forcerespawndinos so they will respawn but it is not working any guide to add the event or it is not possible to do this thanks

**Comment by Ryushoken** [comment]
Use arkopt_ActiveEvent="Easter" instead, you can check what arguments ShooterGame runs with using ps. 

Also, be sure to dino wipe your game for the dino population to repopulate with easter colors. You can use either "arkmanager rconcmd DestroyWildDinos @instance_name" or cheat DestroyWildDinos in-game.

Hope it helps.

**Comment by chalhoub37** [comment]
okay will try thank u man

**Comment by BakaOppai** [comment]
Two years later and this command still doesn't seem to work, the docs don't even mention it.  What is this shit anyway?

**Comment by klightspeed** [comment]
@BakaOppai are you saying that adding `arkopt_ActiveEvent=Easter` to your instance config doesn't add `-ActiveEvent=Easter` to the server command-line, or are you saying that adding `-ActiveEvent=Easter` to the server command-line doesn't activate the Easter event?

You can see what options the ARK server supports at <https://ark.gamepedia.com/Server_Configuration#Command_line_arguments>.  See also <https://github.com/FezVrasta/ark-server-tools#instance-config-files> for how to specify those options in the instance config.

Wherever the option is `-optionname` with no equal sign, use `arkflag_optionname=true`
Wherever the option is `-optionname=value`, use `arkopt_optionname=value`
Wherever the option is `?optionname` with no equal sign, use `ark_optionname=""`
Wherever the option is `?optionname=value`, use `ark_optionname=value`

**Comment by BakaOppai** [comment]
It adds the command line when I check with ps and all but the event isn't working on the maps

**Comment by BakaOppai** [comment]
Well after restarting again for no apparent reason it seems its working now, thx anyway.  Tho I have yet to see any easter colored dinos I have a lot of bunny dodos :P
