### ISSUE TITLE
checkmodupdate failing due to Steam API change

### ISSUE THREAD

**Issue by BigBadaboom** [FezVrasta/ark-server-tools#939]
checkmodupdate started failing for me today.  I was getting a line like the following for every mod:

    Mod 543394681 doesn't exist in the steam workshop

It appears the call to get the mod's time_updated value is failing.  It appears the JSOn returned from the relevant Steam API call has changed slightly.

I was able to fix it by changing the following line in the `getAvailModLastUpdated()` function (approx line 2132) from:

    local remupd="$(curl -s -d "itemcount=1&publishedfileids[0]=${modid}" http://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1 | sed -n 's|^[[:space:]]*"time_updated": \(.*\),|\1|p')"

to:

    local remupd="$(curl -s -d "itemcount=1&publishedfileids[0]=${modid}" http://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1 | sed -n 's|.*"time_updated":[[:space:]]*\([^,]*\),.*|\1|p')"

Hope this helps.

**Comment by klightspeed** [comment]
0b2d093 should fix this.
