### ISSUE TITLE
status command reporting server as offline due to API change

### ISSUE THREAD

**Issue by BigBadaboom** [FezVrasta/ark-server-tools#940]
The Steam API that arkmanager uses to check whether the server is online, is returning JSON of a slightly different format.

To fix, change the function `isTheServerOnline()` at approx line 859.

Change:

    if [[ "$serverresp" =~ "\"addr\": \""([^\"]*):([0-9]*)"\"" ]]; then
to:

    if [[ "$serverresp" =~ "\"addr\":\""([^\"]*):([0-9]*)"\"" ]]; then

ie. remove the space character after `addr\":`.

Hope this helps.

**Comment by klightspeed** [comment]
0b2d093 should fix this.
