### ISSUE TITLE
Server was updated while it was running

### ISSUE THREAD

**Issue by StevenB83** [FezVrasta/ark-server-tools#943]
Hi,
Love this tool and how stable it is, I however have issue with the following bit of code sending all my servers into an endless restart loop. I have tried multiple times doing clean install then just copy in world and config files.
This happens on three different machines for all instances. Sometimes tho it randomly decides that it's fine untill next ARK/mod update comes along.
Is there some way I can find out the cause and not having to comment out/remove the following lines each time I update arkmanager? :p
I know it has something to do with it finding arkmanagerpidfile to be older than arkupdatetimefile, which is false btw.
```
  if [[ -f "$arkserverroot/$arkmanagerpidfile" && "$arkserverroot/$arkmanagerpidfile" -ot "${arkserverroot}/${arkupdatetimefile}" ]]; then
    logprint "Server was updated while it was running"
    bgupdate=1
  fi
```
I use the following script every half hour by cron to update the instances.
```
#!/bin/bash

doUpdate() {
  if [ "$instance" != "allthemods" ]; then
    printf "Starting "${instance}" update - " >> "${HOME}/${instance}update.log"
    date >> "${HOME}/${instance}update.log"
    /usr/local/bin/arkmanager useconfig "$instance" update --update-mods --no-download --warn --saveworld --backup $@ >> "${HOME}/${instance}update.log"
    printf "Finished "${instance}" update - " >> "${HOME}/${instance}update.log"
    date >> "${HOME}/${instance}update.log"
  fi
}

/usr/local/bin/arkmanager useconfig allthemods update --update-mods --downloadonly $@

for instance in $(/usr/local/bin/arkmanager list-instances --brief); do
    sleep 10s
    doUpdate $@ &
done

wait
```

**Comment by klightspeed** [comment]
Do the instances share the same directory?

Are you overriding `arkmanagerpidfile` or `arkupdatetimefile`?

What are the modification times on `Saved/.ark-update.time` and `Saved/.arkmanager-*.pid`?

Perhaps we should use `$arkserverpidfile`?

**Comment by StevenB83** [comment]
Hi,
No none of the instances share directories, even have a seperate for allthemods just in case.
I don't override anything, only change I have in the arkmanager atm (latest version) is the lines I uncommented.

I see something weird is happening..
theisland instance has theese files:
```
-rw-rw-r-- 5 steam steam      6 april  6 06:57 .arkmanager-theisland.pid
-rw-rw-r-- 5 steam steam      6 april  6 06:57 .arkserver-theisland.pid
-rw-rw-r-- 5 steam steam      0 april  6 06:57 .ark-update.time
```
While ragnarok instance has theese files:
```
-rw-rw-r-- 1 steam steam         6 april  6 06:01 .arkmanager-ragnarok.pid
-rw-rw-r-- 5 steam steam         6 april  6 06:57 .arkmanager-theisland.pid
-rw-rw-r-- 1 steam steam         6 april  6 06:01 .arkserver-ragnarok.pid
-rw-rw-r-- 5 steam steam         6 april  6 06:57 .arkserver-theisland.pid
-rw-rw-r-- 5 steam steam         0 april  6 06:57 .ark-update.time
```

What could cause this? I'll take a look through all my configs, something is causing ragnarok to name the files theisland as well.

**Comment by klightspeed** [comment]
Are those `.*-theisland.pid` files present in `/home/steam/ARK-Staging/ShooterGameServer/Saved`?

**Comment by StevenB83** [comment]
They are indeed, perhaps exclude them from being copied from instances? :)

**Comment by klightspeed** [comment]
f02a1ad should remove any such pid files / lock files / etc. from the staging directory.

`.arkmanager-{instance}.pid` is written when the server monitor starts, and is removed when the server monitor has been stopped by arkmanager (whether by the `stop`, `restart` or `update` commands).
`.arkserver-{instance}.pid` is written immediately after the monitor starts the server, and is removed when the server has been stopped by arkmanager (whether by the `stop`, `restart` or `update` commands).
`.ark-update.time` is written after a successful update if a background update was not detected.

The fact that the timestamp on the PID files is old and was not removed after an update suggests that the monitor process was killed by something other than a `stop`, `restart` or `update` command.

**Comment by StevenB83** [comment]
Sweet, great work :)

However, the process has not been killed in any way to my knowledge, it's just not removing the pid files. I can do some more checking on that and report back after I get back from work.

**Comment by StevenB83** [comment]
Thank you again for the swift response and fix.
The pid files do get updated when doing updates, there should be nothing that kills the monitor process as far as I can tell.
After a `arkmanager update --update-mods --saveworld --backup --validate @aberration` the files look like this as they should. Doing a regular update afterwards yields `Your server is already up to date!` as expected.
Problem was most likely the files getting copied from the first updated instance as it has not happened after I added `rm "$arkStagingDir/${arkserverdir}/Saved/".[^.]*` to arkmanager script.
```
steam@GS01:~/Cluster1/Aberration/ShooterGame/Saved$ ll
-rw-rw-r-- 1 steam steam     6 april  7 08:49 .arkmanager-aberration.pid
-rw-rw-r-- 1 steam steam     6 april  7 08:49 .arkserver-aberration.pid
-rw-rw-r-- 4 steam steam     0 april  7 08:49 .ark-update.time
```
```
steam@GS01:~/Cluster1/Aberration/ShooterGame/Saved$ stat .*
  File: .arkmanager-aberration.pid
  Size: 6               Blocks: 8          IO Block: 4096   regular file
Device: 700h/1792d      Inode: 6553649     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1001/   steam)   Gid: ( 1001/   steam)
Access: 2018-04-07 08:49:08.596279958 +0200
Modify: 2018-04-07 08:49:08.596279958 +0200
Change: 2018-04-07 08:49:08.596279958 +0200
 Birth: -
  File: .arkserver-aberration.pid
  Size: 6               Blocks: 8          IO Block: 4096   regular file
Device: 700h/1792d      Inode: 6553733     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1001/   steam)   Gid: ( 1001/   steam)
Access: 2018-04-07 08:49:13.616192389 +0200
Modify: 2018-04-07 08:49:08.604279817 +0200
Change: 2018-04-07 08:49:08.604279817 +0200
 Birth: -
  File: .ark-update.time
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 700h/1792d      Inode: 6033725     Links: 4
Access: (0664/-rw-rw-r--)  Uid: ( 1001/   steam)   Gid: ( 1001/   steam)
Access: 2018-04-07 08:49:08.588280097 +0200
Modify: 2018-04-07 08:49:08.588280097 +0200
Change: 2018-04-07 08:49:08.588280097 +0200
 Birth: -
  File: .autorestart
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 700h/1792d      Inode: 6553765     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1001/   steam)   Gid: ( 1001/   steam)
Access: 2018-04-07 08:49:13.668191483 +0200
Modify: 2018-04-07 08:49:13.668191483 +0200
Change: 2018-04-07 08:49:13.668191483 +0200
 Birth: -
```

**Comment by StevenB83** [comment]
Nevermind, it started doing it again -.- going to look through all the files and try to figure out what is happening this time.
