### ISSUE TITLE
Something's Seriously wrong with mod updates ?

### ISSUE THREAD

**Issue by CaspyBXL** [FezVrasta/ark-server-tools#944]
Hello,

So since 2 days the 3 machines running 3 different clusters are not updating mods anymore ...

We are talking about 3 different machines on different linuxes (Debian, CentOS, Ubuntu).
Also on 3 different Hosters (Online.net / OVH / Own Home Server ).
They all, and i mean all, have the same symptoms ...

arkmanager update --update-mods --saveworld --backup @XXX does not do it anymore ...
I have tried several things .... activating staging or turn it off, trying manual commands not using crontab
but they all do the same ... the servers warns, updates, logs are there saying its updated ... then reboots , and guess what server is ok, but mods did not change anything ... 

so okay ... lets try this out : 
Updated SteamCMD
Updated Arktools

Also tried using --force or --validate ... did not change ...
So did a more drastic aproach ... every hour using

for every mod : 
arkmanager reinstallmod XXXXXX @server
force to redownload the mod, and this does work ...
I don't get it, steam logs show nothing wrong ... arkmanager logs show nothing wrong ...

Could you please advise ?
Or tell me what you need to check this out ?

**Comment by klightspeed** [comment]
What version?  v1.6.40 fixes a problem that could cause this.

**Comment by CaspyBXL** [comment]
Version: 1.6
Channel: master
Commit: 95ac5a6
Release Tag: v1.6.38
Blob SHA: a0df5a2411c9ca96463257e03f79708a4df9cda7

I will try to update to 1.6.40

**Comment by StevenB83** [comment]
I have 1.6.40 installed, but only the first instance get updated. The rest "update", but not really. Will try to debug a little here.

**Comment by CaspyBXL** [comment]
I'm confirming 1.6.4 solved my problem Thank you verry much !!!!
@klightspeed
