### ISSUE TITLE
extend systemd stop with timeout for player ?

### ISSUE THREAD

**Issue by kubilaypeksen** [FezVrasta/ark-server-tools#948]
It's possible to intercept the "shutdown" command with timeout ?

arkmanager.service
```
ExecStop=/usr/libexec/arkmanager/arkmanager.init stop
TimeoutStopSec=180
```

arkmanager.init
```
stop)
      systemctl stop arkmanager@${service} --warn or 180
;;
```

https://www.freedesktop.org/software/systemd/man/systemd.service.html#TimeoutStopSec=

**Comment by klightspeed** [comment]
Are you wanting to warn players that the server is shutting down, or put a limit on how long it takes to shut down?

If you're wanting to put a limit on how long a shutdown takes, then `TimeoutStopSec` belongs in `arkmanager@.service`

If you're wanting to warn players that the server is restarting, then you would want to use `arkmanager stop @instance --warn`

**Comment by kubilaypeksen** [comment]
I want to warn players, but not with `arkmanager stop @instance --warn`. Thats not the problem, i allready read the manuel ^^

But i think this is a good idea for all, when the system shutdown then arkmanager resolv that with a timeout and warning all players.

this is just an idea, not a issues.

(sorry for my english, i am trying)

**Comment by kubilaypeksen** [comment]
ow sorry, i see the `arkmanager@.service` is the new and `arkmanager.service` old ?

**Comment by kubilaypeksen** [comment]
thanks, i try to implement my idea.

**Comment by kubilaypeksen** [comment]
okay, this idea was difficult. I have too little bash script experience.
I prefer to stay at the frontend first ^^
