### ISSUE TITLE
Start  Commandline seems Broken ?

### ISSUE THREAD

**Issue by MuhKuhx** [FezVrasta/ark-server-tools#952]
Well 
i've got 4 Ark Instances, Island/Ragnarok/Scorched/Aberration.. and they are Clustered together
So the Instance.cfg from all of them are literally the same but not the Ports & Saves & Directorys.
So..
my Problem is 
ark_PreventDownloadSurvivors="False"
ark_PreventDownloadItems="False"
ark_PreventDownloadDinos="False"
ark_PreventUploadSurvivors="False"
ark_PreventUploadItems="False"
ark_PreventUploadDinos="False"
ark_noTributeDownloads="False"

Thats in all .cfg's  but Only the map Ragnarok has  the ?PreventDownloadSurvivors=false?Prevent... 
and the others got "??PreventDownloadSurvivors=false??Prevent.." the "??" is Double and i can't get that Fixed...

I apologize for my English but idk why the Other server got those Problems with "??" and the Ragnarok isntance not.. (Even tried to delete the cfg. and copied the ragnarok.cfg edited Ports & Saves etc. but nope doesn't work)

**Comment by dahlskebank** [comment]
No idea why you are getting double question marks, but you can actually leave those in GameUserSettings.ini, there's no need for those settings to be in command-line. Most settings work in either GUS or Game.ini.

**Comment by MuhKuhx** [comment]
Well i Fixed it a few Days ago, i created a new file via ftp called island.cfg for example and that was the Issue i had to copy the main.cfg via Console command cp main.cfg island.cfg <- That helped me get rid of the double question marks
