### ISSUE TITLE
forcenetthreading Option useful for Ark ? 

### ISSUE THREAD

**Issue by CaspyBXL** [FezVrasta/ark-server-tools#959]
Hey @klightspeed ,

arkflag_forcenetthreading=true

Add or don't add in the settings ?

What is ur understanding of this option and how does this impact Linux Networking ?

On windows it made some connections faster but for some people slower ... so not sure how linux adapts to this ??

I have a three way NIC running, will this adapt to this ?

I have 18 Arks running, 9 Three way Clusters, so not sure if this is a good or bad idea !

3 x 1 Gbps (Per cluster 500 Mbps reserved)
+ 1 Failover Backup Line of 1 Gbps in case network goes down on 3 way provider

Thanks for helping me out with some information if you have this.
I'll be glad to post my results after testing, but first wanted ur opinion on this.

**Comment by klightspeed** [comment]
It looks like it depends on what your gameserver to CPU core ratio is.  Network multithreading means running the network code on multiple CPU threads.

`-nonetthreading` was apparently added in https://ark.gamepedia.com/271.15 to try to improve performance of `bRawSockets` mode.
https://ark.gamepedia.com/271.17 defaulted to disabling network threading in `bRawSockets` mode, and the `-forcenetthreading` option was added.

I'm guessing if your gameserver to CPU core ratio is > 1:2 or 1:1, then it's best to turn off network multithreading.

**Comment by CaspyBXL** [comment]
Processeur Intel® Xeon® Platinum 8160 x 2

Sockets 4
Cores per socket 24
Cores Total 96

VmWare ESX 6.0 Infrastructure
Running 9 Linux Debian 8.5 Servers
Per Debian/Cluster 6 Cores
Total of 54 Cores
2 Cores per Instance

42 Cores left for teamspeak servers and NextCloud Servers and SVN servers.
256 GB of High End Server Ram ECC

Would you recommend this option ?

**Comment by klightspeed** [comment]
I don't know if network multithreading will help or not.  When it was introduced in <https://ark.gamepedia.com/243.0>, it supposedly improved CPU performance by 10%.

In <https://ark.gamepedia.com/271.0>, they eliminated the server stalls with `bRawSockets`, which it appears increased its single-threaded performance enough to reduce or negate the performance benefit that network multi-threading previously had.

If you're using e1000 or e1000e virtual NICs, switching to vmxnet may provide a performance improvement (though with SystemD the change of NIC will change the "predictable" name of the interface in the VMs, likely to ens256 [depending on which "slot" ESXi puts the NIC into]).

**Comment by CaspyBXL** [comment]
Many Thanks Klightspeed ! will for sure test this out, but I think this won't change that much on the load, when servers are runnig the cpu's never go above 70%. Even when server highly populated and many people online. So this option is not needed i guess.
