### ISSUE TITLE
Server not listed?

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#96]
I was wondering why I can't find my server in the list...

The name is:
```
! [EU] ARK Ascension [PvPvE][NoLag] - (v183.2)
```

and I can correctly fetch informations querying the Steam Source Queries...

So I think everything should be good, right?

**Comment by Atriusftw** [comment]
What is the output of this?

```cat home/steam/ARK/ShooterGame/Saved/Logs/ShooterGame.log```

**Comment by klightspeed** [comment]
@FezVrasta Is the server behind the same internet gateway as your client?

If so, does your internet gateway support NAT loopback?

**Comment by FezVrasta** [comment]
The server is in a server farm and my client is at home

**Comment by FezVrasta** [comment]
I have tried changing the name (no exclamation mark) but me (and some users) are not able to find it.. On the other hand, some of my friends can find it :/

**Comment by matthewford** [comment]
I had to just manually add the server via steam favourite menu to find mine

**Comment by klightspeed** [comment]
Sounds like this is a ARK server bug - perhaps only listing servers with less than a particular ping.

**Comment by FezVrasta** [comment]
My server has 30 of ping when I'm inside it. but when I check the ping from steam it says 180 (probably because they ping from US while I ping from Italy)

**Comment by Q11x** [comment]
From my experience, it's a  bit random if people can find it or not. 
What I and my players ended up doing, was that I found the server the first time. Then added it to favorites in the game and connected to it. Then others could join me via steam (Using the friend list and "Join game") and thereafter they've always been able to find it again (by searching for it and using favorites). 
They're friends ended up doing the same to connect as well.

What I really miss, is a way to access the games console without entering a server first and manually connect to an IP address. That would have been a great temporary solution for testing servers and connecting for the first time.

**Comment by klightspeed** [comment]
30ms of ping sounds like the local network - it's the same ping my server (which is on my LAN) shows.

The client can take a while to enumerate servers not in the local region.

Also, make sure your server is up-to-date.  The ARK client will refuse to list servers that are on a different major version.

**Comment by FezVrasta** [comment]
@klightspeed the server is located in France, I am in Italy. So I just think that my server has a good connection :D

**Comment by mauzao9** [comment]
I have the Ark running on a Dedicated Server, by no means i can find it on both Steam Servers or In-game. I can only finding it adding the IP Manually then get it as favorite and join from there. 

Is this problems with the server software or something is wrong?

**Comment by imassingham** [comment]
Are you running on Ubuntu? there's an  issue with the ulimit increase in the new version on my system. I had to manually modify sysctl.conf and the other files as per the last version. This fixed an issue with my server not appearing in the server listings and in 'my survivors'.

/usr/local/bin/arkmanager: line 232: ulimit: open files: cannot modify limit: Operation not permitted

**Comment by mauzao9** [comment]
Yes, how can i confirm if that's the issue and fix?
