### ISSUE TITLE
Can't remove pw

### ISSUE THREAD

**Issue by slitterell** [FezVrasta/ark-server-tools#964]
I made a whitelist and configured the server for it. I tested it. It works great. The problem I'd now I can't get rid of the PW protection. I did printconfig and there is no config file that has the PW setting. Restarted and updated the server multiple times. It accepts other changes, just not this one.

**Comment by klightspeed** [comment]
Please check if GameUserSettings.ini still specifies a password.

**Comment by slitterell** [comment]
I quickly thought, "of course, duh!" And I went to verify before returning with an answer and there it is. I feel so sheepish and noobish. :( Thanks! Such an easy answer :)

**Comment by klightspeed** [comment]
It can catch you out - the game server modifies its config when it starts and stores any options specified on its command-line, meaning such options can stick around after they have been removed from the command-line.
