### ISSUE TITLE
Glances shows start commands run every few seconds, is this typical?

### ISSUE THREAD

**Issue by JamesDonaldChilds** [FezVrasta/ark-server-tools#972]
I don't know if this is an actual issue or not, but I was watching my process in glances and I noticed that every couple of seconds, the start command I used runs once for each server. So once every few seconds it shows 5 processes with the start @all command run for just a second or less. Seems like a waste of resources unless its doing this for a reason.

**Comment by klightspeed** [comment]
arkmanager is a bash script, and as such doesn't have threading or async processing, and so needs to call other programs to get stuff done.  While it is monitoring a server, it will sleep for 5 seconds (`sleep 5`), then check if the server is listening (using a perl script).  The apparent "start" command might be either from the time between fork and exec when executing an external command, or from a subshell.

**Comment by JamesDonaldChilds** [comment]
Thank you, that's basically what I thought was happening, I just assumed it would be done under another PID than the start command.

**Comment by klightspeed** [comment]
Subshells inherit the commandline from their parent
