### ISSUE TITLE
Backup feature?

### ISSUE THREAD

**Issue by FezVrasta** [FezVrasta/ark-server-tools#98]
We have not a backup feature.. we should add it.

**Comment by klightspeed** [comment]
i.e. copy the last modified .ark file, all of the .arkprofile and .arktribe files, and the GameUserSettings.ini, to a timestamped backup directory?

**Comment by FezVrasta** [comment]
Yes exactly. But I'm not sure if we need to stop the server to backup the files or what..

**Comment by klightspeed** [comment]
@FezVrasta I don't think so - as long as the server uses the write-and-rename method of replacing the files, a copy should grab either the old state or the new state, and not an invalid intermediate state.

**Comment by FezVrasta** [comment]
Ok so we may plan this feature for 1.2

I've not a lot of time right now, if someone wants to work on it please let me know. Otherwise I'll do it by myself asap.
