### ISSUE TITLE
constant reboots with update --update-mods

### ISSUE THREAD

**Issue by TruWrecks** [FezVrasta/ark-server-tools#981]
I have have 4 servers with 2 sets of different mods. I have a crontab scheduled to check for mod updates every 15 minutes. The update script I am using is being called correctly. The servers are updating when needed but keep rebooting even though there is no update ready.

Ark Update Script:
arkmanager update --validate --update-mods --warn @Server1 @Server2 @Server3 @Server4

I have steamdataroot=/home/steam/steam in arkmanager.cfg
I have tried /home/steam, ~$HOME/.steam, /home/steam/.steam.
The directories exist but nothing is being written. Currently my servers are installed to the /home/steam folder. I can move them into a common folder if that helps. Not sure what else to try.

Thanks for an awesome tool. it has improved my life 200 fold.

**Comment by Hulth** [comment]
--validate will force a re-download of the server and mod-files each time your script is run, you should remove it from any script and only use it when you actually need to validate game or re-download mod files (have had to do it a couple of times when Classic Flyers update didn't take)

**Comment by TruWrecks** [comment]
Thank you!

I knew it had to be something I'm doing wrong. It appears to be working now!
