### ISSUE TITLE
Restart Script?

### ISSUE THREAD

**Issue by paperrain** [FezVrasta/ark-server-tools#987]
Good afternoon, is there a script that restarts all servers at the same time? Instead of recursively as it already does. Because it takes too long to reboot all servers and I've searched around here, but I can't find anything.

Thanks!

**Comment by klightspeed** [comment]
Something like:
```
for i in $(arkmanager list-instances --brief); do
    arkmanager restart @$i &
done
wait
```

**Comment by paperrain** [comment]
Thanks @klightspeed!
