### ISSUE TITLE
Cluster not working

### ISSUE THREAD

**Issue by GladiusG** [FezVrasta/ark-server-tools#991]
Hey, so I've tried creating a cluster server but it refuses to let me transfer characters. I have looked through a lot of people having the same issue but mine has not been resolved.
My cluster ID is set correctly and so is the clusterdiroverride. The servers start but simply do not let me transfer, in fact the servers can't even see eachother. I've tried different ports, installing a different os, reinstalled the os and done everything from scratch again to no avail.
I have a VPS and contacted my support as someone mentioned NAT Loopback and they came back to me with:
_

> our datacenter administrators have verified, that NAT loopback is not available on our services. Since VPS services receive external IP addresses and there are no internal (private) network that could be connected to. In this case you should try to configure the cluster to contact the server via public IP address without the loopback.

_

I'm not sure if I am doing it right but I have tried doing that. I know the folders and all is set correctly and how it should be
The serverroots are "/home/steam/ARK" and "/home/steam/ARK2" with the clusterDirOverride being "/home/steam/"

Any idea on how I could do what they said without the loopback?
It's just getting frustrating at this point

EDIT:
I got it fixed somehow

**Comment by CorsairF4U** [comment]
I'm having the same issue how did you get it fixed?
