### ISSUE TITLE
Discord webhook not functioning

### ISSUE THREAD

**Issue by kzarius** [FezVrasta/ark-server-tools#994]
Trying to troubleshoot a problem with my arkmanager not reporting to Discord at all. I've set up a webhook on discord in a test server, copied its webhook URL into the main arkmanager.cfg like so:

discordWebhookUrl="webhook url in here, I promise"
notifyTemplate="[{instance}] {msg}"
notifyMsgShuttingDown="Shutdown."
notifyMsgStarting="Starting up."
notifyMsgServerUp="Awake."
notifyMsgStoppedListening="-"
notifyMsgServerTerminated="Terminated"

Restarting/stopping+starting a server does not pass any messages. Using notify <msg> also does not send any messages.

**Comment by klightspeed** [comment]
Settings are case sensitive - the webhook URL setting is `discordWebhookURL`

**Comment by kzarius** [comment]
Of course. I should have seen that. Working fine now.
