### ISSUE TITLE
Session timeout when try to connect server.

### ISSUE THREAD

**Issue by kamuran21** [FezVrasta/ark-server-tools#995]
I have created a drobled to create an ark server. Server is running and listening. Also I can see it, on arkservers.net. But, I can join the server and change GameUserSettings.ini file. 
I follow the commands in this page: https://steamcommunity.com/sharedfiles/filedetails/?id=474456344

Is there another guide for create an ark server successfuly?

**Comment by kamuran21** [comment]
Also my server listed here :https://arkservers.net/server/138.68.79.228:27015

**Comment by TruWrecks** [comment]
The server code is not up to date. It should read v288.113 as of today. Try using "arkmanager update --validate @instancename" and put your instance file name after the 2 symbol.

**Comment by kamuran21** [comment]
Hi @TruWrecks , I re-install all server. and update just now. But still get the shame issue. 
Can you try to join server?
![image](https://user-images.githubusercontent.com/12832351/50189984-8e2ee280-0338-11e9-90f6-70c312b8f0ef.png)
https://arkservers.net/server/138.68.79.228:27015

**Comment by kamuran21** [comment]
Problem resolved. Ubuntu version causes the problem. I downgraded it from 18.x.x to 14.x.x  then arkmanager worked like a charm.
