### ISSUE TITLE
Update problem with ark

### ISSUE THREAD

**Issue by DerGartho** [FezVrasta/ark-server-tools#997]
Arkmanager / Server update problem
Can anyone help with arkmanager.
My problem arkmanager take only the old update.

Current version: 3378066
Available version: 3407100
Your server needs to be restarted in order to receive the latest update.
Run "arkmanager update" to do so

Checking for update; PID: 12095
The server has been stopped
Performing ARK update ... Update to 3378066 complete
The server is now running, and should be up within 10 minutes

Only update to 3378066 and not to 3407100

**Comment by TruWrecks** [comment]
Use "arkmanager update --validate @instancename" to force the upgrade.

**Comment by klightspeed** [comment]
You can use the `--verbose` command-line option to show the output of `steamcmd`

**Comment by cosmicc** [comment]
there is an issue here.  I have a 5 server cluster all configured the same.  yet checkupdate has different results for each server, 2 servers show the actual latest current ark version.  2 server show the latest version available from steam is one version back.  1 server shows 2 versions back.  I understand a upgade --force will upgrade it, but thats not the issue here.  I use checkupdate in other scripts, so its pretty important it works consistently.  --verbose hows now new information.  how would these all be querying different versions from steam?

**Comment by DerGartho** [comment]
Hello, the same problem

$ arkmanager update --validate @main
Running command 'update' for instance 'main'
Checking for update; PID: 2863
The server has been stopped
Performing ARK update ... Update to 3378066 complete
The server is now running, and should be up within 10 minutes
$ arkmanager update --verbose
Running command 'update' for instance 'main'
Checking for update; PID: 4231
The server has been stopped
Performing ARK updateExecuting /home/steam/steamcmd/steamcmd.sh +@NoPromptForPas                         sword 1 +login anonymous +force_install_dir /home/steam/ARK +app_update 376030 +                         quit
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
"@NoPromptForPassword" = "1"

Connecting anonymously to Steam Public...Logged in OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '376030' state is 0x606 after update job.
Update to 3378066 complete
The server is starting...
The server is now running, and should be up within 10 minutes

Not install the new version only the old

**Comment by klightspeed** [comment]
Does `/home/steam/Steam/logs/content_log.txt` contain any errors near the end?

**Comment by klightspeed** [comment]
@cosmicc If `checkupdate` is returning the wrong version, then it is likely that `steamcmd_appinfocache` is set to the wrong directory, and so arkmanager is unable to clear the steamcmd appinfo cache.

**Comment by DerGartho** [comment]
The problem
 /mods/ragnarok 

[2018-12-19 08:45:19] AppID 376030 update canceled : File commit failed: failed to move deleted file ".../ShooterGame/Content/Mods/Ragnarok/Ragnarok.umap" (Disk write failure) ".../ShooterGame/Content/Mods/Ragnarok/Ragnarok.umap"
[2018-12-19 08:45:19] AppID 376030 update changed : Running,Committing,Stopping,


i have delete ragnarok and new install

now it works

thx all for the help
