### ISSUE TITLE
arkservers.net broken DB ?

### ISSUE THREAD

**Issue by CaspyBXL** [FezVrasta/ark-server-tools#998]
Hello @klightspeed 

Am I missing something ?
On my Fifth Server that I set up i'm getting something odd here ...
![4klightspeed](https://user-images.githubusercontent.com/20288570/50256723-ed076100-03f7-11e9-8722-36387fc2b0bf.PNG)

People have no issue joining the server and all runs well ... just can't seem to add them on arkservers.net

Have you ever encountered this ? I know its not typical Arkmanager Support but i'm not seeing it ...
HELP ?

Greetings,

**Comment by klightspeed** [comment]
I have no issue querying that server:
```
$ ./query.pl 27015 149.202.65.57
Server Name: FR-RP-Jurassic Arkworld - (v288.114)
Players: 0 / 40
```

I'm guessing either it's an arkservers.net issue or a firewall is blocking the arkservers.net poller.

**Comment by CaspyBXL** [comment]
Well that's the thing all query ports game ports and RCON ports are opened up to public.
As usual ...

**Comment by CaspyBXL** [comment]
Even tried to disable the firewall for a moment. Same ... just won't work ... so I guess Arkservers.net
